### ISSUE TITLE
Congratulations Everyone!

### ISSUE THREAD

**Issue by krischer** [obspy/obspy#1000]
Issue 1000 :-)

![15467456315_977b4fa0a0_k](https://cloud.githubusercontent.com/assets/800487/6838312/8106c13c-d357-11e4-8326-15138a54fb91.jpg)

**Comment by QuLogic** [comment]
:tada: :cake:

**Comment by megies** [comment]
:100:0

**Comment by mbyt** [comment]
`7700 commits / 1000 tickets = 7.7 commits / ticket` !?!

**Comment by trichter** [comment]
Congrats!   ![image](https://cloud.githubusercontent.com/assets/2046150/6858338/f76a4766-d40d-11e4-9f15-658a3d35ad81.png), blow 10x for releases, 1000x for issues

**Comment by QuLogic** [comment]
On a related note, [Travis build 3000](https://travis-ci.org/obspy/obspy/builds/56018922)!

**Comment by ThomasLecocq** [comment]
... and some people developing code is not science ... 

!!!! CONGRATULATIONS !!!!

**Comment by petrrr** [comment]
Already closed?
I actually liked this ticket ;-)

**Comment by ThomasLecocq** [comment]
I don't care,I can still spam it :)

and, to be honest, it's probably one of the most interesting tickets, ever :)

**Comment by megies** [comment]
> it's probably one of the most interesting tickets, ever :)

Only for a human brain. Them github servers must think "what's all the fuss about issue number eight?"
