### ISSUE TITLE
Installation on OS X using Homebrew, Installing the latest master

### ISSUE THREAD

**Issue by bonaime** [obspy/obspy#1006]
After
```
$git clone https://github.com/obspy/obspy.git
$ cd obspy
```
The normal installation is working 
```$ pip install .         # for a normal installation```
but the editable is not
```$ pip install -e -v .   # for an editable installation```
```log
 pip install -e -v .
-v should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+
```
but
```
pip install -v -e . 
```
is working

```log
pip -V
pip 6.0.6 from /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg (python 2.7)
```

**Comment by krischer** [comment]
I was not aware that the order matters. I just fixed it in the wiki.

**Comment by megies** [comment]
@bonaime, it's a wiki.. could've just fixed it right away. :-)
