### ISSUE TITLE
World basemap is flipped east-west

### ISSUE THREAD

**Issue by claudiodsf** [obspy/obspy#1011]
See for instance [this](http://docs.obspy.org/packages/obspy.fdsn.html#module-obspy.fdsn) doc page.
I checked on my local `0.10.1` installation, and I have the same problem.

[Current documentation for master](http://docs.obspy.org/master/packages/obspy.clients.fdsn.html) has a mixed behavior, with one correct basemap and the other one flipped.

**Comment by QuLogic** [comment]
This has already been fixed. See eda1c5daa7c2b68ded78f0466d1770a59fa1eed6.

**Comment by claudiodsf** [comment]
Ok, but in the current documentation from master (http://docs.obspy.org/master/packages/obspy.clients.fdsn.html), the last image is still flipped.

**Comment by QuLogic** [comment]
Great, I'll just reduce the precision some more, then...

**Comment by krischer** [comment]
For the mollweide and the orthographic projections: why not just round to two digits? Nobody will be able to tell the difference for these projections. also the local one is probably still more than good enough with 5-6 digits.

**Comment by QuLogic** [comment]
I think it might be due to something like [this check](https://github.com/matplotlib/basemap/blob/ee6a2f7f95b7a5eff022fcbb2800d7c50b8c97b5/lib/mpl_toolkits/basemap/__init__.py#L4787), so 4 might be the best we get.

**Comment by krischer** [comment]
Thats only 10 meters; more accurate then needed IMHO so I guess that's fine.

**Comment by megies** [comment]
:+1:
