### ISSUE TITLE
Event/Catalogue formats I/O

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#1019]
this happened in the discussion about the reorganization, but I move them here so we can keep track:

_Tobias said:_
Just in case you are working on file I/O: there is some stuff in [here](https://github.com/megies/obspyck/blob/quakeml_b/obspyck.py):
- for focmec: https://github.com/megies/obspyck/blob/quakeml_b/obspyck.py#L1682-L1740
- for hypo71: https://github.com/megies/obspyck/blob/quakeml_b/obspyck.py#L1881-L1889
- for nlloc: https://github.com/megies/obspyck/blob/quakeml_b/obspyck.py#L1881-L1889, https://github.com/megies/obspyck/blob/quakeml_b/obspyck.py#L1943-L2242
- for hyp2000: https://github.com/megies/obspyck/blob/quakeml_b/obspyck.py#L2246-L2395
- for HyopDD there's most likely something in there: https://github.com/krischer/hypoDDpy/blob/master/hypoddpy/hypodd_relocator.py

I just didnt get to extracting all that properly to obspy (and it needs some adapting and tests of course)..

I'm now busy with some of these things, so, where should I start ? 
- work on current `master` (seems obvious)
- create `obspy.io.hypoinverse` based on `obspy.io.cnv` (simplest I've found)
- declare it as an available format for event.write , like in here https://github.com/obspy/obspy/blob/master/setup.py#L251 ?
- regarding this: https://github.com/megies/obspyck/blob/quakeml_b/obspyck.py#L1881-L1889. If one wants both catalogue and station files to be created, I assume I have to declare entry points to `io.hypoinverse`  for `events` and for `inventory` ?

**Comment by megies** [comment]
Sounds about right.. :+1:
If it's only for write support your best template is probably `obspy.io.cnv` / #905 (CNV output as input for VELEST).
(Of course no need for a LICENSE file and it's now under `obspy.io` as you mentioned already)

**Comment by ThomasLecocq** [comment]
@megies : i've updated above. About the "station" file that should go with the CNV for velest, e.g. ?

**Comment by megies** [comment]
I think nobody bothered to add a plugin for VELEST station file output yet because it's pretty quick to do it by hand and it only has to be done once. But in principle it would of course be nice to have more output plugins for `Inventory` objects to generate input station files for various routines out there.

**Comment by ThomasLecocq** [comment]
I'm thinking of a generic `Inventory` output function that would accept keyword-style string, using `str.format`
```{network} {code} {longitude} {latitude}```

but yeah, maybe overkill, in theory only useful once (for me...)

**Comment by QuLogic** [comment]
Another useful thing is input/output of those `CMTSOLUTION` files used by specfem, which I might get to soon-ish.

**Comment by krischer** [comment]
@QuLogic I actually have written code to/from `CMTSOLUTIONS` a couple of times already. I can add them. Should we maybe have a simple `obspy.io.basic_event_format` module that collects these really simple formats?

**Comment by QuLogic** [comment]
@krischer Yea, we should definitely add it; I get asked about it a couple times.

**Comment by ThomasLecocq** [comment]
@krischer : good idea but high risk of getting things messy...

**Comment by megies** [comment]
all but the hypoinverse stuff is in obspy these days i believe, closing
