### ISSUE TITLE
Seisan spikes

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#1020]
following this correction (https://github.com/obspy/obspy/pull/971), I'm reprocessing some SEISAN data, and I am wondering if these "spikes":
![kwui1](https://cloud.githubusercontent.com/assets/916937/7201047/8251d672-e503-11e4-99aa-d0c74a418c02.png)
zoom:
![kwui2](https://cloud.githubusercontent.com/assets/916937/7201050/87712432-e503-11e4-8749-7a21ab16b4c6.png)
are real data of if it's some conversion bug? I don't have any other SEISAN-capable routines to compare the outputs...

it pretty much looks like a delta convolved with an instrument response... so could be "in the data"... 

file: http://homepage.oma.be/lecocq/2012-01-20-0350-00S.MAN___010

**Comment by CTrabant** [comment]
> are real data of if it's some conversion bug? I don't have any other SEISAN-capable routines to compare the outputs...
> 

You could use the seisan2mseed converter here:
https://seiscode.iris.washington.edu/projects/seisan2mseed <https://seiscode.iris.washington.edu/projects/seisan2mseed>

and then compare the miniSEED to what you got.  Of course there are no guarantees that there are no bugs in that code, but hopefully not the same bug.

Chad

**Comment by QuLogic** [comment]
Are you sure that file is the same as the one you plotted? It doesn't even seem to be the same date, and I can see maybe only one spike that seems odd.

**Comment by ThomasLecocq** [comment]
@CTrabant yeah... they look the same... so I guess it's in the data... most probably a delta spike + some instrument response... grr...

![seisanmseed](https://cloud.githubusercontent.com/assets/916937/7292429/f9c5951c-e99b-11e4-8a52-9b70a263ee7f.jpg)
left = obspy.io.seisan | right = seisan2mseed
