### ISSUE TITLE
Reading Pickled files

### ISSUE THREAD

**Issue by sannecottaar** [obspy/obspy#1043]
Hi all,

I'm running into the following issue, although I'm still not sure how much this is just a problem on my end, or a compatibility problem between pickle and the latest future version which lies outside of obspy. 

If I use obspy 0.10.1 with future 0.14.3, and try to read some of my data in pickled format, I get:
  File "/usr/lib/python2.7/pickle.py", line 1124, in find_class
    __import__(module)
ImportError: No module named backports.newstr

The only way around it, is to go to an older version of future, and then that only seems compatible with obspy 0.9.2. Potentially I'll have to use these old versions to read my data and write them out to a different format, so I can read them with the newer versions. 

Thanks for any help on this,
Sanne

**Comment by krischer** [comment]
Hi Sanne,

pickling can really only be used if no module of your installation changes and thus is only useful for temporary storage on a fixed installation. As soon as you update any module you might not be able to open old pickled files anymore.


>  Potentially I'll have to use these old versions to read my data and write  
> them out to a different format, so I can read them with the newer versions.

Pretty much. Now there are ways around that but they are way harder so you best go down that route.

Cheers!

Lion

**Comment by sannecottaar** [comment]
I will do that then and switch format too. 
Thank you!
Cheers,
Sanne
