### ISSUE TITLE
Redirected FDSN client URLs get double-encoding

### ISSUE THREAD

**Issue by QuLogic** [obspy/obspy#1048]
This code will fail with a 400 Bad Request:
```
usgs = Client('USGS', debug=True)

minmag_glob = 6
tstart = UTCDateTime('2000-01-01T00:00:00')
glob_ev = usgs.get_events(starttime=tstart, minmagnitude=minmag_glob)
```
The URL is `http://comcat.cr.usgs.gov/fdsnws/event/1/query?minmagnitude=6.0&starttime=2000-01-01T00%3A00%3A00.000000`. If you use the default client (IRIS), then the URL is `http://service.iris.edu/fdsnws/event/1/query?minmagnitude=6.0&starttime=2000-01-01T00%3A00%3A00.000000`.

However, if you check in wireshark, `comcat.cr.usgs.gov` redirects to `earthquake.usgs.gov`, and the parameters are encoding a second time, so that the URL is `http://earthquake.usgs.gov/fdsnws/event/1/query?minmagnitude=6.0&starttime=2000-01-01T00%253A00%253A00.000000`.

I don't seem to see any handling for 301 Location Moved status codes, though... Is this a bug lower in the stack, or maybe in `future`?

**Comment by QuLogic** [comment]
OK, this looks like a bug in the USGS server:
```
GET /fdsnws/event/1/query?starttime=2000-01-01T00%3A00%3A00.000000&minmagnitude=6.0 HTTP/1.1
Accept-Encoding: identity
Connection: close
User-Agent: ObsPy 0.10.1 (Linux-3.19.5-200.fc21.x86_64-x86_64-with-fedora-21-Twenty_One, Python 3.4.1)
Host: comcat.cr.usgs.gov

HTTP/1.1 301 Moved Permanently
Date: Thu, 14 May 2015 02:54:22 GMT
Server: Apache
Location: http://earthquake.usgs.gov/fdsnws/event/1/query?starttime=2000-01-01T00%253A00%253A00.000000&minmagnitude=6.0
```

The `Location` in the response is double-encoded. I'm going to change the URL in the mapping for USGS, but we should report this bug to someone at USGS.

**Comment by krischer** [comment]
Appears to be `mod_rewrite` messing things up. There are quite some resources online:

* http://tkurek.blogspot.de/2013/06/252f-instead-of-2f-in-url-apache.html
* http://stackoverflow.com/questions/6520484/mod-rewrite-urlencoding-an-already-urlencoded-querystring-parameter-any-way-to
* http://serverfault.com/questions/331899/apache-mod-rewrite-double-encodes-query-string-on-redirect

I'll send them a link to this issue. Nice find!

**Comment by emartinez-usgs** [comment]
We will look at the `mod_rewrite` issue on our server and work to correct it. However it is worth noting here that the "comcat.cr.usgs.gov" server is going away on June 1, 2015. The rewrite is a transitional solution to allow users time to migrate to the new URL:

http://earthquake.usgs.gov/fdsnws/event/1/

An email was sent out notifying users of this change http://geohazards.usgs.gov/pipermail/realtime-feeds/2015-March/000023.html. For long-term success I recommend you also start directly accessing the new URL.

**Comment by krischer** [comment]
> For long-term success I recommend you also start directly accessing the new URL.

Already done. Should go live with the release of ObsPy 0.10.2 next week.

**Comment by emartinez-usgs** [comment]
That's great. I also added the "NE" option to hopefully fix the rewrite issue.

**Comment by krischer** [comment]
I tested with some queries and it now works for me.
