### ISSUE TITLE
Cannot install outside default location

### ISSUE THREAD

**Issue by brunogoetze** [obspy/obspy#1049]
Hello, I am trying to get obspy installed in a cluster computer in my university. Since I don't have administrative privileges, I asked the university IT department to do it, but they need to install it in a non-standard location and they haven't been able to. This is their reply to my:

I have tried to get this installed on the nic cluster, as well as my local machine and I haven't been able to get it to install anywhere other than the main execution path. This means that this software is not written to be installed anywhere I can isolate it and write a module to redirect your environment. If permission were granted you would modify the environment for all users who use the machine, which could cause software conflicts. It continually complains about not being able to install because I'm not installing to the default location, regardless of my administrative privileges. If you would like me to try again please petition the authors of Obspy for instruction on how to install your version in a non standard location as I continually get errors when using the setup.py install --prefix=$HOME/obspy  method.

Does anyone knows how to solve this issue?

Thank you

**Comment by krischer** [comment]
Heyhey,

a very simple way is to just use Anaconda, which does not require root rights:
https://github.com/obspy/obspy/wiki/Installation-via-Anaconda

Other possibilities to install ObsPy without admin privileges are written down here:
https://github.com/obspy/obspy/wiki/Installation-via-PyPi-from-source#on-non-root-access

The same page also has information about how to install ObsPy with from source. Can you install all the dependencies?

There is also no such thing as a default install location in Python. It depends on how and where Python itself has been installed. ObsPy uses Python default installation mechanism so you should be able to find information about your issue online.

If the issue persists, please post the exact and full installation error log here. It is hard to diagnose without it.

Cheers!

**Comment by QuLogic** [comment]
I am going to close this as we have not heard back in 3 months.
