### ISSUE TITLE
remove build dependency on numpy

### ISSUE THREAD

**Issue by petrrr** [obspy/obspy#1051]
We should check if this build dependency could be removed. We have no Fortran code in ObsPy anymore and we do not need `f2py` support of `numpy.distutils`. So there is a good chance that we can replace `numpy.distutils` imports by standard lib distutils or setuptools.

**Comment by petrrr** [comment]
Okay at least the following import seems to require `numpy.distutils`:
```
from numpy.distutils.exec_command import exec_command, find_executable
```
used only in `class Help2ManBuild(build)`.

**Comment by niowniow** [comment]
Does anyone know if the dependency can be removed?

There are certain downsides requiring numpy to be installed prior to obspy, e.g. when trying to deploy an application using obspy on a new machine from a single requirements.txt. (with pip -r).  In an automated context it makes deployment difficult.

**Comment by krischer** [comment]
It currently is still needed as we use numpy distutils for compiliation. I do agree that it would probably be fairly simple to swap it out with the normal distutils and additionally it would be a nice improvement. Our CI should catch any issues. Please let us know if somebody wants to tackle this.

**Comment by megies** [comment]
> e.g. when trying to deploy an application using obspy on a new machine from a single requirements.txt

As a comment, if the machine is identical (in terms of operating system, architecture etc) to another one of your systems, I would just zip an existing Python installation and deploy by unzipping. But yes, that's not always viable.
