### ISSUE TITLE
tutorial PDF no longer built

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#1052]

**Comment by ThomasLecocq** [comment]
should this be ready for 1.0 ?

**Comment by megies** [comment]
Too lazy to fix it now.. don't think that a lot of people depend on it either. We're definitely not holding up the release for it..

If anybody wants to tackle it docs can be re-built afterwards again.

**Comment by megies** [comment]
:tada: 
Actually, tutorial pdf is just fine right now and link is fine, built by our cronjob buildbot couple hours ago. Maybe has something to do with the buildbot Python env update or some of the last minute fixes prior to 1.0.0.
