### ISSUE TITLE
obspy.station.response.PolesZerosResponseStage requires at least 1 pole and 1 zero

### ISSUE THREAD

**Issue by paitor** [obspy/obspy#1053]
Hi 

If I understand the definition of the class obspy.station.response.PolesZerosResponseStage correctly the current implementation requires at least one pole and one zero upon initiation of a new object of this class. This is according to my understanding of the poles and zeros type of transfer function not necessary requirement and neither a requirement of the FDSN station XML and should therefore probably be changed.

regP

**Comment by krischer** [comment]
Can you just pass empty lists. At least initialization works. I did not test if you can actually calculate a response with it thou.

```python
In [1]: from obspy.station.response import PolesZerosResponseStage

In [2]: PolesZerosResponseStage(stage_sequence_number=1, stage_gain=1E6, 
    stage_gain_frequency=1.0, input_units="counts", output_units="m/s", 
    pz_transfer_function_type="LAPLACE (RADIANS/SECOND)", normalization_frequency=2.0, 
    zeros=[], poles=[])
Out[2]:
Response type: PolesZerosResponseStage, Stage Sequence Number: 1
	From counts to m/s
	Stage gain: 1000000.0, defined at 1.00 Hz
	Transfer function type: LAPLACE (RADIANS/SECOND)
	Normalization factor: 1, Normalization frequency: 2.00 Hz
	Poles:
	Zeros:
```

**Comment by paitor** [comment]
Sure that will do the trick for me and should also work with obspy.station.stationxml.write_StationXML(...), thanks for the pointer and sorry for not thinking about this myself before posting...
