### ISSUE TITLE
Typo in documentation of Stream.rotate?

### ISSUE THREAD

**Issue by martinvandriel** [obspy/obspy#1059]
One of the coordinate systems is called LQR and LQT, I suppose it is just a typo but I don't know which one is correct:

http://docs.obspy.org/packages/autogen/obspy.core.stream.Stream.rotate.html

**Comment by megies** [comment]
LQR makes no sense, it's got to be LQT. Thanks for the tip, at least it's only wrong in this one place in the docs, the code is fine.
