### ISSUE TITLE
error when installing from pypi

### ISSUE THREAD

**Issue by mathisonian** [obspy/obspy#1062]
I get the following error after installing from pypi a few minutes ago.

![screen shot 2015-05-28 at 3 16 31 pm](https://cloud.githubusercontent.com/assets/1074773/7868799/5bdde9c2-054c-11e5-97c1-66d2f04962cb.png)

However I am able to successfully import  the FDSN client by pulling down the repo from github and installing that.

**Comment by claudiodsf** [comment]
Hi, 
the current development version (from github) has a new module structure which is different from the stable version (0.10.2).

If you want to use the fdsn client with 0.10.2, you have to do:
```python
from obspy.fdsn import Client
```

Please refer to the current stable documentation: http://docs.obspy.org/packages/obspy.fdsn.html#module-obspy.fdsn

Cheers,
Claudio

**Comment by mathisonian** [comment]
Ah, thanks for the quick response! I must have been looking at the wrong documentation
