### ISSUE TITLE
Instrumental response by obspy coincides with by evalresp at low frequency but differs at high frequency

### ISSUE THREAD

**Issue by lileipku00** [obspy/obspy#1064]
Take one station as an example. The PAZ can be found at
http://ds.iris.edu/mda/IU/ANMO/00/BHZ?timewindow=2015/01/01%2014:30:00-2599/12/31%2023:59:59

The plot of instrumental response at above url is the same as produced by evalresp, but differs at high frequency with that by obspy.

```
import numpy as np
import matplotlib.pyplot as plt
from obspy.signal import pazToFreqResp

poles = [
	-5.943130e+01+0.000000e+00j,
	-2.271210e+01+2.710650e+01j,
	-2.271210e+01-2.710650e+01j,
	-4.800400e-03+0.000000e+00j,
	-7.394060e-02+0.000000e+00j ]
zeros = [0j, 0j]
scale_fac = 2.937713e+14
delta = 0.025
#delta = 0.05
h, f = pazToFreqResp(poles, zeros, scale_fac, delta, 2**14, freq=True)

pi = 3.141592653589793

plt.figure()
plt.subplot(211)
plt.loglog(f, abs(h))
plt.ylabel('Amplitude')
plt.subplot(212)
phase = np.unwrap(np.arctan2(h.imag, h.real)) *180/pi
plt.semilogx(f, phase)
plt.xlabel('Frequency [Hz]')
plt.ylabel('Phase [deg]')
plt.subplots_adjust(wspace=0.3)
plt.show()
```

**Comment by krischer** [comment]
That's to be expected. If you just plot the Poles and Zeros you essentially only deal with stage zero of the instrument chain and the total sensitivity. The later stages, especially the decimation stages might influence the frequencies around nyquist.

You have to use the other stages as well to get the same plot as IRIS. I'm too lazy to check the numerical values but this appears to be identical to the IRIS plot.

```python
import matplotlib.pylab as plt
plt.style.use("ggplot")

import obspy
from obspy.fdsn import Client

c = Client("IRIS")

inv = c.get_stations(
    network="IU", station="ANMO", location="00",
    channel="BHZ", starttime=obspy.UTCDateTime(2015, 1, 1),
    level="response")

inv.plot_response(0.00005)
```
![response](https://cloud.githubusercontent.com/assets/800487/7882587/51e98796-060f-11e5-8ec5-5fe01faa8093.png)

**Comment by lileipku00** [comment]
Thanks @krischer 
 
So it's no problem to remove instrumental response using obspy.

**Comment by krischer** [comment]
I'm fairly sure it works. We tested it with I think literally half a million of responses: https://github.com/obspy/sandbox/tree/master/stationxml_test
