### ISSUE TITLE
plugin table missing for Inventory.write

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1071]
..like we have for Catalog.write: http://docs.obspy.org/packages/autogen/obspy.core.event.Catalog.write.html?highlight=write#obspy.core.event.Catalog.write

**Comment by krischer** [comment]
Maybe we can find a different way to do the old one? Its really a pain to keep the doctest up-to-date....

**Comment by megies** [comment]
obsolete, problem went away by keeping eyes closed long enough
