### ISSUE TITLE
rename datamark to win

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#1072]
Altough win is a stupid name, it's the real name of the data format, while datamark is the name of the datalogger...

As the CSD article is out now, and presents `obspy.win`, this might be a good time to start the name change+deprecation, no ?

**Comment by xiansch** [comment]
I have tried using the datamark i/o on Hi-net win32 and it seems to work.  I am not familiar with the basic win format and the differences from win32, but have never heard of datamark, so second the name obspy.win.  Is anyone familiar with the win/win32 differences and possible conversion issues?  I'm assuming datamark = basic win and not win32?

**Comment by megies** [comment]
@ThomasLecocq any insights?

**Comment by ThomasLecocq** [comment]
Hi,
sorry for the delay, was on holiday :-)

Sooo.. Indeed, "Win" is the name of the format, and "Datamark" is the name of the datalogger, built by Hakusan. I named it "datamark" because it's how it was called in Indonesia by the CVGHM. 

Check the PDF and email of Hakusan corp in the io/datamark folder for more information about win.

So, from what I can tell, the current naming could be changed to win. 

On the other hand, I *think* `win` is not `win32`, the new format stored by the Datamark/Hakusan dataloggers. I have never seen win32 files so I can't tell.

HTH

**Comment by krischer** [comment]
@xiansch Can you provide us with some `win32` files?

**Comment by xiansch** [comment]
I put a pull request on master/docs, there is a sample win32 file and the pdf with the data format.  Normally the win files are 1 min long (100 Hz) but the one I used is downsampled to 20 Hz, and 1 hour, and I extracted only 3 channels because of the file size.  Since the win32 files sometimes contain a lot of channels that are not needed (again, I'm not sure about regular win but I think it is the same) it would also be nice to have the i/o read specific channels only as a input parameter.

**Comment by xiansch** [comment]
Hi, I've contacted NIED about using win32 in the obspy docs but there has been no reply as of yet.  For the time being, is there a way to get io.datamark to do a little more than just read() for the basic win/datamark file, such as read in particular channels?
There are some native tools for doing that on the win site: http://eoc.eri.u-tokyo.ac.jp/WIN/Eindex.html
such as dewin: extracts a channel and writes to .txt file
wch: extracts channels (can do multiple channels) but writes each to a _separate_ win file
so it is possible to extract all channels before reading into obspy, but somewhat troublesome and exponentially increases the number of files in storage.
Ideally I would want to be able to do something like
st= read('datafile.win', 'list of channels or .txt file') which wouldn't take as long as reading in the whole (~2400 channels) file and selecting the channels post-read.

**Comment by krischer** [comment]
The MiniSEED reader supports something similar (http://docs.obspy.org/packages/autogen/obspy.io.mseed.core._read_mseed.html#obspy.io.mseed.core._read_mseed):

```python
st = read("test.mseed", sourcename="BW.UH2..*")
```

This will then only read channels matching the `sourcename` pattern - something very similar can definitely be implemented for reading win files. Also note the `starttime` and `endtime` flags.

Regarding who will actually do it: Nobody is paid to develop ObsPy and we develop things either when we need them ourselves or in our free time when we feel like it (which is quite often :smile:). If you need this ASAP your best bet is to implement it yourself. We'd be very happy to guide and assist you on the way.

For what you want to do, you'd have to add one or more new parameters to `_read_datamark()` (https://github.com/obspy/obspy/blob/master/obspy/io/datamark/core.py#L55) and then just add appropriate `continue` statements in the main loop. Should be fairly straightforward. Once it works just open a pull request and we can discuss your changes.

**Comment by megies** [comment]
obsolete, i believe. at least we have a folder `io.win` ;-P
