### ISSUE TITLE
release process: ensure that rights are set correctly

### ISSUE THREAD

**Issue by petrrr** [obspy/obspy#1074]
In the past, the issue of setting the correct rights in the PyPI distfile already surfaced several times. This causes problems for users when installed system-wide with admin rights (e.g. observed with MacPorts). Ideally this should be resolved by fixing the release process.

**Comment by megies** [comment]
Any more insight on this? This likely is very specific to the mentioned packaging effort, namely MacPorts.. at least I do not remember having a problem like this with other packaging.
In any case, we need more information, otherwise I do not think anybody can work on this and we can not have this block a release.

**Comment by krischer** [comment]
As far as I remember it was an issue with rights in the source distribution, e.g. with some of the files auto-generated by distutils. I'd leave this open and we'll fix this once we have release candidates for the new version.

**Comment by petrrr** [comment]
Well, if you look at the various zip files of the last releases, the rights are set differently (e.g.  0.10.1 is okay, while 0.10.2 does not set read permits). At least for Macports this by default propagates into the packages, and would need extra patching. I think it actually depends on umask setting when doing the release. This problem is that the this already occurred more than once and it would be great if this does not depend on the umask settings of the releaser.

**Comment by megies** [comment]
Do zip files even preserve permissions? I don't think so.. tgz is a different matter, of course. So just only release zip in the future and this is solved?

**Comment by krischer** [comment]
They do preserve permissions by some "external attributes" flag which most unzipping programs on unix honor.

**Comment by megies** [comment]
On Debian Linux, command line `unzip` is simply using the current `umask` for setting all file permissions, so I guess this is Mac specific.

**Comment by krischer** [comment]
Apparently `unzip` should be able to save the permissions: http://stackoverflow.com/questions/13633488/can-i-store-unix-permissions-in-a-zip-file-built-with-apache-ant

I guess it depends on many things - we still need to somehow fix the issue I guess :-(

**Comment by krischer** [comment]
We came up with a plan - just writing down here so we don't forget:

Within the `setup.py` we will set the umask if a `sdist` build is being attempted. This should hopefully fix the issue.

**Comment by krischer** [comment]
Should be fixed by creating the source distribution with

```bash
umask 0022 && chmod -R a+rX . && python setup.py sdist --formats=zip
```

We have to properly test this with the release candidate.

**Comment by krischer** [comment]
@petrrr Can you test `1.0.0rc1` which has been generated with the above method.

https://www.geophysik.uni-muenchen.de/~megies/obspy-1.0.0rc1.zip

**Comment by QuLogic** [comment]
I'm going to close this under the assumption that it is fixed, since the MacPorts item is marked done in #1243.

**Comment by megies** [comment]
I guess we should compile a wiki page on steps that need to be taken (and pitfalls avoided) in releasing in the wiki..
