### ISSUE TITLE
PAZ instrument response

### ISSUE THREAD

**Issue by FadelI** [obspy/obspy#1078]
Dear All,
I am sorry if the question is naive.
How can I remove the instrument response to get the displacement using polezero file like this:

```
File: BHZ.BAZ
-----------------------------------------------------------------------------------------------
ZEROS	3
	+0.000000e+00	+0.000000e+00	
	+0.000000e+00	+0.000000e+00	
	+0.000000e+00	+0.000000e+00	
POLES	5
	-5.943130e+01	+0.000000e+00	
	-2.271210e+01	+2.710650e+01	
	-2.271210e+01	-2.710650e+01	
	-4.800400e-03	+0.000000e+00	
	-7.394060e-02	+0.000000e+00	
CONSTANT	2.937713e+14
------------------------------------------------------------------------------------------------
```

I do not have the gain or the sensitivity.
I do this in SAC using:

```
>> transfer from polezero subtype BHZ.PAZ to none freqlimits 0.001 0.002 40 50
```

Thank you in Advance,
Regards,
Fadel

**Comment by megies** [comment]
[Searching our documentation pages for "paz"](http://docs.obspy.org/search.html?q=paz) what you're looking for to read the SACPZ file is the fifth hit.
[Searching for "sac paz"](http://docs.obspy.org/search.html?q=sac+paz) it is even the first hit:
 - http://docs.obspy.org/packages/autogen/obspy.sac.sacio.attach_paz.html

To remove response using a PAZ  dictionary see [our tutorial](http://docs.obspy.org/tutorial/code_snippets/seismometer_correction_simulation.html?highlight=remove%20response#using-a-paz-dictionary).

Looking at the documentation for [`Stream/Trace.simulate()`](http://docs.obspy.org/packages/autogen/obspy.core.stream.Stream.simulate.html) you can see that you can use `paz_remove="self"` to use PAZ from the dictionary that was previously attached to the (/each) trace when you use the above mentioned routine.
