### ISSUE TITLE
BUG: get_travel_time

### ISSUE THREAD

**Issue by sun031** [obspy/obspy#1090]
While I try to run the followed code, OBSPY gives error.

from obspy.taup import TauPyModel
model = TauPyModel(model="ak135")
arr = model.get_travel_times(1.0, 3.522)

It seems that while depth ranges from 0.1 to 1.2, the get_travel_times command does not work. No related to distance.

The error information gives below:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-83-102b06190c2e> in <module>()
----> 1 arr = model.get_travel_times(1.0, 3.522)

/usr/lib/python2.7/dist-packages/obspy/taup/tau.py in get_travel_times(self, source_depth_in_km, distance_in_degree, phase_list)
    340         tt = TauP_Time(self.model, phase_list, source_depth_in_km,
    341                        distance_in_degree)
--> 342         tt.run()
    343         return Arrivals(sorted(tt.arrivals, key=lambda x: x.time),
    344                         model=self.model)

/usr/lib/python2.7/dist-packages/obspy/taup/taup_time.py in run(self)
     35         arrival times will be in self.arrivals.
     36         """
---> 37         self.depth_correct(self.depth)
     38         self.calculate(self.degrees)
     39 

/usr/lib/python2.7/dist-packages/obspy/taup/taup_time.py in depth_correct(self, depth)
     47             self.depth_corrected_model = self.model.depth_correct(depth)
     48             self.arrivals = []
---> 49             self.recalc_phases()
     50         self.source_depth = depth
     51 

/usr/lib/python2.7/dist-packages/obspy/taup/taup_time.py in recalc_phases(self)
     70                 try:
     71                     seismic_phase = SeismicPhase(temp_phase_name,
---> 72                                                  self.depth_corrected_model)
     73                     new_phases.append(seismic_phase)
     74                 except TauModelError:

/usr/lib/python2.7/dist-packages/obspy/taup/seismic_phase.py in __init__(self, name, tMod)
    108         self.puristName = self.create_purist_name(tMod)
    109         self.parse_name(tMod)
--> 110         self.sum_branches(tMod)
    111 
    112     def create_purist_name(self, tMod):

/usr/lib/python2.7/dist-packages/obspy/taup/seismic_phase.py in sum_branches(self, tMod)
    616                 and self.minRayParamIndex == len(tMod.ray_params) - 1:
    617             # All ray parameters are valid so just copy:
--> 618             self.ray_param = tMod.ray_param.copy()
    619         elif self.maxRayParamIndex == self.minRayParamIndex:
    620             # if "Sdiff" in self.name or "Pdiff" in self.name:

AttributeError: 'TauModel' object has no attribute 'ray_param'

**Comment by QuLogic** [comment]
This bug has already been reported in #1057.
