### ISSUE TITLE
Writing MSEED with STEIM2 

### ISSUE THREAD

**Issue by bonaime** [obspy/obspy#1095]
hi,

We would like to convert MSEED with 'GEOSCOPE16_4' compression into MSEED files with STEIM2 compression. 
The following code does not work 
```python
from obspy.arclink import Client
from obspy import UTCDateTime
client = Client("webdc.eu", 18001, user='test@obspy.org')
client.status_delay=2
t = UTCDateTime("1999-01-01 00:00:00")
st = client.getWaveform("G", "BNG", "", "LHZ", t, t + 60*60)
print(st)
st.write('test.mseed', format="MSEED")
```
the error is
```error
ValueError: Encoding 'GEOSCOPE16_4' cannot be written with ObsPy. Please use another encoding.
```
Is there a way to use STEIM2 while writing MSEED data ?

**Comment by barsch** [comment]
Just use the ```encoding``` parameter, e.g.

```st.write('test.mseed', format='MSEED', encoding='STEIM2')```

more options are listed here

http://docs.obspy.org/packages/autogen/obspy.mseed.core.writeMSEED.html#obspy.mseed.core.writeMSEED

**Comment by bonaime** [comment]
not working with obspy-0.10.2
``` error
In [3]: st.write('test.mseed', format="MSEED", encoding='STEIM2')
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-3-75c43094c965> in <module>()
----> 1 st.write('test.mseed', format="MSEED", encoding='STEIM2')

/Users/bonaime/anaconda/lib/python2.7/site-packages/obspy-0.10.2-py2.7-macosx-10.5-x86_64.egg/obspy/core/stream.pyc in write(self, filename, format, **kwargs)
   1416             raise TypeError(msg % (format,
   1417                                    ', '.join(ENTRY_POINTS['waveform_write'])))
-> 1418         writeFormat(self, filename, **kwargs)
   1419
   1420     def trim(self, starttime=None, endtime=None, pad=False,

/Users/bonaime/anaconda/lib/python2.7/site-packages/obspy-0.10.2-py2.7-macosx-10.5-x86_64.egg/obspy/mseed/core.pyc in writeMSEED(stream, filename, encoding, reclen, byteorder, sequence_number, flush, verbose, **_kwargs)
    714                     information.
    715                     """ % (_i, ident)
--> 716                 raise Exception(msg)
    717             trace_attr['encoding'] = encoding
    718         elif hasattr(trace.stats, 'mseed') and hasattr(trace.stats.mseed,

Exception:
                    Wrong dtype for Stream[0].data for encoding STEIM2.
                    Please change the dtype of your data or use an appropriate
                    encoding. See the obspy.mseed documentation for more
                    information.
```

**Comment by claudiodsf** [comment]
Hi Seb,
what do you get from:
```python
print st[0].data.dtype
```
?

`STEIM2` compression needs integer arrays.

**Comment by krischer** [comment]
You have to convert the floating point data to integers. We don't do that automatically as there is potential loss of accuracy/data.

This should do the trick (you'll still have to look at your data to make sure it "survives" the conversion to integers; raw displacement in meters for example will most likely not):

```python
import obspy
import numpy

st = obspy.read("...")
for tr in st:
    tr.data = np.require(tr.data, dtype=np.int32)

st.write("...", format="mseed", encoding="steim2")

**Comment by megies** [comment]
Unless you scale your data, integers are no option here, looks like. There are encodings implemented in ObsPy to write float data to miniSEED, but file size will be much higher (and other software might not be able to read those float encodings)..
```python
st.write("...", "MSEED", encoding="FLOAT32")
```

**Comment by bonaime** [comment]
In [7]: print st[0].data.dtype
float32

**Comment by nikosT** [comment]
np.require makes tr.data zeros

**Comment by megies** [comment]
> edit: probably cause of the low values are rounded to zero

yes, like stated above for the example data this doesn't work unless some scaling is applied (data varies from 2.2 to 3.0), but then it will be at least difficult and in worst case imporssible to later tell what's in the data..

Any reason to bring this topic forward again @nikosT?

**Comment by nikosT** [comment]
Yep, that's right. I was trying to convert mseed files with FLOAT64 to mseed files with STEIM2 but I had the floating issue, since STEIM2 needs integers. But I think a multiplication should be applied in order to scale up the data to int values -I'm not quite sure if it would mathematical correct-.
