### ISSUE TITLE
Obspy on Raspberry Pi 2 linux-armv7l

### ISSUE THREAD

**Issue by bonaime** [obspy/obspy#1112]
Hi,
How can I install Obspy on a Raspberry Pi 2 linux-armv7l  with Raspbian Wheezy ? 
Is it possible to have an Anaconda package ? 

Thank you

**Comment by megies** [comment]
For global python, works the same as Raspberry Pi 1, via package management, see Wiki.

If you need it in a user space Python installation, it should compile just fine doing `$ pip install obspy` once you have all the compilation dependencies installed via package management.
