### ISSUE TITLE
obspy.station.station.Station() does not require input parameter creation_date

### ISSUE THREAD

**Issue by paitor** [obspy/obspy#1118]
Hi

Just noted that creation_date is not a required parameter in the __init__ method of `obspy.station.station.Station()` as it should be according to the station xml schema. 

regP

**Comment by megies** [comment]
Maybe we should just set it to current time if not explicitly specified..

**Comment by paitor** [comment]
Seems reasonable

**Comment by megies** [comment]
Continued in #1117.
