### ISSUE TITLE
missing implicitly required arguments in obspy.station.channel.Channel()

### ISSUE THREAD

**Issue by paitor** [obspy/obspy#1119]
Hi

I noted in the stationXML schema that if the sample rate group is used then SampleRate is required and further if SampleRateRatio is used then both NumerSamples and NumberSeconds are required. Currently this is not checked for in obspy.station.channel.Channel(). The current structure of the class makes it hard to enforce these requirements though. 

One solution could be to move sample_rate_ratio_number_samples and sample_rate_ratio_
number_seconds into a new class (sample_rate_ratio) and replace these attributes with a sample_rate_ratio attribute with value being the new class, and then enforce sample_rate to be set prior to sample_rate_ratio (i.e. define a .setter method for  sample_rate_ratio where this is checked)

Similarly if calibration_units_description is used then calibration_unit should be required according to the xml schema.

**Comment by megies** [comment]
Continued in #1117.
