### ISSUE TITLE
missing argument external_references in __init__ method of obspy.station.channel.Channel

### ISSUE THREAD

**Issue by paitor** [obspy/obspy#1120]
Hi 

The external_references seems to be missing from the argument list of the  `__init__` method of obspy.station.channel.Channel albeit being described in the doc string, I note that an appropriate setter method is defined and that the `__init__` method actually defaults the argument to an empty list, thus it is of course possible to create a new instance of the class and then append external references to the list, but it would be nice to be able to do so directly upon creation

**Comment by megies** [comment]
Hi there, I think all those tickets you opened are very similar and connected.. I think it's easier if you add new things you notice directly in https://github.com/obspy/obspy/pull/1117 in the first comment by editing it (making a list of things, maybe with checkboxes, see https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments).

**Comment by paitor** [comment]
Ok, sorry will do so if I stumble across more issues

**Comment by megies** [comment]
No problem, I just think all of this belongs in the same place to be addressed.

**Comment by megies** [comment]
Conitnued in #1117.
