### ISSUE TITLE
Shapefile tests do not work with GDAL 2.0.0

### ISSUE THREAD

**Issue by QuLogic** [obspy/obspy#1124]
This came up in #1121 and those tests were changed to be skipped when running with GDAL 2.0.0. They should probably be updated to work correctly in all cases.

Only the `.dbf` files have been changed, and I suspect there is some version field that has been updated.

**Comment by megies** [comment]
Should eventually revert 414ec8ceb6bae6c9faf172bcadad6f38ee30a928.
