### ISSUE TITLE
Get older stable releases docs on RTD

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1129]
This is a followup to #1128.

Once the "Read the docs" style etc. is finalized, we should backport the necessary changes to (some of) the past stable releases to get them on RTD, too.

**Comment by megies** [comment]
Read the docs hasn't been in use for us really, so closing for now.

**Comment by krischer** [comment]
I just turned off all read the docs build to not waste their resources. Should we just delete the read the docs project?

**Comment by megies** [comment]
> I just turned off all read the docs build to not waste their resources. Should we just delete the read the docs project?

Yeah, why not.. our docs build is quite complex and it seems it's less hassle to just do it ourselves..

**Comment by krischer** [comment]
Done.
