### ISSUE TITLE
Plans for including nd format models for obspy.taup?

### ISSUE THREAD

**Issue by mpanning** [obspy/obspy#1133]
Are there any plans to update obspy.taup to use the nd models preferred by the original Java version?  When exploring progressively less Earth-like models, specifying named discontinuities is an important addition.

I can help contribute if this is not already planned.

**Comment by krischer** [comment]
No plans AFAIK but that should be fairly simple to add. A pull request would of course be very welcome!

**Comment by mpanning** [comment]
Okay... I don't have time at this minute, but it just seems like a relatively minor modification to velocity_model.py.  I may take a hack at it in the next couple weeks, and see if I can make it work for a pull request.

**Comment by megies** [comment]
Don't be shy submitting a dirty hack, it doesn't have to be perfect. People can comment on it once there is something to look at. Ideally make a branch off `master`, add some changes and push it to your fork, so people can look at it.

**Comment by ThomasLecocq** [comment]
@mpanning if you don't understand the language used by @krischer and @megies, don't worry, just copy-paste some usable code with comments... :-)

**Comment by mpanning** [comment]
Thanks.  I just forked the repo, and I'll see if I can make a branch and take a hack at it.  Just learning how to do things on github right now.

**Comment by mpanning** [comment]
Just put in a pull request with the updated velocity_model.py and also added tests in taup/tests/test_velocity_model.py

**Comment by krischer** [comment]
Continued in #1147
