### ISSUE TITLE
Support for Japanese ASCII (K-Net/Kik-Net) Release Soon?

### ISSUE THREAD

**Issue by sgjholt** [obspy/obspy#1136]
Hi,

I'm a new starter PhD at Liverpool University and a new user to python/obspy. I want to use obspy to read k-net/kik-net data and noticed that you're in the final stages of adding functionality to read this format. Just wondering when you're planning to release this functionality and how I can upgrade when it is released. Can I simply use the command ' pip install --upgrade obspy ' in terminal ?

Thanks,

James

**Comment by krischer** [comment]
Hi James,

it will definitely go into the next release.

ETA: 1 - 2 months. Definitely before AGU.

Upgrading depends on how you installed obspy in the first place but the general idea is right.

**Comment by krischer** [comment]
If you need it right now you can also use the other branch with that functionality. I'm sure someone at your institute is good enough with git to help you with that.

**Comment by sgjholt** [comment]
Okay! Brilliant, thank you.
