### ISSUE TITLE
QuakeML Resource ID comparison operators

### ISSUE THREAD

**Issue by jsaul** [obspy/obspy#1139]
Please see the following example:

``` python
import sys, obspy.core.event

catalog = obspy.core.event.read_events(sys.argv[1])

for event in catalog:
    for origin in event.origins:
        print origin.resource_id, event.preferred_origin_id
        print origin.resource_id == event.preferred_origin_id
        print str(origin.resource_id) == str(event.preferred_origin_id)
        print type(origin.resource_id), type(event.preferred_origin_id)
```

And the output

```
smi:scs/0.7/Origin#20140824154358.375604.335155 smi:scs/0.7/Origin#20140824154358.375604.335155
False
True
<class 'obspy.core.event.ResourceIdentifier'> <class 'future.types.newstr.newstr'>
```

Trivial comparisons like

``` python
origin.resource_id == event.preferred_origin_id
```

should of course be possible directly, because in QuakeML, Event.preferredOriginID refers to the Origin.publicID (in ObsPy: resource_id) of the preferred origin and testing for equality must be possible directly.

The reason for the above to evaluate as false is that origin.resource_id is of type obspy.core.event.ResourceIdentifier and if the other is not, it will always evaluate to false.

I therefore propose to change:

``` python
class ResourceIdentifier(object):
[...]

    def __eq__(self, other):
        if not isinstance(other, ResourceIdentifier):
            return False
        if self.id == other.id:
            return True
        return False
```

to

``` python
    def __eq__(self, other):
        return self.id == str(other)
```

unless there is some very good reason for probing the type. In that case, of course, event.preferred_origin_id would also be required to become a ResourceIdentifier.

On a side note, it would be desirable if ObsPy could fully support the QuakeML naming of attributes. In particular, the resource_id in ObsPy corresponds to public_id (strictly publicID) in QuakeML and
should therefore be accessible via public_id, too.

**Comment by krischer** [comment]
There is also a function for each of the preferred ids to retrieve it's associated element.

```python
In [1]: import obspy

In [2]: cat = obspy.read_events()

In [3]: cat[0].origins[0] == cat[0].preferred_origin()
Out[3]: True
```

Nonetheless I don't see any downside to the proposed `__eq__` change. I'll wait for some other comments before changing anything - maybe I'm missing something.




> On a side note, it would be desirable if ObsPy could fully support the QuakeML naming of attributes. In particular, the resource_id in ObsPy corresponds to public_id (strictly publicID) in QuakeML and
> should therefore be accessible via public_id, too.

That's a bit on purpose to make clear that our event class is not only QuakeML although it is modelled very strongly after it. Too late to change it but we could introduce aliases for the ids to be accessible as `public_id` as well.

**Comment by megies** [comment]
> but we could introduce aliases for the ids to be accessible as public_id as well.

Aliases clutter the namespace and might confuse people more than they would help.. just my opinion, though.

> Nonetheless I don't see any downside to the proposed __eq__ change. I'll wait for some other comments before changing anything - maybe I'm missing something.

I don't see a problem there either. Many builtin equality checks in Python give `True` even if types of objects differ (e.g. `True == 1`), and the string is what counts for the Resource ID anyway, the only reason why it's an object type is for all the convenience routines around it.

If we rely on `str()` for the comparison, I think it would be a tad clearer though if we implement it like this:
```python
    def __eq__(self, other):
        return str(self) == str(other)
```

Anything that we have to consider in terms of Py2/3 str/unicode there..?

**Comment by krischer** [comment]
> Anything that we have to consider in terms of Py2/3 str/unicode there..?

`future` overwrites `str` with `unicode` on Python 2 so we should be good here.



> but we could introduce aliases for the ids to be accessible as public_id as well.
> 
> Aliases clutter the namespace and might confuse people more than they would help.. just my opinion, though.

Fair point.

Supporting of the full QuakeML naming scheme is still a valid case I think but somebody would have to go through all the elements and make sure this is actually the case. No use to do it only for a couple of things I guess.

**Comment by megies** [comment]
> Supporting of the full QuakeML naming scheme is still a valid case I think but somebody would have to go through all the elements and make sure this is actually the case. No use to do it only for a couple of things I guess.

I'd probably leave it as is for now, any changes in future QuakeML or StationXML releases will be tough enough to handle I think.

**Comment by jsaul** [comment]
> Supporting of the full QuakeML naming scheme is still a valid case I think but somebody would have to go through all the elements and make sure this is actually the case. No use to do it only for a couple of things I guess.

What you are saying is "unless ObsPy is found to be 100.0 percent QuakeML compliant we need not bother to adhere to the QuakeML specification."

I haven't checked against all of the QuakeML specification, but I think the support is pretty decent and for sure is a great start. Renaming a very common attribute like public_id to resource_id makes this effort appear rather halfhearted and ultimately a missed opportunity to promote a seismological standard.

**Comment by megies** [comment]
obsolete, this works as proposed in first post nowadays
