### ISSUE TITLE
add tests for Response.get_sacpz()

### ISSUE THREAD

**Issue by lileipku00** [obspy/obspy#1142]
In `get_sacpz(self)` in **_response.py**_
        `sensitivity = self.instrument_sensitivity.value`
        `return paz_to_sacpz_string(paz, sensitivity)`

and in `paz_to_sacpz_string(paz, instrument_sensitivity)`,
    `constant = paz.normalization_factor * instrument_sensitivity.value`

one of the `.value`s should be removed.

**Comment by megies** [comment]
I can't follow, what's the problem exactly?

**Comment by krischer** [comment]
```python
In [2]: obspy.read_inventory()[0][0][0].response.get_sacpz()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-ae2469a022e5> in <module>()
----> 1 obspy.read_inventory()[0][0][0].response.get_sacpz()

/Users/lion/workspace/code/obspy/obspy/core/inventory/response.py in get_sacpz(self)
   1338         paz = self.get_paz()
   1339         sensitivity = self.instrument_sensitivity.value
-> 1340         return paz_to_sacpz_string(paz, sensitivity)
   1341
   1342

/Users/lion/workspace/code/obspy/obspy/core/inventory/response.py in paz_to_sacpz_string(paz, instrument_sensitivity)
   1360     for c in paz.poles:
   1361         out.append(" %+.6e %+.6e" % (c.real, c.imag))
-> 1362     constant = paz.normalization_factor * instrument_sensitivity.value
   1363     out.append("CONSTANT %.6e" % constant)
   1364     return "\n".join(out)

AttributeError: 'float' object has no attribute 'value'
```

**Comment by megies** [comment]
OK, I see. Well this is embarrassing. I added this functionality on request by someone and asked them to please check it out. So much for the urgency of that request back then. Why ask somebody to implement something for you when you'll never ever gonna use it (or even try it)..

**Comment by megies** [comment]
Should be fixed. But this functionality is still untested. Would be good if somebody took the time to contribute a test.

**Comment by lileipku00** [comment]
I compared the results of get_sacpaz() and IRISWS sacpz. They are consistent.

**Comment by megies** [comment]
Hmm.. actually I added test data already in `sac/tests/data/IU_ANMO_00_BHZ.sacpz` and `sac/tests/data/IU_ANMO_BH.sacpz` that can be tested against `station/tests/data/IU_ANMO_00_BHZ.xml` and `station/tests/data/IU_ANMO_BH.xml`.

Just needs a test written down..

**Comment by lileipku00** [comment]
How do I update  in Anaconda the changes in github repository when there is no new release version?

**Comment by megies** [comment]
If you have everything in place to compile ObsPy from source you can..
```bash
$ conda remove obspy
$ pip install https://github.com/obspy/obspy/archive/releases.zip
```

**Comment by lileipku00** [comment]
Could u plz have a look at this?


```
from obspy.fdsn.client import Client

client = Client('ODC')
inv = client.get_stations(network='IV', station='MNO', location='', channel='BHZ', level='response')
resp = inv[0][0][0].response
```
I got the response of a channel and tried to compare the frequency response from PAZ and eval_resp.

`print resp` outputs
```
Channel Response
	From M/S () to None ()
	Overall Sensitivity: 5.03316e+08 defined at 0.200 Hz
	4 stages:
		Stage 1: PolesZerosResponseStage from M/S to V, gain: 400
		Stage 2: CoefficientsTypeResponseStage from V to COUNTS, gain: 1.25829e+06
		Stage 3: FIRResponseStage from COUNTS to COUNTS, gain: 1
		Stage 4: FIRResponseStage from COUNTS to COUNTS, gain: 1
```
and `print resp.get_sacpz()` outputs
```
ZEROS 3
 +0.000000e+00 +0.000000e+00
 +0.000000e+00 +0.000000e+00
 +0.000000e+00 +0.000000e+00
POLES 3
 -8.850000e-01 +8.870000e-01
 -8.850000e-01 -8.870000e-01
 -4.270000e-01 +0.000000e+00
CONSTANT 5.078458e+08
```
If I understand correctly, Stages 1 and 2 are equivalent to the sacpz in this example, and Stages 3 and 4 are the FIRResponseStages not included in sacpz.

but comparing the frequency spectrum from sacpaz (blue) and `resp.plot(0.01, start_stage=1, end_stage=2)` (green) shows that they are not consistent. The amplitude differs by a seemly constant factor and  the phase is significantly different near 0.09Hz.
![1](https://cloud.githubusercontent.com/assets/12648947/10542077/d8f819fe-7415-11e5-9084-9cb7fe28ef56.png)

comparing with the full response stages `resp.plot(0.01)` (red), I understand the difference of amplitude at frequencies near nyquist frequency, but the phase differs from as low as 0.2Hz. In this case, it implies that removing response using poles and zeros is far less sufficient to recover the true phase of the ground motions. I'm not sure it's the problem of the obspy code or the metadata of this channel or everything is correct and this seismometer works indeed like this.
![2](https://cloud.githubusercontent.com/assets/12648947/10542079/dd4fddca-7415-11e5-9cc7-85d3b7c17c91.png)

**Comment by lileipku00** [comment]
The sacpz response (blue line) is calculated by
`scipy.signal.ltisys.zpk2tf()`
and
`scipy.signal.freqs()`
as done by obspy.

**Comment by krischer** [comment]
Can you put the full code you used for the figures here?

sacpz should be equivalent to the first stage but with the overall sensitivity and the normalization factor.

**Comment by lileipku00** [comment]
```

def sacpz2resp(paz, freqs): 
    zeros = paz["zeros"]
    poles = paz["poles"]
    A0 = paz['gain'] * paz['sensitivity']
    b, a = scipy.signal.ltisys.zpk2tf(zeros, poles, A0)
    if not isinstance(a, np.ndarray) and a == 1.0:
        a = [1.0]
    _, h = scipy.signal.freqs(b, a, 2*np.pi*freqs)
    return h    

def plot_resp(freqs, paz):
    resp = sacpz2resp(paz, freqs)

    plt.figure()
    
    ax[0] = plt.subplot(211)
    ax[0].loglog(freqs, abs(resp), **kwargs)
    ax[0].set_ylabel('Amplitude')
    ax[0].grid()
    # plot phase angles
    
    ax[1] = plt.subplot(212)
    phase = np.arctan2(resp.imag, resp.real)
    ax[1].semilogx(freqs, phase, **kwargs)
    yticks = np.arange(-np.pi, 1.1*np.pi, 0.5*np.pi)
    ax[1].set_yticks(yticks)
    ax[1].set_yticklabels([obspy.station.response._pitick2latex(x) for x in yticks])
    ax[1].set_xlabel('Frequency [Hz]')
    ax[1].set_ylabel('Phase (rad)')
    ax[1].grid()
    plt.subplots_adjust(wspace=0.2, hspace=0.02, top=0.87, right=0.82)    
    plt.show()
    return ax
    
f = np.logspace(-2, np.log10(25), 4096)
ax = plot_resp(f, paz)
resp.plot(0.01, start_stage=1, end_stage=2, axes=ax)
resp.plot(0.01, axes=ax)

  ```

**Comment by megies** [comment]
Can you add `obspy.signal.invsim.pazToFreqResp` to the comparison (see http://docs.obspy.org/tutorial/code_snippets/frequency_response.html)? Just to avoid anything coming in there from your low-level use of scipy routines..?

**Comment by lileipku00** [comment]
Here is the comparison plot by replacing my sacpz2resp with the obspy pazToFreqResp. 

sacpz2resp and pazToFreqResp give rise to the same results. In fact, sacpz2resp is just a simple modification of pazToFreqResp. 

paz = {'gain': 1.009,
 'poles': [(-0.885+0.887j), (-0.885-0.887j), (-0.427+0j)],
 'sensitivity': 503316000.0,
 'zeros': [0j, 0j, 0j]}
zeros = paz["zeros"]
poles = paz["poles"]
scale_fac = paz['gain'] * paz['sensitivity']
h, f = obspy.signal.invsim.pazToFreqResp(poles, zeros, scale_fac, 0.02, 4096, freq=False)

![3](https://cloud.githubusercontent.com/assets/12648947/10544340/1ae69fae-7423-11e5-81dd-7f02dc71d04a.png)

=========================================
Another example without FIRResponseStage
```
client = obspy.fdsn.Client('IRIS')
inv = client.get_stations(starttime=UTCDateTime('2015001'), network='IU', station='ANMO', location='00', channel='BHZ', level='response')
print inv[0][0][0].response.get_sacpz()
```
output
```
ZEROS 2
 +0.000000e+00 +0.000000e+00
 +0.000000e+00 +0.000000e+00
POLES 5
 -5.943130e+01 +0.000000e+00
 -2.271210e+01 +2.710650e+01
 -2.271210e+01 -2.710650e+01
 -4.800400e-03 +0.000000e+00
 -7.394060e-02 +0.000000e+00
CONSTANT 2.937713e+14
```
I compared the sacpz with that on IRIS website, they are coincident.
```
paz = {'gain': 86299.5,
 'poles': [(-59.4313+0j),
  (-22.7121+27.1065j),
  (-22.7121-27.1065j),
  (-0.0048004+0j),
  (-0.0739406+0j)],
 'sensitivity': 3404090000.0,
 'zeros': [0j, 0j]}
f = np.logspace(-2, 1, 1024)
ax = plot_resp(f, paz)
resp.plot(0.01, axes=ax)
```
In this example, there is no FIRResponseStage. Two plots are almost the same but still different in amplitude near nyquist frequency.
![0](https://cloud.githubusercontent.com/assets/12648947/10543877/aa55802c-7420-11e5-8e22-f64ba5aabfdc.png)

**Comment by lileipku00** [comment]
Besides, another thing off this topic.

I met serious memory leakage when using `st.remove_response()` in a loop to process thousands of data files.

I commented my codes inside the loop line by line and confirm that it's `remove_response` causing the leakage. But I can't provide further details on which line in `remove_response` made the crime. I'm not familiar enough with debugging ....

**Comment by krischer** [comment]
@lileipku00 I've processed literally hundreds of thousands of files in a loop and this never occured to me. Do by chance also plot something in the loop?

But who know...maybe it occurs know or only on some machines or only with certain responses? evalresp is quite a mess to be honest.

**Comment by krischer** [comment]
But we should definitely track that down. Do you by chance have a small code + data snippets that reproduces that? continuously processing the same file should also trigger the bug if it exists.

**Comment by megies** [comment]
Actually, I also had some issue recently with a memory leak, didn't have time to track it down so far, though.. maybe it's the same reason..

**Comment by lileipku00** [comment]
Sorry it's `simulate(paz_remove=...)` not `remove_response()`. I don't know if `remove_response()` causes leakage or not. But I'm very sure `simulate(paz_remove=...)` does, on different machines, on my local Ubuntu, on the Centos and Fedora servers ...... I checked the program by each time commenting one line.

```
for ist in range(ist1, ist2):
    for iday in range(iday1, iday2):    
        mseedfile = 'XXXXXX'
        if not os.path.isfile(mseedfile): 
            print('\t\tNo data')
            continue
        print '\t\tProcessing "' + mseedfile + '"'
        st = obspy.read(mseedfile, format='mseed')
        st = st.select(sampling_rate=min(100.0, st[0].stats.sampling_rate))        
        st.merge(fill_value=0.0)
        tr = st[0]
        tr.detrend('linear')        
        tr.simulate(paz_remove=paz, water_level=60.0, zero_mean=False, taper_fraction=taper_fraction, pre_filt=pre_filt)
        # and some other things.....
```

Even after I wrapped the processings in the loop into functions, the leakage still happened.

**Comment by lileipku00** [comment]
In the `Note` of the doc of `pazToFreqResp`, it is mentioned that 
```
In order to plot/calculate the phase you need to multiply the complex part by -1. 
```
And it was done like that in the example http://docs.obspy.org/tutorial/code_snippets/frequency_response.html
```
# take negative of imaginary part
phase = np.unwrap(np.arctan2(-h.imag, h.real))
```

but in `obspy.signal.invsim.seisSim`, `freq_response` calculated by `pazToFreqResp` is deconvolved (inversed and then muliplied with signal spectrum) from the signal spectrum. No `negative of imaginary part` is taken.

Do I misunderstand sth?

**Comment by krischer** [comment]
Can somebody produce a smallish example including all data and what not to reproduce the memory leak? I tried for a bit but could not do it. Thanks!

**Comment by lileipku00** [comment]
I'll post it some other day, when I can make the test with some public data and get the leakage reproduced.  I'll keep that in mind. 

We can come back to the topic of sacpz first.

**Comment by megies** [comment]
Yeah, let's drop the mem leak issue here, please open a new ticket for it with a small self-contained example if possible..

**Comment by megies** [comment]
Hmm, the inventory says the instrument is a LE3D-5S. To me it looks a bit strange for that.. e.g. the poles don't match what Lennartz specifies for LE3D-5S in the manual:
```
Poles: (-0.885+0.887j), (-0.885-0.887j), (-0.427+0j)
```
Dunno, maybe you should contact the operators of the station (INGV?)?

**Comment by megies** [comment]
stale, closing.
