### ISSUE TITLE
Fix links in Docs

### ISSUE THREAD

**Issue by krischer** [obspy/obspy#1157]
This page here is pretty bad: http://docs.obspy.org/master/tutorial/code_snippets/retrieving_data_from_datacenters.html

We'll probably have to go through all the pages and check all the links. I guess a lot are invalid since we renamed lots of modules. Can sphinx check automatically?

**Comment by QuLogic** [comment]
Run `linkcheck` during sphinx build? Are you referring to external or internal links?

**Comment by krischer** [comment]
Mostly internal ones but external ones should of course also be checked. I think the linkchecker from sphinx only works for external links. If the cross links cannot be resolved sphinx does not even put an HTML link there so we cannot use an external tool either.

**Comment by krischer** [comment]
This seems to be the solution: http://sphinx-doc.org/config.html?highlight=nitpicky#confval-nitpicky

**Comment by krischer** [comment]
There are also some other issues with the documentation...this page (and likely others) lack a generated plot: http://docs.obspy.org/master/packages/autogen/obspy.signal.interpolation.plot_lanczos_windows.html

**Comment by megies** [comment]
We have several longstanding issues with the docs.. staticmethods not showing up, new "privatized" `_read_...()` functions not showing up etc. etc.

**Comment by megies** [comment]
Should be fixed with 562efcec1983f4c221b314c743f6be16bf00d536.
