### ISSUE TITLE
stream.rotate('NE->RT') is swapping e and n components

### ISSUE THREAD

**Issue by amir-allam** [obspy/obspy#1158]
I acquire data from IRIS via Client, demean, detrend, and deconvolve instrument response. Then I add back_azimuth to each trace and use stream.rotate. The result is wrong and it appears to be that the e and n components have been swapped. In the attached png, magenta is rotation to RT in sac, blue is in matlab, and red is using obspy.signal.rotate_NE_RT directly, passing each trace as an argument. All of these methods match nicely. However, black is the result of stream.rotate('NE->RT'); green is if I swap e and n in the arguments to a matlab rotation script. So, somehow the components are being passed in the wrong order to rotate_NE_RT() when it is called by stream.rotate()
![rotate_compare_obspy](https://cloud.githubusercontent.com/assets/6842748/10769663/bf3499a8-7cac-11e5-908f-29bf31659873.png)

**Comment by megies** [comment]
The expected output is two components (RT), what are you plotting, in each case?

**Comment by amir-allam** [comment]
The radial component. The stream looks like this:
AK.BMR..BHE  | 2009-04-07T20:11:15.360000Z - 2009-04-07T20:17:55.340000Z | 50.0 Hz, 20000 samples
AK.BMR..BHN  | 2009-04-07T20:11:15.360000Z - 2009-04-07T20:17:55.340000Z | 50.0 Hz, 20000 samples
AK.BMR..BHZ  | 2009-04-07T20:11:15.360000Z - 2009-04-07T20:17:55.340000Z | 50.0 Hz, 20000 samples
AK.DIV..BHE  | 2009-04-07T20:11:15.360000Z - 2009-04-07T20:17:55.340000Z | 50.0 Hz, 20000 samples
AK.DIV..BHN  | 2009-04-07T20:11:15.360000Z - 2009-04-07T20:17:55.340000Z | 50.0 Hz, 20000 samples
AK.DIV..BHZ  | 2009-04-07T20:11:15.360000Z - 2009-04-07T20:17:55.340000Z | 50.0 Hz, 20000 samples
...
and so on.

**Comment by avuan** [comment]
SAC automatically reads header variables CMPAZ and CMPINC to detect disorientations in the BHN and BHE channels. If the sensors are correctly oriented the N channel should have CMPAZ=0 AND CMPINC=90 while for E channel CMPAZ=90 AND CMPINC=90. It could be that obspy.rotate assumes N and E of the stream as standard N and E even if in some cases you can have stations that are not oriented as a standard. e.g. BMR station in the AK netwk is rotated 3 deg. from N. Can obspy.rotate manage CMPAZ and CMPINC info or is it necessary to correct for disorientations before using stream.rotate NE--> RT?

**Comment by amir-allam** [comment]
Here, try it yourself. This script shows my whole workflow, and it should produce the following plot. Green is the (correct) radial component that I get when calling obspy.signal.rotate_NE_RT directly with the N and E components. Blue is the incorrect radial component resulting from stream.rotate(). The blue also matches exactly if I call obspy.signal.rotate_NE_RT with the N and E arguments reversed:
![obspy_problem](https://cloud.githubusercontent.com/assets/6842748/10780457/35e5a910-7d03-11e5-8c5c-0d6a10d7e722.png)


import obspy
import numpy as np
import copy
from obspy.fdsn import Client
def make_bulk_list_from_stalist(stations,t1,t2,loc='*',cmp='BH*'):
    """Make a list for use with get_waveforms_bulk"""
    bulk_list=[]
    for net in stations:
        for sta in net:
            bulk_list.append( (net.code,sta.code,loc,cmp,t1,t2) )
    return bulk_list

def sta_limit_distance(ev,stations,min_dist=0,max_dist=100000,ifverbose=False):
    #Remove stations greater than a certain distance from event
    elat=ev.preferred_origin().latitude
    elon=ev.preferred_origin().longitude
    remlist=[]
    for net in stations: #Loop over network and stations
        for sta in net:
            dist,az,baz=obspy.core.util.gps2DistAzimuth(elat,elon,sta.latitude,sta.longitude)
            if dist/1000 < min_dist or dist/1000>max_dist: #Discard station if too far
                remlist.append(sta) #Keep a list of what to discard
        for sta in remlist: #Loop over discard list
            if sta in net.stations: #Not sure why this is needed, but it is
                net.stations.remove(sta)


def time_shift_sac(st,tshift=0):
    """Shift the b and e values in the sac header """
    for tr in st.traces:
        tr.stats.sac['b']=tr.stats.sac['b']+tshift
        tr.stats.sac['e']=tr.stats.sac['e']+tshift

def add_sac_metadata(st,ev=[],stalist=[]):
    """ Add event and station metadata to an Obspy stream"""
    for tr in st.traces: #Loop over each trace
        tr.write('tmppp.sac',format='SAC')#Write each one
        tmptr=obspy.read('tmppp.sac').traces[0]#This is the best way to make sac objects
        for net in stalist: #Loop over all the networks
            for stan in net: #Find the right station
                if tr.stats.station==stan.code:
                    sta=stan #Hopefully there isn't more than one
        tr.stats.sac=tmptr.stats.sac
        #Station info
        tr.stats.sac['stla']=sta.latitude
        tr.stats.sac['stlo']=sta.longitude
        tr.stats.sac['stel']=sta.elevation/1000 #Change to kilometers
        #Event info
        tr.stats.sac['evla']=ev.preferred_origin().latitude
        tr.stats.sac['evlo']=ev.preferred_origin().longitude
        tr.stats.sac['evdp']=ev.preferred_origin().depth/1000
        tr.stats.sac['mag']=ev.preferred_magnitude().mag
        tr.stats.sac['kevnm']=ev.preferred_origin().time.strftime('%Y%m%d%H%M%S%f')[:-3] #!!!!Weird!!!
        #Station-event info
        tr.stats.sac['dist'],tr.stats.sac['az'],tr.stats.sac['baz']=obspy.core.util.gps2DistAzimuth(tr.stats.sac['evla'],tr.stats.sac['evlo'],tr.stats.sac['stla'],tr.stats.sac['stlo'])
        tr.stats.sac['gcarc']=tr.stats.sac.dist*111.19 #Is this right?
        tr.stats.sac['dist']=tr.stats.sac['dist']/1000 #kilometers
        #Now add component info. Fucking obspy should do this but doesn't
        tmp=tr.stats.channel[2]
        tr.stats.sac['cmpinc']=90.0
        tr.stats.sac['cmpaz']=0.0
        if tmp=='E':
            tr.stats.sac['cmpaz']=90.0
        elif tmp=='Z':
            tr.stats.sac['cmpinc']=0.0
        #Now some extra things
        tr.stats.sac['o']=0
        tr.stats.sac['lpspol']=0 #Component isn't left-handed?
        tr.stats.sac['lcalda']=1 #I don't even know
        print tr.stats.station,tr.stats.sac['evlo'],tr.stats.sac['evla'],tr.stats.sac['stlo'],tr.stats.sac['stla'],tr.stats.sac['dist']
    return st


c=Client("IRIS")

network='AK,YV,PS,AV,IU'
evtime=obspy.UTCDateTime("2009-04-07T20:00:00.000")
cat=c.get_events(starttime=evtime-86400,endtime=evtime+86400,minmagnitude=4,minlatitude=60)
ev=cat[0]
before=100
after=300
min_dist=20
max_dist=300
samp_freq=0
ifrotate=False
ifCapInp=True
ifRemoveResponse=True
ifDetrend=True
ifDemean=True
scale_factor=10.0**9
#Set the important event parameters
ev.preferred_origin().time=obspy.UTCDateTime("2009-04-07T20:12:55.351")
ev.preferred_origin().latitude=61.4542
ev.preferred_origin().longitude=-149.7428
evtime=ev.preferred_origin().time
stations=c.get_stations(network=network,starttime=evtime-before,endtime=evtime+after)
sta_limit_distance(ev,stations,min_dist=min_dist, max_dist=max_dist) #Only get stations 200km away
bulk_list=make_bulk_list_from_stalist(stations,evtime-before,evtime+after)
stream=c.get_waveforms_bulk(bulk_list,attach_response=True )#Get seismograms
#Demean, detrend, deconvolve
stream.detrend('demean')
stream.detrend('linear')
pre_filt = (0.005, 0.006, 10.0, 15.0)
stream.remove_response(pre_filt=pre_filt)
stream=add_sac_metadata(stream,ev=ev,stalist=stations)#This assignment probably doesn't work
time_shift_sac(stream,-1*before)
#Now do some QA: throw out traces with missing data
for tr in stream:
    if tr.stats.npts<tr.stats.sampling_rate*(before+after):
        stream.remove(tr)
stream.sort() #Sorted stream makes for structured loop
for tr in stream.traces: #Add backazimuth to metadata in a particular way...
    tr.stats.back_azimuth=tr.stats.sac['baz']
    print tr.stats.station,' backazimuth: ',tr.stats.back_azimuth
    #Do some qc: throw out any stations without three components
    substr=stream.select(station=tr.stats.station)
    if len(substr)<3:
        for subtr in substr:
            print 'One or more components missing: removing ',subtr.stats.station,' ',subtr.stats.channel
            stream.remove(subtr)
nonrot_stream=copy.deepcopy(stream)
stream.rotate('NE->RT')
####Plot output for one station 'AVAL'
import matplotlib.pyplot as plt
plt.ion()
substr=stream.select(station='AVAL',component='R')
tr=substr[0] #Select the radial component
tt=np.arange(len(tr.data))*tr.stats.delta
plt.plot(tt,tr.data)###THIS IS THE INCORRECT ROTATION
plt.xlim((110,125))
####Rotate manually
substr=nonrot_stream.select(station='AVAL',component='N')
n=substr[0]
substr=nonrot_stream.select(station='AVAL',component='E')
e=substr[0]
[r,t]=obspy.signal.rotate_NE_RT(n.data,e.data,e.stats.back_azimuth)
plt.plot(tt,r)###THIS IS THE CORRECT ROTATION
plt.ylim((-.00005,.00005))

**Comment by amir-allam** [comment]
I'm not allowed to post .py files here, but I can email anyone a standalone sript to produce the following plot starting from an IRIS data request. Green is the (correct) radial component resulting from a call directly to obspy.signal.rotate_NE_RT and passing N and E component data. The blue plot is the radial component result of stream.rotate(). It also matches a call to obspy.signal.rotate() with the N and E arguments swapped.
![obspy_problem](https://cloud.githubusercontent.com/assets/6842748/10780493/a86134b4-7d03-11e5-8b40-08fbde6cb81a.png)

**Comment by QuLogic** [comment]
You can enter Python code here enclosed in triple-backticks.

**Comment by amir-allam** [comment]
```import obspy
import numpy as np
import copy
from obspy.fdsn import Client
def make_bulk_list_from_stalist(stations,t1,t2,loc='*',cmp='BH*'):
    """Make a list for use with get_waveforms_bulk"""
    bulk_list=[]
    for net in stations:
        for sta in net:
            bulk_list.append( (net.code,sta.code,loc,cmp,t1,t2) )
    return bulk_list

def sta_limit_distance(ev,stations,min_dist=0,max_dist=100000,ifverbose=False):
    #Remove stations greater than a certain distance from event
    elat=ev.preferred_origin().latitude
    elon=ev.preferred_origin().longitude
    remlist=[]
    for net in stations: #Loop over network and stations
        for sta in net:
            dist,az,baz=obspy.core.util.gps2DistAzimuth(elat,elon,sta.latitude,sta.longitude)
            if dist/1000 < min_dist or dist/1000>max_dist: #Discard station if too far
                remlist.append(sta) #Keep a list of what to discard
        for sta in remlist: #Loop over discard list
            if sta in net.stations: #Not sure why this is needed, but it is
                net.stations.remove(sta)


def time_shift_sac(st,tshift=0):
    """Shift the b and e values in the sac header """
    for tr in st.traces:
        tr.stats.sac['b']=tr.stats.sac['b']+tshift
        tr.stats.sac['e']=tr.stats.sac['e']+tshift

def add_sac_metadata(st,ev=[],stalist=[]):
    """ Add event and station metadata to an Obspy stream"""
    for tr in st.traces: #Loop over each trace
        tr.write('tmppp.sac',format='SAC')#Write each one
        tmptr=obspy.read('tmppp.sac').traces[0]#This is the best way to make sac objects
        for net in stalist: #Loop over all the networks
            for stan in net: #Find the right station
                if tr.stats.station==stan.code:
                    sta=stan #Hopefully there isn't more than one
        tr.stats.sac=tmptr.stats.sac
        #Station info
        tr.stats.sac['stla']=sta.latitude
        tr.stats.sac['stlo']=sta.longitude
        tr.stats.sac['stel']=sta.elevation/1000 #Change to kilometers
        #Event info
        tr.stats.sac['evla']=ev.preferred_origin().latitude
        tr.stats.sac['evlo']=ev.preferred_origin().longitude
        tr.stats.sac['evdp']=ev.preferred_origin().depth/1000
        tr.stats.sac['mag']=ev.preferred_magnitude().mag
        tr.stats.sac['kevnm']=ev.preferred_origin().time.strftime('%Y%m%d%H%M%S%f')[:-3] #!!!!Weird!!!
        #Station-event info
        tr.stats.sac['dist'],tr.stats.sac['az'],tr.stats.sac['baz']=obspy.core.util.gps2DistAzimuth(tr.stats.sac['evla'],tr.stats.sac['evlo'],tr.stats.sac['stla'],tr.stats.sac['stlo'])
        tr.stats.sac['gcarc']=tr.stats.sac.dist*111.19 #Is this right?
        tr.stats.sac['dist']=tr.stats.sac['dist']/1000 #kilometers
        #Now add component info. Fucking obspy should do this but doesn't
        tmp=tr.stats.channel[2]
        tr.stats.sac['cmpinc']=90.0
        tr.stats.sac['cmpaz']=0.0
        if tmp=='E':
            tr.stats.sac['cmpaz']=90.0
        elif tmp=='Z':
            tr.stats.sac['cmpinc']=0.0
        #Now some extra things
        tr.stats.sac['o']=0
        tr.stats.sac['lpspol']=0 #Component isn't left-handed?
        tr.stats.sac['lcalda']=1 #I don't even know
        print tr.stats.station,tr.stats.sac['evlo'],tr.stats.sac['evla'],tr.stats.sac['stlo'],tr.stats.sac['stla'],tr.stats.sac['dist']
    return st


c=Client("IRIS")

network='AK,YV,PS,AV,IU'
evtime=obspy.UTCDateTime("2009-04-07T20:00:00.000")
cat=c.get_events(starttime=evtime-86400,endtime=evtime+86400,minmagnitude=4,minlatitude=60)
ev=cat[0]
before=100
after=300
min_dist=20
max_dist=300
samp_freq=0
ifrotate=False
ifCapInp=True
ifRemoveResponse=True
ifDetrend=True
ifDemean=True
scale_factor=10.0**9
#Set the important event parameters
ev.preferred_origin().time=obspy.UTCDateTime("2009-04-07T20:12:55.351")
ev.preferred_origin().latitude=61.4542
ev.preferred_origin().longitude=-149.7428
evtime=ev.preferred_origin().time
stations=c.get_stations(network=network,starttime=evtime-before,endtime=evtime+after)
sta_limit_distance(ev,stations,min_dist=min_dist, max_dist=max_dist) #Only get stations 200km away
bulk_list=make_bulk_list_from_stalist(stations,evtime-before,evtime+after)
stream=c.get_waveforms_bulk(bulk_list,attach_response=True )#Get seismograms
#Demean, detrend, deconvolve
stream.detrend('demean')
stream.detrend('linear')
pre_filt = (0.005, 0.006, 10.0, 15.0)
stream.remove_response(pre_filt=pre_filt)
stream=add_sac_metadata(stream,ev=ev,stalist=stations)#This assignment probably doesn't work
time_shift_sac(stream,-1*before)
#Now do some QA: throw out traces with missing data
for tr in stream:
    if tr.stats.npts<tr.stats.sampling_rate*(before+after):
        stream.remove(tr)
stream.sort() #Sorted stream makes for structured loop
for tr in stream.traces: #Add backazimuth to metadata in a particular way...
    tr.stats.back_azimuth=tr.stats.sac['baz']
    print tr.stats.station,' backazimuth: ',tr.stats.back_azimuth
    #Do some qc: throw out any stations without three components
    substr=stream.select(station=tr.stats.station)
    if len(substr)<3:
        for subtr in substr:
            print 'One or more components missing: removing ',subtr.stats.station,' ',subtr.stats.channel
            stream.remove(subtr)
nonrot_stream=copy.deepcopy(stream)
stream.rotate('NE->RT')
####Plot output for one station 'AVAL'
import matplotlib.pyplot as plt
plt.ion()
substr=stream.select(station='AVAL',component='R')
tr=substr[0] #Select the radial component
tt=np.arange(len(tr.data))*tr.stats.delta
plt.plot(tt,tr.data)###THIS IS THE INCORRECT ROTATION
plt.xlim((110,125))
####Rotate manually
substr=nonrot_stream.select(station='AVAL',component='N')
n=substr[0]
substr=nonrot_stream.select(station='AVAL',component='E')
e=substr[0]
[r,t]=obspy.signal.rotate_NE_RT(n.data,e.data,e.stats.back_azimuth)
plt.plot(tt,r)###THIS IS THE CORRECT ROTATION
plt.ylim((-.00005,.00005))
```

**Comment by QuLogic** [comment]
That is very long, and downloads several waveforms. Can you please shorten it to just 3 or 4 traces?

**Comment by megies** [comment]
```python
import matplotlib.pyplot as plt 
from obspy import read

st = read()
for tr in st: 
    tr.stats.back_azimuth = 91.5
st.rotate('NE->RT')

st += read()

plt.figure()
plt.subplot(211)
plt.plot(-1 * st.select(component="E")[0].data, label="-E")
plt.plot(st.select(component="R")[0].data, label="R")
plt.legend()
plt.subplot(212)
plt.plot(st.select(component="N")[0].data, label="N")
plt.plot(st.select(component="T")[0].data, label="T")
plt.legend()
plt.show()
```

Backazimuth 91.5°, so source east of station. Radial away from source, so West is positive. Transversal equal to North. Looks good to me.

![figure_1](https://cloud.githubusercontent.com/assets/1842780/10782104/bd8376dc-7d4d-11e5-9a38-c372f224775b.png)

**Comment by QuLogic** [comment]
Ping @amir-allam?

**Comment by amir-allam** [comment]
Yes?

**Comment by QuLogic** [comment]
Can you provide a shorter example, or is @megies correct in that there is nothing wrong?

**Comment by megies** [comment]
No further replies received, so closing this one, assuming that the provided code was just doing something wrong.
