### ISSUE TITLE
Numpy Array in stats generates error in Trace.__eq__

### ISSUE THREAD

**Issue by trichter** [obspy/obspy#1159]
Sometimes it is handy to quickly attach a numpy array to stats.

I don't know if this is not recommended and hence not supported or if the error in the following code should be considered a bug.

    In [1]: import numpy as np
    In [2]: from obspy.core import Trace
    In [3]: tr = Trace()
    In [4]: tr.stats.stuff = np.array([0,1])
    In [6]: tr2 = tr.copy()
    In [7]: tr == tr2
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-7-ca266852e6c5> in <module>()
    ----> 1 tr == tr2
    /home/richter/anaconda/lib/python2.7/site-packages/obspy-0.10.2-py2.7-linux-x86_64.egg/obspy/core/trace.pyc in __eq__(self, other)
        303             return False
        304         # comparison of Stats objects is supported by underlying AttribDict
    --> 305         if not self.stats == other.stats:
        306             return False
        307         # comparison of ndarrays is supported by NumPy

    /home/richter/anaconda/lib/python2.7/_abcoll.pyc in __eq__(self, other)
        424         if not isinstance(other, Mapping):
        425             return NotImplemented
    --> 426         return dict(self.items()) == dict(other.items())
        427 
        428     def __ne__(self, other):

    ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by megies** [comment]
Hmm, dunno.. in any case, you can attach your array directly to the tr without equality check hickups..

**Comment by trichter** [comment]
That's right. Thanks for this hint. In this case its probably not worth fixing as stats is intended for metadata and not data. Attaching lists to stats is working anyway.

**Comment by megies** [comment]
If you have a proposed change let us know. Closing for now..
