### ISSUE TITLE
ipython notebook import problem

### ISSUE THREAD

**Issue by maratumba** [obspy/obspy#1165]
I installed a few packages and obspy is now broken. Not sure what went wrong. 
I installed ipython notebook, pandas, jsonschema via pip on osX 10.9.5

When I try to import obspy 10.2.0 in ipython, I get an error about numpy version. (``numpy.__version__`` is 1.8.0)

the following is a notebook output but the result is the same in ipython and python consoles:

```python
import obspy
```

    ---------------------------------------------------------------------------

    DistributionNotFound                      Traceback (most recent call last)

    <ipython-input-3-6960ca51d676> in <module>()
    ----> 1 import obspy

    /Library/Python/2.7/site-packages/obspy/__init__.pyc in <module>()
         45 from obspy.core.util.base import make_format_plugin_table
         46 read.__doc__ = \
    ---> 47     read.__doc__ % make_format_plugin_table("waveform", "read", numspaces=4)
         48 readEvents.__doc__ = \
         49     readEvents.__doc__ % make_format_plugin_table("event", "read", numspaces=4)

    /Library/Python/2.7/site-packages/obspy/core/util/base.pyc in make_format_plugin_table(group, method, numspaces, unindent_first_line)
        474         module_short = ":mod:`%s`" % ".".join(ep.module_name.split(".")[:2])
        475         func = load_entry_point(ep.dist.key,
    --> 476                                 "obspy.plugin.%s.%s" % (group, name), method)
        477         func_str = ':func:`%s`' % ".".join((ep.module_name, func.__name__))
        478         mod_list.append((name, module_short, func_str))

    /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.pyc in load_entry_point(dist, group, name)
        316 def load_entry_point(dist, group, name):
        317     """Return `name` entry point of `group` for `dist` or raise ImportError"""
    --> 318     return get_distribution(dist).load_entry_point(group, name)
        319
        320 def get_entry_map(dist, group=None):

    /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.pyc in load_entry_point(self, group, name)
       2219         if ep is None:
       2220             raise ImportError("Entry point %r not found" % ((group,name),))
    -> 2221         return ep.load()
       2222
       2223     def get_entry_map(self, group=None):

    /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.pyc in load(self, require, env, installer)
       1951
       1952     def load(self, require=True, env=None, installer=None):
    -> 1953         if require: self.require(env, installer)
       1954         entry = __import__(self.module_name, globals(),globals(), ['__name__'])
       1955         for attr in self.attrs:

    /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.pyc in require(self, env, installer)
       1964             raise UnknownExtra("Can't require() without a distribution", self)
       1965         map(working_set.add,
    -> 1966             working_set.resolve(self.dist.requires(self.extras),env,installer))
       1967
       1968

    /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.pyc in resolve(self, requirements, env, installer)
        563                     dist = best[req.key] = env.best_match(req, self, installer)
        564                     if dist is None:
    --> 565                         raise DistributionNotFound(req)  # XXX put more info here
        566                 to_activate.append(dist)
        567             if dist not in req:

    DistributionNotFound: numpy>=1.4.0

```python

```

**Comment by megies** [comment]
> I installed a few packages

How? Details?

Looks like two colliding numpy installations, or maybe a new numpy installation on top of an (possibly broken) old one? Who knows..?

**Comment by maratumba** [comment]
> I installed ipython notebook, pandas, jsonschema via pip on osX 10.9.5

**Comment by maratumba** [comment]
I used `--delete-conflicting` option of `easy_install` for `numpy` and the problem seems to be solved for now.
