### ISSUE TITLE
Confusing about the timeout argument in obspy.fdsn.client

### ISSUE THREAD

**Issue by lileipku00** [obspy/obspy#1171]
The parameter `timeout` is the max seconds to waiting the response from the server or the max time length to finish all the data transferring?

**Comment by krischer** [comment]
Yea you are right...the documentation is wrong. Its a web timeout, e.g. the time after the request was sent until the first byte of the response arrives. I'll fix it.

**Comment by lileipku00** [comment]
Yeah. so the timeout is normal.

But is it too large to set a default value of 120s?

**Comment by krischer** [comment]
> But is it too large to set a default value of 120s?

In most cases yes but some web services take a long time to respond. This is especially a problem for the bulk data requests. I think some web services just collect all the data locally before they start sending it ...

So yeah - its way too large for a well behaving web service but not all are well behaved - but the situation has much improved in the last years.

**Comment by krischer** [comment]
Fixed in 819d05c3b06db378ad34d931f83073ed56619286.

**Comment by krischer** [comment]
Thanks for reporting!
