### ISSUE TITLE
PSD values to database

### ISSUE THREAD

**Issue by Jollyfant** [obspy/obspy#1172]
At ORFEUS we are developing a webservice that can calculate PPSDs on the fly from a database of PSD values calculated per day (48 segments).

For this we require to bin the spectral values at periods on a pre-determined interval from 0.001 to  1000 (at every 1/8th octave), so that we can easily store and add the spectral values for different sampling rates (normally the first and last period values are determined by a dummy PSD during _setup of the class, with a min/max period as a function of sampling rate). However, we want to choose or own minimum/maximum that is always the same.

I have modified the code of the PPSD class tailored to our needs, but perhaps it is also interesting  to the community. The main change is that the class no longer uses a dummy PSD during **_setup**. Instead the class sets up the period bins after the real spectral values have been calculated for one segment. The replacement for **_setup** is **_setup_period_bins** function and has arguments (minimum / maximum). Default functionality can be recovered by passing the first/last period through min/max. Some other changes had to be made for this code to be compatible with the rest of the class.

What are your thoughts on this changes? If you're interested I create a pull request so you can evaluate the proposed changes.

Additionally, we implemented a method to parse the current_histogram to a mongodb format, but this is very specific to our needs.

**Comment by megies** [comment]
Right now (and in the last weeks/months) there were pretty drastic internal changes in PPSD and I'm not completely done yet, hope to do the final touches in the next few days. This needs to wait until I get #1166 (further refactoring and cleanup) ready and merged.

But it's not quite clear to me so far what you use the PPSD class for anyway.. do I understand correctly that the psd pieces are precalculated outside of PPSD and that you use PPSD only for the binning/histogram plot?

Anyway, would be good if you push your changes to a branch in your obspy fork on github, then I can have a look at what you need and might be able to add it to PPSD so that you eventually don't need to keep a patched version around at the data center.

**Comment by Jollyfant** [comment]
Hi Megies, I noticed you are busy updating the class and worked on the newest commit. Sorry I was not clear in my explanation. We are using the PPSD class to calculate PSD values for full days (a histogram of 48 segments), and storing those in a database. From this, we want to create larger PPSDs (weeks, months, years) on the fly, by reading daily PSDs from the database and adding them (without having to use ObsPy again).

The main focus is on removing the dummy PSD and calculating the period bins at a later stage (between a user specified min/max instead of between the minimum and maximum period returned by the dummy PSD.

Here is a commit with the changes:
https://github.com/Jollyfant/obspy/commit/d050e9380cc9966cb32c5d06a3669c6f4cbd52fe

Some parameters (e.g. psd_date) will be used internally to determine what day a given PSD belongs to, and may not be suitable for the general class.

**Comment by megies** [comment]
OK, I'll have a look in the next days..

So if you're able to specify custom period/frequency edges of the smoothing and binning at `__init__()` would that be sufficient (I'm a bit confused by `..at a later stage..`)?

One more question to clarify your needs (I assume you saw that I changed the PPSD to store individual smoothed psd instead of histogram stacks):
If I understand correctly, what you store in DB is a 2D period/amplitude histogram stack of a single day? If that's the case I think it would be better to use the new mechanism of storing single smoothed psd in DB, that would allow more fine grained custom stacks by time of day later and takes even less space in the DB, and it would work smoother with the whole PPSD setup, most likely.

**Comment by Jollyfant** [comment]
Yes, specifying them at __init__() would be sufficient. However, setting up the bins during __init__ using a dummy PSD felt like a non-desired solution (despite that it works). Therefore, I preferred to do it "at a later stage" after real spectral values are calculated in __process, and not dummy values. But this is not a necessary change.

We would like to store daily PSDs because a 2D period/amplitude histogram calculated for a day is cheaper than storing all values for separate 48 segments. I do not quite understand how it would take less space? It would naturally be preferable to store all segments individually.

**Comment by megies** [comment]
> Yes, specifying them at init() would be sufficient. However, setting up the bins during init using a dummy PSD felt like a non-desired solution (despite that it works). Therefore, I preferred to do it "at a later stage" after real spectral values are calculated in __process, and not dummy values. But this is not a necessary change.

OK, I'll add the possibility to use user-specified min/max periods at `__init__()`, I have already added the possibility to use different smoothing width (PQLX 1 full octave) and step width in period range (aka histogram bin width; PQLX 1/8 octave) already anyway, so it only makes sense to allow control over the left/right end of the histogram (although in that the right most period bin might have a different width than the others).

> We would like to store daily PSDs because a 2D period/amplitude histogram calculated for a day is cheaper than storing all values for separate 48 segments. I do not quite understand how it would take less space? It would naturally be preferable to store all segments individually.

Well, in the histogram for one day you store roughly `200 (amplitude bins) * 200 (period bins) == 40000` integer values for one day, roughly 90% of them zeros. If you instead store the amplitude bin number of the smoothed psd for each of the segments you end up with roughly `48 (no. of segments) * 200 (period bins) == 9600` integer values, so only 1/4 of storage, plus the chance for finer grained stacks. (Depending on how many bins you want on the amplitude axis.. for a PQLX style plot with 1db bins from -200 to -50 dbs, even a `uint8` going from 0-255 would be sufficient to store -- if that type exists in your DB)

**Comment by krischer** [comment]
Besides the scope of ObsPy so just a comment from my side.

> If you have any suggestions let me know.

Assuming you want to do this for A LOT of stations I guess the best way to store these kind of things would be an actual array database, e.g. something like rasdaman or SciDB. They can also do the stacking/statistics/... inside the database.

They are also made to work with really large amounts of data so I no reason to not store however many segments you want. And disc space is cheap.

**Comment by Jollyfant** [comment]
@megies 
That is true, and would be a good solution. In the db structure we would also like to support queries that filter PSDs (and the associated data) for a given period does not exceed a certain amplitude (so applied as quality control). That is a little complication for us in just storing an array. But I understand what you meant, thanks.

@krischer 
Thanks, I will definitely have a look in to that as well.

**Comment by megies** [comment]
> In the db structure we would also like to support queries that filter PSDs (and the associated data) for a given period does not exceed a certain amplitude (so applied as quality control). That is a little complication for us in just storing an array. But I understand what you meant, thanks.

..and that's easier when storing the 2D stack? I don't understand that part, but don't need to either, I guess.. ;-)

**Comment by ltrani** [comment]
>  I guess the best way to store these kind of things would be an actual array database, e.g. something like rasdaman or SciDB. 

Good suggesiton Lion! Indeed I am going to talk also about this in a dedicated session (track 3) here https://eudat.eu/events/eudat-first-working-groups-workshop-12-13-november-2015-barcelona-spain

**Comment by megies** [comment]
One more question.. do you plan to query the DB for certain features on the PSDs across channels? Or only for a single channel every time (to do a PPSD plot for that channel)?

Just a thought.. the PPSD data for a single channel for one year is roughly 7MB, so no problem to read/save with numpy in no time to reuse directly in obspy (e.g. to make plots).
But I guess you want to query the PSD data also from different QC modules etc.?

**Comment by Jollyfant** [comment]
We want to give the user as much freedom as possible, so querying multiple channels should be a possibility. In the end, it should be used as a QC service. For example, a query could be: exclude all data that has an amplitude above -70 dB between 0.01s and 1s.

**Comment by megies** [comment]
Yeah, that's what I thought, so you need the DB behind it.
Because if it was only about making PPSD plots per channel for custom stacks, just (de)serializing with numpy, and doing everything with ObsPy would probably be easiest.

**Comment by megies** [comment]
With your custom set period limits, you will end up with `nan` values in the smoothed psd segments. With the current implementation of the histogram binning (based on `np.searchsorted` among other routines this means that all `nan` values end up in the top-most bin, see top edge in plot). Furthermore, when you push the psd segments into the DB, you will have to handle `np.nan` values in those arrays.
For me that's not a big issue, but let me know if this will be a problem or what's your take on this.

![figure_1](https://cloud.githubusercontent.com/assets/1842780/11118414/0d39797e-8942-11e5-86cc-b4578ce5358f.png)

**Comment by Jollyfant** [comment]
Hi Megies, that is looking good! If I understand correctly this means that for a given minimum/maximum the `spec_octaves` (center of period bins) will always be at the same position? Regardless of sampling rate?

The evaluation to NaN is not necessarily a problem. In my commit I circumvented this behavior by saving an array of `used_periods`, that is the center of period bins with a value in them (see code), and later loop over this array gathering all values in order.

```
for per_center, per_left, per_right in zip(self.per_octaves, 
                                           self.per_octaves_left, 
                                           self.per_octaves_right):
    if(len(specs) != 0):
        spec_center = specs.mean()
        spec_octaves.append(spec_center)
        used_periods.append(per_center)

**Comment by megies** [comment]
> If I understand correctly this means that for a given minimum/maximum the spec_octaves (center of period bins) will always be at the same position? Regardless of sampling rate?

Yes, the binning/smoothing on the period axis is solely controlled by
 - min/max period range (default is determined as min/max periods of dummy psd, or now optionally user set)
 - step width (i.e. pixel width in plot)  -- as fraction of octave (default 1/8 like PQLX)
 - smoothing width -- as fraction of octave (default one full octave like PQLX)

All of this can now be user controlled during `__init__()` (I'm gonna push my commits to #1166 in some minutes).



> In my commit I circumvented this behavior by saving an array of used_periods, that is the center of period bins with a value in them (see code), and later loop over this array gathering all values in order.

see https://github.com/Jollyfant/obspy/commit/d050e9380cc9966cb32c5d06a3669c6f4cbd52fe#commitcomment-14356474

**Comment by Jollyfant** [comment]
That is exactly what we need. But I don't understand what you mean by smoothing width? I thought the period bin centers are only determined by the first two items you listed (during __init__).

Do you mean the `_period_bin_centers`? Because for now I have been using the `per_octaves` as the period value for which to save the amplitudes.

+ I responded to your line comment.

**Comment by megies** [comment]
> what you mean by smoothing width

The step width is the width of a pixel in the histogram, but the psd is smoothed over a much broader range. In that respect those PQLX plots are a bit misleading..

**Comment by Jollyfant** [comment]
Mhm, so do you think it is fine to use the `per_octaves` periods as representative values of the spectral values that are stored? They should be midway of a a period bin.

**Comment by megies** [comment]
Should be OK. More correct would be to store start/end of the smoothing window, but that's a bit awkward to handle I guess and doesn't bring much advantages.
I'm also cleaning up access to these arrays via getter properties with sensible names right now.. so you'll want to access `ppsd.period_bin_centers` from now on. :-)

**Comment by megies** [comment]
So, I think this can be closed, right? The mongoDB stuff can be implemented on your end, either by subclassing obspy PPSD or by just defining a function that takes PPSD object as an argument..

**Comment by Jollyfant** [comment]
This issue can be closed. We have an implementation for mongo ready. Thanks very much for your help.
