### ISSUE TITLE
Easier way of adding format-specific metadata to Trace objects

### ISSUE THREAD

**Issue by claudiodsf** [obspy/obspy#1178]
Format-specific metadata in `Trace` objects is stored into ad-hoc `AttribDicts`, like, for instance, `Trace.stats.sac`.

If one wants to save a trace object into a specific file format and use this format-specific metadata, one has to create this `AttribDict`. Suppose, for instance, that one wants to generate a synthetic trace, and save it in SAC format using some SAC-specific header field, e.g. (dummy example):

``` python
from obspy import Trace
from obspy.core import AttribDict
import numpy as np

tr = Trace(np.random.random(100))
tr.stats.sac = AttribDict()
tr.stats.sac.a = 10.
tr.write('dummy.sac', format='SAC')
```

This is cumbersome because it requires the user to know an ObsPy internal: the `AttribDict()` class.

It would be nice to be able to create an empty `AttribDict` when trying to access certain `stats` fields for the first time. 

This could be achieved by adding to the `Trace()` class, alongside the existing `defaults` attributes, some "optional" attributes, like, e.g.:

``` python
    defaults = {
        'sampling_rate': 1.0,
        'delta': 1.0,
        'starttime': UTCDateTime(0),
        'endtime': UTCDateTime(0),
        'npts': 0,
        'calib': 1.0,
        'network': '',
        'station': '',
        'location': '',
        'channel': '',
    }
    options = {
        'ah': AttribDict(),
        'ascii': AttribDict(),
        'mseed': AttribDict(),
        'sac': AttribDict(),
    }
```

(just to name a few examples), and then adding something like this in `AttribDict.__getitem__()`:

``` python
    def __getitem__(self, name, default=None):
        try:
            return self.__dict__[name]
        except KeyError:
            # check if we got any default value given at class level
            if name in self.defaults:
                return self.defaults[name]
            if name in self.options:
                self.__setitem__(name, self.options[name])
                return self.options[name]
            # if both are missing check for a given default value
            if default is None:
                raise
            return default
```

I'm not proposing a pull request here, because I'm not sure if this is the best possible implementation (tough it works). It also looks like the list of optional `stats` attributes could be defined in `setup.py` based on the waveform plugins.

What do you think?

**Comment by megies** [comment]
> This is cumbersome because it requires the user to know an ObsPy internal: the AttribDict() class.

Using a simple `dict` works just the same, we just use `Attribdict` for convenient possibility to access attributes with dot-notation.

I'm not sure about this proposal, I think it might lead to even more confusion, and after all if you follow through with this you would end up with ~20 empty stub dictionaries for every file format..?

**Comment by claudiodsf** [comment]
> Using a simple dict works just the same, we just use Attribdict for convenient possibility to access attributes with dot-notation.

That's true.

> I'm not sure about this proposal, I think it might lead to even more confusion

Why might it lead to more confusion?

> and after all if you follow through with this you would end up with ~20 empty stub dictionaries for every file format..?

Actually, implementing it differently, `options` could be a list of keywords (`['ah', 'ascii', 'mseed', 'sac', ...]`), and the empty `AttribDict()` object could be generated, when requested by `AttribDict.__getitem__()`:

```python
    def __getitem__(self, name, default=None):
        try:
            return self.__dict__[name]
        except KeyError:
            # check if we got any default value given at class level
            if name in self.defaults:
                return self.defaults[name]
            if name in self.options:
                self.__setitem__(name, AttribDict())
                return self.__getitem__[name]
            # if both are missing check for a given default value
            if default is None:
                raise
            return default
```

Anyway, let's see what are other people's thoughts on this...

**Comment by krischer** [comment]
I think we should rather just convert attributes that are dictionaries to `AttribDict`, e.g.:

```python
def __setitem__(self, name, value):
    if isinstance(value, dict):
        value = AttribDict(value)
    ...
```

**Comment by claudiodsf** [comment]
@krischer that seems a good solution, allowing, e.g., for:

```python
tr.stats.sac = []
tr.stats.sac.a = 10.
```

:+1:

**Comment by megies** [comment]
> I think we should rather just convert attributes that are dictionaries to AttribDict, e.g.:

might be excessive automagic.. `AttribDict` and `dict` are likely not behaving 100% the same in some respects so this could lead to unexpected behavior. But maybe just paranoid..

**Comment by trichter** [comment]
> I think we should rather just convert attributes that are dictionaries to AttribDict

```
In [11]: tr.stats.sac = {}                                                      
In [12]: tr.stats.sac.a = 10                                                    
In [13]: tr.stats.sac                                                           
Out[13]: AttribDict({'a': 10})
```

Apparently, this was implemented in the meantime.
