### ISSUE TITLE
CMTSOLUTION write out the leading zero

### ISSUE THREAD

**Issue by wjlei1990** [obspy/obspy#1190]
I am using obspy to read and write CMTSOLUTION.

But I found when obspy write out the CMTSOLUTION file, it writes out the leading zero. For example, the original CMT file is:
```
 PDE 2005  2 15 14 42 25.90   4.7600  126.4200  39.7 6.1 6.0 TALAUD ISLANDS, INDONESIA
event name:     C200502151442A
time shift:      6.3000
half duration:   4.4000
latitude:        4.8000
longitude:     126.6600
depth:          56.8000
Mrr:       2.310000e+25
Mtt:      -5.890000e+24
Mpp:      -1.720000e+25
Mrt:       1.120000e+25
Mrp:       5.970000e+25
Mtp:      -2.910000e+25
```

For the same file written out by obspy:
```
 PDE 2005 02 15 14 42 25.90    4.7600  126.4200  39.7 6.1 6.0 TALAUD ISLANDS, INDONESIA
event name:   C200502151442A
time shift:           6.3000
half duration:        4.4000
latitude:             4.8000
longitude:          126.6600
depth:               56.8000
Mrr:            2.310000E+25
Mtt:           -5.890000E+24
Mpp:           -1.720000E+25
Mrt:            1.120000E+25
Mrp:            5.970000E+25
Mtp:           -2.910000E+25
```
For the month, it has the leading zero. And I have checked the global cmt website, there is no leading zero.

I think it might be good to keep them the same. But shouldn't be a big problem for most of other applications.

**Comment by QuLogic** [comment]
There's not really a good definition of the `CMTSOLUTION` files, so I guess the only real reference is pulling something off http://www.globalcmt.org/. The default search result is actually pretty good because it's 1976/1/1 and it shows that there's no leading zero. @krischer I see that you specifically added the leading zero in separate commit; what was the reason for it?

**Comment by krischer** [comment]
I honestly don't remember. I also don't have any strong feelings in this manner so if you two believe it should have no leading zeros then I'll remove them. It looks a bit cleaner with leading zeros but its a messy format in any case.

**Comment by wjlei1990** [comment]
I will be like to delete the leading zero :)

**Comment by krischer** [comment]
I was just about to implement this and stumbled upon this test example which might be the reason why I chose to have leading zeros.

#### Current Version:

```
 PDE 1999 01 01 00 00 00.00   46.1970 -122.1860 250.0 4.2 4.2 WASHINGTON
event name:    hom_explosion
```

#### Possibilities to Remove Leading Zeroes:

```
 PDE 1999  1  1  0  0  0.0    46.1970 -122.1860 250.0 4.2 4.2 WASHINGTON
event name:    hom_explosion
```

```
 PDE 1999  1  1  0  0 00.00   46.1970 -122.1860 250.0 4.2 4.2 WASHINGTON
event name:    hom_explosion
```

```
 PDE 1999  1  1  0  0  0.00   46.1970 -122.1860 250.0 4.2 4.2 WASHINGTON
event name:    hom_explosion
```

I think the current version looks by far the cleanest - but as I said: I have no strong feeling so just let me know what you prefer.

**Comment by wjlei1990** [comment]
Let me test on specfem. I think it shouldn't be a problem at all(won't affect the result)...

**Comment by krischer** [comment]
I'm pretty sure they all work - otherwise I would consider it a bug in specfem. I think its just an aesthetic choice.

**Comment by krischer** [comment]
Is this solved? I assume the leading zero works with SPECFEM?

**Comment by wjlei1990** [comment]
Confirmed. Specfem is happy with it.

I also checked the specfem code to read the CMTSOLUTION file:
https://github.com/geodynamics/specfem3d_globe/blob/master/src/specfem3D/get_event_info.f90#L166

As long as the value are seperated by space, should not be a problem.
