### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by bonaime** [obspy/obspy#1193]
On the footer of this page
https://docs.obspy.org/

the "ObsPy Development Team " link points to
https://github.com/orgs/obspy/members
which does not exists

It should be instead
https://github.com/orgs/obspy/people
or
https://github.com/obspy/obspy/graphs/contributors
or
https://github.com/obspy/obspy/network/members

**Comment by megies** [comment]
That was fixed on master some days/weeks ago.. (see https://docs.obspy.org/master) but thanks for letting us know.
