### ISSUE TITLE
Mars models don't work with obspy.taup

### ISSUE THREAD

**Issue by krischer** [obspy/obspy#1200]
This model for example does not work with the current master: https://dl.dropboxusercontent.com/u/3866312/taup_models/original/mars.tvel

There are just a couple of code paths and assumptions that are not tested and it should be fairly simple to fix. For example the code currently is only tested with a solid core. I fixed a couple of things but then decided to wait until #1189 is done so it does not have to be done twice.

**Comment by QuLogic** [comment]
Does this model work with the Java version?

**Comment by krischer** [comment]
I just checked - once I added two comment lines up top but then yes. I just updated the file linked above.

```bash
$ ./taup_time --ph P -sta 0 0 -evt 10 10 -mod mars.taup

Model: mars
Distance   Depth   Phase   Travel    Ray Param  Takeoff  Incident  Purist    Purist
  (deg)     (km)   Name    Time (s)  p (s/deg)   (deg)    (deg)   Distance   Name
-----------------------------------------------------------------------------------
   14.11     0.0   P        108.32     7.175     34.10    34.10    14.11   = P
```

With #1199 the model parsing gets a bit further along but does not finish.

**Comment by megies** [comment]
This hasn't seen any activity, so I'll bump this to 1.2.0.

**Comment by megies** [comment]
I think it's time to close this
