### ISSUE TITLE
"blockette type 42" error

### ISSUE THREAD

**Issue by sbonaime** [obspy/obspy#1203]
With this script and  Obspy 10.2

``` code
from obspy.arclink.client import Client
from obspy.xseed import Parser
from obspy import UTCDateTime

t=UTCDateTime()
client = Client(user='test@obspy.org')
client.saveResponse('/tmp/ROCAM.LKI.obspy.dataless','G','ROCAM','*','LKI', t,t + 1, format="SEED")
sp=Parser('/tmp/ROCAM.LKI.obspy.dataless')
```

I have this error

``` error
Unknown blockette type 42
```

There are some channels in Geoscope dataless which use blockette 62 but not blockette 42.

Using arclink_fectch I can download a dataless for the same channel which does not contain blockette 42.

I don't think that Obspy creates some blockette 42 at some point. And I don't understand that Arclink server sends different dataless to obspy and arclink_fetch

**Comment by barsch** [comment]
Blockette 42 is not implemented yet, see https://github.com/obspy/obspy/tree/master/obspy/io/xseed/blockette

**Comment by bonaime** [comment]
Yes but there are no blockette 42 in Geoscope dataless !
```code
wget http://geoscope.ipgp.fr/metadata/G/dataless.G.ROCAM.seed
rdseed -Rf dataless.G.ROCAM.seed
<< IRIS SEED Reader, Release 5.3.1 >>
	R = print response data (with addressing for evresp)
	Taking input from dataless.G.ROCAM.seed
Writing RESPONSE file: RESP.G.ROCAM.00.BHE
Writing RESPONSE file: RESP.G.ROCAM.00.BHE
Writing RESPONSE file: RESP.G.ROCAM.00.BHN
Writing RESPONSE file: RESP.G.ROCAM.00.BHN
Writing RESPONSE file: RESP.G.ROCAM.00.BHZ
Writing RESPONSE file: RESP.G.ROCAM.00.BHZ
Writing RESPONSE file: RESP.G.ROCAM.00.HHE
Writing RESPONSE file: RESP.G.ROCAM.00.HHN
Writing RESPONSE file: RESP.G.ROCAM.00.HHZ
Writing RESPONSE file: RESP.G.ROCAM.00.LHE
Writing RESPONSE file: RESP.G.ROCAM.00.LHE
Writing RESPONSE file: RESP.G.ROCAM.00.LHN
Writing RESPONSE file: RESP.G.ROCAM.00.LHN
Writing RESPONSE file: RESP.G.ROCAM.00.LHZ
Writing RESPONSE file: RESP.G.ROCAM.00.LHZ
Writing RESPONSE file: RESP.G.ROCAM.00.VHE
Writing RESPONSE file: RESP.G.ROCAM.00.VHN
Writing RESPONSE file: RESP.G.ROCAM.00.VHZ
Writing RESPONSE file: RESP.G.ROCAM.00.LDI
Writing RESPONSE file: RESP.G.ROCAM.00.LKI
bonaime@geok:/tmp/tt$ grep "BO42" *
bonaime@geok:/tmp/tt$
````
So it should be an arclink server problem ?

**Comment by megies** [comment]
That it's not in RESP output doesn't necessarily mean that it's not in the dataless, RESP is only a subset of dataless SEED.

**Comment by barsch** [comment]
adding ```debug=True``` to the parser shows more info about the parsing process - however I don't see it ..

**Comment by barsch** [comment]
oh and looking at the file in a hex editor shows a blockette 42 - so its in the file ...

**Comment by bonaime** [comment]
When I download dataless from web site (wget http://geoscope.ipgp.fr/metadata/G/dataless.G.ROCAM.seed), there is no blockette 42:
```code
from obspy.xseed import Parser

p=Parser("./dataless.G.ROCAM.seed")
b=p.blockettes

In [5]: b[42]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-c0080ef6a990> in <module>()
----> 1 b[42]

KeyError: 42
```
And there is no problem with the Parser as there is no blockette 42

When I download what should be the same dataless with
```code
from obspy.arclink.client import Client
from obspy.xseed import Parser
from obspy import UTCDateTime

t=UTCDateTime()
client = Client(user='test@obspy.org')
client.saveResponse('/tmp/ROCAM.LKI.obspy.dataless','G','ROCAM','*','LKI', t,t + 1, format="SEED")
sp=Parser('/tmp/ROCAM.LKI.obspy.dataless')
````
I have an error because this dataless has a blockette 42.

I think it should be an arclink server problem

**Comment by barsch** [comment]
its not an ArcLink issue as both seem to be valid dataless SEED files - they seem to have different dataless files on the webserver and in the ArcLink archive - you should contact the network operators to solve this issue

also it shouldn't be big issue to introduce blockette 42 to obspy ... a missing test case was probably the only reason it wasn't implemented yet - so now we have one ;)

**Comment by megies** [comment]
`Blockette 42 – Response Polynomial Dictionary.` if it's in one metadata set but not in the other I can only think of a sensor that is in one but not the other..

**Comment by bonaime** [comment]
I found the problem !
Arclink server (I think) default behavior is to use response dictionary by default. Even if the original dataless does not contain response dictionary. In that case a response dictionary is built. [Arclink_fetch](https://www.seiscomp3.org/wiki/doc/applications/arclink_fetch
) has a "-n" option to "Avoid using response dictionary (default False)"

Geoscope dataless does not contain blockette 42 but Arclink server response to Obspy creates dictionnary in the response and blockette 42. 

It could be interesting to have in Obspy the same option as in Arclink_fetch "Avoid using response dictionary (default False)" to avoid this kind of problem

**Comment by petrrr** [comment]
@bonaime: Just a general comment here. 

It is actually not very surprising that you see this difference between the (original) dataless and the SEED served by Arclink, even if this dataless is the upstream file. As far as I know, it is not used directly. Instead it is converted in a XML representation (inventory XML) which is used internally in SeisComp3, and, exchange among the data centers of the Arclink federation. So there must be a conversion back to SEED at some point when serving data. With this in mind, having them encoded the one way o the other is not that surprising anymore.
