### ISSUE TITLE
StreamPick error : 'module' object has no attribute 'QString

### ISSUE THREAD

**Issue by Claireera** [obspy/obspy#1209]
Hello, 
I'm using StreamPick in order to pick seismic arrival time of a .SAC file. 
I wrote the following lines : 
from obspy.core import read
from streamPick import * 
def Picking(File):
    st =read(File)
    newpick= streamPick(st)
#main program
FileE = '/home/claire/PHD/Working/Data/R110.02/GSW01.15.110.01.00.00.BHE.SAC'
Picking(FileE)

In the console I received the following error message : 

  File "streamPick.py", line 126, in _initMenu
    self.fltrbtn.setStyleSheet(QtCore.QString(

AttributeError: 'module' object has no attribute 'QString'

I tried to update pyqt but I receive the same error message.
Could you help me please?

**Comment by megies** [comment]
This is the wrong place for your question, please try https://github.com/miili/StreamPick/issues.
