### ISSUE TITLE
Guess who's gonna go for Lanczos resampling ?

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#1213]
Hey all,

Soooooo, Friday-brain-dead afternoon:

Comparison of Lanczos resampling & scikits.samplerate.

Verdict:
* ObsPy's Lanczos (OL) is very good
* OL is almost as good as scikits.resample's `sinc_best` method
* The difference between OL and scikits is mostly around the anti-alias filter
* I didn't (yet) managed to identify how strong/ how is scikits.resample anti-alias filter are defined
* OL seems to have an issue after `zerophase=True`, I have to re-set tr.data to an array
* OL is much better than `sinc_fastest`, which I actually use in MSNoise
* OL is 4.5x slower than `sinc_best`, but 2x faster than `sinc_fastest`, for a better result

Conclusion:
* MSNoise 1.4 (coming soon), will use obspy

see the test:

http://nbviewer.jupyter.org/url/msnoise.org/ipynb/Scikits.Samplerate%20vs%20ObsPy.lanczos2.ipynb

**Comment by megies** [comment]
> 4.5x slower than sinc_best, but 2x faster than sinc_fastest

that part is a bit weird..

> MSNoise 1.4 (coming soon), will use obspy

:+1:

**Comment by QuLogic** [comment]
This is somewhat unrelated, but why use `%pylab inline` when you're going to do `import numpy as np`? You can use `%matplotlib inline` just to set up the inline figures without all the excess symbols.

**Comment by ThomasLecocq** [comment]
@megies actually the sinc_fastest is doing a much stronger lowpass filter, lanczos with the settings I have set here, it's the same time as sinc_medium

@qulogic obviously I don't master ipython notebooks :)

**Comment by krischer** [comment]
Heyhey,

thanks for the benchmark :-) A couple of comments:

* Can you try with different windows for the lanczos filter: http://docs.obspy.org/master/packages/autogen/obspy.signal.interpolation.plot_lanczos_windows.html#obspy.signal.interpolation.plot_lanczos_windows I tend to use `window="blackman"` because the window looks the nicest to me.

* Also the `a` value in the lanczos resampling is crucial. For large `a` it converges to a theoretically perfect reconstruction filter. Runtime pretty much increases linearly with increasing `a`. 12 is very good value - 20 is probably about as high as it makes sense. The default of 5 is resonably but probably has a small error.


> I didn't (yet) managed to identify how strong/ how is scikits.resample anti-alias filter are defined

Would be cool to know - maybe we can use it as an inspiration for our own anti-alias filter. I have some trials here if somebody wants to take a look: http://nbviewer.ipython.org/gist/krischer/5501747

**Comment by ThomasLecocq** [comment]
```C
case SRC_SINC_FASTEST :
			return "Band limited sinc interpolation, fastest, 97dB SNR, 80% BW." ;

		case SRC_SINC_MEDIUM_QUALITY :
			return "Band limited sinc interpolation, medium quality, 121dB SNR, 90% BW." ;

		case SRC_SINC_BEST_QUALITY :
			return "Band limited sinc interpolation, best quality, 145dB SNR, 96% BW." ;
```

**Comment by ThomasLecocq** [comment]
Found in src_sinc.c from SRC "libsamplerate0" :
```C
case SRC_SINC_FASTEST :
			return "Band limited sinc interpolation, fastest, 97dB SNR, 80% BW." ;

		case SRC_SINC_MEDIUM_QUALITY :
			return "Band limited sinc interpolation, medium quality, 121dB SNR, 90% BW." ;

		case SRC_SINC_BEST_QUALITY :
			return "Band limited sinc interpolation, best quality, 145dB SNR, 96% BW." ;
```

or in numbers (might be more verbose):
*Fastest*
```
**  f = make_filter (8, 128, 100.3) ;
**  Pass band width  : 0.0039062 (should be 0.0039062)
**  Stop band atten. : 100.71 dB
**  -3dB band width  : 0.484
**  half length      : 2463
**  increment        : 128
*/

```

*mid*
```
** f = make_src_filter (cycles = 21, incr = 491, atten = 122.000000)
**
**   Stop band atten. : 120.61 dB
**   -3dB band width  : 1.811
**   half length      : 22437
**   increment        : 491
*/

```

*best*
```
** f = make_src_filter (cycles = 69, incr = 2381, atten = 160.000000)
**
**   Stop band atten. : 154.67 dB
**   -3dB band width  : 1.922
**   half length      : 340238
**   increment        : 2381
```

**Comment by ThomasLecocq** [comment]
@krischer is there actually already a built-in anti-alias filter available in obspy? Or did I dream that ?

**Comment by krischer** [comment]
Well we don't really have a good one built-in as of now. We really should though.

Fairly solid but acausal one: https://github.com/krischer/LASIF/blob/9c0083d094b76702d41e0426dd9d941db8316e38/lasif/function_templates/preprocessing_function.py#L91-L120

Some years ago I tried to create a good one. It works but it relies on some magic numbers so I did not add it to ObsPy so far: http://nbviewer.jupyter.org/gist/krischer/5501747

**Comment by ThomasLecocq** [comment]
@krischer youre jupyter notebook seems very close to what we need indeed...

**Comment by megies** [comment]
Btw.. should we make the zerophase variant for the cheby we use in decimation the default?

**Comment by krischer** [comment]
I'd rather replace it with the FIR filter. The zerophase chebychev destroys almost half the passband which is a bit much.

**Comment by ThomasLecocq** [comment]
I could also try to rewrite the one used in `libsamplerate` or at least plot it against the other tests cases

**Comment by krischer** [comment]
That would be great! Just be a bit careful to not leak the GPL into ObsPy.

Do they have a generic one or some handtuned onces for a couple of decimation/resampling factors?

**Comment by ThomasLecocq** [comment]
I think it's a generic one. Don't worry, I don't even understand what licences are :-)

**Comment by megies** [comment]
Uhm.. the title and conversation in this ticket lead me to the conclusion that.. uhm, no idea actually. So, closing.. :wink:

**Comment by ThomasLecocq** [comment]
Good to close indeed. The Lanczos resampler has the same result as the scikits.samplerate except around the anti-alias filter. So it's another topic.
