### ISSUE TITLE
Search box in master docs links to docs of latest release

### ISSUE THREAD

**Issue by trichter** [obspy/obspy#1217]
The search box at http://docs.obspy.org/master
directs to http://docs.obspy.org/search.html
and not to http://docs.obspy.org/master/search.html

**Comment by megies** [comment]
Yeah, it's always been like that, unfortunately. Not sure if there's an easy solution. Personally I just usually added the `/master` in the URL again after searching. If you're using the master docs a lot you might want to try the [docset](http://docsets.obspy.org/) using [Dash](https://kapeli.com/dash) or [Zeal](https://zealdocs.org/).

**Comment by megies** [comment]
Ping. I'm not very familiar with how the header bar is set up (I believe it is a fixed asset?).. any chance of a simple fix?

**Comment by megies** [comment]
Fixed
