### ISSUE TITLE
Vertical scale increase with a factor 2

### ISSUE THREAD

**Issue by Claireera** [obspy/obspy#1223]
Hello, 

I notice that st.plot() function multiply with a  factor 2 the vertical axis. I tried to force the attributes vertical_scaling_range=0 and scale=1but it doesn't change anything. 
Is there an other plot parameter to change? 

thanks

**Comment by krischer** [comment]
Hi,

can you please add a short code snippet that reproduces the noticed behaviour? Also please state which version of ObsPy you are using.

```python
In [1]: import obspy
In [2]: obspy.__version__
Out[2]: '0.10.2'
```

Cheers!

Lion

**Comment by krischer** [comment]
A quick reminder: Can you please provide a short example to reproduce the behavior?

**Comment by Claireera** [comment]
Hello, 
Thanks for your answer and sorry for this late response. 
I found the problem : In the metadata, the calibration parameter name : "calib" was set at 2. By default, the function plot() of the stream class, take into account this parameter. 
Thus my data were still the same but the vertical scale was amplified by a factor 2 . 
Cheers 

Claire
