### ISSUE TITLE
Waveform mismatch when removing response between Stream.remove_response vs. Stream.simulate(seedresp)

### ISSUE THREAD

**Issue by dsentinel** [obspy/obspy#1231]
Deferring to the experts whether this is even an issue, or expected error between the 2 implementations. This came up while testing #1185

![responsedifference](https://cloud.githubusercontent.com/assets/14005083/12653856/a1413136-c5ae-11e5-869b-c29db4df4fa4.png)

**Comment by dsentinel** [comment]
```
'''
Lloyd Carothers
show difference between response deconvolution methods
'''
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)
from future.builtins import *  # NOQA

import matplotlib.pyplot as plt
from obspy import UTCDateTime
from obspy.fdsn import Client
from obspy.core.util import NamedTemporaryFile
from obspy.core import Stream
from obspy.clients.fdsn import Client as FDSN_Client
from obspy.clients.iris import Client as OldIris_Client

t1 = UTCDateTime("2010-09-3T16:30:00.000")
t2 = UTCDateTime("2010-09-3T17:00:00.000")
pre_filt = (0.005, 0.006, 30.0, 35.0)
fdsn_client = Client('IRIS')

# Fetch waveform from IRIS FDSN web service into a ObsPy stream object
# and automatically attach correct response
st = fdsn_client.get_waveforms(network='NZ', station='BFZ', location='10',
                                       channel='HHZ', starttime=t1, endtime=t2,
                                       attach_response=True)

assert isinstance(st, Stream)
st_rm_response = st.copy()
st_rm_response.remove_response(output='DISP', pre_filt=pre_filt)

# 

# Download and save instrument response file into a temporary file
with NamedTemporaryFile() as tf:
    respf = tf.name
    old_iris_client = OldIris_Client()
    # fetch RESP information from "old" IRIS web service, see obspy.fdsn
    # for accessing the new IRIS FDSN web services
    old_iris_client.resp('NZ', 'BFZ', '10', 'HHZ', t1, t2, filename=respf)

    seedresp = {'filename': respf,  # RESP filename
                # when using Trace/Stream.simulate() the "date" parameter can
                # also be omitted, and the starttime of the trace is then used.
                'date': t1,
                # Units to return response in ('DIS', 'VEL' or ACC)
                'units': 'DIS'
                }

    # Remove instrument response using the information from the given RESP file
    st.simulate(paz_remove=None, pre_filt=pre_filt, seedresp=seedresp)

tr_rm = st_rm_response[0]
tr_sim = st[0]
time = tr_rm.times()

plt.plot(time, tr_rm.data, 'k')
plt.plot(time, tr_sim.data,'k', color='blue')
plt.show()
```

**Comment by megies** [comment]
(just looking at the image)

 ..should be no problem, just some tiny differences (which gets smaller with time), edge-effects during processing, looks like to me (slight differences in.. tapering? pre-filtering?).
Looking at your code, you're not buffering (i.e. requesting more data before/after processing, and trimming to the interesting bits later). I'd never process data without buffering in real world if at all possible.

I'd wager if you add a couple of minutes of buffer for processing and trim it off later, both traces are the same.. :game_die:

**Comment by dsentinel** [comment]
I thought the same, but there is a little still in the middle of the trace, the whole of which is 1800 seconds.
![responsedifferencemiddle](https://cloud.githubusercontent.com/assets/14005083/12658653/8ffd768c-c5c7-11e5-9f0c-2f0013e358c7.png)
I use the same pre-filter for both.

>So if those two metadata sources don't match, there might be a difference coming from that

I haven't check this by hand yet. Going off the assumption that since they're both coming from the archive they match (or even that they're built from the same source, maybe)

Thanks for having a look. I'm not claiming anything's wrong, just noticed it.
If nobody's worried, can close the issue.

**Comment by krischer** [comment]
The `Trace.simulate()` method is one of the oldest methods in all of ObsPy - some of its default settings are historic and we used other one's in the `Trace.remove_response()` method. 

You can make both behave identical: The bottom shows the difference of both - note that it is almost 7 orders of magnitude less than the absolute values. I attribute that difference to subtle floating point differences - in one case the numerical values for the response stages come from a StationXML file, in the other case from a RESP file. Very small differences in how these values are parsed might cause the remaining difference. Or I missed something else. But in any case: Nothing to worry about! Note that the only line I changed is the `simulate()` call.

This isssue IMHO once again illustrates the fragility of the deconvolution operation where small algorithmic differences can have a big effect...

FYI: We are quite confident that the response curves calculated from StationXML and RESP files are completely identical. We tested it against the whole IRIS inventory - a couple 100,000 response curves all in all. Test case: https://github.com/obspy/sandbox/tree/master/stationxml_test

<img width="2032" alt="screen shot 2016-01-28 at 23 15 56" src="https://cloud.githubusercontent.com/assets/800487/12660715/6c036e0a-c615-11e5-8da0-372a9a75e51e.png">

```python
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)
from future.builtins import *  # NOQA

import matplotlib.pyplot as plt
from obspy import UTCDateTime
from obspy.fdsn import Client
from obspy.core.util import NamedTemporaryFile
from obspy.core import Stream
from obspy.clients.fdsn import Client as FDSN_Client
from obspy.clients.iris import Client as OldIris_Client

t1 = UTCDateTime("2010-09-3T16:30:00.000")
t2 = UTCDateTime("2010-09-3T17:00:00.000")
pre_filt = (0.005, 0.006, 30.0, 35.0)
fdsn_client = Client('IRIS')

# Fetch waveform from IRIS FDSN web service into a ObsPy stream object
# and automatically attach correct response
st = fdsn_client.get_waveforms(network='NZ', station='BFZ', location='10',
                                       channel='HHZ', starttime=t1, endtime=t2,
                                       attach_response=True)

assert isinstance(st, Stream)
st_rm_response = st.copy()
st_rm_response.remove_response(output='DISP', pre_filt=pre_filt)

#

# Download and save instrument response file into a temporary file
with NamedTemporaryFile() as tf:
    respf = tf.name
    old_iris_client = OldIris_Client()
    # fetch RESP information from "old" IRIS web service, see obspy.fdsn
    # for accessing the new IRIS FDSN web services
    old_iris_client.resp('NZ', 'BFZ', '10', 'HHZ', t1, t2, filename=respf)

    seedresp = {'filename': respf,  # RESP filename
                # when using Trace/Stream.simulate() the "date" parameter can
                # also be omitted, and the starttime of the trace is then used.
                'date': t1,
                # Units to return response in ('DIS', 'VEL' or ACC)
                'units': 'DIS'
                }

    # Remove instrument response using the information from the given RESP file
    st.simulate(paz_remove=None, pre_filt=pre_filt, seedresp=seedresp,
                pitsasim=False, sacsim=True, water_level=60)

tr_rm = st_rm_response[0]
tr_sim = st[0]
time = tr_rm.times()

plt.subplot(211)
plt.plot(time, tr_rm.data, color='red', label="remove_response")
plt.plot(time, tr_sim.data, color='black', label="simulate")
plt.legend()
plt.subplot(212)
plt.plot(time, tr_rm.data - tr_sim.data, label="Difference")
plt.legend()
plt.show()
```

**Comment by dsentinel** [comment]
Thanks @krischer for the detailed explanation, and the args needed to get the 2 methods to behave the same. This difference is on the order of what I was expecting. The StationXML_test is also a good reference for what I'm working on.

**Comment by krischer** [comment]
> This difference is on the order of what I was expecting.

Both should be running exactly the same code paths for the response calculation. So the difference can only come from very small floating point differences due to the I/O - might be worthwhile to check out what exactly both are passing to evalresp. But yea - the difference is tiny enough to not worry.
