### ISSUE TITLE
problems with urlencode for ISC FDSN service

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1237]
Due to how `urllib.parse.urlencode` constructs the requested URL (specifically, converting `:` to `%3A`) we have a problem requesting from ISC FDSN service:

Works: http://isc-mirror.iris.washington.edu/fdsnws/event/1/query?starttime=2001-06-23T20:31:00&endtime=2001-06-23T20:37:00

Doesn't work: http://isc-mirror.iris.washington.edu/fdsnws/event/1/query?starttime=2001-06-23T20%3A31%3A00&endtime=2001-06-23T20%3A37%3A00

Which results in problems for us:
```python
from obspy import UTCDateTime
from obspy.fdsn import Client
client = Client("ISC")
# raises an Exception, because we get an unexpected info page
client.get_events(starttime=UTCDateTime("2001-06-23T20:31:00"),
                  endtime=UTCDateTime("2001-06-23T20:37:00"))
```

I guess this is a problem in the upstream server implementation?

**Comment by QuLogic** [comment]
The server is broken as far as I can tell. I captured the stream and the colons are escaped _once_ (there was a double-escape bug at some point.) Not only does the server not unescape the parameters, but it returns HTTP 200 even though it failed!

We can work-around the problem by specifying the `safe=':'` kwarg, but that's only if other servers don't have issues with it.

**Comment by megies** [comment]
Ok, I've sent out an email to ISC IT staff to make them aware of this issue.

**Comment by megies** [comment]
Fixed on server side.

**Comment by pozgo** [comment]
Hi, 

I have clicked both links and they both seems to work for me. What is the error that you are gatting exactly?

**Comment by megies** [comment]
As mentioned before this has been fixed at the server side in the meantime, as prompted by my email.

**Comment by pozgo** [comment]
Okiedokie. Thanks.
