### ISSUE TITLE
Not implemented test cases for the SACTrace class

### ISSUE THREAD

**Issue by krischer** [obspy/obspy#1241]
@jkmacc-LANL While doing something unrelated I discovered three tests in `obspy.io.sac.tests.test_sactrace` that are skipped because they are not yet implemented. I just wondered what is up with those. Can we remove them or do they require implementation?

e.g. https://github.com/obspy/obspy/blob/01c0c4b8c07260e042898e8426298d9bcc57eb7c/obspy/io/sac/tests/test_sactrace.py#L126-L128

**Comment by jkmacc-LANL** [comment]
Lion, those can be removed.  The functionality they test is covered by ObsPy's tests.  Thanks for asking.

**Comment by krischer** [comment]
Great. Done as part of #1039.
