### ISSUE TITLE
obspy.io.sac tests raise warnings

### ISSUE THREAD

**Issue by krischer** [obspy/obspy#1242]
The `obspy.io.sac` tests raise warnings which means we cannot use our test runner in verbose mode (it turns all warnings into errors).

@jkmacc-LANL Sorry for pinging you again but you currently have the greatest understanding of the `io.sac` module. Could you have a look?

In #1039 I already fixed the one with `UserWarning: Non-integers may be truncated. (nzmsec: 500.0)`. Otherwise it appears to only be two small issues.

The others are.

```bash
$ obspy-runtests io.sac -d -v
...
======================================================================
ERROR: test_read_xy_write_xy_from_bytes_io (obspy.io.sac.tests.test_core.CoreTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/tests/test_core.py", line 618, in test_read_xy_write_xy_from_bytes_io
    _write_sac_xy(st, fh)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/core.py", line 272, in _write_sac_xy
    _internal_write_sac_xy(stream[0], filename, **kwargs)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/core.py", line 301, in _internal_write_sac_xy
    sac = SACTrace.from_obspy_trace(trace, keep_sac_header=True)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/sactrace.py", line 1253, in from_obspy_trace
    header = _ut.obspy_to_sac_header(trace.stats, keep_sac_header)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/util.py", line 333, in obspy_to_sac_header
    warnings.warn(msg)
UserWarning: Old header has invalid reftime.

======================================================================
ERROR: test_read_xy_write_xy_from_open_file_binary_mode (obspy.io.sac.tests.test_core.CoreTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/tests/test_core.py", line 632, in test_read_xy_write_xy_from_open_file_binary_mode
    _write_sac_xy(st, tf)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/core.py", line 272, in _write_sac_xy
    _internal_write_sac_xy(stream[0], filename, **kwargs)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/core.py", line 301, in _internal_write_sac_xy
    sac = SACTrace.from_obspy_trace(trace, keep_sac_header=True)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/sactrace.py", line 1253, in from_obspy_trace
    header = _ut.obspy_to_sac_header(trace.stats, keep_sac_header)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/util.py", line 333, in obspy_to_sac_header
    warnings.warn(msg)
UserWarning: Old header has invalid reftime.

======================================================================
ERROR: test_read_xy_write_xy_via_obspy (obspy.io.sac.tests.test_core.CoreTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/tests/test_core.py", line 81, in test_read_xy_write_xy_via_obspy
    tr.write(tempfile, format='SACXY')
  File "/Users/lion/workspace/code/obspy/obspy/core/trace.py", line 888, in write
    Stream([self]).write(filename, format, **kwargs)
  File "/Users/lion/workspace/code/obspy/obspy/core/stream.py", line 1428, in write
    write_format(self, filename, **kwargs)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/core.py", line 282, in _write_sac_xy
    _internal_write_sac_xy(trace, fh, **kwargs)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/core.py", line 301, in _internal_write_sac_xy
    sac = SACTrace.from_obspy_trace(trace, keep_sac_header=True)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/sactrace.py", line 1253, in from_obspy_trace
    header = _ut.obspy_to_sac_header(trace.stats, keep_sac_header)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/util.py", line 333, in obspy_to_sac_header
    warnings.warn(msg)
UserWarning: Old header has invalid reftime.

======================================================================
ERROR: test_valid_sac_from_minimal_existing_sac_header (obspy.io.sac.tests.test_core.CoreTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/tests/test_core.py", line 767, in test_valid_sac_from_minimal_existing_sac_header
    tr.write(tempfile, format='SAC')
  File "/Users/lion/workspace/code/obspy/obspy/core/trace.py", line 888, in write
    Stream([self]).write(filename, format, **kwargs)
  File "/Users/lion/workspace/code/obspy/obspy/core/stream.py", line 1428, in write
    write_format(self, filename, **kwargs)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/core.py", line 431, in _write_sac
    _internal_write_sac(trace, fh, byteorder=byteorder, **kwargs)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/core.py", line 461, in _internal_write_sac
    sac = SACTrace.from_obspy_trace(trace)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/sactrace.py", line 1253, in from_obspy_trace
    header = _ut.obspy_to_sac_header(trace.stats, keep_sac_header)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/util.py", line 333, in obspy_to_sac_header
    warnings.warn(msg)
UserWarning: Old header has invalid reftime.

======================================================================
ERROR: test_write_small_trace (obspy.io.sac.tests.test_core.CoreTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/tests/test_core.py", line 419, in test_write_small_trace
    tr.write(tempfile, format=format)
  File "/Users/lion/workspace/code/obspy/obspy/core/trace.py", line 888, in write
    Stream([self]).write(filename, format, **kwargs)
  File "/Users/lion/workspace/code/obspy/obspy/core/stream.py", line 1428, in write
    write_format(self, filename, **kwargs)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/core.py", line 431, in _write_sac
    _internal_write_sac(trace, fh, byteorder=byteorder, **kwargs)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/core.py", line 462, in _internal_write_sac
    sac.write(buf, ascii=False, byteorder=byteorder)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/sactrace.py", line 1177, in write
    byteorder=byteorder)
  File "/Users/lion/workspace/code/obspy/obspy/io/sac/arrayio.py", line 335, in write_sac
    warnings.warn(msg)
UserWarning: Writing header-only file. Use 'wb+' file mode to update header.

----------------------------------------------------------------------
```

**Comment by jkmacc-LANL** [comment]
No apologies necessary; I'm happy to help.  The `wb+` file mode issue is straight-forward to fix, but the `invalid reftime` warning seems useful enough to keep.  Should I add a `suppress_warnings=False` flag in `util.obspy_to_sac_header`, and set it to `True` in the tests?  This seems hacky, but it would allow the warning to exist by default without failing these tests.

**Comment by krischer** [comment]
No that's fine. We can just catch the warnings in the tests if they are useful. Thus we also actually test the warning.

**Comment by jkmacc-LANL** [comment]
Ok. I'll fix the `wb+` thing and re-write the tests to catch/verify the `reftime` warning.  Should I branch & PR from master or work directly on something else?

**Comment by krischer** [comment]
Just do it on master. It seems to be a small enough change so I'll rebase on top of #1039 if necessary or vice versa.

**Comment by jkmacc-LANL** [comment]
OK, I could use a hint :smile:; how do you catch warnings in tests? [This](https://docs.python.org/2/library/warnings.html#testing-warnings) lets me catch and test them, but they still happen, and so this problem persists.  It looks like (TestCase.assertRaises](https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertRaises) does something similar.  Do you have a suggestion?  Sorry to flail like this.

**Comment by krischer** [comment]
Really?

If you do this

```python
with warnings.catch_warnings(record=True) as w:
    warnings.simplefilter("always")   # Also do this!
```

they should get caught. If not something funny is happening.

**Comment by jkmacc-LANL** [comment]
Hmmm.  Wasn't doing the `simplefilter`; it didn't make sense.  I'll try it.  Thx.

**Comment by krischer** [comment]
Yea I also don't understand why that is needed. I think it might just somehow reset some internal warning registries so it all works in the end. But the `simplefilter` is usually needed.

**Comment by megies** [comment]
Actually, this is not needed to make sure the warning is shown (with normal settings it would get shown on the first occurence), but rather to prevent it not being shown later on (with normal settings like `"once"`, the fact that the warning was shown and shouldn't be anymore later on gets registered in the warning registry -- and then you can later do `"always"` all you like, you won't get the warning -- unless you manually clear the warning registry).
Kind of counter intuitive, right? ;-)

**Comment by megies** [comment]
Here's for illustration:
```python
import warnings


def do_warn(i):
    msg = "W%d" % i
    warnings.warn(msg, UserWarning)

print("#"*50)
print("A")
do_warn(1)
print("B")
do_warn(1)
print("C")
print("#"*50)

print("#"*50)
print("A")
do_warn(2)
print("B")
with warnings.catch_warnings():
    warnings.simplefilter("always")
    do_warn(2)
print("C")
print("#"*50)

print("#"*50)
print("A")
with warnings.catch_warnings():
    warnings.simplefilter("always")
    do_warn(3)
print("B")
do_warn(3)
print("C")
print("#"*50)
```
```
##################################################
A
some_warning.py:6: UserWarning: W1
  warnings.warn(msg, UserWarning)
B
C
##################################################
##################################################
A
some_warning.py:6: UserWarning: W2
  warnings.warn(msg, UserWarning)
B
C
##################################################
##################################################
A
some_warning.py:6: UserWarning: W3
  warnings.warn(msg, UserWarning)
B
some_warning.py:6: UserWarning: W3
  warnings.warn(msg, UserWarning)
C
##################################################
```

**Comment by jkmacc-LANL** [comment]
It looks to me like the warning still happens even inside `warnings.catch_warnings()` context, it's just caught for introspection/testing.  The problem `obspy-runtests -v -d io.sac` is having is that warnings are happening at all.  I'm observing this when I use the `warnings.catch_warnings()` context inside the problem tests.  The warnings still happen and the tests still fail.  Sure, I'd like to test the warnings, but I'd also like to proceed as though they didn't happen, so that the tests pass.

**Comment by krischer** [comment]
Can you push what you have? Then we can have a look and try to dissect what is happening.

**Comment by jkmacc-LANL** [comment]
OK, I'll branch off to keep it off of master.

**Comment by megies** [comment]
FYI, I dug up where I encountered those problems with the warning registry, if you're interested you can check it out here: https://github.com/obspy/obspy/commit/cbe7212c5e7dae0683ad8c4ad85e2b5e0255bc1f#diff-93c710504a1d59384f7fc6ad859e2f06R305

**Comment by jkmacc-LANL** [comment]
I won't be able to get to this until tonight, but for quick references, here's the change I made in sac test_core that is still producing the warnings and test errors:

```python
    def test_read_xy_write_xy_from_bytes_io(self):
        """
        Reading/writing XY sac files from/to io.BytesIO. It's alphanumeric
        so bytes should also do the trick.
        """
        # Original.
        st = _read_sac_xy(self.filexy)

        with io.BytesIO() as fh:
            with warnings.catch_warnings(record=True) as w:
                warnings.simplefilter('always')
                _write_sac_xy(st, fh)
                self.assertEqual(len(w), 1)
                self.assertIn('reftime', str(w[-1].message))

            fh.seek(0, 0)
            st2 = _read_sac_xy(fh)

        self.assertEqual(st, st2)
```

**Comment by jkmacc-LANL** [comment]
Sorry for the delay.  Catching the warnings as posted above works now, for some reason.

**Comment by krischer** [comment]
Continued in #1260.

For future reference: You have enough rights on this repository to turn any issue into a PR. It has been thought for a couple of years that github might remove that functionality but as of now it still works.

Here are a couple of ways to do that: http://stackoverflow.com/questions/4528869/how-do-you-attach-a-new-pull-request-to-an-existing-issue-on-github

**Comment by jkmacc-LANL** [comment]
Thanks, Lion.  I wasn't aware of that.

**Comment by krischer** [comment]
Its VERY hidden functionality ;-) Github should really just offer a button for that.

**Comment by megies** [comment]
> Here are a couple of ways to do that: http://stackoverflow.com/questions/4528869/how-do-you-attach-a-new-pull-request-to-an-existing-issue-on-github

> Its VERY hidden functionality

Well.. it has been in our Wiki for years.. ^^ (maybe the "reading" was just not "interesting enough")

 https://github.com/obspy/obspy/wiki/Interesting-Reading-on-Git%2C-GitHub

**Comment by jkmacc-LANL** [comment]
To be fair, the Wiki has almost 30 pages in it :wink:   I only go there when someone links to it in Issues or on Gitter.  That little "Pages (29)" has actually been pretty effective at dissuading me from exploring the Wiki.   I mean no offense, I just thought it was worth mentioning.

**Comment by megies** [comment]
> To be fair, the Wiki has almost 30 pages in it :wink: I only go there when someone links to it in Issues or on Gitter. That little "Pages (29)" has actually been pretty effective at dissuading me from exploring the Wiki. I mean no offense, I just thought it was worth mentioning.

I know and agree, but it's the only place to put those things we have right now.. :/

**Comment by krischer** [comment]
I have to admit that I have also never seen that particular page before today ;-)

**Comment by jkmacc-LANL** [comment]
Sorry, I didn't look at [this change](https://github.com/obspy/obspy/commit/12a007fc66302f3863f73c428881feecb83aff0c) closely enough .  The integer truncation issue seems like another good warning to keep, especially for all the integer time headers.  I think that casting `new_reftime.microsecond / 1000` to `int` silently circumvents the warning at hand, at the risk of actual data corruption.  Could I do another `catch_warnings()` on those tests or, perhaps more simply, do the casting to `int` inside the offending test(s)?

**Comment by megies** [comment]
> I have to admit that I have also never seen that particular page before today ;-)

We really should have more information about our code base in the Wiki.. and better structured (e.g. how to set up an image test, how to format links/citations in docstrings, how to make docstring links to code objects with custom text... etc.pp). I have to look up some things so often inside the code base myself.. ;-)

**Comment by krischer** [comment]
> Sorry, I didn't look at this change closely enough . The integer truncation issue seems like another good warning to keep, especially for all the integer time headers. I think that casting new_reftime.microsecond / 1000 to int silently circumvents the warning at hand, at the risk of actual data corruption. Could I do another catch_warnings() on those tests or, perhaps more simply, do the casting to int inside the offending test(s)?

Hmm...now that I had a closer look - the code snippet in question (without my int() cast):

```python
            # find the milliseconds and leftover microseconds for new reftime
            _, rem_microsecs = _ut.split_microseconds(new_reftime.microsecond)

            # snap the new reftime to the most recent milliseconds
            # (subtract the leftover microseconds)
            new_reftime.microsecond -= rem_microsecs
            ...

            self.nzmsec = new_reftime.microsecond / 1000
```

Example:

```python
new_reftime.microsecond = 123456

x, rem_microsecs = _ut.sp...                  # x = 123, rem_microsecs = 456
new_reftime.microsecond -= rem_microsecs      # new_reftime.microsecond = 123000
self.nzmsec = new_reftime.microsecond / 1000  # self.nzmsec = 123.0 (a float on python 3!)
...
```

So the `int()` cast just makes sure its an integer without actually possibly loosing accuracy. The same thing could be achieved without doing all this microsecond arithmetics by just using truncating division:

```python
self.nzmsec = new_reftime.microsecond // 1000
```
Am I wrong?

**Comment by jkmacc-LANL** [comment]
Shucks, I forgot that Python 3 always returns floats, even if two integers are involved.  I just was trying to prevent is a user setting an integer header using a float, and having it silently truncate the value.  Maybe I should do:

```python
if integer_header_value % 1:
    warnings.warn(....)
```

**Comment by krischer** [comment]
But does the current code not also truncate the value?

```python
new_reftime.microsecond -= rem_microsecs      # new_reftime.microsecond = 123000
```

performs effectively a truncation.

**Comment by jkmacc-LANL** [comment]
It does, but only when setting `reftime` directly.  The user is also allowed to set `nzmsec` directly. In both cases, the warning is generated by the function/property to sets general integer headers.  The warning was intended to cover all integer header manipulations.

**Comment by krischer** [comment]
Good idea. The modulo operation should be save as double precision floats can accurately represent integers until a super high number. Can you take care of it or should I do it?

**Comment by jkmacc-LANL** [comment]
I'll do it on master.

**Comment by krischer** [comment]
Great :-)
