### ISSUE TITLE
Compilation on win32

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#1249]
Hey,

I'm trying to get Appveyor to build all windows-based packaging. 

The 32 bits versions fail because of a mismatch of flags passed to the libmseed compilation:

```
error: Command "c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG /arch:SSE2 -DWIN32=1 -IC:\Python34_32\envs\_build_placehold_placehold_placehold_placehold_placehold_pla\lib\site-packages\numpy\core\include -IC:\Python34_32\envs\_build_placehold_placehold_placehold_placehold_placehold_pla\include -IC:\Python34_32\envs\_build_placehold_placehold_placehold_placehold_placehold_pla\include /Tcobspy\mseed\src\obspy-readbuffer.c /Fobuild\temp.win32-3.4\Release\obspy\mseed\src\obspy-readbuffer.obj /fp:strict" failed with exit status 2
```

, specifically an incompatibility of /arch:SSE2 and /fp:strict.

it seems there is a hotfix to visual studio 10.0. I have posted it on appveyor's issue list too (https://github.com/appveyor/ci/issues/647).

The reason for it to fail, is the flag "fp:strict" passed. It is defined here: https://github.com/obspy/obspy/blob/0.10.2/setup.py#L476  It was introduced by the correction [1321] of issue #64 by @barsch . Reading #64, I can't really see why the AssertEqual fails (floating point down to the 8th digit or else). Now that we are almost 4 years later, this flag is maybe no longer needed. 

Any idea on how I could test without the flag? I *think* of creating a appveyor'sandbox in my github repo, get a modified 0.10.2 version without the flag and build it there. makes sense?

**Comment by ThomasLecocq** [comment]
Humm.. sorry, it seems the hotfix I've mentionned is for studio 2008...

**Comment by ThomasLecocq** [comment]
testing without fp:strict (at least, trying to...)

https://ci.appveyor.com/project/ThomasLecocq/obspy10-2testwin32

**Comment by megies** [comment]
> testing without fp:strict (at least, trying to...)



> Any idea on how I could test without the flag?

Uhmm.. just do a new branch and remove the flag in a commit..? Should be built by appveyor then (or maybe needs to open a "fake" PR)

**Comment by ThomasLecocq** [comment]
actually now it's gse that doesn't build on p34 ... trying now first to test with default 0.10.2

**Comment by megies** [comment]
> Uhmm.. just do a new branch and remove the flag in a commit..? Should be built by appveyor then (or maybe needs to open a "fake" PR)

But building on a separate project has the advantage that you don't get bogged down in our build queue.. :+1:

**Comment by ThomasLecocq** [comment]
:-) indeed :-)

**Comment by ThomasLecocq** [comment]
are there any tests called "test_writeAndReadDifferentEncodings", which was failing in #60, and the reason for the https://github.com/obspy/obspy/blob/master/setup.py#L527 hack ?

**Comment by barsch** [comment]
https://github.com/obspy/obspy/blob/master/obspy/io/mseed/tests/test_mseed_reading_and_writing.py#L952

**Comment by ThomasLecocq** [comment]
so actually, for what I can tell, this test passes even if I remove the fp:strict flag.

**Comment by ThomasLecocq** [comment]
done with #1265
