### ISSUE TITLE
Use requests instead of urllib

### ISSUE THREAD

**Issue by krischer** [obspy/obspy#1254]
The combination of using `future` and `urllib` on older systems results in downloads not working for HTTPS urls. This bug could and should probably be fixed in the `future` library but we already have `requests` as a hard dependency so we should just use that. See e.g. here:

http://tests.obspy.org/35446/
#1253 already does that for everything except `obspy.clients`. We should also do it there.

**Comment by megies** [comment]
One thing to consider.. from requests docs: `If you're using GET, OPTIONS, POST, PUT, PATCH or DELETE, you can disable redirection handling with the allow_redirects parameter:` Maybe we'll have to manually disallow redirects in most cases that use credentials.

**Comment by megies** [comment]
@krischer, @mwschouten I did some work on this at some point but then didn't have time to work on it more.. if still needed, I pushed it to https://github.com/obspy/obspy/tree/use_requests now..

**Comment by megies** [comment]
For future reference, there's some API changes in `requests` that we probably will have to catch in a compatibility layer, see e.g. <<@krischer please fill in reference to code you showed me today about `requests.Response.json`>>

**Comment by krischer** [comment]
Here you go:

https://github.com/obspy/obspy/blob/4c90ea2cb3cb1be88403161109eda2600d385001/obspy/clients/syngine/client.py#L31-L54

https://github.com/obspy/obspy/blob/4c90ea2cb3cb1be88403161109eda2600d385001/obspy/clients/base.py#L221-L225

**Comment by megies** [comment]
This hasn't seen any activity, so I'll bump this to 1.2.0.

**Comment by d-chambers** [comment]
Any chance we can move this to 2.0.0? May be easier to do it during the `future`-ectomy than on its own?

**Comment by krischer** [comment]
Yes I was thinking the same.

**Comment by krischer** [comment]
I think 1.3.0 is the release we'll now drop Python 2. Or do we want to call this release 2.0? We'll not release another Python 2 supported release after 1.2.0

**Comment by d-chambers** [comment]
To me it feels like a major version bump is in order for dropping python 2, but it isn't that important either way. The important thing is that we are dropping python 2 :smile:

**Comment by megies** [comment]
Yep, we already decided to make 2.0.0 the next release after 1.2.0, it should be discussed in some issue or maybe it was just on gitter dunno

**Comment by trichter** [comment]
I think this issue is obsolete.
