### ISSUE TITLE
Appveyor: Only add "--pr-url ..." to "obspy-runtests ..." if in a PR build

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1270]
This is a follow-up for #1269. I couldn't figure out how to add a conditional if/else to only add "--pr-url ..." to the `obspy-runtests ...` call if `%APPVEYOR_PULL_REQUEST_NUMBER%` is non-empty. So, currently invalid URLs (always `https://github.com/obspy/obspy/pull/`) in `<prurl>`  tag in the xml report get sent to `https://tests.obspy.org`.

**Comment by QuLogic** [comment]
I guess something like [the first comment here](http://help.appveyor.com/discussions/problems/1806-conditional-build-configuration-for-branches-in-appconveyoryml)?

**Comment by QuLogic** [comment]
Or maybe [without PowerShell](http://ss64.com/nt/if.html)?

**Comment by megies** [comment]
Had those pages on my screen (and some others as well), I have to admit, but hate the yaml syntax anyway and have no idea about what Windows syntax (or shell or whatnot) is applicable in Appveyor, so I'll leave this to the Win guys..

**Comment by megies** [comment]
Seems like @barsch is ignoring `prurl` in `obspy/reporter` if it's invalid because of missing number at the end (see http://tests.obspy.org/53024/xml/, http://tests.obspy.org/53024). So this can be closed without a fix, I guess..
