### ISSUE TITLE
Debian package py3 command line scripts not working from an obspy git source tree

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1273]
![screenshot from 2016-02-20 00 25 22](https://cloud.githubusercontent.com/assets/1842780/13192018/771c974e-d768-11e5-908f-0d3f08235d4f.png)

**Comment by QuLogic** [comment]
Have you checked the shebang is correct? Maybe it still points to `python` or `python2`?

**Comment by megies** [comment]
Nah, they're fine..
```
$ head /usr/bin/obspy-runtests 
#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'obspy==1.0.0','console_scripts','obspy-runtests'
__requires__ = 'obspy==1.0.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('obspy==1.0.0', 'console_scripts', 'obspy-runtests')()
    )
```
```
$ head /usr/bin/obspy3-runtests 
#!/usr/bin/python3.4
# EASY-INSTALL-ENTRY-SCRIPT: 'obspy==1.0.0','console_scripts','obspy3-runtests'
__requires__ = 'obspy==1.0.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('obspy==1.0.0', 'console_scripts', 'obspy3-runtests')()
    )
```

**Comment by QuLogic** [comment]
I just re-read the title, and I'm not so sure this is a really a bug. When in the git source tree, you'd import the git directory (since we don't use a `lib` subdirectory), and it's likely you have some old build things there.

**Comment by krischer** [comment]
Yea I'm also not sure if this is a bug....launching from within our repository is always dangerous. Some package (I think its numpy, scipy, or lxml - I forgot) actually prohibits importing the package within its source tree and just raises an exception.

**Comment by megies** [comment]
Hmm.. in any case, I can't even reproduce the problem right now.. so closing.
