### ISSUE TITLE
line "decomp_6b: Neither DAT2 or DAT1 found!" after submitting test report

### ISSUE THREAD

**Issue by barsch** [obspy/obspy#1279]
After running `runtests` and submitting a test report to tests.obspy.org the following line appears:

`decomp_6b: Neither DAT2 or DAT1 found!`

This is the case for all tested environments (Python 2.7, 3.3, 3.4, 3.5; 32bit/64 bit; Windows)

One can even google for this sentence and find it within the following reports:
https://travis-ci.org/obspy/obspy/jobs/70848093#L351
https://travis-ci.org/obspy/obspy/jobs/58534068#L338
https://travis-ci.org/obspy/obspy/jobs/59836264#L341

**Comment by megies** [comment]
That's probably this test (in GSE2).. `test_no_dat2_null_pointer`, `CatchOutput` context manager not doing the job of catching it..

**Comment by petrrr** [comment]
I recall to have see this before on OSX as well, but not always. Is it an Py2 vsl Py3 issue?

**Comment by petrrr** [comment]
Okay I can confirm: The message shows up on OSX only for Py3.

**Comment by barsch** [comment]
while testing only io.gse2 the error pops up in a py 3.3 env for both 32 and 64bit under Windows - (py 2.7 and py 3.4 did work as intended)

**Comment by likueimo** [comment]
anaconda python 3 
obspy 1.0.1
run obspy-runtests still print out decomp_6b: Neither DAT2 or DAT1 found!

**Comment by barsch** [comment]
possible solution: (basically using ```libc.fflush()``` instead of ```sys.stdout.flush()```)
* http://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/ for Linux
* http://stackoverflow.com/questions/35304920/how-to-redirect-c-level-streams-in-python-in-windows for Windows (which works for me for Python <= 3.4 - I couldn't get it to work on 3.5 yet)

Its a huge ugly hack!

**Comment by krischer** [comment]
Yea I could also never get it to work across all Python version on OSX. I know pytest can capture everything so it must be possible.

There is also this fantastically named project: https://github.com/minrk/wurlitzer

I did not test it yet.

**Comment by barsch** [comment]
@QuLogic - almost our current CatchOutput - but replacing ```libc.fflush()``` instead of ```sys.stdout.flush()```

**Comment by megies** [comment]
stale, closing.
