### ISSUE TITLE
404 Not Found after search

### ISSUE THREAD

**Issue by bonaime** [obspy/obspy#1280]
Using the latest ObsPy Documentation (1.0.0), the search tool returns old links

ex search on "arclink" returns
http://docs.obspy.org/packages/obspy.arclink.html
instead of
https://docs.obspy.org/packages/obspy.clients.arclink.html

**Comment by krischer** [comment]
Thats a cache issue - the searching is implemented in javascript so the browsers cache things. Clear your browsers cache or maybe force reload and it should be fixed. The private browsing mode is a good way to test it.

Please reopen if it persists.
