### ISSUE TITLE
Substring indexing of wfdisc files in obspy.io.css.core

### ISSUE THREAD

**Issue by atwinkelman** [obspy/obspy#1290]
When reading in CSS data, I have an issue with substring indexing being one column off and not catching the "foff" byte-offset value:
```
In [1]: from obspy import read
In [2]: st = read("I26DE.2015213.wfdisc", format="CSS")
...
ValueError: invalid literal for long() with base 10: '          '
```

I've verified my wfdisc file conforms to the prescribed CSS 3.0 standard given by [Anderson et al.](https://anf.ucsd.edu/pdf/css30.pdf), specifically that the character positions are within specification. I then compared the character positions read in by [obspy.io.css.core](https://docs.obspy.org/_modules/obspy/io/css/core.html#_read_css) and found an inconsistency that is likely the source of my problem. The first three wfdisc fields, sta, chan, and (start) time, are located at columns 1-6, 8-15, and 17-33, respectively, and are read in by obspy by reading substring characters 0:6, 7:15, and 16:33 (zero-indexed, not-inclusive at the end), again respectively. However, when reading the remaining wfdisc fields starting with endtime at columns 63-79, obspy reads substring characters 61:78. With python's zero-index convention this appears okay but substring extraction is not inclusive at end; the 79th column (string index 78) is not included when reading in the endtime and all wfdisc fields after that. 

The effect is that the last character of each field is trimmed off. In my case, the foff (byte offset) value is a 0 (zero) at column 257. In the obspy.io.css.core source, 
```
offset = int(line[246:256])
```
only includes the spaces leading up to the zero at column 257, but not including the zero:
```
In [12]: line
Out[12]: 'I26H1  BDF       1438387200.00000         0     5805  2015213  1438473599.95000  1728000  20.0000000         0.000143         1.000000 MB2005 o s4 - ./2015/213                                                       I26DE0.w                                  0        -1 20160217 15:28:00'

In [13]: # simulate reading of foff byte offset

In [14]: line[246:256]
Out[14]: '          '

In [15]: line[246:257]
Out[15]: '          0'

In [16]: # simulate reading of enddate

In [17]: line[61:78]
Out[17]: '  1438473599.9500'

In [18]: line[61:79]
Out[18]: '  1438473599.95000'
```

In order to handle this edge case, perhaps the right-hand side of the substring extractions should be increased by one when reading the endtime, nsamp, samprate, calib, calper, datatype, dir, dfile, and foff wfdisc fields (or where appropriate).

For reference, I'm running obspy version 1.0.0:
```
$ conda list | grep obspy
obspy                     1.0.0                    py27_0    obspy
```

**Comment by QuLogic** [comment]
I have not checked the spec, but your analysis and solution seems plausible. Have you considered opening a PR to fix it? (Please use the `maintenance_1.0.x` branch if you do.)

**Comment by atwinkelman** [comment]
In my experience so far with the infrasound group I work with, there are two formats for wfdisc files: 

1. the official CSS 3.0 specification and
2. a common version with the _wfid_ field one column shorter. This means that all the fields following the _wfid_ field fall one column sooner than in the official CSS 3.0 specification.

The second version is apparently common enough that obspy.io.css.core.py was written with substring indices matching this unofficial version. This makes the original obspy.io.css.core.py unable to read css files conforming to the official CSS 3.0 spec. 

In order to be able to read both schemes, I edited to parse wfdisc lines using the whitespace characters present in both formats via `string.split()`. I've edited my local clone, pushed to my fork, and think I'm ready to open a PR.

**Comment by QuLogic** [comment]
> However, when reading the remaining wfdisc fields starting with endtime at columns 63-79, obspy reads substring characters 61:78.

I'm sorry, but I just checked the spec you linked, and those numbers are incorrect. `endtime` is at columns 62-78, hence substring 61:78 is correct.

> In my case, the foff (byte offset) value is a 0 (zero) at column 257.

`foff` is at columns 247-256, not 257.

These numbers are also consistent with the original schema off of which ObsPy's implementation was created. So it appears that your files may be the invalid ones. How were they generated?

**Comment by jkmacc-LANL** [comment]
There are two "wfdisc" specs, one is CSS3.0 by [Anderson et 1990](http://jkmacc-lanl.github.io/pisces/data/Anderson1990.pdf), and a revision by the [NNSA](http://prod.sandia.gov/techlib/access-control.cgi/2002/023055.pdf), which has some longer integer and text columns.  Only the former is "CSS", the latter is called the "NNSA KB Core" schema.  Perhaps the wfidsc @atwinkelman is parsing is the latter?

**Comment by atwinkelman** [comment]
@QuLogic, I've reviewed my notes and found you are correct, ObsPy agrees with Andersen et al. My file indeed does not conform to official CSS 3.0 but rather to NNSA KB Core that @jkmacc-LANL references (thanks for linking those!). I obtained my file from an official datacenter source, so clearly the NNSA format is common. My intent is to be able to read both formats. Would there be objection to expanding to utilize this NNSA KB Core format too?

**Comment by krischer** [comment]
No of course not - the more formats the merrier :-)

If you end up implementing this: Both formats appear to be fairly similar so please try to refactor the `obspy.io.css` module to make sure common parts are not duplicated. The `obspy.io.css` module will then just have two `is_/read_` functions: `is_css()`, `is_nnsa_kb_core()`, `read_css()`, `read_nnsa_kb_core()`. These will then all be registered with ObsPy and our machinery will happily work with all these formats :-)

**Comment by atwinkelman** [comment]
Great, I've added `is_nnsa_kb_core()` and `read_nnsa_kb_core()` to `obspy.io.css.core.py` as suggested.

**Comment by krischer** [comment]
Continued in #1301.
