### ISSUE TITLE
import Error

### ISSUE THREAD

**Issue by lileipku00** [obspy/obspy#1294]
On my Ubuntu, obspy 1.0 works fine, but on the Fedora server, I'm unable to import  obspy.clients and mass_downloader.

```
In [1]: from obspy.clients.fdsn.mass_downloader import GlobalDomain, Restrictions, MassDownloader

ImportError     Traceback (most recent call last)
<ipython-input-1-6ca7f6150bd9> in <module>()
----> 1 from obspy.clients.fdsn.mass_downloader import GlobalDomain, Restrictions, MassDownloader

ImportError: No module named clients.fdsn.mass_downloader

In [2]: import obspy.clients

ImportError    Traceback (most recent call last)
<ipython-input-4-ade10347bb25> in <module>()
----> 1 import obspy.clients

ImportError: No module named clients

In [3]: import obspy

In [4]: import obspy.fdsn

In [5]: import obspy.clients.fdsn

ImportError    Traceback (most recent call last)
<ipython-input-6-c98b42c4a9d7> in <module>()
----> 1 import obspy.clients.fdsn

ImportError: No module named clients.fdsn


```

**Comment by QuLogic** [comment]
How did you install?

**Comment by petrrr** [comment]
Are you sure you are on a 1.0.0 version? 
Please print  __version__:
```
In [1]: import obspy

In [2]: print(obspy.__version__)
1.0.0
```

**Comment by lileipku00** [comment]
Sure, it's 1.0.0.

I installed by `conda update -c obspy obspy`.  This works good on my local PC, but not on the server.

Then I removed obspy totally and reinstalled by  `conda install -c obspy obspy`. 

Finally I removed Anaconda totally and ~/.ipython folder as well, and then install obspy by  `conda install -c obspy obspy`.  That doesn't work.

**Comment by ThomasLecocq** [comment]
easy solution: install from pip !

**Comment by lileipku00** [comment]
I think I found the reason. But I don't know how to solve it.

`pip list` gives:
```
...
numba (0.23.1)
numexpr (2.4.6)
numpy (1.8.1)
obspy (1.0.0)
odo (0.4.0)
openpyxl (2.3.2)
pandas (0.17.1)
path.py (0.0.0)
patsy (0.4.0)
pbr (1.3.0)
pep8 (1.7.0)
...
```

but
```
>>> import obspy
>>> obspy.__version__
'0.10.2'
>>> obspy
<module 'obspy' from '/usr/lib/python2.7/dist-packages/obspy/__init__.py'>
```

The module is imported from the system, not from the Anaconda pkg folder.

I checked `pip`, `conda`, `python` and `ipython` by `which`, they locate in `~/ananaconda/bin`.

**Comment by lileipku00** [comment]
@ThomasLecocq  just tried, but the same wrong.

**Comment by krischer** [comment]
I guess you should remove the debian (the one in `dist-packages`) packages or remove all others and update the debian packages. Also check your `$PYTHONPATH` env variable.

**Comment by lileipku00** [comment]
Hi @krischer , what do you mean by "remove the debian (the one in dist-packages) packages or remove all others and update the debian packages"? Do you mean `'/usr/lib/python2.7/dist-packages/`? It's in the system folder, I have no authority.

```
$ env | grep PYTHON
PYTHONPATH=/soft/python/lib/python2.7/site-packages:
```
It's not the same as 

```
>>> obspy
<module 'obspy' from '/usr/lib/python2.7/dist-packages/obspy/__init__.py'>
```

And even if I changed `$PYTHONPATH` to `.` or anaconda path, it doesn't help.

**Comment by QuLogic** [comment]
You should check if there are any entries in `~/.local/lib/python2.7/site-packages/easy-install.pth` that contain that path.

**Comment by lileipku00** [comment]
I gave up. I guess it's the problem of the configuration of the server. 

`~/anaconda/bin` is the first item in my `PATH`. `which python`, `which ipython`, `which pip`, `which conda` all direct to the programs in it. But the version of python is 2.7.3 shown in the header above  the command lines (run `python` or `ipython` in the terminal), different from the version of 2.7.11 coming with anaconda.

Event if I set `$PYTHONPATH` to null, `sys.path` gives a list of system python pkg path prior to anaconda folders.

If I filter `sys.path` and keep only the anaconda path in the runtime, there are a lot of import errors for missing modules.

I gave up to run the new obspy on the server ...

**Comment by lileipku00** [comment]
@QuLogic  thx.  But no use. There is no `easy-install.pth` anywhere. 

I found a `easy-install.pth` in `~/anaconda/lib/python2.7/site-packages` on my PC. I copied it to the server but still no help.

**Comment by krischer** [comment]
Try to use conda environments. They are usually quite good at resolving these issues. Also read this: http://stackoverflow.com/questions/4271494/what-sets-up-sys-path-with-python-and-when

There is now reasons you should not be able to make it work.

**Comment by lileipku00** [comment]
@krischer solved with the help from SO.

It's because `python` is aliased to the system python.

**Comment by megies** [comment]
Good that it's sorted out. You can use `which` to find out what binary/executable/script actually gets executed (so `which python` to check Python interpreter).

**Comment by lileipku00** [comment]
@megies  I was cheated by `which python`. 

`type python` is the right one telling me `python` is an alias overriding the anaconda python in the $PATH.

**Comment by megies** [comment]
Your sys admin setting an `alias` for all users for `python` to the system python???

That's really bad practice and I'm failing to see a valid use case why anybody would do that.
