### ISSUE TITLE
Is it able to make some process to the Stream chunk got by mass_downloader before writing to local?

### ISSUE THREAD

**Issue by lileipku00** [obspy/obspy#1295]
If we can make some processing such as quality control and resampling to the Stream in memory, we can save the IO time and storage space.

**Comment by krischer** [comment]
Hmm...do you have any particular interface in mind, e.g. can you make up some code how you would image this if it were implemented? 

Saving disc I/O time really does not matter as it is highly limited by the download speed. It would have to happen after being saved to disc as the mass downloader downloads things in fairly large chunks at a time within threads. But it could be an additional stage after the downloading from one FDSN remote client has finished.

**Comment by lileipku00** [comment]
Emm....

In fact, after one night's mass_downloader I found my disk is almost full. The continuous raw data are so big, especially the HH? channels.

Since currently we can pass a custommed function to handle the mseed filename, I think it's also feasible to pass a function as an argument to make some process to the Stream after the chunk is ready.

**Comment by krischer** [comment]
While some processing is possible after a chunk has been downloaded it is in general only possible to process after the station information has been downloaded as one might require the instrument response.

After some more thought I don't think it is sensible to add this added complexity to the mass downloader. If you have some space problem, just download in smaller chunks and do the processing in-between which can be achived with a trivial script. The following mock-up should do the trick:

```python
start = obspy.UTCDateTime(2015, 1, 1)
step = 86400 + 10

while start < obspy.UTCDateTime(2015, 1, 1):
    end = start + step
    res = Restrictions(starttime=start, endtime=end, ...)
    mdl.download(..., restrictions=res, ...)
    # DO THE PROCESSING
    start += step
```

or you loop over different networks or whatever else works for you. FYI: Also make sure to download the proper channel - if you don't need the high sampling rate just use a lower sampled one.
