### ISSUE TITLE
New TauP implementation is much slower than before

### ISSUE THREAD

**Issue by samhaug** [obspy/obspy#1296]
Just an observation. I am going to have to switch back to an older version because so many of my functions rely on this module.

**Comment by QuLogic** [comment]
It is slower because it is more accurate. On the other hand, the new depth cache makes it a bit faster for repeated calls with the same depths.

You can set `obspy.taup.seismic_phase.REFINE_DIST_RADIAN_TOL` to a higher value to reduce the accuracy; I think it should make it faster.

**Comment by samhaug** [comment]
Oh good to know! Thank you.

**Comment by krischer** [comment]
I'm reopening this so that we'll remember to document the `obspy.taup.seismic_phase.REFINE_DIST_RADIAN_TOL` value. It might be good to be able to set this on the `TauPyModel` class.

**Comment by megies** [comment]
`REFINE_DIST_RADIAN_TOL` is gone now in master in favor of `taup._DEFAULT_VALUES` which is a dictionary and I believe it's contents can be adjusted at runtime to modify these accuracy/speed tradeoff things, @johnrudge?

If thats correct we should briefly mention that fact on the taup API front page (`taup/__init__.py`)

**Comment by johnrudge** [comment]
We shouldn't tell users to mess around with the `taup._DEFAULT_VALUES` dictionary. The tolerances are now exposed to all the top-level functions and our recommendation should be to change the `ray_param_tol` argument when asking for a ray path or a travel time if the default tolerance values aren't appropriate for either accuracy or speed reasons. It's the `ray_param_tol` argument of `get_travel_times`, `get_pierce_points`, and `get_ray_paths` that should be documented.

A simple example from `master`:
Very crude tolerance, `ray_param_tol=1e2`:
```
from obspy.taup import TauPyModel
model = TauPyModel("iasp91")
arrivals = model.get_ray_paths(0.0, 1.0, ["P"], ray_param_tol=1e2)
arrivals.plot_rays(plot_type="cartesian")
print(arrivals)
```
![1e2](https://user-images.githubusercontent.com/43536815/175006954-34d10934-87ce-4537-ab3d-03dc0b6cc719.png)
```
5 arrivals
        P phase arrival at 19.172 seconds
        P phase arrival at 20.186 seconds
        P phase arrival at 20.346 seconds
        P phase arrival at 21.273 seconds
        P phase arrival at 21.475 seconds
```

Fine tolerance, `ray_param_tol=1e-6`.
![1e-6](https://user-images.githubusercontent.com/43536815/175008096-228172cb-8b9e-47f3-8455-1b65f4a9c904.png)
```
5 arrivals
        P phase arrival at 19.171 seconds
        P phase arrival at 20.186 seconds
        P phase arrival at 20.346 seconds
        P phase arrival at 21.273 seconds
        P phase arrival at 21.475 seconds
```
You can see you get perfectly decent arrival times with the wide tolerance, but the paths are awful.

**Comment by megies** [comment]
> The tolerances are now exposed to all the top-level functions and our recommendation should be to change the `ray_param_tol` argument when asking for a ray path or a travel time if the default tolerance values aren't appropriate for either accuracy or speed reasons.

Ah yeah, that's good!

**Comment by megies** [comment]
obsolete, i believe
