### ISSUE TITLE
Trigger/Picker module

### ISSUE THREAD

**Issue by kalessinlord** [obspy/obspy#1299]
I noticed possible problem on tutorial of Trigger/Picker(http://docs.obspy.org/tutorial/code_snippets/trigger_tutorial.html)

at 12.3.1, it says:
>>from obspy.signal.trigger import classic_sta_lta
However, this does not work. It would by 
>>from obspy.signal.trigger import classicSTALTA

Also, 
>>plot_trigger(trace, cft, 1.5, 0.5)
should be
>>plotTrigger(trace, cft, 1.5, 0.5)

It seems confusion of _(lower case) occur in the manual (e.g. ).
Or do I misunderstand something?

**Comment by jkmacc-LANL** [comment]
This new syntax is related to a large reorganization and re-naming effort for the ObsPy 1.0 release.  Can you verify that you're using 1.0?

`python -c "import obspy; print(obspy.__version__)"`

**Comment by kalessinlord** [comment]
Yes, I have not yet update the obspy. Thanks for the information.
