### ISSUE TITLE
qulogic repository for el6 python-future dependancy missing

### ISSUE THREAD

**Issue by duperray** [obspy/obspy#1328]
Hi,
Not sure if this is the right place to ask, but python-future package is not available anymore in qulogic repository for el6. This make python-obspy uninstallable.
I noticed a python-futures package in standard redhat repository I don't know if this could be usefull.
In this cas python-obspy required package needs to be changed from python-future to python-futures.
Else could someone repackage python-future in the qulogic repo?

Cheers,

Pierre

**Comment by megies** [comment]
Ping, @QuLogic..

**Comment by QuLogic** [comment]
Sorry, the trouble is that EL 6 is still using Python 2.6 and ObsPy 1.0.0 dropped support for that Python version. There is a way to use Python 2.7 using software collections, but I have not really had a chance to try and package it that way.

**Comment by duperray** [comment]
ok, can you still provide the old python-future and python-obspy package?

**Comment by duperray** [comment]
I meant the older version I use to work with?

**Comment by megies** [comment]
> Sorry, the trouble is that EL 6 is still using Python 2.6 and ObsPy 1.0.0 dropped support for that Python version. There is a way to use Python 2.7 using software collections, but I have not really had a chance to try and package it that way.

Sounds like too much work (.. time that could be used for more worthwile things), to be honest. Is there an important enough reason why falling back to an Anaconda install in this case is not an option?

**Comment by duperray** [comment]
but I use to install the old obspy version with python-future which was provided.
where are these package? deleted?

**Comment by megies** [comment]
Well, if it's a Python 2.6 installation we simply don't support that with ObsPy anymore.

**Comment by megies** [comment]
`Python 2.7.0 was released on July 3rd, 2010.` (https://www.python.org/download/releases/2.7/)

`Python 2.6.9 final was released on October 29, 2013. [...]  All official maintenance for Python 2.6, including security patches, has ended.` (https://www.python.org/download/releases/2.6.9/)

There just simply has to be a limit with backwards compatibility, otherwise maintenance overheads and efforts put on being compatible get ridiculous..

**Comment by duperray** [comment]
I'm not asking you to continue backporting to python 2.6, I'm just asking where are the last package your use to provide of python-future and python-obspy (OLD RELEASE).
I used them, and was very happy with them, but I can't find them anymore
thanks

**Comment by QuLogic** [comment]
There's now a new build up that depends on the official future EPEL package, but still of the 0.10.3 line.

**Comment by duperray** [comment]
thank you so much for your time I will continue using 0.10.3 until I go redhat 7 and python 2.7.
looking in
https://copr-be.cloud.fedoraproject.org/results/qulogic/obspy/epel-6-x86_64/
I can't locate the package, where are they build?

Thanks you

**Comment by QuLogic** [comment]
Right [here](https://copr-be.cloud.fedoraproject.org/results/qulogic/obspy/epel-6-x86_64/00175850-python-obspy/). But why download them by hand? Just use the copr as a repository.

**Comment by megies** [comment]
Loos like this can be closed. Please reopen if necessary.
