### ISSUE TITLE
test_code_formatting complains about missing flake8 on fresh installation

### ISSUE THREAD

**Issue by claudiodsf** [obspy/obspy#1331]
According to [this line of code](https://github.com/obspy/obspy/blob/master/obspy/core/tests/test_code_formatting.py#L30), `test_code_formatting` should be skipped for release builds.

I tried however with a fresh installation of the release build (`1.0.0`, using `virtualenv` and `pip`, and not installing `flake8`) and `obspy-runtests` spits the following error:

```
======================================================================
ERROR: test_flake8 (obspy.core.tests.test_code_formatting.CodeFormattingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/claudio/virtualenvs/obspy_1.0.0/lib/python2.7/site-packages/obspy/core/tests/test_code_formatting.py", line 24, in test_flake8
    report, message = check_flake8()
  File "/Users/claudio/virtualenvs/obspy_1.0.0/lib/python2.7/site-packages/obspy/core/util/testing.py", line 563, in check_flake8
    raise Exception('flake8 is required to check code formatting')
Exception: flake8 is required to check code formatting

----------------------------------------------------------------------
```

**Comment by megies** [comment]
That commit is not in 1.0.0, will be in next point release.

**Comment by claudiodsf** [comment]
Ok, sorry. People are beginning installing 1.0.0 and they run tests for checking installation. This generates confusion.

**Comment by megies** [comment]
No worries.. can't be helped with 1.0.0 though, at least we won't get people confused with this in future releases.
