### ISSUE TITLE
Convert mseed to sac maybe something lost

### ISSUE THREAD

**Issue by likueimo** [obspy/obspy#1333]
The most popular way convert mseed  format to sac format,
I guess is IRIS mseed2sac.
( https://seiscode.iris.washington.edu/projects/mseed2sac )
When I first use obspy try to convert it also, there are something different output. 

This is my mseed file 
https://www.dropbox.com/s/zq76hryer0770cj/VNAS.HHZ.2015.312?dl=0

When I use mseed2sac command to convert it
There are 12 output files 
( I type "```mseed2sac VNAS.HHZ.2015.312```" and output 12 files
Below I type ```saclst NPTS f TW.VNAS..HHZ.D.2015.312.*.SAC``` to see total points 
```
TW.VNAS..HHZ.D.2015.312.000000.SAC    1738425
TW.VNAS..HHZ.D.2015.312.045426.SAC        720
TW.VNAS..HHZ.D.2015.312.045601.SAC     737192
TW.VNAS..HHZ.D.2015.312.070058.SAC       1260
TW.VNAS..HHZ.D.2015.312.070422.SAC     641670
TW.VNAS..HHZ.D.2015.312.085412.SAC     394024
TW.VNAS..HHZ.D.2015.312.100421.SAC       1484
TW.VNAS..HHZ.D.2015.312.100731.SAC     164948
TW.VNAS..HHZ.D.2015.312.104058.SAC       1470
TW.VNAS..HHZ.D.2015.312.104421.SAC    2124138
TW.VNAS..HHZ.D.2015.312.164011.SAC       5228
TW.VNAS..HHZ.D.2015.312.164235.SAC    2624473
```

When I use python code ( rewrite from obspy tutorial ) blew try to convert
```python
#!/usr/bin/env python
import glob
from obspy.core import read

for file in glob.glob('VNAS.HHZ.2015.312'):
  st = read(file)
  tr = st[0]
  msg = "%s converted to %s.%s.%s.sac" % (str(file), tr.stats.station, tr.stats.channel, str(file)[9:18])
  fname = "%s.%s.%s.sac" % (tr.stats.station, tr.stats.channel, str(file)[9:18])
  tr.write(fname, format="SAC")
  print(msg)
```
and output ```VNAS.HHZ.2015.312.sac``` 
When I type ```saclst NPTS f VNAS.HHZ.2015.312.sac```
output is 
```VNAS.HHZ.2015.312.sac    1738425```

The 1738425 points is just one of mseed2sac output files, not all mseed convert to sac.

I am very new in obspy and python ! So maybe I make a obviously mistake.
Thank you to develop the very modern seismology program !

To help us understand and resolve your issue please check that you have provided the information below.

- [ obspy 1.0, python 3.5, Linux ] ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
- [ anaconda ] How did you install ObsPy and Python (pip, anaconda, from source ...)
- [ ] If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/) that demonstrates the issue i.e a small piece of code which reproduces the issue and can be run with out any other (or as few as possible) external dependencies.
- [ first time use obspy ] If this is a regression (Used to work in an earlier version of ObsPy), please note where it used to work.

**Comment by megies** [comment]
```python
  tr = st[0]
  tr.write(fname, format="SAC")
```

You're only writing the first trace in the stream, simply try `st.write(fname, format="SAC")`

**Comment by likueimo** [comment]
Thank you for your assistance !
And how to merge them one sac file better way to do ?
Could you help me again ?
Thank you a lot !

**Comment by barsch** [comment]
use ```st.merge()``` before writing to disk

See https://docs.obspy.org/packages/autogen/obspy.core.stream.Stream.merge.html for all options of the ```Stream.merge``` method

**Comment by likueimo** [comment]
Thank you a lot !

**Comment by megies** [comment]
Beware of pitfalls in merging traces, this should always be the last resort, I think.

**Comment by likueimo** [comment]
What kind of pitfalls may happen ? That I can care when I meet. 
Thank you !

**Comment by krischer** [comment]
http://docs.obspy.org/packages/autogen/obspy.core.stream.Stream.merge.html#obspy.core.stream.Stream.merge

http://docs.obspy.org/packages/autogen/obspy.core.trace.Trace.__add__.html#obspy.core.trace.Trace.__add__

**Comment by likueimo** [comment]
Thank krischer comment !
