### ISSUE TITLE
Write Taup theoretical arrivals in waveform and plot

### ISSUE THREAD

**Issue by likueimo** [obspy/obspy#1337]
Sorry I am new in obspy and python.
Thank a lot answer me the naive question last time !
You are all very nice for new people !
Another naive question
Is obspy possible to write taup theoretical arrivals in sac file or read in trace to plot it 
Like as taup_setsac command
```taup_setsac -pf tele_ph.doc -evdpkm VNAS.HHZ.2016.026.sac```
the tele_ph.doc file inside is 
```P
PcP
PKiKP
SKS
S
ScS
SKiKS
```
All I want to do is just plot like as

![v35](https://cloud.githubusercontent.com/assets/11157543/13904608/b29242f2-eee1-11e5-8e32-577b325dd5f8.png)

Thank you the smartest team to develop obspy !

To help us understand and resolve your issue please check that you have provided the information below.

- [ 1.0,3.5,Linux,] ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
- [anaconda] How did you install ObsPy and Python (pip, anaconda, from source ...)

**Comment by megies** [comment]
> Is obspy possible to write taup theoretical arrivals in sac file or read in trace to plot it

You can set sac specific headers from within obspy. But these are rather features for advanced users, so make sure you understand what you're doing. See http://docs.obspy.org/packages/autogen/obspy.io.sac.sactrace.html for a start.

On the other hand it's simple to add more features to our matplotlib based waveform plots.
E.g.
```python
from obspy import read, UTCDateTime
import matplotlib.pyplot as plt 
from matplotlib.dates import date2num

st = read()
p_onset = UTCDateTime("2009-08-24T00:20:07.700000Z")

fig = plt.figure()
st.plot(fig=fig, show=False)

ax = fig.axes[0]
ax.axvline(date2num(p_onset.datetime), lw=2)

plt.show()
```
![figure_1](https://cloud.githubusercontent.com/assets/1842780/13915966/174a985e-ef58-11e5-8393-25b8a9bc9335.png)

**Comment by krischer** [comment]
I assume this can be closed. Reopen if I am mistaken.

**Comment by likueimo** [comment]
Thank you all guys !

**Comment by ElodieK** [comment]
Hi there,

I would also like to plot arrivals. Following your second option above: onsets are never given in the date format (p_onset = UTCDateTime("2009-08-24T00:20:07.700000Z")) only like arr.time. 

If I have for example,
origin_time = obspy.UTCDateTime(2012, 7, 26, 5, 33, 33) and I 
date2num(origin_time.datetime) = 734710.2316319444

then set a random p_onset = UTCDateTime("2012-07-26T05:43:33.700000Z") 10 minutes later
date2num(p_onset.datetime) = 734710.2385844907
then date2num is wrong. 

Secondly, if I were to set Parr = date2num(origin_time.datetime) + arr.time (from P only)
and then use: ax.axvline(Parr, lw=2), no line shows.

Can you clarify how to go from arr.time to the date time for plotting please?

Thanks!

**Comment by rikimishra** [comment]
I am also a beginner in python and obspy. Hope I will 
get help here as I have been trying hard to get this plotted.It will be really
helpful if you people can help me out.


I want to plot a waveform vs. distance plot for seismograms from different stations.
The plot will be of different eplicentral distances on the Y axis vs. T-8.3delta.
I am getting examples for different channels plotted that too in AIMBAT which I do not have.

Please, please help me out with this.

**Comment by megies** [comment]
@rikimishra your question is not related to this issue and also it is a user question that should be asked on the users mailing list. If you do send an email there, be sure to properly explain your problem better or nobody will probably answer, is my guess. If you expect other people to help you with your problems, you should at least take the time to describe it appropriately.
