### ISSUE TITLE
Update problems on Win7

### ISSUE THREAD

**Issue by tonino0013** [obspy/obspy#1344]
Dear Developer.

Great improvements in Obspy 1.0.0, but since I updated using pip install -U obspy (in Win7)
and I try to run to test some waveforms I get this error:

```
from obspy import read

 raise ImportError("%r has no %r attribute" % (entry,attr))
ImportError: <module 'obspy.io.ascii' from 'C:\Python27\lib\site-packages\obspy\io\ascii\__init__.pyc'> has no 'readSLIST' attribute
```

I updated the Scipy the numpy, everythong and no way to start obspy.

Thank you a lot for the time and effor.

Best regards.

Tonino

**Comment by megies** [comment]
Tonino,

like already mentioned in my reply to your user mailing list post, I think your obspy installation got screwed up somehow during updating.
Installations from source that include compilation and good knowledge of pip/easy_install (both of which do have their shortcomings and can leave your Python environment in a state where you have to manually delete files etc.) and the corresponding directories containing the compiled output are for experienced users mostly and it is impossible for us to know how the state of your installation is and what to do in order to fix it.

Please give Anaconda a try for which we provide binary pre-compiled packages. If you stick to its `conda` builtin package manager it is pretty hard to end up with an inconsistent environment.
https://github.com/obspy/obspy/wiki/Installation-via-Anaconda

**Comment by tonino0013** [comment]
Dear Dr. Megies.

Thank you for the time, I read you are improving to obspy 1.0.1, congrats.

I installed minconda2, I created an environment called seismic then I activated it, like  conda tutorials says, then I installed obspy with the commads that you wrote. But I still I have the problem when I typed obspy-runtests and there are full of warning...

> c:\python27\lib\site-packages\obspy-1.0.0-py2.7-win-amd64.egg\obspy\__init__.py:157:
 ObsPyDeprecationWarning: Module 'obspy.mseed' is deprecated and will stop working with the next ObsPy version. Please import module 'obspy.io.mseed' instead.
  ObsPyDeprecationWarning)

and finally the same error...

> ImportError:
 <module 'obspy.io.ascii' from 'c:\python27\lib\site-packages\obspy-1.0.0-py2.7-win-amd64.egg\obspy\io\ascii\__init__.pyc'> has no 'readSLIST' attribute.

Maybe is for the python version, I must switch to python 3.

Sorry for disturbing but obspy was my great tool for the seismicity in Bolivia, and I do not want to lose it

Best regards.
Tonino

**Comment by megies** [comment]
Wheree did you install anaconda? I don't think you're using it since the path says `C:\python27`?

**Comment by barsch** [comment]
@megies: I dont think he installed it from **source** as ```pip install -U obspy``` on windows gets an egg file - as seen above (c:\python27\lib\site-packages\obspy-1.0.0-py2.7-win-amd64.egg).

Torino,

try the following:
(1) uninstall everything obspy related in the windows package manager (uninstall programs)
(2) check if any obspy package is in c:\python27\lib\site-packages\ - either .egg directories, .egg files or an obspy directory - delete any of them if necessary
(3) in the start menu run Anaconda Command Prompt and type ```python```
(4) run ```import obspy```

report back if this fails

**Comment by tonino0013** [comment]
Dear Robert B. and Tobias M,

*Finally with your suggestions I got it, I have the obspy running in
"anaconda" *
*and I got the Ipython with the notebooks which I think will help me a lot.*

*Thank you Tobias for the new
"https://github.com/obspy/obspy/wiki/Installation-via-Anaconda
<https://github.com/obspy/obspy/wiki/Installation-via-Anaconda>**"*
*and for the email Robert, I did all your steps.*

*Best Regards.*
*Tonino*

2016-03-25 7:47 GMT-04:00 Robert Barsch <notifications@github.com>:

**Comment by megies** [comment]
Good to hear it's working now for you. Might be worth to share what went wrong in case other people end up looking at this ticket.

**Comment by tonino0013** [comment]
Dear Dr. Tobias

Again thank you a lot!! I will share what i did

1. Open a cmd window and type pip uninstall obspy
2. Pip uninstall scipy
3. Pip uninstall numpy
4. Delete all *.egg from the site-package related to scipy, numpy, obspy,
also delete the folders
5. Uninstall miniconda ( in my case bescause i inatalled wrong)
6. Install miniconda, create an environment like the obspy tutorial said.
7. As you have the miniconda and a new environment active try to install
notebook, type conda install notebook
8. In my case i have a 64bit o.s. So for scipy, numpy i download them from
https://www.google.com.bo/url?sa=t&source=web&rct=j&url=http://www.lfd.uci.edu/~gohlke/pythonlibs/&ved=0ahUKEwiagP-Ft97LAhVHmR4KHTmNCdAQFggZMAA&usg=AFQjCNGb6mLzPAl9aNv6Brd8ho_cyvP46Q

9. They are *.wheels so you can install them inside conda with pip install
"wheel-path" . I did this because i was getting an error that told me "no
dll import error" so reading the obspy mail list i saw that i needed to
install the libs for 64bit o.s.

10. Reboot all the pc then Fine, At least obspy runs

Thank you a lot!! Best regards

Tonino
