### ISSUE TITLE
TypeError when reload obpsy

### ISSUE THREAD

**Issue by lileipku00** [obspy/obspy#1346]
Anaconda python 2.7 and obpsy 1.0

```
$ import obspy
$ reload(obspy)
Traceback (most recent call last):

  File "<ipython-input-26-f30d01436852>", line 1, in <module>
    reload(obspy)

  File "/home/user/anaconda/lib/python2.7/site-packages/obspy/__init__.py", line 179, in <module>
    read.__doc__ % make_format_plugin_table("waveform", "read", numspaces=4)

TypeError: not all arguments converted during string formatting
```

**Comment by krischer** [comment]
Hmm...I understand why that happens and that particular error would be very simple to fix. But there are other implications for reloading ObsPy: What happens with the warnings registries, our dynamically generated classes (obspy.core.event) and the resource identifiers and some other things I probably forgot?

In Python 3 this function has been moved to `importlib.reload`.

I guess we should try to support reloading but even the Python doc states: `In many cases extension modules are not designed to be initialized more than once, and may fail in arbitrary ways when reloaded.` so its not really a crucial feature.

Opinions?

**Comment by megies** [comment]
For me reloading never really worked consistently across different packages, so I never really bothered to use it.
I kind of agree, while this one is easy to fix, people could run into more obscure issues, so I'm not sure we want to support it.

**Comment by d-chambers** [comment]
Added wontfix label and closed. Feel free to open if anyone wants to pursue this. Personally, I would l like to see good reasons for needing to reload obspy before spending dev time on this.
