### ISSUE TITLE
Fix arclink decryption tests

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1353]
Follow-up to #1352 and #1347.

What is needed first is a working test server/account with decryption.

**Comment by krischer** [comment]
We could ask someone at the GFZ.

@petrrr Does the INGV have something along these lines.

**Comment by barsch** [comment]
I wrote an email to GFZ - will see what happens ...

**Comment by barsch** [comment]
test server is fixed - current test suite runs with current code (1.0.1rc3) flawless.

**Comment by megies** [comment]
Nice! :+1:
