### ISSUE TITLE
Switch arclink decryption to pycrypto?

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1354]
Follow-up to #1352.

**Comment by barsch** [comment]
also [cryptography](https://cryptography.io/en/latest/) seems to be a valid alternative. The project seems to be very active, has Py3k support and prebuild packages for Windows and conda. However, it comes with a lot of third party dependencies (setuptools, enum34, ipaddress, idna, pycparser, cffi) 

see https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/?highlight=des#cryptography.hazmat.primitives.ciphers.modes.CBC

I wouldn't mind to build this in as another fallback and let the user decide what to install.

**Comment by megies** [comment]
I'd say whatever is..
 - least amount of work/changes for us
 - easy to install (esp. anaconda!)

**Comment by barsch** [comment]
I working drop-in replacement for pycrypto with recent prebuild packages is https://www.pycryptodome.org

**Comment by megies** [comment]
> I working drop-in replacement for pycrypto with recent prebuild packages is https://www.pycryptodome.org

Hmm.. no packaging at least for Debian/Ubuntu for this one..

**Comment by barsch** [comment]
see https://github.com/obspy/obspy/pull/1360 - supports three different crypto libs at the same time
