### ISSUE TITLE
Package for Ubuntu 15.10 missing

### ISSUE THREAD

**Issue by barsch** [obspy/obspy#1364]
ObsPy package for Ubuntu 15.10 (Wily Werewolf) are currently missing

**Comment by megies** [comment]
For Ubuntu I'm only packaging long terms support (LTS) releases. In between releases every 6 months are too much work with the current approach (schroot environments in a virtualbox). Deb packages are more intended for use in longer term installations (servers, computer labs etc.), so unless we switch to Docker based deb packaging I can't do packages for every single Ubuntu release.

To be honest this 6 month release cycle doesn't make much sense to me anyway..

**Comment by QuLogic** [comment]
You could use OBS.

**Comment by megies** [comment]
OBS?
