### ISSUE TITLE
Reading mseed error if mseed encoding is "ASCII"

### ISSUE THREAD

**Issue by wjlei1990** [obspy/obspy#1371]
- [ obspy 1.0.1, python 2.7.11, Linux] 
- [conda install obspy ] 

Hi Obspy group,

I am using obspy to read some very old data(C090497A, data from 1997) and I found issues during reading. The trace.data is not float number, but looks like Hexadecimal.
```
In [26]: import obspy

In [27]: obspy.__version__
Out[27]: u'1.0.1'

In [28]: st = obspy.read("XA.SA51.mseed")

In [29]: st    
Out[29]: 
3 Trace(s) in Stream:
XA.SA51..BHE | 1997-09-04T04:20:12.070000Z - 1997-09-04T09:21:11.070000Z | 20.0 Hz, 361181 samples
XA.SA51..BHN | 1997-09-04T04:20:41.420000Z - 1997-09-04T09:21:36.470000Z | 20.0 Hz, 361102 samples
XA.SA51..BHZ | 1997-09-04T04:20:18.370000Z - 1997-09-04T09:21:08.620000Z | 20.0 Hz, 361006 samples

In [30]: st[0].data  
Out[30]: 
array(['\t', '\t', '\x0c', ..., '\x08', '\x07', '\n'], 
      dtype='|S1')

In [31]: st[0].stats
Out[31]: 
         network: XA
         station: SA51
        location: 
         channel: BHE
       starttime: 1997-09-04T04:20:12.070000Z
         endtime: 1997-09-04T09:21:11.070000Z
   sampling_rate: 20.0
           delta: 0.05
            npts: 361181
           calib: 1.0
         _format: MSEED
           mseed: AttribDict({'record_length': 1024, 'encoding': u'ASCII', 'filesize': 1253376, u'dataquality': u'M', 'number_of_records': 1224, 'byteorder': u'>'})
```
The trace.stats should the `encoding` is `ASCII`, which is different from normal `u'STEIM1'`.

I attached a sample mseed file here(I renamed it as XA.SA51.mseed.txt so github allows me to upload it).
[XA.SA51.mseed.txt](https://github.com/obspy/obspy/files/216384/XA.SA51.mseed.txt)

I am not sure if it is obspy issue or the data issue. Please let me know.

**Comment by krischer** [comment]
The `ASCII` encoding is used to store text values in miniseed which is what you are seeing here. So that is all good. I assume that the header of the file is just wrong?

See this thread for some more information: http://lists.swapbytes.de/archives/obspy-users/2016-March/002003.html

**Comment by megies** [comment]
Can be closed, I guess.

**Comment by wjlei1990** [comment]
Yes :)
