### ISSUE TITLE
Power Spectral Density Plot Issue

### ISSUE THREAD

**Issue by Zappytoes** [obspy/obspy#1372]
I'm running Obspy 0.10.2 with Python 2.7.11 on OSX 10.11.3

I need to make some PSD plots, so I tested out PPSD with data from the IU ANMO station and channel 00.BHZ. A link to what the PSD should look like can be found on the [USGS website] (http://earthquake.usgs.gov/monitoring/operations/station.php?network=IU&station=ANMO#PDF). The PSD I created using Obspy (figure below) does not look similar to what the USGS site shows and it appears to have some issues. I can't seem to nail down what I'm doing wrong.

![anmo_00_bhz_psd](https://cloud.githubusercontent.com/assets/18469106/14539629/6737b79a-023e-11e6-98de-7068f97a43b7.png)

[Here is a link to the SAC data file] (https://drive.google.com/file/d/0B6-mG0LMKLhtMGxBbkpoQlZTeDQ/view?usp=sharing)

[Here is a link to the Pole Zero Info created using rdseed] (https://drive.google.com/file/d/0B6-mG0LMKLhtaUJGa0VXUExPeG8/view?usp=sharing). I've also pasted it at the bottom of this post. 

Here is the script I run:

{{{
from obspy import read
from obspy.signal import PPSD

st = read('2016.098.00.00.00.0195_2016.103.00.00.00.0195.IU.ANMO.00.BHZ.M.SAC')
tr=st.select(channel="BHZ")[0]
paz={'gain':86299.50,
	'poles':[59.43130+0j,
        -22.71210+27.10650j,
        -22.71210 -27.10650j,
        -0.0048004+0j,
        -0.07394060+0j],
	'sensitivity':3404090000.0,
	'zeros':[0j,0j,0j]}
ppsd=PPSD(tr.stats,paz)
print(ppsd.id)
ppsd.add(st)
ppsd.plot()
}}}

Pole Zero file:
* **********************************
* NETWORK   (KNETWK): IU
* STATION    (KSTNM): ANMO
* LOCATION   (KHOLE): 00
* CHANNEL   (KCMPNM): BHZ
* CREATED           : 2016-04-13T22:00:21
* START             : 2014-12-17T18:40:00
* END               : 2599-12-31T23:59:59
* DESCRIPTION       : Albuquerque, New Mexico, USA
* LATITUDE    (deg) : 34.945910 
* LONGITUDE   (deg) : -106.457200
* ELEVATION     (m) : 1671.0 
* DEPTH         (m) : 145.0
* DIP         (deg) : 0.0  
* AZIMUTH     (deg) : 0.0  
* SAMPLE RATE  (Hz) : 20.0
* INPUT UNIT        : M
* OUTPUT UNIT       : COUNTS
* INSTTYPE          : Geotech KS-54000 Borehole Seismometer
* INSTGAIN          : 2.029000e+03 (M/S)
* COMMENT           : N/A
* SENSITIVITY       : 3.404090e+09 (M/S)
* A0                : 8.629950e+04
* Site Name         : Albuquerque, New Mexico, USA
* Owner             : Global Seismograph Network (GSN - IRIS/USGS)
* **********************************
ZEROS	3
	+0.000000e+00	+0.000000e+00
	+0.000000e+00	+0.000000e+00
	+0.000000e+00	+0.000000e+00
POLES	5
	-5.943130e+01	+0.000000e+00
	-2.271210e+01	+2.710650e+01
	-2.271210e+01	-2.710650e+01
	-4.800400e-03	+0.000000e+00
	-7.394060e-02	+0.000000e+00
CONSTANT	+2.937713e+14

**Comment by krischer** [comment]
Before looking into this in more detail: Can you please update to ObsPy 1.0.1 and try again? There have been quite some developments on the PPSD calculations.

**Comment by Zappytoes** [comment]
Thanks, I'll try that. I have to run Obspy on a stand-alone (no internet) computer, so I'll need to get the machine to a place where I can update.

**Comment by Zappytoes** [comment]
Hi,
I updated obspy with the following commands:
sudo port -v selfupdate
sudo port -v upgrade py27-obspy
sudo port select --set obspy obspy27

The update seems to have improved the long period, but the short period still looks wrong....
![anmo_00_bhz_psd_update](https://cloud.githubusercontent.com/assets/18469106/14541786/e8ac9908-0248-11e6-8c4a-58a6ae72eb53.png)

**Comment by krischer** [comment]
I guess either your data or your response information is wrong. Please also never use only poles and zeros when the full response is available - there is a difference. In most cases it affects the frequencies close to Nyquist but it might affect a much broader frequency range - IMHO there is no reason whatsoever to not use the full chain response information.

Here is an example that downloads the data anew and plots the PPSD:

```python
import obspy
from obspy.clients.fdsn import Client
from obspy.signal import PPSD

c = Client("IRIS")

st = c.get_waveforms(network="IU", station="ANMO", location="00", channel="BHZ",
                     starttime=obspy.UTCDateTime(2016, 4, 7),
                     endtime=obspy.UTCDateTime(2016, 4, 12))

inv = c.get_stations(network="IU", station="ANMO", location="00", channel="BHZ",
                     starttime=obspy.UTCDateTime(2016, 4, 7),
                     endtime=obspy.UTCDateTime(2016, 4, 12), level="response")

ppsd = PPSD(st[0].stats, inv)
ppsd.add(st)
ppsd.plot()
```

Result: ObsPy on the left, IRIS Mustang for the same time span on the right:

<img width="1193" alt="screen shot 2016-04-14 at 22 58 47" src="https://cloud.githubusercontent.com/assets/800487/14543632/6cb697ca-0295-11e6-8819-efe4a2201a16.png">

**Comment by Zappytoes** [comment]
Thank you for the advice. You were right that the PZ file was wrong. When compared with the RESP file, the PZ file contained an extra ZERO. Fixing that resulted in a similar PSD to what you have above.

**Comment by krischer** [comment]
Ah yes...well we really could have just seen that - the spectrum even looks clearly like a derivative of the "correct" one...

Happy its solved.
