### ISSUE TITLE
Plotting channel name in "section" waveform plots

### ISSUE THREAD

**Issue by amichelini** [obspy/obspy#1382]
Hi Folks,
first of all thanks for the wonderful job you have been doing with ObsPy. 
I am not notifying a bug.
I write you since I have been playing with a simple (though general) script that makes section plots of data downloaded from a fdsn client. This can be very useful for e.g. promptly visualizing the traces after an earthquake with known  event_id.
One thing that I have not been able to figure out is how to maintain next to each of the traces the actual channel name (e.g., IV.BSSO..BHZ). This is important to keep track of the stations. Is it possible at all ?
I have searched through the previous issues but haven't found anything.

Obspy version:
obspy                     1.0.1                    py27_0    obspy

I am using the standard command 

```
st.plot(type='section', plot_dx=20e3, recordlength=100,
        time_down=True, linewidth=.75, grid_linewidth=.25, orientation='horizontal')
```

am I missing some parameter ???

Thank you in advance for the help

Alberto

**Comment by megies** [comment]
Hi Alberto,

I've never used the section plot myself. Looking at the source code, if you set `st.plot(..., color="station")` you can get a legend with station names but also each trace has a different color, and I think that's probably not what you want.

I assume you're referring to station code (or "network.station") as labels on the traces? It seems no option for this is available. But, I think if you want more customization, you can either..
 * continue to adapt the section plot afterwards (with setting `show=False`), or
 * build the plot from scratch yourself exactly how you want it

Honestly, I think in many cases when one of our builtin plots doesn't match one's personal needs, it's easiest to just do the plot from scratch. It's just not possible to cover all potential needs and wishes, and the our plotting routines are already pretty convoluted and laden with many, many options.

But, customizing the plot should also be pretty simple.. however, I noticed some significant strangeness in how the section plot is set up, namely that the offset axis has some normalization that makes labelling the traces afterwards very hard. I'm proposing a fix for the next bug fix release with #1383. Also see the updated Tutorial example for doing customization on the plot: https://github.com/obspy/obspy/pull/1383/files#diff-e1b32bb704263a9eaca155fc58c64f7e

**Comment by amichelini** [comment]
Dear Tobias,
thank you for the explanation and the time spent on all this. I really appreciate it!
Yes, in the end it may be best to write our own modules but if there is already a lot done like in this case I believe it is better to build on someone's else developments rather than starting from scratch  which may be too cumbersome and time consuming.
In any case the input you gave me is very good and it may be more appropriate just to have two plots one in colour and one as I did.  The reason is that inserting the channel name (ie, net.station.loc.channel) may end up in too cluttered labels and having two plots can be really good. Anyway, teh other possibility of adding on is a good one as well and I will see what I can do (when I have time ....).

Thanks again
Cheers
Alberto

**Comment by megies** [comment]
Ok, I think I can close this, please reopen if necessary.

**Comment by amichelini** [comment]
Hi Tobias,
Absolutely.

I am sorry I did not answer earlier but I have been away and did not check
Cheers
Alberto

On Saturday, 30 April 2016, Tobias Megies <notifications@github.com> wrote:

> Ok, I think I can close this, please reopen if necessary.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/obspy/obspy/issues/1382#issuecomment-215953207>
>


-- 

**************************************************************
Alberto Michelini
Direttore del Centro Nazionale Terremoti
Istituto Nazionale di Geofisica e Vulcanologia (INGV)
Via di Vigna Murata, 605
00143 ROMA, Italy
Ph. +39 06 51860611, e-mail: alberto.michelini@ingv.it
**************************************************************

**Comment by megies** [comment]
> I am sorry I did not answer earlier but I have been away and did not check

No problem at all!
