### ISSUE TITLE
write obspy data to virtual file rather than disk?

### ISSUE THREAD

**Issue by rmodrak** [obspy/obspy#1394]
In some cases it is useful to write seismic data to a virtual file rather than to disk.  For example, writing data to a BytesIO "file" in memory rather than an actual file on disk sometimes makes sense to reduce  I/O load.  By chance does anyone have experience using the obspy write utilities in this manner?

**Comment by rmodrak** [comment]
To use stream.write for virtual file processing, one would need to supply a file object rather than a filename, as I understand it.  Is this possible with obspy?  Sorry if I have overlooked any relevant material in the documentation.

**Comment by rmodrak** [comment]
If it helps, we have in mind a specific use case--being able to pipe seismic data from an obspy stream to a seismic unix utility through a python subprocess.  At the moment, we're interested in virtual file way of doing this, not so much alternative methods, unless they happen to be really simple.

**Comment by megies** [comment]
```python
import io
from obspy import read

tmp = io.BytesIO()
st = read()

st.write(tmp, format="MSEED")
tmp.seek(0)

st = read(tmp)
print(st)
```

**Comment by lileipku00** [comment]
Using `StringIO` could be more efficient since `io.BytesIO` always makes a new copy?

**Comment by QuLogic** [comment]
I don't know what you mean. `StringIO` is the wrong type; the files are written as `bytes`.

**Comment by rmodrak** [comment]
Still having some problems piping BytesIO streams, but I think these are not related to obspy and outside of the scope of the original question.  @megies 's code sketch works just as expected.  Thanks all for the helpful feedback.  If it's alright, I'll go ahead and close.
