### ISSUE TITLE
How to get the full list of routing?

### ISSUE THREAD

**Issue by lileipku00** [obspy/obspy#1395]
`obspy.clients.arclink.Client.get_routing` returns only the primary server providing the data. How do I get all servers sorted in order provding the data for a station? And is there similar function for fdsn?

**Comment by petrrr** [comment]
@lileipku00 
I might be wrong, but it might just be there are currently no secondary routes defined in the EIDA federation.

**Comment by barsch** [comment]
obsolete due to https://github.com/obspy/obspy/pull/1987
