### ISSUE TITLE
Stream to SEGY: dtype of the data and the chosen data_encoding do not match

### ISSUE THREAD

**Issue by josephjamesfarrugia** [obspy/obspy#1396]
obspy version 1.0.1,Python version 2.7.6, OSX.
obspy was installed via pip and python via their website

Hello ObsPy community,

A copy of my code is below is attached. 

Essentially I am trying to write a stream file to SEGY. I've resampled and trimmed the merged stream so that the number of samples does not exceed the maximum allowed (see #1393). Upon writing the stream to SEGY I am given the following error message:

```
obspy.io.segy.core.SEGYCoreWritingError: The dtype of the data and the chosen data_encoding do not match.
            You need to manually convert the dtype if you want to use that
            data_encoding. Please refer to the obspy.io.segy manual for more
            details.
```

Thanks in advance for your help!

[segyconcat.txt](https://github.com/obspy/obspy/files/250993/segyconcat.txt)

**Comment by krischer** [comment]
`obspy.io.segy` can write a number of different data encodings (4 byte IBM and IEEE floats and 2 and 4 byte ints). In your case you previously read a SEG-Y file and `stream.stats.data_encoding` is set - it will thus attempt to use this data encoding when writing and requires the dtype of the data to be compatible with the encoding (one cannot write floats to an int datatype for examples).

After the resampling the data are 64bit floats. You can change it to single precision and force encoding 5 (IEEE floats):

```python
import numpy as np

...

for tr in st:
    tr.data = np.require(tr.data, dtype=np.float32)

st.write("blub.segy", format="segy", data_encoding=5)
```

I'm leaving this open as this should also have a better error message.

**Comment by josephjamesfarrugia** [comment]
@krischer,

Seems like I was able to correct the dtype using the lines of code you wrote above. In an effort minimize the number of samples I set the resampled frequency to the lowest possible limit (15.26 Hz) just to see if I could get the stream to write to SEGY. 

Now I am receiving the same error as in (#1393) again: `struct.error: short format requires SHRT_MIN <= number <= SHRT_MAX`

I've attached my code, please let me know if there's something that I need to change, or if you have an idea of why it's outputting this error.

[code.txt](https://github.com/obspy/obspy/files/252808/code.txt)

**Comment by krischer** [comment]
I think your traces are too long (but kind of hard to judge from the code). SEG-Y cannot store traces with more than 32xxx samples. The error occurs because `obspy.io.segy` tries to squeeze a too large (or too small) number into a 16bit number. I agree that we need much better error messages as also noted in the other issue.

If its not the number of samples it must be some other value - if you know Python well enough you can just (in Ipython):

```python
[1] pdb on
[2] run blub.py
```

It will now just jump to where the exception happened and you can figure out which value it actually is. Otherwise we would also need some test data to run your code with.

Cheers!

**Comment by rmlopes** [comment]
I would like to add something to this discussion. I am trying to write a segy that is a stacking of traces from an original. I found two problems, one of them is this message. I am using notebook frequently and I noticed that I get the error on the 2nd attempt of writing. According to the previous comments I am guessing that the datatype is reset before/after writing? Should it behave like this? See the following example:

`
from obspy.core.stream import read, Stream, Trace
from obspy.core.trace import Stats
import numpy as np

ss = Stream()
print("Reading traces...")
for i in range(1000):
    trace = Trace()
    trace.stats = Stats()
    trace.stats.distance = i
    trace.stats.sampling_rate = 250
    trace.data = np.zeros(5000,  dtype=np.float32)
    
    ss.append(trace)
    
ss.write("test.sgy", format='SEGY')
print("done writing.")
ss.write("test1.sgy", format='SEGY')
print("done writing.")
`

My second problem is related to the distance, but I may need to launch a new issue. With this example I can read and plot the empty segy. With the real data for some reason the `trace.stats.distance` is apparently not being persisted and is undefined.

**Comment by alex0sunny** [comment]
To @rmlopes 
I've figured out that the second attempt won't rise an error if you fill binary header as below.

  ss.write("d:/temp/test.segy", format='SEGY')
  print("done writing.")
  ss.stats.binary_file_header = SEGYBinaryFileHeader()
  ss.stats.binary_file_header.data_sample_format_code = 5 
  ss.write("d:/temp/test1.segy", format='SEGY')
  print("done writing.")

**Comment by sumitav** [comment]
I am getting "writing format segy is not support " whenever I am using stream object to write into segy file.
Kindly help me with this issue.

**Comment by alex0sunny** [comment]
Maybe that's because you have data type float64 instead of float32. And don't forget to explicitly point data_encoding.
The following should work.

  from obspy import read
  st = read()
  for tr in st:
    tr.data = tr.data.astype('float32')
  st.write('temp.segy', data_encoding=5)

**Comment by sumitav** [comment]
I have a very large file so am reading it trace by trace using iread_segy,**Can you please tell how can i extract traces from particular section like from 321 inlines,17-1000  crosslines.**

Kindly help me with this issue.

**Comment by krischer** [comment]
I answered that question in the other issue. Please don't post duplicate questions.

**Comment by sumitav** [comment]
**Have a nd array need to convert that to segy file with necessary default headers but the problem am facing is have converted that array to segy file but its not 3d,where i can't acces x_inline and other parameters.
Can you please tell me how can I convert that nd array say(seismic) to a seg-y file which is 3-d using OBSPY**

**Comment by megies** [comment]
@sumitav these questions are off-topic as far as I can see. Also I don't even understand the last question. In any case, for usage questions, please go via the users mailing list, but be sure to explain better what you are trying to do and what is not working with **short** and self-contained example code, otherwise the chances are slim that you get help.

**Comment by sumitav** [comment]
I was asking how to convert a numpy array(as data) to segy file.Previously have converted the same to segy file but it's 2d in nature i.e., I can't create 3d parameters say depth at particular inline/crossline,,can't define inline and cross line of my own etc etc..
**So given a 3d numpy array how to convert that to a seg-y file with necessary headers and data.**???
Can you please solve this

**Comment by megies** [comment]
@sumitav one last time, please stop posting off-topic in this thread and use the users mailing list for usage questions.

**Comment by megies** [comment]
stale, closing.
