### ISSUE TITLE
Consider switching conda packaging to conda-forge

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1404]
We should check if moving all conda packaging to @conda-forge is a good option for us.
See details in https://github.com/ContinuumIO/anaconda-issues/issues/757#issuecomment-218179202.

**Comment by krischer** [comment]
👍 We should totally do that. AFAIK they also plan to make `conda-forge` a default channel for conda in the long run.

**Comment by megies** [comment]
See conda-forge/staged-recipes#582.

**Comment by megies** [comment]
Already implemented for 1.0.2
