### ISSUE TITLE
Handling of invalid times when parsing SEED volumes (xseed).

### ISSUE THREAD

**Issue by petrrr** [obspy/obspy#1410]
I came across a SEED dataless file which had time set to `24:00:00.0000` in epoch time spans. Even if to some extent it might make sense to indicate the the time span ends with that day, according to the SEED Manual this is not really standard compliant. 

Nonetheless, some programs seems not to enforce this or are resilient, e.g. PDCC and some seiscomp tools. What adds a bit to the confusion and makes it difficult to understand the issue is that Obspy in such a case just silently ignores the value. So if the time is supposed to close an epoch, the parse representation is interpreted as an open ended epoch.

Therefore, I would propose that the behavior wrt parsing invalid datetime value is somewhat modified. I see the following possibilities:
- generate a warning or even an error so that it becomes obvious that the file is not fully compliant;
- accept some invalid values;
- accept some invalid values and generate a warning;

No clear idea what is the best, therefore I start this with as issue. I can provide an PR, once this is discussed and settled.
## 
- ObsPy version, Python version and Platform (Windows, OSX, Linux ...)

Version 1.0.1, Python 3.4.4, OSX/Macports
- How did you install ObsPy and Python (pip, anaconda, from source ...)

Macports
- If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/) that demonstrates the issue i.e a small piece of code which reproduces the issue and can be run with out any other (or as few as possible) external dependencies.

Will provide an example dataless if this is relant
- If this is a regression (Used to work in an earlier version of ObsPy), please note where it used to work.

Not investigated

**Comment by megies** [comment]
> Therefore, I would propose that the behavior wrt parsing invalid datetime value is somewhat modified. I see the following possibilities:
> 
>    * generate a warning or even an error so that it becomes obvious that the file is not fully compliant;
>    * accept some invalid values;
>    * accept some invalid values and generate a warning;

I'd probably go with option 3 if this is really widespread.

**Comment by megies** [comment]
stale, closing.
