### ISSUE TITLE
obspy.taup - Missing core phases in the absence of inner core

### ISSUE THREAD

**Issue by sceylan** [obspy/obspy#1423]
Hi,

I think there is a bug in the TauP package (also might go with #1200):
[I am using obspy version 1.0.1 installed with conda 4.0.6 under python 2.7.11]

I just tested obspy.taup package using a structure file representing Mars w/wo an inner core. The core phases (e.g. PKP, SKS etc) are not populated when there is no inner core. Of course there will be no **I/i** phases, but the **K** phases should exist. When I implement a small inner core (with 0.5 km radius) in the model file, the travel times for the related phases are computed. 

Here is an example output from my script for a source at distance=100 degrees and depth=50 km for three phases; SS, SKKS, SKS [this one is in shadow zone according to the model].

```
WITH INNER CORE:
        SS phase arrival at 1377.796 seconds [JavaTauP=1377.80]
        SKKS phase arrival at 1850.966 seconds [JavaTauP=1850.97]

NO INNER CORE:
        SS phase arrival at 1377.796 seconds
```

This is also an issue for the recent pre-release Java version of 2.3.0. I haven't tested it with the latest official release as I just realized there is one. 

And here are the nd files I used for testing:
[ModelDW-BFGeoth.noInnerCore.nd.txt](https://github.com/obspy/obspy/files/280682/ModelDW-BFGeoth.noInnerCore.nd.txt)
[ModelDW-BFGeoth.nd.txt](https://github.com/obspy/obspy/files/280684/ModelDW-BFGeoth.nd.txt)

 Edit: Stefanie Hempel realized this problem initially with earlier Java versions and she was working on solving this. Maybe she found one.

**Comment by krischer** [comment]
Oh nice - I just tried out the model mentioned in #1200 again and it now mostly works - there are still a couple of stray raypaths but it is much better then before so we might be pretty close to get the code working for non-earth planets.

We did remove all hard coded radii and what not but parts of the code might still assume that any model has at least the same discontinuities (moho, cmb, icmb) as Earth so that might be a part of the problem. If you solved the problem in the java version please let us know - our code started out as a straight port so any fixes should be pretty easy to transfer.

**Comment by stefaniehempel** [comment]
I solved the issue for the Java TauP version. I'll upload that in a few days. Will post the link here.
It is basically only the issue, that it sets iocbBranch==cmbBranch if it doesn't find an inner core, and consequently PcP have the same ray paths as PKiKP, and no wave travel into the core (for Mars models). It's easy to fix this in the class SeismicPhase.

**Comment by krischer** [comment]
Great :-)

Another question: Do all Mars models have a Moho? I don't think the current code works without one. If yes we should be fine here - models of other planets beside Earth and Mars are I guess currently of little interest to the community.

**Comment by sceylan** [comment]
All the models we have handled so far includes a Moho. As far as I know, we are pretty sure that Mars has a Moho discontinuity. If this helps, I ran the java code with a rather smooth gradient at the Moho and it still worked.

**Comment by krischer** [comment]
> I solved the issue for the Java TauP version. I'll upload that in a few days. Will post the link here.
> It is basically only the issue, that it sets iocbBranch==cmbBranch if it doesn't find an inner core, and consequently PcP have the same ray paths as PKiKP, and no wave travel into the core (for Mars models). It's easy to fix this in the class SeismicPhase.

@stefaniehempel Just a quick reminder ;-)

**Comment by megies** [comment]
Just a ping, @stefaniehempel

**Comment by megies** [comment]
Closing this on the assumption that it's likely now fixed in master
