### ISSUE TITLE
reftime parameter for trim, slice and cutout

### ISSUE THREAD

**Issue by trichter** [obspy/obspy#1425]
From time to time I am writing code like

```
for tr in stream:
    tr.trim(tr.stats.starttime + 10, tr.stats.starttime + 50)
```

It'd be nice to just write

```
stream.trim(10, 50, reftime='starttime')
```

reftime would be an attribute of stats holding a UTCDateTime instance. It could also accept UTCDateTime itself.

Any opinions?

**Comment by krischer** [comment]
You can almost do this already: if you pass integers/floats they will be interpreted as offsets to start- and end time.

But I do like the idea - a general way of doing this is cleaner! I'm a bit torn about a magical string parameter that gets resolved to a time while it is run but I don't see another way to do it for multi-trace streams.

**Comment by trichter** [comment]
Oh, didn't expect that. Then, some code in Stream.trim will raise an Exception:

```python
In [13]: read().trim(5, 5, nearest_sample=True)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-5465512edf03> in <module>()
----> 1 read().trim(5, 5, nearest_sample=True)

/home/richter/anaconda/lib/python2.7/site-packages/obspy/core/stream.pyc in trim(self, starttime, endtime, pad, nearest_sample, fill_value)
   1507             if starttime:
   1508                 delta = compatibility.round_away(
-> 1509                     (starttime - tr.stats.starttime) * tr.stats.sampling_rate)
   1510                 starttime = tr.stats.starttime + delta * tr.stats.delta
   1511             if endtime:

TypeError: unsupported operand type(s) for -: 'int' and 'UTCDateTime'
```

The suggested interface would not be compatible with the current interpretation of numbers for start/endtime. (Both values relative to one reftime vs offsets to start and end time)

**Comment by megies** [comment]
Hmm.. I'm not super convinced this is really necessary. And I'm also a bit wary about the string magic.

**Comment by trichter** [comment]
It's handy if you've got traces from multiple events, but I don't have any strong opinion weather it should be included or not.

**Comment by krischer** [comment]
> Oh, didn't expect that. Then, some code in Stream.trim raises an Exception:

Ah that's annoying...it works with `Trace.trim()` though. We should probably fix at least that.

**Comment by claudiodsf** [comment]
Upvoted

**Comment by trichter** [comment]
Another related bug

```
In [3]: read()[0].trim(3, 2)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-f1d9253715ab> in <module>()
----> 1 read()[0].trim(3, 2)

<decorator-gen-132> in trim(self, starttime, endtime, pad, nearest_sample, fill_value)

/home/richter/anaconda/lib/python2.7/site-packages/obspy/core/trace.pyc in _add_processing_info(func, *args, **kwargs)
    229     info = info % "::".join(arguments)
    230     self = args[0]
--> 231     result = func(*args, **kwargs)
    232     # Attach after executing the function to avoid having it attached
    233     # while the operation failed.

/home/richter/anaconda/lib/python2.7/site-packages/obspy/core/trace.pyc in trim(self, starttime, endtime, pad, nearest_sample, fill_value)
   1077         # check time order and swap eventually
   1078         if starttime and endtime and starttime > endtime:
-> 1079             raise ValueError("startime is larger than endtime")
   1080         # cut it
   1081         if starttime:

ValueError: startime is larger than endtime
```

**Comment by trichter** [comment]
I am going to close this one. The mentioned bugs are handled in #2317. The original idea with the reftime parameter was kind of rejected.
