### ISSUE TITLE
Colormapped gap markers in `obspy-scan`

### ISSUE THREAD

**Issue by krischer** [obspy/obspy#1434]
Proposal from the mailing list:http://lists.swapbytes.de/archives/obspy-users/2016-June/002075.html

Should be easy enough and seems like a very good idea!

> Hi
> 
> I don't know who wrote obspy-scan.
> Just I would like to submit an improvement suggestion : should that be possible to make the red vertical bar representing a gap of data in a color scale going from yellow to dark red (could be a logarithmic scale from 10sec to 1d for instance and saturated at the extrem values) depending of the length in sec of the gap.
> 
> I will help to quickly recognize if gaps are important or less important in a global analysis of one year for instance.
> 
> Thanks
> 
> Anne

**Comment by ThomasLecocq** [comment]
While at it, I'd suggest merging continuous chunks of "continuous data markers", that would reduce greatly the number of drawn polygons, e.g. when exporting to PDF.

**Comment by megies** [comment]
Hmm, I'm a bit torn about this one. That would add several more command line arguments to an already pretty cluttered command line interface.. (people might want to customize the limits for the colormap and of course the colormap itself) also.. which colormap to choose? An obvious choice would be a divergent colormap (one end gaps, other end overlaps).. or only differnet colors for gaps?

Many, many options..

A different approach would be to modify the figure after it's initial creation.. with the refactoring that is currently in #1413 it would be simple to use the scan routine from inside a Python script and work on the figure afterwards..
One could cycle through the patches and recolor according to their width in any desired custom fashion..

Really not sure what to do about this..

> While at it, I'd suggest merging continuous chunks of "continuous data markers", that would reduce greatly the number of drawn polygons, e.g. when exporting to PDF.

Off topic.. :stuck_out_tongue_winking_eye:   (gaps/overlaps are merged already..)

**Comment by krischer** [comment]
Hmm..valid point but I still think this would increase the information content of the plots quite a bit. Maybe a single argument akin to the following could work?

`--gap-markers="red"`
`--gap-markers="bwr,-86400,86400`

Thus only two choices - either a single solid color or a colormap with upper and lower saturation limits. IMHO we should also make the colorscale logarithmic no matter what.

**Comment by megies** [comment]
stale, closing.
