### ISSUE TITLE
Duplicated channes in mseed

### ISSUE THREAD

**Issue by heavelock** [obspy/obspy#1438]
Hi!

I think I found a bug in obspy.read module that might be connected with some kind of corruptness of mseed file. I've checked it on two installations of python on different workstations.

First one:
Windows 10, x64
Fresh installation of Anaconda3 4.0.0 with python 3.5
Obspy 1.1.0 installed by pip
This config was prepared just a while before for purpose of quick checking the content of seed files.

My config:
Windows 10, x64
Anaconda 3
Python 3.4
Obspy 1.0.0, I don't remember whether installed via pip or conda.

What is the bug about?
We are using in observatory SWIP programme for quite a lot of tasks. After reading an attached mseed file it's producing plot that contains 16 channels. There are no duplicates but there are channels that are empty or contain only a few samples. Screenshot:
![swip](https://cloud.githubusercontent.com/assets/10303802/15774297/e4fd3b00-297b-11e6-961b-bb3a3dbb0a23.PNG)

The same file opened in ObsPy (just obspy.read()) contains 19 channel with 3 duplicates. Screenshot:
![obspy_read](https://cloud.githubusercontent.com/assets/10303802/15774306/f33fcc3c-297b-11e6-8f1b-b83cb4f206db.PNG)

The strangest thing is that the obspy.read().plot() function is producing a plot with 16 channels and without dupes. Screenshot:
![figure_1](https://cloud.githubusercontent.com/assets/10303802/15774326/0ed1a542-297c-11e6-9b7e-cfbe0cc750af.png)

Here is the mseed file that I'm writing about. I'm using dropbox since the file is too large for attaching to the post.
https://www.dropbox.com/s/6yeiwesu5gepm6k/problematycznyplik.mseed?dl=0

To be honest, I don't know why that happened but the size of 30k samples that are in duplicated channels looks a bit suspicious for me.

**Comment by krischer** [comment]
The plotting method will merge data from the same channel. `automerge=True` will turn that off.

I also don't see any duplicates but the data from the TBVH station has gaps and thus each channel is represented by two Traces.

This is also represented in the plot.

Its a bit strange that each trace from that station has exactly 30k samples but this is not ObsPy's fault - it is the same in the plot you made with your tool. Both plots IMHO show exactly the same.

**Comment by heavelock** [comment]
Well, I think the automerge solves everything.

Thanks for your reply and I'm sorry for bothering you.

**Comment by krischer** [comment]
You are welcome :-)
