### ISSUE TITLE
taup geo should raise Error without geographiclib, not warning

### ISSUE THREAD

**Issue by MMesch** [obspy/obspy#1441]
the taup_geo routine raises only a warning right now if geographiclib is not installed. I think this should raise a true Exception instead because calling the _geo routines is useless without geographiclib. In case someone doesn't want the geographical information he can call the other functions and/or he should mention it explicitly with a keyword in this routine.

**Comment by krischer** [comment]
I agree - there is also another issue where we discuss to just make geographiclib a hard dependency.

**Comment by megies** [comment]
stale, closing.
