### ISSUE TITLE
Guralpe Compressed Format (GCF) read support

### ISSUE THREAD

**Issue by rannof** [obspy/obspy#1446]
Hi,
It there a read plugin for GCF format? I made a module for reading waveforms in this format (no writing option yet). The module is based on one of the io formats (core,libgcf,__init__), but I think there is more to it in order to add it to obspy read function. 
Also, I'm not sure about copyrights, though all format specifications are available online with license details: [http://www.guralp.com/apps/ok?doc=GCF_Intro](http://www.guralp.com/apps/ok?doc=GCF_Intro)
If there is an interest, please let me know.

**Comment by megies** [comment]
The code itself, if written by yourself and not reusing libraries (from Guralp or some other third party), is not bound to any licensing from third parties. We can just include it under LGPL that is the license for all of ObsPy (see #827).
The specs seem to have a strange license, so we'll just simply not include that document within ObsPy.

If you have code to read gcf format, we'd be happy to include it. Just make a new branch off `master` and drop what you have under `io/gcf/`. I can make this issue into a PR then. I've added you to developers team, if you push your branch to obspy/obspy it's easier for other people to add changes. Once we see what is already there we can help with comments on what to do next.

**Comment by rannof** [comment]
OK, I added a pull request #1449 with the module. I also included a utility for converting files to other formats and just added it to io module (not sure where is the right place). I'm still new to the github and not sure if I done things properly.
Cheers,
Ran

**Comment by megies** [comment]
Thanks for the PR. Next time just push the branch and let us know, we [could have made this very ticket into a PR](https://github.com/obspy/obspy/wiki/Interesting-Reading-on-Git%2C-GitHub), avoiding duplicated tickets.
