### ISSUE TITLE
tr.times("matplotlib") fails

### ISSUE THREAD

**Issue by mat2py** [obspy/obspy#1462]
Input:
```
tr = str1[0]
tr.times("matplotlib")
```

Error message:

```
Traceback (most recent call last):

  File "<ipython-input-16-587655343cda>", line 1, in <module>
    b = tr.times('matplotlib')

TypeError: times() takes exactly 1 argument (2 given)
```

**Documentation:**
[link](https://docs.obspy.org/master/packages/autogen/obspy.realtime.rttrace.RtTrace.times.html)

**Other documentation without the inputs:**
[link](https://docs.obspy.org/packages/autogen/obspy.core.trace.Trace.times.html#obspy.core.trace.Trace.times)

**Examples of what should happen given in:**
[link](https://docs.obspy.org/master/tutorial/code_snippets/waveform_plotting_tutorial.html)

**Setup:**
Obspy version: 0.10.2
Python version: 2.7
Platform: Linux, Ubuntu 15.10
Installation: Anaconda

**Comment by krischer** [comment]
You need to update to the latest master - this version is not yet part of the latest released version (beside you are also using an outdated version).

Doc for 1.0.1: http://docs.obspy.org/packages/autogen/obspy.core.trace.Trace.times.html
Doc for master: http://docs.obspy.org/master/packages/autogen/obspy.core.trace.Trace.times.html

**Comment by mat2py** [comment]
Could you guide me how to do that? I tried an update through Anaconda:
`conda update obspy`
and that told me I didn't need to update.

I then followed the method [here](https://github.com/obspy/obspy/wiki/Installation-via-Anaconda) with:
`conda config --add channels obspy
conda create -n obspy1.01 python=2.7`

but after restarting Spyder, the function still fails. Is there some other way to update it / what version am I looking for?

Thanks in advance

**Comment by krischer** [comment]
You'll have to uninstall obspy and install from git:

```bash
$ conda uninstall obspy
$ cd /place/to/where/you/put/code
$ git clone https://github.com/obspy/obspy.git
$ cd obspy
$ conda install pip
$ pip install -v -e .
```

**Comment by mat2py** [comment]
This worked great, thanks!

FOr others who comes across this, the /place/to/where/you/put/code, if you're using anaconda, is likely to be:

`~/anaconda2/lib/python2.7/site-packages`

**Comment by krischer** [comment]
I actually intended this to be the place where you keep around source codes. If you want to install to the `site-packages` directory you can just do `pip install -v .` without the `-e`. The `-e` will create and editable installation meaning it will only place a file pointer to `site-packges`. Thus any time you `git pull` in the repository, it will also update your ObsPy installation.

**Comment by mat2py** [comment]
Ahh okay - I wondered how people did that! Thanks again for the clear explanations (it's a rare thing when it come to linux module installations)
