### ISSUE TITLE
Read/write support for eventtxt format

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1467]
We should add read/write support for the txt format for events as defined by FDSNWS specifications.

**Comment by jkmacc-LANL** [comment]
@megies Seems like there'd be a fair amount of common functionality with `stationtxt`, like parts of the reading and writing functions.  Could it look something like this?
```
io/
   stationtxt/core.py 
      station_text_to_inventory, inventory_to_station_text, is_fdsn_station_text_file, _write_stationtxt
   eventtxt/core.py
      event_text_to_catalog, catalog_to_event_text, is_fdsn_event_text_file, _write_eventtxt
   _fdsn_text_common.py 
      unicode_csv_reader, utf_8_encoder, utcdatetime_or_none, float_or_none, _format_time,
      read_fdsn_text_file (refactored from read_fdsn_station_text_file),
      write_fdsn_text_file (refactored from _write_stationtxt)
```

**Comment by megies** [comment]
Yeah.. sounds like a good idea 👍

**Comment by krischer** [comment]
Or maybe

```
io/
    txt(or csv)/stationtxt.py
                eventtxt.py
                common.py
```

so it does not clutter then main `io` module?

**Comment by megies** [comment]
Also good, we already have `io/ascii` maybe just move everything there..

**Comment by barsch** [comment]
we also got ```io.ascii``` with TSPAIR and LIST formats ^^

I owuld leave it separate modules if written by different people

**Comment by jkmacc-LANL** [comment]
If `eventtxt` is free to move, maybe this would work:
```
io/
    fdsntext/
        common.py
        stationtxt.py
        eventtxt.py
```

**Comment by krischer** [comment]
👍 IMHO the best proposal so far.

**Comment by megies** [comment]
> If eventtxt is free to move

Should be OK, not intended to be used on low-level and experienced users should be able to adapt..

**Comment by markcwill** [comment]
I think the format is a couple of instances of this general [GeoWS](http://data.geows.org/documents/) proposed format. 
It was originally called WSTF, and now looks like it's being called GeoCSV:
http://data.geows.org/documents/GeoCSV.pdf

So, IMO you're either:
1) writing a python `geocsv` module, and then implementing those two formats as instances/schemas,
2) just keep the eventtxt and stationtxt 2 completely separate formats - write `csv.DictReader` & `csv.DictWriter` funcs for them individually, maybe some minimal overlap in entyping functionality, but if another format comes out, then you're basically doing (1).

Thoughts?

**Comment by megies** [comment]
Wasn't aware of the GeoWS, nice insights there, thanks @markcwill!

**Comment by krischer** [comment]
Is that like a CSV with more semantic meaning and georeferencing? Seems pretty nice eespecially for domains where you have less agreed upon standards :)

In any case - this would make almost no practical difference for us as we still would need to define what csv field maps to what attribute of what object. In the end it would look very similar to what we have right now and in the proposed module structure it would go in `common.py`. So the `common.py` could just be some generic CSV reading functionality that maybe does some type conversions and checks that everything is available and the two specialized  implementations would use that.

**Comment by jkmacc-LANL** [comment]
FDSN station text and event text don't look like they quite conform to GeoCSV, no? [(example stationtxt](https://service.iris.edu/fdsnws/station/1/query?network=TA&station=A*&channel=BH?,-BHZ&level=station&format=text),  [example eventtxt)](https://service.iris.edu/fdsnws/event/1/query?minmagnitude=8.5&format=text) I like the idea of supporting a flexible format that has some buy-in [(AGU poster)](http://data.geows.org/documents/IN11F-1809-geocsv_poster.pdf), but would it even work with FDSN station/event text at this point?  It doesn't look like it'd be too much work to just make `io.stationtxt.read_fdsn_station_text_file` generic enough to read both station text and event text.  If FDSN text format switches to GeoCSV proper, perhaps that'd be the time to consider support.

**Comment by trichter** [comment]
FYI, I implemented a basic eventtxt reader over at [obspycsv](https://github.com/trichter/obspycsv).

**Comment by megies** [comment]
We should add that in obspy directly. Both reading and writing would be really valuable to have in there.

**Comment by trichter** [comment]
@megies, could you have a look at obspycsv? Do you think it would be fit to be included in obspy? It would be straightforward to add eventtxt write support. Additionally, I suppose I had to find out how the fields, which are not handled yet, could be mapped to the Event object.

**Comment by megies** [comment]
@trichter yea, sure, i don't see why not from looking at the module :+1:
