### ISSUE TITLE
python setup.py clean has side effects.

### ISSUE THREAD

**Issue by ghisvail** [obspy/obspy#1488]
Running `python setup.py clean` overwrites the version file `obspy/RELEASE-VERSION`. Is this intended ?

**Comment by megies** [comment]
Version lookup is non trivial, mainly so that we are able to see meaningful version number information when testing on development branches (seeing the exact commit that was tested). There's basically three scenarios for installation with regard to version lookup / the `RELEASE_VERSION` file:

 a) installation of a source distribution or a release version binary
    -> `RELEASE_VERSION` is part of the distribution and used for version lookup and there's no reason to do `python setup.py clean`
 b) installation from a git repository
    -> version is determined via git and `RELEASE_VERSION` is updated accordingly
 c) installation from a non-source-distribution tarball (e.g.https://github.com/obspy/obspy/archive/master.zip)
    -> version can not be determined

How are you affected exactly?

**Comment by ghisvail** [comment]
I am building an official Debian package for `obspy`, meaning the source of the latest release are uploaded pristinely to a packaging repository and a debianization is performed on a separate branch. As a result, the version in RELEASE_VERSION should not be changed but even a call to `clean` (which is the first step of the package build process) alters the source by rewriting the RELEASE_VERSION file.

Right now, I am overcoming this by overriding the clean target to rewrite the appropriate version in RELEASE_VERSION after the standard call to `python setup.py clean`, but this is far from ideal. I am also patching the _get_git_version() function to bypass querying the version from git and always use RELEASE_VERSION. Both combined allows me to have a clean build (nothing gets rewritten), and have adequate version numbers in the Python package metadata as well as the manpages.

Quite a lot of work to overcome a single side effect as you can see. Perhaps, there is a better one I did not think of, in this case please feel free to provide suggestions.

**Comment by ghisvail** [comment]
Regarding the scenarii you listed, the Debian build may be attempted from the packaging repository (a+b) or from a debianized source release (a). Both should ideally produce the same result, i.e. the content of `obspy/RELEASE_VERSION` is not touched. 

> there's no reason to do `python setup.py clean`

In your perspective, probably not. However, a condition to check that packaging is done cleanly is that the build can be performed twice in a row (also used for reproducibility testing) without tempering the original sources.

**Comment by megies** [comment]
Why do you need to do debian packaging yourself? Is your distribution not part of those that we provide packages for?

There are build scripts for debian packaging in the repository, also see e.g. [this branch I use for packaging](https://github.com/megies/obspy/tree/deb_1.0.2) and [the single commit to hard code the version in debian builds](https://github.com/megies/obspy/commit/4461555f55ad64fa4f2ee42463660914be6419af).

**Comment by ghisvail** [comment]
> Why do you need to do debian packaging yourself?

There is an interest in having `obspy` [officially](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825954) packaged in Debian and derivatives.

> There are build scripts for debian packaging in the repository

I saw them, and they are a good start. However, they are not (entirely) compliant with our Debian packaging policies. Perhaps you would like to get involved in the packaging effort on the Debian side? In case you have not read it, please have a look at the [Debian for upstream](https://wiki.debian.org/UpstreamGuide) page.

> version.py should be patched to not rely on RELEASE_VERSION

Packaging is always done (at least on our end) on a release version, so why not then?

**Comment by megies** [comment]
> There is an interest in having obspy officially packaged in Debian and derivatives.

Oh, cool. I never decided to go down that road because ObsPy development was still too volatile for the long term stable Debian release cycle..

> I saw them, and they are a good start. However, they are not (entirely) compliant with our Debian packaging policies. Perhaps you would like to get involved in the packaging effort on the Debian side? In case you have not read it, please have a look at the Debian for upstream page.

Yes, I'm aware that our packaging approach is not the usual Debian way. Never bothered to change it.. never change a running system. ;-)

I can try to help to tackle problems when you set up a Debian-kind of Debian packaging workflow..

>> version.py should be patched to not rely on RELEASE_VERSION
> 
> Packaging is always done (at least on our end) on a release version, so why not then?

So, it's not enough to have the release version file in the source distribution tarball? I'm not sure if it will be easy to get `python setup.py clean` to restore the state of the freshly unpacked source dist tarball..

**Comment by ghisvail** [comment]
> So, it's not enough to have the release version file in the source distribution tarball?

Actually, I believe it should be enough. It is just that, at the moment, `obspy` prioritize on looking up the version from `git`, over reading the existing value from `obspy/RELEASE_VERSION`, hence the side effect.

> I'm not sure if it will be easy to get python setup.py clean to restore the state of the freshly unpacked source dist tarball.

I don't think it is the right solution long-term anyway. Conceptually, the `get_git_version` function also does 2 things, i.e. query the version string and write it in a file. Perhaps splitting both actions could help.

**Comment by megies** [comment]
> obspy prioritize on looking up the version from git, over reading the existing value from obspy/RELEASE_VERSION

Sure, it wouldn't work for us the other way round.. but should be easy enough to resolve with a patch in deb packaging.

**Comment by megies** [comment]
Hmm.. actually, when I unpack [the current RC source dist tarball](https://www.geophysik.uni-muenchen.de/~megies/obspy-1.0.2rc6.zip) and run the following commands..

```bash
$ python setup.py install
$ python setup.py clean
$ python setup.py develop
$ python setup.py clean
```

.. `RELEASE-VERSION` file is not changed. The only files that change for me are:

![screenshot from 2016-07-31 13 58 20](https://cloud.githubusercontent.com/assets/1842780/17276336/df426da6-5726-11e6-96d3-81bf09fa48ee.png)

**Comment by ghisvail** [comment]
@megies sure, since the content of the tarball is not contained in a git repository.

In the case of the Debian packaging repository, the release tarball is hosted on one branch plus some additional commits regarding the debianization. Then, when launching the build from there (starting with a call to `clean`), the `obspy` versioneer tries to pick a git version from the packaging repository, instead of using the release version.

Worse, it then rewrites the content of `obspy/RELEASE_VERSION` with the output of `git describe` which picks up the Debian specific tag format. The latter is different from the one you guys use in the upstream repository: we use `upstream/$VERSION` instead of just `$VERSION`. Consequently,  when the build is run from the packaging repository, `obspy` writes a non-conforming version number in `obspy/RELEASE_VERSION`, for instance `upstream/1.0.1{+additional cruft from git describe+dirty}` instead of just `1.0.1`. Let me know whether my explanation was not clear enough.

I understand this issue is somewhat specific, and you guys might be tempted to classify it as a non-fix as a result. The fundamental issue still remains though: calling `python setup.py clean` can produce unexpected artifacts to the source tree.

**Comment by megies** [comment]
> Let me know whether my explanation was not clear enough.

Yes, I understand the problem now.

Can't you just add a patch in the deb packaging to change the version number lookup? You could patch it in a couple of places (e.g. in top-level `__init__.py` where `__version__` is set) but safest would be to patch `obspy.core.util.version.get_git_version` like this:

```diff
diff --git a/obspy/core/util/version.py b/obspy/core/util/version.py
index df0ea7d..b6179da 100644
--- a/obspy/core/util/version.py
+++ b/obspy/core/util/version.py
@@ -139,31 +139,6 @@ def write_release_version(version):
 def get_git_version(abbrev=10, dirty=True, append_remote_tracking_branch=True):
     # Read in the version that's currently in RELEASE-VERSION.
     release_version = read_release_version()
-
-    # First try to get the current version using “git describe”.
-    version = call_git_describe(
-        abbrev, dirty=dirty,
-        append_remote_tracking_branch=append_remote_tracking_branch)
-
-    # If that doesn't work, fall back on the value that's in
-    # RELEASE-VERSION.
-    if version is None:
-        version = release_version
-
-    # If we still don't have anything, that's an error.
-    if version is None:
-        return '0.0.0+archive'
-
-    # pip uses its normalized version number (strict PEP440) instead of our
-    # original version number, so we bow to pip and use the normalized version
-    # number internally, too, to avoid discrepancies.
-    version = _normalize_version(version)
-
-    # If the current version is different from what's in the
-    # RELEASE-VERSION file, update the file to be current.
-    if version != release_version:
-        write_release_version(version)
-
     # Finally, return the current version.
     return version
```

**Comment by ghisvail** [comment]
This is the patch I ended up using:
```
From: Ghislain Antony Vaillant <ghisvail@gmail.com>
Date: Sat, 30 Jul 2016 10:10:27 +0100
Subject: Bypass version query with git.

---
 obspy/core/util/version.py | 5 ++---
 1 file changed, 2 insertions(+), 3 deletions(-)

diff --git a/obspy/core/util/version.py b/obspy/core/util/version.py
index df0ea7d..6842a37 100644
--- a/obspy/core/util/version.py
+++ b/obspy/core/util/version.py
@@ -141,9 +141,8 @@ def get_git_version(abbrev=10, dirty=True, append_remote_tracking_branch=True):
     release_version = read_release_version()
 
     # First try to get the current version using “git describe”.
-    version = call_git_describe(
-        abbrev, dirty=dirty,
-        append_remote_tracking_branch=append_remote_tracking_branch)
+    # Debian: version query with git is disabled.
+    version = None
 
     # If that doesn't work, fall back on the value that's in
     # RELEASE-VERSION.
```
That was the least invasive patch I could come up with.

**Comment by megies** [comment]
So, are there still problems for packaging? Asking, because the next release is imminent (this week) and we would try to get any issues for you solved before releasing..

**Comment by ghisvail** [comment]
Unfortunately. The good news is that my independent audit did not find any other problems besides this. It would have been nice that the status of `evalresp` be explicited upstream instead of here, but it is properly referenced in #827 so it should be fine on our end.

**Comment by krischer** [comment]
The `call_git_describe()` method does check the root folder of the git repository and returns `None` if it is not the expected one. So I assume the tarball is just unpacked into the root level of the git branch in the debian packaging repository? Or does the `call_git_describe()` method not work as expected?

The patch could be avoided in one of two ways:

* In the debian packaging repository, just move everything to a subfolder. I'm not sure if this is feasible from your side.
* We could do a simple regex check in `call_git_describe()` to see if the version number matches the expected pattern. This is based on several assumptions but it would work for this particular case here and its only a single line so why not.

**Comment by megies** [comment]
> The patch could be avoided in one of two ways:
> 
>    - In the debian packaging repository, just move everything to a subfolder. I'm not sure if this is feasible from your side.
>    - We could do a simple regex check in call_git_describe() to see if the version number matches the expected pattern. This is based on several assumptions but it would work for this particular case here and its only a single line so why not.

@krischer  I'm not sure that would be 100% safe. Also, canonical debian packaging is rather rigid, so I think moving things away from their expected places is more cause for problems than a simple patch. Patches are rather common in debian packaging and I don't think our version number routine will change a lot in the near future, so keeping that very tiny patch around in packaging should be fine (patches are also applied loosely, e.g. not rigid with the line numbers, no need to change the patch as long as the code diff still applies).

**Comment by ghisvail** [comment]
> So I assume the tarball is just unpacked into the root level of the git branch in the debian packaging repository?

Exactly. A pristine copy of the source is stored in an upstream branch and the packaging is done in a packaging branch, onto which new upstream releases are merged.

> Or does the call_git_describe() method not work as expected?

I believe it does work as you guys expect for the upstream repository, but the assumptions behind the output of `git describe` are not verified for the packaging repository. Besides, regardless of the history of the packaging branch, `RELEASE_VERSION` should not be changed since we work with released versions only.

> The patch could be avoided in one of two ways:

Considering how light the patch is, I don't mind keeping it downstream TBH.

**Comment by ghisvail** [comment]
> so keeping that very tiny patch around in packaging should be fine

:+1:

**Comment by krischer** [comment]
I think this can be closed. Please reopen if I am mistaken.
