### ISSUE TITLE
Docker tests should be run on open+updated PRs

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1489]
..that would help to fix issues with docker tests during development already (docker tests are run nightly), and we would need far less release candidates when releasing.

~~https://github.com/obspy/obspy/blob/master/misc/scripts/docs_buildbot/update_pull_request_status.py~~

Sending commit status is already implemented in #1487.

**Comment by krischer** [comment]
Are they not run only on the `master` branch? We could make a simple badge and add it to the readme.

**Comment by megies** [comment]
> Are they not run only on the master branch?

Currently yes, but I want to change the cronjob script to run them also on open+updated PRs..

**Comment by krischer** [comment]
Nice. If it takes too long you could just run the docker tests with the two oldest images (centos 7 and debian 7) as most other things should be caught by the travis and appveyor tests.

**Comment by megies** [comment]
> Nice. If it takes too long you could just run the docker tests with the two oldest images (centos 7 and debian 7) as most other things should be caught by the travis and appveyor tests.

I think it should be OK, once the images are set up (fresh once per day) we can run one PR tip through all docker images in roughly one hour.

**Comment by megies** [comment]
This is currently being implemented and should work now, see #1487.
