### ISSUE TITLE
Licensing incompatibility in vendored libmseed source code

### ISSUE THREAD

**Issue by ghisvail** [obspy/obspy#1492]
Whilst inspecting the copyright of the `obspy` files (a necessary evil of the Debian packaging process), I encountered the following inconsistency:

According to the `libmseed` README located at `obspy/io/mseed/src/libmseed`, the library is released under GPL-2+. However the source code of `libmseed` contains a file named `unpackdata.c` with the following copyright notice:

```c
/*
 * Copyright (c) 1996 The Regents of the University of California.
 * All Rights Reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for educational, research and non-profit purposes,
 * without fee, and without a written agreement is hereby granted,
 * provided that the above copyright notice, this paragraph and the
 * following three paragraphs appear in all copies.
 *
 * Permission to incorporate this software into commercial products may
 * be obtained from the Office of Technology Licensing, 2150 Shattuck
 * Avenue, Suite 510, Berkeley, CA  94704.
 *
 * IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
 * FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
 * INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND
 * ITS DOCUMENTATION, EVEN IF THE UNIVERSITY OF CALIFORNIA HAS BEEN
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE
 * PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
 * CALIFORNIA HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT,
 * UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 */
```

In particular, the following part: Permission to use, copy, modify, and distribute this software and its documentation for **educational, research and non-profit purposes**, makes this code non-freely redistributable. According to the corresponding `Makefile`, this file is listed in the source used for compilation of `libmseed`, confirming that the resulting library is composed of files with incompatible licenses.

Were you guys aware of that?

**Comment by ghisvail** [comment]
Quick erratum: `libmseed` is released under the LGPL-2+ not GPL-2+. The issue remains the same.

**Comment by ghisvail** [comment]
I saw you guys made a proper audit [here](https://github.com/obspy/obspy/pull/827), so you guys definitely did your homeworks and it might just be an honest mistake from IRIS. Nonetheless, a clarification on this matter is required.

**Comment by megies** [comment]
Let's wait what @chad-iris has to say about this.

**Comment by krischer** [comment]
We could probably also contact Douglas Neuhauser to ask for permission if necessary - the routines appear to originate from him.

**Comment by megies** [comment]
@ghisvail fyi, @QuLogic is doing rpm packaging and I know he's separating libmseed out as a separate package (maybe evalresp, too), so he might also be able to give some input. While this is surely the cleaner way, I think it makes life harder for ObsPy packaging..

Also compare the overview of packaging efforts in https://github.com/obspy/obspy/issues/824.

**Comment by ghisvail** [comment]
@megies You are correct, vendored code should be packaged separately in theory. In practice, it often depends on how clean the upstream vendoring practice is.

> While this is surely the cleaner way, I think it makes life harder for ObsPy packaging.

Vendored dependencies is common practice. The amount of effort depends on the upstream vendoring practice and layout of the build process.

In the case of `obspy` it does not look too bad, since you guys have the build centralized in one `setup.py` and the vendored code is stored in separate directories and is not patched (please confirm this?).

An improvement would be to provide a `NOTICE` or `COPYRIGHT` file at the root of the `obspy` source code listing all vendored dependencies and corresponding version, origin and licensing, similar to what the Apache license [recommends](http://www.apache.org/legal/src-headers.html#notice). Here is an [example](https://github.com/arrayfire/arrayfire/blob/devel/COPYRIGHT.md) of what I consider a helpful copyright notice.

**Comment by krischer** [comment]
`libmseed` is not patched, but `evalresp` is patched quite a bit. I assume @QuLogic also patches his separate `evalresp` package?

The copyright notice file is a good idea.

**Comment by ghisvail** [comment]
Regarding `evalresp` are these patches `obspy` specific, or were they supposed to address general things? In the latter case, were these patches forwarded upstream?

According to the upstream webpage, there is a new version out (4.0.6). Are there plans for `obspy` to use this release?

**Comment by krischer** [comment]
Ah nice. I was not aware that they released a new version.

The patches are largely obspy specific (mainly to be able to directly pass things to evalresp without having to write files which are then read by evalresp) but also some generic stability improvements. At one point we forwarded them to IRIS I think but I'm not sure what happened with those.

I open an issue to discuss these things: #1493.

**Comment by krischer** [comment]
Pinging @CTrabant under his other handle to make sure he sees this. Which one should we actually use?

**Comment by QuLogic** [comment]
`libmseed` is slightly patched, but all of them are sent upstream. I think they are all part of 2.17, though the 1.0.3 will still use a patched 2.16m. `evalresp` is greatly patched to fix build and other problems. You can find a list of patches [here](https://github.com/QuLogic/rpmbuild-specs/blob/master/SPECS/evalresp.spec#L11).

The new `evalresp` should have been caught by [release monitoring](https://release-monitoring.org/project/5808/), but it seems that they changed their naming scheme.

**Comment by chad-iris** [comment]
The license in the main README for libmseed should definitely clarify that all libmseed code is LGPL except for the few routines with copyright belonging to Berkeley.  That was a simple oversight.  Of course it just clarifies that libmseed is mixed-license.

I'm waiting on some discussion with the author of those encoding/decoding routines before I make any decision about modifying libmseed.

**Comment by krischer** [comment]
It would be great if the license could be changed. Otherwise we are also willing to help (and if necessary rewrite the routines) as we definitely want all of ObsPy to be usable under the LGPL.

**Comment by ghisvail** [comment]
> it just clarifies that libmseed is mixed-license.

Which does not make it ok nonetheless. The terms of the LGPL and the Berkley license are incompatible. The explicit permission required for commercial usage (which makes the code proprietary) contradicts the non-restricted usage terms of the (L)GPL. Therefore, neither a source nor a binary release of `libmseed` should have been made **public** in the first place because of the infringement.

The only path forward is to have the Berkeley code relicensed under compatible terms, or replace its usage with something different entirely. The aftermath from this is that `obspy` inherits the problem due to the embedding of the infringing `libmseed` sources. Hence, `obspy` is not suitable for source release as it is, unless the vendored `libmseed` is stripped from it.

**Comment by krischer** [comment]
This has been resolved in #1540 mainly thanks to @chad-iris!

**Comment by megies** [comment]
:tada:  for making libmseed clean LGPL, @chad-iris!

**Comment by ghisvail** [comment]
`libmseed` is now on its way to Debian, which is a first step towards getting `obspy` packaged as well.

Now `evalresp`...

**Comment by krischer** [comment]
We vendor `evalresp` so there would be no true need to package it separately. I don't know if this is acceptable to Debian.

Note that ObsPy requires an evalresp version with quite a number of patches. @QuLogic does that for rpm packages but I cannot find the repository right now.

Evalresp also has a GPLed component which we replaced with another version but that should be no issue for Debian.

Aside from this: AFAIK there are efforts underway to heavily restructure evalresp - at that point we might be able to directly use it from within ObsPy without any patches which would ease the whole thing.

**Comment by ghisvail** [comment]
> I don't know if this is acceptable to Debian.

Nope. Embedding dependencies is prohibited, although there are exceptions.

> Aside from this: AFAIK there are efforts underway to heavily restructure evalresp - at that point we might be able to directly use it from within ObsPy without any patches which would ease the whole thing.

I see, so I'll wait to see how this develops. Please keep me posted.

**Comment by QuLogic** [comment]
The evalresp patches are [listed here](https://gitlab.com/QuLogic/rpmbuild-specs/blob/master/SPECS/evalresp.spec#L11) and in the [sources](https://gitlab.com/QuLogic/rpmbuild-specs/tree/master/SOURCES).

**Comment by QuLogic** [comment]
Also, I wonder if @chad-iris thinks evalresp might move to GitHub like libmseed did; that would make it much easier to push these patches back.

**Comment by chad-iris** [comment]
Yup, evalresp will be in GitHub.  We plan to release the refactored version summer 2017.  We hope that this version can be used by ObsPy without modification.  To that end, any volunteers for early integration testing would be appreciated.

**Comment by krischer** [comment]
> Yup, evalresp will be in GitHub. We plan to release the refactored version summer 2017. We hope that this version can be used by ObsPy without modification. To that end, any volunteers for early integration testing would be appreciated.

Great :) I'd  be happy to maintain an ObsPy branch alongside the evolution of the new evalresp to make sure it works with ObsPy. It would solve a big pain point for us.

We also have this here: https://github.com/obspy/sandbox/tree/master/stationxml_test

It was originally used to make sure our response calculation with ObsPy from stationxml files is identical to evalresp from RESP files by just testing with every response of the IRIS inventory.
