### ISSUE TITLE
bug in farfield with points of shape (2,n)

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#1499]
in current Master, these lines:
```python
    if ndim == 2:
        # points are given as theta,phi
        points = np.empty((3, npoints))
        points[0] = np.sin(points[0]) * np.cos(points[1])
        points[1] = np.sin(points[0]) * np.sin(points[1])
        points[2] = np.cos(points[0])
```

are very wrong, and destroy the input (arg) `points` if the array is of shape (2,n), i.e. (theta, phi) pairs.

https://github.com/obspy/obspy/blob/master/obspy/core/event/source.py#L455-L460

**Comment by ThomasLecocq** [comment]
and `ndim` should also be set to 3 after this

**Comment by ThomasLecocq** [comment]
working on this now ...

**Comment by megies** [comment]
So it seems this is in the current release version? Has to be fixed in `maintenance_1.0.x` then..

**Comment by ThomasLecocq** [comment]
Ok, the bugfix is easy, but where should I add a test ? 
in  `obspy\imaging\tests\test_source.py` ?
there is no test_source in `obspy.core.tests` AFAIK

**Comment by ThomasLecocq** [comment]
I think @MMesch and I will make the example for the future release, with an update version of the method (allowing to return the magnitude field instead of the disp vector). So, for me, this should be it for now.

**Comment by krischer** [comment]
For future reference: you can convert an issue into a PR: http://stackoverflow.com/questions/4528869/how-do-you-attach-a-new-pull-request-to-an-existing-issue-on-github

;-)
