### ISSUE TITLE
Mass downloader does not work for very old distros

### ISSUE THREAD

**Issue by krischer** [obspy/obspy#1500]
See e.g. here: http://tests.obspy.org/47061/#4

**Comment by megies** [comment]
Punting this to 1.2.1, maybe we can even just close it.. the linked test report has Debian wheezy which hits EOL of LTS in May 2018, so just a few weeks from now.

**Comment by megies** [comment]
I think the affected old distros are either EOL or we don't care too much about them anyway (I guess centos6 might still be affected). Closing.
