### ISSUE TITLE
Spectral estimation bug when trace id don't match

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#1506]
On obspy master: this line:

https://github.com/obspy/obspy/blob/master/obspy/signal/spectral_estimation.py#L782

is not py3 compatible, if i'm not mistaken. This exception is raised when the trace ids don't match the metadata (e.g. and empty `location` when the dataless contains a `00` location).

**Comment by megies** [comment]
Those lines are not covered by our tests.. @ThomasLecocq you can earn some ObsPy-:sparkles: by setting up a minimal test in https://github.com/obspy/obspy/blob/master/obspy/signal/tests/test_spectral_estimation.py (you can use [existing helper functions](https://github.com/obspy/obspy/blob/master/obspy/signal/tests/test_spectral_estimation.py#L69-L93) to get example ppsd object and data and modify tr.stats to raise the error).

**Comment by ThomasLecocq** [comment]
roger that... will do asap (today or tomorrow)

**Comment by ThomasLecocq** [comment]
Aha, I said "today or tomorrow"... Djeez, it's been a long day :-)
