### ISSUE TITLE
Installation obspy-runtests error

### ISSUE THREAD

**Issue by mat2py** [obspy/obspy#1521]
* Please provide the following information:
  -  ObsPy version: 1.0.2
  -  Python 2.7.12
  -  Anaconda 4.1.1 (64-bit)
  -  Ubuntu 15.10

Installed via:
conda config --add channels conda-forge
conda install obspy

Then:
obspy-runtests

results in the exact error described in the traceback here:
http://test.obspy.org/49344/

I have tried an uninstall, delete the cached package download (conda clear --packages) and a reinstall but there is no change to the runtests output.

Is there a solution to this?

**Comment by krischer** [comment]
The tests require `mock` to be installed.

```bash
conda install mock
```

and the rest should work.

**Comment by mat2py** [comment]
..well that was easy. Thanks for the quick response!

**Comment by krischer** [comment]
We'll make sure its installed with obspy in the future :-)

**Comment by QuLogic** [comment]
Or use Python 3.

**Comment by mat2py** [comment]
It's not worth the time spent bug-fixing to switch all my scripts from Python2 to 3 and reinstalling python and the packages, simply because it's newer. When there is an identifiable advantage of 3 over 2 then I probably will but, until then, I would rather focus on research than migrating code.

**Comment by Halauwet** [comment]
I'm using python 3.7 and mock installed on obspy env, obspy-runtests still show error "failed to create process."
I've used anaconda 3 for few months and there is no problem with anaconda.

**Comment by megies** [comment]
@mat2py Python 2 will be EOL end of this year FYI

**Comment by megies** [comment]
@Halauwet mock is a builtin on Python 3, no need to install separately

**Comment by Halauwet** [comment]
hi @megies . thanks for your response.
Yes, I've just checked it because my obspy-runtests have a similar error with mat2py.
Can you help me how to fix "failed to create process" from anaconda 3?

**Comment by megies** [comment]
Maybe this? https://stackoverflow.com/questions/42152589/anaconda-failed-to-create-process
My guess is anybody you ask about such problems could only also use a search engine to find answers, so maybe try that @Halauwet

**Comment by megies** [comment]
Closing this as resoved, this is clearly something else, don't hijack resolved issues please.
