### ISSUE TITLE
ObsPy doesn't honor the ipython's %matplotlib magic command

### ISSUE THREAD

**Issue by legovini** [obspy/obspy#1530]
When using matplotlib on ipython3 like this:
```
In [1]: import matplotlib.pyplot as plt
In [2]: plt.plot()
Out[2]: []
In [3]: plt.show()
```
the result is not satisfactory, as the ipython shell remains hung while showing the plot, and even after the plot window has been closed (not sure if this is a quirk of the frontend I'm using, but I can confirm it happens).

In order to get it work as expected it is necessary to use the `%matplotlib` magic command before importing matplotlib. In this way the `show()` command is not even necessary and the ipython shell remains available and is truly interactive.

I was expecting the same with obspy, but this is not the case: it seems that the `%matplotlib` command is ignored. This is a minimal (non-)working example that reproduces the problem:

```
In [1]: %matplotlib
Using matplotlib backend: TkAgg

In [2]: import obspy

In [3]: st = obspy.read()

In [4]: st.plot()
[plot shows, HUNG SHELL.]
```

If you need further information just let me know. I'll be happy to test a patched version when available. Otherwise, if this is the expected behavior, I'll appreciate a hint on a workaround.

I'm using  python3-obspy 1.0.2.post0+358.ged0c7fb007-1 (git head of a couple of a few days ago) compiled from source on an up to date Debian system (sid branch).
```
$ python3 --version
Python 3.5.2+

$ ipython3 --version
2.4.1
```

Thank you!

**Comment by krischer** [comment]
The plotting is quite complicated in obspy especially in the way it handles automatic showing and plotting. Its proven to work fairly well and we'd probably break something else if we change it. In any case - you can get your desired behavior like this (there are probably other ways as well):

```python
In [1]: %matplotlib
In [2]: import matplotlib.pyplot as plt
In [3]: fig = plt.figure()
In [4]: import obspy
In [5]: obspy.read().plot(fig=fig)
In [6]: plt.show()
```

**Comment by QuLogic** [comment]
You can also do `fig = st.plot(handle=True)`, and then call `plt.show()` whenever you like.

**Comment by krischer** [comment]
I guess this can be closed. Please reopen if neither of the options work/are acceptable.
