### ISSUE TITLE
Refactor CI scripts to use obspy/obspy_github_api

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1534]
Refactor github API stuff in `misc/scripts/docs_buildbot/` into `core.util.github_api` started in #1408.

**Comment by krischer** [comment]
Sorry for the late reply (mainly on the other issue).

Do we really want this in the core obspy module? I think this should be handled outside of it, probably in the `.travis.yml` file or some script in `misc` like it used to be before #1408.

It adds a lot of complexity but is really only important for running our CI so of little interest to the general user.

**Comment by barsch** [comment]
also what happens if we have to switch out github at a certain point ...

**Comment by megies** [comment]
No problem, can always be moved around still.

Personally, I don't see a big problem having it in `core/util`. Keeping it in `misc` is getting annoying and messy as this is getting used in many different places and I certainly won't be bothered with messing around with imports from local python files and handling `sys.path` accordingly.

Only other option for me is keeping this in a separate python package obspy-github-api or whatnot, but that will make more work in maintaining CI scripts because this separate module will have to be installed then in various places.

Other options I'm missing?

**Comment by krischer** [comment]
I'd be fine with having it in `misc` or even a separate package - just having it in the obspy module is IMHO a bit dirty.

Why does it have to be importable? Can it not just a be a script that gets the list of  modules that should be run and pass that to `obspy-runtests`?

**Comment by megies** [comment]
With docs-buildbot parsing for +DOCS and the CI runners parsing for +TESTS there's different use cases now that can be based on the same basics. Also for all the different CI systems we're running (Travis, Appv., our own docker-testbot) it's just way simpler to have it inside `run_tests`..  but yeah, looks like this is starting to take too much time, need to work on other stuff.

**Comment by QuLogic** [comment]
Maybe it's time to start using an existing package, like [https://github3.readthedocs.io/](github3.py)? I haven't really looked to see if it's relevant though.

**Comment by megies** [comment]
Okay, I'll move it in a separate package. That's way cleaner than moving through local folders and looking up a local file for an import from python..

Thanks @QuLogic for pointing out github3.py

**Comment by krischer** [comment]
Great! https://github.com/obspy/obspy_github_api also looks very clean with the `github3.py` module :-)

**Comment by megies** [comment]
I've did a lot more tweaking, looks like the docker scripts are running fine now with the new setup. Fyi, i've spread the work across three virtual machines now, so that we get timely results..
 - machine 1: tests the tips of `master` and `maintenance_1.0.x` if updated, running *all* test suites
 - machine 2: tests the tips of updated PRs
 - machine 3: runs deb packaging and testing on updates to `master` and `maintenance_1.0.x` and PRs

Only thing that should still be done is to pick up requests of specific modules like done in Travis with #1408.

**Comment by krischer** [comment]
Great :-) This should help a lot!
