### ISSUE TITLE
docs-buildbot is picking up +DOCS in issue comments but not in issue description

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1535]
Need to add checking `https://api.github.com/repos/obspy/obspy/issues/NUMBER->body` in addition to `https://api.github.com/repos/obspy/obspy/issues/NUMBER/comments->body`.

**Comment by megies** [comment]
Is fixed in initial commit in obspy/obspy_github_api.

**Comment by krischer** [comment]
I guess this can be closed then? Reopen if I'm mistaken.
