### ISSUE TITLE
sac paz file - how do I read it in, to then apply instrument correction ?

### ISSUE THREAD

**Issue by trac2github** [obspy/obspy#155]
Apologies for such a simple user question : 

My waveform data read in fine - no problems;

I have an external sac-format paz file for that station - how do I 
best read it in to apply the appropriate instrument correction ?

cheers

**Comment by likueimo** [comment]
sorry 
How to remove instrument responds after apply attach_paz 
Thank you

**Comment by megies** [comment]
http://docs.obspy.org/master/packages/autogen/obspy.core.stream.Stream.simulate.html?highlight=self
http://docs.obspy.org/tutorial/code_snippets/seismometer_correction_simulation.html#using-a-paz-dictionary

**Comment by likueimo** [comment]
Thank you again !

**Comment by BoDoNgAhAi** [comment]
Hello, I am sorry for asking simple question. 
I am new in Obpsy and signal processing especially seismology area. I have miniseed and sacpz files. The sacpz file have poles and zeros, and constant value. I used attach_paz command and then tried to remove instrument response applying remove_response command. But it shows that `No response information found. Use `inventory` parameter to specify an inventory with response information.`
As megies mentioned above about the remove instrument response, the example of simulate is not as same as my sacpz file. And i dont know how to implement it. Could you please explain me how to use this "simulate" command? 
I will very appreciate if you provide me some good material or book relating to process waveform data and remove instument response. I have Digital Signal Processing book and it is too difficult to understand for me. Thank you for your time and consideration.
The sacpz file is here: 
[SAC_PZs_RASP_VEL.txt](https://github.com/obspy/obspy/files/6491730/SAC_PZs_RASP_VEL.txt)
