### ISSUE TITLE
Possible bug with get_events

### ISSUE THREAD

**Issue by NoisyLeon** [obspy/obspy#1551]
Hi,
I'm working with obspy 1.0.2 on Linux platform (installed with conda)and encountered a potential bug when I was requiring earthquake catalog from IRIS server. Below is the script that I run:

`from obspy.clients.fdsn.client import Client
import obspy

client=Client('IRIS')
starttime=obspy.core.utcdatetime.UTCDateTime('2011-12-01')
endtime=obspy.core.utcdatetime.UTCDateTime('2011-12-31')
cat = client.get_events(starttime=starttime, endtime=endtime, minmagnitude=5.5, catalog='ISC', magnitudetype='ms')
print cat`

And this is the result I got:
**37 Event(s) in Catalog:
2011-12-30T09:22:15.690000Z | -14.517,  -75.431 | 3.8 MS
2011-12-28T20:32:28.290000Z | -60.761,  -25.913 | 4.5 MS
...
2011-12-02T06:57:45.840000Z |  +8.421,  -82.877 | 4.3 MS
2011-12-02T00:22:53.880000Z | -34.025,  +58.044 | 5.1 MS**

I set the minimum magnitude to be Ms=5.5, but it gave me several events with magnitude much smaller than 5.5.

**Comment by krischer** [comment]
Hi,

I replicated your script except initializing the client with `client = Client("IRIS", debug=True)` which also show the URLs it actually downloads.

In this case it downloads http://service.iris.edu/fdsnws/event/1/query?minmagnitude=5.5&starttime=2011-12-01T00%3A00%3A00.000000&catalog=ISC&magnitudetype=ms&endtime=2011-12-31T00%3A00%3A00.000000 which it fully correct so its not an ObsPy issue.

You'd have to check with the ISC or IRIS but what I think happens is that the `minmagnitude` restriction is applied to the moment magnitude and not the surface wave magnitude which can differ greatly. The correct behavior is not really specified in the fdsn web service specs. If you leave out the `magnitudetype` it will show correctly. If you use `includeallmagnitude=True` you will get all the magnitudes available for a single event.

Cheers!

Lion

**Comment by megies** [comment]
As Lion already pointed out, this is related to the way magnitudes are filtered out on server side. It's most likely doing the filtering on the *preferred* magnitude (maybe even on all magnitudes in the event.. would have to check in detail) and not on the magnitude type you requested. On a first impression this feels strange, but as Lion said, the FDSN official standard definition is likely just not clear enough on that detail.

In any case, you can add the following at the end of your script to filter after fetching the events:
```python
cat = cat.filter('magnitude >= 5.5')
```

You gotta be careful though, there might be a chance that you will be missing events with magnitude over the threshold but without a `Ms` type magnitude this way.

**Comment by NoisyLeon** [comment]
Hi Lion, Tobias,
Thank you for your replies. They are really helpful.
