### ISSUE TITLE
tr.stats['sampling_rate'] value changed when output to SAC file

### ISSUE THREAD

**Issue by ChingWeiChen** [obspy/obspy#1556]
OS: win8.1 x64
python version: 2.7

Hello: 
      I tried to create my own SAC file with the raw data in ASC-II format.
I created the new Trace for both waveform header and tr.data following the method from  [http://lists.swapbytes.de/archives/obspy-users/2014-April/001362.html](url)

and here is my problem, 

I only gave the values for ['starttime'], ['sampling_rate'] and 'tr.data' then writting it into SAC file. However, the ['sampling_rate'] changed but still with the correct [npts]. Then I tried some other values for ['sampling_rate'] and some could show correctly and some couldn't.

Here are my python code and intput file (test.7z).
[https://drive.google.com/open?id=0B2O-qHVUqbkWa3c1eWZwdFZqb00](url)

Note: The url is correct, but didn't work when click it directly.

Thanks a lot,
ChingWei

**Comment by megies** [comment]
I cannot reproduce or understand your problem.

Here's a few comments on your program snippet, though:

 - a trace created from scratch never has `.stats.sac`
 - you don't have to initialize it with a length 1 zeros array
 - if you do not want to write any SAC-specific header fields, you don't need `.stats.sac` at all

```python
#-*- coding: utf-8 -*-
import obspy as op
import numpy as np
import glob
import os
from datetime import datetime
from obspy.core import Trace, AttribDict


inpf = '20120401000000-SM-100-NE-velocity.dat'

#creating empty sac file
newt = Trace()
if not hasattr(newt.stats,"sac"):
    newt.stats.sac = AttribDict({})
    newt.data = np.zeros(1)

#Reading input data
with open(inpf, 'r') as oo:
    for p, line in enumerate(oo):
        if p == 0:
            sttime = (datetime.strptime(line,"TIME : %Y/%m/%d  %H:%M:%S\n")).isoformat("T")+"Z"
            #TIME : 2012/04/01  00:00:00
        elif(p == 2):
            samplingrate = int((line.split(' '))[3])

    data = np.loadtxt(inpf, dtype='float', skiprows=5)
    time, vcom, ecom, ncom = data[:,0], data[:,1], data[:,2], data[:,3]


newt.stats['station'] = u'SMNE'
newt.stats['network'] = u'TP'
newt.stats['location'] = u'02'
newt.stats['channel'] = u'HHZ'
newt.stats['starttime'] =sttime
newt.stats['sampling_rate'] = 250
#vcom for example
newt.data = vcom


#------DIFFERNENT for SAMPLING_RATE (250 is what I need)
#output_sampling250
newt.stats['sampling_rate'] = 250
newt.write('test_250.sac', format='SAC')

#output_sampling100
newt.stats['sampling_rate'] = 100
newt.write('test_100.sac', format='SAC')


#output
newt.write('test.sac', format='SAC')
```

**Comment by ChingWeiChen** [comment]
Thanks for your response, it does give me a lot of help for my coding skills.
My problem is, i tried to create a .sac file (output file) with giving the following data information, ['starttime'], ['sampling_rate'], trace.data and some other station information. Generally, obspy will automatically identify the ['npts'], ['endtime'], ['npts'] etc.  
When I read the output .sac file, however, the value of ['sampling_rate'] is not the same as I gave.
I tried to express more clearly.
thanks again.

**Comment by jkmacc-LANL** [comment]
Below is a minimal self-contained example (I think) that also shows the output.  Is this what you get?  Which part is the problem? 

```python
import datetime
import io
import numpy as np
from obspy.core import Trace, AttribDict, read

def write_and_peek(trace):
    with io.BytesIO() as f:
        trace.write(f, format='SAC')
        f.seek(0)
        tr = read(f, format='SAC')[0]
        print tr.stats

vcom = np.random.random(1000)
sttime = datetime.datetime.now()

newt = Trace()
newt.stats.sac = AttribDict({})
newt.data = np.zeros(1)

newt.stats['station'] = u'SMNE'
newt.stats['network'] = u'TP'
newt.stats['location'] = u'02'
newt.stats['channel'] = u'HHZ'
newt.stats['starttime'] = sttime
newt.data = vcom

#output_sampling 250
newt.stats['sampling_rate'] = 250
write_and_peek(newt)

#output_sampling100
newt.stats['sampling_rate'] = 100
write_and_peek(newt)
```

`sampling_rate` 250
```
         network: TP
         station: SMNE
        location: 02
         channel: HHZ
       starttime: 2016-10-17T07:21:57.052175Z
         endtime: 2016-10-17T07:22:01.048175Z
   sampling_rate: 249.999984741
           delta: 0.00400000024414
            npts: 1000
           calib: 1.0
         _format: SAC
             sac: AttribDict({u'nzyear': 2016, u'nzjday': 291, u'iztype': 9, u'khole': u'02', u'nzhour': 7, u'lcalda': 1, u'iftype': 1, u'nvhdr': 6, u'depmin': 0.00036864314, u'kcmpnm': u'HHZ', u'nzsec': 57, u'depmen': 0.50110978, u'depmax': 0.99763685, u'lovrok': 1, u'scale': 1.0, u'delta': 0.0040000002, u'nzmsec': 52, u'lpspol': 0, u'b': 0.00017499999, u'e': 3.9961753, u'leven': 1, u'kstnm': u'SMNE', u'nzmin': 21, u'npts': 1000, u'knetwk': u'TP'})
```

`sampling_rate` 100
```
         network: TP
         station: SMNE
        location: 02
         channel: HHZ
       starttime: 2016-10-17T07:21:57.052175Z
         endtime: 2016-10-17T07:22:07.042175Z
   sampling_rate: 100.0
           delta: 0.01
            npts: 1000
           calib: 1.0
         _format: SAC
             sac: AttribDict({u'nzyear': 2016, u'nzjday': 291, u'iztype': 9, u'khole': u'02', u'nzhour': 7, u'lcalda': 1, u'iftype': 1, u'nvhdr': 6, u'depmin': 0.00036864314, u'kcmpnm': u'HHZ', u'nzsec': 57, u'depmen': 0.50110978, u'depmax': 0.99763685, u'lovrok': 1, u'scale': 1.0, u'delta': 0.0099999998, u'nzmsec': 52, u'lpspol': 0, u'b': 0.00017499999, u'e': 9.9901752, u'leven': 1, u'kstnm': u'SMNE', u'nzmin': 21, u'npts': 1000, u'knetwk': u'TP'})
```

**Comment by ChingWeiChen** [comment]
For given sampling_rate 250, the output sac file actually shows 249.999984741.
However, for given sampling_rate 100, the output sac file can shows correctly.

**Comment by krischer** [comment]
That should be a consequence of floating point accuracy: Floating point numbers cannot accurately represent any number. Sac internally represent the sample spacing as a single precision floating point number so it has to be inverted to calculate the sampling rate. This, coupled with the conversion from 64bit (Python internally uses this) to 32bit and back, causes the problem. 

```python
# Demonstration - the actual calculations are likely a bit different.
>>> 1.0 / np.float32(1.0 / 250.0)
249.99998812563774
```

**Comment by ChingWeiChen** [comment]
Thank you for all of your responses. Now I understand where the problem is.
I just tried to output in MSEED format and it shows correctly.

Thanks again!

**Comment by jkmacc-LANL** [comment]
FYI, If you need to do a `sampling_rate` comparison, NumPy provides a useful function for it, `numpy.testing.assert_allclose`. 

Thanks!
