### ISSUE TITLE
undefined symbol: msr_unpack_steim2 (Red Hat)

### ISSUE THREAD

**Issue by duperray** [obspy/obspy#1571]
Hi,
I get
Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import obspy
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib64/python2.6/site-packages/obspy/**init**.py", line 47, in <module>
> > >     read.**doc** % make_format_plugin_table("waveform", "read", numspaces=4)
> > >   File "/usr/lib64/python2.6/site-packages/obspy/core/util/base.py", line 476, in make_format_plugin_table
> > >     "obspy.plugin.%s.%s" % (group, name), method)
> > >   File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
> > >     return get_distribution(dist).load_entry_point(group, name)
> > >   File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
> > >     return ep.load()
> > >   File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
> > >     entry = **import**(self.module_name, globals(),globals(), ['**name**'])
> > >   File "/usr/lib64/python2.6/site-packages/obspy/mseed/core.py", line 19, in <module>
> > >     from obspy.mseed import util
> > >   File "/usr/lib64/python2.6/site-packages/obspy/mseed/util.py", line 23, in <module>
> > >     from obspy.mseed.headers import (ENCODINGS, ENDIAN,
> > >   File "/usr/lib64/python2.6/site-packages/obspy/mseed/headers.py", line 537, in <module>
> > >     C.POINTER(C.c_int32), C.POINTER(C.c_int32), C.c_int, C.c_int]
> > >   File "/usr/lib64/python2.6/ctypes/**init**.py", line 366, in **getattr**
> > >     func = self.**getitem**(name)
> > >   File "/usr/lib64/python2.6/ctypes/**init**.py", line 371, in **getitem**
> > >     func = self._FuncPtr((name_or_ordinal, self))
> > > AttributeError: /usr/lib64/python2.6/site-packages/obspy/core/util/../../lib/libmseed_Linux_64bit_py26.so: undefined symbol: msr_unpack_steim2

you probably repackaged the libmseed without rebuilding/repackaging obspy-0.10.3 against it.
2.17 is not compatible with 2.18? unfortunately libmseed-2.17 is not available anymore?

I know you don't maintain anymore obspy-0.10.3 can you provide the libmseed-2.17 rpm back?

Regards,

Pierre

**Comment by QuLogic** [comment]
I deleted the 2.18 build and rebuilt 2.17 for EL6 and 2.18 for everything else. Let me know if you can properly downgrade now. You might have to clear the cache and/or reinstall obspy as well.

**Comment by megies** [comment]
No feedback, so closing. Feel free to reopen if problems persist.
