### ISSUE TITLE
get_stations no longer works for IRIS client

### ISSUE THREAD

**Issue by romaguir** [obspy/obspy#1577]
Hello,
It appears that I can no longer retrieve stations using the IRIS client.  Below is a script that I could run several months ago, but now gives me the error 'The current client does not have a station service.'
Is there a reason IRIS no longer offers this service?  I am using obspy v1.0.1 on Ubuntu, installed via anaconda.

`from obspy.clients.fdsn.client import Client`
`from obspy import UTCDateTime`
`client = Client(‘iris’)`
`start = UTCDateTime(‘2006-01-01’)`
`end = UTCDateTime(‘2008-01-01’)`
`network = client.get_stations(network='YS',station='*',starttime=start,endtime=end)`

Thanks!

**Comment by derick-hess** [comment]
hmm, I just tried your example code in obspy 1.0.2 and received
The (YS) network with 71 stations.

inventory created at 2016-10-27T19:19:06.000000Z
	Created by: IRIS WEB SERVICE: fdsnws-station | version: 1.1.20
		    http://service.iris.edu/fdsnws/station/1/query?starttime=2006-01-01...
	Sending institution: IRIS-DMC (IRIS-DMC)

**Comment by romaguir** [comment]
Thanks for checking this.  That's interesting that the code works for you... I updated to obspy 1.0.2 and I still get the error 'The current client does not have a station service.'  Looking at the client information confirms that the only services available are 'available_event_catalogs' and 'available_event_contributors'.

`client = Client("IRIS")`
`client`

FDSN Webservice Client (base url: http://service.iris.edu)
Available Services: 'available_event_catalogs', 'available_event_contributors'

Use e.g. client.help('dataselect') for the
parameter description of the individual services
or client.help() for parameter description of
all webservices.

**Comment by romaguir** [comment]
It turns out the issue must be related to my local network.  I logged into a remote server and the code runs fine.

**Comment by CTrabant** [comment]
> Hello,
> It appears that I can no longer retrieve stations using the IRIS client. Below is a script that I could run several months ago, but now gives me the error 'The current client does not have a station service.'
> Is there a reason IRIS no longer offers this service?
> 
The IRIS DMC just fixed an issue with one of the backend web servers that ultimately serves the WADLs.  At a guess, if ObsPy won't try talking to a service without getting a WADL first, then it may error out assuming the service is down.  The symptom for external users was likely a transient error, as other backends continued to function correctly.

Apologies for the interruption in service.  Hopefully we've cleared things up now, so please let us know if there are further problems.

Chad

PS While on the subject of fdsnws-event implementations, I would to remind all ObsPy users that the IRIS implementation will not be offered in the long term.  Here is the message included at the top of the service documentation:
Notice This web service will not be offered long term. Users are recommended to transition their use of this service to other endpoints <http://www.fdsn.org/webservices/datacenters/>. Of particular interest for DMC users:

International Seismological Centre <http://www.isc.ac.uk/>: 
http://isc-mirror.iris.washington.edu/fdsnws/event/1/ <http://isc-mirror.iris.washington.edu/fdsnws/event/1/>
http://www.isc.ac.uk/fdsnws/event/1/ <http://www.isc.ac.uk/fdsnws/event/1/>
and

United States Geological Survey <http://earthquake.usgs.gov/>:
http://earthquake.usgs.gov/fdsnws/event/1/ <http://earthquake.usgs.gov/fdsnws/event/1/>

**Comment by krischer** [comment]
> The IRIS DMC just fixed an issue with one of the backend web servers that ultimately serves the WADLs. At a guess, if ObsPy won't try talking to a service without getting a WADL first, then it may error out assuming the service is down. The symptom for external users was likely a transient error, as other backends continued to function correctly.

That is correct - if the `Client` cannot get a WADL it assumes an implementation does not have that particular service. There is probably no easy way around that for us as we parse the WADL to determine the capabilities of the service to offer a niceish interface to for example extra arguments. We've also had this for at least two years and never had a major issues with that approach.

For future reference, initializing a client with `debug=True`, i.e.

```python
from obspy.clients.fdsn import Client
c = Client("IRIS", debug=True)
```

does show quite some detail about what is actually going on.

**Comment by megies** [comment]
> I would to remind all ObsPy users that the IRIS implementation will not be offered in the long term.

Maybe we could think about adding a deprecation warning when users request data from IRIS event WS inside ObsPy to raise awareness?
