### ISSUE TITLE
Discussion: Access trace.header items as a dictionary

### ISSUE THREAD

**Issue by snitramodranoel** [obspy/obspy#1588]
Any thoughts out there on making `trace.header` into a mapping object, e.g.

```python
print(trace.header['ensemble_number'])
```

**Comment by jkmacc-LANL** [comment]
I may be misunderstanding, but I think this is already possible:

```python
In [1]: from obspy import read

In [2]: tr = read()[0]

In [3]: tr.stats['channel']
Out[3]: u'EHZ'
```

**Comment by krischer** [comment]
Almost all headers in ObsPy use this class here which provides attribute as well as item access: https://docs.obspy.org/packages/autogen/obspy.core.util.attribdict.AttribDict.html

**Comment by megies** [comment]
`ensemble_number` sounds very SEGY-y, I think this is about `SEGYTrace`.

**Comment by krischer** [comment]
Ah I see. So dictionary access does not work if one uses the internal `_read_segy()` method.

```python
>>> from obspy.io.segy.segy import _read_segy
>>> _read_segy("./00001034.sgy_first_trace").traces[0].header["ensemble_number"]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
 ...
TypeError: 'SEGYTraceHeader' object is not subscriptable
```

Note that it does work (also for SEG-Y files) if you just use the main obspy `read()` routine (which also performs format auto-detection):

```python
>>> import obspy
>>> obspy.read('./00001034.sgy_first_trace')[0].stats["segy"]["trace_header"]["ensemble_number"]
0
>>> obspy.read('./00001034.sgy_first_trace')[0].stats.segy.trace_header.ensemble_number
0
```

**Comment by megies** [comment]
Looks like this is properly answered, so I'll close this issue. Please reopen if there's any questions left.

**Comment by snitramodranoel** [comment]
Thanks @krischer, the problem is that I was indeed using `_read_segy` from `obspy.io.segy.segy`.
