### ISSUE TITLE
remove_response output unit

### ISSUE THREAD

**Issue by rdno** [obspy/obspy#1594]
Hi,

I was testing instrument response removal with two different files (RESP file and Station.xml). I noticed that while output unit is velocity, outputs are matched. However, when output unit is velocity they are different.

I am using the `simulate` method for RESP file and `remove_response` method for Station.xml file.

Codes I have used and their plots are below:
```python
sac_file = "seis/obsd/RSSD.IU.10.LHZ.obs.sac"
resp_file = "seis/obsd/RESP.IU.RSSD.10.BHZ"
staxml = "staxml/IU.RSSD.xml"
pre_filt = [0.007273, 0.009091, 0.022222, 0.026667]
st = obspy.read(sac_file)
seedresp = {'filename': resp_file,
            'units': 'VEL'}
st.detrend("demean")
st.detrend("linear")
st.taper(max_percentage=0.05)
st.simulate(paz_remove=None, pre_filt=pre_filt, seedresp=seedresp)
st.detrend("demean")
st.detrend("linear")
st.taper(max_percentage=0.05)
st.filter("bandpass", freqmin=1.0/110, freqmax=1.0/45)

inv = obspy.read_inventory(staxml)
st2 = obspy.read(sac_file)
st2.detrend("demean")
st2.detrend("linear")
st2.taper(max_percentage=0.05)
st2.remove_response(output="VEL", inventory=inv, pre_filt=pre_filt,
                    zero_mean=False, taper=False)
st2.detrend("demean")
st2.detrend("linear")
st2.taper(max_percentage=0.05)
st2.filter("bandpass", freqmin=1.0/110, freqmax=1.0/45)
```

![resp_vs_xml](https://cloud.githubusercontent.com/assets/77037/20393756/5353eaf6-acdd-11e6-825d-5beaadbcc6bd.png)

```python
sac_file = "seis/obsd/RSSD.IU.10.LHZ.obs.sac"
resp_file = "seis/obsd/RESP.IU.RSSD.10.BHZ"
staxml = "staxml/IU.RSSD.xml"
pre_filt = [0.007273, 0.009091, 0.022222, 0.026667]

st = obspy.read(sac_file)
seedresp = {'filename': resp_file,
            'units': 'DISP'}
st.detrend("demean")
st.detrend("linear")
st.taper(max_percentage=0.05)
st.simulate(paz_remove=None, pre_filt=pre_filt, seedresp=seedresp)
st.detrend("demean")
st.detrend("linear")
st.taper(max_percentage=0.05)
st.filter("bandpass", freqmin=1.0/110, freqmax=1.0/45)

inv = obspy.read_inventory(staxml)
st2 = obspy.read(sac_file)
st2.detrend("demean")
st2.detrend("linear")
st2.taper(max_percentage=0.05)
st2.remove_response(output="DISP", inventory=inv, pre_filt=pre_filt,
                    zero_mean=False, taper=False)
st2.detrend("demean")
st2.detrend("linear")
st2.taper(max_percentage=0.05)
st2.filter("bandpass", freqmin=1.0/110, freqmax=1.0/45)
```

![resp_vs_xml_in_disp](https://cloud.githubusercontent.com/assets/77037/20393807/8713c258-acdd-11e6-8200-a8b4b41b69d6.png)

If the output unit is set to velocity in `remove_response`, the integral of the output is consistent with the `simulate` (with displacement output):
```python
st = obspy.read(sac_file)
seedresp = {'filename': resp_file,
            'units': 'DISP'}
st.detrend("demean")
st.detrend("linear")
st.taper(max_percentage=0.05)
st.simulate(paz_remove=None, pre_filt=pre_filt, seedresp=seedresp)
st.detrend("demean")
st.detrend("linear")
st.taper(max_percentage=0.05)
st.filter("bandpass", freqmin=1.0/110, freqmax=1.0/45)

inv = obspy.read_inventory(staxml)
st2 = obspy.read(sac_file)
st2.detrend("demean")
st2.detrend("linear")
st2.taper(max_percentage=0.05)
st2.remove_response(output="VEL", inventory=inv, pre_filt=pre_filt,
                    zero_mean=False, taper=False)
st2.integrate()
st2.detrend("demean")
st2.detrend("linear")
st2.taper(max_percentage=0.05)
st2.filter("bandpass", freqmin=1.0/110, freqmax=1.0/45)
```
![resp_vs_xml_in_disp_integral_of_xml](https://cloud.githubusercontent.com/assets/77037/20394503/00cdf058-ace0-11e6-9dce-39418c6a5964.png)

Check if the integral of `VEL` is equals to `DISP`:
```python
inv = obspy.read_inventory(staxml)
st = obspy.read(sac_file)
st.detrend("demean")
st.detrend("linear")
st.taper(max_percentage=0.05)
st.remove_response(output="VEL", inventory=inv, pre_filt=pre_filt,
                   zero_mean=False, taper=False)
st.integrate()
st.detrend("demean")
st.detrend("linear")
st.taper(max_percentage=0.05)
st.filter("bandpass", freqmin=1.0/110, freqmax=1.0/45)

inv = obspy.read_inventory(staxml)
st2 = obspy.read(sac_file)
st2.detrend("demean")
st2.detrend("linear")
st2.taper(max_percentage=0.05)
st2.remove_response(output="DISP", inventory=inv, pre_filt=pre_filt,
                    zero_mean=False, taper=False)
st2.detrend("demean")
st2.detrend("linear")
st2.taper(max_percentage=0.05)
st2.filter("bandpass", freqmin=1.0/110, freqmax=1.0/45)
```
![xmls](https://cloud.githubusercontent.com/assets/77037/20394891/621891c8-ace1-11e6-9f0e-e948dcc72f49.png)

Same check for RESP file:
```python
st = obspy.read(sac_file)
seedresp = {'filename': resp_file,
            'units': 'VEL'}
st.detrend("demean")
st.detrend("linear")
st.taper(max_percentage=0.05)
st.simulate(paz_remove=None, pre_filt=pre_filt, seedresp=seedresp)
st.integrate()
st.detrend("demean")
st.detrend("linear")
st.taper(max_percentage=0.05)
st.filter("bandpass", freqmin=1.0/110, freqmax=1.0/45)

st2 = obspy.read(sac_file)
seedresp = {'filename': resp_file,
            'units': 'DISP'}
st2.detrend("demean")
st2.detrend("linear")
st2.taper(max_percentage=0.05)
st2.simulate(paz_remove=None, pre_filt=pre_filt, seedresp=seedresp)
st2.detrend("demean")
st2.detrend("linear")
st2.taper(max_percentage=0.05)
st2.filter("bandpass", freqmin=1.0/110, freqmax=1.0/45)
```
![resps](https://cloud.githubusercontent.com/assets/77037/20394912/6d704ac0-ace1-11e6-82ac-72725a32f749.png)
---
Data files I have used: [datas.zip](https://github.com/obspy/obspy/files/597749/datas.zip)

It seems like there is a problem with `remove_response`'s units. I have also tested with `SAC`. It is consistent with `simulate` output. Are there anything wrong with the usage of `remove_response` in these examples? If so, let me know.

Thanks.

**Comment by wjlei1990** [comment]
This is terrifying...We need to figure this out :(

**Comment by krischer** [comment]
Hui...you had me scared there for a bit but I think it is just the order in which the `water_level` and `pre_filt` arguments are applied. We definitely have to to make sure both variants behave the same or at least document the differences. But once again this shows just how very fragile instrument correction unfortunately is. 

We definitely still have to investigate why there are differences and which processing is more correct in some to be defined sense.


In any case: Thanks a lot for testing this. The core features of ObsPy should really be vetted as much as possible!

### Example A: Turn off prefilt and use ridiculously high water level.

```python
sac_file = "RSSD.IU.10.LHZ.obs.sac"
resp_file = "RESP.IU.RSSD.10.BHZ"
staxml = "IU.RSSD.xml"
pre_filt = [0.007273, 0.009091, 0.022222, 0.026667]
st = obspy.read(sac_file)
seedresp = {'filename': resp_file,
            'units': 'DISP'}
st.detrend("demean")
st.detrend("linear")
st.taper(max_percentage=0.05)
st.simulate(paz_remove=None, seedresp=seedresp, water_level=100000)
st.detrend("demean")
st.detrend("linear")
st.taper(max_percentage=0.05)
st.filter("bandpass", freqmin=1.0/110, freqmax=1.0/45)

inv = obspy.read_inventory(staxml)
st2 = obspy.read(sac_file)
st2.detrend("demean")
st2.detrend("linear")
st2.taper(max_percentage=0.05)
st2.remove_response(output="DISP", inventory=inv, 
                    zero_mean=False, taper=False, water_level=100000)
st2.detrend("demean")
st2.detrend("linear")
st2.taper(max_percentage=0.05)
st2.filter("bandpass", freqmin=1.0/110, freqmax=1.0/45)

plt.figure(figsize=(15, 8))
plt.subplot(211)
plt.plot(st[0].times(), st[0].data, color="blue", label="RESP file (simulate), displacment")
plt.plot(st2[0].times(), st2[0].data, color="green", label="StationXML file (remove_response), displacement")
plt.legend()
plt.xlim(2000, 4000)
plt.ylim(-0.00001, 0.00001)

plt.subplot(212)
plt.plot(st[0].times(), (st[0].data - st2[0].data), label="Difference")
plt.legend()
plt.xlim(2000, 4000)
plt.ylim(-0.00001, 0.00001)

plt.tight_layout()
plt.show()
```

![index](https://cloud.githubusercontent.com/assets/800487/20411923/0e429a92-ad24-11e6-80e0-50fd315aabf9.png)



### Example B: Responses

This shows that the calculated responses are exactly identical for `simulate()`, and `remove_response()`. They internally call these two functions respectively.

```python
import matplotlib.pyplot as plt
import obspy
import numpy as np

resp_file = "RESP.IU.RSSD.10.BHZ"
staxml = obspy.read_inventory("IU.RSSD.xml").select(location="10", channel="BHZ")


delta = 1.0 / 40.0
nfft = 4096

r_staxml_disp, freq_staxml_disp = staxml[0][0][0].response.get_evalresp_response(delta, nfft, output='DISP')
r_staxml_vel, freq_staxml_vel = staxml[0][0][0].response.get_evalresp_response(delta, nfft, output='VEL')
r_staxml_acc, freq_staxml_acc = staxml[0][0][0].response.get_evalresp_response(delta, nfft, output='ACC')


from obspy.signal.invsim import evalresp
r_resp_disp, freq_resp_disp = evalresp(delta, nfft, resp_file, obspy.UTCDateTime(2008, 8, 8),
                                       units="DISP", freq=True, network="IU", station="RSSD",
                                       locid="10", channel="BHZ")
r_resp_vel, freq_resp_vel = evalresp(delta, nfft, resp_file, obspy.UTCDateTime(2008, 8, 8),
                                     units="VEL", freq=True, network="IU", station="RSSD",
                                     locid="10", channel="BHZ")
r_resp_acc, freq_resp_acc = evalresp(delta, nfft, resp_file, obspy.UTCDateTime(2008, 8, 8),
                                     units="ACC", freq=True, network="IU", station="RSSD",
                                     locid="10", channel="BHZ")
plt.figure(figsize=(20, 10))

plt.subplot(231)
plt.title("Displacement Responses")
plt.semilogy(freq_staxml_disp, np.abs(r_staxml_disp), label="stationxml")
plt.semilogy(freq_resp_disp, np.abs(r_resp_disp), label="resp")
plt.ylim(1E10, 2E12)
plt.legend()

plt.subplot(234)
plt.title("Displacement difference")
plt.plot(freq_staxml_disp, np.abs(r_staxml_disp) - np.abs(r_resp_disp))
plt.ylim(-1E-15, 1E-15)

plt.subplot(232)
plt.title("Velocity Responses")
plt.semilogy(freq_staxml_vel, np.abs(r_staxml_vel), label="stationxml")
plt.semilogy(freq_resp_vel, np.abs(r_resp_vel), label="resp")
plt.ylim(1E9, 1.1E10)
plt.legend()

plt.subplot(235)
plt.title("Velocity difference")
plt.plot(freq_staxml_vel, np.abs(r_staxml_vel) - np.abs(r_resp_vel))
plt.ylim(-1E-15, 1E-15)

plt.subplot(233)
plt.title("Acceleration Responses")
plt.semilogy(freq_staxml_acc, np.abs(r_staxml_acc), label="stationxml")
plt.semilogy(freq_resp_acc, np.abs(r_resp_acc), label="resp")
plt.ylim(1E7, 1E9)
plt.legend()

plt.subplot(236)
plt.title("Acceleration difference")
plt.plot(freq_staxml_acc, np.abs(r_staxml_acc) - np.abs(r_resp_acc))
plt.ylim(-1E-15, 1E-15)

plt.tight_layout()
plt.show()
```

![index](https://cloud.githubusercontent.com/assets/800487/20411859/b4ce4d9e-ad23-11e6-9223-fbf606378c7e.png)

**Comment by wjlei1990** [comment]
Easy...My friend :)

Seems it is solved?

**Comment by rdno** [comment]
Thanks for the detailed response. Raising the `water_level` does solve the problem . Even if the `pre_filt` is given, outputs are consistent.

Do you have an advice on how to select the  `water_level` value? Doesn't high values have potential to cause problems, too? For this example, `water_level` as low as `70` seems to give the "right" result.

If you have an answer, please let us know. In the mean time, I think we can close this issue.

**Comment by megies** [comment]
> Do you have an advice on how to select the water_level value? Doesn't high values have potential to cause problems, too? For this example, water_level as low as 70 seems to give the "right" result.

Using water level in response removal always needs the user to set sane values, and those values depend dramatically on *a)* the shape of the response curve (as the water level is relative to the lowest point in the inverted spectrum, i.e. relative to the peak of the amplitude response) and *b)* on the frequency range you're actually interested in. So, unfortunately, **there is no universally valid value for the water level**.  For that reason I've added the plot option (`remove_response(..., plot=True)`) to see exactly what is happening to your data. Obviously, higher values of the water level lead to potentially over-corrected "blown-up" parts in the result, and low values might lead to a cut-off in the inverted spectrum in frequency regions you're interested in (and thus potential distortions).

**Comment by krischer** [comment]
I just revisited this and I just did not pay attention. Everything is already documented - its just that the default water level for the `simulate()` method is 600 and the default water level for the `remove_response()` method is 60. Manually setting both to the same results in identically corrected traces - so all is good.

`simulate()` is one of the oldest methods in ObsPy and a water level of 600 is incredibly conservative. `remove_response()` has a more practical value of 60 which IMHO makes more sense. If you use the `pre_filt` option it should be alright to set the water level to maybe 600 but I would not go much higher except if you really know the response of all your instruments and can guarantee that the `pre_filt` cuts out all data not in the passband of the instrument.

**Comment by megies** [comment]
> its just that the default water level for the simulate() method is 600 and the default water level for the remove_response() method is 60. Manually setting both to the same results in identically corrected traces - so all is good.

IIRC, I took the chance with the new function to set a lower water level. For my use cases 600 was usually way too high. But then again.. it always depends on the use case at hand. E.g. when deconvolving a seismometer directly to acceleration you get bitten by water level easily, as the response doesn't have a plateau anymore.. so.. shows once again, instrument correction is just not a "one size fits all" scenario. Again.. therefore the `plot=True` option!
