### ISSUE TITLE
Blockette 1001 Frames missing when writing mseed data

### ISSUE THREAD

**Issue by aringler-usgs** [obspy/obspy#1596]
Hello,

It appears that when writing mseed files the number of frames gets dropped.  Assuming I am not doing some really silly here is what I am finding.

```
#!/usr/bin/env python

from obspy.core import read

st= read('00_LHZ.512.seed', details=True)

st.write('00_LHZ.512.seedExample',format='MSEED')
```

Here are the first two records from the original file:

```
Record 001241 (0) Type Q Network IU Station ANMO Location 00 Channel LHZ
Time 2016,001,00:00:00.0695 Samples 235 Factor 1 Mult 1 (1sps)
IO: GOODTM (0x20) 
Blockettes 2 Correction 0 Data Start 64 First Block 48 Host Swap LE
1000-DATAONLY: STEIM-2 Swap=BE Len=9
1001-QTADEXT: Quality=100% Usec=38 Frames=7

Record 001242 (1) Type Q Network IU Station ANMO Location 00 Channel LHZ
Time 2016,001,00:03:55.0695 Samples 230 Factor 1 Mult 1 (1sps)
IO: GOODTM (0x20) 
Blockettes 2 Correction 0 Data Start 64 First Block 48 Host Swap LE
1000-DATAONLY: STEIM-2 Swap=BE Len=9
1001-QTADEXT: Quality=100% Usec=38 Frames=7

```

Here are the first two records from the file written in obspy:

```
Record 000001 (0) Type Q Network IU Station ANMO Location 00 Channel LHZ
Time 2016,001,00:00:00.0695 Samples 235 Factor 1 Mult 1 (1sps)
Blockettes 2 Correction 0 Data Start 64 First Block 48 Host Swap LE
1001-QTADEXT: Quality=100% Usec=38 Frames=0
1000-DATAONLY: STEIM-2 Swap=BE Len=9

Record 000002 (1) Type Q Network IU Station ANMO Location 00 Channel LHZ
Time 2016,001,00:03:55.0695 Samples 230 Factor 1 Mult 1 (1sps)
Blockettes 2 Correction 0 Data Start 64 First Block 48 Host Swap LE
1001-QTADEXT: Quality=100% Usec=38 Frames=0
1000-DATAONLY: STEIM-2 Swap=BE Len=9
```

I believe this is happening because the number of frames isn't being included in the miniSEED dictionary when the data is read using the details flag (only part of the 1001 blockette is being retained).  I have attached the data so others can reproduce this as desired.

If this is indeed the case I would be happy to make a pull-request to include frames.  Or perhaps there is a reason for not including them?

Thanks for your help!
Adam

[example.zip](https://github.com/obspy/obspy/files/605031/example.zip)

**Comment by krischer** [comment]
This probably has to be handled by `libmseed`. ObsPy does not retain per-record information and this information is really only known at the time of record writing.

@CTrabant: How can we force `libmseed` to fill the frames count in Blockette 1001? Is that possible?

**Comment by chad-iris** [comment]
As surmised, it is not handled by `libmseed`.  The frame count is not set or used beyond parsing it and printing the value in a couple of places.  It is redundant information with no real value beyond esoteric data forensics as far as I know.  I would be interested to learn if it's important somehow.

**Comment by aringler-usgs** [comment]
@chad-iris you can have situations where the digitizer's memory didn't dump correctly so you might have frames with different sample rates in the same record (I believe this happened with Q680s).  

However, this probably falls under the definition of "esoteric data forensics."  So maybe it isn't an issue, but definitely something we try to retain in our data (for when something strange happens).

Below is an example (data is attached).  However, if we are the only ones that use this, then it might not be worth fixing (and this ticket could be closed).

Thanks for everyone's help.

![screen shot 2016-11-29 at 8 13 52 am](https://cloud.githubusercontent.com/assets/2599501/20715358/27b8d6b2-b60c-11e6-9841-21cc06c641cb.jpg)


[LHE_00000-33.seed.zip](https://github.com/obspy/obspy/files/619348/LHE_00000-33.seed.zip)

**Comment by krischer** [comment]
@aringler-usgs, @chad-iris Feel free to close this issue at your leisure. I personally don't really have an opinion on this but if `libmseed` decides to write the frame count ObsPy will naturally also gain that functionality.

**Comment by chad-iris** [comment]
I'll put it on the consideration list for libmseed for the next round of development.

Note that the frame count is being lost because the data is being re-written (and re-encoded) and likely not on a record-by-record basis.  In the case @aringler-usgs described it would likely only be unpacked completely if the sample count in the header matches the sum of all the samples in the mixed-frame encoded data, if the sample count is short some data will be left behind.  So even if a frame count was being inserted, repacking corrupt data can result in problems more subtle and significant.

I can't close the issue though, someone with permission to do that needs to.
