### ISSUE TITLE
Add verbose validation when writing QuakeML files

### ISSUE THREAD

**Issue by krischer** [obspy/obspy#1600]
See https://github.com/obspy/obspy/pull/1376#issuecomment-262844025

> It would be nice if obspy.core.event.Catalog.write() passed a "verbose" parameter on to obspy.io.quakeml.core._write_quakeml() and [obspy.io.quakeml.core._validate()] ...

**Comment by megies** [comment]
Bumping to 1.2.0

**Comment by megies** [comment]
stale, closing.
