### ISSUE TITLE
Getting velocity time history from MSEED file

### ISSUE THREAD

**Issue by ketanbj90** [obspy/obspy#1610]
I have recorded strong motion data in MSEED format from Indian seismic network. I am able to read that using obspy. I have the dataless SEED volume for the corresponding station. Could any one help me extracting velocity time history using MSEED and dataless SEED volume using obspy tool

**Comment by megies** [comment]
http://docs.obspy.org/tutorial/code_snippets/seismometer_correction_simulation.html#using-a-dataless-full-seed-file-or-xmlseed-file

**Comment by krischer** [comment]
I assume this answers the question. Please reopen if some problems remain.
