### ISSUE TITLE
Roundtrip read/write/read test for auto-generated full QuakeML needed

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1626]
We should do a round-trip read/write/read test with a full auto-generated (random) QuakeML file.. see #1621, https://github.com/obspy/obspy/pull/1622#discussion_r92927814.

**Comment by d-chambers** [comment]
[Hypothesis](https://github.com/HypothesisWorks/hypothesis) might work well here.

I would be reluctant to include such a test or tests in the main test suite; users working on something unrelated could experience random quakeml failures making for a frustrating/unhelpful experience.

A better approach could be to make a script that autogenerates many catalog objects then pickles any that don't round trip and still eval equal. The script could then be run many times and proper tests written in the quakeml test module when issues crop up.

**Comment by megies** [comment]
stale, closing.
