### ISSUE TITLE
Can not write shapefile output if unicode characters in path to output file

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1635]
```python
In [4]: catalog.write('/tmp/test_äöü.shp', format='SHAPEFILE')
     49     if not GDAL_VERSION_SUFFICIENT:
     50         raise ImportError(GDAL_TOO_OLD_MSG)
---> 51     if not filename.endswith(".shp"):
     52         filename += ".shp"
     53 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)
```

Problem might be present in other I/O plugins as well..

**Comment by megies** [comment]
Punting to 1.1.0

**Comment by megies** [comment]
Bumping this to 1.1.1

**Comment by megies** [comment]
@DominikStr maybe you could have a look if this is still a problem in current master and if it happens for other write plugins as well (e.g. writing waveforms to miniseed, ...)

**Comment by DominikStr** [comment]
I can't reproduce the problem. I tried the `write` plugins for waveforms and stations with Unicode characters as well and found no errors there.

Only tried it with one or two formats but that should not affect this problem. 
So I would say that this problem is already fixed.

**Comment by megies** [comment]
This is a Python 2 only problem, I think. You could make another conda env with python 2 to reproduce this, @DominikStr.

**Comment by megies** [comment]
Also, a similar Python 2 only problem is #1482

**Comment by megies** [comment]
This has become irrelevant after dropping Python 2
