### ISSUE TITLE
SAC: specify time window with seconds relative to user defined time markers

### ISSUE THREAD

**Issue by seisman** [obspy/obspy#1643]
This is not a bug report. It's a feature request.

As a 3-year SAC user and an ObsPy new user, one of the SAC features I like so much is that SAC allows users to specify the time window to read with seconds relative to user defined time markers.

Example below helps explain this feature. The `cut` command below tell SAC that "I only want to read the data in the time window 10 s before time marker t0 to 20 s after t0".
```
SAC> cut t0 -10 t0 20
SAC> read example.sac
```
This feature has at least two advantages:
1. flexible: In SAC, all available time markers are `B|E|O|A|F|T0-T9` (even `user0`-`user9` if one needs more time markers). A and T0-T9 are usually used to store theoretical or observed phase arrivals. And this feature makes it easier to read only the P phase segment from a long waveform.
2. efficient: This feature makes it much faster to read a 10 seconds time window from a one-day waveform.

In obspy, `read()` has arguments `starttime` and `endtime` to specify the time window to read. But there are two limitations:
1. `read()` reads the whole file into memory and then trim based `starttime` and `endtime`, thus time-consuming if users only want to read 10 s time window from a one-day waveform.
2. these two arguments only accept UTCDateTime or float value (relative to `trace.stats.starttime`). If users only need P phase segments, they have to read all traces in and loop over all traces to calculate phase arrival times and convert phase arrival times to UTCDateTime based on event origin time. It's a little tedious.

One way to implement this feature using obspy looks like this:
```python
from obspy import read, Stream
from obspy.io.sac.util import get_sac_reftime
import glob

st = Stream()
for filename in glob.glob("*.SAC"):
    tr = read(filename, headonly=True)[0]
    T0 = get_sac_reftime(tr.stats.sac) + tr.stats.sac.t0
    st += read(filename, starttime=T0-1, endtime=T0+3)[0]
```
It's not difficult but a little inconvenient.

So, it would be better if : 

1. `starttime` and `endtime` in `read()` can accept string values like `"T0-10"`, `"T4+10"`, and these string values can be used by obspy.io.sac and maybe other data formats. (I took a quick glance at the obspy code. It seems a little difficult to implement and possibly affect other functions).

2. add two more arguments to `read()`, maybe `sac_starttime` and `sac_endtime`, and pass these two arguments to the waveform reader method in obspy.io.sac. (It's easier to implement but looks ugly.)

What do you think about this feature? Is it possible to be added into obspy?

**Comment by jkmacc-LANL** [comment]
Hi, @seisman.  I agree that it is common in SAC to do many operations around the relative time headers.  This is rather SAC-specific, though, and I think your suggestion 1) brings too much "SAC-ness" directly into the ObsPy `read` function.  Your suggestion 2) is more in line with how ObsPy's `read` handles format-specific behavior.  Would something like `read(filename, cut=('t0', -1, 3))` work, which would trigger a snippet of code similar to your post?  This syntax would be pretty intuitive to a SAC user, I think.

**Comment by jkmacc-LANL** [comment]
P.S.  I'm not sure that the snippet you posted actually works, as the SAC format plugin doesn't currently use the `starttime` or `endtime` keywords...

**Comment by krischer** [comment]
`starttime` and `endtime` are always applied, regardless of the format plugin. If the particular format does not support both arguments they will still be read and trimmed immediately afterwards.

https://github.com/obspy/obspy/blob/e9697cde8e3d2f63f9095490b6949596b00e47ff/obspy/core/stream.py#L249-L252

Considering that SAC files are usually pretty small and not encoded it might actually not be worth it to implement trimming on the plugin side. I guess the performance dominant part is the seeking to the correct file - the actual reading is super quick and reading a couple less kilobytes might not actually be much faster.

**Comment by seisman** [comment]
I performed some tests and agree with @krischer that the actual reading is mostly fast enough and there is no need to implement trimming in sac reader. And the snippet in my first comment is much slow due to `read` every SAC file twice. In case other users may need this, I provide a faster way to do this:
``` python
#!/usr/bin/env python
from obspy import read
from obspy.io.sac.util import get_sac_reftime

st = read("*.sac")
for tr in st:
    if 't2' not in tr.stats.sac:
        print("skip this trace or raise an error")
        continue
    T2 = get_sac_reftime(tr.stats.sac) + tr.stats.sac.t2
    tr.trim(starttime=T2-5, endtime=T2+5)
```

I think we may still need such feature, considering that it's so common for SAC users. Maybe we can add a function which helps converting SAC relative time marker to absolute UTCDateTime. This help function may look like this:

```python
def sac_relative_to_utcdatetime(header, tmark, offset=0):
    if 't2' not in header:
        print("raise an error")
  
    time = get_ref_time(header) + header[tmark] + offset
    return time
```

**Comment by megies** [comment]
Maybe it's an option to define a new function e.g. `trim_sac(stream, start_reference, start_offset, end_reference, end_offset)` (within `obspy.io.sac`) that does the trimming on a Stream basis (assuming SAC as data source and therefore that `tr.stats.sac` is present)?

But I also don't see a big problem with your aaproach 2 `add two more arguments to read(), maybe sac_starttime and sac_endtime`..

**Comment by claudiodsf** [comment]
Wouldn't it be better to bind all SAC-specific methods to the `SACTrace` object? Those are very specific use cases, after all.

**Comment by seisman** [comment]
Approach 2 `add two more arguments to read(), maybe sac_starttime and sac_endtime` is OK but it's not enough.

Sometimes we may need two (even three or more) waveform segments from the same trace, for example, P phase segment defined by time marker t0 and S phase segment by time marker t1.

If `read()` can accept arguments like sac_starttime and sac_endtime, we can call 
```
P = read(filename, sac_starttime="T0-5", sac_endtime="T0+5")[0]
```
to read P phase segment, and call 
```
read(filename, sac_starttime="T1-5", sac_endtime="T1+5")
```
to read S phase segment. However, calling `read()` twice is much time-consuming based on some speed tests.

In such cases, a better way is
``` python
from obspy import read, Stream
from obspy.io.sac.util import get_sac_reftime

st = read("*.sac")
P_st = Stream()
S_st = Stream()
for tr in st:
   if 't0' not in tr.stats.sac:
        print("skip this trace or raise an error")
   T0 = get_sac_reftime(tr.stats.sac) + tr.stats.sac.t0
   P_st.append(st.slice(T0-5, T0+5))

   if 't1' not in tr.stats.sac:
        print("skip this trace or raise an error")
   T1 = get_sac_reftime(tr.stats.sac) + tr.stats.sac.t1 
   S_st.append(st.slice(T1-5, T1+5))
```
A help function `sac_relative_to_utcdatetime` allows users to convert any relative time markers to UTCDatetime, and also allow users to use already existing functions like slice, trim and maybe others.

**Comment by krischer** [comment]
That looks nice. I would honestly just add this snippet to the `obspy.io.sac` documentation and refer users to it. The `sac_relative_to_utcdatetime` function also sounds useful.

ObsPy has fairly different semantics from SAC and I would be a bit careful to add too many SAC specific features that are not really needed. Especially if that functionality can be easily reproduced with a short code snippet.

**Comment by seisman** [comment]
It will be great if `sac_relative_to_utcdatetime` can be added into `obspy.io.sac`. Maybe we should choose a better function name.

**Comment by jkmacc-LANL** [comment]
I don't think it'd be hard to add some SAC-specific keyword arguments to `read`, but I'm also sensitive that the SAC data model could be leaking upwards into ObsPy.  If the data are in SAC format and you'd like to use the SAC data model, would it be better to just use the stuff in `obspy.io.sac` directly and file an enhancement request to [PySAC](https://github.com/LANL-Seismoacoustics/pysac) for a `cut` function?  ObsPy's data model is different from SAC's.  @krischer or @megies, is there a way to do a partial file read relative to an event time, in pure ObsPy?

**Comment by claudiodsf** [comment]
@jkmacc-LANL Totally agree (this was the sense of my comment above). 

However, why not have a `cut` function in `obspy.io.sac`? And, by the way, what's the difference between `PySAC` and `obspy.io.sac`?

**Comment by krischer** [comment]
> @krischer or @megies, is there a way to do a partial file read relative to an event time, in pure ObsPy?

No. This also requires some kind of relation between event and waveform which most formats aside from SAC don't have. We could take about this if we ever get a more general data set object going as we've been discussing a couple of times in the past.

**Comment by jkmacc-LANL** [comment]
@claudiodsf PySAC is just the name I used to release the SAC IO module due to licensing considerations with my employer.  They're the same code.

**Comment by jkmacc-LANL** [comment]
Is there a standard way in ObsPy to cut traces in a Stream using things in a Catalog and/or an Inventory (like predicted phase windows, etc)?  For the sake of general code reuse, maybe instead of a SAC `cut` it would be better for `io.sac` to have `SACTrace.to_catalog` and `SACTrace.to_inventory` methods, and an ObsPy `get_windows(catalog, inventory, stream=None, **kwargs)` for use with:

```python
windows = get_windows(catalog, inventory, stream, start=('P', -3), end=('S', 15))
for trace, (starttime, endtime) in zip(stream, windows):
    trace.trim(startime, endtime)
```

**Comment by krischer** [comment]
Sounds great! I'm not sure where this should live but I'm open for suggestions. Sounds like a good first use case for our discussed `DataSet` object ;-)

**Comment by megies** [comment]
stale, closing.
