### ISSUE TITLE
ah format: read only specific trace from file?

### ISSUE THREAD

**Issue by brainstormot** [obspy/obspy#1646]
Hello, I am Hyuck Kang

I am dealing with ah format file containing many traces. When testing on my data, I should load whole file although I need only one trace. It takes a lot of time. Of cousre, if I divide my file, it will be not problem. But I want to leave my data as it is. But "read()" method seem that it doesn't have functions which pick specific trace by index.

So I wonder if obspy has way to read only 'nth' trace from file or not.

Thank you.

**Comment by krischer** [comment]
Hi,

currently ObsPy does not support that for AH files but it would be fairly easy to add. Essentially you'd have to add one or more additional arguments to this function here:

https://github.com/obspy/obspy/blob/e9697cde8e3d2f63f9095490b6949596b00e47ff/obspy/io/ah/core.py#L44

As this is a fairly obscure feature it is unlikely to be implemented if you don't take the lead but we are very willing to work with you to add it :)

Cheers!

Lion

**Comment by brainstormot** [comment]
Thank you!

**Comment by krischer** [comment]
Did you really mean to close this? It is a valid feature request after all.

**Comment by brainstormot** [comment]
Oh, I asked for a simple curiosity because I felt uncomfortable. But I seem to have forgotten the original meaning of "Issue". Thaks for your advice. I'm going to reopen this.

**Comment by megies** [comment]
stale, closing.
