### ISSUE TITLE
Error when comparing obspy.core.utcdatetime.UTCDateTime and datetime.datetime objects

### ISSUE THREAD

**Issue by sfieux** [obspy/obspy#1652]
It seems that comparing an UTCDateTime and a datetime object always return False, no matter the actual date values. The following was tested on Linux Redhat 6.4 with Python 2.7.10 and obspy 1.0.2:

```
>>> from obspy.core.utcdatetime import UTCDateTime
>>> from datetime import datetime
>>> a = datetime(1990, 1, 1, 0, 0, 0)
>>> e = UTCDateTime(2000, 1, 2, 1, 39, 37)
>>>
>>> a < e
False
>>> e < a
False
>>> a <= e
False
>>> e <= a
False
>>> a > e
False
>>> e > a
False
>>> a >= e
False
>>> e >= a
False
>>> a == e
False
>>> e == a
False
```

**Comment by sfieux** [comment]
Further investigation shows that in all UTCDateTime comparing methods (`__eq__`, `__ne__`, `__lt__`, `__le__`, `__gt__`, `__ge__`), the "other" date is converted to float using`float(other)`. When this other date is a datetime object, this raises a `TypeError` that is catched silently, and makes the method return with `False`.

**Comment by krischer** [comment]
Yea - we could easily make this more general by replacing the `self.timestamp - float(other)` in all the comparison methods with `(self - UTCDateTime(other)).timestamp` - then all the comparison methods will work with everything that can be converted to a `UTCDateTime` object.

This is definitely convenient but maybe a bit much "magic" from a design perspective? I'm still for it though. Other thoughts?

**Comment by sfieux** [comment]
I think it requires a careful approach, as it could cause performance issues. This is the kind of method that might be intensely used, for instance when sorting a huge list of dates or a dated objects.

Maybe it would be better to convert the other date only in the except block ? Something like

```
def __lt__(self, other):
        """
        [Same documentation]
        """
        try:
            return round(self.timestamp - float(other), self.__precision) < 0
        except (TypeError):
            return self.__lt__(UTCDateTime(other)) 
        except (ValueError):
            return False
```

**Comment by krischer** [comment]
True - it would be quite a bit slower if `other` is already a float or a `UTCDateTime` object (other cases will require conversion to a `UTCDateTime` object in any case). But then we are talking about really small numbers so I'm not sure it really matters for anything practical.

```python
In [1]: from obspy import UTCDateTime

In [2]: dt = UTCDateTime()

In [3]: %timeit UTCDateTime(dt)
The slowest run took 6.54 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.84 µs per loop

In [4]: %timeit float(dt)
The slowest run took 24.84 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 510 ns per loop

In [5]: ts = dt.timestamp

In [6]: %timeit UTCDateTime(ts)
The slowest run took 9.17 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.25 µs per loop
```

**Comment by krischer** [comment]
This is also related to #975 which should be resolved before this issue here can be attacked.

**Comment by barsch** [comment]
this needs a rewrite anyway - comparison should be done on the nanoseconds integer value if its an UTCDateTime object - and we need special cases for float timestamps or datetime objects

so I guees we have to do a few isinstance() checks ...
