### ISSUE TITLE
FDSN client should allow 204 status to be handled separately

### ISSUE THREAD

**Issue by adam-iris** [obspy/obspy#1656]
If the FDSN client is given a valid request that returns no data, it raises an FDSNException.
https://github.com/obspy/obspy/blob/master/obspy/clients/fdsn/client.py#L1315

It would be convenient if in this case it raised a subclass such as FDSNNoDataException, this would allow calling code to distinguish an overly restrictive search from a "real" error.

This seems like it would be a pretty simple change, I'd be happy to put together a pull request unless there's some reason not to do this.

**Comment by krischer** [comment]
I can no harm in that so please go for it 😄 

Currently one has to parse the error message to get the desired behavior which admittedly is pretty ugly.

**Comment by krischer** [comment]
Continued in #1657.
