### ISSUE TITLE
Some tests try to reach the network but docs say they shouldn't

### ISSUE THREAD

**Issue by reidpr** [obspy/obspy#1660]
`obspy-runtests --help` reports:

>     Providing no modules will test all ObsPy modules which do not require an
>     active network connection.

I am running `obspy-runtests` with:

>    $ obspy-runtests -d

My reading of the documentation above is that this should not try to touch the internet at all. However, the test suite reports two failures and one error having to do with "Network is unreachable". For example:

>     Failed example:
>           st = read("https://examples.obspy.org/loc_RJOB20050831023349.z")
>     Exception raised:
>         Traceback (most recent call last):
>           [...]
>         OSError: [Errno 101] Network is unreachable

This system has partial access to the internet; most sites are blocked, but there is a whitelist. `examples.obspy.org` is not on that whitelist. DNS works. Thus, I can get an IP address for `examples.obspy.org` but cannot connect to it.

The problem tests:

>     FAIL: plot_tfr (obspy.signal.tf_misfit)
>     Doctest: obspy.signal.tf_misfit.plot_tfr

>     ERROR: test_read (obspy.core.tests.test_stream.StreamTestCase)

>     FAIL: read (obspy.core.stream)
>     Doctest: obspy.core.stream.read

Expected behavior: These three tests are skipped.

I couldn't find any related open issues.

* ObsPy version: 1.0.2
* Python version: 3.5.2
* Platform: Linux (Debian Jessie)
* ObsPy install: Miniconda (v4.2.12)
* Python install: via `apt-get`

**Comment by megies** [comment]
There are a couple of tests that use network in our non-network module tests. One reason to leave this as is is that some network-based routines in our core module should be run by all CI. There's currently some work on making network tests work without network connection, similar to `vcrpy`, see https://github.com/obspy/obspy/tree/vcr.

Is this a big problem for you? I would say this is very low priority (and might be obsolete when the vcr stuff is ready)..

**Comment by reidpr** [comment]
Thanks for following up.

My use case is demo. We want to say "look, we can run various cool frameworks in our environment", with ObsPy being one of them. This argument is marginally weaker with a partial test suite (we added `-x core -x stream` to make it pass), but I doubt it would flip any user decisions.

I will let you know if users complain about it.

**Comment by jkmacc-LANL** [comment]
Hmmm, I think core and stream are a huge chunk of what would be considered a valid ObsPy test suite.  I think the vcr stuff will be pretty valuable in this use-case, on systems with no intertubes.

**Comment by megies** [comment]
> I think the vcr stuff will be pretty valuable

Absolutely..

> I think core and stream are a huge chunk of what would be considered a valid ObsPy test suite

Indeed.

> We want to say "look, we can run various cool frameworks in our environment",

Just add  "look, tests run fine, those two or three network failures are expected since we're blocked"..?

Curious.. what kind of environment would that be?

**Comment by reidpr** [comment]
> Just add "look, tests run fine, those two or three network failures are expected since we're blocked"..?

I'm fine with that, but I need the test suite to succeed (exit with status code zero). The ObsPy test suite runs as one test in a BATS test suite that does a lot of other stuff as well.

In fact, what you suggest is basically what I did: skip the failing tests. It's heavy-handed because I couldn't figure out how to exclude at a finer granularity than modules.

In principle I could analyze the output (in this case, many hundreds of lines of stack trace) and see if the failures were as expected, but I don't have the resources to maintain that.

> Curious.. what kind of environment would that be?

It's a containerized environment on our supercomputers at Los Alamos called [Charliecloud](https://github.com/hpc/charliecloud). In fact @jkmacc-LANL suggested including ObsPy.

**Comment by megies** [comment]
> It's heavy-handed because I couldn't figure out how to exclude at a finer granularity than modules

Short term: ~~You can use `py.test` for more granularity..~~ Actually, it seems py.test only has test *inclusion* based on specifying test method name but not *exclusion* by name.. :-(

Long term: Like I mentioned, this will likely be obviated by #1663 which maybe still can make it into 1.1.0.

> It's a containerized environment on our supercomputers at Los Alamos called Charliecloud. In fact @jkmacc-LANL suggested including ObsPy.

:tada: next supercomputer infiltrated! ;-)

**Comment by QuLogic** [comment]
> Actually, it seems py.test only has test inclusion based on specifying test method name but not exclusion by name..

Use 'not _name_' for exclusion.

**Comment by megies** [comment]
> Use 'not name' for exclusion.

Interesting.. didn't read the helpstring thoroughly enough...

```
  -k EXPRESSION         only run tests which match the given substring
                        expression. An expression is a python evaluatable
                        expression where all names are substring-matched
                        against test names and their parent classes. Example:
                        -k 'test_method or test_other' matches all test
                        functions and classes whose name contains
                        'test_method' or 'test_other'. Additionally keywords
                        are matched to classes and functions containing extra
                        names in their 'extra_keyword_matches' set, as well as
                        functions which have names assigned directly to them.
```

So @reidpr there might be a slim chance to use py.test to deselect those few tests that need network and run all other default tests..

**Comment by megies** [comment]
@reidpr you could do the following to execute most tests and omitting a few problematic ones:

```bash
$ export OBSPY=$(python -c "import os, obspy; print(os.path.dirname(obspy.__file__))")
$ py.test $OBSPY -s -k 'not test_read' --ignore=$OBSPY/scripts/tests/test_print.py --ignore=$OBSPY/clients --ignore=$OBSPY/core/tests/test_code_formatting.py
```

**Comment by megies** [comment]
obsolete, I believe
