### ISSUE TITLE
CWB client from NEIC needs to be tighter

### ISSUE THREAD

**Issue by ketchum-usgs** [obspy/obspy#1668]
The current 1.0.2 obspy.clients.neic  client.py code was changed by the Obspy group after my very rough submission that I did for Geoscience Australia.  It uses data.find(b"EOR") to look for the End-of-request tag in the data, but it does not require this tag to be on a 512 byte boundary.  As such it might find this string in the compressed MiniSEED returned by accident.  Several ObsPy users have reported problems with this change as the returned blocks are not aligned and the MiniSEED conversion in ObsPy detects that the last block is not the right size.

I would like you to change:

                            if data.find(b"EOR") >= 0 :
to:

                            if data.find(b"<EOR>") >= 0 and (totlen + data.find(b"<EOR>")) % 512 == 0:

This looks for the entire <EOR> string rather than just "EOR" and insures that the string is aligned on a 512 byte boundary.  For miniSEED this boundary would contain the ASCII sequence number which can never be "<EOR>".

I am not a python user so I am not able to fully test this change, but my review indicates it would work.

Thanks,
Dave

**Comment by megies** [comment]
This was already improved in `maintenance_1.0.x` for the upcoming point release 1.0.3, see #1563.

Also, there was a question whether a real protocol specification exists, see https://github.com/obspy/obspy/pull/1563#issuecomment-256342324..

**Comment by ketchum-usgs** [comment]
Tobias,

Thanks for the reply.  I remembered that we had found this issue before and that a fix was recommended, but the user in Australia was still seeing it in the ‘latest’ release.  I will inform him that it should get better when the new release point comes out.

Dave

> On Feb 11, 2017, at 7:20 AM, Tobias Megies <notifications@github.com> wrote:
> 
> This was already improved in maintenance_1.0.x for the upcoming point release 1.0.3, see #1563.
> 
> Also, there was a question whether a real protocol specification exists, see #1563 (comment)..
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

David Ketchum - contractor          Office:  303 273-8479
ketchum@usgs.gov                    Cell :   303 520-5840

**Comment by megies** [comment]
@ketchum-usgs, there's still the question whether we should change the matching to only match on on multiples of 512 bytes. Is this the official protocol to always have 512 byte blocks?

**Comment by ketchum-usgs** [comment]
Tobias,

Yes, MiniSEED is always a multiple of 512 bytes and while the CWB can store MiniSEED of other sizes they are always a power of 2 and are not allowed to be smaller than 512 bytes, there are none that routinely store data blocks larger than 512 bytes.  

The protocol is simple - send in the command line terminated with <tab> or <newLine> and read a series of 512 byte blocks.  The very last 512 byte block will start with the bytes ‘<EOR>’.  In a miniSEED file this first portion of the file is always the “sequence number” which can never be ‘<EOR>’.  

The Java based query reads the first 64 bytes, decodes the Blockette 1000 to get the record length, and then reads that record length.  In the ObsPy I think that just insuring correct alignment of the ‘<EOR>’ on 512 byte boundaries is sufficient, though if a CWB uses 4096 byte miniSEED once in a great while this will not work.  Again, non-of the institutions running CWBs store anything but 512 byte miniSEED.

So my suggestion to insure the position of ‘<EOR>’ is always on a 512 byte boundary is the correct thing to do.

Dave

> On Feb 11, 2017, at 12:34 PM, Tobias Megies <notifications@github.com> wrote:
> 
> @ketchum-usgs, there's still the question whether we should change the matching to only match on on multiples of 512 bytes. Is this the official protocol to always have 512 byte blocks?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

David Ketchum - contractor          Office:  303 273-8479
ketchum@usgs.gov                    Cell :   303 520-5840

**Comment by megies** [comment]
Actually, looking at #1563 details, the 512 byte constraint was also already added, so this is really a duplicate and already resolved for upcoming 1.0.3.
