### ISSUE TITLE
Slow retrieval from earthworm wave server

### ISSUE THREAD

**Issue by tparker-usgs** [obspy/obspy#1678]
Pulling long segments of continuous data from an earthworm wave server takes a very long time. 

clients.earthworm.waveserver.get_waveforms() makes a copy of the server response for each tracebuf extracted. This causes the time needed for processing the data to grow very quickly as the size of the server response grows.

**Comment by krischer** [comment]
Dealt with in #1680.

For future reference: there is no need to have issue + PR for the same thing. We can also turn an issue into a PR from a certain branch if needed. This reduces clutter and just makes it a bit easier for us to keep track of everything. Nonetheless thanks for talking the issue :-)

**Comment by QuLogic** [comment]
There's also no need to close the issue manually when "Fixes #..." is in the description.

**Comment by megies** [comment]
> We can also turn an issue into a PR from a certain branch if needed

See https://github.com/obspy/obspy/wiki/Interesting-Reading-on-Git%2C-GitHub

**Comment by krischer** [comment]
> There's also no need to close the issue manually when "Fixes #..." is in the description.

Oh nice :) I did not know that.

**Comment by tparker-usgs** [comment]
Thanks. I'll avoid the duplication in the future.

*************************************
Tom Parker
U.S. Geological Survey
Alaska Volcano Observatory
4200 University Drive
Anchorage, AK 99508
tparker@usgs.gov
907-786-7030 (phone)
907-786-7401 (fax)
