### ISSUE TITLE
How to change the "trace_sequence_number_within_line" in the header of a SEG Y file

### ISSUE THREAD

**Issue by rico4** [obspy/obspy#1693]
I have a question about the header file of a SEG Y file. I can create a SEG Y file but cannot set the header of the file. I created a stream but was not able to put that stream into the output file.
I would like to change the "trace_sequence_number_within_line" in the header file.

Thanks in advance
Best regards

**Comment by megies** [comment]
Probably better asked on the users mailing list.. I think here probably only @krischer knows the answer right away but you might reach some SEGY users on the mailing list..

**Comment by rico4** [comment]
ok thank you

**Comment by krischer** [comment]
In ObsPy format specific header can usually be set by setting `trace.stats.FORMAT`. Here is an example for SEG-Y.

```python
In [5]: tr.write("out.sgy", format="segy")
/Users/lion/workspace/code/obspy/obspy/io/segy/core.py:349: UserWarning: CREATING TRACE HEADER
  warnings.warn("CREATING TRACE HEADER")

In [6]: obspy.read("out.sgy")[0].stats.segy.trace_header.trace_sequence_number_within_line
Out[6]: 0

In [7]: tr.stats.segy = {"trace_header": {"trace_sequence_number_within_line": 77}}

In [8]: tr.write("out.sgy", format="segy")

In [9]: obspy.read("out.sgy")[0].stats.segy.trace_header.trace_sequence_number_within_line
Out[9]: 77
```

**Comment by rico4** [comment]
Thank you very much, that works. 
I have another question. If I change to "trace_sequence_number_within_field_record" it does not see it. Is there somewhere a list with all the header with the names of the header inputs?

**Comment by barsch** [comment]
https://github.com/obspy/obspy/blob/master/obspy/io/segy/header.py ?

**Comment by rico4** [comment]
Perfect, thanks a lot

**Comment by krischer** [comment]
You can also read an existing SEG-Y file with `st = obspy.read(FILENAME, unpack_trace_headers=True)` and you will see them all with `st[0].stats.segy`. They are not unpacked by default for performance reasons

Once you can do what you want to do: Please consider writing a short tutorial "Working with SEG-Y" so we can put it here (https://docs.obspy.org/tutorial/). This would help others in the long run :)

**Comment by krischer** [comment]
I assume this can be closed.

**Comment by rico4** [comment]
ok I will do that.
