### ISSUE TITLE
trigger_onset in coincidence trigger

### ISSUE THREAD

**Issue by rico4** [obspy/obspy#1706]
I would like to use an easy trigger before applying a more advance trigger. I found the function "trigger_onset". I tried to put it into the" coincidence_trigger" function but this told me that it just supports recstaltapy, classicstalta, recstalta, zdetect, carlstatrig, delayedstalta, classicstaltapy. Can one of them be used that it is similar as the trigger onset function?

Thank you for your help

**Comment by megies** [comment]
If I understand correctly you want to do a coincidence trigger without a trigger function, i.e. assuming you're inputting the characteristic functions already. You can do that by setting `trigger_type=None`, see https://docs.obspy.org/packages/autogen/obspy.signal.trigger.coincidence_trigger.html?highlight=None.

**Comment by rico4** [comment]
Yes something like that. The inputs for the characteristic functions can then be the times determined by the trigger_onset function or how do I handle the inputs?

**Comment by megies** [comment]
Just input your preprocessed data as a stream into coincidence_trigger and set `trigger_type=None` and set your thresholds of choice?

**Comment by rico4** [comment]
ah ok I got it :)

**Comment by megies** [comment]
OK closing.. reopen if necessary..
