### ISSUE TITLE
avoid electronic signals in trigger

### ISSUE THREAD

**Issue by rico4** [obspy/obspy#1710]
Because I have many electronic signals I tried to search a method to avoid triggering electronic signals but could not find anything. I am not sure if this is possible. In the "coincidence_trigger" function one can set the coincidence sum to a number (e. g. 3). If that is the case it is taken as a trigger. Now my idea is to not take it as a trigger if the trigger happens at exactly the same time over most of the channels. Is this possible or do I have to write something on my own. Below is an example:
![stream1trigger35](https://cloud.githubusercontent.com/assets/26170898/23758069/d6daccd8-04e8-11e7-9c80-9d747f40e70f.png)

**Comment by jkmacc-LANL** [comment]
Hi @rico4 .  Questions like this about usage are better as emails to the [ObsPy Users mailing list](http://lists.swapbytes.de/mailman/listinfo/obspy-users).  Doing so helps keep the number of GitHub Issues low, to help the developers, and you'll get more people who can respond to your question on the mailing list than on a GitHub Issue.

**Comment by krischer** [comment]
Another option is our gitter channel here: https://gitter.im/obspy/obspy

Usually a couple of us hang out in it and it is a good place to ask quick questions :) You can use your github account to log into it. The mailing list of course reaches a much bigger audience.

**Comment by krischer** [comment]
I also don't have an answer to your particular channel except maybe filtering out the questionable timespan prior to calling the coincidence trigger by just trimming the traces.

**Comment by calum-chamberlain** [comment]
Even though this is closed, I have a suggestion:
[redPy](https://github.com/ahotovec/REDPy) tries to weed out these things by looking at kurtosis and outlier ratios.  Disclaimer, I haven't used this extensively, but it makes sense and is already written, so might be worth a quick try? Function in question is here: https://github.com/ahotovec/REDPy/blob/master/redpy/trigger.py#L193

**Comment by krischer** [comment]
Nice. I did not know about this. I added to our wiki.

**Comment by rico4** [comment]
Thank you very much for the response. Then I will contact you on the Obspy mailing list if I have further issues :)

**Comment by megies** [comment]
Well.. the coincidence trigger usually is used with channels from different stations so that local issues like yours don't trigger.. also, I'd always trigger on pre-filtered traces, your signal looks extremely high-frequency.. maybe a lowpass could help. But then again you seem to be working with very high frequencies and together with the all channels seeing the electronic noise.. i figure you're maybe doing acoustic emissions?

**Comment by rico4** [comment]
Ah ok. The channels are actually from different stations so maybe I made something wrong with the data that it does not recognize that there are different stations. Now I also applied a bandpass filter from 1-20 kHz which seems to make sense. 
Yes the data origin from a hydro-fracturing experiment in crystalline rock.
