### ISSUE TITLE
UTCDateTime with matplotlib's date2num

### ISSUE THREAD

**Issue by yannikbehr** [obspy/obspy#1715]
I observed some strange behaviour of `UTCDateTime` together with matplotlib's `date2num` function:
With matplotlib 1.5.2, obspy 1.0.3 and python2.7

```
In [1]: from matplotlib.dates import date2num
In [2]: from obspy import UTCDateTime
In [3]: date2num(UTCDateTime('2017-03-13T12:00:00.00Z'))
Out[3]: 736401.0
In [4]: date2num(UTCDateTime('2017-03-13T12:00:00.00Z').datetime)
Out[4]: 736401.5
```
if I don't convert the `UTCDateTime` object into a `datetime` object, the output is rounded down to the beginning of the day.

With matplotlib 2.0, obspy 1.0.3 and python3.5 `date2num` fails with `TypeError: 'datetime.date' object is not callable` if I don't convert the `UTCDateTime` object into a `datetime` object.

Cheers,
Yannik

**Comment by megies** [comment]
Thanks for reporting, @yannikbehr, we had some of these problems a while ago and I thought we'd fixed it once and for all.. guess we need to have another look)

Btw.. Starting with upcoming 1.1.0 there will be no need to manually go via `date2num` anymore, see #1339.

**Comment by yannikbehr** [comment]
I was just wondering whether you were aware of it. At least from my side there is no need to fix it especially with the new mpl feature in the pipeline.

**Comment by barsch** [comment]
is this related to: http://stackoverflow.com/questions/10825926/python-3-x-rounding-behavior

**Comment by megies** [comment]
> With matplotlib 1.5.2, obspy 1.0.3 and python2.7

Seems to be on Python 2..

**Comment by barsch** [comment]
older matplotlib version checked if its an instance of datetime while matplotlib 2.0.0 checks if the object has a date method attached 

matplotlib 1.5.2 (https://github.com/matplotlib/matplotlib/blob/v1.5.3/lib/matplotlib/dates.py#L222-L231)
-> datetimes were slightly differently handled as other objects
```
>>> date2num(datetime.datetime(2017, 3, 13, 12, 0))
736401.5
>>> date2num(UTCDateTime('2017-03-13T12:00:00.00Z'))
736401.0
```

matplotlib 2.0.0 (https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/dates.py#L223-L233)
```
>>> date2num(datetime.datetime(2017, 3, 13, 12, 0))
736401.5
>>> date2num(UTCDateTime('2017-03-13T12:00:00.00Z'))
*** TypeError: 'datetime.date' object is not callable
``` 

the documentation for date2num states that datetime objects or a list of daetime objects is expected - so don't if we can do much on our side ...

**Comment by barsch** [comment]
Converting to datetime before using date2num is the way to go for the reasons I stated above - with the upcoming ObsPy release you may use ```UTCDateTime.to_matplotlib()```
