### ISSUE TITLE
GSE2 read error on UTCDateTime call

### ISSUE THREAD

**Issue by freiter** [obspy/obspy#1723]
OBSPY Version: 1.0.3, Python 3.5 Platform: Win10X64 (installed via Anaconda3)

On calling the GSE2 read function from the script below I receive the error
File "c:\Anaconda3\envs\obspy\lib\site-packages\obspy\core\utcdatetime.py", line 330, in __init__
    dt = datetime.datetime(*args, **kwargs)
ValueError: second must be in 0..59

The python code file and the offending GSE2 file are attached in a zip file.

Best regards
Franz Reiter

from obspy import read
import numpy as np

#set length of trace in seconds
tracelength = 300

myFileName = r'c:\test\20070519_1619.GSE2'
st1 = read(myFileName, verify_chksum=False)
for index, x in np.ndenumerate(st1):
    #print(index, x)
    dt = x.stats.starttime
    x = x.slice(starttime=dt, endtime=dt + tracelength)
    myFileName = r'c:\test\\'
    myFileName = (myFileName + x.stats.station + '.' + x.stats.channel + '.'
              + x.stats.starttime.strftime("%Y") + '.' + str(x.stats.starttime.timetuple().tm_yday) + '.'
              + x.stats.starttime.strftime("%H") + '.' + x.stats.starttime.strftime("%M") + '.'
              + x.stats.starttime.strftime("%S") + '.mseed')
    x.write(myFileName, format='MSEED')

[GSE2toMSEED.zip](https://github.com/obspy/obspy/files/847504/GSE2toMSEED.zip)

**Comment by barsch** [comment]
your GSE2 files contains a WID2 headers with an incorrect datetime such as:

```WID2 2007/05/19 16:17:60.000 KIZ   HHN Nano CM6   144001  120.000000   0.25E+00   1.000 STS-2    0.0 90.0```

it worked for me after changing to a correct datetime value.

**Comment by megies** [comment]
@freiter would be good if you let the source of the GSE file know about the `...:60` second start time problem (they should correctly wrap to a new minute with 0 seconds)

**Comment by freiter** [comment]
@megies As I wrote in the obspy-users list the files are 10 yrs old. It is a published dataset by Diehl et. al, 2009 (Geophys. J. Int., 176, 542-554, doi: 10.1111/j.1365-246X.2008.03985.x). I can tell the corresponding author.

**Comment by megies** [comment]
Ah.. OK, nevermind then.. overlooked the files were so old, no need to start research on how the data was written and whether the problem might still exist in this case.
