### ISSUE TITLE
Error on mst_pack during conversion of a GSE2 file to mseed

### ISSUE THREAD

**Issue by freiter** [obspy/obspy#1724]
OBSPY Version: 1.0.3, Python 3.5 Platform: Win10X64 (installed via Anaconda3)

The script shown below and attached in the zip archive seeks all GSE2 files in the current directory and converts them to mseed single traces.
Conversion method: read into a stream. slice each trace into 5 min long pieces, write on disk with its stream name, channel, day of year, min, second as mseed file.
The script worked well on many old GSE2 files. For one file containing 200 traces (attached in the zip archive), the read operation works without error, the write operaton exits after writing 55 mseed files with the following error:
[ERROR.ZIP](https://github.com/obspy/obspy/files/851794/ERROR.ZIP)

File "C:\Anaconda3\envs\obspy\lib\site-packages\obspy\io\mseed\core.py", line 932, in _write_mseed
    raise Exception('Error in mst_pack')
Exception: Error in mst_pack

Pyton code used:
```python
from obspy import read
from obspy import Stream
import numpy as np
import glob, os

#set length of trace in seconds
tracelength = 300

os.chdir(r'e:\TEST')
for file in glob.glob("*.GSE2"):
    print(file)
    st1 = read(file, verify_chksum=False)
    print(st1.__str__(extended=True))
    os.mkdir(os.path.splitext(file)[0])
    os.chdir(os.path.splitext(file)[0])
    for i in range(0, st1.count()):
        dt = st1[i].stats.starttime
        st1[i] = st1[i].slice(starttime=dt, endtime=dt + tracelength)
        myFileName = (st1[i].stats.station + '.' + st1[i].stats.channel + '.'
              + st1[i].stats.starttime.strftime("%Y") + '.' + str(st1[i].stats.starttime.timetuple().tm_yday).zfill(3) + '.'
              + st1[i].stats.starttime.strftime("%H") + '.' + st1[i].stats.starttime.strftime("%M") + '.'
              + st1[i].stats.starttime.strftime("%S") + '.mseed')
        st1[i].write(myFileName, format='MSEED')
```

**Comment by megies** [comment]
Maybe you can replace the last line with:

```python
try:
     st1[i].write(myFileName, format='MSEED')
except:
     st1[i].write('/tmp/some_file', format='SLIST')
```

..and check what's in the file? Or drop in a debugger and check the contents of the Trace that can't be written?

**Comment by ThomasLecocq** [comment]
full error on win64py27

```
Traceback (most recent call last):
  File "GSE2toMSEED_ERROR.py", line 24, in <module>
    st1[i].write(myFileName, format='MSEED')
  File "obspy\obspy\core\trace.py", line 928, in write
    Stream([self]).write(filename, format, **kwargs)
  File "obspy\obspy\core\stream.py", line 1439, in write
    write_format(self, filename, **kwargs)
  File "obspy\obspy\io\mseed\core.py", line 921, in _write_mseed
    raise Exception('Error in mst_pack')
Exception: Error in mst_pack
Error: msr_encode_steim2(_BISS__HHN_D): Unable to represent difference in <= 30 bits
Error: msr_pack(_BISS__HHN_D): Error packing data samples
```

and the faulty trace:
![image](https://cloud.githubusercontent.com/assets/916937/24202234/bcc02184-0f12-11e7-9af4-ba3cce390d28.png)
contains an ugly dirac...

**Comment by Jollyfant** [comment]
Well that explains a lot.. seems to be working as intended but maybe the error could be slightly more descriptive.

**Comment by megies** [comment]
If the error tracebac prints as @ThomasLecocq showed it, it should be clear enough. But probably that's some mseed C layer stdout that is not shown on Linux because we catch it and silence it? @freiter did you see those messages "Unable to represent difference in <= 30 bits" when the error occurred?

**Comment by Jollyfant** [comment]
IMHO the difference in <= 30 bits is not very clear if you are unfamiliar with STEIM2 compression. There could be an added suggestion to check for spikes in the data to help users.

**Comment by freiter** [comment]
I did not see the exact cause for the error as @ThomasLecocq mentioned. The full error message is as folllows: 

"GSE2toMSEED_ERROR.py", line 27, in <module>
    st1[i].write(myFileName, format='MSEED')
  File "C:\Anaconda3\envs\obspy\lib\site-packages\obspy\core\trace.py", line 898, in write
    Stream([self]).write(filename, format, **kwargs)
  File "C:\Anaconda3\envs\obspy\lib\site-packages\obspy\core\stream.py", line 1444, in write
    write_format(self, filename, **kwargs)
  File "C:\Anaconda3\envs\obspy\lib\site-packages\obspy\io\mseed\core.py", line 932, in _write_mseed
    raise Exception('Error in mst_pack')
Exception: Error in mst_pack

**Comment by freiter** [comment]
Thanks to @ThomasLecocq and @megies for their suggestions to make the script fail-safe. I could handle all files with the `Error in mst_pack` with the following script:

```
from obspy import read
import glob, os
#set length of trace in seconds
tracelength = 300
os.chdir(r'e:\ERROR')
for file in glob.glob("*.GSE2"):
    st1 = read(file, verify_chksum=False)
    for i in range(0, st1.count()):
        dt = st1[i].stats.starttime
        st1[i] = st1[i].slice(starttime=dt, endtime=dt + tracelength)
        myFileName = (st1[i].stats.station + '.' + st1[i].stats.channel + '.'
              + st1[i].stats.starttime.strftime("%Y") + '.' + str(st1[i].stats.starttime.timetuple().tm_yday).zfill(3) + '.'
              + st1[i].stats.starttime.strftime("%H") + '.' + st1[i].stats.starttime.strftime("%M") + '.'
              + st1[i].stats.starttime.strftime("%S") + '.mseed')
        try:
            st1[i].write(myFileName, format='MSEED')
        except:
            st1[i].data = st1[i].data.clip(-2e30, 2e30)
            st1[i].write(myFileName, format='MSEED')
```

I put the clip function into the except block because it significantly increases file size and therefore should not run on non-faulty traces.
Why I can't see the full error could come from the different python version (py 3.5x vs 2.7x), but probably not from the operating system (win?? x64 in both cases).

**Comment by ThomasLecocq** [comment]
>I put the clip function into the except block because it significantly increases file size and therefore should not run on non-faulty traces.

This could be because `numpy.clip` returns `floats` and your original data are `ints`, I didn't check that.

>Why I can't see the full error could come from the different python version (py 3.5x vs 2.7x), but probably not from the operating system (win?? x64 in both cases).

I'm running on obspy-master version, not release 1.0.3, so maybe I already have a newer version of libmseed.

**Comment by krischer** [comment]
The changes in #1658 push the error messages to the very end also on non-windows systems which should make them more visible:

```
...
obspy.io.mseed.InternalMSEEDError: Encountered 2 error(s) during a call to mst_pack():
msr_encode_steim2(_BISS__HHN_D): Unable to represent difference in <= 30 bits
msr_pack(_BISS__HHN_D): Error packing data samples
```

> IMHO the difference in <= 30 bits is not very clear if you are unfamiliar with STEIM2 compression. There could be an added suggestion to check for spikes in the data to help users.

That would need to happen in libmseed as ObsPy just forwards those error messages. We could of course catch and rephrase it but that would mean we have to check and potentially adapt for new libmseed versions. I'd personally like to avoid that. If someone feels strongly that the error message should be improved, please open an issue on the libmseed github repo.

**Comment by megies** [comment]
I think the error message is meaningful enough, great that it's visible on Win now too. 👍
