### ISSUE TITLE
Support waveform/stream stacking

### ISSUE THREAD

**Issue by seisman** [obspy/obspy#1741]
Waveform stacking is frequently used in seismic data processing. Popular stacking methods are:

- linear stack
- Nth root stack
- phase weighted stack

I will try to implement it if it's possible to be included into obspy, maybe `obspy.Stream` or `obspy.signal`.

**Comment by calum-chamberlain** [comment]
Linear and phase-weighted stacks at implemented in eqcorrscan, would be happy to contribute them here if wanted?

**Comment by ThomasLecocq** [comment]
@calum-chamberlain I'm happy to contribute here too with the/comparing with the pws of msnoise.

**Comment by krischer** [comment]
This (almost done ;-) ) branch (https://github.com/obspy/obspy/pull/1002) also contains these stacks - so work should probably invested into finishing that branch and then generalizing the functionality.

**Comment by ThomasLecocq** [comment]
👍 for generalizing the stacks outside the array stuff... so investing on #1002 to do that is the way to go !

**Comment by trichter** [comment]
Implemented in #2440.
