### ISSUE TITLE
clients.neic: Blacklisted IP addresses

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1744]
Our public IP addresses at LMU Munich are blacklisted by the NEIC server we use for testing. I'm assuming that some automated routine blacklisted us for the large number of requests (when running obspy testsuites). @ketchum-usgs are you in contact with the people running the server (since you contributed the code initially).. so that we know whom to contact about this?

**Comment by ketchum-usgs** [comment]
Tobias,

I will create the necessary ticket but I would need to know the subnets your queries are coming from and the target NEIC server. 

Mark Vigil and Chris Bidwell will actually handle this. 

Dave

> On Mar 31, 2017, at 4:49 AM, Tobias Megies <notifications@github.com> wrote:
> 
> Our public IP addresses at LMU Munich are being blacklisted by the NEIC server we use for testing. I'm assuming that some automated routine blacklisted us for the large number of requests (when running obspy testsuites). @ketchum-usgs are you in contact with the people running the server (since you contributed the code initially).. so that we know whom to contact about this?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

David Ketchum - contractor          Office:  303 273-8479
ketchum@usgs.gov                    Cell :   303 520-5840

**Comment by megies** [comment]
Thanks for replying so fast, I've sent you an email about this.

**Comment by megies** [comment]
stale, and we're still blocked xD, closing.
