### ISSUE TITLE
AH (Ad Hoc) write support

### ISSUE THREAD

**Issue by s-schneider** [obspy/obspy#1754]
Currently there is read support for AH files, but no write support. I just wrote a short script, based on the obspy.io.ah module to write an read-in AH file as an AH-file again, but I have issues with the header information.

[https://github.com/s-schneider/nmPy/blob/master/nmpy/util/writeah.py
](https://github.com/s-schneider/nmPy/blob/master/nmpy/util/writeah.py)

**Comment by barsch** [comment]
I wrote the AH reader using those header files: https://github.com/obspy/obspy/tree/master/obspy/io/ah/docs which itself were extracted from ftp://www.orfeus-eu.org/pub/software/mirror/ldeo.columbia/ - I couldn't find any other proper documentation about AH 

also be aware there are two versions of AH - version 2 is as far as I know nowhere used and lacks proper real live example files

hope it helps,
Robert

**Comment by s-schneider** [comment]
thanks! It kind of works, but only if i specify the format
`st = read('foo.AH, format='AH')`

Otherwise I have problems with the _get_ah_version where the fixed values do not match. Do you have a clue what the purpose of these is?
```
elif magic == 6:
    # AH1 has no magic variable :/
    # so we have to use some fixed values as indicators
    try:
        fh.seek(12)
        if xdrlib.Unpacker(fh.read(4)).unpack_int() != 6:
            return False
        fh.seek(24)
        if xdrlib.Unpacker(fh.read(4)).unpack_int() != 8:
            return False
        fh.seek(700)
        if xdrlib.Unpacker(fh.read(4)).unpack_int() != 80:
            return False
        fh.seek(784)
        if xdrlib.Unpacker(fh.read(4)).unpack_int() != 202:
            return False
    except:
        return False
    return '1.0'
```

**Comment by barsch** [comment]
I really don't remember how I extracted this information - could be buggy ...

its probably somewhere buried deep inside ftp://www.orfeus-eu.org/pub/software/mirror/ldeo.columbia/ah_alpha.tar.Z - I rember looking especially on C files in ah2asc

also the comments on this PR https://github.com/obspy/obspy/pull/851 may help ...

**Comment by barsch** [comment]
ah i remember now - those fields are length indicator for the following string - as those strings are fixed, the length values are therefore also fixed:

_ah1.f_
![ah1](https://cloud.githubusercontent.com/assets/602450/3756069/f66facd8-182a-11e4-866b-57921aa87792.png)

AH v1 works with fixed strings therefore it reads (keep in mind XDR reads fields in a multiple of 4 bytes):

```
4 bytes = int (6) == length of following string
8 chars == string ('RSCP\0\0')
4 bytes = int (6) == length of following string
8 chars == string ('IPZ\0\0\0')
4 bytes = int (8) == length of following string
8 chars == string ('null\0\0\0\0')
```

**Comment by s-schneider** [comment]
Ah perfect, I hope I can make it work!

**Comment by s-schneider** [comment]
Robert, thanks! It works now. Right now I'm using the dictionary of each trace in the stream
`trace.stats.ah.station`, `trace.stats.ah.event`, `trace.stats.ah.record` etc as input. I'm just thinking about how to implement it in a `stream.write` format, linking station and event information of the inventory and catalog to it

**Comment by krischer** [comment]
Great. Make sure to send us  a PR once it fully works :)

**Comment by s-schneider** [comment]
I'm sorry for the stupid question, but as this will be my first PR for obspy: How should I design a test for the write module?

**Comment by Jollyfant** [comment]
I think it would be nice test to read => write => read a file.

**Comment by barsch** [comment]
look into other obspy.io modules. e.g. https://github.com/obspy/obspy/blob/master/obspy/io/ascii/tests/test_ascii.py

**Comment by s-schneider** [comment]
Ok thanks you guys. I added a test and sent a PR :)

**Comment by krischer** [comment]
Continued in #1757
