### ISSUE TITLE
Import error after installation python 3.5 (and 2.7)

### ISSUE THREAD

**Issue by emeraldbullet** [obspy/obspy#1758]
Hello,

I am trying to install OBSPY v 1.03-py35_1 via conda v 4.3.14 on MacOs 10.12.4 w/ updated Xcode (8.3.1) & Command line tools. I set-up environments for both python 3.5 & python 2.7 and cannot get it to work in either. Here are examples of the error:

In the python 3.5 environment after installation/update I run the command:
obspy-runtests

And get this ImportError:
ImportError: dlopen(/Users/(my user name)/anaconda2/envs/py35/lib/python3.5/site-packages/lxml/etree.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libicui18n.56.dylib
  Referenced from: /Users/(my user name)/anaconda2/envs/py35/lib/libxslt.1.dylib
  Reason: image not found

Using Ipython in the python 3.5 environment I run the command:
from obspy.core import read

And get this ImportError (same as above):
dlopen(/Users/(my user name)/anaconda2/envs/py35/lib/python3.5/site-packages/lxml/etree.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libicui18n.56.dylib
  Referenced from: /Users/(my user name)/anaconda2/envs/py35/lib/libxslt.1.dylib
  Reason: image not found

Any/all suggestions are welcome. Thank-You!

**Comment by QuLogic** [comment]
The conda-forge packages were (and still are, IMO) broken. Try `conda install 'icu=56.*' 'libxslt=1.1.29=2'`, and see further discussion in #1677.

**Comment by emeraldbullet** [comment]
That worked great, Thanks!!
