### ISSUE TITLE
ImportError: cannot import name 'iread_segy'

### ISSUE THREAD

**Issue by induswell** [obspy/obspy#1772]
I am following the example given in [obspy.io.segy.segy.iread_segy](https://docs.obspy.org/master/packages/autogen/obspy.io.segy.segy.iread_segy.html#obspy.io.segy.segy.iread_segy) documentation to iteratively read trace by trace through a big SEG-Y file, but got error on the import line:

`from obspy.io.segy.segy import iread_segy`

ImportError: cannot import name 'iread_segy'

I am using ObsPy 1.0.3 installed via Anaconda on Mac OSX Sierra.

Thanks!

**Comment by QuLogic** [comment]
That page is for `master`, which has not been released yet. Documentation of SEG-Y for released versions is [here](https://docs.obspy.org/packages/obspy.io.segy.html).

**Comment by krischer** [comment]
If you need the `iread_segy` function right now you can also just install the latest master branch. Best go to our chat room (https://gitter.im/obspy/obspy) if you need help with that.
