### ISSUE TITLE
Add support for the IRIS Federated Catalog Service

### ISSUE THREAD

**Issue by CelsoReyes** [obspy/obspy#1778]
IRIS has a  [Federated Catalog Webservice](https://service.iris.edu/irisws/fedcatalog/1/) that I have been tasked with integrating into ObsPy.

From the webpage:

> The irisws-fedcatalog web service returns selected time series channels from across multiple FDSN data centers. The combined catalog of channels is updated daily from each contributing data center.

The use of this module is similar to the existing fdsn Client.
```python
from obspy.clients.fdsn import FederatedClient
client = FederatedClient()
data = client.get_waveforms( ... ) #  just like normal
data = client.get_waveforms_bulk( ... ) #  just like normal
inv = client.get_stations( ... ) #  just like normal
inv = client.get_stations_bulk( ... ) #  just like normal
```

These would behave much like the normal versions, except that they would retrieve data from any number of data centers (providers), depending on the response of the fedcatalog service

one can also get the routing information without downloading the data
```
routes = client.get_routing( ... )
routes = client.get_routing_bulk( ... )
```

I have attached a diagram that shows how the parts interact:
[FederatedClient.pdf](https://github.com/obspy/obspy/files/979481/FederatedClient.pdf)

**Comment by megies** [comment]
I've copied the description over to #1779.. not much use for two duplicated tickets in parallel, I think.
