### ISSUE TITLE
wrong results with PPSD

### ISSUE THREAD

**Issue by blazvicic** [obspy/obspy#1793]
Hi!

I wanted to do some PPSD with obspy and somehow I fail to get a plot.

from obspy import  read_inventory, read
from obspy.signal import PPSD

```
st = read("data/waveforms/CEY.HHE.2017.001.00.00.00")
inv = read_inventory("data/staxml/CEY.xml")
#inv = {'gain': 60077000.0,'poles': [-0.037004+0.037016j, -0.037004-0.037016j,-251.33+0j, -131.04-467.29j, -131.04+467.29j],'sensitivity': 2516778400.0,'zeros': [0j, 0j]}

ppsd = PPSD(st[0].stats, metadata=inv)
ppsd.add(st)

st = read("data/waveforms/CEY.HHE.2017.002.00.00.00")
ppsd.add(st)

ppsd.plot()
```

If I use PAZ line it works, but if i use staxml line, the plot looks like that:
https://drive.google.com/open?id=0BzMcKedS7yadNWR3TFEwSlBWN3M

So either i'm doing something wrong (maybe staxml is not ok?) or there is a problem with "Metadata can be provided as an Inventory (e.g. from a StationXML file or from a request to a FDSN web service)"

Thanks!

**Comment by megies** [comment]
Your data seems to be ending up in the top-most bin (notice the yellow bar at the top). So, unless your station is sitting in the middle of a construction site, your metadata in the StationXML is probably wrong.. (or, of course the waveform data could have been tampered with and it's thus not correcting from digital counts to acceleration correctly)

Did you create the StationXML yourself or downloaded it from a data center?

**Comment by blazvicic** [comment]
ok, thanks, I will try downloading the sta xml.
Currently, I am using stationxml file created by db2stationxml command from Antelope software... Up till now i did not have any problems with this - and obspy is reading the file without any problems.

**Comment by blazvicic** [comment]
well, no luck... 
The only place on fdsn I could find this station is ORFEUS, and there is no data in the staxml except of location. I also finf the stationxml on http://eida.gfz-potsdam.de/webdc3/ but obspy does not read stationxml file downloaded from there...

**Comment by Jollyfant** [comment]
@blazvicic, you need to specify `level=response` to get all information from the web service.

    http://www.orfeus-eu.org/fdsnws/station/1/query?sta=CEY&level=response

ObsPy will be able to read ArclinkXML from the interface in the next release.

**Comment by blazvicic** [comment]
Ok, i downloaded the response from orfeus now and it seems with this staxml everything is ok. I will ask next week at the antelope user group meeting whats up with the staxml from antelope. Thanks!
