### ISSUE TITLE
Pathlib aware functions

### ISSUE THREAD

**Issue by krischer** [obspy/obspy#1794]
All of our I/O functions, mainly the various `read_X()` variants should be made aware of `pathlib` objects as these are getting more and more common.

**Comment by markcwill** [comment]
While we're at it, can I throw in request for support for URL-type strings, or `urlparse.ParseResult` objects? It'd be really nice to at least have some interface to patch in a custom way to turn a string into a file or IO object. The world is moving toward massively parallel stateless apps, and more of our files are at an `http://`, or `s3://` endpoint, and I'm starting to pass local file locations like this: `file:///path/to/file.txt`. 

Just thinking out loud, not 100% sure how this would look... also don't know how much this steps on the `Client` implementations for remote requests...

**Comment by krischer** [comment]
I'm not entirely sure what you mean so excuse me ig I misunderstood your request. `obspy.read("http://example.com/file")` already works. We could add support for a couple more protocols I guess but at a certain point it would just be simpler to do:

```python
def read_s3(path):
    with io.BytesIO() as buf:
        buf.write(s3.read_storage(path))
        buf.seek(0, 0)
        return obspy.read(buf)
```

**Comment by markcwill** [comment]
My thought was, if you're type-checking `filename_or_url` for `Path`, why not also check for a urllib `ParseResult`, and have a hook or method or plugin for dealing with various URL schemes. I didn't realize you had support for http, but it looks like you just check for `://`, and then pass to `requests`, so there's not really any place to add other schemes, maybe monkey patch `obspy.core.util.download_to_file`. Right now, passing it any URL string that `requests` doesn't understand will throw an Exception I imagine.

So yes, I agree wrapping `read` is the best option for now. Just wondering if there isn't a better one via a plugin system. Maybe not.

**Comment by megies** [comment]
If I understand correctly this would mean adding an entry point for all (or at least the most important) routines like `read`, `read_inventory` or `read_events`. Essentially replacing the current `if '://' in filename: # use requests for http downloading` with a plugin point for the ["scheme" part of the URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax)..

```
    'obspy.plugin.uri': [
        'file = obspy.core.util.base:open_file_stub',
        'http = obspy.core.util.base:download_to_file',
        'https = obspy.core.util.base:download_to_file',
    ]
```

I guess this is something that's only interesting for very advanced users, as not many people plug in more entry points into our structure (like tapers, or filters). Also, users could also do this by wrapping a tiny function around e.g. `read` that first fetches data from somewhere (e.g. some cloud storage `s3://...`) and then feeds the data to `read`.
But if people really push back such download helper routines it might be a benefit I guess. In any case it's probably a "why not".

**Comment by markcwill** [comment]
@megies, that's pretty much what I was saying. @krischer agree, it sounded like this was a proposal for an overhaul for all the functions:

> mainly the various read_X() variants 

so just putting my two cents in. I think maybe this was aimed at the main `read` so in that case, much easier to just wrap it myself. If this is going to be abstracted (as some type of Reader class/interface) to apply to all the `read_X` functions, I was just thinking out loud about how that would look.

We're getting too dangerously close to a chicken-and-egg problem, that I don't want to touch... [[should this be plugin specific, (`read_MSEED` knows how to open StreamIO, FileIO, some URL, `read_SAC` only knows to open FileIO, etc)]] so I'm going to stop now :)

**Comment by krischer** [comment]
> We're getting too dangerously close to a chicken-and-egg problem, that I don't want to touch... [[should this be plugin specific, (read_MSEED knows how to open StreamIO, FileIO, some URL, read_SAC only knows to open FileIO, etc)]] so I'm going to stop now :)

The URL parsing is done in `obspy.core` so it works for all file formats. The rest will hopefully be unified soon so each plug-in will always receive either a `BytesIO` object or some other reader that returns bytes (like an open file) - at that point I do hope to also unify all the `read_X()` function to have more common logic.

**Comment by lijunzh** [comment]
For now, we can easily use `obspy.read(str(Path('some/path/to/read'))`, but it will be great if our `read` is compatible with `pathlib.Path` object.

**Comment by dsentinel** [comment]
For functions that consume a path, currently in the form of a string,
`patharg = getattr(patharg, 'path', patharg)`
at the top will allow `str` or `pathlib` objects to used.

**Comment by dsentinel** [comment]
> My thought was, if you're type-checking filename_or_url for Path, why not also check for a urllib ParseResult, and have a hook or method or plugin for dealing with various URL schemes. I didn't realize you had support for http, but it looks like you just check for ://, and then pass to requests, so there's not really any place to add other schemes, maybe monkey patch obspy.core.util.download_to_file. Right now, passing it any URL string that requests doesn't understand will throw an Exception I imagine.

We did something similar with the NRL. 
https://github.com/obspy/obspy/blob/e68351d03a100137529dbac06615f140c8a5fb39/obspy/clients/nrl/client.py#L49

**Comment by tloubrieu-jpl** [comment]
Hello,

We are going to be soon interested in reading (obspy.core.read) from s3 buckets for our planetary data system. This is for for a science demo use case using the Apollo seismic observations of the moon.

Could that be part of this ticket ? 
Are you aware of anything proposed yet to read from s3 objects ?

I believe we could contribute ourselves with development and PR.

Thanks

**Comment by megies** [comment]
> Could that be part of this ticket ?

Please open a separate ticket as this has nothing to do with `pathlib`. :wink:

**Comment by megies** [comment]
Most functionality should be pathlib aware by now, so closing this. We can open new tickets if we find anything that needs to made pathlib aware.
