### ISSUE TITLE
Issues during installation

### ISSUE THREAD

**Issue by youlimao** [obspy/obspy#1799]
To whom it may concern:
     I am new to Python and currently working on a project rely on segy data. I tried to install the ObsPy on my machine (anaconda on Windows 7, python 3.5).

First, I tried: conda install obspy, which give me error package not found

Then, I tried to use pip install: pip install git+https://github.com/obspy/obspy.git
Somehow, half way through the installation process, I got some issues. I googled the issue can still could not fix it. I attached the screen shots of error during my installation:

![capture2](https://cloud.githubusercontent.com/assets/28906575/26415804/5c38d728-4079-11e7-8b4e-97021d6d58c2.PNG)
![capture1](https://cloud.githubusercontent.com/assets/28906575/26415811/60e22356-4079-11e7-81c9-ab538c65f467.PNG)

Does anyone have any idea on this issue?

Best,

Youli

**Comment by youlimao** [comment]
I downloaded the zip file and tried: python setup.py install,somehow it worked.

**Comment by krischer** [comment]
As written here (https://github.com/obspy/obspy/wiki/Installation-via-Anaconda) you have to install ObsPy using `conda` from the `conda-forge` channel. Either add it once and for all or only for the ObsPy installation:

```bash
$ conda install -c conda-forge obspy
```

I don't know a lot regarding compilation on windows so others will have to chime in if it still matters to you. Note that you can also `pip install obspy` and it will download a pre-compiled ObsPy package for windows which should also just work.

**Comment by krischer** [comment]
Also try not to use the zip file from github as it not an officially released version, use pypi for that: https://pypi.python.org/pypi/obspy
