### ISSUE TITLE
Does the bandpassfilter work correctly?

### ISSUE THREAD

**Issue by brainstormot** [obspy/obspy#1800]
Hi, I'm Hyuck

I have a problem with using bandpassfilter on 'Stream'

When I tried it like as belows, it didn't work well.
I think it makes huge artifact in front of the trace.
Not only in this trace, but also most of traces are similar to this.

<img width="729" alt="image" src="https://cloud.githubusercontent.com/assets/9497946/26564886/4d4f81ce-4521-11e7-8865-46466259fb99.png">

Did I do something wrong? or  Does the bandpassfilter have some bug?

```
def bandpass(data, freqmin, freqmax, df, corners=4, zerophase=False):
    """
    Butterworth-Bandpass Filter.

    Filter data from ``freqmin`` to ``freqmax`` using ``corners``
    corners.
    The filter uses :func:`scipy.signal.iirfilter` (for design)
    and :func:`scipy.signal.sosfilt` (for applying the filter).

    :type data: numpy.ndarray
    :param data: Data to filter.
    :param freqmin: Pass band low corner frequency.
    :param freqmax: Pass band high corner frequency.
    :param df: Sampling rate in Hz.
    :param corners: Filter corners / order.
    :param zerophase: If True, apply filter once forwards and once backwards.
        This results in twice the filter order but zero phase shift in
        the resulting filtered trace.
    :return: Filtered data.
    """
    fe = 0.5 * df
    low = freqmin / fe
    high = freqmax / fe
    # raise for some bad scenarios
    if high - 1.0 > -1e-6:
        msg = ("Selected high corner frequency ({}) of bandpass is at or "
               "above Nyquist ({}). Applying a high-pass instead.").format(
            freqmax, fe)
        warnings.warn(msg)
        return highpass(data, freq=freqmin, df=df, corners=corners,
                        zerophase=zerophase)
    if low > 1:
        msg = "Selected low corner frequency is above Nyquist."
        raise ValueError(msg)
    z, p, k = iirfilter(corners, [low, high], btype='band',
                        ftype='butter', output='zpk')
    sos = zpk2sos(z, p, k)
    if zerophase:
        firstpass = sosfilt(sos, data)
        return sosfilt(sos, firstpass[::-1])[::-1]
    else:
        return sosfilt(sos, data)
```

Frankly, I cannot comprehend the bandpassfilter code because I don't know the algorithm.

p.s. 'df' is sampling_rate in the above. But I learned that df = 1/T_max, isn't it?

**Comment by krischer** [comment]
You have to detrend and taper it before filtering to remove any linear trend and to make sure it starts with zero, e.g.

```python
st.detrend("linear")
st.taper(max_percentage=0.05, type="hann")
st.filter("bandpass", ...)
```

Otherwise your code looks correct - the `Stream.filter(...)` method takes care that all arguments are passed correctly to the underlying `bandpass(...)` function so you should not have to worry about it.


The `calib` factor also does not really do anything.

**Comment by megies** [comment]
👍 the large mean of the data is the problem here.

**Comment by brainstormot** [comment]
Thank for your kind reply. @krischer 

It works well.

![image](https://cloud.githubusercontent.com/assets/9497946/26668686/d5db5b42-46e5-11e7-9c9b-10fe6ed12b42.png)
