### ISSUE TITLE
Make locations2degree numpy compatible?

### ISSUE THREAD

**Issue by rizac** [obspy/obspy#1803]
Hi all,

This is not an issue but a sort of enhancement request/ question:
I would like to ask if you plan to make `locations2degree` (https://github.com/obspy/obspy/blob/master/obspy/geodetics/base.py#L309) numpy compatible. From the code it seems straighforward as all python `math` functions have a corresponding `numpy` equivalents (I implemented by myself such a method with a bunch of tests which confirm it's just a matter of string substitution).

Thank you in advance

**Comment by barsch** [comment]
why don't you open up a PR if you already have existing code + tests ?

**Comment by rizac** [comment]
Cause I first wanted to check if that was a desired behaviour or not.
I'll open a pull request then later, thanxs. Are there guidelines for tests? (I saw that obpsy uses doctests in the code, I am using pytest)

**Comment by barsch** [comment]
depends what you plan exactly: so do you plan
* to improve performance by using numpy internally (existing test will not fail)
* to extend it that numpy variables are additionally accepted (existing test will not fail)
* to replace it with numpy variables only (input/output is numpy only, existing tests will fail)

for the first two options you can IMHO just go ahead - for the latter one needs to check how this util function is used within ObsPy and if an API change is acceptable - I don't know how much this util function is used in other projects ...

concerning tests: we got doctests (mainly for documentation) as well as unit tests, e.g. https://github.com/obspy/obspy/blob/master/obspy/geodetics/tests/test_util_geodetics.py#L211-L244 - just have a look at the other unit tests

**Comment by rizac** [comment]
Done it (with few new tests all passing), thank you. However, when I try to push my branch:
```
git push -u origin locations2degrees_np_compatible
```
it tells me "Permission to obspy/obspy.git denied" (obviously). You should you grant me some permission i guess (or should I do something different?)

Thanks

**Comment by krischer** [comment]
You have to fork ObsPy to your own account (button at the top right), push your changes to that fork, and then send a PR from that.

https://opensource.guide/how-to-contribute/#opening-a-pull-request

**Comment by rizac** [comment]
Thanks

**Comment by rizac** [comment]
Created PR #1804 now merged with #1805 (see bug #1802)
