### ISSUE TITLE
Error in test_catch_output

### ISSUE THREAD

**Issue by trichter** [obspy/obspy#1809]
See http://tests.obspy.org/85131/#1

```
Traceback (most recent call last):
File "/opt/anaconda/envs/obspy/lib/python3.5/site-packages/obspy/core/tests/test_util_misc.py", line 52, in test_catch_output
self.assertEqual(out.stdout, b"abc\ndef\nghi\njkl\n")
AssertionError: b'abc\n\x1b[?1034hdef\nghi\njkl\n' != b'abc\ndef\nghi\njkl\n'
```

I installed obspy-master in an anaconda environment. See also http://tests.obspy.org/85118/ with the same failure.

**Comment by barsch** [comment]
will be obsolet with any implemention of a new CatchOutput manager - see https://github.com/obspy/obspy/pull/1854
