### ISSUE TITLE
A UTM converter?

### ISSUE THREAD

**Issue by lijunzh** [obspy/obspy#1812]
This is merely for discussion. I've been dealing with small dense array these days. It helps with coding (and is more intuitive) converting la&lo to UTM location. Do we have something built already?

I did found [this page](https://docs.obspy.org/tutorial/code_snippets/coordinate_conversions.html) in the doc that teaches you to use [pyproj](https://pypi.python.org/pypi/pyproj). However, it does not seem to solve my problem. I found this [utm](https://pypi.python.org/pypi/utm) on PyPI and has been using it for a while. It is pretty reliable and fast. I think we should have a page mentioning it in case someone else wants to make the conversion as I do.

**Comment by krischer** [comment]
Sounds good! Maybe just expand the existing page with a second option?

**Comment by lijunzh** [comment]
Good to hear people likes my idea. I will start a pull request to expand the docs. It might take some time since I never messed with obspy's docs before. Need to get myself familiar with the file structure etc.

**Comment by lijunzh** [comment]
Closed issue by accident. Reopen it until PR expand the docs.

**Comment by krischer** [comment]
By all means: Please go for it! Documentation work is always really appreciated.

**Comment by lijunzh** [comment]
@krischer I am a bit lost in the Obspy file system. Where should I start to change docs? Could you please point me to the source file of [this page](https://docs.obspy.org/tutorial/code_snippets/coordinate_conversions.html)?

Thanks a lot.

**Comment by trichter** [comment]
Hi, the source file for the mentioned page is located here: `obspy/misc/docs/source/tutorial/code_snippets/coordinate_conversions.rst`

**Comment by lijunzh** [comment]
@trichter Thanks a lot. How could I miss that? Anyway, I will make the changes shortly.

**Comment by trichter** [comment]
@lijunzh No problem, it's nested quite deep and `misc` is probably not the first folder you would look into...
