### ISSUE TITLE
Wrong ray path in moho reflected phases in taup at short distances

### ISSUE THREAD

**Issue by dmelgarm** [obspy/obspy#1815]
Hello,

Im using v1.0.1 on Mac OSX 10.11.6, obspy was isntalled via pip.

I'm having an issue with taup and moho reflected phases at short (a few degrees)  distances. The follwing code:

```
from obspy.taup import TauPyModel

depth_in_km=10.1
dist_in_degs=3.0
phase_list=['p','P','Pn','S','s','Sn']
velmod=TauPyModel(model='iasp91')
paths=velmod.get_ray_paths(depth_in_km,dist_in_deg,phase_list=phase_list)
paths.plot(plot_type='cartesian')
```

produces this result:

![rays_error](https://user-images.githubusercontent.com/2658464/27248061-86c88460-52b3-11e7-895e-72dd969ab2cb.png)

The Pn and Sn phases are very far from the station. Any ideas on how to correct this?

Thanks!

**Comment by QuLogic** [comment]
This is a dupe of #1392, which was fixed in 1.0.2.
