### ISSUE TITLE
Problem reading ObsPy SC3ML inventory (FW: mailing list)

### ISSUE THREAD

**Issue by Jollyfant** [obspy/obspy#1816]
Hi

I’ve made a station inventory using Gempa’s SMP tool. I’ve ensured the I export the xml as SC3XML/0.7, in line with Obspy.

However, when I try to read the inventory in Obspy, I get the following error:

    Traceback (most recent call last):
    File "./test.py", line 4, in <module>
    inv = read_inventory('sph1r17_VOiLA-onshore-8.xml')
    ...
    File "/Users/sph1r17/anaconda/lib/python3.5/site-packages/obspy/io/seiscomp/sc3ml.py", line 472, in _read_channel
     response_element, cha_element,
    UnboundLocalError: local variable 'response_element' referenced before assignment

The xml file is here if anyone would like to see it:  https://www.dropbox.com/s/nso0fdtf5uj3yeo/sph1r17_VOiLA-onshore-8.xml?dl=0.

The smp repository can be found here:  https://smp.gempa.de/sph1r17/VOiLA-onshore

The sensor and digitiser response seems to be correctly attached in the xml file.

Can anyone assist me here with trying to get to the root of the problem?

Thanks in advance for your help
Steve

**Comment by Jollyfant** [comment]
See #1817 for pull request

**Comment by Jollyfant** [comment]
To find response information the code expected the publicID to be prepended with `reponsePaz#` (to differentiate easily type of response (i.e. between PAZ & Polynomial). However, in this case the publicID is an arbitrary string. 

It also crashed on the missing `<depth>` element in the channel definitions.

**Comment by megies** [comment]
Next time just open the PR, no need for a second "plain issue" ticket duplicate, just bloats our issue list and makes finding things later harder, IMHO.
