### ISSUE TITLE
PPSD - accelerometer

### ISSUE THREAD

**Issue by shicks-seismo** [obspy/obspy#1824]
I think the PPSD function should eventually include a special handling case for an accelerometer. This is a little like the 'ringlaser' / rotational case, but the frequency response still needs to be deconvolved.

**Comment by megies** [comment]
Are you sure there's a problem?

**Comment by shicks-seismo** [comment]
Well, for the seismometer case, the PSD spectrum is multiplied by 2*pi*f to bring it with respect to acceleration. This step does not need to be taken for an accelerometer.
Or am I missing something?

**Comment by megies** [comment]
The response that is calculated by evalresp should be going to "velocity", regardless of input sensor type (data are usually in raw counts anyway). So deriving afterwards to go to acceleration should be fine.

Of course it's still a bit different because the PSD is calculated on raw data which is proportional to acceleration, but I guess that should be fine as well. Not 100% sure as I'm not working with accelerometers, really.  Maybe @aringler-usgs can comment on this.

**Comment by shicks-seismo** [comment]
Yes, I agree that evalresp to correct for velocity should be fine.

PPSD doesn't use evalresp though as the frequency response is deconvolved from the PSD - not from the raw trace. In my usage case, I am using a PAZ dictionary, and no correction to velocity is being done prior to calculation of the PSD.

The other alternative is to get velocity is to integrate the traces first, or to add an extra complex zero in the accelerometer PAZ dictionary, but I don't think this is the natural choice for calculating PSDs.

Interested to hear Adam's thoughts.

**Comment by megies** [comment]
> PPSD doesn't use evalresp though

In general it does, if you're using anything else but a PAZ dictionary.

> as the frequency response is deconvolved from the PSD - not from the raw trace

still it's being calculated by evalresp in general, just not in your case (PAZ dict)

> In my usage case, I am using a PAZ dictionary, and no correction to velocity is being done prior to calculation of the PSD.

PPSD doesnt do instrument correction before PSD, i.e. in time domain. It actually used to do it in time domain but this was changed a long time ago in #931 which is in ObsPy since version 1.0.0 (Feb 2016).

> The other alternative is to get velocity is to integrate the traces first, or to add an extra complex zero in the accelerometer PAZ dictionary, but I don't think this is the natural choice for calculating PSDs.

So, actually when a PAZ is provided, PPSD silently assumes that the PAZ is going to velocity. That's just historical reasons because I used to always only worked with seismometers. Maybe this should be stated in the docstring. But at least it's clearly stated that using a SEED Parser or Inventory is by far preferred to a PAZ dictionary.. ;-)


In any case.. as a workaround, you should be able to use your PAZ that go to acceleration and use the `hydrophone` switch (if you're on master at least), which omits differentiating:

```python
 810             # Do not differentiate when `special_handling="hydrophone"`
 811             if self.special_handling == "hydrophone":
 812                 spec = spec / respamp
 813             else:
 814                 spec = (w ** 2) * spec / respamp
```

**Comment by aringler-usgs** [comment]
Opps.  I just saw this today.

Would it be helpful to have a special handling case of "accelerometer," which would not assume velocity PAZ?  Let me know if you would like this and we can have someone here do a pull request.

**Comment by megies** [comment]
I'm a bit torn on this one. Actually, I think it might be cleanest to eventually get rid of the PAZ dictionary option completely and enforce "proper" metadata. For Inventory objects, it's clear to what units the Response is going and we can handle it internally properly.

A different approach might be to implement a helper function that converts a plain PAZ dictionary (specifying the output units, be it velocity or acceleration) to a `Response` object? Basically the other way around from #1097 (which I never finished..).

**Comment by krischer** [comment]
This seems to be the better plan to me. Our `Response` object could easily offer a convenience method `Response.from_paz()` that generates the correct object hierarchy.

**Comment by aringler-usgs** [comment]
Let us see what we can do for making a Response.from_paz() method.  @amkearns-usgs was going to look into this.

**Comment by amkearns-usgs** [comment]
Hi, as mentioned I am currently working on a function to create a response from p/z values. I am currently working with python 2 and trying to run the testing script (runtests.py). I'm getting an error from this. Should I be trying to run tests from python 3?

**Comment by barsch** [comment]
```runtest.py``` should work under python 2.7 - why don't you post the full traceback?

**Comment by megies** [comment]
@amkearns-usgs `pytest` is probably most convenient when you only want to run a single specific test case.. see https://docs.pytest.org/en/latest/usage.html#specifying-tests-selecting-tests

**Comment by amkearns-usgs** [comment]
=========================  test_response.py  =========================
unhandled exception occurred while testing test_response
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/logilab/common/pytest.py", line 447, in testfile
    options=self.options, outstream=sys.stderr)
  File "/usr/lib/python2.7/dist-packages/logilab/common/pytest.py", line 763, in __init__
    testLoader=NonStrictTestLoader())
  File "/usr/lib/python2.7/unittest/main.py", line 77, in __init__
    self.module = __import__(module)
  File "test_response.py", line 29, in <module>
    from obspy.core.util import MATPLOTLIB_VERSION
ImportError: cannot import name MATPLOTLIB_VERSION
*******************************************************************************
Ran 1 test cases in 0.00s (0.00s CPU), 1 errors
0 modules OK (1 failed)
failures: obspy/obspy/core/tests/test_response [1/1]

**Comment by krischer** [comment]
Did you install ObsPy as a dev version and also remove all previously installed ObsPy versions?

```bash
pip install -v -e .  # In ObsPy's root directory
```

I can also only recommend developing on Python 3. The way we set things up results in ObsPy pretty much being Python 3 code with Python 2 being handled by a compatibility layer.

**Comment by megies** [comment]
> File "/usr/lib/python2.7/dist-packages/logilab/common/pytest.py", line 447, in testfile

Not sure about your environment setup..  but I'd avoid using global system environment for development

**Comment by QuLogic** [comment]
> > File "/usr/lib/python2.7/dist-packages/logilab/common/pytest.py", line 447, in testfile
> 
> Not sure about your environment setup.. but I'd avoid using global system environment for development

That is also the wrong `pytest`, which may not have been removed in older distros. You might need to install/use `py.test` or similar.

**Comment by megies** [comment]
@QuLogic Sure? Recent Anaconda packages also seem to go by `pytest` rather than `py.test`.

```bash
(master) wintermute:~/anaconda/envs/master/lib/python2.7/site-packages$ find . -name '*pytest*'
./pytest-3.2.3-py2.7.egg-info
./_pytest
./_pytest/pytester.py
./_pytest/pytester.pyc
./pytest.py
./pytest.pyc
./pytest_random-0.2.dist-info
./sqlalchemy/testing/plugin/pytestplugin.py
./sqlalchemy/testing/plugin/pytestplugin.pyc
./pytest_xdist-1.16.0-py2.7.egg-info
(master) wintermute:~/anaconda/envs/master/lib/python2.7/site-packages$ find . -name '*py.test*'
(master) wintermute:~/anaconda/envs/master/lib/python2.7/site-packages$ 
```

Anaconda installs executables as both `py.test` and `pytest` for me, doing exactly the same.

```bash
(master) wintermute:~/anaconda/envs/master/lib/python2.7/site-packages$ which py.test 
/home/megies/anaconda/envs/master/bin/py.test
(master) wintermute:~/anaconda/envs/master/lib/python2.7/site-packages$ which pytest 
/home/megies/anaconda/envs/master/bin/pytest
(master) wintermute:~/anaconda/envs/master/lib/python2.7/site-packages$ ll /home/megies/anaconda/envs/master/bin/py.test
-rwxrwxr-x 1 megies users 138 Oct  6 12:12 /home/megies/anaconda/envs/master/bin/py.test*
(master) wintermute:~/anaconda/envs/master/lib/python2.7/site-packages$ ll /home/megies/anaconda/envs/master/bin/pytest
-rwxrwxr-x 1 megies users 138 Oct  6 12:12 /home/megies/anaconda/envs/master/bin/pytest*
(master) wintermute:~/anaconda/envs/master/lib/python2.7/site-packages$ diff /home/megies/anaconda/envs/master/bin/py.test /home/megies/anaconda/envs/master/bin/pytest
(master) wintermute:~/anaconda/envs/master/lib/python2.7/site-packages$
```

Debian, too.. https://packages.debian.org/search?keywords=pytest&searchon=names&suite=stable&section=all

**Comment by QuLogic** [comment]
The `pytest` _executable_ was only added in 3.0. And whatever the executable might be named, the code should certainly not be in a `logilab` directory; that's definitely the old and mostly useless one.

**Comment by megies** [comment]
Ok, no idea about this logilab thingy.. but judging from that it's in `dist-packages`.. without knowing the distro, this looks like system-packaging.. so, that this bundled pytest gets used from outside of the bundling package seems like bad habit..?

**Comment by megies** [comment]
Should be obsolete, I believe, if an Inventory is provided
