### ISSUE TITLE
Ways to Speed Processing Large SEG-Y Files

### ISSUE THREAD

**Issue by induswell** [obspy/obspy#1826]
Hello:

First of all, ObsPy is a great product. Thank you for all your excellent works!

Are there best practices on processing large SEG-Y files? I have recently run into SEG-Y files with over 1TB in size containing hundreds of millions of traces. I have tried to iteratively read the SEG-Y file described [here](https://docs.obspy.org/master/packages/autogen/obspy.io.segy.segy.iread_segy.html#obspy.io.segy.segy.iread_segy) using the current ObsPy master branch. 

```
from obspy.io.segy.segy import iread_segy
for trace in iread_segy(filename):
    # Do something meaningful.
    print(int(trace.data.sum() * 1E9))
```

It allows me to process through the big SEG-Y file, but it takes a several days to finish. 

Are there any other avenues that I can explore to improve the process time? Please advise.

Thanks in advance.

Indus

**Comment by krischer** [comment]
Hey Indus,

have you checked what the limiting factor is? Is it I/O (with ObsPy) or the actual processing you are doing? If it is the I/O: There are probably a bunch of things in `obspy.io.segy` that could be done in a more efficient manner. If it is processing you'll probably have to parallelize it in some fashion. That is fairly easy with SEG-Y as the format basically consists of lots of evenly sized blocks that can be processed in an embarrassingly parallel fashion.

If you give us a bit more information we can give more helpful advise :)

Cheers!

Lion

**Comment by induswell** [comment]
Thanks for your quick reply, @krischer. Basically I am reading the SEG-Y file trace by trace and save the trace data along with a few trace header attributes to delimited text files. Currently, the reading/saving process does about 400 traces per second. Sounds like parallel processing is possible. Please advise.

Thanks,
Indus

**Comment by krischer** [comment]
Please add some timers to figure out what is actually the slowest part. If it disc I/O limited (which with 400 traces/second might well be the case - if you save each trace to a different file you'll have a lot of file write to different physical disc (or SSD) locations) you will not gain a lot if you start hitting that disc with multiple parallel processes.

Also be aware that ASCII encoded data is terribly slow and and space inefficient to write.

The following snippet will print some semi-accurate timing information. Add more steps for finer grained information. You should probably also calculate averages for all of these every 1000 or so traces to get more trustworthy measurements.

```python
import time
...

from obspy.io.segy.segy import iread_segy

_s = time.time()
for trace in iread_segy(filename):
    _a = time.time()
    print("Time for reading trace with ObsPy:", _a - _s)
    # Do something meaningful.
    print(int(trace.data.sum() * 1E9))
    _b = time.time()
    print("Time for processing:", _b - _a)
    _s = time.time()
```

**Comment by megies** [comment]
stale, closing.
