### ISSUE TITLE
dayplot when delta is 0.15094

### ISSUE THREAD

**Issue by cerinunn** [obspy/obspy#1828]
I'm having trouble with 'dayplot'. I think something is going wrong with the pixels with the delta value is a long decimal value  - or something like that. There's a code snippet below. 

Correct - delta = 1 s: 
<img width="706" alt="screen shot 2017-06-28 at 11 52 35" src="https://user-images.githubusercontent.com/10745578/27631289-4f887ce6-5bf8-11e7-9e05-5aa458b9140a.png">

Incorrect - delta = 0.15094 s: 
<img width="702" alt="screen shot 2017-06-28 at 11 53 14" src="https://user-images.githubusercontent.com/10745578/27631333-695b71d2-5bf8-11e7-98bb-e4526ad6acca.png">

```
from obspy.core import Stream, Trace
import numpy as np
stream = Stream()
trace = Trace()
trace.data = np.array([87.0,87.25,87.5,87.75,88.0,88.25,88.5,88.75,89.0,89.25, 89.5, 89.75, 0.0, 0.25,
  0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2.75, 3.0, 3.25, 3.5, 3.75, 4.0, 4.25, 4.5, 4.75,
  5.0, 5.25,  5.5, 5.75,6.0, 6.25,  6.5, 6.75,7.0, 7.25,  7.5, 7.75, ])
trace.trim(endtime=trace.stats.starttime+3*60,pad=True)
stream.append(trace)

# In this plot, the lines are smooth (with one discontinuity between 89.75 and 0.0)
# To see it, zoom in manually
stream[0].stats.delta=1
stream.plot(type ='dayplot',time_offset=0,show_y_UTC_label=False)

# In this plot, the discontinuity is incorrect (and occurs several times),
# and the line between 0 and 7.75 is stepped
stream[0].stats.delta= 0.15094
stream.plot(type ='dayplot',time_offset=0,show_y_UTC_label=False)

```

ObsPy is version 1.0.2, installed from Anaconda on Mac. Python version is 3.5. 

Thanks in advance for any help!!!!

**Comment by krischer** [comment]
The dayplots (and also the normal stream plots) are not meant to be zoomed in - they can only be viewed at the original zoom settings. What you are seeing is just an artifact of the min-max-binning which is used to make the plots feasible for very large sample counts (plotting each sample is way too expansive and the binning acts as decimation operation that does not change the appearance of the plot).

If you decrease the interval, the binning no longer kicks in and and it plots "fine" for this delta.

```python
stream.plot(type="dayplot", interval=5.0)
```

**Comment by cerinunn** [comment]
Lion, thanks for the helpful reply. Excellent service, as always!!
