### ISSUE TITLE
How to add a vline  in Obspy

### ISSUE THREAD

**Issue by maihao14** [obspy/obspy#1833]
I want to add a  vertical line in Obspy plot figure  just  like  :Python matplotlib  command 
    plt.axvline(1234)  to point out a special point in plot figure
I do not know how to do this in  obspy  plot function 
Looking for your help!

**Comment by Jollyfant** [comment]
In `Stream.plot()` you can specify `handle=True`. That will return the figure handle that can then be edited.

    import datetime
    fig = st.plot(handle=True) 
    fig.axes[0].axvline(datetime.datetime(2011, 3, 11))

Will plot a vertical bar on a waveform plot at 2011-03-11T00:00:00. Hope it helps.

**Comment by QuLogic** [comment]
For any small-to-medium modifications, you should use the Matplotlib API as @Jollyfant described. For large modifications, it's better to just create the plot yourself.
