### ISSUE TITLE
FDSNException: No data available for request

### ISSUE THREAD

**Issue by MarthaDeen** [obspy/obspy#1835]
Hi, 

I tried downloading continuous data using client.get_waveforms() (fdsn_client set to IRIS). I did this for the networks II, GT, IU, G (4 stations) and AU (8 stations). 

from obspy.fdsn import Client
fdsn_client = Client('IRIS')
st = fdsn_client.get_waveforms(network='AU', station='CARL', location='00',channel='LHZ', starttime=t1, endtime=t2,attach_response=True)

For the stations of AU I get an error:
FDSNException: No data available for request

I tried retrieving a station list for the AU network using client.get_stations, but there were none. The network is listed on the fdsn website though.. 
Is anyone else having similar problems? Should it be a problem of obspy, fdsn or the specific network?

Thanks for your help!

**Comment by Jollyfant** [comment]
Hi, what version of ObsPy are you running? You are importing from obspy.fdsn which no longer exists.

    import obspy
    print obspy.__version__

because this snippet works for me and I can see the AU inventory from IRIS.

    from obspy.clients.fdsn import Client
    fdsn_client = Client("IRIS")
    print fdsn_client.get_stations(network="AU")

    >>> Inventory (159 Stations)

**Comment by MarthaDeen** [comment]
Hi Jollyfant, 

I have ObsPy version 0.10.2
Today I do get the list of stations of the network AU using
print fdsn_client.get_stations(network="AU")

But still the same message when trying to get the waveforms. 
Did you manage to download the data?

**Comment by ThomasLecocq** [comment]
@MarthaDeen 0.10.2 has been released on 27 May 2015, maybe it's time for you to update your installation and test with the latest version...

**Comment by Jollyfant** [comment]
If you want to get channel or response information you will need to pass another keyword:

    fdsn_client.get_stations(network="AU", level="channel")

or in the case of instrument response pass `level="response"`.

For waveforms it is OK for me. Can you run the following code to see if it works:

    from obspy.clients.fdsn import Client
    from obspy import UTCDateTime

    client = Client("IRIS")
    t1 = UTCDateTime("2010-02-27T06:30:00.000")
    st = client.get_waveforms("AU", "*", "*", "*", t1, t1 + 5)

    >>> 167 Trace(s) inStream ...

The fact that you get no data is possibly because the request is too large, or that there is no data for the requested time window. If you give us your script we can check.

**Comment by MarthaDeen** [comment]
@ThomasLecocq I already did

**Comment by MarthaDeen** [comment]
@Jollyfant 
I used: 
st = fdsn_client.get_waveforms(network='AU', station='CARL', location='00',channel='LHZ', starttime=t1, endtime=t2,attach_response=True)
with t1= UTCDateTime("2013-01-1T0:00:00.000")
and t2 = t1+5;
The problem lies in the fact that this station (as many other stations from this network) does not have a location 00, nor does it have a channel LHZ.
It worked after using the wildcard options! 
st = client.get_waveforms("AU", "CARL", "*", "*", "??Z",t1, t2)
That is, for the BNZ component.

Thanks for your help!

**Comment by Jollyfant** [comment]
Ok nice! Feel free to re-open this issue if necessary.

**Comment by ThomasLecocq** [comment]
@MarthaDeen sorry, I didn't get it due to a typo :) !

> I had ObsPy version to 0.10.2
> ...
> Now I updated my ObsPy version to 0.10.3
