### ISSUE TITLE
obspy_version script

### ISSUE THREAD

**Issue by bonaime** [obspy/obspy#1836]
Hi,

Can you add this simple script to obspy/misc/scripts/ ? 

obspy_version:
```bash
python -c "from obspy import __version__; print __version__"
```

**Comment by krischer** [comment]
What is the main rational behind that request? Two lines of Python is in my opinion reasonable. But if there is an actual need for this I'm open to discuss this.

Personally I'd rather restructure all the scripts we have and just have a single `obspy` entry-point that then delegates to the other scripts similar to how git does it. Then this could have an `obspy --version` variant.

**Comment by bonaime** [comment]
It could be usefull for people posting issues.

**Comment by QuLogic** [comment]
All commands take `-V`/`--version`, so I don't see the point.

**Comment by megies** [comment]
> All commands take -V/--version, so I don't see the point.

Also, `obspy-runtests` shows version number and path to installation..

```
$ obspy-runtests 
Running /home/megies/git/obspy/obspy/scripts/runtests.pyc, ObsPy version '1.0.3.post0+1265.g9f951c11b9.obspy.master'
...
```

So, I'm also not sure if we really need this..

**Comment by bonaime** [comment]
ok !
