### ISSUE TITLE
signal/util.py/_npts2nfft: Indentation mistake

### ISSUE THREAD

**Issue by sceylan** [obspy/obspy#1837]
We have noticed an indentation error in  `obspy/signal/util.py`, method `_npts2nfft` when determining nfft. Which `if` level does the `else` statement at the end belong to (line 294-295)? 

```        
    # check if we have a bad factorization with large primes
    if smart and nfft > 5000 and not _good_factorization(nfft):
        # try a few numbers slightly larger for a suitable factorization
        # in most cases after less than 10 tries a suitable nfft number with
        # good factorization is found
        for i_ in range(1, 11):
            trial = int(nfft + 2 * i_)
            if _good_factorization(trial):
                nfft = trial
                break
        else:
            nfft = next_pow_2(nfft)
```

**Comment by calum-chamberlain** [comment]
Fairly sure this isn't an error - the else relates to the for statement as documented [here](https://docs.python.org/2/tutorial/controlflow.html#break-and-continue-statements-and-else-clauses-on-loops).

**Comment by sceylan** [comment]
Aha! Thanks a bunch.
