### ISSUE TITLE
read_inventory fails on bad station metadata

### ISSUE THREAD

**Issue by shaharkadmiel** [obspy/obspy#1839]
For some reason which I have not figured out yet, station IV.LATE (INGV, Latera) caused the ``read_inventory`` function to fail with an ``AttributeError: 'NoneType' object has no attribute 'strip'`` 

Traceback:

```python
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/core/inventory/inventory.py", line 72, in read_inventory
    format=format)[0]
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/core/util/base.py", line 462, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/io/stationxml/core.py", line 155, in _read_stationxml
    networks.append(_read_network(network, _ns))
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/io/stationxml/core.py", line 201, in _read_network
    stations.append(_read_station(station, _ns))
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/io/stationxml/core.py", line 242, in _read_station
    channels.append(_read_channel(channel, _ns))
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/io/stationxml/core.py", line 312, in _read_channel
    longitude=longitude, elevation=elevation, depth=depth)
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/core/inventory/channel.py", line 129, in __init__
    self.location_code = location_code
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/core/inventory/channel.py", line 207, in location_code
    self._location_code = value.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

After some debugging, I realised that in the ``_read_channel`` function, all values (longitude, latitude, elevation, depth, code, and location_code) are ``None`` and that causes the ``Channel.__init__`` to fail.

Currently, my workaround is to wrap line 237 in ``obspy/io/stationxml/core.py`` in a ``try/except`` statement:

```python
    channels = []
    for channel in sta_element.findall(_ns("Channel")):
        try:
            channels.append(_read_channel(channel, _ns))
        except AttributeError:
            warnings.warn('No channels available for station:\n'
                          '{}'.format(str(station)))
        # channels.append(_read_channel(channel, _ns))
    station.channels = channels
```

This results in a station entry in the inventory object with 0 channels.

I don't know if this is the preferred behavior but for now it works for me.

**Comment by krischer** [comment]
Hi Shahar,

can you upload the file? If it has a channel and all the coordinates are not set it is not valid StationXML file but I agree that ObsPy should be forgiving here and read it nonetheless.

Cheers!

**Comment by shaharkadmiel** [comment]
Here you go:

[IV.LATE.xml.zip](https://github.com/obspy/obspy/files/1141939/IV.LATE.xml.zip)

**Comment by Jollyfant** [comment]
We did it for SC3ML in https://github.com/obspy/obspy/pull/1817 so might as well do it for StationXML too.

**Comment by krischer** [comment]
Done in #1840.

**Comment by petrrr** [comment]
@shaharkadmiel: OT, but I'd like to encourage you to report metadata issues back to the respective data centre. We, i.e. INGV data centre, appreciate such reports and even if we might not react immediately, we try to resolve them. Of cause some preliminary analysis/description of the problem helps.

I'm aware that currently it is not always straight for find the right place to report. For INGV seismic datacentre you can report to eida@ingv.it or use the following public project I just created:
 * https://github.com/INGV/EIDA-metadata

Sorry for hitchhiking this issue ;-)

**Comment by megies** [comment]
> OT, but I'd like to encourage you to report metadata issues back to the respective data centre

👍

**Comment by petrrr** [comment]
While there is effectively some issue in the metadata catalog for the cited station, I guess that it still might occur that a station has no selected channel-epoch for a station. If the selected channel epochs are zero, this needs to be handled and no channel related data should be expected.
