### ISSUE TITLE
Obspy st.merge(method=1) problem: "Can't merge traces with same ids but differing sampling rates!"

### ISSUE THREAD

**Issue by Danielita88** [obspy/obspy#1846]
- I have a data in MSEED with these characteristics:

print st0
3 Trace(s) in Stream:
.AN6..S Z | 2010-03-02T00:57:03.143000Z - 2010-03-02T01:57:03.123000Z | 50.0 Hz, 180000 samples
.AN6..S N | 2010-03-02T00:57:03.143000Z - 2010-03-02T01:57:03.123000Z | 50.0 Hz, 180000 samples
.AN6..S E | 2010-03-02T00:57:03.143000Z - 2010-03-02T01:57:03.123000Z | 50.0 Hz, 180000 samples
print st2
3 Trace(s) in Stream:
.AN6..S Z | 2010-03-02T02:57:03.149000Z - 2010-03-02T03:57:03.129000Z | 50.0 Hz, 180000 samples
.AN6..S N | 2010-03-02T02:57:03.149000Z - 2010-03-02T03:57:03.129000Z | 50.0 Hz, 180000 samples
.AN6..S E | 2010-03-02T02:57:03.149000Z - 2010-03-02T03:57:03.129000Z | 50.0 Hz, 180000 samples
print st3
3 Trace(s) in Stream:
.AN6..S Z | 2010-03-02T03:57:03.153000Z - 2010-03-02T04:57:03.133000Z | 50.0 Hz, 180000 samples
.AN6..S N | 2010-03-02T03:57:03.153000Z - 2010-03-02T04:57:03.133000Z | 50.0 Hz, 180000 samples
.AN6..S E | 2010-03-02T03:57:03.153000Z - 2010-03-02T04:57:03.133000Z | 50.0 Hz, 180000 samples
print st4
3 Trace(s) in Stream:
.AN6..S Z | 2010-03-02T04:57:03.156000Z - 2010-03-02T05:57:03.136000Z | 50.0 Hz, 180000 samples
.AN6..S N | 2010-03-02T04:57:03.156000Z - 2010-03-02T05:57:03.136000Z | 50.0 Hz, 180000 samples
.AN6..S E | 2010-03-02T04:57:03.156000Z - 2010-03-02T05:57:03.136000Z | 50.0 Hz, 180000 samples
print st5
3 Trace(s) in Stream:
.AN6..S Z | 2010-03-02T05:57:03.159000Z - 2010-03-02T06:57:03.139000Z | 50.0 Hz, 180000 samples
.AN6..S N | 2010-03-02T05:57:03.159000Z - 2010-03-02T06:57:03.139000Z | 50.0 Hz, 180000 samples
.AN6..S E | 2010-03-02T05:57:03.159000Z - 2010-03-02T06:57:03.139000Z | 50.0 Hz, 180000 samples
print st6
3 Trace(s) in Stream:
.AN6..S Z | 2010-03-02T06:57:03.162000Z - 2010-03-02T07:57:03.142000Z | 50.0 Hz, 180000 samples
.AN6..S N | 2010-03-02T06:57:03.162000Z - 2010-03-02T07:57:03.142000Z | 50.0 Hz, 180000 samples
.AN6..S E | 2010-03-02T06:57:03.162000Z - 2010-03-02T07:57:03.142000Z | 50.0 Hz, 180000 samples
print st7
3 Trace(s) in Stream:
.AN6..S Z | 2010-03-02T07:57:03.165000Z - 2010-03-02T08:57:03.245802Z | 50.0 Hz, 180000 samples
.AN6..S N | 2010-03-02T07:57:03.165000Z - 2010-03-02T08:57:03.245802Z | 50.0 Hz, 180000 samples
.AN6..S E | 2010-03-02T07:57:03.165000Z - 2010-03-02T08:57:03.245802Z | 50.0 Hz, 180000 samples
print st8
3 Trace(s) in Stream:
.AN6..S Z | 2010-03-02T08:57:03.168000Z - 2010-03-02T09:57:03.148000Z | 50.0 Hz, 180000 samples
.AN6..S N | 2010-03-02T08:57:03.168000Z - 2010-03-02T09:57:03.148000Z | 50.0 Hz, 180000 samples
.AN6..S E | 2010-03-02T08:57:03.168000Z - 2010-03-02T09:57:03.148000Z | 50.0 Hz, 180000 samples
print st9
3 Trace(s) in Stream:
.AN6..S Z | 2010-03-02T09:57:03.172000Z - 2010-03-02T10:57:03.152000Z | 50.0 Hz, 180000 samples
.AN6..S N | 2010-03-02T09:57:03.172000Z - 2010-03-02T10:57:03.152000Z | 50.0 Hz, 180000 samples
.AN6..S E | 2010-03-02T09:57:03.172000Z - 2010-03-02T10:57:03.152000Z | 50.0 Hz, 180000 samples
print st10
3 Trace(s) in Stream:
.AN6..S Z | 2010-03-02T10:57:03.175000Z - 2010-03-02T11:57:03.155000Z | 50.0 Hz, 180000 samples
.AN6..S N | 2010-03-02T10:57:03.175000Z - 2010-03-02T11:57:03.155000Z | 50.0 Hz, 180000 samples
.AN6..S E | 2010-03-02T10:57:03.175000Z - 2010-03-02T11:57:03.155000Z | 50.0 Hz, 180000 samples

- I am trying to unit this data in a single file and transform it into SAC format with this code:
	
        ...
        for file in glob.glob('*AN6*'):  
            ST = read(file)
            sta2='HUAD'
            ST[0].stats.station=sta2	
            ST[0].stats.channel='SHZ'
            st += ST[0]
        print('Ordenando...')
        st.sort(['starttime'])
        st.merge(method=1)
        st = st.slice(ti,tf)        
        for i in range(len(st)):
            day_of_year = ti.timetuple().tm_yday
            header='2010.'+'{:03d}'.format(day_of_year)+'.00_00_00' 
            if ma.isarray(st[i].data):
                st[i].data.fill_value = 0
                st[i].stats.processing= str(sum(st[i].data.mask))
                st[i].data=st[i].data.filled()
            print('Guardando...')
            file2=header+'.'+st[i].stats.station+'.'+st[i].stats.channel
            st[i].write(sav+"/"+file2+'.SAC', format="SAC")

- But, when I try to run the program, it sends me this error:

/usr/lib/python2.7/dist-packages/obspy/core/stream.py:2838: UserWarning: Incompatible traces (sampling_rate, dtype, ...) with same id detected. Doing nothing.
  warnings.warn(msg)
Traceback (most recent call last):
  File "mseed2sac_v2.py", line 67, in <module>
    st.merge(method=1)
  File "/usr/lib/python2.7/dist-packages/obspy/core/stream.py", line 1918, in merge
    self._merge_checks()
  File "/usr/lib/python2.7/dist-packages/obspy/core/stream.py", line 1856, in _merge_checks
    raise Exception(msg)
Exception: Can't merge traces with same ids but differing sampling rates!

. If I use the data st0 to st6, the program runs without problem, but if I add st7 the program does not work.

PLEASE HELP!!

**Comment by megies** [comment]
What does the following say?

```python
for tr in st7:
    print tr.stats.sampling_rate
    print tr.stats.sampling_rate == 50
```

**Comment by Danielita88** [comment]
Oh! There is the problem

for tr in st6:
...     print tr.stats.sampling_rate
... 
50.0
50.0
50.0
for tr in st7:
...     print tr.stats.sampling_rate
... 
49.9986
49.9986
49.9986
for tr in st8:
...     print tr.stats.sampling_rate
... 
50.0
50.0
50.0

Do you know how I fix it?

**Comment by megies** [comment]
Well.. the solution depends on where the problem comes from..

If the mismatched sampling rate is fake, i.e. its a metadata problem only, you can just reset the sampling rate to 50 Hz:

```python
for tr in st7:
    print tr.stats.sampling_rate == 50
```

But if the sampling rate really is different.. you should rather resample your data to 50 Hz, take a look at:

http://docs.obspy.org/master/packages/autogen/obspy.core.trace.Trace.resample.html?highlight=resample#obspy.core.trace.Trace.resample

**Comment by d-chambers** [comment]
@megies can this be closed or is it a good idea to add something to deal with floating point sampling rates that are "very close" ?

**Comment by megies** [comment]
> is it a good idea to add something to deal with floating point sampling rates that are "very close" ?

I think this is really an edge case, to me it seems like either a digitizer or file format problem and I don't see how any much-used digitizer would want to output data files sampled at `49.9986` Hz.

As long as not more people have problems like that I would ignore it as an extreme edge case that should be dealt with in user code.

**Comment by Linvill** [comment]
Hi,

I possibly came across a similar issue. We are continuously writing 16bit data into 10 second ASDF (https://asdf-definition.readthedocs.io/en/latest/) files . The digitizer card is clocked by a synthesizer output of a GPS card at 200 kHz and therefore should be exact within errors of course.

Now, for testing I wanted to load one trace (location = 25) of five 10 second ASDF-snippets into an Obspy Stream and merge it:

```
from pathlib import Path
import pyasdf
from obspy.core import Stream
import numpy as np

# Path to asdf files
asdf_folder = Path('path/to/asdf/files')
asdf_list = list(sorted(asdf_folder.glob('*.h5')))

file_names = []
npts_all = []
delta = []
stream_1 = Stream()
locations = [25] #np.linspace(1, 32, 32, dtype=int)
for index, file_name in enumerate(asdf_list):

    asdf_1 = pyasdf.ASDFDataSet(file_name, mode='r')
    start_time = asdf_1.waveforms.XB_02.raw_recording[0].stats.starttime
    end_time = asdf_1.waveforms.XB_02.raw_recording[0].stats.endtime
    for location in locations:
        stream_1 += asdf_1.get_waveforms(network='XB', station='02',
                                         location=str(int(location)).zfill(2), channel="001",
                                         starttime=start_time,
                                         endtime=end_time,
                                         tag="raw_recording")
    # print(stream_1[index].stats.sampling_rate)
    # stream_1[index].stats.sampling_rate = 200000
    # stream_1.plot(outfile='single_channel.png')
print(stream_1)

for tr in stream_1:
    tr.stats.sampling_rate = 200000.0

# stream_1.merge(misalignment_threshold=0.5)
stream_2 = stream_1.copy()
stream_2.merge(method=0)
print(stream_2)
stream_1.merge(method=0)
```

- print(stream_1) shows me:

5 Trace(s) in Stream:
XB.02.25.001 | 2021-07-07T09:54:58.629657Z - 2021-07-07T09:55:08.629652Z | 200000.0 Hz, 2000000 samples
XB.02.25.001 | 2021-07-07T09:55:08.629657Z - 2021-07-07T09:55:18.629652Z | 200000.0 Hz, 2000000 samples
XB.02.25.001 | 2021-07-07T09:55:18.629657Z - 2021-07-07T09:55:28.629652Z | 200000.0 Hz, 2000000 samples
XB.02.25.001 | 2021-07-07T09:55:28.629657Z - 2021-07-07T09:55:38.629652Z | 200000.0 Hz, 2000000 samples
XB.02.25.001 | 2021-07-07T09:55:38.629657Z - 2021-07-07T09:55:48.629652Z | 200000.0 Hz, 2000000 samples

- Trying to merge stream_1 including messing around with sampling rates results in the following error:
  Traceback (most recent call last):
    File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\pydevd.py", line 1448, in _exec
      pydev_imports.execfile(file, globals, locals)  # execute the script
    File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
      exec(compile(contents+"\n", file, 'exec'), glob, loc)
    File "E:/Linus_1/22_GMuG_DAQ/01/DUGseis-acquisition/dug_seis/acquisition/scripts/x_plot_saw_teeth_of_consecutive_asdfs.py", line 37, in <module>
      stream_1.merge(method=0)
    File "C:\ProgramData\Anaconda3\envs\DUGSeis\lib\site-packages\obspy\core\stream.py", line 1994, in merge
      self._cleanup(**kwargs)
    File "C:\ProgramData\Anaconda3\envs\DUGSeis\lib\site-packages\obspy\core\stream.py", line 3053, in _cleanup
      cur_trace += trace
    File "C:\ProgramData\Anaconda3\envs\DUGSeis\lib\site-packages\obspy\core\trace.py", line 731, in __add__
      raise TypeError("Sampling rate differs: %s vs %s" %
  TypeError: Sampling rate differs: 199999.99999999997 vs 200000.0

- Surprisingly, stream_2 (copy of stream_1) I was able merge:
1 Trace(s) in Stream:
XB.02.25.001 | 2021-07-07T09:54:58.629657Z - 2021-07-07T09:55:48.629652Z | 200000.0 Hz, 10000000 samples

I do not really understand why this is happening as timestamps and sampling rates of the traces look fine? Would appreciate any suggestion you might have! In case you'd like to try with data, you will find the asdf files here: https://polybox.ethz.ch/index.php/s/ZPqtGW26SHwNMD8

Thanks,
Linus
