### ISSUE TITLE
Fatal Python Crash on Windows using evalresp

### ISSUE THREAD

**Issue by krischer** [obspy/obspy#1851]
This test crashes Python on windows:

https://github.com/obspy/obspy/blob/e9ba7721b1a23d5386533ac968efbb24056cfb63/obspy/io/xseed/tests/test_core.py#L854-L874

I neither have ready access to a windows machine with a dev environment nor do I know enough about windows to debug this. Can someone look into this? It is probably something deep into evalresp...

**Comment by barsch** [comment]
sometimes it works sometimes not - really hard to reproduce - however when it fails it crashes at line 563 in evresp.c (https://github.com/obspy/obspy/blob/e9ba7721b1a23d5386533ac968efbb24056cfb63/obspy/signal/src/evalresp/evresp.c#L563) - any ideas?

**Comment by krischer** [comment]
Can you somehow compile with debug symbols turned on? It should tell you which value it cannot free. Or maybe add print statements in the `free_channel()` function to see where exactly it crashes?

I also guess it crashes when evalresp directly reads the RESP file and not when ObsPy parses it and feeds it to evalresp. It might be hard to reproduce due to the long jump evalresp uses? But this are all just guesses to be honest.

**Comment by barsch** [comment]
args it late - ofc free_channel is a function too - anyway final crash point is:

https://github.com/obspy/obspy/blob/e9ba7721b1a23d5386533ac968efbb24056cfb63/obspy/signal/src/evalresp/alloc_fctns.c#L603

crashes with multiple python versions at the same point

**Comment by barsch** [comment]
btw when it runs trough the following warning pops up:
```
d:\workspace\obspy\obspy\io\xseed\parser.py:1374: UserWarning: Epoch TW.TATO..BHE [1994-10-01T00:00:00.000000Z - 2599-12-31T23:59:59.000000Z]: Response stage 7 does not end with blockette 58. Proceed at your own risk.
  warnings.warn(_epoch_warn_msg(msg))
```

**Comment by krischer** [comment]
Yea - our resp -> inventory converter raises that warning. On Linux/OSX evalresp still manages to calculate some response. I'll prod around a bit tomorrow and see what is in the struct on my computer.

Can you print the contents of the blkt struct? But this is a recursive structure so it might be a couple of levels down...

**Comment by barsch** [comment]
![untitled](https://user-images.githubusercontent.com/602450/29195210-906c6860-7e2d-11e7-9e9f-7616ef52815a.png)

this_blkt->type 10 goes into case GAIN which again crashes

https://github.com/obspy/obspy/blob/e9ba7721b1a23d5386533ac968efbb24056cfb63/obspy/signal/src/evalresp/alloc_fctns.c#L661-L663

**Comment by QuLogic** [comment]
There are several invalid reads in that test according to valgrind: https://gist.github.com/QuLogic/9ee4fc7f9d8470f510faa4109ceeec24. We really need to see about upgrading to latest evalresp.

**Comment by QuLogic** [comment]
Looking at `free_channel` as pointed to by the valgrind log, there's a gain blockette pointer that seems to be used for multiples stages:
```gdb
(gdb) define print_stage
Type commands for definition of "print_stage".
End with a line saying just "end".
>p $arg0
>p $arg0.sequence_no
>p $arg0.input_units
>p $arg0.output_units
>p "Blockettes:"
>set $blkt = $arg0.first_blkt
>while $blkt
 >p $blkt
 >p $blkt.type
 >set $blkt = $blkt.next_blkt
 >end
>end

(gdb) print_stage chan_ptr->first_stage.next_stage.next_stage.next_stage.next_stage.next_stage
$162 = (struct stage *) 0x148fce0
$163 = 6
$164 = 4
$165 = 4
$166 = "Blockettes:"
$167 = (struct blkt *) 0x13faac0
$168 = 5
$169 = (struct blkt *) 0x16b1e00
$170 = 9
$171 = (struct blkt *) 0x15456e0
$172 = 10

(gdb) print_stage chan_ptr->first_stage.next_stage.next_stage.next_stage.next_stage.next_stage.next_stage
$173 = (struct stage *) 0x1611970
$174 = 7
$175 = 4
$176 = 4
$177 = "Blockettes:"
$178 = (struct blkt *) 0x140a910
$179 = 5
$180 = (struct blkt *) 0x1436350
$181 = 9
$182 = (struct blkt *) 0x15456e0
$183 = 10
```
So stages 6 and 7 share the same gain blockette struct (no other pointers are shared in this pipeline). I didn't really dive into the source to see why this might be happening.

**Comment by QuLogic** [comment]
There isn't even a gain blockette in stage 7...

**Comment by megies** [comment]
This seems really exotic.. so I'm tempted to bump it to 1.2.1. Any objections @krischer?
