### ISSUE TITLE
obspy reading ah-format data files

### ISSUE THREAD

**Issue by haydarkaraoglu** [obspy/obspy#1861]
For reading ah files I had to change 

obspy.io.ah.core._read_ah1  as follows:

before:

ah_stats.event.comment = _unpack_string(data)

after:

        try:
            ah_stats.event.comment = _unpack_string(data)
        except:
            ah_stats.event.comment = None

You may want to change this for the new versions

**Comment by barsch** [comment]
what is the content of data - why is it failing? Instead of just ignoring errors with an general exception it would be better to figure out why its failing and fix it properly - why don't you attach the failing file so we can have a look?

**Comment by barsch** [comment]
closing - please reopen if you can contribute more to this error - otherwise we have no chance to properly handle it ...
