### ISSUE TITLE
plot waveforms over multiple days does accurately plot data

### ISSUE THREAD

**Issue by SCEDC** [obspy/obspy#1863]
Obspy version: 1.0.3, OSX, python 2.7.11

I had two time windows: July 24-27 and July 27-30.  These can be accessed at http://service.scedc.caltech.edu/ftp/outgoing/*ms

When I plot the data in obspy for both streams - I see differences in the data for the time period July 27.  When I write streams to file however, the data points are the same.

![screen shot 2017-08-25 at 2 38 24 pm](https://user-images.githubusercontent.com/1987779/29797574-b88a1d82-8c0c-11e7-9f9a-407cdb3031c0.png)

**Comment by SCEDC** [comment]
Here is another plot - that might show the differences better.  I had zoomed in after running;
ch = read('0724/CIRCT__HNZ___2017205_000000.ms')
ch += read('0724/CIRCT__HNZ___2017208_000000.ms')
ch.plot(automerge=False)
![screen shot 2017-08-28 at 4 50 10 pm](https://user-images.githubusercontent.com/1987779/29798416-ac8b73a0-8c11-11e7-969c-449f502c1896.png)

**Comment by megies** [comment]
I'm assuming this is an artifact of the min-max-windowing, note that the min-max windows don't start at the same points in time for both plots, so there likely is a wiggle that in the upper case is fully contained in one min-max window and in the lower case is spanning across the border of two min-max windows.

In any case, zooming into min-max plots or interpreting single wiggles in min-max plot doesn't really make sense to me, so I'd tend to consider this a non-issue? Any min-max plot should not be zoomed in so much (and the window size should not be increased so much) that the zigzag of the min-max becomes visible..

**Comment by megies** [comment]
stale, closing.
