### ISSUE TITLE
Mass downloader - progress indicator

### ISSUE THREAD

**Issue by shicks-seismo** [obspy/obspy#1865]
Possible enhancement to the Mass Downloader function: it would be great during download to see some sort of progress indicator in the terminal - e.g. how many files / stations / channels are remaining to download. Something like that given by `rysnc --info=progress2` would be very useful. Not sure if this is possible though using fdsn webservices.

**Comment by barsch** [comment]
hmm I don't think it would "fit" into ObsPy - we should try to stay low on UI stuff such as plots etc. - we should focus on more low-level stuff

also AFAIK there is no way to get the current/total download sizes from the web service - so it the progress could only be calculated using the client - another point that such progressbar should be platform independend - building such thing is no easy task so we would have to introduce another dependency

so I'm going to close for now - if you still think that's a must to have feel free to reopen

**Comment by megies** [comment]
Well, there's `progressbar` or `tqdm`, but I totally agree that as a library we don't want too much interactive stdout stuff.
