### ISSUE TITLE
ASCII SLIST uses only float32 

### ISSUE THREAD

**Issue by heavelock** [obspy/obspy#1869]
Is there any particular reason why in the obspy.io.ascii module there is assumed that any float written or read by it has to be float32? 

I'm currently working on a script that involves saving signal with response removed to an ASCII file and unfortunately the accuracy that is used by default in ObsPy is not high enough for me. 

BTW: Comparing sample to sample with same signal but saved and read to SAC gives me a 10883 errors from numpy.testing.assertion_almost_equal for a signal 12221 samples long.

**Comment by barsch** [comment]
nope - IRIS does not define in the SLIST/TSPAIR documentation (http://ds.iris.edu/ds/nodes/dmc/data/formats/simple-ascii/) but looking at the current implementation of ```mseedtoascii.c``` (https://github.com/iris-edu/mseed2ascii/blob/f117564953ae6c1e0330483d3f176b334f841608/src/mseed2ascii.c) it seems that doubles are also supported

feel free to add a PR fixing this issue

**Comment by heavelock** [comment]
Thanks for the green light. I will try to add possibility to manually define format of written floats in following days.

**Comment by megies** [comment]
Also, looks like scientific notation is OK, so the larger impact might actually be to switch to writing as `%g` (or with some custom accuracy if you will).

https://github.com/iris-edu/mseed2ascii/blob/f117564953ae6c1e0330483d3f176b334f841608/src/mseed2ascii.c#L312-L324
