### ISSUE TITLE
Fix Travis Py3.5 32bit build?

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1879]
It's currently broken and annoying for new PRs that will always get a red X for Travis.

See e.g. #1876 and e.g. https://travis-ci.org/obspy/obspy/builds/272860603?utm_source=github_status&utm_medium=notification

**Comment by barsch** [comment]
while you are on - please also remove py 3.3 - see #1712

**Comment by megies** [comment]
Not working on this right now.. just put this as a reminder, as it will likely get annoying soon for new PRs..

**Comment by megies** [comment]
Deactivated that build for now, see f4c8f5dcffc02fec5ba0c8eae4ba31c30080486b

**Comment by megies** [comment]
what's python 3.5?
