### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by elmerehbi** [obspy/obspy#1884]
I created a new environment and installed Obspy but importing returns a "No module named Obspy".

Here's what I did:

`conda config --add channels conda-forge`
`conda create --name obspy python=3.5 obspy`
`source activate obspy`
`ipython`
`import obspy`

**Comment by QuLogic** [comment]
It doesn't look like you installed ipython into the conda environment; try doing that also. I think newer versions should detect this mismatch and figure out proper paths, but I'm not certain when/if that happened.

**Comment by jkmacc-LANL** [comment]
I'm not sure if this is intended, but anaconda seems to fall back to looking in the root installation when it can't find packages.  This leads to all sorts of confusing behavior.

-Jon

________________________________

**Comment by elmerehbi** [comment]
@QuLogic 
AS far as I understand Jupyter's Ipython notebook runs on the Ipython kernel. I am not sure if ipython is different but I did install and it updated it to `6.1.0-py35_0` from conda-forge.
The problem persists.

@jkmacc-LANL 
> anaconda seems to fall back to looking in the root installation when it can't find packages
I do not think this is true unless I misunderstood you:

In ipython:
`!which python`
`/home/user/anaconda3/envs/obspy/bin/python`

**Comment by QuLogic** [comment]
But did you install ipython in the `obspy` environment?

**Comment by megies** [comment]
> It doesn't look like you installed ipython into the conda environment

@elmerehbi 

```
$ conda list
```

..to get a list of installed packages and check for obspy

---

> I'm not sure if this is intended, but anaconda seems to fall back to looking in the root installation when it can't find packages. This leads to all sorts of confusing behavior.

@jkmacc-LANL This is most definitly **not intended behavior** and conda really shouldn't do that, unless you explicitly request it by e.g. putting something in your `PYTHONPATH`. If you can reproduce behavior like this you should definitly report it to the Anaconda guys as a bug.

One similar thing I frequently see people running into, though, is that a separate environment is created and activated, but e.g. IPython or Jupyter is not installed in that separate environment as well. Doing `$ ipython` (or `$ jupyter notebook`) then often falls back to the `root` environment's `bin` directory (which often gets added to `PATH` during initial Anaconda installation) and in consequence people end up with an IPython (or Jupyter notebook) session that they think is running in the activated environment, while in fact it's a `root` environment session.

That's one of the main reasons why I recommend to **not use the root environment for anything at all** besides managing other environments with `conda` and **not install any other packages in the root env**.

The other reason being that getting the root env broken by updates (i.e. no `conda` commands working anymore -- has happened to me before) can be really annoying and hard to fix especially for less experienced users, because then you really have to fix the installation the hard way, manually in the file system.

**Comment by elmerehbi** [comment]
@megies 
Yes I did the install in the obspy env.

And obspy is listed in conda list`

> why I recommend to not use the root environment for anything at all 

That's what I am doing after having gone into trouble months ago. And I do not have any conda problems. I usually update conda in the root environment and update all packages in the activated environment.

**Comment by elmerehbi** [comment]
PS: I use zsh which by default activates a py3 env. I don't thing this has anything to do with the problem as I am manually activating the obspy environment.

**Comment by elmerehbi** [comment]
Solved.

Ok so I updated conda and then updated all modules in the obspy env and now it works. It downgraded obspy to 1.0.2

Here's the details of the update:
```
The following NEW packages will be INSTALLED:

    blas:             1.1-openblas       conda-forge
    chrpath:          0.16-0             conda-forge
    dbus:             1.10.22-0          conda-forge
    expat:            2.2.1-0            conda-forge
    gmp:              6.1.2-0            conda-forge
    gst-plugins-base: 1.8.0-0            conda-forge
    gstreamer:        1.8.0-2            conda-forge
    libuuid:          1.0.3-1            conda-forge
    libxcb:           1.12-1             conda-forge
    openblas:         0.2.19-2           conda-forge
    ruby:             2.4.1-0            conda-forge
    xorg-kbproto:     1.0.7-1            conda-forge
    xorg-libice:      1.0.9-2            conda-forge
    xorg-libsm:       1.2.2-2            conda-forge
    xorg-libx11:      1.6.4-6            conda-forge
    xorg-libxau:      1.0.8-3            conda-forge
    xorg-libxdmcp:    1.1.2-3            conda-forge
    xorg-libxext:     1.3.3-2            conda-forge
    xorg-libxrender:  0.9.10-0           conda-forge
    xorg-libxt:       1.1.5-0            conda-forge
    xorg-renderproto: 0.11.1-1           conda-forge
    xorg-xextproto:   7.3.0-1            conda-forge
    xorg-xproto:      7.0.31-6           conda-forge
    yaml:             0.1.6-0            conda-forge

The following packages will be UPDATED:

    libpng:           1.6.28-0           conda-forge --> 1.6.28-1                      conda-forge
    matplotlib:       1.5.3-np113py35_8  conda-forge --> 2.0.2-py35_2                  conda-forge
    numpy:            1.13.1-py35_0                  --> 1.13.1-py35_blas_openblas_200 conda-forge [blas_openblas]
    pyqt:             4.11.4-py35_2      conda-forge --> 5.6.0-py35_4                  conda-forge
    qt:               4.8.7-7            conda-forge --> 5.6.2-5                       conda-forge
    scipy:            0.19.1-np113py35_0             --> 0.19.1-py35_blas_openblas_202 conda-forge [blas_openblas]

The following packages will be DOWNGRADED:

    obspy:            1.0.3-py35_1       conda-forge --> 1.0.2-py35_1                  conda-forge
    zlib:             1.2.11-0           conda-forge --> 1.2.8-3                       conda-forge
```

**Comment by megies** [comment]
I think the issue might have been that obspy 1.0.3 is not matplotlib 2 compatible. In the 1.0.2 package we might not have specified this incompatibility, that's why it's downgrading..

**Comment by megies** [comment]
Maybe you installed it in a different env? `conda info -e` to list your envs and `conda list -n <envname>` to list packages in a specific env.

**Comment by HanBao3** [comment]
> Maybe you installed it in a different env? `conda info -e` to list your envs and `conda list -n <envname>` to list packages in a specific env.
Thanks Megies. Yeah I got it, and also have it work in the Jupyter Notebook.
Many thanks.
-Han

**Comment by HanBao3** [comment]
Thanks Megies. Yeah I got it, and also have it work in the Jupyter Notebook.
Many thanks.
-Han

> Maybe you installed it in a different env? `conda info -e` to list your envs and `conda list -n <envname>` to list packages in a specific env.

Thanks Megies. Yeah I got it, and also have it work in the Jupyter Notebook.
Many thanks.
-Han

**Comment by HanBao3** [comment]
> Maybe you installed it in a different env? `conda info -e` to list your envs and `conda list -n <envname>` to list packages in a specific env.

Thanks Megies. Yeah I got it, and also have it work in the Jupyter Notebook.
Many thanks.
-Han

**Comment by muratbeyhan** [comment]
I'm new programmer on python
I have installed anaconda jubyter notenook i python obspy etc.
I would like to test and try to learn how we can run python scripts. Then I try to following excersise and got following error. 
actualyy even when I use Pycharm I got similar error message about could not find module obspy. sorry for disturbing you but I'm at the beginning of Python programming .
I used anaconda prpmpt and I activated using  "conda activate obspy"
then when  I tried to import obspy following error occured.

conda activate obspy
(obspy) c:\seed>python
>>>import obspy
Traceback (most Recent call last):
 File "(stdin)", line 1 in (module)
importError: no module named obspy
>>>
also when I installed Anaconda I was installed python 3.7
but when I use anaconda promt it says python 2.7.15 installed and using

I hope you can help me 
regards
Murat

**Comment by megies** [comment]
Please ask for help in the gitter chat with usage problems like these. @muratbeyhan 

You can check what packages are installed in your env with `conda list`
