### ISSUE TITLE
ModuleNotFoundError: No module named 'obspy.core' but runtests shows OK sometimes and not stable.

### ISSUE THREAD

**Issue by sphinx07** [obspy/obspy#1886]
Hi,

I tried to install Obspy through Anaconda and ran tests through obspy-runtests. It says OK after '$ obspy-runtests'. But when I tried to type in "import obspy.core", it returned the following message:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-08fb4410fadf> in <module>()
----> 1 import obspy.core

ModuleNotFoundError: No module named 'obspy.core'

I thought I might screw up the installation since I tried homebrew, macport and finally Anaconda but I am not sure what the actual problem is.

I am using macOS Sierra, version 10.12.6, Python 3.6.1 and Obspy 1.0.3. 

I wonder if anyone can help me figure out how I can get it work? That will be really helpful!!!

Thanks a lot!

Claire

**Comment by sphinx07** [comment]
Just a follow up. I ran the tests again ($ obspy-runtests) and it reported a lot of failures this time. However, I didn't do anything and looks like it is not stable.

**Comment by sphinx07** [comment]
Solved! It seems like I confused my laptap with mac port.

**Comment by megies** [comment]
We can really recommend Anaconda for fully self-contained Python environments. But anyways, glad you could figure it out.

**Comment by sphinx07** [comment]
@megies Thanks a lot for your reply! Indeed, Anaconda is the one that finally worked.
