### ISSUE TITLE
Invalid version schema "0.0.0.dev+.gXXX" - may not work with newer versions of setuptools, pip, and PyPI

### ISSUE THREAD

**Issue by barsch** [obspy/obspy#1889]
```C:\Miniconda-x64\envs\test\lib\site-packages\setuptools\dist.py:350: UserWarning: The version specified (u'0.0.0.dev+.g5c641b2cb1') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.```

see also https://ci.appveyor.com/project/obspy/obspy/build/1.0.5140-warnings/job/rxhusf826vk5atia

**Comment by megies** [comment]
I don't know where this version number is coming from.. likely a downloaded dev tarball from github, in any case this should fix it I think:

```diff
--- a/obspy/core/util/version.py
+++ b/obspy/core/util/version.py
@@ -107,7 +107,7 @@ def call_git_describe(abbrev=10, dirty=True,
     # (this line prevents official releases)
     # should work again now, see #482 and obspy/obspy@b437f31
     if "-" not in line and "." not in line:
-        version = "0.0.0.dev+.g%s" % line
+        version = "0.0.0.dev+0.g%s" % line
     else:
         parts = line.split('-', 1)
         version = parts[0]
```

**Comment by barsch** [comment]
> I don't know where this version number is coming from.. likely a downloaded dev tarball from github, in any case this should fix it I think:

it was an automated CI build after commit https://github.com/obspy/obspy/commit/5c641b2cb11b1b6882eed27c01d40747828cc373 within https://github.com/obspy/obspy/pull/1888
