### ISSUE TITLE
Failure to read underline "_" character from dataless file

### ISSUE THREAD

**Issue by paitor** [obspy/obspy#1893]
In the attached dataless file ([UP_BACU_HH.dataless.zip](https://github.com/obspy/obspy/files/1303020/UP_BACU_HH.dataless.zip)) the site_name field in blockette 50 holds the string "T3930_b A6689 3930" as can be verified by opening the file using [pdcc](http://ds.iris.edu/ds/nodes/dmc/software/downloads/pdcc/), however running 

    from obspy.io.xseed import Parser
    print Parser("UP_BACU_HH.dataless").blockettes[50][0].site_name

outputs "T3930 b A6689 3930". 

Note that also writing strings with the underline character to a dataless file also fails (sorry, no simple code-snippet available here). 

(running obspy 1.0.3 on open suse installed via pip a few months ago)

**Comment by megies** [comment]
Can confirm the bug also exists in `master`.
