### ISSUE TITLE
get_datalogger_resp() and get_sensor_resp()

### ISSUE THREAD

**Issue by jdassink** [obspy/obspy#1897]
I appreciate the new NRL class in the Obspy master.. great job!

It would be valuable to be able to pull separate sensor and datalogger response stages into a Obspy Response object, as get_response() does.

In some of my use cases, my sensor is home-made not part of the NRL library while the datalogger is. After this, I could append the stages using response.response_stages.append()

**Comment by krischer** [comment]
@dsentinel, @nick-iris Would it be fine for you to change `get_datalogger_resp()` and `get_sensor_resp()` to return and ObsPy `Response` object? Both are only use once in the code base and they are converted to `Response` objects immediately.
