### ISSUE TITLE
Matplotlib deprecation warning

### ISSUE THREAD

**Issue by Khalilsqu** [obspy/obspy#1901]
Before submitting an Issue, please review the [Issue Guidelines](https://github.com/obspy/obspy/blob/master/CONTRIBUTING.md#submitting-an-issue).

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform: windows, 3.6, obspy 1.0.3
  -  How did you install ObsPy and Python (wheel file)
  -  If possible please supply a short, self contained, correct example that
     demonstrates the issue.
  
C:\Anaconda3\lib\site-packages\matplotlib\cbook.py:136: MatplotlibDeprecationWarning: The axisbg attribute was deprecated in version 2.0. Use facecolor instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)

**Comment by QuLogic** [comment]
This is fixed in `master` by #1792 already.
