### ISSUE TITLE
obspy.signal.util.next_pow_2

### ISSUE THREAD

**Issue by Khalilsqu** [obspy/obspy#1905]
I am just wondering does the function obspy.signal.util.next_pow_2 is same as matlab function nextpow2?

matlab
nextpow2(18000) = 15

obspy
obspy.signal.util.next_pow_2(18000)= 32768 = 2**15

**Comment by krischer** [comment]
Yep. Only that matlab returns the exponent whereas ObsPy return the actual number.

**Comment by ogalanis** [comment]
Technically, the matlab function returns the exponent of the next  
power of 2 and the obspy function returns the actual next power of 2.  
So,

(obspy next power of two) = 2 ^ (matlab next power of two)
or
(matlab next power of two) = log2 (obspy next power of two)




Παραθέτοντας από Khalil Al Hooti <notifications@github.com>:

**Comment by ThomasLecocq** [comment]
just to say, with the new `scipy.fftpack` since 0.18, `next_fast_len` is a product of 1s, 3s and 5s, faster and more stable than powers of 2...
