### ISSUE TITLE
[feature] Perform FTAN

### ISSUE THREAD

**Issue by vvug** [obspy/obspy#1907]
It would be great to perform the frequency-time analysis (FTAN) from within ObsPy. Is there any plan to implement this feature?

**Comment by krischer** [comment]
ObsPy can calculate misfits in the time-frequency domain: https://docs.obspy.org/tutorial/code_snippets/time_frequency_misfit.html

**Comment by vvug** [comment]
Thanks @krischer, that's indeed useful, but I'm more interested in plotting the dispersion curve of a signal and measuring travel times on several frequency (period) intervals...

**Comment by krischer** [comment]
Okay - that would have to be tacked onto that - we have nothing built-in in ObsPy to do that. But you can use the wavelet transform used in the misfits to construct a TF representation or use the same things that `st.spectrogram()` is using.

If I remember correctly @ThomasLecocq had something to automatically pick something in dispersion curves.

**Comment by ThomasLecocq** [comment]
yep, in https://github.com/ThomasLecocq/msnoise-tomo we have an FTAN code that works OK, but the code is not ready for production yet (have to find some time). And yes, the FTAN should at some point be moved down in obspy :)

**Comment by vvug** [comment]
Thanks @ThomasLecocq, I'm looking forward to see your code integrated in ObsPy!

**Comment by megies** [comment]
stale, closing.
