### ISSUE TITLE
Bug in rotate2zne with non-orthogonal components

### ISSUE THREAD

**Issue by fbernauer** [obspy/obspy#1913]
obspy version: 1.0.3
installed with anaconda
According to the documentation, rotate2zne works explicitly also for non orthogonal systems. Looking into the source code, I realized, that for the basis transformation from an arbitrary system (u v w) to (z n e), the **transposed** basis vector matrix is taken. In my opinion, the **inverse** matrix must be taken.
For the transformation from one orthogonal system to another orthogonal system, the transposed matrix is equal to the inverse matrix. But in general, for non orthogonal systems, this is not the case. 
I will run some test on this issue and let you know about the results, soon.

**Comment by QuLogic** [comment]
I think some of this was discussed in #1061.

**Comment by megies** [comment]
I think there just was some confusion about the *transpose* being used.. but that's probably just owed to how the base vectors are set up.
The *matrix-inverse* is in the code alright, when using `inverse=True`. So, I think there actually is no bug and this can be closed (although we currently only have a round-trip test for non-orthogonal input and the intermediate result should be tested as well).

**Comment by megies** [comment]
Ok, so we *do* have a bug in reconstruction of ZNE components from a set of three non-orthogonal components. We have a sane real data test from two seismometers on a step table now, and we also have a working fix that has our old tests passing. I'll prepare a PR with the fix now.

Thanks to @jwassermann and @fbernauer for the code fix and many thanks for recording the test data to @fbernauer!

**Comment by megies** [comment]
So, here's what we currently have for asserting correctness of reconstructing orthogonal components from three arbitrary ones. This is using the patch from @jwassermann that I'll push in a bit.. we're fairly confident now, that this works correctly now. The only shortcoming of below test is probably that we reconstruct UVW and those three components basically have the same signal (due to the step table operating vertically). Maybe we should pimp the testing by comparing..
 - simple rotation from UVW to a slightly rotated orthogonal system
 - reconstruction into that same system from a set of three somponents taken from U/V/W/X/Y/Z

```python
import matplotlib.pyplot as plt
from obspy import read, UTCDateTime
from obspy.signal.rotate import rotate2zne


st = read('http://examples.obspy.org/step_table_galperin_and_xyz.mseed')
# remove step table signal trace, it has 'HXZ' channel code and gets in the way
# when selecting the second seismometer's Z trace
st = st.select(station='TRC*')
print(st)

t1 = UTCDateTime('2017-10-11T12:33:15')
t2 = UTCDateTime('2017-10-11T12:33:40')

st.filter('bandpass', freqmin=0.05, freqmax=10)
st.detrend('constant')
st.trim(t1, t2)

t = st[0].times()

az_u = 90.0
dip_u = -(90.0 - 54.7)
az_v = 330.0
dip_v = -(90.0 - 54.7)
az_w = 210.0
dip_w = -(90.0 - 54.7)
az_x = 65.0
dip_x = 0.0
az_y = 335.0
dip_y = 0.0
az_z = 0.0
dip_z = -90.0

azimuth = {
    'U': az_u,
    'V': az_v,
    'W': az_w,
    'X': az_x,
    'Y': az_y,
    'Z': az_z,
    }

dip = {
    'U': dip_u,
    'V': dip_v,
    'W': dip_w,
    'X': dip_x,
    'Y': dip_y,
    'Z': dip_z,
    }


def zne_from(components='UVW'):
    traces = [st.select(component=c)[0] for c in components]
    dips = [dip[c] for c in components]
    az = [azimuth[c] for c in components]
    z, n, e = rotate2zne(traces[0], az[0], dips[0],
                         traces[1], az[1], dips[1],
                         traces[2], az[2], dips[2])
    return z, n, e


def uvw_from(z, n, e):
    traces = [z, n, e]
    dips = [dip_u, dip_v, dip_w]
    az = [az_u, az_v, az_w]
    u, v, w = rotate2zne(traces[0], az[0], dips[0],
                         traces[1], az[1], dips[1],
                         traces[2], az[2], dips[2],
                         inverse=True)
    return u, v, w


fig, axes = plt.subplots(nrows=3)
fig2, axes2 = plt.subplots(nrows=3)

# plot directly recorded UVW in second figure
for ax, comp in zip(axes2, 'UVW'):
    data = st.select(component=comp)[0]
    ax.plot(t, data, alpha=0.6, label='original UVW')

# reconstruct UVW from various component combinations
for components in ['UVW', 'XYZ', 'UYZ', 'XWZ']:
    # first reconstruct ZNE
    z, n, e = zne_from(components)
    for data, ax, label in zip([z, n, e], axes, 'ZNE'):
        ax.plot(t, data, alpha=0.6, label='from ' + components)
        ax.set_ylabel(label)
    # then reconstruct UVW from ZNE with inverse option in rotate2zne
    u, v, w = uvw_from(z, n, e)
    for data, ax2, label in zip([u, v, w], axes2, 'UVW'):
        # for the second figure we already plotted the original UVW recorded
        # data
        if components == 'UVW':
            continue
        ax2.plot(t, data, alpha=0.6, label='from ' + components)
        ax2.set_ylabel(label)

for ax in (axes[-1], axes2[-1]):
    ax.set_xlabel("time")
    ax.legend(loc='lower center')
for fig_ in (fig, fig2):
    fig_.tight_layout()
plt.show()
```

![figure_1](https://user-images.githubusercontent.com/1842780/31501394-6eb55de4-af6a-11e7-8f38-821b14b2d383.png)
![figure_2](https://user-images.githubusercontent.com/1842780/31501398-72a98f9c-af6a-11e7-93e1-0dfa74446184.png)

**Comment by megies** [comment]
I also added a foto with the test data recording setup to our examples repo: http://examples.obspy.org/step_table_galperin_and_xyz.jpg

![](http://examples.obspy.org/step_table_galperin_and_xyz.jpg)
