### ISSUE TITLE
Mission "clean test logs" pt.2: Keep it that way

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1914]
As pointed out in #1888, we need to make sure the test runner output stays clean in CI. We should catch stdout and stderr of the `runtests` call in Travis (and optionally Appveyor as well -- Windows likely has quite some different behavior in compiled stuff) and slap a regex check for any unwanted output on it and fail CI if there's any unwanted output. That way we can prevent new PRs cluttering our testrunner output again.

**Comment by trichter** [comment]
With pytest this issue is obsolete, because output is caught by default.
