### ISSUE TITLE
Is it possible to save user generated fields to MINISEED?

### ISSUE THREAD

**Issue by cerinunn** [obspy/obspy#1923]
Hello, 
I'd like to save some extra information to a miniseed file. The attribute dictionary could have any name. 
I can use an attribute dictionary while manipulating the stream within ObsPy, but it doesn't save into the file. Is this possible? 
Many thanks, 
Ceri 

```
    from obspy.core import Trace
    import numpy as np
    from obspy.core import AttribDict
    tr = Trace(np.random.random(100))
    tr.stats.extras = AttribDict()
    tr.stats.extras.a = 10.
    print(tr.stats.extras.a)
    tr.write('dummy.miniseed', format='MSEED')


    st = read('dummy.miniseed')
    tr = st[0]
    print(tr.stats.extras.a)
```

**Comment by barsch** [comment]
nope - miniseed is pretty much fixed and you can't add arbitrary data

**Comment by cerinunn** [comment]
Thought that might be the case. Thanks for the super quick reply!

**Comment by barsch** [comment]
np - questions such as this is also sometimes better asked in the gitter chat https://gitter.im/obspy/obspy

**Comment by megies** [comment]
You'll probably want to save those details in a QuakeML file.. these can hold arbitrary info besides the "standard" event infos, see http://docs.obspy.org/master/tutorial/code_snippets/quakeml_custom_tags.html?highlight=extra
