### ISSUE TITLE
cannot read mseed, sac

### ISSUE THREAD

**Issue by Khalilsqu** [obspy/obspy#1953]
Before submitting an Issue, please review the [Issue Guidelines](https://github.com/obspy/obspy/blob/master/CONTRIBUTING.md#submitting-an-issue).

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version 1.0.3 , Python version 3.5.4 and Platform (Windows 10, 64)
  -  How did you install ObsPy and Python (anaconda)

I am trying to follow one of the workshops you have provided.
2016-06-24_cig

when trying to run this example code

```
import obspy

# ObsPy automatically detects the file format.
st = obspy.read('example.mseed')
print(st)

# Fileformat specific information is stored here.
print(st[0].stats.mseed)
```
I get this error:
TypeError: Unknown format for file example.mseed
the same happens for sac

after trying to specify the format = 'mseed'
`st = obspy.read('example.mseed', format='mseed')
`
a different error is thrown
for mseed
TypeError: Required argument 'month' (pos 2) not found 
for sac
SacIOError: Actual and theoretical file size are inconsistent.
Actual/Theoretical: 43375/7676992364
Check that headers are consistent with time series.

I thought I am getting this error since I initially installed unofficial obspy from this site http://www.lfd.uci.edu/~gohlke/

But I removed my python version 3.6 and installed anaconda for python 3.5 and obspy is then installed from conda.

Yet the same problem arises

I am using windows 10 -64bit

Please answer me before deleting the issue!

**Comment by krischer** [comment]
Hi,

two things:

* Can you try removing the `format=mseed`?
* Can you upload the files somewhere?

Cheers!

Lion

**Comment by krischer** [comment]
ObsPy definitely works for these files (at least the original ones) so it must be something with your installation.

**Comment by Khalilsqu** [comment]
Hi Lion, 

Thank for your message. 

The files are the same ones available in one of your worskshops. 
https://github.com/obspy/docs/tree/master/workshops/2016-06-24_cig/ObsPy/data

Though I can read segy files:
`from obspy.io.segy.core import _read_segy`

However, I get an error when trying the same for mseed or sac
```
from obspy.io.sac.core import _read_sac
stream = _read_sac('example.sac')
```
mseed:
TypeError: Required argument 'month' (pos 2) not found
for sac:
SacIOError: Actual and theoretical file size are inconsistent.
Actual/Theoretical: 43375/7676992364
Check that headers are consistent with time series.


I installed obspy in the root directory. However, I uninstalled obspy today morning and created virtual env for python 3.5 and installed obspy into this env

```
>>conda create -n obspy python=3.5
>>activate obspy
>>conda install -c obspy obspy
>> python
>>> import obspy
>>> stream = obspy.read('example.mseed')
```

I got exactly the same errors as above


Could you please let me know what installation I have to follow to get it all working. I am using wind10-64

Regards

**Comment by krischer** [comment]
Hmm - it works fine on my machine with ObsPy 1.0.3:

```python
In [4]: obspy.read("https://github.com/obspy/docs/blob/master/workshops/2016-06-24_cig/ObsPy/data/example.mseed?raw=true")
Out[4]:
6 Trace(s) in Stream:
IV.BDI..BHE | 2014-04-04T01:33:37.045000Z - 2014-04-04T02:15:10.695000Z | 20.0 Hz, 49874 samples
IV.BDI..BHE | 2014-04-04T02:15:23.535000Z - 2014-04-04T03:08:04.485000Z | 20.0 Hz, 63220 samples
IV.BDI..BHN | 2014-04-04T01:33:43.975000Z - 2014-04-04T02:15:12.125000Z | 20.0 Hz, 49764 samples
IV.BDI..BHN | 2014-04-04T02:15:22.725000Z - 2014-04-04T03:08:10.025000Z | 20.0 Hz, 63347 samples
IV.BDI..BHZ | 2014-04-04T01:33:26.745000Z - 2014-04-04T02:15:11.195000Z | 20.0 Hz, 50090 samples
IV.BDI..BHZ | 2014-04-04T02:15:24.025000Z - 2014-04-04T03:08:16.825000Z | 20.0 Hz, 63457 samples

In [5]: obspy.read("https://github.com/obspy/docs/blob/master/workshops/2016-06-24_cig/ObsPy/data/example.sac?raw=true")
Out[5]:
1 Trace(s) in Stream:
AI.BELA..BHN | 2010-03-11T06:17:18.000000Z - 2010-03-11T08:02:18.000000Z | 20.0 Hz, 126001 samples
```

Three more things I can think of doing:

1. `import obspy; print(obspy.__file__)`: This has to be consistent with your conda environment path.
2. Can you try to install obspy via `conda-forge`: `conda install -c conda-forge obspy`. This should not change anything but the `obspy ` channel is deprecated.
3. Can you run the tests `obspy-runtests` and report the results to us?

**Comment by Khalilsqu** [comment]
![capture](https://user-images.githubusercontent.com/22060413/31878807-2c567c0a-b7d3-11e7-88d1-f8d6f9c81f1a.JPG)


I cannot install obspy using conda install -c conda-forge obspy

**Comment by krischer** [comment]
You forgot the `-c` before the `conda-forge`. Also please uninstall the old ObsPy.

**Comment by Khalilsqu** [comment]
![capture2](https://user-images.githubusercontent.com/22060413/31879031-f557a0c0-b7d3-11e7-8b99-6429dfd65e4b.JPG)

**Comment by krischer** [comment]
Hmm - I really don't know is wrong with your installation. Can you post the full output of `conda list`? You could also try creating a new env with python 3.6 and see if that solves the issue by chance:

```bash
$ conda create -n obspy_py36 python=3.6
$ source activate obspy_py36
$ conda install -c conda-forge obspy
```

Also can one of the windows guys chime in? @barsch @ThomasLecocq

**Comment by Khalilsqu** [comment]
![condalist](https://user-images.githubusercontent.com/22060413/31879784-6e30cfec-b7d6-11e7-8a52-cbd03fdd7fd9.png)

still no luck with py36

![capture2](https://user-images.githubusercontent.com/22060413/31879965-f9601852-b7d6-11e7-95a2-8299af742068.JPG)


Though I can read segy files using 

```
from obspy.io.segy.core import _read_segy
st = _read_segy('segyfile')
```
However I cannot read segy files using the normal read method.

import obspy
st = obspy.read('segyfile', format='segy')

For mseed and sac neither methods works.

Anyway I dont want to take all your time. I think I will just live with the working method of segy reading. I microseismic event files I do have all segy files.
I just wanted to go through your workshop tutorial and learn more about obspy.

Thanks and regards

**Comment by krischer** [comment]
Can you run the tests?

`obspy-runtests`

This should most definitely work and somehow the plug-ins did get registered for you (or the `read()` method cannot find them). You can probably also use the internal mini-SEED and SAC reading routines as you already do for SEG-Y.

**Comment by Khalilsqu** [comment]
Where Should I run obspy-runtests?
In the command window or or python shell

internal reading is not working for mseed and sac.

I tested for python 2.7 but still no luck. I took a while to install py27 environment.
![2 7](https://user-images.githubusercontent.com/22060413/31881653-17779068-b7dc-11e7-821f-6c0edd9096ad.JPG)

**Comment by Khalilsqu** [comment]
Just removed all My anaconda installation and installed this files instead

ObsPy-1.0.3-py35_7-Windows-x86_64.exe
I found it here https://github.com/obspy/obspy/releases/

But still no success

![obspy](https://user-images.githubusercontent.com/22060413/31886161-1492e7e4-b7eb-11e7-8a5c-eedce896a313.JPG)

**Comment by megies** [comment]
> # ObsPy automatically detects the file format.
> st = obspy.read('example.mseed')

I strongly believe this was added after 1.0.3, so it will only be in a released version with 1.1.0, see #1321 and https://github.com/obspy/obspy/blob/d1f10bb9a35c5160b722ca7cd45112ceb0a67ddf/CHANGELOG.txt#L30 noting it after 1.0.3 in the "master" changelog (for 1.1.0).

**Comment by krischer** [comment]
`obspy.read()` always auto-detected the file format. It is new for writing.

**Comment by krischer** [comment]
I think you have multiple ObsPy installations, e.g. `C:\ObsPy\...`, `C:\Anconda3\envs\obspy_py27`, .. and maybe others

I guess there is some cross-talk happening? Please jump on gitter which might make it easier to debug.

**Comment by ThomasLecocq** [comment]
Aaaaaaah, did you install ObsPy Anaconda Distribution ???

**Comment by megies** [comment]
> obspy.read() always auto-detected the file format. It is new for writing.

Aah.. sorry.

**Comment by ThomasLecocq** [comment]
@Khalilsqu how did you download the example.mseed file ? could you open it in notepad.exe and check that it's not a wrong HTML failure page or else? 
if should look like this:
![image](https://user-images.githubusercontent.com/916937/31889250-6ae9312a-b7ff-11e7-80c5-be67e4c79990.png)

**Comment by Khalilsqu** [comment]
holy moly... 

please delete it now the issue. I feel a shame and stupid if someone knows that I was struggling all day trying to read mseed file while the file is corrupted when downloaded from internet.

 @ThomasLecocq thank, you are genius. 

and sorry wasting your time.
![last](https://user-images.githubusercontent.com/22060413/31893541-b683caf6-b803-11e7-9213-72f532e382ac.JPG)

**Comment by krischer** [comment]
Good to hear that it works now :)

**Comment by barsch** [comment]
at least we learned that ObsPy made it to this list: http://www.lfd.uci.edu/%7Egohlke/pythonlibs/  ^^

**Comment by ThomasLecocq** [comment]
@Khalilsqu you have noooo idea how many times I have this issue... when reading a file fails... and then you open it and all you can read is "403 forbidden" :) (or "please login to the hotel captive proxy webpage to continue browsing the web") :-)
