### ISSUE TITLE
Convert RESP file to XML format--Obspy 

### ISSUE THREAD

**Issue by Johumel** [obspy/obspy#1971]
Before submitting an Issue, please review the [Issue Guidelines](https://github.com/obspy/obspy/blob/master/CONTRIBUTING.md#submitting-an-issue).

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a short, self contained, correct example that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.

Hello,
Please, is there a function in Obspy that can convert a response file to XML format?

**Comment by krischer** [comment]
Yes - the next ObsPy version (due someday this week) can read RESP files with `obspy.read_inventory()` which you can then again write out as StationXML.

https://github.com/obspy/obspy/wiki/What's-New-in-ObsPy-1.1

In the future please consider using the [[obspy-user] mailing list](http://lists.swapbytes.de/mailman/listinfo/obspy-users) or our [gitter chat](https://gitter.im/obspy/obspy) for generic questions. Github is mainly for bug fixes and code development/discussions.
