### ISSUE TITLE
obspy build failing as dependency with readthedocs

### ISSUE THREAD

**Issue by JackWalpole** [obspy/obspy#1974]
I'm trying to use obspy to download some data as an example in the docs for splitwavepy http://splitwavepy.readthedocs.io/en/latest/ ... recently the readthedocs build has been failing.  I reported the issue here https://github.com/rtfd/readthedocs.org/issues/3191#issuecomment-339400132 and according to the readthedocs people this is a "packaging problem" possibly related to "trying to import a dependency on setup.py".

Here's my build error:

> Collecting numpy (from -r docs/doc-requirements.txt (line 5))
> Using cached numpy-1.13.3-cp35-cp35m-manylinux1_x86_64.whl
> Collecting matplotlib (from -r docs/doc-requirements.txt (line 6))
> Using cached matplotlib-2.1.0-cp35-cp35m-manylinux1_x86_64.whl
> Collecting scipy (from -r docs/doc-requirements.txt (line 7))
> Downloading scipy-1.0.0-cp35-cp35m-manylinux1_x86_64.whl (49.6MB)
> Collecting nb2plots (from -r docs/doc-requirements.txt (line 8))
> Using cached nb2plots-0.5.2.zip
> Collecting obspy (from -r docs/doc-requirements.txt (line 9))
> Using cached obspy-1.0.3.zip
> Complete output from command python setup.py egg_info:
> Traceback (most recent call last):
> File "/tmp/pip-build-molsc2j4/obspy/setup.py", line 33, in 
> import numpy # @unusedimport # NOQA
> ImportError: No module named 'numpy'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/tmp/pip-build-molsc2j4/obspy/setup.py", line 37, in <module>
>     raise ImportError(msg)
> ImportError: No module named numpy. Please install numpy first, it is needed before installing ObsPy.
> 
> ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-molsc2j4/obspy/

**Comment by megies** [comment]
Can you post a link to your build instructions for readthedocs? If you're compiling ObsPy in there (as opposed to e.g. pulling in conda packages), then numpy has to be installed *before* starting to compile obspy. So maybe you need to do separate install steps, one for numpy then one for obspy.

**Comment by JackWalpole** [comment]
I didn't realise you could use conda with readthedocs, apparently you can.  However, I think I fixed my issue by ticking the "Use system packages" box in the advanced settings.

<img width="555" alt="screen shot 2017-10-26 at 13 59 58 1" src="https://user-images.githubusercontent.com/10852170/32054472-60bfea0a-ba56-11e7-84da-b3c0745c77ec.png">

Cheers

**Comment by krischer** [comment]
There is definitely a way to install numpy on rtd before installing ObsPy. Maybe in the dependency setting or something? We also once tried to get our documentation to work on rtd but never really managed completely.

Long-term we should probably consider getting rid of `numpy.distutils` and just use the normal `distutils`. This works fine on at least linux and osx (I have no experience on windows to be honest).

**Comment by amaggi** [comment]
The `ImportError: No module named numpy. Please install numpy first, it is needed before installing ObsPy.` has raised its ugly head again...

I'm writing some code to transform geomagnetic data into miniseed using obspy. On my setup everything works fine. 

When I tried to get continuous integration to work on gitlab using a shared runner, I ran into this numpy problem, which should probably have been solved by now.

Here is more information: 

**The `.gitlab-ci.yml`file**
````
image: "python:3.7"

before_script:
  - python3 --version
  - pip3 --version
  - pip3 install -r requirements.txt

stages:
  - test

pytest:
  stage: test
  script:
  - python3 -m pytest
````

**The `requirements.txt` file**
````
numpy==1.17.3
pandas==0.24.2
pytest==4.6.7
python-dateutil==2.8.1
pathlib==1.0.1
obspy==1.1.1
`````

And the **output of the failed build on the gitlab runner** : 
Job [#375188586](https://gitlab.com/alessia.maggi/imag_client/-/jobs/375188586)

**Comment by heavelock** [comment]
We had for some time in the Travis' build matrix the same error but on 2.7 with minimum dependencies that was tackled by @megies in #2507. However it looks like he tacked it by bumping the minimum versions of dependencies which anyway are way older then ones that you are using.

I personally can recommend switching your base image to  miniconda and working with conda then. Here is my adapted .gitlab-ci.yml:

```yml
image: continuumio/miniconda3:latest

before_script:
  - apt-get update && apt-get upgrade -yy
  - conda create -c conda-forge -n env-test python=3.7 --file=requirements.txt --

test-stage:
  script:
    - source activate env-test
    - pytest --cov=module-name

```

What's more, pathlib is a part of the standard library since python 3.4 so there is no need to install it.

**Comment by amaggi** [comment]
Thank you @heavelock . Based on your suggestion, I adapted the .gitlab-ci.yml to:

````
image: continuumio/miniconda3:latest

before_script:
  - apt-get update && apt-get upgrade -yy
  - conda create -c conda-forge -n env-test python=3.7 --file requirements.txt

test-stage:
  script:
    - source activate env-test
    - python -m pytest --cov=imag_client
````
and the requirements.txt file to
````
pandas==0.24.2
pytest==5.3.1
pytest-cov==2.8.1
python-dateutil==2.8.1
obspy==1.1.1
````
which resulted in a successful CI run.

**Comment by megies** [comment]
@amaggi, yeah it seemed to be an old numpy version that was the problem in our case. So curious how it went bad with you requesting 1.17.. well, you got it working, so all good I guess. :+1:

**Comment by amaggi** [comment]
@megies The problem only occurs with pip installation, not conda installation. 

I'm not exactly sure why, but the error message did seems to say that setup.py was checking for numpy upon installation.
