### ISSUE TITLE
Any function for retrieving data on a station_based mode?

### ISSUE THREAD

**Issue by sphinx07** [obspy/obspy#1986]
Hi there, 

I wonder if there is any function in obspy that can help me to retrieve data on a station-based mode?

For example, I have the coordinate of station A and I would like to get events within back azimuths of 0~30 degrees of station A, then which function is the best to use? I checked get_events, there are only options limiting the radius instead of back azimuth, besides that, I cannot find any others.

Thanks!

Best,
Claire

**Comment by krischer** [comment]
Hi,

please don't cross post on GitHub and the mailing list. I'll answer there.

Cheers!

Lion
