### ISSUE TITLE
CNV writing phase_mapping fails

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#2001]
This line:
https://github.com/obspy/obspy/blob/master/obspy/io/cnv/core.py#L63

doesn't work because 

``values.update(("P", "S"))`` returns ``None``

This works:
```python
values = set(phase_mapping.values())
values.update(("P","S"))
    if values != set(("P", "S")):

```

**Comment by megies** [comment]
Fixed in maintenance branch
