### ISSUE TITLE
Add support to sc3ml 0.10 schema for stations

### ISSUE THREAD

**Issue by claudiodsf** [obspy/obspy#2004]
Any plans to add support to [sc3ml 0.10 schema](http://geofon.gfz-potsdam.de/ns/seiscomp3-schema/0.10/)?

**Comment by Jollyfant** [comment]
Looks like the only change in the 0.10 schema is the introduction of a `ResponseIIR` stage. But it's not really used so it should be trivial almost?

@andres-h

**Comment by megies** [comment]
also see #1873 for event data

**Comment by claudiodsf** [comment]
To give some context, we had to move to a development version of SC3, since they [recently introduced](https://github.com/SeisComP3/seiscomp3/commit/135092b96055f4f419618bebe30907de60ba50e7) decimation attributes for PAZ stages, which we do have in our metadata.

**Comment by Jollyfant** [comment]
@claudiodsf can you post an example of metadata in the 0.10 format with the decimation attributes? Also, do you have one with the newly introduced responseIIR element?

**Comment by claudiodsf** [comment]
@Jollyfant Sorry for reeeeaaaly long delay. Attached is an example.
[OVPF.BOR1.dataless.fdsnwml2inv.xml.zip](https://github.com/obspy/obspy/files/1889152/OVPF.BOR1.dataless.fdsnwml2inv.xml.zip)

**Comment by Jollyfant** [comment]
We can represent IIR filters using the `PolesZerosResponseStage` right? Something like this for the example you provided as a mapping.. anyone confirm?

    <responseIIR publicID="ResponseIIR/20171214124152.521971.13" name="ResponseIIR/20171214124152.521971.13">
      <type>D</type>
      <gain>1</gain>
      <gainFrequency>1</gainFrequency>
      <decimationFactor>0</decimationFactor>
      <delay>0</delay>
      <correction>0</correction>
      <numberOfNumerators>1</numberOfNumerators>
      <numberOfDenominators>1</numberOfDenominators>
      <numerators>1</numerators>
      <denominators>0.999999</denominators>
    </responseIIR>

	ResponseIIR/20171214124152.521971.13 
	From COUNTS to COUNTS
	Stage gain: 1.0, defined at 1.00 Hz
	Decimation:
		Input Sample Rate: 100.00 Hz
		Decimation Factor: 0
		Decimation Offset: 0
		Decimation Delay: 0.00
		Decimation Correction: 0.00
	Transfer function type: DIGITAL (Z-TRANSFORM)
	Normalization factor: 1, Normalization frequency: 0.00 Hz
	Poles: (0.999999+0j)
	Zeros: (1+0j)

 I would like to refactor this module a little bit and include the 0.10 then..

**Comment by andres-h** [comment]
> We can represent IIR filters using the PolesZerosResponseStage right?

Not so trivial, but should be doable with tf2zpk(), see https://github.com/andres-h/fdsnws_scripts/blob/f4577a26e45fc8068705dbfc7f783dd1bbc9cce5/fdsnwsscripts/seiscomp/fdsnxml.py#L254

**Comment by Jollyfant** [comment]
Alright, thanks. I am unfamiliar with it, but this result seems a little wonky:

    tf2zpk([1.0], [0.999999])
    >>> (array([], dtype=float64), array([], dtype=float64), 1.000001000001)

**Comment by Jollyfant** [comment]
Maybe this can make it to `1.2.0` still but someone will need help me out with the IIR stage and write a good test for it. There's a WIP pull request with some code and a basic test.

**Comment by megies** [comment]
"Maybe" and "someone" are words that make me think it will probably stay with 1.3.0.. ;-)

**Comment by yochaibh** [comment]
I tried to load the seiscomp inventory version 0.1 and it looks like that the FAP response is not recognized. Any plan to add support to FAP response to the inventory?

**Comment by megies** [comment]
> I tried to load the seiscomp inventory version 0.1

Actually the file you have is schema version 0.10

**Comment by yochaibh** [comment]
You are right it is 0.10 I changed the version name to 0.6 and after losing the FAP  the inventory was uploaded successfully.

**Comment by megies** [comment]
@yochaibh i'm adding read support to #2124, can i include your file (stripped down to FAP response) in obspy for testing? Btw, this FAP response in your file looks very strange to me, maybe you want to double check.. it says gain 1 at 0.02 Hz and then the list elements go from 0.5 Hz to 50 Hz with a linear rise in amplitude and constant phase. This looks very odd to me.

**Comment by yochaibh** [comment]
Hi,

You can use the file, I agree that the response looks strange an I will
check it. I think that the problem is confusion between frequency and
period.

Thanks for all

Yochai

P.S

If you need that I will send any additional information please let me know.

**Comment by megies** [comment]
> You can use the file, I agree that the response looks strange an I will check it. I think that the problem is confusion between frequency and period.

This could also be an issue of units not/wrong specified (displacement / velocity etc).

**Comment by megies** [comment]
obsolete
