### ISSUE TITLE
check new nonlinloc version 7

### ISSUE THREAD

**Issue by megies** [obspy/obspy#2005]
This is just a reminder to check if our nonlinloc read/write plugins work fine with new nonlinloc version 7: http://alomax.free.fr/nlloc/soft7.00/Update.html

**Comment by claudiodsf** [comment]
Got it. I’ll try to look into that.

**Comment by ThomasLecocq** [comment]
@claudiodsf is this ok ? should we move it to 2.0.0 & add test files ?

**Comment by megies** [comment]
CC @filefolder :rofl:

**Comment by megies** [comment]
I think we fixed some things that came up with new NLLoc hyp format with Nlloc v7, so, I'll close this for now.
