### ISSUE TITLE
seishub: authentication check not working

### ISSUE THREAD

**Issue by megies** [obspy/obspy#2007]
The authentication check `Client.test_auth()` seems broken and always returns `True`. Probably not worth fixing given that seishub kind of is replaced by [jane](http://github.com/krischer/jane).

CC @trichter

**Comment by barsch** [comment]
lets just deprecate obspy.seishub and obspy.db ...

**Comment by krischer** [comment]
Hehe - @megies would not like that ;-)

https://github.com/obspy/obspy/pull/1947

But we should IMHO really consider deprecating them long-term.

**Comment by megies** [comment]
I'm not intending to work on this issue, it's just for information..

**Comment by trichter** [comment]
@megies Thx, I used to use seishub for querying local cluttered waveform files, but not anymore.

**Comment by trichter** [comment]
> lets just deprecate obspy.seishub and obspy.db ...

I don't know the current status, but with sqlalchemy 1.4.0 we have new test fails in the db module.

See #2720 and https://tests.obspy.org/113566/

**Comment by barsch** [comment]
fixed in #2815
