### ISSUE TITLE
NOR to CNV

### ISSUE THREAD

**Issue by shicks-seismo** [obspy/obspy#2009]
io.nordic reads in pick weight from a cnv catalogue (i.e. 0 to 4) as the arrival.timeweight variable.
However, when writing the same catalogue to CNV format, the weights are not written. This is because CNV is trying to write pick.time_errors.uncertainty.
I'm not sure which is the correct convention here, but they should be consistent ...
Perhaps a fix needed for a future update ...?

**Comment by krischer** [comment]
I assigned @megies and @calum-chamberlain because I think they are originally responsible for the `io.cnv` and `io.nordic` modules ;-)

**Comment by megies** [comment]
Uhm.. I haven't used CNV export in ages, so I'll hapilly accept PRs. Argumentation seems reasonable, do you have examples for real world use of this pick weight stuff?

**Comment by calum-chamberlain** [comment]
I definitely used my discretion for where to put the weight in `io.nordic`... Those values are weights used in computing locations, and should be a vague representation of pick uncertainty. But, they are not in any kind of time units, when I transfer to NonLinLoc for large catalogues I do some stats to try and relate those weights to pick uncertainty in time (which is what I would think pick.time_errors.uncertainty should be).

Without knowing the CNV format, I would say that Nordic is doing what I think it should, and I don't think the two values are interchangeable. My take is that it should be up to the user to convert in some sensible way between the weights and physical uncertainty values.

I have many examples for pick-weights in Nordic format if needed - also weighted picks are included in the tests for `io.nordic`.

**Comment by megies** [comment]
Is this still an issue or should we close it (I'm tempted to). Has been stale for 1.5 years now.
