### ISSUE TITLE
Inventory write fails when network starts before year 1900, due to datetime strftime

### ISSUE THREAD

**Issue by iceseismic** [obspy/obspy#2013]
inventory.write fails  when the network start_date is before 1900  ( which it is for the New Zealand national network, ==1884), due to the datetime strftime(), which requires year >= 1900.

[ Using obspy 1.1 through anaconda, and python 2.7 ] 

Fails through line 320 in inventory.py, in write   ; line 864 in core.py in _write_stationxml ; line 928 in core.py, in _write_network ; line 928 in core.py in _get_base_node_attributes, ; line 1490 in core.py in _format_time,  and line 1213 in utcdatetime.py in strftime.
Final line in the traceback is "ValueError: year=1884 is before 1900; the datetime strftime() methods require year >= 1900"

**Comment by barsch** [comment]
```strftime``` is always problematic - we should better use something similar to ```UTCDateTime.__str__```  (https://github.com/obspy/obspy/blob/master/obspy/core/utcdatetime.py#L948-L965) which can handle years from 0-9999

**Comment by krischer** [comment]
Fixed in #2015. Note that this already works in ObsPy 1.1.0 with Python 3.x. With my new fix it also works on Python 2 but a quick fix for you would be to just create a new conda environment with Python 3.

**Comment by krischer** [comment]
@QuLogic Any idea why this is not getting closed automatically? It has been fixed in #2015 and the commits are also already merged to `master`. I think I also used the correct wording in the description of the other pull request.

**Comment by megies** [comment]
> this is not getting closed automatically

strange indeed..

**Comment by QuLogic** [comment]
The commit is in `master`, but the commit message never said it fixed this issue. The PR _description_ did, but it's targetting `maintenance_1.1.x`, so no closing/fixing message ever got to `master`.

**Comment by megies** [comment]
Blah, that's something should be changed by github.. it's really unintuitive.
