### ISSUE TITLE
obspy-mopad: error if source-mechanism start with a minus symbol

### ISSUE THREAD

**Issue by seisman** [obspy/obspy#2014]
- ObsPy: 1.1.0
- Python: Python 3.6.2 from Anaconda
- Platform: Linux

obspy-mopad reports an error if the `source-mechanism` starts with `-`. This issue seems related to the argument parser.
```
$ obspy-mopad plot -1,-1,-1,0,0,0                                                       
usage: obspy-mopad plot [-h] [-f <filename>] [-P] [-O] [-V <lat,lon,azi>]
                        [-p <projection>] [-U] [-N <no. of points>]
                        [-s <size in cm>] [-w <colour>] [-r <colour>]
                        [-a <alpha>] [-D]
                        [-d <index> <linewidth> <colour> <alpha>]
                        [-e <size> <linewidth> <alpha>] [-b]
                        [-l <linewidth> <colour> <alpha>]
                        [-n <linewidth> <colour> <alpha>] [-q <dpi>] [-L]
                        [-i {NED,USE,XYZ,NWU}] [-I]
                        source-mechanism
obspy-mopad plot: error: the following arguments are required: source-mechanism
```

**Comment by krischer** [comment]
Yea this is a limitation/consequence of Python's `argparse`. Anything that starts with a dash is considered to be an optional argument and there is no way for `argparse` to distinguish between an argument or an actual value. A workaround is to pass it as a string with an additional space in the beginning, e.g.

```bash
$ obspy-mopad plot " -1,-1,-1,0,0,0"
```

I'm closing this because I don't think we can easily have a proper fix for this.

**Comment by QuLogic** [comment]
You can use two dashes to separate optional arguments from positional arguments. `obspy-mopad plot -- -1,-1,-1,0,0,0` works, though there's apparently nothing to plot.

**Comment by krischer** [comment]
Ah nice. Didn't know that. It should be a fully white circle as its a perfect implosion ;-)

**Comment by megies** [comment]
I'm reopening this, because I think it would be good to add this piece of information to the help string?

**Comment by QuLogic** [comment]
It's standard behaviour in `argparse` and most GNU utilities. But I'm not sure how to get `argparse` to explicitly show it in the usage listing.

**Comment by megies** [comment]
Hmm.. actually since it's standard behavior, we shouldn't add it ourselves. The proper fix would rather be to file a PR upstream for argparse usage info text..
