### ISSUE TITLE
Read and merge miniSEED traces - Memory Error

### ISSUE THREAD

**Issue by nukolas** [obspy/obspy#2019]
I am working with a temporary seismometer network of 10x instruments which was active over about 10 days.  In total, the miniseed waveform files are approx 350 Mb.  If I try to read and merge all files, the process maxes out my memory and swap (15Gb RAM, 15Gb SWAP) and I receive a memory error.

Is there a more memory efficient way to read and merge waveform files?

Here is my code:

    def read_merge_trim():

        dat_dir = '/DATA/'
        tce_dir = '/DATA/PROCESSED/'
        if not os.path.exists(tce_dir):
            os.makedirs(tce_dir)

        st = Stream()
        file_list = []
        for path, subdirs, files in os.walk(dat_dir):
            for name in files:
                if name.endswith('.msd'):
                    print(os.path.join(path, name))
                    file_list.append(os.path.join(path, name))
        for file in file_list:
            st += read(file)

        st.sort(['starttime'])
        print('Merging traces...')
        st.merge(method=1, fill_value=0)

Obspy 1.0.3
Python 2.7
Linux 64-bit

**Comment by krischer** [comment]
I guess this might use a lot of memory because miniseed is pretty efficient at compressing data and uses a lot more memory once unpacked - furthermore temporary copies are required for actually merging the traces so its memory usage peak could be fairly high. These are all just guesses and I did not do any benchmarking - it might well be that ObsPy does some silly things in there.

A couple of suggestions:

(1) It is fairly cumbersome to work with very large traces so maybe just work with smaller increments of data?
(2) MiniSEED files can be merged by just slapping them together on the command line: `cat file1.mseed file2.mseed > merged_file.mseed`

**Comment by megies** [comment]
> (2) MiniSEED files can be merged by just slapping them together on the command line: cat file1.mseed file2.mseed > merged_file.mseed

That's true, but this looks to be about merging gaps/overlaps though, so concatenating is not equivalent.

But @krischer is right, this is not the right approach as it blows up in memory which is not a surprise, actually. If you really need merging gaps/overlaps you should break down your workflow to e.g. work on daily files.

But, to be honest, at the end of the day.. such inexpensive pre-processing of data for specific workflows is IMHO best done on the fly right during processing, and the original raw data kept for posterity.

**Comment by nukolas** [comment]
Thanks @krischer and @megies, I take your comments on board, although this is difficult to implement and more cumbersome for my situation.

Below is an explanation of my task, this isn't an Obspy issue I suppose, so maybe GitHub is not the most appropriate to discuss this - if so, can you suggest a better place?

What I am working on is a grid of HVSR (Horiz. to Vert. Spec. Ratio) measurement made using temporary deployments of 10x instruments.  I have all my raw data files in a file structure arranged by instrument + component ID, and a csv log file with the instrument ID, start and end date-times for each HVSR measurement point.   There are many gaps in the traces, in fact more gaps than data.  My pre-processing merges all of the data files into traces identified by instrument ID and component and then I cut these traces into segments defined by the start and end date-times in my csv log file.  I don't keep the gaps which are interpolated in the merge process, and some of these segments span across a date change (e.g. 15-11-17-T23:00:00 to 16-11-17-T01:00:00), so I need a workflow which can deal with this.  These final segments are what I work on for all subsequent processing.

As you can see, this is not an array deployment for xcorr processing or the like (which for this it would be appropriate to break down the workflow and merge the data files e.g. for a daily basis).

For this project, I have approximately 100 individual HVSR deployments, so I need a script which can read in all my data files and output the merged traces corresponding to each deployment without any manual arrangement of the data files into a file system before pro-processing.

My script for sorting and cutting the merges traces is as follows:
 
    ## Read deployment log file
    data = pd.read_csv(dat_dir + '/seismic_log_HVSR.csv')

    ## Create lists from deployment log cols
    line = data.LINE.tolist()
    station = data.STATION.tolist()
    instrument = data.INSTRUMENT.tolist()
    start_date = data.START_DATE_GMT.tolist()
    start_time = data.START_TIME_GMT.tolist()
    end_date = data.END_DATE_GMT.tolist()
    end_time = data.END_TIME_GMT.tolist()

    sites = [str(l)+'-'+str(s) for l,s in zip(line,station)]
    t = [s_d+'-T'+s_t for s_d,s_t in zip(start_date, start_time)]
    dt = [e_d+'-T'+e_t for e_d,e_t in zip(end_date, end_time)]

    freq = 0.01

    ## Loop through HV deployments
    for i, (instr, site, start, stop) in enumerate(zip(instrument, sites, t, dt)):
        print('Slicing traces...')
        print('Station: ' + site)
        print('Instrument ID: ' + instr)
        print('Start: ' + start)
        print('Stop: ' + stop)
        t = UTCDateTime(start)
        dt = UTCDateTime(stop)
        st_select = st.select(id='*'+str(instr)+'*')
        st_slice = st_select.slice(t, dt)
        print('Filtering traces...')
    ## Cut trace and save for each time interval
        st_slice.filter('highpass', freq=freq)
        st_slice.detrend(type='demean')
        st_slice.taper(max_percentage=0.1, type='hann', max_length=None, side='both')
    ## Write merged & filtered traces
        print('Writing traces...')
        for tr in st_slice:
            print(tr)
            print(site)
            tr.stats.station = site
            tr.write(tce_dir + '/' + site + '_' + str(instr) + '_' + tr.stats.channel + '.msd', format='MSEED')


One work around that I can see would be to load in all my raw files into a stream as I have been doing, but only merge files between a certain start and end date-time range, instead of merging the whole lot with filling the gaps and then cutting it to the desired segment.  I don't know how to implement this using Obspy, can you help me on this one or any other ideas?

**Comment by megies** [comment]
This is now going in the direction of a user question about Python/ObsPy programming in general,  best asked on the users mailing list. I didn't read everything and obviously we (the core devs) could help but we just don't have the time to solve such problems for everybody (for free ;-)..

I'm gonna close this, feel free to reopen if anything else comes up.
