### ISSUE TITLE
Totally newbie: questions on PPSD

### ISSUE THREAD

**Issue by crsengineering** [obspy/obspy#2020]
ObsPy version: 1.02
OS: Ubuntu 16.02, i686

Hi to all, I'm newbie about ObsPy and Python, so I apologize if my questions would be so stupid.....

I'm trying to replicate graph in "Instrumentation in Earthquake seimology, vol. 2, fig. 2.48" about noise of MEMS accelerometer, for comparison among several commercial MEMS accelerometers and seismic instruments.

1) on PPSD example it's reported dataless of BW_KW1 reports sensor as Trillium (output in velocity), so why graph is PPSD example is in [m^2/s^4/Hz]? Should'n it be in [m^2/s^2/Hz], should it?

2) for sensors I get poles and zeros from datasheet, but now I'm using a simulated trace sampled at 50 Hz, can I use a simple 1th order, 50 Hz low pass filter pole for dataless of MEMS accelerometer?

Thanks.

**Comment by megies** [comment]
Please go via the users mailing list with this kind of questions, so that the user base can offer help. Thanks.

**Comment by megies** [comment]
Also you should consider updating to 1.1.0 which has new features in PPSD, see changelog and the what's new page in the wiki.
