### ISSUE TITLE
core: deprecate attach_response() or show Warning

### ISSUE THREAD

**Issue by megies** [obspy/obspy#2025]
We should remove `Stream/Trace.attach_response()` as soon as possible. It's unfortunate that we overlooked to deprecate it for release `1.1.0` but we should now add the deprecation to `1.1.1` and we should still consider to remove it for release of `1.2.0`, at least if it comes a considerable time span before `1.1.1`.

**Comment by krischer** [comment]
I actually feel quite strongly that we should NOT remove this for at least the next couple of releases. We broke backwards compatibility once with `1.0.0` and it was fairly painful in parts so I see little reason to do it again if there are not some very clear and tangible benefits. An option would be to just raise a warning if `attach_response()` is used. Then it keeps working as it always did but people will at least be aware that something might go wrong and are steered towards the proper way of doing things.

**Comment by megies** [comment]
Fair enough, I guess..

**Comment by samuelchodur** [comment]
Would you like to set a release version for removal in stone so the warning can be more descriptive?

**Comment by megies** [comment]
I agree with @krischer's argumentation that maybe a removal is not really necessary and a warning will do the trick. So a generic 'you better use remove_response(inventory=...)' should do the trick.

**Comment by megies** [comment]
Just adding a note to the docs should be OK actually
