### ISSUE TITLE
Correlations not normalised

### ISSUE THREAD

**Issue by calum-chamberlain** [obspy/obspy#2035]
The recent correlation implementation does not correctly normalise for moving window correlations. Currently the total data window standard deviations are accounted for, rather than the standard deviations at each step.  A result of this is that, in the example [here](https://gist.github.com/calum-chamberlain/50b80dd0be71916906e33e532654ebe1) correlations are suppressed, with a perfect correlation given a value of ~0.55 rather than 1.0.

The example is a little extensive, but I see two options, either [zero-normalised](https://en.wikipedia.org/wiki/Cross-correlation#Zero-normalized_cross-correlation_(ZNCC)) (as used generally in template matching, where both the mean and standard deviation at each step are accounted for), or [normalised](https://en.wikipedia.org/wiki/Cross-correlation#Normalized_cross-correlation_(NCC)) (where only the standard deviation is accounted for). In the example I adapted the correlate function (or rather a hack thereof) to generate zero-normalised cross-correlations using bottleneck for moving window standard deviations.  I guess we wouldn't want to add bottleneck as a dependency though?

For interest sake, [EQcorrscan](http://eqcorrscan.readthedocs.io/en/latest/submodules/utils.correlate.html) uses zero-normalised cross-correlations and [FastMatchedFilter](https://github.com/beridel/fast_matched_filter/blob/master/fast_matched_filter/src/matched_filter.c#L115) uses the other type.

## System info
* Tested on Ubuntu and MacOS
* conda install, Python 3.5

**Comment by trichter** [comment]
Thanks for raising this issue. Coming from a noise background, where generally the data is much longer than the interesting shifts in the correlation function, this difference didn't play a mayor role. I think, we refrained from implementing the rolling standard deviation, because we feared a negative impact on the performance.

A possibility would be to include `demean='moving'`, `normalize='moving'` options to add support for this normalization. We should compare performance of a plain numpy appoach (e.g. [this one](http://www.rigtorp.se/2011/01/01/rolling-statistics-numpy.html)) against your bottleneck version.

Another kind of ugly work-around for your use case: Tentatively "correct" the normalization by adding a factor (5**0.5, square of quotient of window length) and calculate the correct normalizations only for interesting shifts.

**Comment by calum-chamberlain** [comment]
Ah, fair enough (re noise background) - sorry I didn't weigh in on the original PR that made this change, I think I missed it.

It definitely can have a large negative impact on performance, how about I write a couple of hacks with the numpy striding you suggested and the bottleneck version (and without) and plot up some memory and time measurements? I would definitely prefer to do it in numpy though. I'll play with some things this week and put results up here.

**Comment by calum-chamberlain** [comment]
So I ran some tests and put the results in a [notebook](https://gist.github.com/calum-chamberlain/40978a9e4e7cf7d8d1fcd4581416e9de).  The TLDR breakdown is that the rolling window numpy isn't memory efficient or fast enough for decent size datasets, which is as expected because it creates a N^2 array from an N-sized array the does a N individual calculations. The bottleneck implementation uses rolling window algorithms directly.

Of interest (assuming adding bottleneck as a dependency is a no go) is [scikit-learn's implementation](https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/template.py), which we should be able to repurpose.  Instead of using rolling windows they use a cumulative sum approach.  I avoided this in EQcorrscan because I was writing it in C (and was trying to balance memory and speed for large datasets) and ran into floating point rounding errors when the numbers got really big (think long-ish seismic dataset with a decent earthquake in it), but I haven't tried this in Python. No time tonight, but shouldn't be too hard to mock up.

**Comment by trichter** [comment]
Thanks for the analysis! This cumulative sum approach seems to be a nice trick to calculate "[fast normalized cross-correlation](http://www.academia.edu/download/3607630/10.1.1.21.6062.pdf)". Maybe that's the way to go, if it is not too much work to pull this from scikit? The code "looks" fast and efficient.

Regarding the interface, could be around `demean/normalize=None, 'naive', 'rolling' or 'moving'`. But the default should stay at 'naive' for backwards compatibility and efficiency reasons. True and False must still be supported.
Removing normalize keyword is probably no option. It's better to put up a warning in the docs.

I think nobody will have any objections if you want to add this feature :wink:

**Comment by calum-chamberlain** [comment]
Sounds good, I like the `'naive'` keyword too. I will crack on and make a PR.  

The cumulative sum method won't be as memory efficient as some other methods, but it shouldn't be too bad, especially for most things that you might use Obspy correlations for.

I should make sure I add some tests for all cases of `demean/normalize` including cases with large ranges in the data (to ensure we don't get into any issues representing massive cumulative sums).

**Comment by megies** [comment]
@trichter I think we can leave you in charge of this issue, OK?

**Comment by trichter** [comment]
OK, will do. Please jump in in time if you disagree on the course.

**Comment by megies** [comment]
Just give us a heads-up in case you guys want to do anything backwards incompatible. As far as I understood from briefly skimming over #2042 it's introducing another option? So that should not be real critical..

**Comment by trichter** [comment]
fixed in #2042
