### ISSUE TITLE
Minor correction in obspy.signal.PPSD

### ISSUE THREAD

**Issue by Jollyfant** [obspy/obspy#2039]
Hi, was trying to do very precise PSD processing of our archive. Unfortunately I need to work with exact samples and expect 48 segments (30 min. each) per day. The PPSD calculation always uses a single sample per segment more than it should and results in to the final daily segment being dropped.

Here is some demo code:

    import obspy
    import numpy as np

    header = {
        "starttime":  obspy.UTCDateTime("2017-01-01T00:00:00"),
        "network": "GB",
        "station": "MCH1",
        "channel": "BHE"
    }

    # 24.5 hours to account for 50% overlap through the next day
    print tr = obspy.Trace(data=np.arange(30 * 60 * 49, dtype=np.int32), header=header)
    >>> GB.MCH1..BHE | 2017-01-01T00:00:00.000000Z - 2017-01-02T00:29:59.000000Z | 1.0 Hz, 88200 samples

    ppsd = obspy.signal.PPSD(
        tr.stats,
        obspy.read_inventory("http://www.orfeus-eu.org/fdsnws/station/1/query?sta=MCH1&cha=BHE&level=response"),
    )

    ppsd.add(tr)

    print len(ppsd._times_processed)
    >>> 47

When we add a single second extra to the trace it will give 48 PSDs as expected but that is incorrect.

Here is a list of the segments it calculates:

    GB.MCH1..BHE | 2017-01-01T00:00:00.000000Z - 2017-01-01T01:00:00.000000Z | 1.0 Hz, 3601 samples
    GB.MCH1..BHE | 2017-01-01T00:30:00.000000Z - 2017-01-01T01:30:00.000000Z | 1.0 Hz, 3601 samples
    ...
    GB.MCH1..BHE | 2017-01-01T22:30:00.000000Z - 2017-01-01T23:30:00.000000Z | 1.0 Hz, 3601 samples
    GB.MCH1..BHE | 2017-01-01T23:00:00.000000Z - 2017-01-02T00:00:00.000000Z | 1.0 Hz, 3601 samples

It shows that the final sample used per segment overlaps and we are using 3601 samples per segment, not 3600 as we should. IMHO It can be fixed easily by subtracting tr.stats.delta from the end time of each segment.

I think it could be changed, what do you reckon @megies?

**Comment by megies** [comment]
I'm aware of limitations of the current approach, feeding in Traces. For cases that need to be ultra-exact, probably it would be easiest to add a new, additional method to add individual data slices (and raising an exception on wrong-length user input)? That would then leave the preparing the slices to the user and thus be fully transparent to them.

About the additional sample (making it 3601 in this case), I agree that this should be fixed..

**Comment by Jollyfant** [comment]
> (So this issue probably mixes two things that should be addressed, one for the maintenance line and one for master?)

I was only referencing the last sample problem, but I'm writing some atm to address this.
