### ISSUE TITLE
Obspy: mSEED to Ascii by using SLIST - problem zero offset

### ISSUE THREAD

**Issue by sambanne** [obspy/obspy#2050]
Hi all,

I am trying to convert mseed files to ascii files in Obspy by using SLIST.
I don't get errors, but the ascii output seems to have a zero offset; all values are positive and lie around 60000.
The real data (in the mseed file) has no zero offset and is centered around zero (both positive and negative values).

Does anybody understand why there is suddenly an offset in the ascii file? 
How can I solve this problem?

Thanks!

The Ascii output looks like this:

_TIMESERIES DATA, 899751 samples, 250 sps, 2015-01-01T00:00:00.000000, SLIST, INTEGER, 
64402	64196	64005	64092	63932	64194
64550	64680	64791	64566	64362	63880
63230	63059	63237	63793	63925	63814 etc._

I use the following Obspy code (Python 2.7.11 on Ubuntu 14.04.5, installed by Anaconda)

import obspy
import numpy
from obspy import read
import sys
from sys import argv

st=read('data.mseed')
t1=obspy.UTCDateTime(year=2015,julday=1,hour=0,minute=0,second=0)
t2=obspy.UTCDateTime(year=2015,julday=1,hour=0,minute=59,second=59)
st.trim(t1,t2)
tr=st[0]
tr.write("data.ascii",format="SLIST")

**Comment by barsch** [comment]
please attach the mseed file too

**Comment by megies** [comment]
No way to reproduce without the data file we asked for. Closing for lack of feedback. Please reopen if necessary.
