### ISSUE TITLE
 obspy-scan can not read wildcard at Windows CMD eviroment

### ISSUE THREAD

**Issue by likueimo** [obspy/obspy#2054]
I tried that obspy-scan with wildcard(*) is working at Linux platform.
Same command at Windows CMD is not working.
Only work with "." 
BUT wildcard work with Windows built-in command at CMD (ex : DIR *)
Easy to understand with Windows CMD screenshot
(same as Windows Powershell)
![test](https://user-images.githubusercontent.com/11157543/35078228-33db0722-fc3c-11e7-9884-d066fd423ca6.PNG)

---

Before submitting an Issue, please review the [Issue Guidelines](https://github.com/obspy/obspy/blob/master/CONTRIBUTING.md#submitting-an-issue).

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
1.1.0, python 3.6 with conda, Windows 10
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
miniconda
  -  If possible please supply a short, self contained, correct example that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.

**Comment by megies** [comment]
I have no idea about Windows command prompt, really. Maybe @ThomasLecocq  can comment.

On *nix the wildcards are expanded by the shell before actually calling the program, so what goes to scan is actually the resolved, matching file/directory names..

**Comment by ThomasLecocq** [comment]
Not sure it's a win problem... Why would you want to pass a * to this function? 

Maybe linux is doing the globbing before actually calling the func, therefore providing the ArgumentParser with the folders. I guess windows just passes the *. So, if that's the case, we need something like this:

```python
if  "".join(paths).count("*") != 0 and sys.platform == "win32":
    paths = glob.glob(paths)
```

**Comment by ThomasLecocq** [comment]
```sh
C:\Users\TLecocq\Desktop>python testwild.py
['testwild.py']

C:\Users\TLecocq\Desktop>python testwild.py *
['testwild.py', '*']
```

**Comment by megies** [comment]
> if "".join(paths).count("*") != 0 and sys.platform == "win32":
>     paths = glob.glob(paths)

Yeah, I guess we could just run each path through `glob` if on Windows..

**Comment by likueimo** [comment]
Actually, I just want plot Z channel of my seismic data. 
So I really do is like as ``obspy-scan *HZ*``
BUT, no data read in with * at Windows CMD.

**Comment by ThomasLecocq** [comment]
ok in the meantime, you can just run
``obspy-scan "HHZ,BHZ,SHZ,EHZ" `` 

I think it should work (or at least something like this, providing a list of possible paths)

**Comment by megies** [comment]
> BUT, no data read in with * at Windows CMD.

like mentioned, since it looks like Windows is not expanding those wildcards, you'll have to specify a valid path for now. easiest is to use the top level directory your data resides in

**Comment by likueimo** [comment]
Thank you guys for replying me so fast.
But, as I cd to seismic data folder, and type ``obspy-scan HHZ``
Nothing happen.
![test2](https://user-images.githubusercontent.com/11157543/35160153-521a3dc0-fd77-11e7-8af8-0f874c1fec09.PNG)

**Comment by megies** [comment]
Well.. "HHZ" is not a dir or filename, you could try `> obspy-scan .` (`.` for current directory), not sure if that works on windows.. or go one level higher and then do `> obspy-scan test` (`Test` as the directory name).

**Comment by ThomasLecocq** [comment]
@megies can the ``--id`` be used to reg-match the component ?

```
--id ID               Optional, a SEED channel identifier (e.g.
                        'GR.FUR..HHZ'). You may provide this option multiple
                        times. Only these channels will be plotted.
```

like using ``--id ?.?.?.?HZ`` or ``--id *.*.*.*HZ``?

**Comment by megies** [comment]
@ThomasLecocq Nope, currently no wildcard matching in that option.

**Comment by megies** [comment]
I feel like closing this one. Feels like an external issue that windows command prompt does not resolve those wildcards as *nix does.Everybody feel free to reopen if there is demand

**Comment by likueimo** [comment]
Got it. Thank you !  
I will retry this issue.  
If there is anything that I can help, I will submit here.

**Comment by megies** [comment]
>  I will retry this issue.

Well I guess it's kind of a non-issue, actually. Linux just resolves wildcards on the comman line and Windows doesn't apparently, so on windows you have to specify correct directory and/or filenames without wildcards (recursing through given directories still works since it's done inside obspy).

Although, it might be interesting to see if it works with chinese characters in directory structure, I'm pretty sure not all of our code is unicode safe when it comes to filenames and paths..
