### ISSUE TITLE
Documentation for trace.detrend

### ISSUE THREAD

**Issue by Keowne** [obspy/obspy#2055]
Hi there, just following up from recent discussion at the end of the Pull Request "higher order detrend function #1173". [Am creating a new Issue rather than new Pull request as unfortunately I don't have the time to figure that process out right now and simply create havoc with git at the best of times.] This is for ObsPy 1.1.0 by the way.

So in short, for the documentation regarding the obspy.core.trace.Trace.detrend, "**options" isn't explained in the same way that it is on say, for obspy.core.trace.Trace.filter, and there's no equivalent example usage. So documentation-wise, I suppose incorporating something like the following into obspy.core.trace.Trace.detrend would help:

```
:param options: Necessary keyword arguments for the respective detrend type
            that will be passed on. (e.g. ``order=2``, ``dspline=100`` for ``"spline"``)

.. rubric:: Example

>>> from obspy import read
>>> st = read()
>>> st.detrend('spline',order=2,dspline=100,plot=True)

.. plot::

from obspy import read
st = read()
st.detrend('spline',order=2,dspline=100,plot=True)

```
The reason for using st.detrend as opposed to st[0].detrend or tr.detrend is simply to illustrate that you can apply the process to the whole stream and not just on a trace by trace basis.

Many thanks.

**Comment by megies** [comment]
closed by above PR
