### ISSUE TITLE
A bug of _rotate_to_zne in obspy/obspy/core/stream.py

### ISSUE THREAD

**Issue by CovMat** [obspy/obspy#2056]
In line 3203 and 3204 of [https://github.com/obspy/obspy/blob/master/obspy/core/stream.py](https://github.com/obspy/obspy/blob/master/obspy/core/stream.py), the function ```_rotate_to_zne``` only deal with two types of component pair: ```components=("Z12", "123")```

However, for channels ```BHN``` ```BHE``` of some stations, the azimuths may be far away from 0 degree and 90 degrees. We can see an example in:
[http://ds.iris.edu/mda/DK/ANGG/--/BHN?timewindow=2011/10/22%2000:00:00-2012/05/02%2023:59:59](http://ds.iris.edu/mda/DK/ANGG/--/BHN?timewindow=2011/10/22%2000:00:00-2012/05/02%2023:59:59)
[http://ds.iris.edu/mda/DK/ANGG/--/BHE?timewindow=2011/10/22%2000:00:00-2012/05/02%2023:59:59](http://ds.iris.edu/mda/DK/ANGG/--/BHE?timewindow=2011/10/22%2000:00:00-2012/05/02%2023:59:59)

In above example, the azimuth of ```BHN``` is  ```238```, and ```BHE``` is ```328```, which means these horizontal components should also be rotated, although their names are ```BHN``` and ```BHE```.

I think using ```components=("ZNE","Z12", "123")``` may be better in ```_rotate_to_zne``` .

Many thanks.

**Comment by megies** [comment]
1) I tend to disagree, ZNE should clearly only be used for oriented instruments. So I would consider the provided data to be "buggy" in that regard and channel naming should be changed by the people recording the data. I think hardly anybody would suspect non-oriented data when given data with ZNE component codes.

2) If you really, nevertheless encounter non-oriented data with ZNE component codes (like in this case), the user can easily specify that those should be used in rotation when using `Stream.rotate()` (you should avoid using the low-level private functions directly).

**Comment by CovMat** [comment]
@megies 
Thanks.
I have sent a email to IRIS to report wrong component codes of station DK.ANGG

**Comment by megies** [comment]
> I have sent a email to IRIS to report wrong component codes of station DK.ANGG

Well.. maybe it would be better to contact Danish network operators..

**Comment by krischer** [comment]
Just for documentation purposes - @megies proposed solution to the problem at hand:

```python
st.rotate("->ZNE", inventory=inv, components=["ZNE"])
```
