### ISSUE TITLE
RT130 data encoding '32' not implemented

### ISSUE THREAD

**Issue by jau827** [obspy/obspy#2058]
**GitHub should mainly be used for bug reports and code developments/discussions. For generic questions, please use either the [[obspy-users] mailing list](http://lists.swapbytes.de/mailman/listinfo/obspy-users) (for scientific questions to the general ObsPy community) or our [gitter chat](https://gitter.im/obspy/obspy) (for technical questions and direct contact to the developers).**

---

Before submitting an Issue, please review the [Issue Guidelines](https://github.com/obspy/obspy/blob/master/CONTRIBUTING.md#submitting-an-issue).

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)

obspy 1.1.0
Python 3.6
macOS 10.13.1 High Sierra

  -  How did you install ObsPy and Python (pip, anaconda, from source ...)

Anaconda

  -  If possible please supply a short, self contained, correct example that
     demonstrates the issue.

    >>> from obspy import read
    >>> import obspy
    >>> a = read("/Volumes/RT130-R2D2/2018019/R2D2/1/210000005_0036EE80")

Following Error Received:

    Traceback (most recent call last):
      File "<pyshell#13>", line 1, in <module>
        a = read("/Volumes/RT130-R2D2/2018019/R2D2/1/210000005_0036EE80")
      File "<decorator-gen-31>", line 2, in read
      File "/Users/jau827/anaconda/envs/py36/lib/python3.6/site-
    packages/obspy/core/util/decorator.py", line 301, in _map_example_filename
         return func(*args, **kwargs)
      File "/Users/jau827/anaconda/envs/py36/lib/python3.6/site-packages/obspy/core/stream.py", 
    line 235, in read
        st.extend(_read(file, format, headonly, **kwargs).traces)
      File "<decorator-gen-32>", line 2, in _read
      File "/Users/jau827/anaconda/envs/py36/lib/python3.6/site-
    packages/obspy/core/util/decorator.py", line 211, in uncompress_file
        result = func(filename, *args, **kwargs)
      File "/Users/jau827/anaconda/envs/py36/lib/python3.6/site-packages/obspy/core/stream.py", 
    line 277, in _read
        headonly=headonly, **kwargs)
      File "/Users/jau827/anaconda/envs/py36/lib/python3.6/site-
    packages/obspy/core/util/base.py", line 412, in _read_from_plugin
         list_obj = read_format(filename, **kwargs)
       File "/Users/jau827/anaconda/envs/py36/lib/python3.6/site-
    packages/obspy/io/reftek/core.py", line 102, in _read_reftek130
        verbose=verbose)
      File "/Users/jau827/anaconda/envs/py36/lib/python3.6/site-
    packages/obspy/io/reftek/core.py", line 252, in to_stream
        raise NotImplementedError(msg)
    NotImplementedError: Reftek data encoding 'b'32'' not implemented yet. Please open an issue 
    on GitHub and provide a small (< 50kb) test file.

  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.

**Comment by megies** [comment]
Looks like this encoding is uncompressed data, so should be easy to add. Like the message states, please provide a small test file. ;-)

**Comment by jau827** [comment]
Please see attached file, thank you!

[230000005_0036EE80 copy.zip](https://github.com/obspy/obspy/files/1656136/230000005_0036EE80.copy.zip)

**Comment by megies** [comment]
@jau827 is there some recognizable signal in this data? do you happen to have it in a different file format?

**Comment by jau827** [comment]
@megies Unfortunately not, this was taken from a Reftek RT130 so it is in the reftek format. Which type of file format would help you? I could try to convert it. Were you able to read it in at all?

**Comment by megies** [comment]
nevermind.. converted it with an old conversion tool I had lying around

**Comment by megies** [comment]
’rt_mseed’ is showing errors during converting the file.. "Warning: Corrupted DT packet in file /tmp/230000005_0036EE80", but it seems it's converting just fine..

**Comment by megies** [comment]
@jau827 see #2059 should be working now.

**Comment by jau827** [comment]
@megies So, first thank you for all your help, second, I'm very new to how github works..do I need to re-install obspy or something? What should I do with the link you've posted #2059 ?

**Comment by megies** [comment]
Since it looks like you're on Anaconda and Mac, it should be easy to try this fix. In your environment, you can do..

```
# uninstall the conda package
conda remove obspy
# install the latest commit in that PR from source
pip install https://github.com/obspy/obspy/archive/9c36dc8200fcb345ab6fd58589167fcbe43e5d73.zip
```

**Comment by jau827** [comment]
@megies It works now! Thank you!
