### ISSUE TITLE
time shift in Lanczos interpolation not shifting any data

### ISSUE THREAD

**Issue by trichter** [obspy/obspy#2071]
Not sure if this is a bug or if it should work as it is now. The time shift parameter in Lanczos interpolation does only change the starttime for me, but does not shift the data:

```
In [1]: from obspy import read

In [2]: from obspy.signal.cross_correlation import correlate, xcorr_max

In [3]: tr = read()[0]

In [4]: tr.detrend()
Out[4]: BW.RJOB..EHZ | 2009-08-24T00:20:03.000000Z - 2009-08-24T00:20:32.990000Z | 100.0 Hz, 3000 samples

In [5]: tr2 = tr.copy()

In [6]: tr2.interpolate(100, 'lanczos', a=20, time_shift=0.02)
Out[6]: BW.RJOB..EHZ | 2009-08-24T00:20:03.020000Z - 2009-08-24T00:20:33.010000Z | 100.0 Hz, 3000 samples

In [7]: cc = correlate(tr.data, tr2.data, 1000)

In [8]: xcorr_max(cc)  # expected shift 2 or -2
Out[8]: (0, 0.9999999999999997)

In [9]: tr2 = tr.copy()  # now try sub-sample shifting

In [10]: tr2.interpolate(100, 'lanczos', a=20, time_shift=0.005)
Out[10]: BW.RJOB..EHZ | 2009-08-24T00:20:03.005000Z - 2009-08-24T00:20:32.995000Z | 100.0 Hz, 3000 samples

In [11]: cc = correlate(tr.data, tr2.data, 1000)

In [12]: xcorr_max(cc)  # max cc should be a bit smaller than 1
Out[12]: (0, 0.9999999999999997)
```

Edit: Similar results for `'weighted_average_slopes'`. Am I missing something?

**Comment by megies** [comment]
Uhm.. I think you're mixing up high-level and low-level views of the data. From a high-level perspective, changing the starttime of the `Trace` while not changing the `Trace.data` array is equal to performing an actual time shift on the data. From a low-level perspective, when working directly with `Trace.data` the change in trace start time won't affect the result.. you'll need a different approach in your workflow, I'd just remember the time shift and add it to the cross correlation shift at the very end.

**Comment by trichter** [comment]
OK, I get you point. But then, the time_shift parameter just changes the metadata. The docs say `time_shift: Interpolation can also shift the data with subsample accuracy...` which somehow implies that the data is actually shifted. I did not expect from an `interpolate` function, that it is performing subsample shifting by just changing the starttime which is of course trivial and can be done without the interpolate function.

**Comment by krischer** [comment]
I see your point and we should maybe change the documentation a bit. If I remember correctly I added this parameter but I don't really exactly recall why. I guess it was convenient to have a function that can "shift" the data and then exactly interpolate on chosen new time samples?

Nonetheless I actually think that changing the metadata with subsequent interpolation is a pretty good way to shift data in time assuming there is enough data at the boundaries to avoid any boundary effects.
