### ISSUE TITLE
Potential problem with seiscomp3 fdsnws module

### ISSUE THREAD

**Issue by rannof** [obspy/obspy#2078]
Hi,
I'm not sure if its a feature or bug nor if it is a fixable issue with obspy or seiscomp3.
When using obspy to download stream data from an fdsnws server spawned by seiscomp3 (newest precompiled version),
the server is hanged with CLOSE_WAIT on the port. After several reads, the server reaches its client limit and freeze. 
============== example of client side ================
```
from obspy.clients.fdsn import Client as fdsnclient
.
.
.
def get_data(self):
    for tr_id in tr_id_list: # loop over several trace ids
        self.flink = fdsnclient(self.fdsnserver, timeout=30)
        stream = self.flink.get_waveforms(tr_id.network, tr_id.station, tr_id.location, tr_id.channel, self.starttime, self.endtime)
    .
    .
    .
(exit python script, re-run it after a while)
```
==============================================

=========== output on server ============
```
> netstat -a | grep 8181
tcp       27      0 0.0.0.0:8181            0.0.0.0:*               LISTEN     
tcp      230      0 ws-fdsn:8181            clientip:54342 CLOSE_WAIT 
tcp      611      0 ws-fdsn:8181             clientip:58324 CLOSE_WAIT
.
.
.
(similar entries as the limit of clients on the module)
```
==================================== 

A workaround:
============== No problem code ==========
```
def get_data(self):
    from obspy.clients.fdsn import Client as fdsnclient # import within the function)
    for tr_id in tr_id_list: # loop over several trace ids
        self.flink = fdsnclient(self.fdsnserver, timeout=30)
        stream = self.flink.get_waveforms(tr_id.network, tr_id.station, tr_id.location, tr_id.channel, self.starttime, self.endtime)
    del self.flink # delete the client object
```
=====================================

  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
obspy v 1.0.2 (possibly also newer versions), osx, linux (windows not tested) 
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
pip, anaconda
  -  If possible please supply a short, self contained, correct example that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
Do not know.

**Comment by krischer** [comment]
I don't think this is our fault. The fdsnws client does not do any fancy HTTP keep-alive connections or similar things. And I think `CLOSE_END` indicates that the local program should close the socket. That also seems to be the conclusion in https://github.com/SeisComP3/seiscomp3/issues/163.

Can this be closed?
