### ISSUE TITLE
merge streams with fill_value "None"

### ISSUE THREAD

**Issue by clotairem** [obspy/obspy#2080]
I am trying to use the merge method of the stream class with data with gaps. It should result in a numpy maskedarray. However, it seems some of the traces are converted and some not so that merging fails (see below).
For the context, I would like to merge miniseed chunks but only those without gaps (there may be gaps between them or not). The solution I am following is to first merge() all using the option"None" and then split() to retrieve the continuous traces:
```
day_stream.merge(fill_value="None")
day_stream.split()
```
If you have a better idea...
thanks!

```
4 Trace(s) in Stream:
XY.NR45..EH1 | 2017-09-29T08:46:14.810000Z - 2017-09-29T08:46:36.715000Z | 200.0 Hz, 4382 samples
XY.NR45..EH1 | 2017-09-29T08:46:58.615000Z - 2017-09-29T08:48:35.100000Z | 200.0 Hz, 19298 samples
XY.NR45..EH1 | 2017-09-29T08:48:35.105000Z - 2017-09-29T08:50:35.625000Z | 200.0 Hz, 24105 samples
XY.NR45..EH1 | 2017-09-29T08:50:35.630000Z - 2017-09-29T08:59:59.995000Z | 200.0 Hz, 112874 samples
Traceback (most recent call last):
  File "./sdrsplit.py", line 111, in <module>
    day_stream.merge(fill_value="None")
  File "/Users/clotaire/miniconda2/envs/obspy/lib/python2.7/site-packages/obspy/core/stream.py", line 1946, in merge
    interpolation_samples=interpolation_samples)
  File "/Users/clotaire/miniconda2/envs/obspy/lib/python2.7/site-packages/obspy/core/trace.py", line 793, in __add__
    gap = create_empty_data_chunk(delta, lt.data.dtype, fill_value)
  File "/Users/clotaire/miniconda2/envs/obspy/lib/python2.7/site-packages/obspy/core/util/base.py", line 175, in create_empty_data_chunk
    temp *= fill_value
TypeError: Cannot cast ufunc multiply output from dtype('S11') to dtype('int32') with casting rule 'same_kind'
```

**Comment by megies** [comment]
> I would like to merge miniseed chunks but only those without gaps

You can just use `Stream.merge(-1)`, see https://docs.obspy.org/packages/autogen/obspy.core.stream.Stream.merge.html and the linked page of underlying method https://docs.obspy.org/packages/autogen/obspy.core.stream.Stream._cleanup.html


Regarding your error, you should not mix up `"None"` (as a string) and `None` (the Python builtin) which has a very different meaning..

**Comment by clotairem** [comment]
Thanks a lot, this was a stupid mistake...
