### ISSUE TITLE
Assigning floating point precision in the StationTXT output (or others)

### ISSUE THREAD

**Issue by nick-iris** [obspy/obspy#2084]
Currently there is no way to specify the decimal precision of individual floating point values printed in the [StationTXT](https://github.com/obspy/obspy/blob/master/obspy/io/stationtxt/core.py) Inventory output format. It would be useful to have a way to trim float values to a specified precision in the output.

Perhaps when a subclass of the [obspy.core.util.obspy_types.CustomFloat](https://github.com/obspy/obspy/blob/master/obspy/core/util/obspy_types.py#L206-L225) class is printed, the value could be trimmed to the `lower_uncertainty` and `upper_uncertainty` values if they are present. This would be similar to the way the `minusError` and `plusError` xml attributes are [assigned](https://github.com/obspy/obspy/blob/master/obspy/io/stationxml/core.py#L943-L959) in the [obspy.io.stationxml.core](https://github.com/obspy/obspy/blob/master/obspy/io/stationxml/core.py) module. 

**Example**

```python
import obspy
from obspy.core.util.obspy_types import FloatWithUncertainties
import sys


obs_network = obspy.core.inventory.Network('YW')
obs_station = obspy.core.inventory.Station('1006',
                                           FloatWithUncertainties(
                                                36.62230733,
                                                lower_uncertainty=-0.000001,
                                                upper_uncertainty=0.000001),
                                           FloatWithUncertainties(
                                                -97.73533425,
                                                lower_uncertainty=-0.000001,
                                                upper_uncertainty=0.000001),
                                           321.42,
                                           start_date='2016-06-22T12:27:53',
                                           end_date='2016-07-26T15:02:53')
obs_network.stations = [obs_station]
inv = obspy.core.inventory.Inventory([obs_network], '')
inv.write(sys.stdout, format='STATIONTXT', level='station')

```
The example above would print the station latitude and longitude to 6 decimal places of precision instead of 8. This is because the `lower_uncertainty` and `upper_uncertainty` values where set to -0.000001 and 0.000001 respectively.

i.e.
```
#Network|Station|Latitude|Longitude|Elevation|SiteName|StartTime|EndTime
YW|1006|36.622307|-97.735334|321.42|||
```

**Comment by nick-iris** [comment]
Thanks for looking at this. For now I'm going to round my source coordinates to 6 decimal places to match the SEED limitation. In the future I might try to add ObsPy support for specifying the floating point precision.

**Comment by megies** [comment]
Sounds like this can be closed then? Feel free to reopen when you feel like this should be back on the agenda.
