### ISSUE TITLE
taup problem with solar model

### ISSUE THREAD

**Issue by benjaminfernando** [obspy/obspy#2086]
Hi, 

I am trying to use Obspy.taup to create some travel-time curves for a model of the Sun (though one that is currently a Poisson Solid) however I am getting an error when I try and use taup_create.build_taup_model.

I have checked this procedure with an iasp91 example, and that works fine, but with the custom model I am using a series of errors are thrown. The two models are identical in content, apart from the values of course being different. A .txt version of the .tvel file that I'm using is attached. 

Thanks, 

Ben 

-Obspy 1.1.0 on OsX downloaded using Anaconda

Using: from obspy.taup import taup_create 
taup_create.build_taup_model(‘solar_constant_density_backup.tvel’)

Building obspy.taup model for 'solar_constant_density_backup.tvel' ...
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-8d44c3e3d9da> in <module>()
----> 1 tc.build_taup_model('solar_constant_density_backup.tvel')

~/anaconda/envs/salvus/lib/python3.6/site-packages/obspy/taup/taup_create.py in build_taup_model(filename, output_folder, verbose)
    179                             output_filename=output_filename)
    180     mod_create.load_velocity_model()
--> 181     mod_create.run()
    182 
    183 

~/anaconda/envs/salvus/lib/python3.6/site-packages/obspy/taup/taup_create.py in run(self)
    119         """
    120         try:
--> 121             self.tau_model = self.create_tau_model(self.v_mod)
    122             # this reassigns model! Used to be TauModel() class,
    123             # now it's an instance of it.

~/anaconda/envs/salvus/lib/python3.6/site-packages/obspy/taup/taup_create.py in create_tau_model(self, v_mod)
     84             self.max_range_interval * pi / 180.0, self.max_interp_error,
     85             self.allow_inner_core_s,
---> 86             _DEFAULT_VALUES["slowness_tolerance"])
     87         if self.debug:
     88             print("Parameters are:")

~/anaconda/envs/salvus/lib/python3.6/site-packages/obspy/taup/slowness_model.py in __init__(self, v_mod, min_delta_p, max_delta_p, max_depth_interval, max_range_interval, max_interp_error, allow_inner_core_s, slowness_tolerance, skip_model_creation)
     74         if skip_model_creation:
     75             return
---> 76         self.create_sample()
     77 
     78     def __str__(self):

~/anaconda/envs/salvus/lib/python3.6/site-packages/obspy/taup/slowness_model.py in create_sample(self)
    154         if self.debug:
    155             print("coarse_sample")
--> 156         self.coarse_sample()
    157         if self.debug:
    158             self.validate()

~/anaconda/envs/salvus/lib/python3.6/site-packages/obspy/taup/slowness_model.py in coarse_sample(self)
    821             is_p_wave=self.p_wave,
    822             radius_of_planet=self.v_mod.radius_of_planet,
--> 823             is_spherical=self.v_mod.is_spherical)
    824 
    825         self.p_layers = np.insert(self.p_layers, index, curr_p_layer)

~/anaconda/envs/salvus/lib/python3.6/site-packages/obspy/taup/slowness_layer.py in create_from_vlayer(v_layer, is_p_wave, radius_of_planet, is_spherical)
    323 
    324         if bot_depth.shape:
--> 325             if bot_depth[-1] == radius_of_planet and bot_vel[-1] == 0.0:
    326                 bot_depth[-1] = 1.0
    327         ret['bot_p'] = (radius_of_planet - bot_depth) / bot_vel

IndexError: index -1 is out of bounds for axis 0 with size 0

[solar_constant_density_backup copy.txt](https://github.com/obspy/obspy/files/1784509/solar_constant_density_backup.copy.txt)

**Comment by krischer** [comment]
I'm not sure if we'll get around to fixing this soon. I hope so but cannot promise it. Did you try the Java TauP library? It tends to work with some edge cases where our port does not.

**Comment by benjaminfernando** [comment]
Yes, it does work with the Java TauP binaries, I was just hoping to simplify the working a little by doing everything in ObsPy. 

If you are able to fix it, would you be able to update this thread? That would be much appreciated. 

Thanks,
Ben

**Comment by krischer** [comment]
Sure thing!

**Comment by megies** [comment]
@johnrudge I tried this one to see if works now, but building the model takes ages (not sure if that's supposed to be like that but it feels weird), even if I reduce the number of layers down to 38. It's stuck inside `SlownessModel.ray_param_inc_check()` and `add_slowness()` gets called a gazillion times looks like.

**Comment by megies** [comment]
This is with number of layers reduced to 38

```
Building obspy.taup model for 'solar_constant_density_backup.copy.tvel' ...
filename = solar_constant_density_backup.copy.tvel
Done reading velocity model.
Radius of model  is 689655.337
Using parameters provided in TauP_config.ini (or defaults if not) to call SlownessModel...
Parameters are:
taup.create.min_delta_p = 0.1 sec / radian
taup.create.max_delta_p = 11.0 sec / radian
taup.create.max_depth_interval = 115.0 kilometers
taup.create.max_range_interval = 0.04363323129985824 degrees
taup.create.max_interp_error = 0.05 seconds
taup.create.allow_inner_core_s = True
Slow model  17802 P layers,24072 S layers
Method run is done, but not necessarily successful.
Traceback (most recent call last):
  File "/tmp/modcrea.py", line 2, in <module>
    taup_create.build_taup_model('solar_constant_density_backup.copy.tvel')
  File "/home/megies/git/obspy/obspy/taup/taup_create.py", line 178, in build_taup_model
    mod_create.run()
  File "/home/megies/git/obspy/obspy/taup/taup_create.py", line 117, in run
    self.tau_model = self.create_tau_model(self.v_mod)
  File "/home/megies/git/obspy/obspy/taup/taup_create.py", line 106, in create_tau_model
    return TauModel(self.s_mod, radius_of_planet=v_mod.radius_of_planet)
  File "/home/megies/git/obspy/obspy/taup/tau_model.py", line 63, in __init__
    self.calc_tau_inc_from()
  File "/home/megies/git/obspy/obspy/taup/tau_model.py", line 134, in calc_tau_inc_from
    self.tau_branches[wave_num, crit_num].create_branch(
  File "/home/megies/git/obspy/obspy/taup/tau_branch.py", line 79, in create_branch
    time_dist = self.calc_time_dist(s_mod, top_layer_num, bot_layer_num,
  File "/home/megies/git/obspy/obspy/taup/tau_branch.py", line 96, in calc_time_dist
    layer_num = np.tile(layer_num, plen).reshape((plen, llen))
  File "<__array_function__ internals>", line 180, in tile
  File "/home/megies/miniconda3/envs/master/lib/python3.9/site-packages/numpy/lib/shape_base.py", line 1258, in tile
    c = c.reshape(-1, n).repeat(nrep, 0)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 3.19 GiB for an array with shape (24073, 17802) and data type int64
```

```
#Solar - doesn't like big jumps
#remove     696486.543    504.58816    291.40864    5
    0.0    6.864425    3.963177622    5   
    144.752    6.9085688    3.988664056    5   
    532.807    8.1454419    4.702773074    5   
    647.086    8.7999794    5.080670475    5   
    990.249    10.25845    5.922718869    5   
    1556.643    11.992565    6.923910631    5   
    2318.909    13.985118    8.074311642    5   
    3297.28    16.478816    9.514048854    5   
    4579.491    19.908128    11.49396306    5   
    6218.301    24.503838    14.14729747    5   
    8331.837    30.880435    17.82882746    5   
    11171.143    38.192285    22.05032603    5   
    15202.795    45.90873    26.50541762    5   
    20924.498    56.32606    32.5198659    5   
    28780.994    68.8023    39.72302643    5   
    39626.956    83.284015    48.08404848    5   
    54455.746    100.28561    57.89992393    5   
    74528.399    120.4442    69.53849129    5   
    99952.23    143.33577    82.75494539    5   
    131573.063    169.58258    97.90854821    5   
    168558.469    198.88472    114.8261466    5   
    209454.612    229.85054    132.7042711    5   
    258175.836    255.3876    147.4480996    5   
    309122.498    279.44546    161.3379116    5   
    358352.937    304.09388    175.5686835    5   
    406069.432    331.30796    191.2807399    5   
    451977.502    362.02864    209.0173328    5   
    497061.97    397.88804    229.720767    5   
    540954.122    438.95072    253.4283164    5   
    581767.721    478.33264    276.1654785    5   
    613284.93    501.75896    289.6906706    5   
    638254.228    510.45312    294.7102462    5   
    659118.994    510.10692    294.5103676    5   
    674762.465    507.1972    292.83044    5   
    684295.942    505.40608    291.7963363    5   
    689655.337    504.5416    291.2972286    5   
```

**Comment by johnrudge** [comment]
Well, the sun is rather big, so I don't think you can just use the default `max_delta_p = 11.0 sec / radian` and `max_depth_interval = 115.0 kilometers` without creating massive models. To get the sun to work you probably need to manually call `TauPCreate` with some appropriate values set. @benjaminfernando probably knows what values to set if this managed to work with the java code.

**Comment by johnrudge** [comment]
This seems to work:
```
from obspy.taup.taup_create import TauPCreate
from obspy.taup import TauPyModel

mod_create = TauPCreate(input_filename='megies_solar.tvel',
                        output_filename='megies_sol.npz',
                        max_depth_interval = 100000,
                        max_delta_p=100.0,
                        verbose = False)
mod_create.load_velocity_model()
mod_create.run()

model = TauPyModel('sol.npz')
arrivals = model.get_ray_paths(0.0, 60.0)
arrivals.plot_rays()
```

**Comment by johnrudge** [comment]
It at least produces a plot...
![Figure_1](https://user-images.githubusercontent.com/43536815/169812559-9432227d-4a10-4977-8fb6-96333e99ff77.png)

**Comment by megies** [comment]
> Well, the sun is rather big, so I don't think you can just use the default `max_delta_p = 11.0 sec / radian` and `max_depth_interval = 115.0 kilometers` without creating massive models. To get the sun to work you probably need to manually call `TauPCreate` with some appropriate values set. @benjaminfernando probably knows what values to set if this managed to work with the java code.

Ah good stuff. Yea I didn't look into it, just copy/pasted from the original post.

:+1:
