### ISSUE TITLE
can't read Double Difference catalog

### ISSUE THREAD

**Issue by ArthurRodgers** [obspy/obspy#2095]
I got errors trying to read QuakeML file generated by web-request

cat_dd = obspy.core.event.read_events('./foo.xml')

Single origin is generated by the following web request:
http://service.ncedc.org/fdsnws/event/1/query?start=2018-01-04T00:00:00.0&end=2018-01-05T00:00:00.0&minmag=3&catalog=DD&includeallmagnitudes=false&includearrivals=false&includemechanisms=false&orderby=time&format=xml

Reports error:
ValueError: Setting attribute "origin_type" failed. Value "Double Difference" could not be converted to type "Enum(["hypocenter", "centroid", "amplitude", "macroseismic", "rupture start", "rupture end"])"

This breaks some code that used to work

Note: first time bug report

**Comment by ArthurRodgers** [comment]
Note that the origin type from QuakeML file is:
<type>Double Difference</type>

**Comment by ArthurRodgers** [comment]
This may be a problem with QuakeMl written by NCEDC. Can this be checked?

**Comment by Jollyfant** [comment]
It seems that the QuakeML schema does not allow for that value as the `origin type`. IMHO it would be more appropriate for the source to adapt in this case.

**Comment by krischer** [comment]
Yea that is most definitely an invalid QuakeML file. The allowed origin types are documented here: http://docs.obspy.org/packages/obspy.core.event.header.html#obspy.core.event.header.OriginType

They coincide with what QuakeML allows: https://github.com/obspy/obspy/blob/cd581f0e27d34987681ecb0ea624cb2b0e3f4197/obspy/io/quakeml/data/QuakeML-BED-1.2.xsd#L45-L53

I think we should still change ObsPy so it would throw a warning in these cases but at least it would read the rest of the file.

**Comment by krischer** [comment]
This seems to be fixed server side and also "fixed" in ObsPy in #2106.

**Comment by megies** [comment]
> This seems to be fixed server

Wow, that's a quick reaction from NCEDC
