### ISSUE TITLE
Obspy spectrogram not producing expected results 

### ISSUE THREAD

**Issue by benjaminfernando** [obspy/obspy#2100]
Hi, 

I have an issue getting obspy.Trace.spectrogram to work properly on certain stations

I'm using the attached code(spectrogram.txt), along with a bunch of inputs (two attached for reference). On the station V.V.4 everything looks fine, and the spectrogram makes sense. On V.V.5 however, the spectrogram is basically blank. Both input files are effectively identical in format, so I'm not sure why this is - am I missing something basic? I've replaced .ascii with .txt for the purposes of uploading. 

I'm running Obspy 1.1.0 installed via conda on a Mac. 
[spectrum.txt](https://github.com/obspy/obspy/files/1887910/spectrum.txt)
[V.V4.RTZ.txt](https://github.com/obspy/obspy/files/1887916/V.V4.RTZ.txt)
[V.V5.RTZ.txt](https://github.com/obspy/obspy/files/1887917/V.V5.RTZ.txt)

Thanks 
Ben

**Comment by megies** [comment]
Maybe you can find help on the users mailing list..

**Comment by krischer** [comment]
The second file does not have any data in the second column so there are only 0. So naturally the spectrum is blank. Its not blank when you use the scipy spectrogram as you are actually reading in the 4th column which does have data.

**Comment by benjaminfernando** [comment]
Sorry, that was so incredibly stupid of me! I had used [:,1] when I meant [:,3]. Thanks!

**Comment by krischer** [comment]
No problem :)
