### ISSUE TITLE
does not have 'dataselect' and/or 'station' services

### ISSUE THREAD

**Issue by ElodieK** [obspy/obspy#2103]
Hi there,

I'm using the mass downloader for earthquake: obspy.UTCDateTime(2011, 6, 12, 21, 3, 26) with IRIS and ISC clients however am getting these errors:

[2018-04-10 10:44:56,888] - obspy.clients.fdsn.mass_downloader - INFO: Cannot use client 'ISC' as it does not have 'dataselect' and/or 'station' services.
[2018-04-10 10:44:56,888] - obspy.clients.fdsn.mass_downloader - INFO: Downloaded 0.0 MB in total.

Any suggestions please?

Thanks,
Elodie

**Comment by krischer** [comment]
The ISC does not have a dataselect nor a station service (it only serves event meta information) so it cannot be used to download that data from them - so that message is expected (it also only states it as an `INFO` message). The mass downloader dynamically figures out the capabilities of each service - one of the requirements is that the service can server waveforms and station metainformation in the first place.

It usually does not hurt to just leave the `providers` keyword argument empty. It will then just use all providers it knows about.

**Comment by ElodieK** [comment]
It is not just the ISC, it's also IRIS which I've downloaded data from for other earthquakes in the past.

________________________________

**Comment by ElodieK** [comment]
In [59]: run globaldata_afar.py

[2018-04-10 11:20:40,516] - obspy.clients.fdsn.mass_downloader - INFO: Initializing FDSN client(s) for IRIS.

[2018-04-10 11:20:40,520] - obspy.clients.fdsn.mass_downloader - INFO: Cannot use client 'IRIS' as it does not have 'dataselect' and/or 'station' services.

[2018-04-10 11:20:40,520] - obspy.clients.fdsn.mass_downloader - INFO: Successfully initialized 0 client(s): .

[2018-04-10 11:20:40,520] - obspy.clients.fdsn.mass_downloader - INFO: ============================== Final report

[2018-04-10 11:20:40,520] - obspy.clients.fdsn.mass_downloader - INFO: 0 MiniSEED files [0.0 MB] already existed.

[2018-04-10 11:20:40,520] - obspy.clients.fdsn.mass_downloader - INFO: 0 StationXML files [0.0 MB] already existed.

[2018-04-10 11:20:40,520] - obspy.clients.fdsn.mass_downloader - INFO: Downloaded 0.0 MB in total.

---------------------------------------------------------------------------

IndexError                                Traceback (most recent call last)

/Users/elodiekendall/Desktop/0PATHS/OBSPY/globaldata_afar.py in <module>()

     86

     87         sta_xml_file_list = glob.glob(os.path.join("stations/*.xml"))

---> 88         inv = read_inventory(sta_xml_file_list[0])

     89         for sta_xml in sta_xml_file_list[1:]:

     90            inv += read_inventory(sta_xml)


IndexError: list index out of range



On the shell:

Installed new opener with handlers: [<obspy.clients.fdsn.client.CustomRedirectHandler object at 0x109282c50>]

Base URL: http://service.iris.edu

Request Headers: {'User-Agent': 'ObsPy/1.1.0 (Darwin-15.6.0-x86_64-i386-64bit, Python 3.5.3)'}

Downloading http://service.iris.edu/fdsnws/dataselect/1/application.wadl with requesting gzip compression

Downloading http://service.iris.edu/fdsnws/event/1/application.wadl with requesting gzip compression

Downloading http://service.iris.edu/fdsnws/station/1/application.wadl with requesting gzip compression

Downloading http://service.iris.edu/fdsnws/event/1/catalogs with requesting gzip compression

Downloading http://service.iris.edu/fdsnws/event/1/contributors with requesting gzip compression

Uncompressing gzipped response for http://service.iris.edu/fdsnws/event/1/application.wadl

Uncompressing gzipped response for http://service.iris.edu/fdsnws/station/1/application.wadl

Uncompressing gzipped response for http://service.iris.edu/fdsnws/dataselect/1/application.wadl

Downloaded http://service.iris.edu/fdsnws/station/1/application.wadl with HTTP code: 200

Downloaded http://service.iris.edu/fdsnws/dataselect/1/application.wadl with HTTP code: 200

Downloaded http://service.iris.edu/fdsnws/event/1/application.wadl with HTTP code: 200

Downloaded http://service.iris.edu/fdsnws/event/1/catalogs with HTTP code: 200

Uncompressing gzipped response for http://service.iris.edu/fdsnws/event/1/contributors

Downloaded http://service.iris.edu/fdsnws/event/1/contributors with HTTP code: 200

Discovered station service

Discovered dataselect service

Discovered event service

Storing discovered services in cache.



Thanks.


________________________________

**Comment by krischer** [comment]
Thanks. It is not a firewall issue on your side.

I assume there was a temporary internet connection problem at one point. Our internal fdnsws client caches service discovery so they are only discovered once within a python run. Can you restart `ipython` and `run globaldata_afar.py` again or just run `python globaldata_afar.py` on the shell? I think it should work then.

**Comment by ElodieK** [comment]
Yes, it's working- thanks a lot.
Elodie
________________________________

**Comment by krischer** [comment]
Great :-)

**Comment by ElodieK** [comment]
Hi,


I'm having the same problem. My internet looks fine and I'm re-opening python and still no download. Is the problem your side?


Thanks.


________________________________

**Comment by krischer** [comment]
I'm pretty sure this is not ObsPy's fault. Does this:

```bash
python -c "from obspy.clients.fdsn import Client; Client('IRIS', debug=True)"
``` 

report discovered station + dataselect services? If yes then everything should work and there is some other issue. The mass downloader internally does the same.

**Comment by ElodieK** [comment]
Ah yes- found it.

Thanks again!
________________________________
