### ISSUE TITLE
GRF Format 

### ISSUE THREAD

**Issue by serdarkuyuk** [obspy/obspy#2108]
Could anyone help on how to read GRF (Generic Recording Format) format which is An Open, Device and Platform Independent, Packet Oriented Digital Waveform Data Recording Format 

here is basic information
http://banfill.net/doc/GRFDescription.pdf
here is the detailed format
http://banfill.net/doc/GRF.pdf

I can send you if you need an example file. 
Thanks in advance

**Comment by krischer** [comment]
The format does not look too complicated, and it is also appears to be well thought out and documented so it should be fairly simple to create a reader for the format.

I don't think anyone will find the time soon to do this so you would need to lead the effort to add GRF support to ObsPy. There are a few steps to this:

* Write `_is_grf()` and `_read_grf()` functions. The first should return `True`/`False` for any file that is passed to it based on whether it is a GRF or not. The second one should read a GRF file to an `obspy.Stream` object.
* These functions have to be registered in the root level `setup.py` file. At this point of time ObsPy will work with GRF.

To get started best look at some of the existing I/O plug-ins (https://github.com/obspy/obspy/tree/master/obspy/io) and just copy one and modify it. Once you got a basic version working we can help to polish and fully integrate it into ObsPy.

**Comment by megies** [comment]
@DominikStr you could maybe have a shot at this one.

@serdarkuyuk we would need an example file first, though.

**Comment by gbbofh** [comment]
I found a collection of example files on the site that hosts the documentation for the format. I am willing to give this a shot if there hasn't been any work on it.

**Comment by megies** [comment]
Sure, go ahead, I don't know of any ongoing efforts towards this.

**Comment by megies** [comment]
stale, closing.
