### ISSUE TITLE
Option to suppress output from evalresp

### ISSUE THREAD

**Issue by shicks-seismo** [obspy/obspy#2110]
Hi, when removing instrument response using remove_response, I get a bunch of FIR normalized warnings, which I'm not worried about as they refer to the FIR filter that isn't affecting my response correction. 
But a lot of these warnings appear, taking up lots of room in the terminal so I can't see the more useful information.
Would it be possible to somehow suppress output from remove_response / evalresp as a non-default option?

**Comment by krischer** [comment]
Yes this would be possible but would require some modifications in `evalresp` - the `hide_sensitivity_mismatch_warning` option is implemented in a similar way. Have a look: https://github.com/obspy/obspy/blob/f7363fbf20ff04daf29a9351b4a5f8d4e4abce56/obspy/core/inventory/response.py#L879

**Comment by shicks-seismo** [comment]
Thanks, @krischer. I had a look but haven't been able to get my head around it, so may need another hint or two.
Would we need to make a change to just the evalresp wrapper or the evalresp source code, too?

**Comment by krischer** [comment]
Yes of course. Sorry for being so short worded. This line

https://github.com/obspy/obspy/blob/57121a68adf2722902ba2a613e7d93a7049ef3d2/obspy/core/inventory/response.py#L1350

calls into a C function. Its function signature needs to be know for `ctypes` to work and is defined here:

https://github.com/obspy/obspy/blob/57121a68adf2722902ba2a613e7d93a7049ef3d2/obspy/signal/evrespwrapper.py#L238

And the actual function in C is here:

https://github.com/obspy/obspy/blob/57121a68adf2722902ba2a613e7d93a7049ef3d2/obspy/signal/src/evalresp/_obspy_wrapper.c#L54

This then calls into the rest of evalresp. So what you would have to do to conditionally silence the FIR normalization warning is to to add a new parameter to all of these and then find the corresponding code in evalresp to only print it if this parameters is true or false.

Hope this helps!

**Comment by shicks-seismo** [comment]
Thanks @krischer, I see what you mean now. I found the warning flag in resp_fctns.c
A silly novice question here, but if I make ad-hoc changes to these C functions in my own ObsPy installation, do I need to recompile them, or does this somehow happen when the wrapper is called?

**Comment by megies** [comment]
You need to recompile, e.g. by doing pip install again.

**Comment by shicks-seismo** [comment]
Ah ok, my installation is with anaconda, and I don’t see the evalresp src/ directory so I assume this isn’t included. I assume then the best option is to install a new obspy-dev environment, which should contain everything I need…?

**Comment by krischer** [comment]
You just need a C compiler (installing XCode or the cmd line dev tools for osx will do the trick). Then just `pip install -v -e .` in the ObsPy repository in a Python environment that does not have ObsPy and you should be good to go.

**Comment by Jollyfant** [comment]
By the way on my MacOSX system the file is stored under:

    obspy/build/temp.macosx-10.11-intel-2.7/obspy/signal/src/evalresp

**Comment by krischer** [comment]
yes - but the final shared ibrary is later copied to `obspy/obspy/lib` which is where ObsPy expects it to be.

**Comment by megies** [comment]
Pretty sure this was at least partially fixed by #2677?
