### ISSUE TITLE
Add Ubuntu 18.04

### ISSUE THREAD

**Issue by megies** [obspy/obspy#2123]
This is a reminder to add Ubuntu 18.04 to packaging which is supposed to be released today.

**Comment by krischer** [comment]
Works fine: http://tests.obspy.org/94070/

I ran it on a machine with a lot of memory but it did need a lot.

**Comment by krischer** [comment]
e3522781d24adad24e5cefa77aa1801861a4a628 changes a .deb package to make it work.

**Comment by megies** [comment]
Packages for Ubuntu 18.04 LTS "bionic" are up.
