### ISSUE TITLE
How skip the 512 firsts bits on mseed file with obspy

### ISSUE THREAD

**Issue by mike535** [obspy/obspy#2142]
Hi Obspy developers.
I need skip first 512 bytes in files mseed with obspy library.
similar to what the function seek() does.

Thanks by you help

**Comment by megies** [comment]
Open your file with `io.BytesIO` and use `seek` to move to your starting location, then give the `BytesIO` object to `obspy.read`.

**Comment by megies** [comment]
Also this seems more suited for asking on the users mailing list..
