### ISSUE TITLE
Cannot import function/method XYZ   (aka "the big rename" issues)

### ISSUE THREAD

**Issue by siosys** [obspy/obspy#2143]
I just installed Anaconda/obspy following the instructions at https://github.com/obspy/obspy/wiki/Installation-via-Anaconda

After running through the instructions and launching the python interpreter, I can import obspy, obspy.core, and obspy.core.utils. Trying to import gps2DistAzimuth from either of these entries returns an ImportError for gps2DistAzimuth. If I try to import from obspy.core.util.geodetics or obspy.core.util.geodetics.base it returns a ModuleNotFoundError for the geodetics module.

I've tried this on both python 2.7 and 3.6. conda version is 4.5.3, obspy version is 1.1.0. I've tried it on macOS 10.11, 10.12, and 10.13 and all return the same errors.

**Comment by kaspervanwijk** [comment]
In the latest version (1.1.0), you want to use gps2dist_azimuth
<https://docs.obspy.org/packages/autogen/obspy.geodetics.base.gps2dist_azimuth.html#obspy.geodetics.base.gps2dist_azimuth>

best,
kasper

Kasper van Wijk
Department of physics
University of Auckland
https://www.physics.auckland.ac.nz/people/kvan637

**Comment by megies** [comment]
@siosys you either skipped some major version and didn't update your obspy for more than two years or you overlooked those deprecation warnings when working on obspy 1.0.

In any case, please see..
 - https://github.com/obspy/obspy/wiki/What%27s-New-in-ObsPy-1.0#new-internal-structure and..
 - https://github.com/obspy/obspy/wiki/What%27s-New-in-ObsPy-1.1#deprecations-are-locked-and-loaded

Using IPython and tab completion it should be simple to figure out what functions/methods were renamed to, but if that doesn't work for you, you can search the 1.0.3 docs for the old function name (e.g. use https://docs.obspy.org/archive/1.0.3/search.html?q=gps2DistAzimuth) and then click on `[source]` at the right (e.g. leading to https://docs.obspy.org/archive/1.0.3/_modules/obspy/geodetics/base.html#gps2DistAzimuth) to see the deprecation and new name of the routine.
