### ISSUE TITLE
IRISWS (clients.iris): REST API change in boolean parameters

### ISSUE THREAD

**Issue by megies** [obspy/obspy#2144]
Preparing for 1.1.1RC1, I noticed there was a **change in REST API of IRISWS timeseries endpoint** (around Feb 2nd 2018 -- compare http://tests.obspy.org/?page=24&module=clients.iris, last good test: http://tests.obspy.org/92277/) which causes us some test fails on current `maintenance_1.1.x` branch.

The **boolean parameter `correct` could prior to that change be specified as a flag** `...&correct` which was interpreted as `...&correct=true`. This is also what the [docs](http://service.iris.edu/irisws/timeseries/1/) imply and all other boolean parameters (`demean`, `diff` etc.) still work the old way as well as flags.

@chad-iris can you please forward this issue to whoever is maintaining that WS? My feeling is that this change might be unintentional, but if it stays this way on server side we can easily adapt to it. Thanks!

---

Compare the following (only difference is the added `&correct`:

**This works:**

`http://service.iris.edu/irisws/timeseries/1/query?network=IU&station=ANMO&location=00&channel=BHZ&starttime=2005-01-01T00%3A00%3A00.000&endtime=2005-01-01T00%3A01%3A00.000&output=plot&demean&int&envelope`

**While this isn't working anymore:**

`http://service.iris.edu/irisws/timeseries/1/query?network=IU&station=ANMO&location=00&channel=BHZ&starttime=2005-01-01T00%3A00%3A00.000&endtime=2005-01-01T00%3A01%3A00.000&output=plot&demean&correct&int&envelope`

```
Error 400: Bad Request

The Timeseries webservice was unable to understand your request. Bad correct value:  (must be 'true' or 'false')

Usage details are available from http://service.iris.edu/irisws/timeseries/1

Request:
http://service.iris.edu/irisws/timeseries/1/query?network=IU&station=ANMO&location=00&channel=BHZ&starttime=2005-01-01T00%3A00%3A00.000&endtime=2005-01-01T00%3A01%3A00.000&output=plot&demean&correct&int&envelope

Request Submitted:
2018/05/09 11:58:36.680 GMT

Service Version:
ws-timeseries:1.5.2
li4:84
```

**Comment by bruce-iris** [comment]
(A) That was unintentional. I will fix it.
(B) That change was in response to confusion that a user was seeing in request that he had. I believe he was using correct=auto which doesn’t do what you might think.

Old logic:
correct=true (true)
correct (true)
correct=&lt;anything but true&gt; (false)

Current logic:
correct=true (true)
correct=false (false)
correct=&lt;anything but true or false&gt; (400 error)

Will change it to:
correct=true (true)
correct (true)
correct=false (false)
correct=&lt;anything but true or false&gt;  (400 error)

Sorry about that. 

Cheers
-Bruce irisws-timeseries dev.

**Comment by megies** [comment]
Thanks for the detailed clarification @bruce-iris. And no worries, I was just wondering about this sudden test fail we were seeing, I don't think that it affected a lot of our users and I'm glad that you can sort it out.

I'm closing this as resolved on server side.
