### ISSUE TITLE
Use one CI runner with different/non-UTF8 locale

### ISSUE THREAD

**Issue by megies** [obspy/obspy#2150]
We should change one CI test runner to use at least non-Latin alphabet or ideally a non UTF-8 locale to be able to catch problems on systems with different locales. See #2147 and #2148.

Travis has e.g. [Chinese UTF8 locales, it seems](https://github.com/travis-ci/travis-cookbooks/blob/4ef62935f9f21405bbc7b5e9023ff010410c172d/cookbooks/travis_build_environment/attributes/default.rb#L38), for non UTF8 we'd probably have to `localegen` them in CI.

**Comment by QuLogic** [comment]
Who uses non-UTF8 locales at this point?

**Comment by megies** [comment]
stale, closing.
