### ISSUE TITLE
massdownloader not finding stations

### ISSUE THREAD

**Issue by jwebster8** [obspy/obspy#2155]
If you run the code below, the massdownloader wont find any stations/data in the circular region.  However I know there are stations there with data, and in the bottom of attached code, I show that the normal fdsn  client.get_stations  returns what I expect.

Am I doing something wrong? Or is there something broken in the massdownloader?

```

import obspy
from obspy.clients.fdsn.mass_downloader import CircularDomain, Restrictions, MassDownloader
from obspy.clients.fdsn import Client
from obspy.core import UTCDateTime
from obspy.clients.fdsn.header import URL_MAPPINGS

lat = 39.883
lon = -88.901
minR = 0.0
maxR = 1.0


st = obspy.UTCDateTime(2014,1,1, 1,0,0)
et = st+(3600*24*14)       

# via the massdownloader
print('\n\n')
print('------------- MASSDOWNLOADER OUTPUT -------------------')
domain = domain = CircularDomain(latitude=lat, longitude=lon, minradius=minR, maxradius=maxR)
restrictions = Restrictions( starttime=st, endtime=et, network='GS', minimum_length=0, reject_channels_with_gaps=False, sanitize=False)

mdl = MassDownloader(providers=['IRIS'])
mdl.download(domain, restrictions, mseed_storage="tmp/waveforms", stationxml_storage="tmp/stations") 



#now via the regular fdsn
print('\n\n\n\n')
print('--------------- FDSN Client.getStations OUTPUT ----------' )
client = Client('IRIS')
inv = client.get_stations(network='GS', starttime=st, endtime=et, latitude=lat, longitude=lon, minradius=minR, maxradius=maxR)

print(inv)

```

Here is the output...

```
------------- MASSDOWNLOADER OUTPUT -------------------
[2018-05-21 17:25:02,308] - obspy.clients.fdsn.mass_downloader - INFO: Initializing FDSN client(s) for IRIS.
[2018-05-21 17:25:06,285] - obspy.clients.fdsn.mass_downloader - INFO: Successfully initialized 1 client(s): IRIS.
[2018-05-21 17:25:06,285] - obspy.clients.fdsn.mass_downloader - INFO: Total acquired or preexisting stations: 0
[2018-05-21 17:25:06,285] - obspy.clients.fdsn.mass_downloader - INFO: Client 'IRIS' - Requesting reliable availability.
[2018-05-21 17:25:06,461] - obspy.clients.fdsn.mass_downloader - INFO: Client 'IRIS' - Successfully requested availability (0.18 seconds)
[2018-05-21 17:25:06,467] - obspy.clients.fdsn.mass_downloader - INFO: Client 'IRIS' - Found 0 stations (0 channels).
[2018-05-21 17:25:06,468] - obspy.clients.fdsn.mass_downloader - INFO: Client 'IRIS' - No data available.
[2018-05-21 17:25:06,468] - obspy.clients.fdsn.mass_downloader - INFO: ============================== Final report
[2018-05-21 17:25:06,468] - obspy.clients.fdsn.mass_downloader - INFO: 0 MiniSEED files [0.0 MB] already existed.
[2018-05-21 17:25:06,468] - obspy.clients.fdsn.mass_downloader - INFO: 0 StationXML files [0.0 MB] already existed.
[2018-05-21 17:25:06,468] - obspy.clients.fdsn.mass_downloader - INFO: Client 'IRIS' - Acquired 0 MiniSEED files [0.0 MB].
[2018-05-21 17:25:06,468] - obspy.clients.fdsn.mass_downloader - INFO: Client 'IRIS' - Acquired 0 StationXML files [0.0 MB].
[2018-05-21 17:25:06,468] - obspy.clients.fdsn.mass_downloader - INFO: Downloaded 0.0 MB in total.



--------------- FDSN Client.getStations OUTPUT ----------
Inventory created at 2018-05-21T23:25:06.000000Z
	Created by: IRIS WEB SERVICE: fdsnws-station | version: 1.1.33
		    http://service.iris.edu/fdsnws/station/1/query?starttime=2014-01-01...
	Sending institution: IRIS-DMC (IRIS-DMC)
	Contains:
		Networks (1):
			GS
                Stations (12):
			GS.DEC01 (Heartland Borehole/Surface)
			GS.DEC02 (ADM Borehole/Surface)
			GS.DEC03 (Forest Parkway Borehole/Surface)
			GS.DEC04 (Sangamon Road Surface Site)
			GS.DEC05 (Apollo Drive Surface Site)
			GS.DEC06 (Neely Ave Surface Site)
			GS.DEC07 (Harrison Ave Surface Site)
			GS.DEC08 (Union Local 159 Surface Site)
			GS.DEC09 (Kile Street Surface Site)
			GS.DEC10 (Finch Street Surface Site)
			GS.DEC11 (Phillips Surface Site)
			GS.DEC12 (Boyd Road Surface Site)
		Channels (0):
```

**Comment by megies** [comment]
Your unlucky because of the default of `location_priorities` in the `Restrictions` class.. try something like `Restrictions(..., location_priorities=('', '00', '10', '01', '02'))` and it fetches the data.

@krischer, I don't full understand the reasoning of this (default) `location_priorities` setting. As you even mention in the docstring of `Restriction`, `"Location codes are arbitrary and there is no rule as to which location is best."` I totally agree and I would strongly suggest to change the default behavior to regard channels with *any* location code.

(Furthermore, I think it's usual to use `01`, `02` when incrementing location code, one more point why I don't understand the default of `location_priorities=("", "00", "10")`)

**Comment by jwebster8** [comment]
yep, that worked.  Thanks for the quick reply guys

**Comment by megies** [comment]
I'll reopen this, since I want to hear opinions on the `location_priorities` issue. I think it needs a change.

**Comment by krischer** [comment]
> @krischer, I don't full understand the reasoning of this (default) location_priorities setting. As you even mention in the docstring of Restriction, "Location codes are arbitrary and there is no rule as to which location is best." I totally agree and I would strongly suggest to change the default behavior to regard channels with any location code.
> 
> (Furthermore, I think it's usual to use 01, 02 when incrementing location code, one more point why I don't understand the default of location_priorities=("", "00", "10"))

Yes I think I agree with changing this to a better default. Accepting anything by default would probably be a bad idea as some stations have a very large number of locations and the mass downloader would then just download everything with the way things currently are.

How about expanding the default values to `["", "00", "10", "01", "02", "03", "20"]`? I'd be happy to add other locations codes as well.

**Comment by megies** [comment]
> the mass downloader would then just download everything with the way things currently are.

maybe that should be changed in the long run.. but yeah, low priority I guess


> How about expanding the default values to ["", "00", "10", "01", "02", "03", "20"]? I'd be happy to add other locations codes as well.

Much better than current situation, but also just a quick fix that doesn't really solve the underlying problem just works around it for some common cases.

**Comment by jwebster8** [comment]
For what it's worth, what I was expecting was that the default location (and channel) code would be '*' (everything), and that if someone wanted just a subset of the station's data, then they would specify what they wanted.

**Comment by krischer** [comment]
What are the `EP`, `S1`, `S3`, `T0`, and `2C` location code supposed to be?

**Comment by megies** [comment]
> As I cannot think of another solution I propose to just use the 20 most common location codes in the whole IRIS inventory:

Sounds good, and nice idea to just do statistics. For more crazed stats, we could multiply location codes by their encountered duration.. ;-)

**Comment by megies** [comment]
Hmm, maybe we move this to 1.2.0? Changes behavior a bit, and then we could do 1.1.1 now and people are supposed to move to 1.2.0 soonish anyway..

**Comment by megies** [comment]
> What are the EP, S1, S3, T0, and 2C location code supposed to be?

Interesting that there are so strange ones among the top list..

**Comment by krischer** [comment]
Okay - so `EP` seems to be either barometers, the clock phase, or some state of health channel, `S1`/`S3` either accelerometers. fiberoptic strain sensors, or synthetics seismograms,  `T0` strainmeters, and `2C` are accelerometers.

I'll not include these in the default list but only all the "numerical" codes and the empty one.

**Comment by krischer** [comment]
Dealt with in #2159.

**Comment by Jollyfant** [comment]
For good measure this is the result for EIDA:

    -- 46566
    00 15812
    10 1377
    01 847
    20 251
    90 185
    02 155
    XX 120
    03 106
    05 96
    80 88
    81 68
    04 65
    07 63
    BT 63
    SF 48
    06 47
    AH 35
    FH 33
    91 25
    60 21
    08 12
    15 11
    51 9
    09 8
    11 6
    V0 5
    30 4
    A1 4
    A0 3
    BH 3
    BZ 3
    12 2
    13 2
    14 2
    16 2
    17 2
    18 2
    19 2
    21 2
    22 2
    23 2
    31 2
    40 2
    41 2
    C0 2
    G0 2
    J0 2
    M0 2
    P0 2
    S0 2
    33 1
    36 1
    39 1
    43 1
    44 1
    45 1
    46 1
    A2 1
    C1 1
    D0 1
    M1 1
    V1 1

**Comment by krischer** [comment]
Cool :-) Seems the chosen set of location codes is also sensible for EIDA.
