### ISSUE TITLE
CSS format reading / file type detection

### ISSUE THREAD

**Issue by Keowne** [obspy/obspy#2160]
Hello,

Was advised on the mailing list to post this issue here.

I've been happily working with CSS format files generated by the Pisces package but have a small issue when trying to read them with ObsPy. Essentially, I get an unknown file format error using 'read' unless I specify what the data format is explicitly, i.e., st = read("file.wfdisc", format = "CSS"). 

Without specifying the format, the full traceback is:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-2-6eef146513fc> in <module>()
----> 1 st = read('/DEMO_data/2018001.DEMO.wfdisc')

<decorator-gen-146> in read(pathname_or_url, format, headonly, starttime, endtime, nearest_sample, dtype, apply_calib, check_compression, **kwargs)

~/anaconda3/lib/python3.6/site-packages/obspy/core/util/decorator.py in _map_example_filename(func, *args, **kwargs)
    299                         except IOError:
    300                             pass
--> 301         return func(*args, **kwargs)
    302     return _map_example_filename
    303 

~/anaconda3/lib/python3.6/site-packages/obspy/core/stream.py in read(pathname_or_url, format, headonly, starttime, endtime, nearest_sample, dtype, apply_calib, check_compression, **kwargs)
    233         pathname = pathname_or_url
    234         for file in sorted(glob(pathname)):
--> 235             st.extend(_read(file, format, headonly, **kwargs).traces)
    236         if len(st) == 0:
    237             # try to give more specific information why the stream is empty

<decorator-gen-147> in _read(filename, format, headonly, **kwargs)

~/anaconda3/lib/python3.6/site-packages/obspy/core/util/decorator.py in uncompress_file(func, filename, *args, **kwargs)
    209     else:
    210         # no compressions
--> 211         result = func(filename, *args, **kwargs)
    212     return result
    213 

~/anaconda3/lib/python3.6/site-packages/obspy/core/stream.py in _read(filename, format, headonly, **kwargs)
    275     """
    276     stream, format = _read_from_plugin('waveform', filename, format=format,
--> 277                                        headonly=headonly, **kwargs)
    278     # set _format identifier for each element
    279     for trace in stream:

~/anaconda3/lib/python3.6/site-packages/obspy/core/util/base.py in _read_from_plugin(plugin_type, filename, format, **kwargs)
    390                 break
    391         else:
--> 392             raise TypeError('Unknown format for file %s' % filename)
    393     else:
    394         # format given via argument

TypeError: Unknown format for file /DEMO_data/2018001.DEMO.wfdisc
```
It seems the automatic file type detection isn't working, something I note was in a thread about 3 years ago (http://lists.swapbytes.de/archives/obspy-users/2015-February/001642.html). However, I'm not sure if this is ObsPy related, or Pisces related.

I've attached files representing a 30 second example here.

System details:
ObsPy 1.1.0, installed via Anaconda Navigator, running on OSX 10.11.6 with Python version is 3.6.4.

Many thanks.

[DEMO_data.zip](https://github.com/obspy/obspy/files/2043136/DEMO_data.zip)

**Comment by megies** [comment]
@DominikStr you could have a look at this one maybe? Seems like the `is_css()` routine is not properly recognizing this file as CSS.

**Comment by DominikStr** [comment]
The example given with `st = read('/DEMO_data/2018001.DEMO.wfdisc')` works perfectly for me without specifyingthe file format.
The only thing I cant open are the files in the folder "DEMO_data\w" individual. I think these contain the trace informations. So this should not be the problem.

**Comment by megies** [comment]
Alright, thanks for checking @DominikStr! Closing this as invalid then. @Keowne let us know if you still have problems with this. I just noticed the strange path as well `'/DEMO_data/2018001.DEMO.wfdisc'` maybe that was the problem...?

> The only thing I cant open are the files in the folder "DEMO_data\w" individual

I think this is how the CSS reader works, you point it to the "metadata" wfdisc file which contains info where the actual data files are stored. So should be fine.

**Comment by Keowne** [comment]
Thanks for checking this issue. 

My original description was for using ObsPy 1.1.0. I can still replicate the problem there and the issue stemmed from the assert lines in `_is_css()`, not the directory structure.

 Specifically:

`assert(line[26:27] == b".")` and
`assert(line[71:72] == b".")`

I can see however that in ObsPy version 1.1.1 that these lines have been changed to:

`assert(line[26:28] == b".")` and
`assert(line[71:73] == b".")`

Those changes mean that I don't get the same problem as before, so this fortunately has been resolved outside of this ticket (from the looks of things, in [ticket 2162](https://github.com/obspy/obspy/pull/2162)).

**Comment by megies** [comment]
> Those changes mean that I don't get the same problem as before, so this fortunately has been resolved outside of this ticket (from the looks of things, in [ticket 2162](https://github.com/obspy/obspy/pull/2162)).

Very nice, thanks for checking and reporting back @Keowne! :tada:
