### ISSUE TITLE
UTCDateTime microseconds

### ISSUE THREAD

**Issue by bvicic** [obspy/obspy#2161]
Dear all.
I don't know if this was already discussed, but I have a problem with UTCDateTime.

> from obspy import UTCDateTime
> ti = UTCDateTime('2016-03-06T19:11:18.052634Z')
> ti.microsecond
> 52634

it is the same if I read the event.origins[0].time.microsecond

As you can see, the 0 in .microsecond is lost. Is there a way around this?
Thanks!

**Comment by ThomasLecocq** [comment]
Well, no. Because the integer amount of microseconds is 52634.

I guess you want it formatted, use `` "%.6f"%(ti.microsecond/1e6) ``, but that would be "seconds" technically.

For questions like this please use the mailing list next time.
