### ISSUE TITLE
Type Error while reading .resp file with read_inventory

### ISSUE THREAD

**Issue by fnwolf** [obspy/obspy#2170]
Dear all, 

this is my first issue, i'll do my best to give all the information needed.
I try to read a response file in RESP format using obspy.read_inventory, basically like this:

`import obspy 
inv = obspy.read_inventory('/run/media/felixw/workdisc_1/6D6-Trillium-250sps.resp', format='RESP')`

This leads to the following error message: 

File "/home/felixw/anaconda3/lib/python3.6/site-packages/obspy/io/xseed/parser.py", line 1127, in get_response_for_channel
stages[b.stage_sequence_number].append(b)

TypeError: unhashable type: 'list'

I tried converting the .resp file into a dataless seed and read that one - converting works, read_inventory gives the same error. You can find the .resp file here: https://www.dropbox.com/s/644r9lsdqv0larx/6D6-Trillium-250sps.resp?dl=0 (couldn't upload it directly to this issue).

Do you have any idea, what i could do to solve that? That would be a great help to me, thanks a lot!

Some information on my ObsPy and Python: i installed both via anaconda3, using Python 3.6 and ObsPy 1.1 on a Fedora 27 computer.

Best wishes and again, thanks for helping,
Felix

**Comment by megies** [comment]
I can confirm the problem and it indeed seems like a bug to me..

**Comment by fnwolf** [comment]
Good to hear that you can recreate the error...
Nevertheless, i just now managed to create a workaround:
convert the .resp file to a dataless seed (I used PDCC) and then do the following:

`from obspy.io.xseed import Parser
from obspy.core import UTCDateTime

dataless = Parser('/run/media/felixw/workdisc_1/6D6-Trillium-250sps.seed')
seed_id = 'BHZ'  # channel identifier
inv = dataless.get_paz(seed_id, UTCDateTime("2018-06-13")) # this collects all information needed as metadata for PPSD`

This is a bit crude to do but now I can create the ppsd-plots I aimed for

**Comment by krischer** [comment]
Dealt with in #2189.

I think the file is not fully compliant with how most other RESP files look but the next ObsPy version will read it just fine. Please see the other issue for details.
