### ISSUE TITLE
Empty QuantityError instances changes in roundtrip to disk 

### ISSUE THREAD

**Issue by d-chambers** [obspy/obspy#2173]
obspy 1.1.0, ubuntu 16.04, python 3.6

It seems saving a simple event object to disk (with a single empty origin) and then loading causes the loaded event and original event not to evaluate to equal. For example:

```python
import obspy
import obspy.core.event as ev

# create event and save to disk
origin = ev.Origin(time=obspy.UTCDateTime('2016-01-01'))
event = ev.Event(origins=[origin])
event.write('temp.xml', 'quakeml')

# read from disk
event2 = obspy.read_events('temp.xml')[0]

# saved and loaded event should be equal
print(event2 == event)  # False

# depth_errors are no longer equal
print(event2.origins[0].depth_errors == event.origins[0].depth_errors)  # False

# event has a QuantityError with all None values and event2 has None 
print(type(event.origins[0].depth_errors))  # QuantityError
print(type(event2.origins[0].depth_errors))  # NoneType

# setting event.origins[0].depth_errors to None fixes the problem
event.origins[0].depth_errors = None
print(event == event2)  # True
```

Not sure but this may be related to #2166?

**Comment by megies** [comment]
Feels like it should be `None` in both cases. But it might hurt people if we change it like that..

**Comment by megies** [comment]
> Not sure but this may be related to #2166?

It's slightly related but still a different issue.

**Comment by krischer** [comment]
How about adding this

```python
    def __eq__(self, other):
        if other is None and bool(self) is False:
            return True
        return super(QuantityError, self).__eq__(other)
```

to the `QuantityError` class? Even though this might not be entirely clean Python it is semantically what we want and it would solve this particular issue.

If this is not acceptable for some reason I would also set it to `None` during the reading process.

**Comment by d-chambers** [comment]
Without thinking too hard about this, the "most correct" thing to do is probably set the `depth_errors` to `None` by default and not init an empty instance of `QuantityError`, anyond know why it is not this way? @megies is probably right though, this could break some codes so it may be better to use @krischer 's fix. It's more pythonic to use `not bool(self)` rather than `is` though I think.

**Comment by krischer** [comment]
Dealt with in #2185

**Comment by megies** [comment]
I'm not entirely sure I really like the "solution", it really feels non-Pythonic and covers one sloppiness with another sloppiness. But hey, at least it likely won't break codes... so, 'so what' I guess.

**Comment by krischer** [comment]
I initially felt the same but I'm now okay with it. It still fails a comparison with "is" but an "==" comparison now works. As "None" is Pythons null value is seems fair to compare equal to a quantity error which has only null values.

**Comment by megies** [comment]
> As "None" is Pythons null value is seems fair to compare equal to a quantity error which has only null values.

For me an empty quantity error feels more like an empty list or empty dict. But hey, not worth it to put toom uch thought or discussion into this. Let's just stick with the newly implemented "fix" if OP is happy with it. :-)

**Comment by d-chambers** [comment]
@megies I agree, it is a bit sloppy but I don't have a strong opinion either way. 
The main thing we need to ensure (and we probably need more tests for) is that any valid catalog saved to disk and reloaded will always evaluate to equal to the original catalog.
