### ISSUE TITLE
[MassDownloader] String Template: do not require all the fields

### ISSUE THREAD

**Issue by paride** [obspy/obspy#2174]
Currently the "String Template" option for `mseed_storage` requires all the fields to be present in the string (`{network}`, `{station}`, `{location}`, `{channel}`, `{starttime}`, and `{endtime}`). Sometimes it can be useful to define only some of them. Practical case: while working with a single station I didn't define `{network}` and `{station}`, and the substitution didn't work.

What about changing the ANDs to ORs here: https://github.com/obspy/obspy/blob/master/obspy/clients/fdsn/mass_downloader/utils.py#L545 ?

The same goes for `stationxml_storage`: https://github.com/obspy/obspy/blob/master/obspy/clients/fdsn/mass_downloader/utils.py#L489.

**Comment by megies** [comment]
Sounds totally reasonable to me.

I'd make it..

```python
elif any('{%s}' % key  in str_or_fct for key in ('network', 'station', ...)):
```

**Comment by paride** [comment]
This will have to be tackled differently: https://github.com/obspy/obspy/pull/2178#issuecomment-401127129.

**Comment by ThomasLecocq** [comment]
Are we still waiting for this for 1.2.0 ? @paride @krischer

**Comment by krischer** [comment]
I'd argue its not urgent - if we have time we do it for 1.2.0, otherwise we punt it to the next release.

**Comment by paride** [comment]
I am moving away from seismology, so I doubt I will work on this any soon. Feel free to close the issue if you prefer.

**Comment by megies** [comment]
I think I'll close this. It's not urgent and users should just stick to the default usage of having all items in the string.
