### ISSUE TITLE
Installation issue on MacOS High Sierra

### ISSUE THREAD

**Issue by skedar12** [obspy/obspy#2182]
I am trying to install obspy on my MacOS High Sierra laptop (10.13.5) via Anaconda following the obspy installation instruction.  I am getting the following the error message below.  Could not find helpful tip on line.  Any suggestions?

Thanks!

Sharon

$ conda install obspy
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

`$ /anaconda3/bin/conda install obspy`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/anaconda3
              CONDA_SHLVL=0
                  MANPATH=/opt/passcal/man
                     PATH=/anaconda3/bin:/Users/skedar/anaconda3/bin:/Library/Frameworks/Python.
                          framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versio
                          ns/3.6/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin
                          :/usr/sbin:/sbin:/opt/X11/bin:/opt/passcal/bin:/opt/passcal/other/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /Users/skedar/.condarc
 populated config files : /Users/skedar/.condarc
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : /anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/conga-forge/osx-64
                          https://conda.anaconda.org/conga-forge/noarch
                          https://conda.anaconda.org/python/osx-64
                          https://conda.anaconda.org/python/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /anaconda3/pkgs
                          /Users/skedar/.conda/pkgs
       envs directories : /anaconda3/envs
                          /Users/skedar/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Darwin/17.6.0 OSX/10.13.5
                UID:GID : 1840527711:703763885
             netrc file : None
           offline mode : False

V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conga-forge/noarch/repodata.json>
Elapsed: 00:00.151154
CF-RAY: 4311c7c2ac885408-LAX

The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/conga-forge

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.

A reportable application error has occurred. Conda has prepared the above report.

**Comment by krischer** [comment]
Hmm - I've never seen this error before. I would assume it is a `conda` error. Can you install any other package from `conda-forge`?  Maybe its also just some temporary issue. The one thing that sticks out to me is that you have two `conda` installations in your `PATH`: `/anaconda3/bin` and `/Users/skedar/anaconda3/bin`. There are also many other potential Python installation in your `PATH` - this might really have some unexpected consequences.

If you cannot install other packages, maybe try reinstalling your conda installation or contact the conda guys. If ObsPy is the culprit, please get back to us.

**Comment by skedar12** [comment]
Thanks.  I will follow up on your suggestions and with Anaconda.  Stay tuned...

**Comment by skedar12** [comment]
Success!  Uninstalled all versions of Anaconda, and reinstalled per the obspy instructions.

Many thanks
