### ISSUE TITLE
Cartopy local projection for south hemisphere. 

### ISSUE THREAD

**Issue by seballgeyer** [obspy/obspy#2193]
Hi, 
There is a misbehavior on the local projection option on the South hemisphere using cartopy:

Test code as follow:

```
import matplotlib.pyplot as plt
import obspy
from obspy.clients.fdsn import Client
auspass = Client("http://auspass.edu.au:8080")
station = auspass.get_stations(network='*',station='*',starttime=obspy.UTCDateTime('1950-01-01'),endtime=obspy.UTCDateTime())
station.plot(projection='local', color_per_network=True)
```

**The fix is the following:**
In obspy/imaging/maps.py (line 618 --  620)
```
        proj_kwargs['central_latitude'] = lat_0
        proj_kwargs['central_longitude'] = lon_0
        proj_kwargs['standard_parallels'] = [lat_0,lat_0] #Line to add to have the same behavior than Basemap
        proj = ccrs.AlbersEqualArea(**proj_kwargs)
```

Thanks

Sebastien

**Comment by seballgeyer** [comment]
Hi

The FDSNWS server will be a long term server. We are just starting to import data into it. We will inform FDSN about it in a near future. 

Cheers, 

Sebastien

**Comment by megies** [comment]
Fix looks good to me on a quick glance..

There's still behavior discrepancy in default of station labels and missing lat/lon ticklabels.. but no idea about that, never touched the cartopy versions of the map code..

## Basemap
![basemap](https://user-images.githubusercontent.com/1842780/44259614-4d03b600-a212-11e8-831c-9dacedfffd26.png)

## Cartopy Before
![cartopy](https://user-images.githubusercontent.com/1842780/44259634-5db42c00-a212-11e8-9440-51439c7d4641.png)

## Cartopy After
![cartopy](https://user-images.githubusercontent.com/1842780/44259610-49702f00-a212-11e8-80d2-2e4234a3705a.png)

**Comment by seballgeyer** [comment]
I might be able to provide the modification for the lat Lon ticklabels and the station labels. 
I will provide it early next week. 

Cheers, 

--
Sébastien Allgeyer
Post-doctoral Fellow
Research School of Earth Science
ANU College of Physical and Mathematical Sciences
The Australian National University
Canberra 0200 Australia
sebastien.allgeyer@anu.edu.au

**Comment by megies** [comment]
> The FDSNWS server will be a long term server. We are just starting to import data into it. We will inform FDSN about it in a near future.

OK, cool. I'll add it to our list then, so that it's included in next release..
