### ISSUE TITLE
problem writing segy file: maximum number of traces (too large number in header field)

### ISSUE THREAD

**Issue by superzappie** [obspy/obspy#2194]
Hello,
I am encountering the problem where I can't write all my traces to a segy file using obspy. Is there any way around this problem; can I still write segy files with more than 32767 traces?

In another thread I found: 
https://github.com/obspy/obspy/issues/1393
a similar problem arose, then it was about the amount of samples within a trace. 
A minimalistic working example is provided below, as well as the error message. 
As a note, I was able to read in segy files with more than 32767 traces. 
Thanks in advance. 

error: short format requires (-32768) <= number <= 32767

```python
import numpy as np
from obspy import Trace, Stream
import sys
from obspy.io.segy.segy import SEGYTraceHeader, SEGYBinaryFileHeader
from obspy.core import AttribDict

stream = Stream()

for i in range(32768):
    trace=Trace(data=np.array([1,2,3,4],dtype='float32'))
    trace.stats.delta = 0.000125
    if not hasattr(trace.stats,'segy.trace_header'):
        trace.stats.segy={}
    trace.stats.segy.trace_header = SEGYTraceHeader()
    stream.append(trace)

stream.stats = AttribDict()
stream.stats.binary_file_header = SEGYBinaryFileHeader()

stream.write("migrated_infilled.sgy", format="SEGY", data_encoding=1,
             byteorder=sys.byteorder)
```

**Comment by krischer** [comment]
The issue arises from the fact that upon writing SEG-Y data ObsPy writes the "Number of data traces per ensemble" field in the binary file header and sets it to the number of traces. This field is (according to the documentation) mandatory for prestack data. Its a signed 2-byte integer (its also not really clear if some integers in SEG-Y can be unsigned so we currently opt for maximal compatibility) so the largest number it can represent is 2^15-1 = 32767.

The SEG-Y documentation is unfortunately really vague about what exactly that means but that is what we are using right now. If this can be interpreted in a different way I'd be happy to change it and then ObsPy would happily write larger files (it can already read arbitrary sized SEG-Y files).

Let me know what you think.

**Comment by superzappie** [comment]
Thank you for your quick reaction. Indeed, setting:
stream.stats.binary_file_header.number_of_data_traces_per_ensemble=1
solves the problem. Writing the number of traces to this field is not necessary, in my case at least. Might have been nice if the exception somehow pointed me towards this field.

**Comment by krischer** [comment]
> Might have been nice if the exception somehow pointed me towards this field.

That's a good idea. I implemented it in #2196.

Aside from that: Do you have any insight into what `stream.stats.binary_file_header.number_of_data_traces_per_ensemble` actually is supposed to represent. Can we safely not set it to get around this limitation?

**Comment by johollow** [comment]
> But even then, there are multiple fields in the binary header where the number of samples could be located.

It is important to record the number of samples because without that information the boundaries between each trace are ambiguous. The number of traces in the file is not typically recorded anywhere. It may be inferred from the size of the file if every trace is the same length.

I asked around out of curiosity, and an "ensemble" as it tuns out was originally intended to mean a collection of traces that came from the same shot in active source acquisition. Sometimes the word is used to mean other groupings of traces that are similar for some reason, for example sharing the same offset between source and receiver. It was not intended to mean the number of traces in the file.

**Comment by superzappie** [comment]
I guess my last reply I talked about the number of samples in a trace, while the thread was originally about the number of traces. Yes, the number of samples in a trace is important to record in the file header. In the upcoming segy rev2, problems with overflows are adressed by setting new fields with more bytes for both numner of traces and number of samples in a trace. Right now I have script that sets the number of data traces per ensemble to 1, then manually overwrite is using something like outfile.seek(321?)  and write a 0 or anything that makes sense to evade the raise error.

**Comment by superzappie** [comment]
I guess my last reply I talked about the number of samples in a trace, while the thread was originally about the number of traces. Yes, the number of samples in a trace is important to record in the file header. In the upcoming segy rev2, problems with overflows are adressed by setting new fields with more bytes for both numner of traces and number of samples in a trace. Right now I have script that sets the number of data traces per ensemble to 1, then manually overwrite is using something like outfile.seek(321?)  and write a 0 or anything that makes sense to evade the raise error.

**Comment by megies** [comment]
#2196 was merged and if I understand correctly nothing much else can be done for this issue? Can we close this ticket?

**Comment by megies** [comment]
I think there's nothing more we can do here besides what was done in #2196.
