### ISSUE TITLE
obspy.io.seiscomp.inventory._read_sc3ml issue

### ISSUE THREAD

**Issue by kocum1** [obspy/obspy#2202]
When I try to read  xml file of Seiscomp3, I get this error.

    _read_float_var(temp / channel.sample_rate, ClockDrift)
    TypeError: unsupported operand type(s) for /: 'NoneType' and 'SampleRate'

What should I do to solve this problem?

**Comment by krischer** [comment]
Can you upload the file so we can diagnose the problem?

**Comment by megies** [comment]
Looks like it is in maintenance branch as well.. see #1993?

**Comment by kocum1** [comment]
[ALIG.xml.zip](https://github.com/obspy/obspy/files/2232337/ALIG.xml.zip)

Here is the xml file.

**Comment by Jollyfant** [comment]
The file `GO.GHRG` can be read with the appropriate version of ObsPy. Not sure if this fix has already been merged, but it has been patched.

`GO.ALIG` is missing a the sample rate numerator in the `HHE` component.

    <sampleRateDenominator>1</sampleRateDenominator>

And for the other channels:

    <sampleRateNumerator>100</sampleRateNumerator>
    <sampleRateDenominator>1</sampleRateDenominator>

While the sample numerator is an optional property in the schema. What should we do if it is missing? Throw an exception?

**Comment by megies** [comment]
The missing numerator is forbidden by the SC3ML schema (only checked 0.10 xsd though), so it's a broken file.

```xml
 893   <xs:complexType name="Decimation">
 894     <xs:sequence>
 895       <xs:element name="analogueFilterChain" type="scs:Blob" minOccurs="0" maxOccurs="1"/>
 896       <xs:element name="digitalFilterChain" type="scs:Blob" minOccurs="0" maxOccurs="1"/>
 897     </xs:sequence>
 898     <xs:attribute name="sampleRateNumerator" type="xs:integer" use="required"/>
 899     <xs:attribute name="sampleRateDenominator" type="xs:integer" use="required"/>
 900   </xs:complexType>

```


The other issue seems fixed reading through the above comments.

So closing this, please feel free to reopen should the issue persist on current mainentance and/or master branch.
