### ISSUE TITLE
unable to read seed or mseed downloaded from IRIS

### ISSUE THREAD

**Issue by cthouser** [obspy/obspy#2203]
Hi, I can read mseed that has been created for obspy tutorials (see below), but I cannot read seed or mseed that I downloaded from IRIS.  I extracted data from IRIS via web browser download and direct via ftp, both failed.  

>>> st = read("IV_BOB.mseed")
>>> st
<obspy.core.stream.Stream object at 0x1a1519d630>
>>> print(st)
3 Trace(s) in Stream:
IV.BOB..BHE | 2011-03-11T05:45:14.325000Z - 2011-03-11T06:46:27.675000Z | 20.0 Hz, 73468 samples
IV.BOB..BHN | 2011-03-11T05:45:08.415000Z - 2011-03-11T06:46:26.115000Z | 20.0 Hz, 73555 samples
IV.BOB..BHZ | 2011-03-11T05:45:08.445000Z - 2011-03-11T06:46:29.295000Z | 20.0 Hz, 73618 samples
>>> st2 = read("day1test2.315034.seed")
/Users/chouser/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/io/mseed/headers.py:828: InternalMSEEDWarning: readMSEEDBuffer(): Record starting at offset 3584 is not valid SEED. The rest of the file will not be read.
  warnings.warn(_w, InternalMSEEDWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-31>", line 2, in read
  File "/Users/chouser/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/util/decorator.py", line 301, in _map_example_filename
    return func(*args, **kwargs)
  File "/Users/chouser/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/stream.py", line 248, in read
    raise Exception("Cannot open file/files: %s" % pathname)
Exception: Cannot open file/files: day1test2.315034.seed

Here is the info of the data download
===============================================================================
day1test.721106.tar.mseed  Jul 26 15:12, 630 KBytes
SEED Format version: 2.4
Volume Label: day1test
Seed volume span from 2010,010,08:23:45.000000 -- 2010,010,16:13:00.000000
Stations: ANMO
Channels: LDO LFZ LH1 LH2 LHZ LN1 LN2 LNZ LWD LWS

I am running Python 3.6.5 in the obspy environment.  I installed it using anaconda.  Running MacOS 10.13.4 High Sierra.

(obspy) dhcp9-132:seis_pds chouser$ which python3
/Users/chouser/anaconda3/envs/obspy/bin/python3
(obspy) dhcp9-132:seis_pds chouser$ python3 -V
Python 3.6.5

I also tried in ipython and had the same error.

Thanks,

Christine

**Comment by cthouser** [comment]
I was testing different files and grabbed the wrong info, so there is a mismatch.

The file in the example: day1test2.315034.seed  is full seed.

Its info is: 
===============================================================================
day1test2.315034.seed  Jul 27 11:10, 664 KBytes
SEED Format version: 2.4
Volume Label: day1test2
Seed volume span from 2010,010,08:23:45.000000 -- 2010,010,16:13:00.000000
Stations: ANMO
Channels: LDO LFZ LH1 LH2 LHZ LN1 LN2 LNZ LWD LWS

I had the same error with seed and mseed downloaded from IRIS.

Thanks

**Comment by megies** [comment]
Can you upload the file you're having problems with somewhere or attach it to a comment?

**Comment by cthouser** [comment]
Here are the seed file and the mseed file in a zip file.  I downloaded them using the following breakfast requests from the IRIS website http://ds.iris.edu/ds/nodes/dmc/forms/breqfast-request/

day1test2.315034.seed  Jul 27 11:10, 664 KBytes
SEED Format version: 2.4
Volume Label: day1test2
Seed volume span from 2010,010,08:23:45.000000 -- 2010,010,16:13:00.000000
Stations: ANMO
Channels: LDO LFZ LH1 LH2 LHZ LN1 LN2 LNZ LWD LWS

day1test.721106.tar.mseed  Jul 26 15:12, 630 KBytes
SEED Format version: 2.4
Volume Label: day1test
Seed volume span from 2010,010,08:23:45.000000 -- 2010,010,16:13:00.000000
Stations: ANMO
Channels: LDO LFZ LH1 LH2 LHZ LN1 LN2 LNZ LWD LWS


[iris_files.zip](https://github.com/obspy/obspy/files/2292369/iris_files.zip)

**Comment by megies** [comment]
> I downloaded them using the following breakfast requests from the IRIS website http://ds.iris.edu/ds/nodes/dmc/forms/breqfast-request/

since you're using obspy.. why not download via FDSNWS Client?

**Comment by megies** [comment]
> day1test2.315034.seed Jul 27 11:10, 664 KBytes

seems like an OK dataless file



> day1test.721106.tar.mseed Jul 26 15:12, 630 KBytes

seems like an OK tar file with both dataless and miniseed data packed into it, just the suffix is misleading


Really, just use our fdsnws client and you get the data without confusion what file formats you specified during your original request using some other tools..

**Comment by megies** [comment]
I don't see a problem with those two files, so closing.. feel free to reopen if I'm mistaken

**Comment by cthouser** [comment]
In the future I plan to use obspy to download data directly.  I have been asked to test data from a new seismometer and couldn't get obspy to read the files.  I could not tell if the problem was with the files or obspy, so I tried these test files I downloaded from IRIS and could not open them either with the error that it is not valid seed.  Can you get the obspy "read" command to work for the day1test.721106.tar.mseed or day1test2.315034.seed files?

**Comment by megies** [comment]
> Can you get the obspy "read" command to work for the day1test.721106.tar.mseed

Like mentioned this is a tar archive and the ".mseed" suffix is misleading. You need to untar the file, it is a tar archive containing two files actually, one dataless SEED and one miniSEED.



> or day1test2.315034.seed files?

Like stated above already, it seems to me this is a dataless SEED file, so it contains station metadata and you read it using obspy's `read_inventory()` routine.
