### ISSUE TITLE
Default water-level in signal.invsim.simulate_seismometer vs. tr.remove_response

### ISSUE THREAD

**Issue by shicks-seismo** [obspy/obspy#2208]
Just wondering why the default water level in simulate_seismometer is 600.0, but in remove_response it is 60.0.
Is this intended, or is there a typo here with the decimal point position?

**Comment by megies** [comment]
600 is way too high, I think and if I remember correctly, we just decided to not change the old default to not alter behavior but when adding the new response removal methods we put a more useful default value.
