### ISSUE TITLE
remove response from Knet

### ISSUE THREAD

**Issue by serdarkuyuk** [obspy/obspy#2209]
I am trying to remove the response from K-net traces. It seems Obspy cannot handle. Do anyone know how?

**Comment by megies** [comment]
> It seems Obspy cannot handle. Do anyone know how?

Yes, your problem is exactly that...   uhm, wait, actually I just noticed I'm not a psychic. But maybe adding information to your question might be able to help us help you. :stuck_out_tongue_winking_eye:

**Comment by serdarkuyuk** [comment]
This is how I handle it...

calib = st[0].stats.calib
a=st[0].detrend()
a[0].data=a[0].data*calib

The response in Knet is just a multiplication with one number ...

**Comment by megies** [comment]
> The response in Knet is just a multiplication with one number ...

Does Knet distribute proper metadata in a file format accepted by the international seismo community, e.g. dataless SEED or StationXML? I think it is strange to distribute data with the frequency dependency of the instrument already corrected (at least assuming there is one -- I know only very, very few instrument types that do not have one), but even so, a plain frequency-independent scaling can and should be represented in one of the standard seismological metadata formats..

That point aside, if you have the necessary info in `trace.stats.calib` (but not in a proper metadata file), there is nothing wrong with doing it like you do.

**Comment by serdarkuyuk** [comment]
For those who do not know about knet data, here is the info...
http://www.kyoshin.bosai.go.jp/kyoshin/man/knetform_en.html
there is scale factor in line 14 that needs to be multiplied.
I think all the data in Knet are already response corrected, so you won't find a metadata as you expect in seed etc...
cheers

**Comment by megies** [comment]
Actually, I saw we even have a kwarg for this purpose: http://docs.obspy.org/master/packages/autogen/obspy.core.stream.read.html?highlight=apply_calib

So you could have obspy apply that calibration factor immediately when reading the data.

There's only very few waveform file formats that store a calibration factor alongside the raw data, so this switch is not advertized a lot, and personally I would not be very comfortable to use it across arbitrary data sets, rather only with very specific data like in your case.

**Comment by serdarkuyuk** [comment]
Wow, I learn one more thing... thank you...
