### ISSUE TITLE
NotImplementedError: Reftek data encoding 'b'32'' not implemented yet

### ISSUE THREAD

**Issue by thanosvrat** [obspy/obspy#2214]
-  ObsPy version 1.1.0, Python version 3.6.6 and Platform Windows 8.1 x64
  -  ObsPy and Python installed via anaconda
  -  If possible please supply a short, self contained, correct example that
     demonstrates the issue.

```
st_ref = obspy.read(r"C:\Users\toshiba\Desktop\Test\062919800_00917A30")

C:\ProgramData\Anaconda3\envs\obspy\lib\site-packages\obspy\io\reftek\core.py:157: UserWarning: Detected permuted packet sequence, sorting.
  warnings.warn(msg)
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-4-57cdee3e239a> in <module>()
      1 # Read in all ref files from one instrument
----> 2 st_ref = obspy.read(r"C:\Users\toshiba\Desktop\Test\062919800_00917A30")

<decorator-gen-156> in read(pathname_or_url, format, headonly, starttime, endtime, nearest_sample, dtype, apply_calib, check_compression, **kwargs)

C:\ProgramData\Anaconda3\envs\obspy\lib\site-packages\obspy\core\util\decorator.py in _map_example_filename(func, *args, **kwargs)
    299                         except IOError:
    300                             pass
--> 301         return func(*args, **kwargs)
    302     return _map_example_filename
    303 

C:\ProgramData\Anaconda3\envs\obspy\lib\site-packages\obspy\core\stream.py in read(pathname_or_url, format, headonly, starttime, endtime, nearest_sample, dtype, apply_calib, check_compression, **kwargs)
    233         pathname = pathname_or_url
    234         for file in sorted(glob(pathname)):
--> 235             st.extend(_read(file, format, headonly, **kwargs).traces)
    236         if len(st) == 0:
    237             # try to give more specific information why the stream is empty

<decorator-gen-157> in _read(filename, format, headonly, **kwargs)

C:\ProgramData\Anaconda3\envs\obspy\lib\site-packages\obspy\core\util\decorator.py in uncompress_file(func, filename, *args, **kwargs)
    209     else:
    210         # no compressions
--> 211         result = func(filename, *args, **kwargs)
    212     return result
    213 

C:\ProgramData\Anaconda3\envs\obspy\lib\site-packages\obspy\core\stream.py in _read(filename, format, headonly, **kwargs)
    275     """
    276     stream, format = _read_from_plugin('waveform', filename, format=format,
--> 277                                        headonly=headonly, **kwargs)
    278     # set _format identifier for each element
    279     for trace in stream:

C:\ProgramData\Anaconda3\envs\obspy\lib\site-packages\obspy\core\util\base.py in _read_from_plugin(plugin_type, filename, format, **kwargs)
    410         raise TypeError(msg % (format_ep.name, ', '.join(eps)))
    411     # read
--> 412     list_obj = read_format(filename, **kwargs)
    413     return list_obj, format_ep.name
    414 

C:\ProgramData\Anaconda3\envs\obspy\lib\site-packages\obspy\io\reftek\core.py in _read_reftek130(filename, network, location, component_codes, headonly, verbose, **kwargs)
    100             network=network, location=location,
    101             component_codes=component_codes, headonly=headonly,
--> 102             verbose=verbose)
    103         return st
    104     except Reftek130UnpackPacketError:

C:\ProgramData\Anaconda3\envs\obspy\lib\site-packages\obspy\io\reftek\core.py in to_stream(self, network, location, component_codes, headonly, verbose)
    250                        "open an issue on GitHub and provide a small (< 50kb) "
    251                        "test file.").format(eh.data_format)
--> 252                 raise NotImplementedError(msg)
    253             header = {
    254                 "network": network,

NotImplementedError: Reftek data encoding 'b'32'' not implemented yet. Please open an issue on GitHub and provide a small (< 50kb) test file.
```

I followed the guidelines given in #2058 and #2059, however, the problem still remains but now Jupyter is raising the error Reftek data encoding '32' not implemented yet

**Comment by megies** [comment]
Well, since you are on Windows, I can not really help you with compilation of ObsPy from source as suggested in #2058. From hearsay it likely is not trivial to set up compilation tools correctly.

If you're desperate for this feature, I guess one very ugly way would be to simply manually modify your working anaconda installation with making changes to `C:\ProgramData\Anaconda3\envs\obspy\lib\site-packages\obspy\io\reftek\core.py` as seen here: https://github.com/obspy/obspy/pull/2059/files#diff-b5aef08f8cd81c4a607c8deeebbe3625

(Even better make a dedicated new environment for this hacking..)

**Comment by heavelock** [comment]
There is always a way of using linux on windows in form of either `Windows Subsystem for Linux` which works only on Windows10 or some independent tools such as Babun. Not super efficient but enough for prototyping and checking.

**Comment by thanosvrat** [comment]
Thank you for your reply!

I followed your instructions and now a new problem appeared.

# Read in all ref files from one instrument
st_ref = obspy.read(r"C:\Users\Thanos-LAB\Desktop\Test\062941445_009060F0")

C:\ProgramData\Anaconda3\lib\site-packages\obspy\io\reftek\core.py:356: UserWarning: No channel code specified in the data file and no component codes specified. Using stream label and number of channel in file as channel codes.
  warnings.warn(msg)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\obspy\io\reftek\core.py in to_stream(self, network, location, component_codes, headonly, verbose, sort_permuted_package_sequence)
    366                             assert tr.stats.endtime == UTCDateTime(
--> 367                                ns=t_last) + (npts_last - 1) * delta
    368                         if npts:

AssertionError: 

During handling of the above exception, another exception occurred:

Reftek130Exception                        Traceback (most recent call last)
<ipython-input-2-7ada113008b4> in <module>()
      1 # Read in all ref files from one instrument
----> 2 st_ref = obspy.read(r"C:\Users\Thanos-LAB\Desktop\Test\062941445_009060F0")

<decorator-gen-156> in read(pathname_or_url, format, headonly, starttime, endtime, nearest_sample, dtype, apply_calib, check_compression, **kwargs)

C:\ProgramData\Anaconda3\lib\site-packages\obspy\core\util\decorator.py in _map_example_filename(func, *args, **kwargs)
    299                         except IOError:
    300                             pass
--> 301         return func(*args, **kwargs)
    302     return _map_example_filename
    303 

C:\ProgramData\Anaconda3\lib\site-packages\obspy\core\stream.py in read(pathname_or_url, format, headonly, starttime, endtime, nearest_sample, dtype, apply_calib, check_compression, **kwargs)
    233         pathname = pathname_or_url
    234         for file in sorted(glob(pathname)):
--> 235             st.extend(_read(file, format, headonly, **kwargs).traces)
    236         if len(st) == 0:
    237             # try to give more specific information why the stream is empty

<decorator-gen-157> in _read(filename, format, headonly, **kwargs)

C:\ProgramData\Anaconda3\lib\site-packages\obspy\core\util\decorator.py in uncompress_file(func, filename, *args, **kwargs)
    209     else:
    210         # no compressions
--> 211         result = func(filename, *args, **kwargs)
    212     return result
    213 

C:\ProgramData\Anaconda3\lib\site-packages\obspy\core\stream.py in _read(filename, format, headonly, **kwargs)
    275     """
    276     stream, format = _read_from_plugin('waveform', filename, format=format,
--> 277                                        headonly=headonly, **kwargs)
    278     # set _format identifier for each element
    279     for trace in stream:

C:\ProgramData\Anaconda3\lib\site-packages\obspy\core\util\base.py in _read_from_plugin(plugin_type, filename, format, **kwargs)
    410         raise TypeError(msg % (format_ep.name, ', '.join(eps)))
    411     # read
--> 412     list_obj = read_format(filename, **kwargs)
    413     return list_obj, format_ep.name
    414 

C:\ProgramData\Anaconda3\lib\site-packages\obspy\io\reftek\core.py in _read_reftek130(filename, network, location, component_codes, headonly, verbose, sort_permuted_package_sequence, **kwargs)
    107             component_codes=component_codes, headonly=headonly,
    108             verbose=verbose,
--> 109             sort_permuted_package_sequence=sort_permuted_package_sequence)
    110         st.merge(-1)
    111         st.sort()

C:\ProgramData\Anaconda3\lib\site-packages\obspy\io\reftek\core.py in to_stream(self, network, location, component_codes, headonly, verbose, sort_permuted_package_sequence)
    374                                "issue on GitHub and provide your file for"
    375                                "testing.")
--> 376                         raise Reftek130Exception(msg)
    377                     st += tr
    378 

Reftek130Exception: Reftek file has a trace with an inconsistent endtime or number of samples. Please open an issue on GitHub and provide your file fortesting.

**Comment by megies** [comment]
Could be a duplicate of #2036. Patching your files won't be a viable option here, I fear. That's too big of a change.

Also, please try to get formatting right, it's a pain to look at such posts, https://guides.github.com/features/mastering-markdown/

**Comment by megies** [comment]
Btw.. this is now describing a totally different issue than OP.
