### ISSUE TITLE
konno

### ISSUE THREAD

**Issue by ArthurRodgers** [obspy/obspy#2215]
**GitHub should mainly be used for bug reports and code developments/discussions. For generic questions, please use either the [[obspy-users] mailing list](http://lists.swapbytes.de/mailman/listinfo/obspy-users) (for scientific questions to the general ObsPy community) or our [gitter chat](https://gitter.im/obspy/obspy) (for technical questions and direct contact to the developers).**

---

Before submitting an Issue, please review the [Issue Guidelines](https://github.com/obspy/obspy/blob/master/CONTRIBUTING.md#submitting-an-issue).

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a short, self contained, correct example that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.

**Comment by megies** [comment]
@ArthurRodgers something went wrong, your issue description is missing.

**Comment by ArthurRodgers** [comment]
Hi Tobias –

Yes, I was searching for an example of Konno-Omachi smoothing. I was not ready to submit a question, but I can create an example code and post it.

I’m wondering about the expected input spectrum(a) – are these the Complex or real Fourier amplitude spectra?

I think it would be helpful to have a section in the tutorial about computing and plotting spectra

I’ll post an example soon

Thanks,
Artie

**Comment by ArthurRodgers** [comment]
I'm trying to compute and smooth Fourier amplitude spectrum. I'm using numpy for FFt and would like to use Konno-Ohmachi smoothing.

I'm using obspy 1.1.0 on Mac OSX 10.13.6 installed with anaconda
I could not get K-O smoothing to work in tests below (commented out)
The input SAC file (S_25_29.y) is from a numerical simulation, strong motion from Mw 6.5 earthquake at a few kilometers.
Test case uses simple moving average smoothing.

import obspy
from obspy.signal.konnoohmachismoothing import konno_ohmachi_smoothing
import matplotlib.pyplot as plt
import numpy as np

delta = 0.01

st = obspy.read('S_25_29.y')
st.detrend()
st.taper(type='hann', max_percentage=0.05)
st.interpolate(sampling_rate=1/delta)

# FFT
freq = np.fft.fftfreq(st[0].stats.npts, delta)
freq_shifted = np.fft.fftshift(freq)
y = st[0].data
F = np.fft.fft(y)
F_shifted = np.fft.fftshift(F)

# I've tried variants of arguments for K-O smoothing, but haven't gotten it to work:
#F_ko = konno_ohmachi_smoothing(F, freq)
#F_ko = konno_ohmachi_smoothing(np.abs(F), freq)
#F_ko = konno_ohmachi_smoothing(np.abs(F_shifted), freq_shifted)


fig = plt.figure(figsize=(4,4), dpi=300)
ax = fig.add_subplot(111)
ax.plot(freq_shifted, np.abs(F_shifted), color='b', linewidth=1, label='vsmin=500 m/s')
# Simple smoothing using 5-point moving average
ax.plot(freq_shifted, obspy.signal.util.smooth(abs(F_shifted), 5), freq_shifted, color='k', linestyle='--', linewidth=2)
ax.set_xlim(0.05,10)
ax.set_xscale('log')
ax.set_ylim(0.01,100)
ax.set_yscale('log')
ax.set_xlabel('Frequency, Hz')
ax.set_ylabel('Fourier Amplitude, m/s/Hz')

**Comment by megies** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by krischer** [comment]
I took the liberty to reformat your post.

I did not test your example so I don't know what goes wrong on your end, but I think it is the fact that you also use the negative frequencies. If you use `rfft()` it will only return the positive ones (which for real-valued input is sufficient) and it works fine.

Here is a small example:

```python
import obspy
from obspy.signal.konnoohmachismoothing import konno_ohmachi_smoothing
import obspy.signal.util
import numpy as np
from numpy.fft import rfft, rfftfreq
import matplotlib.pyplot as plt

tr = obspy.read()[0]

spec, freqs = rfft(tr.data), rfftfreq(tr.stats.npts, tr.stats.delta)

plt.figure(figsize=(12, 6))
plt.loglog(freqs, np.abs(spec), label="raw", color="grey")
plt.loglog(freqs,
           obspy.signal.util.smooth(abs(spec), 5),
           label="moving average")
plt.loglog(freqs,
           konno_ohmachi_smoothing(abs(spec), freqs, normalize=True),
           label="konno ohmachi")

plt.legend()
plt.show()
```

![screen shot 2018-09-19 at 12 32 05](https://user-images.githubusercontent.com/800487/45748100-0dacf880-bc08-11e8-8611-a34c9ae4ee1a.png)

**Comment by ArthurRodgers** [comment]
Thanks Lion. This makes sense now and I’ve got my code using the K-O smoothing as expected.
Thanks!
