### ISSUE TITLE
Trouble plotting with labels and only over a specific length of time

### ISSUE THREAD

**Issue by jau827** [obspy/obspy#2221]
**GitHub should mainly be used for bug reports and code developments/discussions. For generic questions, please use either the [[obspy-users] mailing list](http://lists.swapbytes.de/mailman/listinfo/obspy-users) (for scientific questions to the general ObsPy community) or our [gitter chat](https://gitter.im/obspy/obspy) (for technical questions and direct contact to the developers).**

---

Before submitting an Issue, please review the [Issue Guidelines](https://github.com/obspy/obspy/blob/master/CONTRIBUTING.md#submitting-an-issue).

* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...) Python 3.6.2, macOS 10.13.6 High Sierra

  -  How did you install ObsPy and Python (pip, anaconda, from source ...) `conda list` says `obspy 0.0.0+archive   <pip>`   installed probably a year ago

I am trying to plot my traces, and I've been trying two different ways to plot. Both ways do some things for me, but neither does everything I want. Allow me to show you.

```
flipsevenone = esevenone.copy() #copy of the original trace (esevenone)
dt1 = esevenone.stats.starttime

flipseventwo = eseventwo.copy()
dt2 = eseventwo.stats.starttime

flipseventhree = eseventhree.copy()
dt3 = eseventhree.stats.starttime

flipsevenone.plot(color = 'r', starttime = dt + 125, endtime = dt + 160, size = (1500, 400))
flipseventwo.plot(color = 'b', starttime = dt + 125, endtime = dt + 160, size = (1500, 400))
flipseventhree.plot(color = 'g', starttime = dt + 125, endtime = dt + 160, size = (1500, 400))
```
This produces a plot with UTC time on the x-axis (which is what I want). I like that I can slice hte data to be a certain length of time that I specify. However, I have found no way to add x, y labels to the axes and a title. Maybe I am just missing it and it's right in front of my face?

```
time = flipsevenone.times()

plt.figure(figsize = (22, 10))
plt.subplot(111)
plt.plot(time, flipsevenone, 'k')
plt.ylabel('Counts')
plt.xlabel('Time (seconds)')
plt.show()
```
This produces a plot with labels (which is what I want). However, I cannot figure out how to slice the data to a specific length. More importantly, I'm having trouble slicing the data and plotting, and I really don't like that the x axis is in seconds. I've tried `fig.autofmt_xdate()` but this did nothing. Thanks for the help in advance! - Jau827

**Comment by megies** [comment]
GitHub should mainly be used for bug reports and code developments/discussions. For generic usage questions, please use either the [obspy-users] mailing list.
