### ISSUE TITLE
UTCDateTime object has no attribute '_UTCDateTime_ns'

### ISSUE THREAD

**Issue by EoghanTotten** [obspy/obspy#2223]
Hi All,
         I have encountered the error as per the title of this issue. It seems that the latest version of obspy causes issues with the UTCDateTime. Such an attribute, when dumped to a pickle file, for example, causes issues when trying to re-read the pickle file. This is not the case for older versions of obspy, in my experience. The error takes place in obspy/core/utcdatetime/_get_ns: would it be possible to add a try/except loop to get around this issue? Many thanks.

**GitHub should mainly be used for bug reports and code developments/discussions. For generic questions, please use either the [[obspy-users] mailing list](http://lists.swapbytes.de/mailman/listinfo/obspy-users) (for scientific questions to the general ObsPy community) or our [gitter chat](https://gitter.im/obspy/obspy) (for technical questions and direct contact to the developers).**

---

Before submitting an Issue, please review the [Issue Guidelines](https://github.com/obspy/obspy/blob/master/CONTRIBUTING.md#submitting-an-issue).

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a short, self contained, correct example that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)

**Comment by trichter** [comment]
Hi,

are you sure you are using version 1.1.0?

The relevant PR is #1664

I use the master version of ObsPy and can pickle UTC objects without any problems.

```
In [12]: from obspy import UTCDateTime as UTC

In [13]: import pickle

In [14]: pickle.loads(pickle.dumps(UTC()))
Out[14]: 2018-10-01T15:33:14.461407Z

In [15]: obspy.__version__
Out[15]: '1.1.0.post0+420.gad46197741.dirty.obspy.master'
```

**Comment by EoghanTotten** [comment]
I believe so, on anaconda, it says my version is 1.1.0.
> 
> are you sure you are using version 1.1.0?
> 
> The relevant PR is #1664
> 
> I use the master version of ObsPy and can pickle UTC objects without any problems.
> 
> ```
> In [12]: from obspy import UTCDateTime as UTC
> 
> In [13]: import pickle
> 
> In [14]: pickle.loads(pickle.dumps(UTC()))
> Out[14]: 2018-10-01T15:33:14.461407Z
> 
> In [15]: obspy.__version__
> Out[15]: '1.1.0.post0+420.gad46197741.dirty.obspy.master'
> ```

**Comment by trichter** [comment]
Can you paste some output? Otherwise, it will be difficult to help.

```py
import obspy
print(obspy.__version__)
from obspy import UTCDateTime as UTC
import pickle
print(pickle.loads(pickle.dumps(UTC())))
```

**Comment by kdalbey** [comment]
I encountered the same problem in the master branch as of yesterday (August 24, 2020)  I'm running Anaconda 5 (updated to latest version) on windows 10 and I was compiling with 
https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16
my environment.yml file looks like this

dependencies:
- setuptools==41.0.1
- pip==19.0.3
- python==3.7.3
- numpy-base==1.16.6  
- numpy==1.16.6
- conda-forge::basemap==1.2.2
- basemap-data-hires==1.2.0
- deprecated==1.2.7
- future==0.16.0
- geos==3.8.1
- jupyter==1.0.0
- networkx==2.3
- numba==0.44.1
- pandas==0.24.2
- proj==7.1.0
- toml==0.9.4
- pytest==5.0.1
- pytest-cov==2.8.1
- pywavelets==1.0.3
- scikit-learn=0.21.2
- scikit-image=0.15.0
- conda-forge::diskcache==3.1.1 
- conda-forge::geographiclib==1.49
- conda-forge::nbval==0.9.4
- conda-forge::opencv==4.1.1
- pip:
  - cx-Oracle==6.1
  - EMD-signal==0.2.7
  - nvector==0.5.2
  - pisces==0.3.2
  - obspy-master.zip

**Comment by kdalbey** [comment]
ok I've solved that problem and found another one

if you go to trace.py and insert one line shown here
    def __setstate__(self, state):
        self.__dict__.update(state)
        # trigger refreshing
--->  self.__setitem__('starttime', state['starttime'])
        self.__setitem__('sampling_rate', state['sampling_rate'])

it solves that problem, I'm going to futz with the other problem tomorrow and may have another solution for you

**Comment by kdalbey** [comment]
Anyway, here's some output.... there's something weird with newint going on, after state is pickled back in I and I try to print just the keys new int is having a problem... it also happens when I try to print just state rather than the restored trace 

this version has a few prints inserted so line numbers are slightly off of the current master branch I don't yet know if this is related to the other problem but it seems be related to this issue (reading in pickle files created with obspy version I think 1.0.3, which I couldn't get to LINK on my windows machine during the pip install)

~\AppData\Local\Continuum\anaconda3\envs\testD\lib\site-packages\obspy\core\trace.py in __setstate__(self, state)
    260         print("self keys post update(state)")
    261         for key in self.__dict__.items():
--> 262             print(key)
    263         # trigger refreshing
    264         self.__setitem__('sampling_rate', state['sampling_rate'])

~\AppData\Local\Continuum\anaconda3\envs\testD\lib\site-packages\obspy\core\util\attribdict.py in __repr__(self)
     64 
     65     def __repr__(self):
---> 66         return "%s(%s)" % (self.__class__.__name__, self.__dict__)
     67 
     68     def __getitem__(self, name, default=None):

~\AppData\Local\Continuum\anaconda3\envs\testD\lib\site-packages\future\types\newint.py in __repr__(self)
     92         """
     93         value = super(newint, self).__repr__()
---> 94         assert value[-1] == 'L'
     95         return value[:-1]
     96 

AssertionError:

**Comment by kdalbey** [comment]
ok the other bug https://github.com/obspy/obspy/issues/2702
was the same as this one (problematic importing from old pickle files)
the common solution to both is listed in
https://github.com/obspy/obspy/issues/2702

**Comment by megies** [comment]
@kdalbey pickle is no safe option for persistent storage of data across large spans of time / changing software environments. You should really consider storing your data in a different form.

**Comment by kdalbey** [comment]
@megies I agree with you but I'm new to the project and it's not my call to make

**Comment by d-chambers** [comment]
Yup

**Comment by megies** [comment]
Ooops, i meant to hit "comment and close" anyway :rofl:
