### ISSUE TITLE
Obspy is not available from current channels of conda

### ISSUE THREAD

**Issue by zfang-slim** [obspy/obspy#2224]
I try to create an environment by conda with obspy by the following command:

`conda create -n myenv obspy`

However, it reports the following errror

PackagesNotFoundError: The following packages are not available from current channels:

  - obspy

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**GitHub should mainly be used for bug reports and code developments/discussions. For generic questions, please use either the [[obspy-users] mailing list](http://lists.swapbytes.de/mailman/listinfo/obspy-users) (for scientific questions to the general ObsPy community) or our [gitter chat](https://gitter.im/obspy/obspy) (for technical questions and direct contact to the developers).**

---

Before submitting an Issue, please review the [Issue Guidelines](https://github.com/obspy/obspy/blob/master/CONTRIBUTING.md#submitting-an-issue).

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a short, self contained, correct example that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)

**Comment by heavelock** [comment]
Obspy is available through `conda-forge` channel. You have to add it to conda config with use of this command ``conda config --add channels conda-forge``. 

PS: https://github.com/obspy/obspy/wiki/Installation-via-Anaconda

**Comment by QuLogic** [comment]
Please follow the instruction that @heavelock linked above.

We have no control over what may or may not appear in other channels.

**Comment by megies** [comment]
Also note that Python 3.7 packages are not yet available but should be soonish, hopefully. See conda-forge/obspy-feedstock#18
