### ISSUE TITLE
SEG2 to SEGY

### ISSUE THREAD

**Issue by hamauro** [obspy/obspy#2230]
Hi all

I want to convert SEG2 files to SEGY, including all the headers, i.e. also binary headers. Especially writing the binary headers causes some troubles (basically, it is not written to the SEGY-file). Before I spend ages on that and write a new routine: is there already a SEG2-to-SEGY tool on the "market", which escaped my search?

Thanks and cheers,
Mauro

**Comment by megies** [comment]
This sounds like a question you might want to reach more people than listening here. Maybe try the users mailing list? Or at least our gitter channel?

**Comment by d-chambers** [comment]
This probably falls outside the scope of what we would do in obspy. Like @megies said, it's probably best to try asking the mailing list. Closing for now, feel free to reopen if needed.
