### ISSUE TITLE
Synchronize files

### ISSUE THREAD

**Issue by thanosvrat** [obspy/obspy#2231]
ObsPy v 1.1.0, Python v 3.6.6, Windows 10

In Seismic Analysis Code (SAC) there is the command "Synchronize" available to synchronize the reference times of all files read. 
Is there a similar command in ObsPy?
If not, is there another way to synchronize the reference times?

**Comment by thanosvrat** [comment]
ObsPy v 1.1.0, Python v 3.6.6, Windows 10

In Seismic Analysis Code (SAC) there is the command "Synchronize" available to synchronize the reference times of all files read. 
Is there a similar command in ObsPy?
If not, is there another way to synchronize the reference times?

**Comment by d-chambers** [comment]
For those of us not familiar with SAC, can you describe what you would expect this to do in obspy?

**Comment by thanosvrat** [comment]
There are some files having recorded the same event but they have different reference times, so I need to determine the latest starting time of all files and define it as the reference time for all the files.

**Comment by ThomasLecocq** [comment]
```python
import numpy as np
st = read("yourfiles")
maxstart = np.max([tr.stats.starttime for fr in st])
minend =  np.min([tr.stats.endtime for fr in st])
st.trim(maxstart, minend)
```

**Comment by thanosvrat** [comment]
> ```python
> import numpy as np
> st = read("yourfiles")
> maxstart = np.max([tr.stats.starttime for fr in st])
> minend =  np.min([tr.stats.endtime for fr in st])
> st.trim(maxstart, minend)
> ```

Thank you very much! It worked fine!!
