### ISSUE TITLE
Resolve wildcarded filenames in read_inventory('*.xml')

### ISSUE THREAD

**Issue by Scavatore** [obspy/obspy#2238]
Hi!

I am having trouble with reading more than one station to my inventory. I am using [Mass downloader](https://docs.obspy.org/packages/autogen/obspy.clients.fdsn.mass_downloader.html) to download and write data to files in separate script.
The problem is that I can easily read different data traces from the folder and get them in one stream and I wanted to do the same with stations as Inventory. Something like this:

```python
st = read(pathname_or_url= "path/*", format="MSEED")
stations = read_inventory(path_or_file_object= "path/*", format="STATIONXML")
```
But with _read_inventory_ I encoutered this error:
> OSError: Error reading file "path/ * ": failed to load external entity "path/*"

So after some googling I ended up with writing it myself, reading stations one by one. But I don't like it and there must be some easier way than this:

```python
 st = read(pathname_or_url= "path/*", format="MSEED")
 for i in range(0,len(st)):
     network = st[i].meta.network
     station = st[i].meta.station
     path = "path/" + network + "." + station + ".xml" #default format of massdownloader for storage of stations
     stations1 = read_inventory(path_or_file_object= path, format="STATIONXML")
     stations += stations1
```

Hope that it's clear, if not tell me ;).
Thank you!

**Comment by megies** [comment]
I thought we had an issue for this already.. but I can't find any, so thanks for opening a ticket. We definitely need to do this same as with `read()`

**Comment by ThomasLecocq** [comment]
will be done with #2326
