### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by lijunzh** [obspy/obspy#2239]
Many of our dependencies have been bumped to Python 3.7. Do we have a plan to follow up and add Python 3.7 support soon?

**Comment by lijunzh** [comment]
I am writing this question because you will have to downgrade from 3.7 to 3.6 if you recently install the Anaconda directly from their official installer in order to install obspy via conda-forge channel. It does not seem to be too big a change to add 3.7 support in my opinion.

**Comment by petrrr** [comment]
Hi @lijunzh I have added a Python 3.7 subport in the packages system to which i contribute (Macports).

I have not seen particular problem up to now, but I have to admit that I use only relatively small part of the Obspy. However, several tests in the release because of changes in output, so these are not really relevant. 

I'd assume this has been fixed in the meantime in master, but I have not tested yet.

**Comment by lijunzh** [comment]
@petrrr Thanks for the quick reply. A temporary workaround is to install via pip which does not reinforce the python version prereqs. So far, I haven't seen any problem yet. I will keep it posted if anything wired happened.

**Comment by QuLogic** [comment]
Since you're referring to conda, that's up to the conda-forge packaging people, not ObsPy: https://github.com/conda-forge/obspy-feedstock/pull/18 (which happen to be the same people, yea, but there doesn't seem to be anything wrong with ObsPy itself.)

**Comment by megies** [comment]
Py37 conda packages should be building right now and be available soon. See https://github.com/conda-forge/obspy-feedstock/pull/18

**Comment by eyeris** [comment]
Hi Is the support for python 3.7 available now?

**Comment by heavelock** [comment]
Yes.

**Comment by eyeris** [comment]
I am using conda installation method and I have conda ersion 4.7.12 and python version 3.7.Its giving me following error. 
![image](https://user-images.githubusercontent.com/4762674/67681705-f4b57000-f9e1-11e9-8a51-b5ba07226aac.png)

**Comment by ThomasLecocq** [comment]
You're trying to install ``obspyck`` ?

**Comment by eyeris** [comment]
No. I am following the exact instructions in the documentation but get this error. However, in the documentation, ther eis no mention of python 3.7 support.

**Comment by megies** [comment]
@eyeris OS? architecture?

**Comment by eyeris** [comment]
Windows 10 Education x64

**Comment by megies** [comment]
Packages for win64 for Py 3.6 and 3.7 are online, no idea how your conda dependency solver ends up with `=2.7|3.5`.
But yeah, @ThomasLecocq has a valid point, if you have packages that depend on obspy (especially on specific, older versions) that could cause it.

![Screenshot from 2019-10-29 11-38-09](https://user-images.githubusercontent.com/1842780/67759922-a5eaf300-fa40-11e9-9f7f-bef0a0a05e10.png)

**Comment by ThomasLecocq** [comment]
following the instructions using anaconda package installer, you'll have two lines for "obspy" when searching for a package: "obspy" and "obspyck", make sure to un-check the "obspyck" box, this is causing the failure you see.

**Comment by eyeris** [comment]
Hi thanks a lot for the support but still I am getting the same error. I am not getting "obspypk" as you shown and I copied the full error list below.  Hope this wil help to identify where the exat error is.

![image](https://user-images.githubusercontent.com/4762674/67905576-f2137000-fbc5-11e9-82cc-4be861b3b491.png)
![image](https://user-images.githubusercontent.com/4762674/67905584-fb044180-fbc5-11e9-8596-861858444061.png)
![image](https://user-images.githubusercontent.com/4762674/67905599-05264000-fbc6-11e9-83b3-b57d4ad2b3c3.png)
