### ISSUE TITLE
"FDSNException: Unknownn Error (ConnectionResetError): Connection reset by peer" How to by pass?

### ISSUE THREAD

**Issue by ChrisBail** [obspy/obspy#2244]
Hi,
Not sure I had to put the thread here on the mailing list... anyway.
So I do some processing on some waveforms by using `get_waveforms` inside a loop. I use `Client`  to load the IRIS client before the loop. After couple of minutes/hours I have the following message:
`FDSNException: Unknownn Error (ConnectionResetError): Connection reset by peer`
Where does this error come from? How could I rewrite my code to handle this error? i.e. Should I call `Client` after each iteration? Put it in a `while` loop until the connection is reset?

Thanks in advance for your help and tips,

Cheers,
Ch.

**Comment by krischer** [comment]
This tends to be an error when the server either crashes or cancels the connection for another reason. There is a not a lot you can do here except waiting a few seconds and trying again. Just wrap the offending code block in a `try`/`except`. If you decomposed your code in functions I like using something like this decorator here (it only catches `socket.timeout` errors so you'll have to adapt it a bit).


```python
class retry():
    """
    Decorator that will keep retrying the operation after a timeout.

    Useful for remote operations that are prone to fail spuriously.
    """
    def __init__(self, retries: int, wait_time: float):
        self.retries = retries
        self.wait_time = wait_time

    def __call__(self, f: typing.Callable):
        def wrapped_f(*args, **kwargs):
            for _ in range(self.retries):
                try:
                    retval = f(*args, **kwargs)
                except socket.timeout:
                    time.sleep(self.wait_time)
                    continue
                else:
                    return retval
                raise

        return wrapped_f
```

**Comment by ChrisBail** [comment]
Thanks a lot Lion, I'll implement that! From your experience, are the deconnections more frequent on IRIS server?

ch.

On 10/15/2018 01:00 PM, Lion Krischer wrote:

This tends to be an error when the server either crashes or cancels the connection for another reason. There is a not a lot you can do here except waiting a few seconds and trying again. Just wrap the offending code block in a try/except. If you decomposed your code in functions I like using something like this decorator here (it only catches socket.timeout errors so you'll have to adapt it a bit).

class retry():
    """
    Decorator that will keep retrying the operation after a timeout.

    Useful for remote operations that are prone to fail spuriously.
    """
    def __init__(self, retries: int, wait_time: float):
        self.retries = retries
        self.wait_time = wait_time

    def __call__(self, f: typing.Callable):
        def wrapped_f(*args, **kwargs):
            for _ in range(self.retries):
                try:
                    retval = f(*args, **kwargs)
                except socket.timeout:
                    time.sleep(self.wait_time)
                    continue
                else:
                    return retval
                raise

        return wrapped_f

**Comment by zhong-yy** [comment]
Hi, I wonder how you solved this problem. I sometimes encountered the same error from `get_waveforms`, but sometimes the code woks well. I tried using a `try...except ConnectionResetError ...` clause, but it is surprising that the error was not caught.

**Comment by megies** [comment]
stale, closing.
