### ISSUE TITLE
PPSD.plot: argument xaxis_frequency does not affect argument period_lim

### ISSUE THREAD

**Issue by samuelchodur** [obspy/obspy#2245]
I scanned through Issue results when searching for 'PPSD' and did not see a similar issue, so my apologies if I missed it. 

According to the [docs](https://docs.obspy.org/packages/autogen/obspy.signal.spectral_estimation.PPSD.plot.html), when 'xaxis_frequency' is set to True, 'period_lim' should be expecting a tuple containing the frequency range in Hz as opposed to a tuple containing a period range. I am not finding this to be the case. If what I am finding is true, either the docs should be updated or some code should be changed.

This is not a regression that I am aware of.

Thanks for your time!

ObsPy version: 1.1.0
Python version: Python 3.6.6
Platform: Linux
ObsPy installed from Anaconda

Example:
```python
from obspy.clients.fdsn.client import Client
from obspy import UTCDateTime
from obspy import read
from obspy.signal import PPSD

client = Client("IRIS")

starttime = UTCDateTime('2018-09-18')
endtime = UTCDateTime('2018-09-19')
inventory = client.get_stations(network='PE', station='PAPL',
            starttime=starttime, endtime=endtime, level='response')

tr = read('waveforms/PE.PAPL..HHZ__20180918T000000Z__20180919T000000Z.mseed')
tr = tr.select()[0] 

ppsd = PPSD(tr.stats, metadata=inventory)
ppsd.add(tr)
ppsd.plot(xaxis_frequency=True, period_lim=(1.0, 5.0)
```

**Comment by megies** [comment]
Thanks for reporting. FYI, the plot axis limits can be easily adjusted post-plotting using minimal matplotlib as well, as a short term fix. Let me know if you need help.

**Comment by dsentinel** [comment]
I vaguely remember having a similar issue. It may work if in reverse order.

**Comment by megies** [comment]
Nah, the problem was that the inverse of given `period_lim` was taken, but when frequency is requested, actually the x coordinates for the plot are already inverted, so no need to invert the given `period_lim`.
