### ISSUE TITLE
Add Python 3.7 to CI build matrix

### ISSUE THREAD

**Issue by megies** [obspy/obspy#2247]
We should add a Python 3.7 build to CI for at least one platform..

**Comment by megies** [comment]
I think CI should also build 3.7 now for PRs against maintenance branch, I think it looks up the config from master. If not, we should backport #2249.

**Comment by megies** [comment]
- [ ] Also need to add python 3.7 version specifier in setup.py

**Comment by heavelock** [comment]
The newest PRs(ie #2260) are not being built on 3.7 at Travis and the CircleCI is still using old config.  So the #2249 and #2257 should be backported to maintenance branch.
