### ISSUE TITLE
AR picker fails for low amplitude data

### ISSUE THREAD

**Issue by calum-chamberlain** [obspy/obspy#2252]
Bug occurs in:
- Current obspy master, Linux, installed from source

This issue was raised on the gitter chat by @Dieselinium_twitter. The AR picker uses floats in the internal c-func, but gives incorrect pick-times when there are low amplitudes. I haven't fully investigated this, but I suspect it is a rounding error and could be fixed by using double-precision for some internal variables in the c-func.

@Dieselinium_twitter found this case after removing instrument response from his data, resulting in low amplitude ground-motion data.

The below minimal example is adapted from the [AR-picker tutorial](https://docs.obspy.org/tutorial/code_snippets/trigger_tutorial.html#ar-picker):

```python
import numpy as np
from obspy.core import read
from obspy.signal.trigger import ar_pick


tr1 = read('https://examples.obspy.org/loc_RJOB20050801145719850.z.gse2')[0]
tr2 = read('https://examples.obspy.org/loc_RJOB20050801145719850.n.gse2')[0]
tr3 = read('https://examples.obspy.org/loc_RJOB20050801145719850.e.gse2')[0]

for tr in [tr1, tr2, tr3]:
    tr.data = tr.data * 1e-6
    tr.data = tr.data.astype(np.float32)
    tr.plot()
df = tr1.stats.sampling_rate
p_pick, s_pick = ar_pick(tr1.data, tr2.data, tr3.data, df,
                         1.0, 20.0, 1.0, 0.1, 4.0, 1.0, 2, 8, 0.1, 0.2)
print(p_pick)
```

This plots each trace, just to make sure that the data can be represented at float32 (which they can).  This outputs a p-pick time of: `-0.10000000149011612`, when it would (without the gain) output `30.6350002289`.

**Comment by megies** [comment]
Should be fixed with #2253.
