### ISSUE TITLE
tr.filter should return dtype of tr.data and not always float64 data

### ISSUE THREAD

**Issue by pdales** [obspy/obspy#2261]
**GitHub should mainly be used for bug reports and code developments/discussions. For generic questions, please use either the [[obspy-users] mailing list](http://lists.swapbytes.de/mailman/listinfo/obspy-users) (for scientific questions to the general ObsPy community) or our [gitter chat](https://gitter.im/obspy/obspy) (for technical questions and direct contact to the developers).**

---

Before submitting an Issue, please review the [Issue Guidelines](https://github.com/obspy/obspy/blob/master/CONTRIBUTING.md#submitting-an-issue).

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a short, self contained, correct example that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)

**Comment by calum-chamberlain** [comment]
Can you provide some context for this request please?

Regarding whether the methods should return higher-precision data, see #1302 for a discussion on this.

**Comment by pdales** [comment]
Ok same Issue thanks

**Comment by megies** [comment]
Please take time to add some information or reasoning on the matter next time? Thanks.
