### ISSUE TITLE
Reftek data encoding 'b'32'' not implemented yet.

### ISSUE THREAD

**Issue by StevenSewell83** [obspy/obspy#2267]
Hi,

I am trying to read in reftek 130 data and have received the following message

NotImplementedError: Reftek data encoding 'b'32'' not implemented yet. Please open an issue on GitHub and provide a small (< 50kb) test file.

I have attached a test file (hopefully).

**Comment by megies** [comment]
This is implemented in master already but sadly not yet in a released version (will be part of 1.2.0).
If you want to use it, you'll have to install the current master branch (trivial on Linux and OSX (?), not so much on Windows, though)

See #2059 and up-to-date changelog.
