### ISSUE TITLE
obspy.io.seiscomp._read_events() misses some picks

### ISSUE THREAD

**Issue by nackerley** [obspy/obspy#2273]
The attached file has 7 picks associated with an event, but this is what I get when I use obspy.io.seiscomp._read_events() to read it:

``` python
from obspy import read_events
print(read_events('test_sc3ml_0.9.xml')[0])
```
```
Event:  1952-12-25T04:28:32.500000Z | +43.850,  -80.970 | 3.0 MN | manual

                    resource_id: ResourceIdentifier(id="smi:ca.seismo/event/evid/19521225.0428002")
                     event_type: 'earthquake'
           event_type_certainty: 'known'
            preferred_origin_id: ResourceIdentifier(id="smi:ca.seismo/origin/solid/19521225.0428002")
         preferred_magnitude_id: ResourceIdentifier(id="smi:ca.seismo/magnitude/solid/magcnt/19521225.0428001/1")
                           ---------
                          picks: 6 Elements
                     amplitudes: 1 Elements
                        origins: 2 Elements
                     magnitudes: 3 Elements
             station_magnitudes: 1 Elements
```
My expectation is that all 7 picks should be loaded.

I have the same problem regardless of whether I use 1.1.1rc1.post0+436.g3ffa3209c6.obspy.master installed using "python setup.py develop" after cloning from github, or version 1.1.0 installed using anaconda.

I have this problem both with sc3ml 0.9 (obspy 1.1.0 and 1.1.1) and 0.10 (obspy 1.1.1): 
[test_sc3ml.xml.zip](https://github.com/obspy/obspy/files/2650661/test_sc3ml.xml.zip).

**Comment by calum-chamberlain** [comment]
The pick that is not read in is an amplitude pick.  It looks like this gets lost in the transformation because it isn't referenced by an arrival (but it is referenced by an amplitude). As far as I can tell, only picks referenced by arrivals are converted (below is the reference to pick conversion from the `sc3ml_0.10__quakeml_1.2.xsl` file).
```
   <!-- picks, referenced by arrivals -->
   <xsl:for-each select="scs:arrival">
      <!--xsl:value-of select="scs:pickID"/-->
      <xsl:for-each select="../../scs:pick[@publicID=current()/scs:pickID]">
         <xsl:call-template name="genericNode"/>
      </xsl:for-each>
   </xsl:for-each>
```

**Comment by megies** [comment]
@nackerley we use the official SC3ML -> QuakeML xml stylesheets for conversion, so this might be an issue best filed at https://github.com/gempa/seiscomp3..

But probably it makes sense to drop those amplitude picks, they seem pretty SC3 specific and I don't see much use for them in the QuakeML/ObsPy Event domain? (Besides a round trip conversion back to SC3ML obviously)

**Comment by nackerley** [comment]
Thanks for digging into this @calum-chamberlain. I can see how to work around it now, at least, if that's what I have to do.

@megies, this is the thing, it is all about round-trip conversion. The dropped picks are an artefact of a legacy in-house data format. It's representable in QuakeML so I figured it ought to be representable in sc3ml. I can ask at Gempa, but I don't see the stylesheet translators at https://github.com/gempa/seiscomp3 (It's a bit fuzzy where they actually come from).

**Comment by Brtle** [comment]
It's not the right repository! https://github.com/gempa/seiscomp3 is just a fork not updated of https://github.com/SeisComP3/seiscomp3.

The stylesheet translators are located in [this folder](https://github.com/SeisComP3/seiscomp3/tree/master/src/trunk/libs/xml).

**Comment by Brtle** [comment]
By the way I did a [pull request](https://github.com/SeisComP3/seiscomp3/pull/208) to fix the XSLT files in seiscomp.

**Comment by gempa-stephan** [comment]
The pull request was accepted.
