### ISSUE TITLE
Update test images to Matplotlib 3

### ISSUE THREAD

**Issue by calum-chamberlain** [obspy/obspy#2274]
Reminder: in #2269 we found that some fails were coming from the update in Matplotlib 3.  At some point, when mpl 3 is more stable (once mpl 3.0.2 is out?), we should update our plots to mpl 3.

From @megies in #2269:
> I'm okay with merging this right now, just open an issue please as a reminder to switch baseline images to mpl 3 at some point, ideally against the 1.2.0 milestone?

**Comment by megies** [comment]
I just realized, Mpl 3 is Python 3 only, so this is for 2.0.0

**Comment by megies** [comment]
This is kinda obsolete since we don't even do image tests right now
