### ISSUE TITLE
inventory.remove() is missing in 1.1.0

### ISSUE THREAD

**Issue by alexgorb** [obspy/obspy#2287]
inv.remove() method is missing in 1.1.0 installed using conda on Linux and Mac platforms. Taking into account that manual (written March 2014) states its existence it is very frustrating to chase the truth. 

Python 2.7.13 (default, Aug  4 2017, 15:58:16) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from obspy import read_inventory
>>> inv=read_inventory()
>>> dir(inv)
['_Inventory__copy_inventory_metadata', '__add__', '__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__getitem__', '__hash__', '__iadd__', '__init__', '__len__', '__long__', '__module__', '__native__', '__ne__', '__new__', '__nonzero__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__unicode__', '__weakref__', '_networks', '_repr_pretty_', 'created', 'get_channel_metadata', 'get_contents', 'get_coordinates', 'get_orientation', 'get_response', 'module', 'module_uri', 'networks', 'next', 'plot', 'plot_response', 'select', 'sender', 'source', 'write']
>>> import obspy
>>> obspy.__version__
u'1.1.0'

**Comment by QuLogic** [comment]
What manual? I don't see `remove` listed anywhere in the [`Inventory` docs](http://docs.obspy.org/packages/autogen/obspy.core.inventory.inventory.Inventory.html).

**Comment by QuLogic** [comment]
Those are docs for `master`, which you can see from the URL and the version `ObsPy Documentation (1.1.1rc1.post0+538.g94356a114c.obspy.master)` at the top of the page.

This was added in #2088 and will be in 1.2.0 whenever it's released.
