### ISSUE TITLE
libgcf assumes 6 character stream IDs

### ISSUE THREAD

**Issue by mmcgo** [obspy/obspy#2289]
The GCF reader (libgcf.py) assumes the stream ID is 6 characters, and hard-codes access to element 4:
```
    header['station'] = stid[:4]
    header['channel'] = (channel_prefix[:2] + stid[4]).upper()
```

The Stream ID is made up of three parts: first is up to 4 characters for serial number, then one char for channel letter, then one channel for tap number. Rather than assume the channel letter is at index 4, it should be considered the 2nd last...
```
    header['station'] = stid[:-2]
    header['channel'] = (channel_prefix[:2] + stid[-2]).upper()
```

This was causing some valid GCF files to be considered invalid when they had short IDs.

**Comment by megies** [comment]
Easy to fix, thanks for the patch.

**Comment by brcayar** [comment]
Hi i need some help about obspy and gcf files

**Comment by megies** [comment]
@brcayar Please post usage questions on the users mailing list, see the wiki for a link to the mailing list. Thank you.
