### ISSUE TITLE
New GCF format options and digitizer types

### ISSUE THREAD

**Issue by mmcgo** [obspy/obspy#2291]
in libgcf.py, lines 93/94
```
    if sysid >> 31 & 0b1 > 0:
        sysid = (sysid << 6) >> 6
```
See [GCF format](http://www.guralp.com/apps/ok?doc=GCF_format) section 3.1.3 - there is another option to steal more bits from the SysID field. This is, in fact, used for Minimus and Affinity (see section 3.2).

Please also note that we have updated the above document to add support for some new sample rates that the Minimus can generate (see section 4.1.1).
Section 4.1.2 also updates the fractional timestamps, and allocates the 4th bit of “compression code” byte, as mentioned in #2290 , for use with 5000sps.

**Comment by megies** [comment]
Please feel free to provide patches or Pull Requests to extend functionality, see https://github.com/obspy/obspy/blob/master/CONTRIBUTING.md

**Comment by paitor** [comment]
Hi

Has anyone had a look at this yet? Else I've just updated my C-code to the latest (2018) revision of the gcf format so could have a go at it (seems like a good opportunity to finally make a reinvestment).

**Comment by megies** [comment]
I believe this might be obsolete with the recent changes in GCF module
