### ISSUE TITLE
ZeroDivisionError reading sc3ml with zero sampling rate

### ISSUE THREAD

**Issue by medlin01GA** [obspy/obspy#2293]
obspy read_inventory does not handle the case when reading sc3ml that the sampleRateNumerator and sampleRateDenominator are *both* zero. This occasionally crops up in real world data, in which case the channel sample_rate should be set to zero.

Add a test case to elicit the ZeroDivisionError and fix in sc3ml inventory reader.

Context:
* Obspy version: 1.1.1rc1
* Python version: all
* Platforms: all

**Comment by Jollyfant** [comment]
Related to #2294
