### ISSUE TITLE
FDSN EIDA token auth: allow signed messages as token files

### ISSUE THREAD

**Issue by rizac** [obspy/obspy#2297]
The following line of `_validate_eida_token `:

https://github.com/obspy/obspy/blob/454f4abe734c85bfc528af2cb43499bf7343cc72/obspy/clients/fdsn/client.py#L1909

Issues in my case a "false positive" as I am working with an EIDA token with the "header":

BEGIN PGP SIGNED MESSAGE

instead of

BEGIN PGP MESSAGE.

One possible fix  is to simply change the regex pattern to something less strict, e.g.:
```
if re.search(pattern=r'\bBEGIN PGP\b', string=token, 
```

I can issue a PR but beforehand I would like to get some insights: as I am not a token expert, maybe `_validate_eida_token ` prevents some subtle issues I am unaware of.

Thank you very much

**Comment by rizac** [comment]
Any feedback?

**Comment by megies** [comment]
Feel free to send a PR against `master` @rizac. Does the token mechanism work in any case? I'm quite confused with the EIDA setup and I don't think we have a real test case on any server that we can use to request restricted data.

In any case you should be able to work around this problem by simply removing the signature block in your token file and getting rid of ` SIGNED` keywords as well?

**Comment by megies** [comment]
Oh and you can convert your issue into a PR to avoid duplicated tickets, see https://github.com/obspy/obspy/wiki/Interesting-Reading-on-Git%2C-GitHub
