### ISSUE TITLE
obspy-scan doc does not document depiction of data overlaps

### ISSUE THREAD

**Issue by ghfbsd** [obspy/obspy#2301]
Hi - Just a short suggestion to modify a sentence in the obspy-scan documentation reporting that blue lines/blocks represent data overlaps.  (I had to read the code to figure this out.)  Suggest

"Start times of traces with available data are marked by crosses, gaps are indicated by vertical red lines."

be changed to read,

"Start times of traces with available data are marked by crosses, gaps are indicated by vertical red lines, and overlaps are indicated by blue lines."

George Helffrich

**Comment by megies** [comment]
Thanks for reporting!

**Comment by megies** [comment]
To be fixed here: https://www.geophysik.uni-muenchen.de/talkdetails/1991
