### ISSUE TITLE
Create nightly (conda) builds of the master branch

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#2335]
Hey,

**Aim of this issue:** 
discussing the case.

**Idea:**
Having "nightly" builds, or "when-master-changes" builds of the conda packages , maybe restricted to 1 or 2 python versions (3.6 & 3.7). That would allow ``conda install -c somewhere obspy=dev``  or ``conda install -c conda-forge/label/dev obspy`` or ...

Of course, it's possible to install from source, like with my own .htaccess binding ``pip install http://msnoise.org/obspy-master.zip`` but this requires the users to have the build tools installed (and even if it's getting easier on Windows, it's still not super straightforward for classic "workshop" users).

Aaaanyway, what do you think of this?

**Comment by ThomasLecocq** [comment]
example from the GlueViz guys: http://docs.glueviz.org/en/stable/installation/developer.html

**Comment by megies** [comment]
Having nightly or weekly packages would be nice. But..

 - I don't think conda-forge will ever open pandora's box and support something like this. I bet their CI is under heavy enough load with only building release versions for the whole world
 - Setting up and maintaining an infrastructure for this ourselves very likely is a major effort and I'm not sure if we should really open another front line

So.. hmmm dunno

**Comment by ThomasLecocq** [comment]
Thinking about it a bit, we could only build packages when master changes, which much less than nighly :-)

**Comment by megies** [comment]
It'd be cool if we could reuse the conda-forge infrastructure like in a fork to not swamp their Q. But it won't work because of the secret tokens I bet..

**Comment by megies** [comment]
I don't think conda people would like us to use up that many CI resources, so closing.
