### ISSUE TITLE
trace.filter hangs for no apparent reason

### ISSUE THREAD

**Issue by shaharkadmiel** [obspy/obspy#2349]
I have tested this with obspy 1.1.0, 1.1.1, and the current master branch. The ``filter()`` method on either a ``Stream`` or a ``Trace`` object sometimes hangs with no apparent reason. CPU load is 100%.

I have tried this in a new conda env as well.

My most recent example is this:

```python
from obspy import UTCDateTime
from obspy.clients.fdsn import Client as fdsnClient

t0  = UTCDateTime("2018-02-01T00:00:00.Z")
t1  = UTCDateTime("2018-02-01T01:30:00.Z")

client = fdsnClient('IRIS')
stream = client.get_waveforms('IM', 'I53*', '*', 'BDF', t0, t1)

stream.detrend('demean')
stream.taper(0.05)
stream.filter('bandpass', freqmin=0.1, freqmax=1, corners=4, zerophase=True)
```

**Comment by calum-chamberlain** [comment]
This doesn't run slow for me - takes 86ms for the filter on my OSX machine (running obspy 1.1.0 and scipy 0.19.1).  Ideas below though:

The slow running may be a case of a slow FFT.  Resampling and *sometimes* filtering work in the frequency domain and the FFT routines used can be slow for datasets where the number of samples is a large prime. In this case I end up with 108001 samples, which is not prime, so I'm surprised it is slow for you. Filtering also seems to run in the frequency domain only when there is only one denominator in the filter. I haven't checked if this is the case for your filter.

*If* it is an FFT issue, you might find that you get appreciable speed-ups if you use data with a "fast" number of samples.  Scipy has a function (`from scipy.fftpack import next_fast_len`) that works out the next fast number of samples for the FFT - in this case you might either pad your data with zeros to this length, or download that number of samples.

The reason I mention my scipy version is obspy uses scipy under the hood for this, so most of the time will be spent using scipy functions.  I have just updated scipy to 1.2.1 (from conda) and this runs slightly faster (78.2ms).

Can you provide some more details on what OS you are running and what scipy version? And can you test padding your data to 109350 samples and see what happens, if it is still slow we can rule out FFT issues:

```python
import numpy as np
from scipy.fftpack import next_fast_len

tr = stream[0].copy()
zeros = np.zeros(next_fast_len(tr.stats.npts))
zeros[0:tr.stats.npts] = tr.data
tr.data = zeros
%timeit tr.filter('bandpass', freqmin=0.1, freqmax=1, corners=4, zerophase=True)
```
This runs in 9.58ms, versus 11ms for the un-padded data for me...

**Comment by calum-chamberlain** [comment]
Note: 108001 isn't prime, but it looks like it only has 4 factors, similarly 86400001 (one sample over one day of 100 Hz data) isn't prime, but only has four factors, and I usually have issues computing the FFT for that case. Could be an FFT issue.

**Comment by krischer** [comment]
Our butterworth filters operate in the time domain and thus there is no FFT performed in the example. It would be interesting to figure out what the actually slow part is.

@shaharkadmiel Can you figure out which operation is actually slow in here: https://github.com/obspy/obspy/blob/5ed796d252c6418c4ce0c38798def26e5965ce3b/obspy/signal/filter.py#L39

Also what versions of python/numpy/scipy and and what operating system are you using?

**Comment by calum-chamberlain** [comment]
Ah, confusion in how `numpy.convolve` worked - apologies, ignore my rambling about FFTs then...

**Comment by megies** [comment]
> Also what versions of python/numpy/scipy and and what operating system are you using?

Cant reproduce either @shaharkadmiel. Without further info on numpy/scipy etc we likely wont be able to reproduce.

**Comment by shaharkadmiel** [comment]
The problem resolved. I don’t know how or why. I was away for two weeks, came back, did a bunch of updates including numpy and scipy and I cannot reproduce either. All I know is that at the time I was up to date with all packages installed. I’m on macOS 10.13.6.

**Comment by krischer** [comment]
I like problems that solve themselves :-)

**Comment by megies** [comment]
@shaharkadmiel you could look back in revisions of your env if you're on Anaconda

```
conda list --revisions
conda install --revision 70
```

But anyway.. if it's old numpy / scipy versions we don't care roo much really, I guess.
