### ISSUE TITLE
Better UTCDateTime error messages

### ISSUE THREAD

**Issue by d-chambers** [obspy/obspy#2352]
When the `__init__` method of `UTCDateTime` fails it produces very opaque error messages. It would be nicer if they were more clear. For example:

It would be nice if this code:

```python
import numpy as np
import obspy

utc = obspy.UTCDateTime(np.NaN)
```
produced and error message like this:

```python 
ValueError: nan is not a valid input for UTCDateTime
```

rather than

```python
TypeError: integer argument expected, got float
```

**Comment by ThomasLecocq** [comment]
I can work on this when finishing #2337 on Friday.

**Comment by d-chambers** [comment]
Sure, if you want to 😁

**Comment by megies** [comment]
> I can work on this when finishing #2337 on Friday.

wink wink, nudge nudge  ;-P

**Comment by krischer** [comment]
> wink wink, nudge nudge ;-P

;-)

**Comment by d-chambers** [comment]
Let's bump this to 2.0 since we will probably be doing some `UTCDateTime` refactoring anyway...

**Comment by megies** [comment]
Obsolete, above example shows `TypeError: 'float' object cannot be interpreted as an integer`
