### ISSUE TITLE
Massdownloader returns no data availability at 5 EIDA-nodes due to "matchtimeseries"-parameter in wadl-file

### ISSUE THREAD

**Issue by flixha** [obspy/obspy#2366]
When using the FDSN massdownloader (MDL) to request data from the NOA EIDA node, the MDL recently returns no availability of any data. My last successful download from NOA with the MDL was 2019-01-19, and I did not change python/obspy versions since then (tried obspy 1.1.0 and 1.1.1 in python 3.5 and 3.7,respectively, in conda). At the same time, the NOA node is still correctly accessible via the fdsn-services URL - so I am unaware why things should have changed.

Running the MDL with `debug=True`, however, I found that the MDL initializes the NOA client with 24 services, including the `matchtimeseries` and `includeavailability`-services. However, at least the `matchtimeseries`-service is not implemented at the node (for comparison: the GFZ client initializes only 22 services, and it does not have the two services mentioned above). The debugger outputs that the MDL requests the station-availability from the following URL:
[fdsn-request with matchtimeseries=true](http://eida.gein.noa.gr/fdsnws/station/1/query?starttime=2019-01-01T00%3A00%3A00.000000&endtime=2019-02-01T00%3A00%3A00.000000&level=channel&latitude=38.0&longitude=24.0&minradius=0.0&maxradius=1.0&matchtimeseries=true&format=text)

This URL fails to return data because of the statement `matchtimeseries=true`, and returns HTTP code 204 (no content). Removing that statement from the URL correctly returns the station-availability list: [request without matchtimeseries=true](http://eida.gein.noa.gr/fdsnws/station/1/query?starttime=2019-01-01T00%3A00%3A00.000000&endtime=2019-02-01T00%3A00%3A00.000000&level=channel&latitude=38.0&longitude=24.0&minradius=0.0&maxradius=1.0&format=text)

But because no data is returned from the URL due to the statement, the MDL concludes that there is no data at the NOA node and will hence not download anything, no matter the request. However, it will also not issue an error.

I am not too familiar with the clients and their initialization in obspy, but I am trying to see what is the root cause of this problem. I guess this is related to a "misunderstanding" during requesting available services - but from the node or from the MDL?

```python
import obspy
from obspy.clients.fdsn.mass_downloader import CircularDomain, \
    Restrictions, MassDownloader

domain = CircularDomain(latitude=38.0, longitude=24,
                        minradius=0.0, maxradius=1.0)
restrictions = Restrictions(starttime=obspy.UTCDateTime(2019, 1, 1),
                            endtime=obspy.UTCDateTime(2019, 2, 1),
                            chunklength_in_sec=86400)
mseed_storage = ("./{network}/{station}/"
                 "{starttime}.{endtime}.{network}_{station}_{location}_{channel}.mseed")
stationxml_storage = "stationXML/{network}/{station}.xml"
mdl = MassDownloader(providers=["NOA"], debug=True)
mdl.download(domain, restrictions, mseed_storage, stationxml_storage,
             threads_per_client=1)
```

```
[2019-03-27 15:03:31,515] - obspy.clients.fdsn.mass_downloader - INFO: Initializing FDSN client(s) for NOA.
Installed new opener with handlers: [<obspy.clients.fdsn.client.CustomRedirectHandler object at 0x7f93426216d8>]
Base URL: http://eida.gein.noa.gr
Request Headers: {'User-Agent': 'ObsPy/1.1.1 (Linux-2.6.32-754.10.1.el6.x86_64-x86_64-with-redhat-6.10-Santiago, Python 3.7.1)'}
Downloading http://eida.gein.noa.gr/fdsnws/dataselect/1/application.wadl with requesting gzip compression
Downloading http://eida.gein.noa.gr/fdsnws/event/1/application.wadl with requesting gzip compression
Downloading http://eida.gein.noa.gr/fdsnws/station/1/application.wadl with requesting gzip compression
Downloading http://eida.gein.noa.gr/fdsnws/event/1/catalogs with requesting gzip compression
Downloading http://eida.gein.noa.gr/fdsnws/event/1/contributors with requesting gzip compression
Uncompressing gzipped response for http://eida.gein.noa.gr/fdsnws/dataselect/1/application.wadl
Downloaded http://eida.gein.noa.gr/fdsnws/dataselect/1/application.wadl with HTTP code: 200
HTTP error 404, reason Not Found, while downloading 'http://eida.gein.noa.gr/fdsnws/event/1/contributors': b'Error 404: Not Found\n\nThe requested resource does not exist on this server.\n\nUsage details are available from /fdsnws/event/1/\n\nRequest:\n/fdsnws/event/1/contributors\n\nRequest Submitted:\n2019-03-27T14:03:34.016879\n\nService Version:\n1.2.0\n'
HTTP error 404, reason Not Found, while downloading 'http://eida.gein.noa.gr/fdsnws/event/1/application.wadl': b'Error 404: Not Found\n\nThe requested resource does not exist on this server.\n\nUsage details are available from /fdsnws/event/1/\n\nRequest:\n/fdsnws/event/1/application.wadl\n\nRequest Submitted:\n2019-03-27T14:03:34.018887\n\nService Version:\n1.2.0\n'
HTTP error 404, reason Not Found, while downloading 'http://eida.gein.noa.gr/fdsnws/event/1/catalogs': b'Error 404: Not Found\n\nThe requested resource does not exist on this server.\n\nUsage details are available from /fdsnws/event/1/\n\nRequest:\n/fdsnws/event/1/catalogs\n\nRequest Submitted:\n2019-03-27T14:03:34.020244\n\nService Version:\n1.2.0\n'
Uncompressing gzipped response for http://eida.gein.noa.gr/fdsnws/station/1/application.wadl
Downloaded http://eida.gein.noa.gr/fdsnws/station/1/application.wadl with HTTP code: 200
Discovered dataselect service
Discovered station service
Storing discovered services in cache.
[2019-03-27 15:03:31,720] - obspy.clients.fdsn.mass_downloader - INFO: Successfully initialized 1 client(s): NOA.
[2019-03-27 15:03:31,817] - obspy.clients.fdsn.mass_downloader - INFO: Total acquired or preexisting stations: 0
[2019-03-27 15:03:31,818] - obspy.clients.fdsn.mass_downloader - INFO: Client 'NOA' - Requesting reliable availability.
Downloading http://eida.gein.noa.gr/fdsnws/station/1/query?starttime=2019-01-01T00%3A00%3A00.000000&endtime=2019-02-01T00%3A00%3A00.000000&level=channel&latitude=38.0&longitude=24.0&minradius=0.0&maxradius=1.0&matchtimeseries=true&format=text with requesting gzip compression
Downloaded http://eida.gein.noa.gr/fdsnws/station/1/query?starttime=2019-01-01T00%3A00%3A00.000000&endtime=2019-02-01T00%3A00%3A00.000000&level=channel&latitude=38.0&longitude=24.0&minradius=0.0&maxradius=1.0&matchtimeseries=true&format=text with HTTP code: 204
[2019-03-27 15:03:31,990] - obspy.clients.fdsn.mass_downloader - INFO: Client 'NOA' - No data available for request.
[2019-03-27 15:03:31,990] - obspy.clients.fdsn.mass_downloader - INFO: Client 'NOA' - No data available.
[2019-03-27 15:03:31,990] - obspy.clients.fdsn.mass_downloader - INFO: ============================== Final report
[2019-03-27 15:03:31,990] - obspy.clients.fdsn.mass_downloader - INFO: 0 MiniSEED files [0.0 MB] already existed.
[2019-03-27 15:03:31,990] - obspy.clients.fdsn.mass_downloader - INFO: 0 StationXML files [0.0 MB] already existed.
[2019-03-27 15:03:31,991] - obspy.clients.fdsn.mass_downloader - INFO: Client 'NOA' - Acquired 0 MiniSEED files [0.0 MB].
[2019-03-27 15:03:31,991] - obspy.clients.fdsn.mass_downloader - INFO: Client 'NOA' - Acquired 0 StationXML files [0.0 MB].
[2019-03-27 15:03:31,991] - obspy.clients.fdsn.mass_downloader - INFO: Downloaded 0.0 MB in total.
```

**Comment by flixha** [comment]
I have dug a bit deeper and the issue appears to be the contents of the wadl-file returned by the EIDA node. [http://eida.gein.noa.gr/fdsnws/station/1/application.wadl](url) lists `matchtimeseries`as a parameter, while the following request shows that the parameter is not actually supported by the service (same link as above): request [http://eida.gein.noa.gr/fdsnws/station/1/query?starttime=2019-01-01T00%3A00%3A00.000000&endtime=2019-02-01T00%3A00%3A00.000000&level=channel&latitude=38.0&longitude=24.0&minradius=0.0&maxradius=1.0&matchtimeseries=true&format=text](url) 

Checking through the other EIDA node's station-wadl files, I found that the same issue arises for the nodes at ODC-KNMI (ORFEUS), BGR, NIEP, LMU and KOERI. So my MDL can't download any data from any of these node. Sounds like a problem that someone else may have noticed if it affects all these nodes, or I have some problems with my installation. So can someone confirm the issue?

**Comment by Jollyfant** [comment]
@flixha yes this seems to be a problem at the end points. I have updated the `application.wadl` for ODC-KNMI. Can you confirm it works now? I will bring this issue up at the EIDA level and request it to be fixed at other data centers.

**Comment by flixha** [comment]
@Jollyfant Yes it works now at ODC-KNMI (ORFEUS). Thanks for the quick update!

**Comment by krischer** [comment]
Great :-)

**Comment by svelasquezc** [comment]
I don't know if someone here is in charge of sismo.sgc.gov.co:8080, but the stationWS presents this same issue. [sismo.sgc.gov.co:8080/fdsnws/station/1/application.wadl](SISMO application.wadl)

**Comment by megies** [comment]
> I don't know if someone here is in charge of sismo.sgc.gov.co:8080, but the stationWS presents this same issue. http://[sismo.sgc.gov.co:8080/fdsnws/station/1/application.wadl](http://sismo.sgc.gov.co:8080/fdsnws/station/1/application.wadl)

@svelasquezc you would have to get in touch with them directly
