### ISSUE TITLE
Plotting no working 

### ISSUE THREAD

**Issue by edwarzambrano** [obspy/obspy#2367]
Hi Obspy Community,

I am trying to plot some seismograms and got a comment (**<Figure size 800x250 with 1 Axes>**) and the plotting didn't appear, after that, I tried to follow the tutorial: http://docs.obspy.org/tutorial/code_snippets/reading_seismograms.html, and I got the same result.

```
>>> from obspy import read
>>> st = read('http://examples.obspy.org/RJOB_061005_072159.ehz.new')
>>> print(st)
1 Trace(s) in Stream:
.RJOB..Z | 2005-10-06T07:21:59.850000Z - 2005-10-06T07:24:59.845000Z | 200.0 Hz, 36000 samples
>>> st.plot()
<Figure size 800x250 with 1 Axes>
>>> 
```

Could you help me with this issue, please.

I appreciate your cooperation and assistance

conda version : 4.6.8
ObsPy version: 1.1.1 
Python version: 3.7.2 
Platform: linux-64
ubuntu: 18.04.2
The installation of ObsPy and Python was via anaconda

**Comment by jkmacc-LANL** [comment]
This looks related to matplotlib.  If you don’t make plotting interactive, you’ll need to explicitly show the figure.  Try:

```python
import matplotlib.pyplot as plt 

<your code here>

plt.show()
```

**Comment by edwarzambrano** [comment]
> This looks related to matplotlib. If you don’t make plotting interactive, you’ll need to explicitly show the figure. Try:
> 
> ```python
> import matplotlib.pyplot as plt 
> 
> <your code here>
> 
> plt.show()
> ```

The plotting not working yet

**Comment by megies** [comment]
Put your code into a Python file and execute it without any interactive features (Ipython etc). If that does not work, check your matplotlib backend settings in matplotlibrc. If you set a backend that can not open a window (like "AGG") then no window will ever open, no matter what.

This is clearly no development related issue. Please use the users mailing list for any further questions with this.
