### ISSUE TITLE
SACTrace._allt  not changing kztime

### ISSUE THREAD

**Issue by carenelarmat** [obspy/obspy#2368]
Hello, 

Noticed that the _allt method for the class obspy.io.sac.SACTrace does change all the times in the sac header at the exception of the kztime. Can this be fixed?

Many thanks!

**Comment by jkmacc-LANL** [comment]
Thanks for raising this, @carenelarmat.  I'll try to tackle it quickly!

**Comment by carenelarmat** [comment]
The trick is that kztime doesn't exists as attribute in the header of trace or SACTrace. It appears when the trace is written back in sac. So all is about testing which attribute is already defined in the header and will be used in the writing operation. 

As an example, I wrote a method to change all time for a trace object, and the key is to make sure that b is defined before the shift of time, and kztime will be automatically changed. 
Here is the method for a trace (not a SACTrace): 

def allt(self,shift):
    if (not hasattr(self.stats.sac,'b')):
        self.stats.sac['b']=0
        self.stats.sac['e']=self.stats.endtime-self.stats.starttime
    for hdr in ['b', 'o', 'a', 'f'] + ['t' + str(i) for i in range(10)]:
        if (hasattr(self.stats.sac,hdr)):
            val = getattr(self.stats.sac, hdr)
            self.stats.sac[hdr]= val+shift

Hope this helps.

**Comment by jkmacc-LANL** [comment]
Thanks, @carenelarmat.  You're right that `kztime` isn't a header, it's a convenience.  The equivalent here would be `SACTrace.reftime`, which is a `UTCDateTime` and has its own `.date` and `.time` attributes instead of "kzdate" and "kztime".  Documentation on modifying the reference time while keeping the time headers consistent can be found [here](https://docs.obspy.org/master/packages/autogen/obspy.io.sac.sactrace.html#reference-time-and-relative-time-headers).

> the key is to make sure that b is defined before the shift of time

A problem I've seen before with synthetic SAC files is that `b`/`e` is undefined, which makes the file invalid, as the data vector has no connection to the reference time.  Is this a SPECFEM thing?  I've seen this a few times now.  You're right, if `b` not set, it can't be adjusted with `_allt` or when moving the `.reftime`.  Does SAC assume that an unset `b` is zero?

Could you give a code example of the specific problem you're having?

**Comment by jkmacc-LANL** [comment]
I saw this on the [CHNHDR documentation](https://ds.iris.edu/files/sac-manual/commands/chnhdr.html) :

> ALLT v: Add v seconds to all defined header times.  Subtract v seconds from the reference time.

Is the problem that `SACTrace._allt` doesn't do the second part, adjust the reference time?

**Comment by carenelarmat** [comment]
Yes. I verified it by an example I can send shortly.
I am now checking how SACTrace.write() handles a non-zero sac.b or sac.o.

Carene Larmat, EES-17
LANL, carene@lanl.gov<mailto:carene@lanl.gov>, 505 667 2074



On Mar 28, 2019, at 2:27 PM, jkmacc-LANL <notifications@github.com<mailto:notifications@github.com>> wrote:


I saw this on the CHNHDR documentation<https://ds.iris.edu/files/sac-manual/commands/chnhdr.html> :

ALLT v: Add v seconds to all defined header times. Subtract v seconds from the reference time.

Is the problem that SACTrace._allt doesn't do the second part, adjust the reference time?

**Comment by carenelarmat** [comment]
So I have an original data file with the following timing:
saclst b e o kztime f data_orig.sac
data_orig.sac     -317.693      6479.2           0 22:17:17.700

Using ch allt +317.693 with sac, I created a time-shifted data file with the following timings:
saclst b e o kztime f data_shift.sac 
data_shift.sac            0      6796.9     317.693 22:12:00.007

Let's try to do the same with SACTrace._allt (We are now in python terminal)
 sac = SACTrace.read('data_orig.sac')
print(sac.b,sac.e,sac.o,sac.reftime)
(-317.6929931640625, 6479.2018721699715, 0.0, UTCDateTime(1969, 11, 20, 22, 17, 17, 700000))
#Here we go, shifting times:
sac._allt(317.693)
print(sac.b,sac.e,sac.o,sac.reftime)
(6.835937711002771e-06, 6796.894872169972, 317.6929931640625, UTCDateTime(1969, 11, 20, 22, 17, 17, 700000))

So reftime is not changed accordingly. Let's see if this has consequence if we save the SACTrace.
sac.write('data_shift_withSACTrace.sac')

Now, using saclst in the terminal:
data_shift_withSACTrace.sac  6.83594e-06      6796.9     317.693 22:17:17.700

Inconsistent. So yes, the reference time has to be changed accordingly.

**Comment by jkmacc-LANL** [comment]
What's the `iztype` of the file?

**Comment by carenelarmat** [comment]
saclst iztype f data_orig.sac 
data_orig.sac     -12345

**Comment by jkmacc-LANL** [comment]
I think is see what's happening.  `SACTrace.allt` is written to simply adjust all relative time headers together.  It doesn't care about the reference time.  If what you want to do is make set the reference time such that `b` is equal to zero, I think you would just modify the reference time itself using the current value of `b`:

```python
In [48]: data, delta = np.linspace(-317.693, 6479.2, num=100, endpoint=True, retstep=True)

In [49]: sac = SACTrace(b=-317.693, e=6479.2, o=0, nzhour=22, nzmin=17, nzsec=17, nzmsec=700, data=data, delta=delta)

In [51]: sac.lh()
Reference Time = 01/01/1970 (001) 22:17:17.700000
	iztype IB: begin time
b          = -317.6929931640625
delta      = 68.65548706054688
e          = 6479.200225830078
iftype     = itime
internal0  = 2.0
iztype     = ib
lcalda     = False
leven      = True
lovrok     = True
lpspol     = True
npts       = 100
nvhdr      = 6
nzhour     = 22
nzjday     = 1
nzmin      = 17
nzmsec     = 700
nzsec      = 17
nzyear     = 1970
o          = 0.0

In [52]: sac.reftime += sac.b

In [53]: sac.lh()
Reference Time = 01/01/1970 (001) 22:12:00.007000
	iztype IB: begin time
b          = 0.0
delta      = 68.65548706054688
e          = 6796.893218994141
iftype     = itime
internal0  = 2.0
iztype     = ib
lcalda     = False
leven      = True
lovrok     = True
lpspol     = True
npts       = 100
nvhdr      = 6
nzhour     = 22
nzjday     = 1
nzmin      = 12
nzmsec     = 7
nzsec      = 0
nzyear     = 1970
o          = 317.6929931640625

```

`SACTrace.reftime` can be modified directly, and it keeps the values of the relative time headers consistent.

**Comment by carenelarmat** [comment]
That answers my question in addition to the help(sac._allt) which explicitly proposes the alternative to set iztype which will take part of shifting the reference time. 
 Part of my confusion is that I took the bad habit to do 'ch allt 317' instead of 'ch allt 317 iztype io' in sac. I now understand the danger of skipping the definition of iztype. 

Maybe you can consider having an optional argument on SACTrace._allt which will allow the user to enter the iztype. 

Many thanks

**Comment by jkmacc-LANL** [comment]
Actually, `iztype` is also a managed attribute.  If `o` is set, and you `sac.iztype = “io”` to set the reference time to be origin-based, it will set the `iztype` and move the `reftime` to the time of the `o` header (so the value of `o` is now zero), which automatically shifts all the relative time headers as in the example above.  Try it!

**Comment by jkmacc-LANL** [comment]
Closing for now.  Thanks!
