### ISSUE TITLE
adding uncertainties to Nordic catalog read

### ISSUE THREAD

**Issue by WayneCrawford** [obspy/obspy#2375]
obspy's nordic reader (nordic.core._read_uncertainty) does not currently appear to save hypocenter uncertainties (based on my runs and looking at the code in the Master branch).  It seems like this would be pretty easy to do, as the values are already read and the code for calculating the confidence ellipsoid seems to already exist. 
 I propose to add this capability unless someone with permissions wants to do it or tells me why it's harder than it seems.

Regards
Wayne Crawford

**Comment by calum-chamberlain** [comment]
Hi Wayne,

Go for it.  I tried at one point but failed to get code to reliably give the right conversion.  Possibly someone has provided something better now. My efforts were up here somewhere,  but I'm in the field at the moment and can't find it.

CJ Chamberlain, out of office

________________________________

**Comment by WayneCrawford** [comment]
I've been working on 2D ellipses so 3D shouldn't be too difficult.  But I figured that there'd be an even easier method, using the inverse function of `confidence_ellipsoid_to_xyz()` in your _write_hyp_error_line code (below).  But I can't find `confidence_ellipsoid_to_xyz()` in the obspy repository: does it really exist?




```
def _write_hyp_error_line(origin):
    ...
    try:
        errors = origin.origin_uncertainty[
            'confidence_ellipsoid'].confidence_ellipsoid_to_xyz()
```

**Comment by calum-chamberlain** [comment]
I'm in the field at the moment and struggling to find the relevant code or old pulls on my phone.

CJ Chamberlain, out of office

________________________________

**Comment by megies** [comment]
>  But I can't find `confidence_ellipsoid_to_xyz()` in the obspy repository: does it really exist?

I found it in the git log, seems it got scrapped again during #1924:

612fe4f61831d7a17a4b022f81ed8aec71edb0cc

**Comment by WayneCrawford** [comment]
If you have an old version I could start from there, otherwise I could go from scratch.  I think most of the work would actually be in the core/event directory where I would need to add the following methods:
base.py:ConfidenceEllipsiod: from_xyz(), from_covariance(), to_xyz(), to_xy(), to_covariance()
origin.py:OriginUncertainty: from_xy(), from_xyz(), from_covariance(), to_xyz(), to_xy(),to_covariance(),to_xycovariance()

One problem is that even "standard" catalogs don't always seem to write uncertainties in the right units.  They are specified as 'm' in QuakeML (and obspy), but I downloaded a catalog from the ISC and the uncertainty numbers for global quakes are generally between 10 and 30, so I'm guessing kilometers

**Comment by WayneCrawford** [comment]
Hi,
I modified the "nordic" code so that it can calculate uncertainty ellipses and read high accuracy hypocenters.  Unfortunately, I stil haven't figured out how to download the branch to my computer, test it, and upload it again.  So I simply attached the modified files here, both of which replace the existing files in io.nordic.  I've also attached a Nordic file that one can test the new features on.  I'm sorry about this sloppy way of updating, if it's too much work for someone else to integrate, I can try to do it the right way later on.

[core.txt](https://github.com/obspy/obspy/files/3091684/core.txt)
[utils.txt](https://github.com/obspy/obspy/files/3091685/utils.txt)
[nordic_highaccuracy.txt](https://github.com/obspy/obspy/files/3091693/nordic_highaccuracy.txt)

The major changes are:

- A new _ellipses class in util.py (the class does more than what is needed and could be useful to other obspy functions, but until it is completed and validated I prefer it stays here)
- Adding 'H' to ACCEPTED_TAGS in utils.py
- Setting the uncertainty ellipse in core._read_uncertainty
- A new routine to read high accuracy ('H') lines : core._read_highaccuracy
- Call to core._read_highaccuracy in core._extract_event

Still to do:

- Make an _ellipsoid class that calculates 3D ConfidenceEllipsoids
- Make the method to output a covariance matrix from the uncertainty ellipse (should be a pretty easy add-on to the _ellipse class)

**Comment by krischer** [comment]
@calum-chamberlain I assigned the issue to you. Let us know if that is not okay!

**Comment by calum-chamberlain** [comment]
Keen to have a look soon,  back from fieldwork on Monday.  Sorry I haven't been any help so far!

CJ Chamberlain, out of office

________________________________

**Comment by calum-chamberlain** [comment]
Hi @WayneCrawford it would be really helpful if you can do the updates using git - I'm not sure what branch you based this on at the moment.
You should be able to do something along the lines of:
```bash
# Make sure you are where you want the obspy directory to be created
git clone https://github.com/obspy/obspy.git
git checkout master # assuming that you are basing this on master, I think this counts as a feature
git checkout -B nordic_ellipse_conv # create a branch based on master, you can change the name if you want
```
Then make your changes (if you have made your changes to the branch you based your new branch on you should just be able to replace the files.  You should then check that the tests still pass (you can you [`obspy-runtests`](https://docs.obspy.org/master/packages/autogen/obspy.scripts.runtests.html), which can select just the tests you want, or you can just run `python obspy/io/nordic/tests/test_nordic.py` to call just the nordic tests from your obspy directory. You should also try running flake8 on your files (`flake8 obspy/io/nordic/core.py` and `flake8 obspy/io/nordic/utils.py`).

Once you are happy you should add then commit the files, make sure to only add the files that you have changed:
```bash
git add obspy/io/nordic/core.py obspy/io/nordic/utils.py obspy/io/nordic/tests/data/nordic_highaccuracy
git commit -m "Your useful commit message"
```
Make sure to give some useful commit message when you commit. Once you have committed you should be able to push your new branch back to here - if you don't have permissions to push a branch up here then let us know.  To push you can run:
```bash
git push origin nordic_ellipse_conv
```
If you used a different branch name you will need to change that branch name here as well.  You should then be able to create a pull request in the browser.

Let me know if you have any issues, looking forward to having more of a poke around soon.

**Comment by calum-chamberlain** [comment]
We might want to reinstate the tests that [I wrote back in the commit that got scraped](https://github.com/obspy/obspy/commit/612fe4f61831d7a17a4b022f81ed8aec71edb0cc#diff-83fbea4e45557d446dcda89dea422626L240) as well to save us from re-writing the wheel... I think we also discussed that it would be good to have the conversions as methods on the `ConfidenceEllipsoid` object in event - I still think that would be a good place for them so that they are obviously available for other things. Open to thoughts though!

**Comment by WayneCrawford** [comment]
Hi,

Thanks for the tutorial!  I did all of the actions (including the tests), added two test methods: test_read_high_accuracy() and test_read_uncert_ellipse(), and added and commited the files.

But git push returned:
```
(obspy) FRISKA:obspy 561> git push origin nordic_ellipse_conv
error: src refspec nordic_ellipse_conv does not match any.
error: failed to push some refs to 'https://github.com/obspy/obspy.git'
```

even thought I'm pretty sure I did the branching right (i.e., exactly as you said): here's my history minus the most boring stuff

```
  535  git clone https://github.com/obspy/obspy.git
  536  git checkout master
  537  git checkout -B nordic_ellipse_conv
  552  python obspy/obspy/io/nordic/tests/test_nordic.py 
  556  cd obspy
  557  git add obspy/io/nordic/core.py obspy/io/nordic/utils.py obspy/io/nordic/tests/data/sfile_highaccuracy obspy/io/nordic/tests/test_nordic.py 
  558  git commit -m "Now reads high accuracy lines and calculates confidence ellipses (but not ellipsoids)"
  561  git push origin nordic_ellipse_conv
  562  history
```

**Comment by calum-chamberlain** [comment]
Can you run `git status` to check that everything you have changed has been added/committed - the error message thrown by git isn't that helpful.

However, this might be a permissions thing, sorry, I don't think I have the power to change that: @krischer would you add @WayneCrawford to the collaborators list so that he has permission to create new branches here (I can't see if he is already on that list)? Or would you rather this come from a fork - I'm not that fond of working on a fork, I always fail to keep them up to date, which is why I recommended this approach first.

**Comment by calum-chamberlain** [comment]
Thanks @krischer: @WayneCrawford can you have another go at pushing and let me know if you get the same issue?

**Comment by WayneCrawford** [comment]
I tried again and it gave me the same message.  Then I reran the "checkout" and "commit" commands.  It gave me a list of "other" files for this commit (see below), which worries me, but when I run "push" it now at least asks me for my username and password before rejecting me:

```
(obspy) FRISKA:obspy 517> git push origin nordic_ellipse_conv
Username for 'https://github.com': crawford@ipgp.fr
Password for 'https://crawford@ipgp.fr@github.com': *******
remote: Permission to obspy/obspy.git denied to WayneCrawford.
fatal: unable to access 'https://github.com/obspy/obspy.git/': The requested URL returned error: 403
```

Maybe my user information isn't the same that @krischer entered in the "Contributers" list?

Once that's settled, I think I should re-checkout and re-commit to see if I can get rid of the seemingly-irrelevant file list  I assume that if I rerun "checkout -B" it will crush the old nordic_ellipse_conv?  Should I completely reload or at least checkout the master first?

Regards
Wayne

```
(obspy) FRISKA:obspy 513> git checkout -B nordic_ellipse_conv
M	obspy/io/seisan/docs/seisan_8.2.1.pdf
M	obspy/io/seisan/tests/data/2001-01-13-1742-24S.KONO__004
M	obspy/io/seisan/tests/data/2005-07-23-1452-04S.CER___030.mseed
M	obspy/io/seisan/tests/data/9701-30-1048-54S.MVO_21_1
M	obspy/io/sh/tests/data/TEST_090101_0101.ASC
M	obspy/io/sh/tests/data/TEST_090101_0101.QHD
M	obspy/io/stationxml/tests/data/stationxml_BK.CMB.__.LKS.xml
M	obspy/io/stationxml/tests/data/stationxml_IU.ANTO.30.LDO.xml
M	obspy/io/win/docs/E-MAN_LS-7000XT_7_format.pdf
M	obspy/io/win/tests/data/10030302.01
M	obspy/io/y/docs/NmxDataFormats_RefGuide_14602R4.pdf
M	obspy/signal/src/evalresp/evalresp.ide
M	obspy/signal/tests/data/BW.KW1._.EHZ.D.2011.090_downsampled.asc.gz
M	obspy/signal/tests/data/BW.UH4._.EHZ.D.2010.147.cut.slist.gz
M	obspy/signal/tests/data/IUANMO_ppsd_fullresponse.npz
M	obspy/signal/tests/data/KARC.LHZ.SAC.asc.gz
M	obspy/signal/tests/data/KARC_corrected.sac.asc.gz
M	obspy/signal/tests/data/RESP.NZ.CRLZ.10.HHZ.windows
M	obspy/signal/tests/data/loc_RJOB20050801145719850.e.polfilt.gz
M	obspy/signal/tests/data/loc_RJOB20050801145719850.n.polfilt.gz
M	obspy/signal/tests/data/manz_waldk.a01.gz
M	obspy/signal/tests/data/pitsa_noise.npy
M	obspy/signal/tests/data/ppsd_kw1_ehz.npz
M	obspy/signal/tests/data/ref_STS2
M	obspy/signal/tests/data/ref_unknown
M	obspy/signal/tests/data/rjob_20051006_t_115deg.gz
M	obspy/signal/tests/data/rotz_20081028_kirnos.gz
M	obspy/signal/tests/data/rotz_20081028_wood_anderson.gz
M	obspy/signal/tests/data/rotz_20081028_wwssn_sp.gz
M	obspy/signal/tests/data/timingquality.mseed
M	obspy/signal/tests/data/tiny_quality_file.mseed
M	obspy/signal/tests/images/degree_1_spline_detrend.png
M	obspy/signal/tests/images/plot_lanczos_window.png
M	obspy/signal/tests/images/polynomial_detrend.png
M	obspy/signal/tests/images/ppsd_restricted_stack.png
M	obspy/signal/tests/images/ppsd_spectrogram.png
M	obspy/signal/tests/images/ppsd_temporal.png
M	obspy/signal/tests/images/time_frequency_gofs.png
M	obspy/signal/tests/images/time_frequency_misfits.png
M	obspy/signal/tests/images/time_frequency_representation.png
M	obspy/signal/tests/images/xcorr_pick_corr.png
M	obspy/taup/data/1066a.npz
M	obspy/taup/data/1066b.npz
M	obspy/taup/data/ak135.npz
M	obspy/taup/data/herrin.npz
M	obspy/taup/data/iasp91.npz
M	obspy/taup/data/prem.npz
M	obspy/taup/data/pwdk.npz
M	obspy/taup/data/sp6.npz
M	obspy/taup/tests/images/cartesian_many_phases.png
M	obspy/taup/tests/images/cartesian_many_phases_buried_station.png
M	obspy/taup/tests/images/cartesian_many_phases_one_way.png
M	obspy/taup/tests/images/spherical_diff_phases.png
M	obspy/taup/tests/images/spherical_many_phases.png
M	obspy/taup/tests/images/spherical_many_phases_buried_station.png
M	obspy/taup/tests/images/spherical_many_phases_one_way.png
M	obspy/taup/tests/images/spherical_more_then_360.png
M	obspy/taup/tests/images/traveltimes_many_phases.png
M	obspy/taup/tests/images/traveltimes_many_phases_multiple_degrees.png
M	obspy/taup/tests/images/traveltimes_plot_all_False.png
M	obspy/taup/tests/images/traveltimes_plot_all_True.png
Switched to a new branch 'nordic_ellipse_conv'
```

and then when I run git-commit I get the same list of files (in red) with a message saying "no changes added to commit" (of course, this is the second time I'm running git-commit):
```
git commit -m "Now reads high accuracy lines and calculates confidence ellipses (but not ellipsoids)"
On branch nordic_ellipse_conv
Changes not staged for commit:
	modified:   obspy/io/seisan/docs/seisan_8.2.1.pdf
	modified:   obspy/io/seisan/tests/data/2001-01-13-1742-24S.KONO__004
	modified:   obspy/io/seisan/tests/data/2005-07-23-1452-04S.CER___030.mseed
	modified:   obspy/io/seisan/tests/data/9701-30-1048-54S.MVO_21_1
	modified:   obspy/io/sh/tests/data/TEST_090101_0101.ASC
	modified:   obspy/io/sh/tests/data/TEST_090101_0101.QHD
	modified:   obspy/io/stationxml/tests/data/stationxml_BK.CMB.__.LKS.xml
	modified:   obspy/io/stationxml/tests/data/stationxml_IU.ANTO.30.LDO.xml
	modified:   obspy/io/win/docs/E-MAN_LS-7000XT_7_format.pdf
	modified:   obspy/io/win/tests/data/10030302.01
	modified:   obspy/io/y/docs/NmxDataFormats_RefGuide_14602R4.pdf
	modified:   obspy/signal/src/evalresp/evalresp.ide
	modified:   obspy/signal/tests/data/BW.KW1._.EHZ.D.2011.090_downsampled.asc.gz
	modified:   obspy/signal/tests/data/BW.UH4._.EHZ.D.2010.147.cut.slist.gz
	modified:   obspy/signal/tests/data/IUANMO_ppsd_fullresponse.npz
	modified:   obspy/signal/tests/data/KARC.LHZ.SAC.asc.gz
	modified:   obspy/signal/tests/data/KARC_corrected.sac.asc.gz
	modified:   obspy/signal/tests/data/RESP.NZ.CRLZ.10.HHZ.windows
	modified:   obspy/signal/tests/data/loc_RJOB20050801145719850.e.polfilt.gz
	modified:   obspy/signal/tests/data/loc_RJOB20050801145719850.n.polfilt.gz
	modified:   obspy/signal/tests/data/manz_waldk.a01.gz
	modified:   obspy/signal/tests/data/pitsa_noise.npy
	modified:   obspy/signal/tests/data/ppsd_kw1_ehz.npz
	modified:   obspy/signal/tests/data/ref_STS2
	modified:   obspy/signal/tests/data/ref_unknown
	modified:   obspy/signal/tests/data/rjob_20051006_t_115deg.gz
	modified:   obspy/signal/tests/data/rotz_20081028_kirnos.gz
	modified:   obspy/signal/tests/data/rotz_20081028_wood_anderson.gz
	modified:   obspy/signal/tests/data/rotz_20081028_wwssn_sp.gz
	modified:   obspy/signal/tests/data/timingquality.mseed
	modified:   obspy/signal/tests/data/tiny_quality_file.mseed
	modified:   obspy/signal/tests/images/degree_1_spline_detrend.png
	modified:   obspy/signal/tests/images/plot_lanczos_window.png
	modified:   obspy/signal/tests/images/polynomial_detrend.png
	modified:   obspy/signal/tests/images/ppsd_restricted_stack.png
	modified:   obspy/signal/tests/images/ppsd_spectrogram.png
	modified:   obspy/signal/tests/images/ppsd_temporal.png
	modified:   obspy/signal/tests/images/time_frequency_gofs.png
	modified:   obspy/signal/tests/images/time_frequency_misfits.png
	modified:   obspy/signal/tests/images/time_frequency_representation.png
	modified:   obspy/signal/tests/images/xcorr_pick_corr.png
	modified:   obspy/taup/data/1066a.npz
	modified:   obspy/taup/data/1066b.npz
	modified:   obspy/taup/data/ak135.npz
	modified:   obspy/taup/data/herrin.npz
	modified:   obspy/taup/data/iasp91.npz
	modified:   obspy/taup/data/prem.npz
	modified:   obspy/taup/data/pwdk.npz
	modified:   obspy/taup/data/sp6.npz
	modified:   obspy/taup/tests/images/cartesian_many_phases.png
	modified:   obspy/taup/tests/images/cartesian_many_phases_buried_station.png
	modified:   obspy/taup/tests/images/cartesian_many_phases_one_way.png
	modified:   obspy/taup/tests/images/spherical_diff_phases.png
	modified:   obspy/taup/tests/images/spherical_many_phases.png
	modified:   obspy/taup/tests/images/spherical_many_phases_buried_station.png
	modified:   obspy/taup/tests/images/spherical_many_phases_one_way.png
	modified:   obspy/taup/tests/images/spherical_more_then_360.png
	modified:   obspy/taup/tests/images/traveltimes_many_phases.png
	modified:   obspy/taup/tests/images/traveltimes_many_phases_multiple_degrees.png
	modified:   obspy/taup/tests/images/traveltimes_plot_all_False.png
	modified:   obspy/taup/tests/images/traveltimes_plot_all_True.png

no changes added to commit
```

**Comment by calum-chamberlain** [comment]
The long list of changed files might be due to [changes in mode](https://stackoverflow.com/questions/1580596/how-do-i-make-git-ignore-file-mode-chmod-changes) - can you try running `git diff obspy/taup/tests/images/traveltimes_plot_all_True.png`: this will tell you what change was made, if is just a mode change then you might want to follow the link above and ignore mode changes.

I wouldn't re-clone everything yet, but if you do then yes, checkout master first before the `git checkout -B new_branch` command to make sure your changes are based on master.

RE the permissions thing - you would usually enter your username rather than your email, maybe try that?

**Comment by calum-chamberlain** [comment]
It doesn't look to me like you are on the list I was expecting, but I miss typed the name. 
 @krischer, I was looking in the obspy/developers list but incorrectly said contributors. Is that the last @WayneCrawford needs to be on to push a new branch?

Thanks for the efforts on git things!

**Comment by QuLogic** [comment]
Do you really need to push here? Just push to your fork.

**Comment by calum-chamberlain** [comment]
Yeah, sure, sorry, I get frustrated with forks.

@WayneCrawford we should probably start again - start off by making a fork on github (hit the fork button button at the top right), then clone the fork and go through the branch creation and adding files there, then push your branch to your fork (if you cloned the fork then the `origin` should be set to your fork already).  Then you can create a pull request from your fork. Sorry for the confusion!

**Comment by calum-chamberlain** [comment]
Hi @WayneCrawford, looks like you managed to [make that fork](https://github.com/WayneCrawford/obspy/tree/nordic_ellipse) and add your changes, but it looks like you added those files that git thought were [changed but not by you](https://github.com/obspy/obspy/commit/b2f6f4a735db688e7486f657a1b0f23ff0ec592e), I think we need that commit to not be there, so you will need to undo that, then re-do the later commits.  I think you will want to use `git reset --soft b2f6f4a735db688e7486f657a1b0f23ff0ec592e` to reset to that commit.

Did you see what the changes where that git thought were made to those files (with `git diff filename`)? These kind of things can happen when the mode of the file is changed (often not by you deliberately), or with older versions of git. In general avoid committing files that you know you haven't changed.

Once you are happy and want some comments or help then feel free to open a pull request.

**Comment by krischer** [comment]
> It doesn't look to me like you are on the list I was expecting, but I miss typed the name.
> @krischer, I was looking in the obspy/developers list but incorrectly said contributors. Is that the last @WayneCrawford needs to be on to push a new branch?

@WayneCrawford You have to accept the invitation to the developer team. You should have received an email from github.

**Comment by WayneCrawford** [comment]
It was in my spambox!  Maybe wild animals are not allowed?  Done.

Wayne

_______________________________
Wayne Crawford
CNRS Researcher
Institut de Physique du Globe de Paris
1, rue Jussieu
75238 Paris Cedex 05
+33 6 5151 1054

On 26 April 2019 at 12:00:10, Lion Krischer (notifications@github.com) wrote:

It doesn't look to me like you are on the list I was expecting, but I miss typed the name.
@krischer, I was looking in the obspy/developers list but incorrectly said contributors. Is that the last @WayneCrawford needs to be on to push a new branch?

@WayneCrawford You have to accept the invitation to the developer team. You should have received an email from github.

**Comment by megies** [comment]
> Maybe wild animals are not allowed?

Only those with less than 8 legs. :octocat:

**Comment by megies** [comment]
i think there was quite some work on nordic, so chances are this is obsolete.. not sure
