### ISSUE TITLE
Streams with uneven Traces can cause segfault with ar_picker

### ISSUE THREAD

**Issue by mhearne-usgs** [obspy/obspy#2382]
Versions:
 - Obspy 1.1.0
 - Python 3.7.3
 - OSX 10.13.6

Obspy and Python were both installed using conda and the conda-forge channel.

Summary:
If you have (enough) Stream objects with uneven Traces (Traces with different lengths), and you pass these to the ar_pick() method, you can eventually get a segmentation fault. Attached is a script which segfaults on my Mac and a colleague's.

If you uncomment the section in the script which slices the stream to match the smallest range of time common to all Traces, the segfault goes away.

We suspect that the C code behind ar_pick allocates memory for all three traces based on the length of one of them, and then writes the data without checking the length of the individual traces.  However, we'll leave it to the Obspy team to confirm this.

Workaround:

Ensure that each Stream's traces have the same number of points

[testfault.zip](https://github.com/obspy/obspy/files/3074639/testfault.zip)

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a short, self contained, correct example that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)

**Comment by krischer** [comment]
This is already fixed in ObsPy 1.1.1. Please update.

https://github.com/obspy/obspy/pull/2184
