### ISSUE TITLE
Change merge rights?

### ISSUE THREAD

**Issue by krischer** [obspy/obspy#2384]
Right now only very few people can merge code to `master` (only admins can right now). The `developer` group on the other hand has almost 50 people which I think is a bit too many to grant `master` merge rights. I propose to add a new group `maintainers` (or something like it) where we can add long-time contributors who we'd trust that they are careful with merging.

This would help us in dealing with the large amount of pull requests and people can merge pieces of the code in which they are confident.

**Comment by QuLogic** [comment]
I'm not up-to-date on _who_ to add, but I'm sure adding more maintainers couldn't hurt.

**Comment by megies** [comment]
Go ahead, having a few more people with merge rights might be necessary.

**Comment by krischer** [comment]
@obspy/maintainers You now should all be able to merge PRs into the `master` and `maintenance_xxx` branches. Please let me know if we should add more people and also please use this power to review and merge PRs! Let's see how this goes.!
