### ISSUE TITLE
CSS: Better error message for unsupported data encodings

### ISSUE THREAD

**Issue by HAMAMA-SAN** [obspy/obspy#2387]
from obspy.core import read
data=read("*****.wfdisc")
print(data)

but I got error>>>

TypeError: Unknown format for file ******.wfdisc

Thanks
Hamama

**Comment by jkmacc-LANL** [comment]
Hi, it’s hard to diagnose your issue without a [minimum working example](https://stackoverflow.com/help/mcve). Could you please post the content of your input file, to help someone reproduce your error?

**Comment by megies** [comment]
First of all whats your obspy version?

**Comment by megies** [comment]
Also, you can check if it's a problem with format autodetection by using `read("*.wfdisc", format='CSS')`

**Comment by HAMAMA-SAN** [comment]
Python 3.7

  File "C:\Users\CIA\Anaconda3\envs\obspy\lib\site-packages\obspy\io\css\core.py", line 134, in _read_css
    dtype = DTYPE[line[143:145]]

KeyError: b's3'

**Comment by jkmacc-LANL** [comment]
I suspect this is related to `s3` being an unsupported data type, combined with a non-specific error message.

**Comment by HAMAMA-SAN** [comment]
I17H1      BDF  1208736000.00000       -1  1115766  2008112  1208750400.00000   288000  20.0000000         0.000095        10.000000 MB2000 - s3 n                                                     ../2008/112/           ArchI17CI.1208736000.w          0       -1         25-APR-08

This is one line from wfdisc file .
yes i found "s3"

This mean that i have to remove s3?

Thanks in advance

**Comment by jkmacc-LANL** [comment]
`s3` is the binary file format (3-byte signed integer), which looks to be unsupported.  The [pisces](https://jkmacc-lanl.github.io/pisces/) project may be of help, as it has an `s3` reader.  Full disclosure: I’m the author.

**Comment by HAMAMA-SAN** [comment]
Thanks a lot for your help i will try it

**Comment by HAMAMA-SAN** [comment]
Dear jkmacc,
The problem was in s3 format i tried to save wfdisc again in s4 and it works well.

**Comment by jkmacc-LANL** [comment]
That’s great. Are you requesting a better error message, or docstring about supported data types?

**Comment by HAMAMA-SAN** [comment]
Can you tell me how I can use pisces project with ObsPy.?

**Comment by d-chambers** [comment]
@HAMAMA-SAN,
Have you looked through the [Pisces documentation](https://jkmacc-lanl.github.io/pisces/)? If you have additional questions about it the [Pisces github page](https://github.com/jkmacc-LANL/pisces) would be a better place to ask specific questions.

**Comment by HAMAMA-SAN** [comment]
Thanks for your reply
