### ISSUE TITLE
No module future

### ISSUE THREAD

**Issue by geovii** [obspy/obspy#2391]
I am using Spyder and i get the message:
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
File "C:\Python35\Lib\site‑packages\obspy\io\__init__.py", line 4, in 
ImportError: No module named 'future'

I have installed module future though.

**Comment by krischer** [comment]
How did you install ObsPy? Is `future` in `C:\Python35\Lib\site‑packages`? Also make sure you don't have multiple version of Python in your $PYTHONPATH (or the equivalent on windows) env variable.
