### ISSUE TITLE
Bundled autosummary will stop working with Sphinx 2

### ISSUE THREAD

**Issue by QuLogic** [obspy/obspy#2393]
Building docs with Sphinx 2 fails; I don't have the backtrace handy any more, but it's because of our bundled `autosummary` extension. In order to build I've attempted to rebase our copy with the version in 2.0.1 here: https://github.com/QuLogic/obspy/commit/2d0b2c3659407301871ab9b3ebf9ad9abec2ad08

It worked in Fedora 30 and above, but not 28 or 29. That works out to Sphinx >=1.8.4 and <=1.7.6.

I did not check whether the output made sense yet.

**Comment by d-chambers** [comment]
Should be solved by #2662
