### ISSUE TITLE
 How to draw PS waves on the graph?

### ISSUE THREAD

**Issue by KOUKILEO** [obspy/obspy#2394]
First-I am sorry that I am a newbie.and my English is not good as well.
I saw 12.6.2. AR Picker in the tutorial. 
He can find the position of the p and S waves.
Then How can I draw the vertical line of p and S waves on the waveform?
Like the red and green lines in The picture below.
![定地震](https://user-images.githubusercontent.com/20551345/57189298-95e5d100-6f3f-11e9-8e93-ce1bca762f5c.jpg)

**Comment by d-chambers** [comment]
Hi @KOUKILEO,

Have you seen the [plots from the picker docs](https://docs.obspy.org/tutorial/code_snippets/trigger_tutorial.html) ? These will get you close to what you are after, but you may need to employ some [matplotlib](https://matplotlib.org/tutorials/index.html) to get the rest of the way. 

It would be best to ask questions like this in the future on the [obspy gitter channel](https://gitter.im/obspy/obspy) or mailing list. Usually the github issues are used more for obspy development focused topics.

**Comment by megies** [comment]
Check out these mails on the mailing list:
http://lists.swapbytes.de/archives/obspy-users/2017-July/002483.html

Essentially you can use `UTCDateTime.matplotlib_date` to get an x-coordinate you can use for plotting on an matplotlib time x-axis.

To search the users mailing list use this one google:
`my search terms site:lists.swapbytes.de/archives/obspy-users/`

**Comment by megies** [comment]
@KOUKILEO you can also post to the mailing list if you can't find the information you need searching through the mailing list archive.

**Comment by KOUKILEO** [comment]
> @KOUKILEO如果找不到您需要通過郵件列表存檔搜索的信息，也可以發佈到郵件列表。

Ok, understand, thank you for your reply, I will try it out according to your statement, thank you very much for your help.

**Comment by KOUKILEO** [comment]
@megies  Ok, understand, thank you for your reply, I will try it out according to your statement, thank you very much for your help.
