### ISSUE TITLE
tr.stats.sac documentation needed

### ISSUE THREAD

**Issue by cnlg-lanl** [obspy/obspy#2395]
Lacking documentation on how to add sac fields to the tr.stats.sac property.  Would like to be able to export sac files with station and geographical information not currently contained in the tr.stats objects.

**Comment by jkmacc-LANL** [comment]
I can try to make that more clear in the module docs.  Thanks!

**Comment by megies** [comment]
I think there were a lot of changes in SAC and their docs in the meantime? Please reopen if still needed
