### ISSUE TITLE
'reported' not exists in evaluation_status in Origins

### ISSUE THREAD

**Issue by haneemedhat** [obspy/obspy#2396]
Hello,

Appreciate your support as we have an issue while updating the "evaluation_status" for Origins as we tried to set it to value="reported" but it failed with the error below:

`Error updating event: Setting attribute "evaluation_status" failed. Value "reported" could not be converted to type "Enum(["preliminary", "confirmed", "reviewed", "final", "rejected"])"`

However, When we checked the source code in the link below for the Enum of "evaluation_status", we found it not including the "reported" value but it already exists in its documentation just below the Enum definition.

https://github.com/obspy/obspy/blob/c1bca0655fde4e628dc6c8483b67025864eb85cc/obspy/core/event/header.py#L101

And just for your info, we use currently version 1.1.0 but it seems same issue in newer versions too.

**Comment by d-chambers** [comment]
Yes this is interesting, 

The docs clearly state that the status "reported" is supported. However, version 1.2 (revision 20130214b) of the [QuakeML spec](https://quake.ethz.ch/quakeml/docs/REC?action=AttachFile&do=view&target=QuakeML-BED-20130214b.pdf) (page 25) does not list reported as a supported value. We either need to correct the docs or support the status. Anyone know why "reported" made its way to the docs?

**Comment by megies** [comment]
Pushed a fix directly to maintenance branch
