### ISSUE TITLE
Rewrite mseed file

### ISSUE THREAD

**Issue by scg94** [obspy/obspy#2399]
Hi,

I am trying to write a mseed file second by second, without replacing what is already into it, but every time I write it, it replaces the other data. This is my code fragment:

```python
stats= {'network': 'AC', 'station': '999', 'location': '00',  
            'channel':'TS', 'npts': len(data), 
            'sampling_rate': 100, 'mseed' : {'dataquality' : 'D'}, 'starttime': starttime}
stream =Stream([Trace(data=data, header=stats)])
stream.write('/home/pi/SIATA/Software/Acelerometro/out.mseed',format='MSEED')
```
Could someone help me?
Thanks.

**Comment by megies** [comment]
I'm not sure what you're trying to do exactly, but my best guess is you want to do multiple `stream.write(..)` commands appending to the same file? If that's the case, try:

```
with open('/home/pi/SIATA/Software/Acelerometro/out.mseed', 'ab') as fh:
    for ... in ...:
        stream = ...
        stream.write(fh, format='MSEED')
```

In any case, for basic usage questions like this (as opposed to bug reports, enhancement proposals or feature requests), please go via the users mailing list in the future, thanks!

**Comment by megies** [comment]
Please feel free to reopen if this didn't answer your question.

**Comment by scg94** [comment]
> Please feel free to reopen if this didn't answer your question.

Hi @megies, thanks for your response, it was very helpful.

However, now I have another problem. I was able to rewrite the file, but now it creates multiple traces when I write it, I make myself understand?. Attached image.

![image](https://user-images.githubusercontent.com/26225871/58127296-a605dd80-7bda-11e9-8f55-f11dc646ff7c.png)

I want to rewrite the file, as I do now, but in one trace per file. Is this possible?. What I do, is write a file with 100 data per second of an acceleration component.

```python
...
xFile_name = open('/home/pi/SIATA/Datos/Ladera/Mseed/X/'+ActualName+'x.mseed','ab')
while 1:
      for x in range (datapoints): #It does this to take 100 data every second. 
            readData() #Read Acceleration
            #sample = int(float(data_Acc[3])*1000)
            dataX[x]= int(float(data_Acc[3])*1000) #sample
            timenow=datetime.datetime.now()
      statsX= {'network': 'GX', 'station': '999', 'location': '00',  
            'channel':'TS', 'npts': len(dataX), 
            'sampling_rate': 100, 'mseed' : {'dataquality' : 'D'}, 'starttime': starttime}
      streamX =Stream([Trace(data=dataX, header=statsX)]) 
      streamX.write(xFile_name,format='MSEED')
```

This works well for what I say, write the same file, which I appreciate, but it writes many traces (one per second), and I would like only one trace. Could this be possible?

I hope you can help me again. 
Thanks.

**Comment by d-chambers** [comment]
@scg94,
Once you have your `Stream` object you can iterate through each trace and save that. Is this what you are asking?

for example,
```python
import obspy

st = obspy.read()
for n, tr in enumerate(st):
    tr.write(f'mseed_file_{n}.mseed', 'mseed')
```
You might also find the [documentation on merging ](https://docs.obspy.org/packages/autogen/obspy.core.stream.Stream.merge.html) traces useful if you need to combine traces from the same channel.

**Comment by megies** [comment]
@scg94 when reading a MiniSEED file, it gets merged into as few as possible traces automatically, but that only works if there are no gaps in between traces. So my best guess is, the file you wrote has gaps.

As far as I can see, you are timestamping your data from inside the Python loop. This is your problem, timestamping should be done by the digitizer or some other means that can guarantee correct time stamps. Your timestamping is totally haphazard. If you can be sure the data you assembled earlier is gapless in time you should just increment your timing info in the for loop.

**Comment by scg94** [comment]
> @scg94 when reading a MiniSEED file, it gets merged into as few as possible traces automatically, but that only works if there are no gaps in between traces. So my best guess is, the file you wrote has gaps.
> 
> As far as I can see, you are timestamping your data from inside the Python loop. This is your problem, timestamping should be done by the digitizer or some other means that can guarantee correct time stamps. Your timestamping is totally haphazard. If you can be sure the data you assembled earlier is gapless in time you should just increment your timing info in the for loop.

@megies and @d-chambers, Thanks for your answer. I understand what you tell me, and I could do it, but I think there is something that can be a problem.

Every minute I store an information corresponding to other data of the accelerometer, which implies that I must leave the "for" cycle to save this data in a .txt file.

I don't know if it's very clear, I hope you can help me.

**Comment by krischer** [comment]
Hi @scg94.

Is this still an issue? In any case: I'm not entirely clear what you are asking? As @megies you should definitely rely on the times be the digitizer and not the computer time when writing the data (there is very likely much too much latency and other accuracy issues involved.

Also why do you have to leave the "for" loop to do something? Can you not just do it as part of the loop?
