### ISSUE TITLE
pip install -v -e not working

### ISSUE THREAD

**Issue by edwarzambrano** [obspy/obspy#2406]
* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a short, self contained, correct example that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)

**Comment by QuLogic** [comment]
Please fill in the template.

**Comment by megies** [comment]
Closing, feel free to reopen with appropriate information.
