### ISSUE TITLE
Issue calling IRIS DMC Library of Nominal Responses for Seismic Instruments in ObsPy

### ISSUE THREAD

**Issue by webersam** [obspy/obspy#2418]
Dear ObsPy team

I very like the IRIS DMC Library of Nominal Responses for Seismic Instruments and often use it with ObyPy. An issue came up with a new logger setting:
![image](https://user-images.githubusercontent.com/52156792/60007005-c14c8880-9671-11e9-8bc5-752054567b27.png)

* Python 3.7.2 (miniconda3)
* Platform: Linux
  - Distributor ID: Ubuntu
  - Description:    Ubuntu 18.04.2 LTS
  - Release:        18.04
  - Codename:       bionic

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a short, self contained, correct example that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)

Could you help me to get the correct response?

**Comment by krischer** [comment]
This looks like an issue in the NRL to me - this file: http://ds.iris.edu/NRL/dataloggers/nanometrics/centaur/10.off.lp.txt

has two sections `[100]`.

@dsentinel Do you know who to report this to? An alternative would be to use `strict=False` in the `ConfigParser`. @webersam: You could probably monkey-patch this in if it is urgent.

**Comment by rbbbenson** [comment]
This issue was resolved on June 24, 2019, modifying the RESP file entry in the Nominal Response Library.

**Comment by krischer** [comment]
I can confirm that ObsPy can now read this file. Thanks a lot for the quick reply!

**Comment by megies** [comment]
@krischer, for future reference: nrl_contact@iris.washington.edu see bottom of page http://ds.iris.edu/NRL/
