### ISSUE TITLE
Add a _get_coordinates() method in fdsn client

### ISSUE THREAD

**Issue by aringler-usgs** [obspy/obspy#2425]
Would there be a reason to not include a `_get_coordinates()` method `obspy.clients.fdsn`?  

A number of our processing methods could avoid pulling metadata twice if such a method existed.  I noticed something like this exists in `obspy.clients.arclink.client.Client.get_waveforms`.

Would there be a reason to not include this method?  We would be happy to do a pull request if such a method would be useful. 

@dwilson-usgs

**Comment by krischer** [comment]
The FDSN web services do not really have this functionality so even if we'd implement a ` ._get_coordinates()` method it would still have to query the stations endpoint. Currently one could already do `c.get_stations(...).get_coordinates(SEED_ID)` which I think is not much different to your proposed solution.

If you require something else I'd still rather see it implemented as a method on the `Inventory` class.

Why do you need to pull metadata twice?

**Comment by aringler-usgs** [comment]
I was thinking it might allow for grabbing the metadata when you grab the station.  Similar to the attach_response.  However, I suppose what you are suggesting would basically do the same thing.

**Comment by dwilson-usgs** [comment]
Hi Lion,

Currently you need to pull metadata separately because when you retrieve a
trace object via obspy.clients.arclink.client.Client.get_waveforms(),
obspy.core.trace.Stats does not have coordinate information for the trace.
A get_coordinates() method for a trace or stream would essentially be
a more efficient way to do c.get_stations(...).get_coordinates(SEED_ID) for
each trace.

Thanks,
Dave

**Comment by megies** [comment]
In general we nowadays favor canonical methods (fetch metadata into an `Inventory`) over comfy but magicky routines (attaching custom defined dictionaries to `Trace` objects). We believe having `attach_response()` and consorts was a bad design decision as it can lead to obscure problems later on, e.g. when merging traces later on, the attached metadata might get inconsistent. So we think that always having the metadata separate and using them on the fly whenever needed is the better and safer road.

On that note, we were discussing adding a new data structure to combine waveforms, metadata and maybe even event data, called e.g. a `DataSet`. That could also replace fetching waveforms with attach metadata by fetching waveforms and automatically fetching corresponding metadata into an Inventory inside the `DataSet`. But we never got around to properly finishing the design.. I was sure there must be an issue for it but I can't find it right now
