### ISSUE TITLE
raise ObsPyMSEEDFilesizeTooSmallError

### ISSUE THREAD

**Issue by YounessCHOUBIK** [obspy/obspy#2427]
Hello friends,

I got this error when trying to read a mseed file:
**raise ObsPyMSEEDFilesizeTooSmallError(msg)
ObsPyMSEEDFilesizeTooSmallError: The smallest possible mini-SEED record is made up of 128 bytes. The passed buffer or file contains only 23.**

Any solution!

**Comment by d-chambers** [comment]
Can you please attach the file?

**Comment by YounessCHOUBIK** [comment]
I have an ordinary mseed file which I downloaded from iris.com.
When I try the following code, the file is read without error:

```
tr = obspy.read("sparkTest/PM01.XB.mseed")
print(tr[0].stats)
```
But when I try this one I get the error above:

`tr = obspy.read(BytesIO("sparkTest/PM01.XB.mseed"), format='mseed').merge()[0]`

By the way I am trying to read a mseed file located in HDFS using spark and the first code does not work using spark.

**Comment by QuLogic** [comment]
> `BytesIO("sparkTest/PM01.XB.mseed")`

That's not how you initialize a `BytesIO` object. Please [read its docs](https://docs.python.org/3/library/io.html#io.BytesIO).

**Comment by YounessCHOUBIK** [comment]
I found that code in this Obspy workshop pdf (page 12)
[http://www.orfeus-eu.org/documents/bucharest2015/24Sept2015_03_P.Danecek-Python_and_ObsPy_an_opportunity_to_drive_the_innovation.pdf](url)

**Comment by derick-hess** [comment]
Not sure about pyspark or getting data from obspy or miniseed into a pyspark data frame but if oyu just need to read from HDFS I would maybe try using hdfs in pydoop

This will allow you pydoop.hdfs.open_file()
That should return a file handle to you which Obspy can probably read. 

This is a guess though as I don't use hadoop or HDFS, but that is the way I would go about trying.

**Comment by barsch** [comment]
the example in the linked PDF you are refering to shows how to read a byte string and not a file name - as suggested above read the associated

closing for now

> 
> 
> > `BytesIO("sparkTest/PM01.XB.mseed")`
> 
the example in the linked PDF you are refering to shows how to read a byte string and not a file name (plain string)

closing for now, feel free to reopen if you still can't figure it out
