### ISSUE TITLE
Problem get_waveform Error: FDSNNoDataException: No data available for request.

### ISSUE THREAD

**Issue by mariacarrizo** [obspy/obspy#2429]
Dear users

I have reviewed the inventory of stations and chosen a station an channel to plot:

from obspy.clients.fdsn import Client
client = Client("IRIS")

inv=client.get_stations(network="*",station="*",minlongitude=-10,maxlongitude=40,
                   minlatitude=20, maxlatitude=60,level="channel",channel='BH?')

inv[30]

Network TT (Seismic Network of Tunisia)
	Station Count: 1/3 (Selected/Total)
	2008-01-01T00:00:00.000000Z - 2599-12-31T23:59:59.000000Z
	Access: open
	Contains:
		Stations (1):
			TT.TATN (Tataouine, Tunisia, Africa)
		Channels (3):
			TT.TATN.00.BHZ, TT.TATN.00.BHN, TT.TATN.00.BHE

Then I try to obtain the waveform for the BHZ channel shown in the inventory using this:

from obspy.core import UTCDateTime
t = UTCDateTime('2016-12-17T10:51:0.00000' )
st=client.get_waveforms(network='TT',station='TATN', location='00',channel='BHZ',starttime=t,endtime=t+120*60 )

Then I obtain the following error:

FDSNNoDataException                       Traceback (most recent call last)
<ipython-input-14-1a3a5c5099d5> in <module>
      3 t = UTCDateTime('2016-12-17T10:51:0.00000' )
      4 
----> 5 st=client.get_waveforms(network='TT',station='TATN', location='00',channel='BHZ',starttime=t,endtime=t+120*60 )

~/anaconda3/lib/python3.6/site-packages/obspy/clients/fdsn/client.py in get_waveforms(self, network, station, location, channel, starttime, endtime, quality, minimumlength, longestonly, filename, attach_response, **kwargs)
    829         # Gzip not worth it for MiniSEED and most likely disabled for this
    830         # route in any case.
--> 831         data_stream = self._download(url, use_gzip=False)
    832         data_stream.seek(0, 0)
    833         if filename:

~/anaconda3/lib/python3.6/site-packages/obspy/clients/fdsn/client.py in _download(self, url, return_string, data, use_gzip)
   1381             debug=self.debug, return_string=return_string, data=data,
   1382             timeout=self.timeout, use_gzip=use_gzip)
-> 1383         raise_on_error(code, data)
   1384         return data
   1385 

~/anaconda3/lib/python3.6/site-packages/obspy/clients/fdsn/client.py in raise_on_error(code, data)
   1705     if code == 204:
   1706         raise FDSNNoDataException("No data available for request.",
-> 1707                                   server_info)
   1708     elif code == 400:
   1709         msg = ("Bad request. If you think your request was valid "

FDSNNoDataException: No data available for request.
Detailed response of server:

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a short, self contained, correct example that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)

**Comment by heavelock** [comment]
IRIS datacenter seems not to have requested data. The other provider, Geofon, who is indicated here https://www.fdsn.org/networks/detail/TT/, has it.

http://geofon.gfz-potsdam.de/fdsnws/dataselect/1/query?starttime=2016-12-11T10%3A50%3A00&endtime=2016-12-11T12%3A50%3A00&network=TT&station=TATN&location=00&channel=BHZ&nodata=404

Change argument of Client to 'GFZ' and it should work. Here is a list of all available clients:
https://docs.obspy.org/packages/obspy.clients.fdsn.html

For the future, I think that this type of questions would be better suited for the Obspy's mailing list.

**Comment by maaz-shahid99** [comment]
FDSNNoDataException("No data available for request.",)
`inv = client.get_stations(network="XA", station="S11", channel="SPZ", level="response", starttime=t1)`

I'm requesting data for Apollo alsep missions from IRIS. Is the data not available? Although I can download the data from the iris website directly
