### ISSUE TITLE
Is there a way to get manually picked P wave arrival time by reading seismic wave data?

### ISSUE THREAD

**Issue by BimLee** [obspy/obspy#2430]
Recently, I was working on the project of earthquake warning, which requires the manual picking P wave arrival time to compare with the machine learning of P wave arrival time,  I downloaded the waveforms data (.mseed) and stations data (XML) through  obspy. Clients. Fdsn. mass_downloader, So how do I get the manual picking P wave arrival time instead of ar_pick()?

**Comment by megies** [comment]
Please use the obspy users mailing list for such general usage questions, thanks.
