### ISSUE TITLE
get meta data from npz

### ISSUE THREAD

**Issue by sadalsuud** [obspy/obspy#2431]
There is a way for I can get sampling_rate as in 3.1 https://docs.obspy.org/tutorial/code_snippets/reading_seismograms.html but from ppsd ? I load a npz and then how I can get get sampling_rate? ... 

Any comments or suggestions that can help me are welcome

**Comment by megies** [comment]
```python
ppsd = PPSD.load_npz(..)
ppsd.sampling rate
```
?
