### ISSUE TITLE
NotImplementedError with equal aspect on 3D axes introduced in Matplotlib 3.1.0

### ISSUE THREAD

**Issue by heavelock** [obspy/obspy#2437]
Matplotlib in version 3.1.0 instead of showing warning raises NotImplementedError when trying to set up an equal aspect ratio in 3DAxes object.

In tests it affects:
`obspy.imaging.tests.test_source.RadPatternTestCase`

Dirty workaround would be probably just to remove from `obspy.imaging.source:_setup_figure_and_axes` kwarg containing equal aspect ratio. As https://github.com/matplotlib/matplotlib/issues/1077#issuecomment-14006279 points out, results given by setting the equal aspect ratio are just wrong.

PR from matplotlib:
https://github.com/matplotlib/matplotlib/pull/13474#issue-254696667

**Comment by d-chambers** [comment]
@heavelock does this still over on master? I thought I fixed it in #2424 but maybe there is another case I missed.

**Comment by heavelock** [comment]
You are right, my local copy was not fully fetched with the original repo but with my fork. Everything passes properly.
