### ISSUE TITLE
Speed of read fcnt file with same time  length is quite different

### ISSUE THREAD

**Issue by xichaoqiang** [obspy/obspy#2439]
* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
Obspy 1.1.1, Python3.6, Windows 64bit
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
Anaconda
  -  If possible please supply a short, self contained, correct example that
     demonstrates the issue.
I try read 50 min length data from two fcnt file, but I found that time is quite different.
file1 is about 1 hour length  ,read 50 min time is about 0.2s
file2 is bout 115hour length , read 50 min time is about 23.2s 
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)
<pre><code>def print_readtime(fcnt_file):
#read head to get starttime and endtime
    hd=obspy.read(fcnt_file, format='rg16',headonly=True)
    pts=hd.traces[0].meta.npts #15000
    dt=hd.traces[0].meta.delta #0.002 ,each trace=30s
    start_time=hd.traces[0].meta.starttime
    end_time=hd.traces[-1].meta.endtime
    end_time1=start_time+(pts*100-1)*dt #100*30s=50 min
#to get readfile time
    t1 = time()
    st=obspy.read(fcnt_file, format='rg16',merge=True,start_time=start_time,end_time=end_time1) 
#read 50min data
    t2=time()
#print information
    print("total time of fcnt file is " + str((end_time - start_time) / 3600) + " h")
    print("read fcnt (50 min) time= "+str(t2-t1)+" s")
    print(pts)
    print(dt)
fcnt_file1=r"F:\20190506jinhua\1.fcnt"
fcnt_file2=r"F:\20190506jinhua\data\Other\1\1.0.0.fcnt"
print_readtime(fcnt_file1)
print_readtime(fcnt_file2)</code></pre>
Output information
<pre><code>
total time of fcnt file is 1.166666111111111 h
read fcnt (50 min) time= 0.21045732498168945 s
15000
0.002
total time of fcnt file is 115.74999944444446 h
read fcnt (50 min) time= 23.204906225204468 s
15000
0.002
</code></pre>

**Comment by ThomasLecocq** [comment]
Yep, it's normal, even if you pass start time and end time, the whole file is parsed it seems, which takes time...

**Comment by d-chambers** [comment]
@xichaoqiang, I would recommend you select the data you need, or might need, and use obspy to convert it to a different format and size that is more conducive to your application.

**Comment by xichaoqiang** [comment]
Thanks I got it
