### ISSUE TITLE
Attribute Error with numpy.fft.fftpack in remove_response

### ISSUE THREAD

**Issue by khannema** [obspy/obspy#2446]
-  ObsPy version 1.1.1.1 , Python version 3.7 and Platform majaro (linux)
-  from source (Arch User Repository)
while executing the following line:  
st.remove_response(pre_filt=pre_filt,output='VEL',inventory=inv)
I receive the following error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-7f230bce6785> in <module>
      1 pre_filt = (0.005, 0.006, 60.0, 65.0)
----> 2 st.remove_response(pre_filt=pre_filt,output='VEL',inventory=inv)

/usr/lib/python3.7/site-packages/obspy/core/stream.py in remove_response(self, *args, **kwargs)
   3067         """
   3068         for tr in self:
-> 3069             tr.remove_response(*args, **kwargs)
   3070         return self
   3071 

</usr/lib/python3.7/site-packages/decorator.py:decorator-gen-153> in remove_response(self, inventory, output, water_level, pre_filt, zero_mean, taper, taper_fraction, plot, fig, **kwargs)

/usr/lib/python3.7/site-packages/obspy/core/trace.py in _add_processing_info(func, *args, **kwargs)
    233     info = info % "::".join(arguments)
    234     self = args[0]
--> 235     result = func(*args, **kwargs)
    236     # Attach after executing the function to avoid having it attached
    237     # while the operation failed.

/usr/lib/python3.7/site-packages/obspy/core/trace.py in remove_response(self, inventory, output, water_level, pre_filt, zero_mean, taper, taper_fraction, plot, fig, **kwargs)
   2720             recognizable by matplotlib e.g. '.png').
   2721         """
-> 2722         limit_numpy_fft_cache()
   2723 
   2724         from obspy.core.inventory import PolynomialResponseStage

/usr/lib/python3.7/site-packages/obspy/core/util/misc.py in limit_numpy_fft_cache(max_size_in_mb_per_cache)
    612     for cache in ["_fft_cache", "_real_fft_cache"]:
    613         # Guard against different numpy versions just to be safe.
--> 614         if not hasattr(np.fft.fftpack, cache):
    615             continue
    616         cache = getattr(np.fft.fftpack, cache)

AttributeError: module 'numpy.fft' has no attribute 'fftpack'

I "solved" it by commenting out line 2722 in  /usr/lib/python3.7/site-packages/obspy/core/trace.py.

**Comment by calum-chamberlain** [comment]
See Issue #2434 and subsequent PR: #2435 

Thanks for reporting this, but I think it should be fixed in master now.

**Comment by khannema** [comment]
Ok thank you!
