### ISSUE TITLE
UTCDateTime parsing of dashed separated format

### ISSUE THREAD

**Issue by d-chambers** [obspy/obspy#2447]
In the past I have been able to use `UTCDateTime` to parse strings whose hour, minute, and second are separated by `'-'` as well as `:`. I am not sure if this is officially supported but I haven't run into any issues until today. However, I found that if only an hour and minute is provided it does not work. For example,

```python
from obspy import UTCDateTime
print(UTCDateTime('2019-01-01T10-33-00'))  #  2019-01-01T10:33:00.000000Z
print(UTCDateTime('2019-01-01T10-33'))  #  2019-01-02T19:00:00.000000Z
print(UTCDateTime('2019-01-01T10-33-00'))  #  2019-01-01T10:33:00.000000Z
```

I am using Ubuntu 18, python 3.7 and obspy master. I think we should consider this a bug and either 1) fix it, or 2) raise an error if users (like me) are abusing the `UTCDateTime` string parsing. 

Edit: fixed third code example

**Comment by barsch** [comment]
the second print line is not a bug as ```2019-01-01T10-33``` is a valid ISO 8601 formated date/time string and gets interpreted as such - its basically the same as ```2019-01-01T10:00:00-33:00```, which results into ```2019-01-02T19:00:00.000000Z```

ofc a time zone of ```-33:00``` does not exist and hours are limited to 00 to 23, however I couldn't find a limitation of the hour given within the timezone indicator

anyway I suggest to either remove the ```T``` within the string you are using or use a proper ISO 8601 format, like having a ```:``` as divider in the time string, e.g. ```2019-01-01T10:33```

I don't get the third print line in your example ....

**Comment by d-chambers** [comment]
Thanks @barsch,

I had forgotten that ISO 8601 specifies time zones in this way, and it didn't even cross my mind that it might be the case as a timezone of -33 doesn't make a lot of sense.  I suspect specifying a timezone in a `UTCDateTime` constructor is uncommon, but thanks for clearing this up.

I guess the confusion comes from `UTCDateTime`'s extremely flexible (and sometimes surprising) parsing of time strings which can change significantly based on whether the string complies with ISO 8601. A few examples:

```python 
import obspy
# These three strings are all very similar, and at first glance they appear to indicate the
# same time. However, the first string has a time zone indication, the second one 
# indicates minutes, the third a time zone of -2:33
print(obspy.UTCDateTime('2019-01-01T02:02-33'))  #  2019-01-02T11:02:00.000000Z
print(obspy.UTCDateTime('2019-01-01T02-02-33'))  # 2019-01-01T02:02:33.000000Z
print(obspy.UTCDateTime('2019-01-01T02-02:33'))  # 2019-01-01T04:33:00.000000Z

# The meaning of the last char group is set to seconds if a decimal is found (skipping minutes)
print(obspy.UTCDateTime('2019-01-01T02-02.33'))   # 2019-01-01T02:00:02.330000Z

#  This one is particularly confusing as the T character enables the interpretation of time zones 
print(obspy.UTCDateTime('2019-01-01T02-02'))  #  2019-01-01T04:00:00.000000Z
print(obspy.UTCDateTime('2019-01-01 02-02'))  #  2019-01-01T02:02:00.000000Z
```
The `iso8601` keyword is handy for bringing a bit more discipline to the parsing. One just has to be aware, as I am now thanks to your reply, of the possibility of part of the string indicating a time zone rather than a minute value.

In hindsight, `UTCDateTime`s constructor might be a bit too flexible. However, the cost of changing anything now certainly outweighs the benefits. Do you think it would be worth adding a note about these potential gotchas in the docstring of `UTCDateTime`?
