### ISSUE TITLE
massdownloader domain 

### ISSUE THREAD

**Issue by ArthurRodgers** [obspy/obspy#2462]
I'm running Obspy '1.1.0' installed with conda 4.6.1
I'm having a problem with user defined polygon (rotated rectangle) with massdownloader

The code below tests my class and returns boolean if lon, lat point is in domain. However, I'm getting no waveforms returned with my domain. When I run with a simple Rectangular domain I get data back. Wondering if my implementation  misses something obvious or if this is unsupported or has changed.

```python
import numpy as np
from obspy.clients.fdsn.mass_downloader import Domain
from shapely.geometry import Point
from shapely.geometry.polygon import Polygon

class Arbitrary_Rectangle(Domain):
    def __init__(self, lons_vect, lats_vect):
        Domain.__init__(self)
        lons_lats_vect = np.column_stack((lons_vect, lats_vect))        
        self.polygon = Polygon(lons_lats_vect)
        self.b = [ min(lons_vect), min(lats_vect), max(lons_vect), max(lats_vect) ]
    
    def get_query_parameters(self):
        return {"minlatitude": self.b[1],
                "minlongitude": self.b[0],
                "maxlatitude": self.b[3],
                "maxlongitude": self.b[2]}

    def is_in_domain(self, longitude, latitude):
        if self.polygon.contains(Point(longitude,latitude)):
            return True
        return False

lons_vect = [ -120.64040, -121.91833, -123.85736, -122.56127, -120.64040 ]
lats_vect = [ 37.04718, 36.31746, 38.42426, 39.17461, 37.04718 ] 
domain = Arbitrary_Rectangle(lons_vect, lats_vect)

lat = 38.5
lon = -122.0
print(lon, lat, domain.is_in_domain(lon, lat))
```

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a short, self contained, correct example that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)

**Comment by megies** [comment]
I don't see any problems with this. Can you post an example mass downloader script that shows your case of no data returned? I would recommend to start with a working example with a builtin unrotated rectangle and then do the same with a just slightly rotated rectangle at the same location, to see if it works.

**Comment by ArthurRodgers** [comment]
Thanks Tobias. I discovered error - simply flipping order of lat, lon in domain.is_in_domain method. I've modified the class to handle arbitrary polygons. Maybe others would find this useful.

The test below is verified to work for requesting BK network broadband data for Northern California and a rotated rectangular domain spanning the USGS 3D detailed model of the region.

# massdownloader_test.py

from obspy import UTCDateTime
from obspy.clients.fdsn import Client
from obspy.clients.fdsn.mass_downloader import Domain, RectangularDomain, Restrictions, MassDownloader
from shapely.geometry import Point
from shapely.geometry.polygon import Polygon
import os
import sys
import numpy as np

# Class for arbitrary  polygon
class Arbitrary_Polygon(Domain):
    """
    Class to define arbitrary polygon
    """
    def __init__(self, vertices):
        """
        Inherits obspy.clients.fdsn.mass_downloader.Domain
        Polygon is defines by vertices, a numpy array of longitude, latitude pairs
        The polygon must be closed, that is last (lon, lat) values must be equal to the first values
        """
        Domain.__init__(self)
        if vertices.shape[1] != 2:
            sys.exit('Problem with vertices.shape: '+vertices.shape)
        if vertices[0,0] != vertices[-1,0] and vertices[0,1] != vertices[-1,1]:
            vertices.append([vertices[0,0], vertices[0,1]], axis=0)
        self.polygon = Polygon(vertices)
        self.minlongitude = min(vertices[:,0])
        self.maxlongitude = max(vertices[:,0])
        self.minlatitude = min (vertices[:,1])
        self.maxlatitude = max(vertices[:,1])
    
    def get_query_parameters(self):
        """
        Returns minimum and maximum values of latitude and longitude of polygon
        """
        return {"minlatitude": self.minlatitude ,
                "minlongitude": self.minlongitude,
                "maxlatitude": self.maxlatitude,
                "maxlongitude": self.maxlongitude}

    def is_in_domain(self, latitude, longitude):
        """
        Returns boolean if (latitude, longitude) location is within (True) or outside (False) polygon
        """
        if self.polygon.contains(Point(longitude, latitude)):
            return True
        return False

# Data center
data_center = 'NCEDC'
# Time for 2019/01/04 Berkeley earthquake Mw 4.4
tstart = UTCDateTime("2018-01-03")
tend = UTCDateTime("2018-01-05")
# Smaller - East Bay domain
min_lon = -122.7
max_lon = -121.5
min_lat = 37.4
max_lat = 38.3
# Magnitude limits
min_mag = 4.0
max_mag = 4.5
# Parameters for seismogram time length
min_length = 0.25
tbefore = 10.
tafter = 180.

client = Client(data_center)
cat_ncss = client.get_events(starttime=tstart, endtime=tend,
                              minlatitude=min_lat, minlongitude=min_lon, 
                              maxlatitude=max_lat, maxlongitude=max_lon,
                              minmagnitude=min_mag, maxmagnitude=max_mag,
                              catalog='NCSS')

# Create directory for this event and raw data 
event_id = str(cat_ncss[0].resource_id).split('/')[-1]
if not os.path.isdir(event_id):
    os.mkdir(event_id)
raw_wf_data_dir = event_id+'/RAW/'
if not os.path.isdir(raw_wf_data_dir):
    os.mkdir(raw_wf_data_dir)
sta_metadata_dir = raw_wf_data_dir+'/_station_xml/'
if not os.path.isdir(sta_metadata_dir):
    os.mkdir(sta_metadata_dir)

# Report number of events
print ('cat_ncss found: '+str(cat_ncss.count())+' event(s)')   
evlon = cat_ncss.events[0].origins[0].longitude
evlat = cat_ncss.events[0].origins[0].latitude

# Standard Rectangluar domain
domain_r = RectangularDomain(minlatitude=min_lat, maxlatitude=max_lat, minlongitude=min_lon, maxlongitude=max_lon)

# Arbitrary Rectangular domain
# ordered pairs of (lon, lat) starting in upper left, moving clockwise
# This test defines a closed polygon
#lons_vect = [ min_lon, max_lon, max_lon, min_lon, min_lon ]
#lats_vect = [ max_lat, max_lat, min_lat, min_lat, max_lat ]
# This test does not close the polygon
#lons_vect = [ min_lon, max_lon, max_lon, min_lon ]
#lats_vect = [ max_lat, max_lat, min_lat, min_lat ]
# This test uses a rotated rectangle defined by the USGS Detailed Model of the SFBA
lons_vect = [ -120.64040, -121.91833, -123.85736, -122.56127, -120.64040 ]
lats_vect = [ 37.04718, 36.31746, 38.42426, 39.17461, 37.04718 ] 
vertices = np.column_stack((lons_vect, lats_vect))
domain_ar = Arbitrary_Polygon(vertices)

net = 'BK'
channels = [ 'BH[ZNE]' ]
locations = ['00', '', '01']

# Restrictions for waveform query, this time use minimum length restriction
restrictions = Restrictions(starttime=cat_ncss[0].origins[0].time - tbefore,
        endtime=cat_ncss[0].origins[0].time + tafter,
        network=net,
        channel_priorities=channels,
        location_priorities=locations,
        reject_channels_with_gaps=True,
        minimum_length=min_length,
        minimum_interstation_distance_in_m=1)        
# Use massdownloader - check which domain you are using in mdl.download
mdl = MassDownloader(providers=[data_center])

try:
    mdl.download(domain_ar, restrictions, mseed_storage=raw_wf_data_dir,
                 stationxml_storage=sta_metadata_dir)
except:
    print ('\n\n#########     DOWNLOAD ERROR: moving on      ##########\n\n')

**Comment by megies** [comment]
Glad you worked it out. This is relying on shapely, so I'm not sure if we should have it we might not want to include it in the code base - we could add it as an example in `Domain` docstring though, same as the example with the country border example.
Closing for now, feel free to make a PR for inclusion in documentation as an example
