### ISSUE TITLE
Remove annoying print statement

### ISSUE THREAD

**Issue by rizac** [obspy/obspy#2474]
https://github.com/obspy/obspy/blob/b99a2d6d0443e517e6b46f37cb751f4c1c184390/obspy/signal/spectral_estimation.py#L838

It's probably a leftover (looks like the typical print statement issued for some kind of debug, and as often happens, there forgotten). You will excuse me if I left it to be done (I do not issue a PR for such a small detail), I hope you can remove it in future releases, it's obviously really annoying when calling that function in a process handling stderr stdout and warnings captured.

Thanks
R

**Comment by megies** [comment]
I'll remove this, but I'm curious how you are running into this at all to be honest. Are you calling `__process()` manually?

**Comment by rizac** [comment]
No need to call `__process()` manually, I simply call `psd.add(trace)`:

https://github.com/obspy/obspy/blob/b99a2d6d0443e517e6b46f37cb751f4c1c184390/obspy/signal/spectral_estimation.py#L807

(whether that 'if' branch is a remote possibility, it's another matter. Anyway, we are processing millions of segments thus in our case we might jump there sometimes)

**Comment by megies** [comment]
This `while t1 + self.ppsd_length - tr.stats.delta <= t2:` is supposed to make sure there is enough data to compute a full slice on the remainder of the Trace. That's why I'm asking, that print shouldn't be encountered, so I'm curious how you ended up getting it.
