### ISSUE TITLE
UTCDateTime, np.datetime64, and np.timedelta64

### ISSUE THREAD

**Issue by d-chambers** [obspy/obspy#2479]
It seems `np.datetime64` and `np.timedelta64` are becoming very widely-used. However, `UTCDateTime` currently doesn't interact with these objects as one would expect:

```python
import numpy as np
from obspy import UTCDateTime as UTC

# init numpy time representations
npdt = np.array(['2000-01-01', '2012-01-01T01:10'], dtype='datetime64[ns]')
offset = np.timedelta64(3, 'M')

# init obspy time representation
utc = UTC('2010-01-01')

# gt or lt
utc < npdt  # simply returns False
utc > npdt  # also returns False
npdt < utc  # returns an array of False 
npdt > utc  # return an array of True

# adding/subtracting numpy time delta 
utc + offset  # TypeError raised
offset + utc  # Also raises TypeError
``` 
So, I guess we have four options:

1. We ignore numpy's time representation and continue doing our own thing with `UTCDateTime`.

2. We try to make `UTCDateTime` recognize numpy's time formats and play nicely with them.

3. We *adopt* numpy's time formats as the core of `UTCDateTime` (maybe subclassing  `datetime64`).

4. We *outright replace* `UTCDateTime` with numpy's data structures.

Option 1 doesn't seem wise as we would effectively be alienating ourselves from any future numpy improvements, as well as reinforcing conceptual (ie API) barriers between numpy and obspy.

At first glance Option 2 appears to be the least disruptive, but it may be harder to implement than one might think. For example, if we step through the following code:
```python
npdt < utc
```
numpy's broadcasting machinery ends up calling `UTCDateTime.__gt__` for each element of the datetime64 array with the `other` argument as an `int`. The meaning of this `int` depends on the units specified upon initialization but in this case it means nanoseconds from epoch time. However, `UTCDateTime` interprets real numbers as seconds from epoch time, eg
```python
utc > 10  # True, utc is gt epoch time + 10 seconds
```
So we would either have to  guess at the units of the `other` parameter based on its size (not a good idea) or somehow get the contextual info about the units (not sure if this is possible/feasible).

I am not sure if option 3 would solve the issues mentioned with option 2. We would need to look more into it. 

Option 4 would, of course, be very disruptive and probably break lots, if not most, codes. 

I think @markcwill suggested option 3/4 at one point in time but I don't remember where. Also of note is the conversation on #2072. 

Any thoughts?

**Comment by markcwill** [comment]
Thanks for looking into this! I like (4) but I think (3) is the most realistic near-term. This helps clear up the "units" issue which the numpy type handles much better than what we are referring to as "precision" which is not quite accurate. If you need these things now, then I think (2) is a good idea if possible.

As long as we have the hard numpy dependency in the `tr.data` array (which is forever/foreseeable future) I think it would be wise to have a plan to migrate to `datetime64` as much as possible, since once we pass the "minimum numpy version", this type is guaranteed to be available and should be well supported. It seems like there will be a LOT of advantages to using a standard data type for this.

**Comment by megies** [comment]
regarding (2), we could show a warning when comparing an `int` with a `UTCDateTime`. Personally, I'd never do such a thing anyway, I'd be way to scared about what actually is done. I'd always either convert my integer into a UTCDateTime for comparison or vice versa.
And then we could do a proper comparison if the UTCDateTime object is in front actually (this still will be tricky, consider the `precision` mechanics)

There's also an option (1.5) I think, we could have some helper conversion routines (similar to `UTCDateTime.matplotlib.date`) to ease interactions a bit.

(3) and (4) are **massive** changes that would take a big amount of time/work. Not sure if it's worth it in the short/mid term. I'd say, more important to get releases out for now.

**Comment by d-chambers** [comment]
>There's also an option (1.5) I think, we could have some helper conversion routines (similar to UTCDateTime.matplotlib.date) to ease interactions a bit.

Ya, I think this is a sensible path forward. I did a bit of it in #2480.

If we are going to do anything **massive** it should be done before the release of 2.0, so best be thinking about it.

**Comment by megies** [comment]
Actually, I think we agreed on releasing 2.0 as soon as 1.2.0 is out pretty much, with same functionality and only dropping Py2/3 compat. That might be easiest for any pending PRs to adapt to Python3-only codebase after the big Py2 drop.

**Comment by megies** [comment]
Obsolete, since we switched to using integer nanoseconds for our time base
