### ISSUE TITLE
Trace trim silently fails to pad when trace is not a masked array

### ISSUE THREAD

**Issue by nienkebrinkman** [obspy/obspy#2481]
Hi guys, 
I have been trying to trim a trace where I wanted to keep the entire trace length, 
which means i pass `pad = True` and `fill_value = myfloat` to `trace.trim`. However obspy uses `numpy.ma.MaskedArray.filled`. My trace object contain data as `numpy.ndarray` for which `trace.data.filled()` fails. It does so silently without letting me know. 

Additionally, when you call `trace.data.filled()` you do so without passing the `fill_value` seen in the line below:
https://github.com/obspy/obspy/blob/79a83855c8c1498d9370c2a4e063ace256f2be27/obspy/core/trace.py#L1157

The same issue was discussed in the mailing list (http://lists.swapbytes.de/archives/obspy-users/2013-March/000885.html), but never answered.

**Comment by d-chambers** [comment]
Hi @nienkebrinkman, do you have a small reproducible example you can post here?

**Comment by nienkebrinkman** [comment]
Hi @d-chambers ,
 
I attached an example, where I create a trace with 10000 samples. Then I trim this trace and I would like to keep the 10000 samples and fill the other values with zero (`pad = True` and ` fill_value = 0.0`, but instead it returns 801 samples.

```
import obspy
from obspy.core.trace import Trace
import numpy as np

# Creating trace in obspy
npts = 10000
trace_data = np.random.rand(npts)

or_time = obspy.UTCDateTime(2019,10,15,10,0,0) # Origin Time
dt = 1/20.

Trace = Trace(trace_data, header={"starttime": or_time, 'delta': dt})

# Start and stop time of the part I would like:
start = obspy.UTCDateTime(2019,10,15,10,1,0)
end = obspy.UTCDateTime(2019,10,15,10,1,40)

# Trim the trace (I would like to have the other values set to zero)
Trace.trim(starttime=start, endtime=end, pad=True, nearest_sample=True, fill_value=0.0)
```

**Comment by trichter** [comment]
Hi,

I think there is a misconception. pad is used to trim at time points outside the time frame of the original trace, filling the trace with the given ``fill_value``. (from the documentation)

Maybe the following code does what you want to achieve?

```
trace.slice(None, start).data[:] = 0
trace.slice(end, None).data[:] = 0
```

or with the use of the ``pad`` parameter:

```
orig_start = trace.stats.starttime
orig_end = trace.stats.endtime
trace.trim(start, end).trim(orig_start, orig_end, pad=True, fill_value=0)
```

I did not test both code snippets.

**Comment by megies** [comment]
:+1:  slice what you want to change and modify array of the slice

**Comment by megies** [comment]
Please reopen if it's not clear yet.
