### ISSUE TITLE
Current CI test fails in min/max caused by recent future

### ISSUE THREAD

**Issue by megies** [obspy/obspy#2486]
Just for the record, current CI test fails like this one  (https://travis-ci.org/obspy/obspy/jobs/597519495#L3660) are caused by future 0.17-0.18.1 and will be fixed by PythonCharmers/python-future#514

Basically current future breaks with min/max over length-1 generators:

```python
from future.builtins import *
min(x for x in [1])
```

```
Traceback (most recent call last):
  File "/tmp/futtest.py", line 4, in <module>
    min(x for x in [1])
  File "/home/megies/git/python-future/src/future/builtins/new_min_max.py", line 9, in newmin
    return new_min_max(_builtin_min, *args, **kwargs)
  File "/home/megies/git/python-future/src/future/builtins/new_min_max.py", line 46, in new_min_max
    return _builtin_func(args[0])
ValueError: min() arg is an empty sequence
```

**Comment by megies** [comment]
The upstream fix in `future` has been merged into master

**Comment by ThomasLecocq** [comment]
@megies this vanishes with 2.0.0 right ?

**Comment by megies** [comment]
Yeah no more future ( 0_o )
