### ISSUE TITLE
Cannot write zero sample rate trace data as miniSEED

### ISSUE THREAD

**Issue by nick-iris** [obspy/obspy#2488]
**Description of bug**
ObsPy cannot write zero sample rate miniSEED. This is important for non time series data, such as LOG channels.

**To reproduce the bug**
1.) Download some zero sample rate LOG data from the DMC.

e.g. http://service.iris.edu/fdsnws/dataselect/1/query?network=YW&channel=LOG&starttime=2016-01-01&endtime=2016-12-31&nodata=404

2.) Read this 0 sample rate data using ObsPy

```python
import obspy
st = obspy.read("fdsnws-dataselect_2019-10-23t18_11_00z.mseed")
```

3.) Try to write this data as miniSEED

```python
st.write('fdsnws-dataselect_2019-10-23t18_11_00z.mseed', format='MSEED')
```

resulting in the following exception

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda2/lib/python2.7/site-packages/obspy/core/stream.py", line 1443, in write
    write_format(self, filename, **kwargs)
  File "//anaconda2/lib/python2.7/site-packages/obspy/io/mseed/core.py", line 626, in _write_mseed
    (1.0 / trace.stats.sampling_rate * HPTMODULUS) % 100 != 0:
ZeroDivisionError: float division by zero
```

**System info**
  -  ObsPy version: 1.1.1
  - Python version: 2.7 
  - Platform: OSX
  - ObsPy was installed using Anaconda

**Comment by megies** [comment]
This is easy to fix, I just tested it, only this if/else needs changing.
With this change the writing works fine it seems:

```python
 641         if starttime % 100 != 0 or \
 642            (trace.stats.sampling_rate and (1.0 / trace.stats.sampling_rate * HPTMODULUS) % 100 != 0):
 643             use_blkt_1001 = True
```


But I'm not aware how this blockette 1001 stuff should be treated with 0 sps data, so I'll leave it to @krischer

**Comment by megies** [comment]
ping @krischer

**Comment by megies** [comment]
@krischer I will close this aplying the above fix if I don't hear any other feedback til tomorrow, see https://github.com/obspy/obspy/issues/2488#issuecomment-546371100

**Comment by krischer** [comment]
#2509 already exists ;-P

**Comment by megies** [comment]
It didn't at the time of writing ;-P
