### ISSUE TITLE
Set up CODEOWNERS file

### ISSUE THREAD

**Issue by megies** [obspy/obspy#2490]
We could set up a CODEOWNERS file to automatically mention/request reviews from people in charge of some parts of the code base, see https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

It's not really doing much, rather some meta thingy I guess, though. Still might help to track who's in charge of some parts of the code (esp. for I/O plugins)

**Comment by trichter** [comment]
Done in #3208
