### ISSUE TITLE
Sensitivity to order in inventory 

### ISSUE THREAD

**Issue by hurstk** [obspy/obspy#2491]
<!--

Bug report

Title:  Sensitivity to order in inventory 
Submitter:  Ken Hurst  (ken.hurst@jpl.nasa.gov)
Date: 28 October 2019

Obspy version:  1.1.0
Python version: Python 3.6.8 :: Anaconda, Inc.
Mac OS:  OSX 10.13.6

Description:
If the order of components in the station.xml file is for example V,W,U, instead of the usual U,V,W, then when rotating to ZNE, the rotation matrix is permuted, and hence the rotation is incorrect. 

I have included enough files to demonstrate the problem:

East_bad.png                            Plot showing the incorrect rotation result
East_good.png				Plot showing a proper rotation result
INV					Directory containing both good and bad inventories
Logfile.bad				"Bad" rotation log file with some debug print statements
Logfile.good				"Good" rotation log file with some debug print statements
POS-response_ACC.msd			Input mseed file - this has had the instrument response removed and is expressed in acceleration.
POS-response_ACC_ZNEbad.msd		Output mseed file with incorrect rotation produced with the rortation from the inventory file with V,W,U channel order
POS-response_ACC_ZNEgood.msd		Output mseed file with proper rotation produced with the rortation from the inventory file with U,V,W channel order
bin					Directory with the "ObsRotate2enz" python program that I used

./INV:					
Inventory_Station_Order_Difference	Output of grep showing the order of the channels in each inventory file
inventory_VBBPOS1Hz.xml			"Bad" inventory file with V,W,U channel order
inventory_VBBPOS1HzKH1.xml		"Good:" inventory file with U,V,W channel order

./bin:
ObsRotate2enz				The python program used to produce the good and bad mseed files with the corresponding inventory file. 

It may be related to https://lists.swapbytes.de/archives/obspy-users/2018-January/002666.html

[Example_Inv_permute.tar.zip](https://github.com/obspy/obspy/files/3781756/Example_Inv_permute.tar.zip)

**Comment by megies** [comment]
@hurstk your script is rather confusing and very hard to read. In any case, from what I see you are grabbing responses and orientations etc by indexing on the Inventory object. That's not what you should do, ever, if you want to keep your sanity.. ;-)
You want to use as high-level functionality as possible at any given time, so what you want to use is [`Stream.rotate()`](http://docs.obspy.org/master/packages/autogen/obspy.core.stream.Stream.rotate.html?highlight=rotate#obspy.core.stream.Stream.rotate) providing the inventory you read in and let obspy figure out rotation.

Should you really need to lookup orientations or responses, there's helper methods on `Inventory`.. e.g.
 - http://docs.obspy.org/master/packages/autogen/obspy.core.inventory.inventory.Inventory.get_coordinates.html
 - http://docs.obspy.org/master/packages/autogen/obspy.core.inventory.inventory.Inventory.get_orientation.html

See http://docs.obspy.org/master/packages/autogen/obspy.core.inventory.inventory.Inventory.html#Public%20Methods

Lastly, if you **really** need to pick things from an inventory by indexing, you should make sure to first filter you inventory to only include really what you're looking for.

```python
inv = read_inventory(...)
inv_tmp = inv.select(channel='HHV', ...)
```

At this point, I'm assuming the problems come from the indexing on the Inventory, if you encounter a problem with `Stream.rotate()` let us know.

**Comment by hurstk** [comment]
Thanks Tobias.
I rewrote it with stream.rotate as you suggested and it is now invariant with the order in the inventory file.

I will be sure to look for higher-level entries next time!

Thanks
Ken

**Comment by megies** [comment]
Good to hear it works now
