### ISSUE TITLE
Using PPSD without instrument response

### ISSUE THREAD

**Issue by CoralieAubert** [obspy/obspy#2494]
Hello,

I am currently working with miniseed data already corrected from the instrument response.
Then, I do not have neither dataless or instrument response.

I would like to calculate PSD, using the PPSD from obspy.

Is it possible to do that? Do I have to declare a unity gain, sensibility and paz which would describe a flat instrument response for example?

Can you give to me an example?

Thanks for help,
Regards,
Coralie

**Comment by megies** [comment]
Two options here, either you create a flat instrument response (see #2408) or you could abuse that legacy `special_handling` kwarg, see https://github.com/obspy/obspy/issues/2240#issuecomment-428944786

Hope it's clear now, feel free to reopen if needed

**Comment by MiguelonGonzalez** [comment]
> Two options here, either you create a flat instrument response (that's what I do in such cases, when I have to mix in already corrected data in any workflow, see #2408) or you could abuse that old and ugly legacy `special_handling` kwarg, see [#2240 (comment)](https://github.com/obspy/obspy/issues/2240#issuecomment-428944786)
> 
> Hope it's clear now, feel free to reopen if needed

Hi @megies! Could you share the paz you use for doing that?
I thought #2408 method was allready incorporated to obspy, but is still a pull request.
Thanks by advance

**Comment by aringler-usgs** [comment]
@MiguelonGonzalez 

Could you try the following: `paz = {'gain':1., 'sensitivity': 1., 'poles':[0+0*1j], 'zeros': [0+ 0*1j]}`?  I haven't tested it, but it should work.  Let me know if it doesn't and I can check it further.

**Comment by MiguelonGonzalez** [comment]
> @MiguelonGonzalez
> 
> Could you try the following: `paz = {'gain':1., 'sensitivity': 1., 'poles':[0+0*1j], 'zeros': [0+ 0*1j]}`? I haven't tested it, but it should work. Let me know if it doesn't and I can check it further.

Oh great, thank you very much! It works fine and the PPSD is plotted right, although there is a *RuntimeWarning*:
`RuntimeWarning: invalid value encountered in divide
  h = polyval(b, s) / polyval(a, s)`

**Comment by MiguelonGonzalez** [comment]
> @MiguelonGonzalez oh that might be a singularity. You might need to do something like `'poles': [1-1j], 'zeros': [1-1j]` since there might be a division by zero with what I gave you.

Wow, today it does not work with either other of the two ([0+0*1j] nor [1-1j]). Wondering what could be happening...
