### ISSUE TITLE
Bug in remove_response? (not including sensor Dip?)

### ISSUE THREAD

**Issue by flofux** [obspy/obspy#2495]
Hi all,

I think I might have found a bug in the remove_response function - or I am doing something stupid. Basically I have the feeling it's not taking into account the Dip of the respective channel (or I don't know where in stationxml the Dip is defined). Here's a quick example that shows the behaviour:

```
from obspy.clients.fdsn import Client
from obspy import UTCDateTime
import matplotlib.pyplot as plt

fdsn = Client('ODC')
t1 = UTCDateTime('2018-05-09T10:48:00')
t2 = UTCDateTime('2018-05-09T10:55:00')

data = fdsn.get_waveforms(network='OE', station='CONA', location='', channel='HHZ', starttime=t1, endtime=t2)
inv = fdsn.get_stations(network='OE', station='CONA', location='', channel='HHZ', starttime=t1, endtime=t2, level='response')
inv_minus = fdsn.get_stations(network='OE', station='CONA', location='', channel='HHZ', starttime=t1, endtime=t2, level='response')

inv[0][0][0].dip = 90.0
inv_minus[0][0][0].dip = -90.0

data_deconv = data.copy()
data_deconv_minus = data.copy()

data_deconv.remove_response(inventory=inv, output='VEL')
data_deconv_minus.remove_response(inventory=inv_minus, output='VEL')

plt.plot(data_deconv[0].data, label='90')
plt.plot(data_deconv_minus[0].data, label='-90')
plt.legend()
plt.show()
```

If the data is plotted, it is identical, even though it should have opposite sign ...

Any thoughts? Is the dip of the channel specified elsewhere in the stationXML?

Best regards,
Florian

**Comment by krischer** [comment]
Hi Florian,

the `remote_response()` function only deconvolves the instrument response, it does not do anything else. To rotate you'll have to use `.rotate()` with the `->ZNE` function: https://docs.obspy.org/packages/autogen/obspy.core.stream.Stream.rotate.html

This requires all three components to be available but otherwise it could only handle trivial cases.

**Comment by flofux** [comment]
Yay, that was fast! Thanks Lion - I didn't now that. So it's a feature, not a bug.

**Comment by krischer** [comment]
I guess that depends on the point of view ;-) It would be interesting if remove response would also rotate but many people would probably not expect that.

**Comment by megies** [comment]
> but many people would probably not expect that.

:+1: I'd rather keep it separate and no rotation magic

PS: Depending on input (if already named `ZNE` for example) you'll have to specify `components=['ZNE']` as well, people have tripped over that before
http://docs.obspy.org/master/packages/autogen/obspy.core.stream.Stream.rotate.html?highlight=components
