### ISSUE TITLE
distaz method of Iris Client returns lxml.objectify.FloatElement

### ISSUE THREAD

**Issue by heavelock** [obspy/obspy#2497]
I just noticed that distaz method of Iris client is returning objectify floats instead of pure floats. Only value of `ellipsoidname` is returned as native str. I see that there was similar bug for seishub client which was fixed. In my opinion, those values should be casted to native types. Should I change it?

```python
from obspy.clients.iris import Client
distaz = Client().distaz(0, 0, 1, 1)
type(distaz['ellipsoidname'])
>> str
type(distaz['distance'])
>> lxml.objectify.FloatElement
```

**Comment by megies** [comment]
Yes please make a PR for it @heavelock if you feel like it. It should indeed be plain float.
