### ISSUE TITLE
Automatic notifications using client.get_events

### ISSUE THREAD

**Issue by echavess** [obspy/obspy#2512]
Hi all, 

I am writing an script that pretends to send automatic notifications via SMS, email and facebook posts once a new earthquake is the Seiscomp3 database. For this, I am using client.get_events in the next way:

```
		update_time = UTCDateTime() + 60
		starttime = UTCDateTime() - 60 # 300 seconds = 5 minutes

		try:
			cat = self.client.get_events(starttime=starttime,
										 minlatitude=minlat, maxlatitude=maxlat,
										 minlongitude=minlon, maxlongitude=maxlon,
										 mindepth=mindepth, maxdepth=maxdepth,
										 minmagnitude=minmagnitude, 
                                                                                     maxmagnitude=maxmagnitude,
										 updatedafter= update_time, orderby='time-asc', 
										 includearrivals=True,
										 )
```
the code runs automatically every 60 s. The main idea is that it will be looking for new events every single minute and notify if there is any. However, I think I am missing something because some times there's a new event in database but it was not detected by client.get_events and so there is no alarms or notifications. Am I configuring this function correctly? How do you all recommend to set the parameters for automatically looking for new events evert 60s and notify when there is a new one? 

Thanks

**Comment by megies** [comment]
This might be better addressing the users mailing list to reach more people..

**Comment by ThomasLecocq** [comment]
@echavess I suppose you found an answer to this since then ? If yes, maybe you could also write a small tutorial for the documentation? :-) Closing this.
