### ISSUE TITLE
Reftek read issue: Reftek data encoding '32' not implemented yet

### ISSUE THREAD

**Issue by jimtal001** [obspy/obspy#2513]
Hello,
I've been using obspy to read Reftek archived data files successfully while files were steim compressed.  The compression option on the digitizers were changed to 32 (I believe it means no compression). On running my python code with the compression change I received the message below:
 
"Reftek data encoding '32' not implemented yet. Please open an issue on GitHub and provide a small (< 50kb) test file."

I do not have access to a small <50kb file so I uploaded the 14mb file.  The download link to a sample file is provided below.
https://gofile.io/?c=26nvI2 

Thank you for your assistance
Jim

**Comment by megies** [comment]
Duplicate, see #2267.
