### ISSUE TITLE
Getting rid of Sphinx Warnings

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#2518]
Currently, the doc builder complains for some files with:

```
/private-backup/home/obspy/update-docs-pr/src/obspy/misc/docs/source/packages/obspy.core.event.rst:: WARNING: document isn't included in any toctree
/private-backup/home/obspy/update-docs-pr/src/obspy/misc/docs/source/packages/obspy.core.event.header.rst:: WARNING: document isn't included in any toctree
/private-backup/home/obspy/update-docs-pr/src/obspy/misc/docs/source/packages/obspy.core.inventory.rst:: WARNING: document isn't included in any toctree
/private-backup/home/obspy/update-docs-pr/src/obspy/misc/docs/source/packages/obspy.core.util.rst:: WARNING: document isn't included in any toctree
/private-backup/home/obspy/update-docs-pr/src/obspy/misc/docs/source/packages/obspy.io.nied.rst:: WARNING: document isn't included in any toctree
```

this https://stackoverflow.com/questions/15249340/warning-document-isnt-included-in-any-toctree-for-included-file/40725923#40725923

suggests to use the file-wide metadata ``:orphan:`` (https://www.sphinx-doc.org/en/master/usage/restructuredtext/field-lists.html#file-wide-metadata) to ``If set, warnings about this file not being included in any toctree will be suppressed.``

**Comment by ThomasLecocq** [comment]
ping @megies

**Comment by megies** [comment]
Interesting.. didn't know about that one. It's weird, because we never could figure out why those warnings even show up, because they clearly are in toctrees.. but I guess suppressing is the only choice..

Go ahead if you like @ThomasLecocq  :muscle:

**Comment by ThomasLecocq** [comment]
the case of ``obspy.io.nied`` is special, in ``misc\packages\index.rst`` the file is called via

```
.. autosummary::
    :toctree: .
    :nosignatures:

    obspy.io.ah
...
    obspy.io.nied.knet
...
```

**Comment by ThomasLecocq** [comment]
actually none of them are in toctrees "as is"

**Comment by megies** [comment]
Tilde means only the part behind the last plot is rendered as text (but full path is used for internal link still). (kind of a shortcut for more general version e.g.
```
:meth:`Stream.filter() <obspy.core.stream.Stream.filter>`
```

**Comment by ThomasLecocq** [comment]
ok, so for the core stuff I think passing the full location could work. For Nied, we can orphan it. Pushing a PR, we'll see

**Comment by ThomasLecocq** [comment]
my local git is fu*ed up, will be for later or tomorrow.

**Comment by megies** [comment]
[![xkcd: git](https://imgs.xkcd.com/comics/git.png)

**Comment by ThomasLecocq** [comment]
EXACTLY ! my master branch looks like a Xmass tree with rebased sh* ... damn
