### ISSUE TITLE
Will Obspy be compatible soon with newer versions of pyproj?

### ISSUE THREAD

**Issue by carlosfherrera** [obspy/obspy#2523]
Dear Obspy team,

I just had to deal for the first time with the issue posted in this [thread](https://github.com/obspy/obspy/issues/2445). In my machine (Ubuntu 18.04 and Python 3.6.9) I've Obspy 1.1.1 installed via Apt repository, and I also have QGIS installed via the same method. 

The last QGIS repository update for Ubuntu installed pyproj 2.4.1. But this package version messed up my Obspy installation. The solution was to downgrade pyproj back to version 1.9.5.1. So, from now, I'll have to be careful to uncheck the pyproj update every time the software updater notification pops up.

So, to hopefully stop worrying about this soon, will Obspy be ever compatible with any version of pyproj? Or there are no plans about this in the short term?

Thanks!

**Comment by megies** [comment]
> The last QGIS repository update for Ubuntu installed pyproj 2.4.1.

Where was that pyproj package coming from? Pyproj version should stay static as it comes from Ubuntu repo, no? What was the problem with the newer pyproj?

**Comment by megies** [comment]
Still, why does your apt-installed pyproj version change?

**Comment by carlosfherrera** [comment]
Hi megies,

The pyproj version update comes from the QGIS repository update. When I check the available pyproj package for Ubuntu using `sudo apt-cache policy python3-pyproj`, this is what appears:
```
python3-pyproj:
  Installed: 1.9.5.1-3build1
  Candidate: 2.4.1+ds-1~bionic0
  Version table:
     2.4.1+ds-1~bionic0 500
        500 http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu bionic/main amd64 Packages
 *** 1.9.5.1-3build1 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
```
For now, this shows that pyproj 1.9.5.1 is installed, because I manually downgraded the version, but the systems recommends the newer version. 

When pyproj 2.4.1 gets installed, I get exactly the same AttributeError as shown in [#2445]( https://github.com/obspy/obspy/issues/2445) when I call any Obspy module in the Python prompt.

**Comment by megies** [comment]
Well, there is a custom repository involved that changes one of our dependencies' version, there is not much that can be done from a packaging point of view. There's always a chance your system breaks when mixing up package versions from packages that are in the main distribution. These are not expected to change.
N.b. QGIS has its own apt repositories (dont know `ubuntugis`) and I never had problems on Debian using that to update QGIS.

In any case, you should be able to upgrade to 1.2.0 soonish, so I'll close this in favor of #2295
