### ISSUE TITLE
How to write STA2 in .gse2 ?

### ISSUE THREAD

**Issue by unron0830** [obspy/obspy#2526]
-  Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 15:42:17) [MSC v.1500 64 bit (AMD64)]
   -Platform (Windows)

1.Original data:
[https://drive.google.com/file/d/1-OrNDyvWKSnUN2vG13_vn-UA6d7xnkIU/view?usp=sharing](url)
2.Output data:
[https://drive.google.com/file/d/1RvZ8FJWhdTChzxjfvjAQNjMqHHGnfcmQ/view?usp=sharing](url)
3.Wanted data
[https://drive.google.com/file/d/1cTMxe5QI2cjrIKvx4QdKFV5VUQ0CXC1N/view?usp=sharing](url)

Frist Question:
I used `tr.write() ` for `.gse2` ,and I had added coordination for the station.
I would like to know how to write STA2 for `.gse2` just like `3.Wnated data`.
The header is  three  lines in `3.Wnated data` 

Second Question:
I have changed the  sampling rate `tr.stats.sampling_rate = 100.0` but the sampling rate still is 200.
When I use `print tr.state   `  for check.

 ```
coding: utf-8
from obspy import Trace
import numpy as np
import shutil
import os 
from obspy.core import UTCDateTime
tr = Trace()
aa=['EQ_18205200.txt'] 
latitude=121.6509  #     Latitude (degrees, S is negative)
longitude=99       #     Longitude (degrees, W is negative)
elevation=24.6668  

for a in aa:
    f = open("D:\EQ_data\EQ_18205200.txt","r") 
    StationCode = f.readline().split(":",1)[-1].replace('\n',' ').replace('\r','')
    InstrumentKind= f.readline().split(":",1)[-1]
    StartTime= f.readline().split(":",1)[-1].replace('/',"")
    RecordLength= f.readline().split(":",1)[-1] 
    ampleRate= f.readline().split(":",1)[-1]
    AmplitudeUnit= f.readline().split(":",1)[-1]
    AmplitudeMAX_U= f.readline().split(":",1)[-1]
    AmplitudeMAX_N= f.readline().split(":",1)[-1]
    AmplitudeMAX_E= f.readline().split(":",1)[-1]
    DataSequence= f.readline().split(":",1)[-1]
    Data= f.readline().split(":",1)[-1]
    dd = f.readlines()
    dd[0].split()

    z=[]
    N=[]
    E=[]

    for i in range(len(dd)): # i=0,1,2,3....17999
        if (i+1)%2 == 1 : 
            data = dd[i].split() 
            z.append(int(float(data[1])*1000)) 
            N.append(int(float(data[2])*1000))
            E.append(int(float(data[3])*1000)) 

    z = np.array(z)
    N = np.array(N)
    E = np.array(E)

    tr.data = N
    tr.stats
    tr.stats.network = "TW"
    tr.stats.station = " H     N"
    tr.stats.sampling_rate = 100.0
    tr.stats.delta = 1.0/200.0
    tr.stats.starttime = UTCDateTime(StartTime)
    tr.stats.Lat=latitude
    tr.stats.Lon=longitude
    tr.stats.Elev=elevation
    outputName=a[0:(len(a)-4)]+".gse"
    tr.write(outputName,format="GSE2",inplace=True)
       
    tr.data = E
    tr.stats
    tr.stats.network = "TW"
    tr.stats.station = " H     E"
    tr.stats.sampling_rate = 100.0
    tr.stats.delta = 1.0/200.0
    tr.stats.starttime = UTCDateTime(StartTime)
    tr.write("Tempout2",format="GSE2",inplace=True)

    tr.data = z
    tr.stats
    tr.stats.network = "TW"
    tr.stats.station = " H     Z"
    tr.stats.sampling_rate = 100.0
    tr.stats.delta = 1.0/200.0
    tr.stats.starttime = UTCDateTime(StartTime)

    tr.write("Tempout3",format="GSE2",inplace=True)

    with open(outputName, "a") as wfd:  ####
        for f in ['Tempout2', 'Tempout3']: 
            with open(f, "rb") as fd: 
                shutil.copyfileobj(fd, wfd)  
    os.remove(os.getcwd()+"\Tempout2") ####
    os.remove(os.getcwd()+"\Tempout3") ####

**Comment by ThomasLecocq** [comment]
For the sampling rate, you define delta as 0.005, that's 200 hz...

**Comment by megies** [comment]
> I would like to know how to write STA2 for `.gse2`

Take a look [here](https://github.com/obspy/obspy/blob/d192527db401c7d0b8cd8ce0e742049c0873557c/obspy/io/gse2/libgse2.py#L537-L576), you basically have to fill up `tr.stats['gse'] = {...}` with your info.
I'd highly encourage keeping waveforms and metadata separate, though, and you should set up StationXML files to store your station info, unless you are using other legacy codes that need that info inside the GSE file.

>  I have changed the sampling rate `tr.stats.sampling_rate = 100.0` but the sampling rate still is 200.
> When I use `print tr.state ` for check.

Not sure what is happening, please provide a *short* example code snippet that is not relying on local files or people can not reproduce without significant effort (i.e. not likely to happen).

>    tr.stats.station = " H     Z"

btw, this doesn't seem canonical, why not put component info in `tr.stats.channel`?

**Comment by unron0830** [comment]
First, I used` .insert` to insert the SAT2 (second line) directly.
Second, thanks for ThomasLecocq I fixed the delta number and it works.
