### ISSUE TITLE
Infinite loop when trying to read full SEED file without any mini SEED records

### ISSUE THREAD

**Issue by yetinam** [obspy/obspy#2534]
When trying to read a full SEED file without any mini SEED records, while specifying input format MSEED, the code runs into an infinite loop.

Example file (contained FSEED file): http://webservices.ingv.it/webservices/ingv_ws_data/data/view_waveform_at_ingv.it/2015/08/24/093006_1594696/1594696_data.tgz

Code to reproduce:
```
import obspy
obspy.read('1594696_data/1594696_data.fseed', 'MSEED')
```

Code gets stuck searching for first data record, in the following loop:
https://github.com/obspy/obspy/blob/6d6d20c7c35126b18de5d33af962aa1c51dbfdd7/obspy/io/mseed/util.py#L646

I suppose the problem could be fixed with a check if EOF has been reached. For intended behavior I'm unsure if an exception should be raise or rather if just an empty Stream object should be returned.

ObsPy version: 1.1.0 (installed through pip in a conda virtual env)
Python version: 3.6.5
OS: Ubuntu 18.04

**Comment by megies** [comment]
Thanks for the comprehensive bug report @yetinam! Will be fixed in #2535
