### ISSUE TITLE
Obspy obspy-scan fnmatch issue

### ISSUE THREAD

**Issue by grajh** [obspy/obspy#2545]
Hi!

I tried running 'obspy-scan' script with fnmatch style wildcards in '--id' argument and it does not seem to work properly.

$ obspy-scan /events_fs/* -f MSEED --id 'Z3.A250A..HH[NE]'

All I get is this.
![Figure_1](https://user-images.githubusercontent.com/32673009/73948245-01a70100-48f9-11ea-883b-69c4d092b390.png)

If I run the script with the command below (without wildcards, only seed ID), the figure is plotted correctly.

$ obspy-scan /events_fs/* -f MSEED --id 'Z3.A250A..HHE'

I am running Obspy version 1.1.1 on Anaconda and Python 3

**Comment by grajh** [comment]
I see that these lines were added in the current version on GitHub compared to the one I have installed.

 ```
        data_keys = list(self.data.keys())
        if seed_ids is not None:
            ids = []
            for id_ in seed_ids:
                # allow fnmatch type wildcards in given seed ids
                if any(special in id_ for special in '*?[]!'):
                    ids.extend(fnmatch.filter(data_keys, id_))
                else:
                    ids.append(id_)
            # make sure we don't have duplicates in case multiple wildcard
            # patterns were given and some ids were matched by more than one
            # pattern
            ids = list(set(ids))
            seed_ids = ids
```

**Comment by grajh** [comment]
Ok. Installing current master solved the issue. Sorry for reporting this.

**Comment by megies** [comment]
All good @grajh. We'll have a new release out soon, with this feature included.
