### ISSUE TITLE
Problem with Client

### ISSUE THREAD

**Issue by sjarrowsmith** [obspy/obspy#2551]
I've started getting an error after updating to the latest ObsPy:

from obspy.clients.fdsn import Client

DATASELECT = 'http://service.iris.edu/ph5ws/dataselect/1'
client = Client('http://service.iris.edu',
                    service_mappings={
                        'dataselect': DATASELECT
                    },
                    debug=True
                    )

Installed new opener with handlers: [<obspy.clients.fdsn.client.CustomRedirectHandler object at 0x7ff572669150>]
Base URL: http://service.iris.edu
Custom service mappings:
	dataselect: 'http://service.iris.edu/ph5ws/dataselect/1'
Request Headers: {'User-Agent': 'ObsPy/1.1.1 (Darwin-18.7.0-x86_64-i386-64bit, Python 3.7.6)'}
Downloading http://service.iris.edu/ph5ws/dataselect/1/application.wadl with requesting gzip compression
Downloading http://service.iris.edu/fdsnws/event/1/application.wadl with requesting gzip compression
Downloading http://service.iris.edu/fdsnws/station/1/application.wadl with requesting gzip compression
Downloading http://service.iris.edu/fdsnws/event/1/catalogs with requesting gzip compression
Downloading http://service.iris.edu/fdsnws/event/1/contributors with requesting gzip compression
Downloaded http://service.iris.edu/fdsnws/event/1/catalogs with HTTP code: 200
Uncompressing gzipped response for http://service.iris.edu/fdsnws/event/1/contributors
Downloaded http://service.iris.edu/fdsnws/event/1/contributors with HTTP code: 200
Uncompressing gzipped response for http://service.iris.edu/fdsnws/event/1/application.wadl
Downloaded http://service.iris.edu/fdsnws/event/1/application.wadl with HTTP code: 200
Downloaded http://service.iris.edu/ph5ws/dataselect/1/application.wadl with HTTP code: 200
Downloaded http://service.iris.edu/fdsnws/station/1/application.wadl with HTTP code: 200
Discovered event service
  File "<string>", line 104
XMLSyntaxError: Opening and ending tag mismatch: meta line 9 and head, line 104, column 8

**Comment by megies** [comment]
Was this problem solved @sjarrowsmith ?

**Comment by sjarrowsmith** [comment]
Yes, sorry for the unnecessary post! I discovered that the Client IRIS requests were not working due to an internet proxy issue. I had just updated ObsPy and assumed the problem was with ObsPy.
Keep up the great work!
