### ISSUE TITLE
Bug in Tau-P C routines

### ISSUE THREAD

**Issue by 1sbeller** [obspy/obspy#2559]
Hi,

We have found a bug in Tau-P C function bullen_radial_slowness_inner_loop from inner_tau_loops.c when obspy is compiled on IBM architectures. 

Sometimes, the function returns NaN values. This happens when square roots arguments: 
sqrt_top = sqrt(pow(LAYER(i, SL_TOP_P), 2) - pow(p[i], 2));
sqrt_bot = sqrt(pow(LAYER(i, SL_BOT_P), 2) - pow(p[i], 2));
are closed to zero.

In floating point arithmetic the argument may become slightly negative in which case some compilers return NaN while others return zero since sqrt_top and sqrt_bot are floats and not complex values. A workaround here is to take:
sqrt_top = sqrt(fmax(0.,pow(LAYER(i, SL_TOP_P), 2) - pow(p[i], 2)));
sqrt_bot = sqrt(fmax(0.,pow(LAYER(i, SL_BOT_P), 2) - pow(p[i], 2)));
fmax could probably be replaced with fabs, but I feel this is safer to use fmax.

Also, this check may not give the expected behavior:
if ((LAYER(i, SL_BOT_DEPTH) - LAYER(i, SL_TOP_DEPTH)) < 0.0000000001) {
    continue;
 }
if it happens that LAYER(i,j) presents a NaN value the condition will return false and later calculations will be performed with NaN values. It would be safer to add a second check for NaNs. Something like that:
double dumb_var = ((LAYER(i, SL_BOT_DEPTH) - LAYER(i, SL_TOP_DEPTH)) ;
if (dumb_var < 0.0000000001)  || isnan(dumb_var)) {continue;}
or the equivalent
if (dumb_var < 0.0000000001)  || dumb_var != dumb_var) {continue;}

Stephen

**Comment by megies** [comment]
@1sbeller fmax is not available, you got a different suggestion? https://ci.appveyor.com/project/obspy/obspy/builds/30819886/job/7fwl2bjln91mhaco#L366

**Comment by 1sbeller** [comment]
That's a strange, fmax has been introduced in the C math library since the C99 norm (ex: https://en.cppreference.com/w/c/numeric/math/fabs). And the source code is indeed including math.h.

Anyway, another less beautiful workaround could be to add if statements checking the negativity of the argument, something like this:
  double arg_top = pow(LAYER(i, SL_TOP_P), 2) - pow(p[i], 2);
  double arg_bot = pow(LAYER(i, SL_BOT_P), 2) - pow(p[i], 2);
  if (arg_top < 0.) {arg_top = 0.;}
  if (arg_bot < 0.) {arg_bot = 0.;}  
  sqrt_top = sqrt(arg_top);
  sqrt_bot = sqrt(arg_bot);

Also I see that isnan is not recognized as well. For this one, the test (dumb_val == dumb_val) should work since a NaN is by definition different than itself.

Hope this works.

Stephen

**Comment by 1sbeller** [comment]
As a side note: if the compiler is following the C89 norm instead of the C99, I think the declaration of arg_top, arg_bot and dumb_var should be perform before the for loop.

Stephen

**Comment by megies** [comment]
added those new changes

**Comment by 1sbeller** [comment]
Hi Tobias,

It appears that it failed again. This is compiling on my side:

void bullen_radial_slowness_inner_loop(
        double *layer,
        double *p,
        double *time,
        double *dist,
        double radius,
        int max_i) {
    int i;
    double B, sqrt_top, sqrt_bot;
    double arg_top, arg_bot, dumb_var;
    
    
    for (i=0; i<max_i; i++) {
        dumb_var = (LAYER(i, SL_BOT_DEPTH) - LAYER(i, SL_TOP_DEPTH));
        if ((dumb_var < 0.0000000001) || (dumb_var != dumb_var)) {continue;}

        B = log(LAYER(i, SL_TOP_P) / LAYER(i, SL_BOT_P)) /
            log((radius - LAYER(i, SL_TOP_DEPTH)) /
                (radius - LAYER(i, SL_BOT_DEPTH)));
        arg_top = pow(LAYER(i, SL_TOP_P), 2) - pow(p[i], 2);
        arg_bot = pow(LAYER(i, SL_BOT_P), 2) - pow(p[i], 2);
        if (arg_top < 0.) {arg_top = 0.;}
        if (arg_bot < 0.) {arg_bot = 0.;}
        sqrt_top = sqrt(arg_top);
        sqrt_bot = sqrt(arg_bot);

        dist[i] = (atan2(p[i], sqrt_bot) - atan2(p[i], sqrt_top)) / B;
        time[i] = (sqrt_top - sqrt_bot) / B;
    }
}

Stephen

**Comment by megies** [comment]
Thanks for the new patch, I don't use C, so I'm glad I fon't have to look it up. :)

**Comment by QuLogic** [comment]
MSVC is far from being C99 compatible; they focus on C++ standards.
