### ISSUE TITLE
adjust to setuptools removing "Feature"

### ISSUE THREAD

**Issue by megies** [obspy/obspy#2564]
setuptools is removing `Feature` which we use in `setup.py`.

e.g. https://ci.appveyor.com/project/obspy/obspy/builds/30961775/job/b6ah67ssmapinays?fullLog=true#L506
```
setup.py:586: DistDeprecationWarning: Features are deprecated and will be removed in a future version. See https://github.com/pypa/setuptools/issues/65.
  require_features=('system-evalresp', 'system-libmseed')
setup.py:574: DistDeprecationWarning: Features are deprecated and will be removed in a future version. See https://github.com/pypa/setuptools/issues/65.
  setuptools.Feature.__init__(self, *args, **kwargs)
C:\Miniconda-x64\envs\test\lib\site-packages\numpy\distutils\numpy_distribution.py:16: DistDeprecationWarning: Features are deprecated and will be removed in a future version. See https://github.com/pypa/setuptools/issues/65.
  Distribution.__init__(self, attrs)
```

**Comment by ThomasLecocq** [comment]
@megies done in 1.2.1 and 2.0.0 is rebased, right ?

**Comment by megies** [comment]
Well the quick fix is in 1.2.1, but we might want to reimplement this mechanism again. Not sure if anybody actually uses that mechanism though??

**Comment by megies** [comment]
@QuLogic I know you are packaging libmseed separate from obspy for fedora.. so you're really the only person I could think of that might be using this mechanism.. no idea really, you have an opinion on whether we need to reimplement this? I'm tempted to just close this, so far I have no indication that anybody is using this feature whatsoever

**Comment by QuLogic** [comment]
We could patch it downstream, I guess. Though I currently have the annoying contention that libmseed 3 is out, but ObsPy doesn't yet support it. If we want to keep this in, we could do like Matplotlib, which reads the setting from a `setup.cfg`.

**Comment by megies** [comment]
Assuming this is obsolete if nobody needed this in the meantime, so closing
