### ISSUE TITLE
polarization.vidale_adapt: possible mis-ordered complex covariance matrix elements

### ISSUE THREAD

**Issue by dngreen** [obspy/obspy#2565]
Obspy version:1.1.0, python version: 3.7

Two elements of the complex covariance matrix in obspy.signal.polarization.vidale_adapt are possibly mis-ordered.

Lines 270 and 271 of obspy.signal.polarization.py are currently
```
covmat[1][2] = np.dot(zx, nx.conjugate())
covmat[2][1] = covmat[1][2].conjugate()
```

Suggest it should be:
```
covmat[1][2] = np.dot(nx, zx.conjugate())
covmat[2][1] = covmat[1][2].conjugate()
```

Tests suggest that current implementation produces significantly noisier smallest eigenvalues than suggested fix.

[Apologies if I've not formatted this issue correctly, or mis-understood the code; first attempt at raising an issue - please let me know if I should be doing something else].

**Comment by ThomasLecocq** [comment]
@jwassermann ?

**Comment by jwassermann** [comment]
Hm, needs a closer look

Von meinem iPhone gesendet

**Comment by dngreen** [comment]
A little more context if it helps.

Vidale (1986) Eqn 2 is:

![Cvidale](https://user-images.githubusercontent.com/20835956/75095690-7764cb00-558f-11ea-9699-15a9cf98d5d4.png)

I think the current obspy implementation is this:

![Cobspy](https://user-images.githubusercontent.com/20835956/75095696-83e92380-558f-11ea-97d3-4f2b9110b314.png)

The consequence for the output eigenvalues is demonstrated in the example below (an air-to-ground coupled wave recorded on a 3-component seismometer arrives at approx. sample 6000):

Current implementation:

![eigenval_test_current](https://user-images.githubusercontent.com/20835956/75095709-ab3ff080-558f-11ea-85a4-ad2c3b082fa0.png)

Result when suggested implementation made:

![eigenval_test_proposed](https://user-images.githubusercontent.com/20835956/75095716-bf83ed80-558f-11ea-9ac3-94f1e16f8271.png)

The largest effect (for the example above) is for the smallest eigenvalue (but there is a small effect on the intermediate eigenvalue as well). Therefore this will have consequences for the calculation of both rectilinearity (L.287) and planarity (L.289 of obspy/polarization.py).

I haven't investigated effect on eigenvectors.

Hope this is helpful.

**Comment by jwassermann** [comment]
Just checked and yes you are perfectly right - thanks for pointing this out. I changed the code already to use the same notation as the Flinn method (np.cov). In the light of  this I would also change the adaptive windowing to be selectable - sometimes the output of the Vidale with adaptive windowing looks very weird.In order to backward compatible the switch vor adaptive will be set to True
@megies makes that sense?

**Comment by megies** [comment]
> In order to backward compatible the switch for adaptive will be set to True

Sounds good to me. So what are the exact changes to be done?
 - change `np.dot(zx, nx.conjugate())` as described in first post
 - make adaptive selectable (what part of the code exactly should be optional, wasn't immediately apparent from a quick glance at the code)

Anything else @jwassermann, @dngreen?

**Comment by jwassermann** [comment]
I have the code ready and will send it asap

Von meinem iPhone gesendet

**Comment by megies** [comment]
@dngreen can you have a look at #2570 and see if it fixes things for you?

**Comment by dngreen** [comment]
The fix looks good. Thanks @megies and @jwassermann for looking at this.
