### ISSUE TITLE
Docs erroneously state seg2 write capability

### ISSUE THREAD

**Issue by Khalilsqu** [obspy/obspy#2572]
your documentation about seg2 says that it is possible to read and **write** seg2 data. However, I have not found support (function or method) to write seg2 data.

**Comment by megies** [comment]
There is no write support for SEG2. Where did you read that?

**Comment by Khalilsqu** [comment]
@megies 


SEG2 | Class to read and write SEG 2 formatted files. The main reason this is
-- | --
[here the documentation](https://docs.obspy.org/packages/autogen/obspy.io.seg2.seg2.html
)

```
class SEG2(object):
    """
    Class to read and write SEG 2 formatted files. The main reason this is
    realized as a class is for the ease of passing the various parameters from
    one function to the next.

    Do not change the file_pointer attribute while using this class. It will
    be used to keep track of which parts have been read yet and which not.
    """
```

**Comment by megies** [comment]
Thank you, we will correct this misinformation.
