### ISSUE TITLE
Is TFR the same as FTAN?

### ISSUE THREAD

**Issue by rramariano** [obspy/obspy#2575]
Hello, I am trying to study on how to perform FTAN for analysis and I was wondering if the plot from [obspy.signal.tf_misfit.plot_tfr](https://docs.obspy.org/packages/autogen/obspy.signal.tf_misfit.plot_tfr.html#obspy.signal.tf_misfit.plot_tfr) represent the same/almost the same thing as this [FTAN diagram](https://images.app.goo.gl/GSg5ox3RRwuJbtb18)?

If not, then how can I perform FTAN using Obspy?

Thanks.

**Comment by megies** [comment]
Our documentation has sufficient info on what is done, including references to papers.

https://docs.obspy.org/packages/autogen/obspy.signal.tf_misfit.html
https://docs.obspy.org/citations.html#kristekova2006
https://docs.obspy.org/citations.html#kristekova2009

Please use the users mailing list if you want to discuss other algorithms.
