### ISSUE TITLE
option to open EVT file without applying metadata on raw data

### ISSUE THREAD

**Issue by grapagnani** [obspy/obspy#2582]
applies to: **master** branch at time of writing
relevant files: <code>io.kinemetrics/*</code>

Hello, the current code opens a Kinemetrics EVT file, reads data and calibration information of the instrument and then, by default, applies the calibration on the raw data. We then get a Stream object with data expressed in m/s**2 unit instead of count. That is fine.

However, the current code already contains some lines of code which would allow to open the file and get a Stream object with data in plain count instead of m/s**2. But, for a reason I don't know, this code is incomplete.

It would be great if you could complete the code to allow, as an option, for opening EVT files and get raw data instead of data converted to m/s**2. The diff in attachment is all it takes to enable this feature.

To make things clear:
- the default behavior remains: open the EVT file, provide a Stream object with data in m/s**2 unit
- this addon enable to open the file with: <code>st = read("myfile.evt", raw=True)</code>, and get a Stream object with data in plain count.

Could you please add this feature ?

[io_kinemetrics_core.patch.txt](https://github.com/obspy/obspy/files/4318415/io_kinemetrics_core.patch.txt)

**Comment by ThomasLecocq** [comment]
solved by #2866 merged into master
