### ISSUE TITLE
Encountered 1 error(s) during a call to readMSEEDBuffer():

### ISSUE THREAD

**Issue by albertleonardo** [obspy/obspy#2584]
Hi community,

I am trying to read a MSEED file and I get this error message:
**InternalMSEEDError: Encountered 1 error(s) during a call to readMSEEDBuffer():
msr_unpack_data(UV_HORQ__SHN_D): only decoded 3580 samples of 3581 expected**

The code I'm trying to run is just this:
**st = read('2013-08-13-2059-50M.COL___224')**
 
when using headonly=True, there are 222 traces in the file. I checked the file in a hex editor, I found an empty space in the file. After removing the empty space, I am able to read the file but it only shows 140 traces out of the 222. The problem is apparently only related to one trace, with id UV.HORQ..SHN. 

You can find the file here: https://drive.google.com/file/d/1J18kI9vAr9jhEKPtJaWFSnnfctPRt18T/view?usp=sharing

Some more info
Python 3.7.3
obspy                     1.1.0, installed using conda on MacOS Mojave 10.14.6

Any workaround for this situation? I have many files with the same situation

Help is appreciated, thanks

**Comment by megies** [comment]
What do you mean "an empty space"?

**Comment by megies** [comment]
Also, please try with current release 1.2.0.

**Comment by albertleonardo** [comment]
From issue #1981 I thought I might have a similar problem and this is what I found

<img width="1247" alt="Screen Shot 2020-03-13 at 10 25 54 AM" src="https://user-images.githubusercontent.com/26013212/76644862-13418100-6515-11ea-9f39-c6002183f983.png">

Also, I tried release 1.2.0 and got the same error.

**Comment by megies** [comment]
I see a screenshot with many numbers on it. Would you care to elaborate a bit more what seems to be the issue here? Right now my impression is you are dealing with a broken MiniSEED file that has invalid records or something?

**Comment by megies** [comment]
No feedback, closing for now. Please reopen if you have more information, especially if it is indeed a valid file and not a broken one.
