### ISSUE TITLE
Rotating from UVW into ZNE using `rotate2zne`

### ISSUE THREAD

**Issue by john-robert** [obspy/obspy#2587]
**obspy version: 1.1.1.
installed with anaconda**
I'm fearing I discovered a flaw in  `obspy.signal.rotate.rotate2zne`. 

1)
If I set `inverse=False` (so desiring to rotate from UVW to ZNE), the matrix inversion (line 229) is still performed as the code reads `if not inverse:`.

2)
In the next line of code (232), I think, the rotation matrix *m* in it's present definition should actually be it's transpose. So it should read:  
`z, n, e = np.dot(m.T, [data_1, data_2, data_3])`,  
If this assessment is correct, then these two operations lead to not correct results. This is because: *m<sup>-1</sup>* != *m<sup>T</sup>*.

I apologise if I somehow do not follow proper procedure.

**EDIT**

So I thought a bit more mathematically about it and I think I understand now. The code as is makes use of the fact that one should define the rotation matrix starting from the orthogonal system (So UVW = A * ZNE). As Obspy does that, to rotate from UVW into ZNE, one needs the inverse matrix of A and this is what line 229 actually does. Tricky. I guess my problem was that analysing a UVW signal where only one component has a non-zero value actually must project the way it's done.

**Comment by megies** [comment]
Not sure what exactly seems to be the problem, you could have a look at #1927 and follow up if anything is still unclear. Pretty sure it was properly fixed back then.

**Comment by john-robert** [comment]
Yep, you could close this issue. It is was some mathematics that I did not correctly interpret for a, in defence, very special case in a non-orhtoganl component system.

**Comment by krischer** [comment]
Haha - I was also just about to look into this once again but we've been over this 5 times already in the last years and I'm also fairly sure its correct by now.

**Comment by ThomasLecocq** [comment]
maybe it's more a documentation issue then, no?
