### ISSUE TITLE
StationXML output version hard-coded

### ISSUE THREAD

**Issue by mikehagerty** [obspy/obspy#2590]
I noticed that the output SCHEMA_VERSION is hard-coded in obspy 1.2 
to StationXML 1.1, regardless of what the input version was.
(e.g., in obspy/io/stationxml/core.py:   45 SCHEMA_VERSION = "1.1")

I wonder of if it would be more backwards compatible to allow the
output version to be the same as the input version if desired.

If a user reads in an old version using read_inventory() and writes it
back out using inventory.write(), it seems like the schema version could be
stored in inventory.extra or somewhere similar.
validate_stationxml() could use this schema version for validation on output.
Or, a flag on inventory.write() could indicate the user wants to use the default (1.1) schema,
regardless of input version.

I guess the issue is that if in between the read and write, the user modifies the
inventory, it will do so with BaseNode objects that conform to the new schema,
but I think if you know what you're doing this could be handled (e.g. if the changes
aren't too big), and in any case, the validation will fail on write() as expected.

Just a thought.

**Comment by megies** [comment]
We decided against supporting output of 1.0 and 1.1 as it would make the code base really messy with lots of if/else switches and also the object structure had to be adjusted for StationXML 1.1, so some values are not even stored anymore that were removed in the schema.

Partly this is owed to the fact that the StationXML 1.1 topic came in at a point where the release was *way* overdue already (I had to be convinced to actually still include it, and had significant work to do to get it in) and adding even more complexity (besides being able to read both versions) would have been a major delay on the release. Being able to read both was already tricky to get done right.

I think it should be very feasible to keep a dedicated Python environment on ObsPy 1.1.1 if you really need to produce old StationXML 1.0 files, just for these StationXML I/O operations?
