### ISSUE TITLE
how to remove the gap or overlap when to stream connect？

### ISSUE THREAD

**Issue by peacewyz** [obspy/obspy#2607]
**hello 
       I want to link several days data to one stream. but it is generate overlap.  because of the sample rate is not strictness and have an extra number.**

Source            Last Sample                 Next Sample                 Delta           Samples 
KK.DT014.TB.BHZ   2018-10-23T00:00:00.000000Z 2018-10-23T00:00:00.000000Z -0.010000       -1      
KK.DT014.TB.BHZ   2018-10-24T00:00:00.000000Z 2018-10-24T00:00:00.000000Z -0.010000       -1      
KK.DT014.TB.BHZ   2018-10-25T00:00:00.000000Z 2018-10-25T00:00:00.000000Z -0.010000       -1      
KK.DT014.TB.BHZ   2018-10-26T00:00:00.000000Z 2018-10-26T00:00:00.000000Z -0.010000       -1      
KK.DT014.TB.BHZ   2018-10-27T00:00:00.000000Z 2018-10-27T00:00:00.000000Z -0.010000       -1      
KK.DT014.TB.BHZ   2018-10-28T00:00:00.000000Z 2018-10-28T00:00:00.000000Z -0.010000       -1      
Total: 0 gap(s) and 6 overlap(s)

**if i want to remove the overlap of the link data, how can i fix it ?
thanks for very one who can help me!
Best regards!

Zhi**

**attachment: code**

def Data_connect(file_name):
    Z=0 
    for root,dirs,files in os.walk(file_name):
            for file in files:
                name, suf = os.path.splitext(file)                  
                savename=name[-6:]                
                if (suf == ".BHZ") : 
                    Seismic_connect_save = root+r'\connectdata'
                    if not os.path.isdir(Seismic_connect_save):  os.mkdir(Seismic_connect_save)     
                    Z=Z+1
                    if Z==1:
                        print('*******************')
                        print(os.path.join(root,file)) 
                        stZ = read(os.path.join(root,file)) 
                    if Z>=2:
                        #print(stZ) 
                        print('---------------------')
                        print(os.path.join(root,file)) 
                        stZ = (stZ + read(os.path.join(root,file)) ) 
    print(stZ[2].stats)
    stZ.get_gaps()
    stZ.print_gaps()

**Comment by peacewyz** [comment]
uses Stream._cleanup can fix it!

**Comment by megies** [comment]
Ideally you want to use the public method in user code, as private methods are subject to change without notice:

`stream.merge(-1)` does the same thing as `_cleanup()`

http://docs.obspy.org/master/packages/autogen/obspy.core.stream.Stream.merge.html?highlight=cleanup
