### ISSUE TITLE
error in spectral estimation.py

### ISSUE THREAD

**Issue by kpsanjay** [obspy/obspy#2613]
Hello i am also getting error
I am getting error " /home/sanjay/anaconda2/envs/obspy/lib/python3.7/site-packages/obspy/signal/spectral_estimation.py:968: UserWarning: Error getting response from provided metadata:
AttributeError: 'str' object has no attribute 'format_seed'"
[obspy_PSD.log](https://github.com/obspy/obspy/files/4621851/obspy_PSD.log)

[obspy_PSD.log](https://github.com/obspy/obspy/files/4621857/obspy_PSD.log)

**Comment by megies** [comment]
Github issue tracker is for development related issues. All usage questions should be posted to the users mailing list as I have pointed out multiple times now, in private email and in the gitter chat.

https://github.com/obspy/obspy/wiki#stay-informed
