### ISSUE TITLE
matplotlib RuntimeWarning: More than 20 figures have been opened.

### ISSUE THREAD

**Issue by mikehagerty** [obspy/obspy#2615]
I'm making/saving response plots in batch mode.
matplotlib appears to keep all the figures open between calls to
response.plot().

It seem that a single line would fix this:

core/inventory/response.py line 1865
from:  
```
if outfile:
    fig.savefig(outfile)
else: ...
```

to: 
```
if outfile:
    fig.savefig(outfile)
    plt.close(fig)
else: ...
```

Perhaps there is another reason you're not closing the (saved) fig that I'm missing (?)

Cheers

**Comment by QuLogic** [comment]
`fig` is returned from the function for you to do what you please (including closing it.)

**Comment by mikehagerty** [comment]
Good point!
