### ISSUE TITLE
no 'get_waveforms_bulk' attribute when using a SDS-type Client

### ISSUE THREAD

**Issue by 19giovi87** [obspy/obspy#2616]
Instead of using a FDSN client, waveforms stored in a local repository ("sds store") can be downloaded using the appropriate obspy client. 
A Client of this type rises the following error

`'Client' object has no attribute 'get_waveforms_bulk'`

**To Reproduce**

1) import the client
`from obspy.clients.filesystem.sds import Client
2) construct the client, using the path of the local repository
`CLIENT = Client("/pathToSdsStore")` 
3) CLIENT.get_waveform_bulk won't be found

Operating System: CentOS release 6.7 (HPC cluster)
Python version: python 3.6
obspy version: latest

**Comment by megies** [comment]
Bulk requests on SDS Client are not implemented. But, the whole idea of having the bulk request on other clients is to reduce the overhead of HTTP interactions, i.e. bundle everything in one HTTP request to speed things up. With a local SDS storage that's not a thing, so just make a for loop in your code to request multiple SEED IDs. :-)

**Comment by ThomasLecocq** [comment]
wildcards are also acceped in ``get_waveforms`` for globbing networks or stations...

**Comment by d-chambers** [comment]
I think this is more about API compatibility. For background, it has to do with https://github.com/eqcorrscan/EQcorrscan/issues/394. Although it would just be a few simple loops increasing API compatibility between all the clients is, IMHO, very worthwhile.

**Comment by megies** [comment]
Sure thing, if there's a valid use case to promote it. If somebody wants to implement it go ahead, it would indeed be a very simple PR to make :+1:

**Comment by megies** [comment]
@19giovi87 not sure how this is done in EQCorrscan, but if you need a workaround now, you might get away by subclassing the current SDS client like..

```python
from obspy import Stream
from obspy.clients.filesystem.sds import Client as SDSClient


class SDSBulkClient(SDSClient):
    def get_waveforms_bulk(...):
        st = Stream()
        for ... in bulk:
            st.append(self.get_waveforms(...))
        return st
```

.. and giving that to EQCorrscan. Unless the SDS Client is coded into EQCorrscan as a fixed option..

**Comment by megies** [comment]
@millipedes take a look at this if you want a good first issue to tackle

**Comment by millipedes** [comment]
@megies I am taking a look now.
CC @dsentinel

**Comment by millipedes** [comment]
@megies It seems as though your idea of making a bulk subclass would work (unless structurally we would want to implement it in another way).  In the gitter, you had mentioned that there would need to be a test, are you referring to a unit test? If so I can make a unit test for the method in the class.

I am unfamiliar currently with how the project is set up, is there an SOP to making commits to the project?  I have seen under the project tab that there are several columns that a commit needs to go through to become a part of the package. Is there somewhere where I would submit these (potentially unit test and the subclass) files for review etc.?

**Comment by dsentinel** [comment]
> @megies It seems as though your idea of making a bulk subclass would work (unless structurally we would want to implement it in another way).

I think the idea here is to incorporate this functionality into `SDSClient` so that it has the same interface as HTTP clients like FDSN. So we need to add `get_waveforms_bulk` to `obspy.clients.filesystem.sds.Client ` as `obspy.clients.fdsn.client.Client` does. And perhaps other related supporting functionality.

The call signature should / interface should line up with `fdsn.client` so let that be the model.

> In the gitter, you had mentioned that there would need to be a test, are you referring to a unit test? If so I can make a unit test for the method in the class.

Yes, there should be unittest, as many as necessary to adequately test the new feature. Again you can reference the relevant tests for `fdsn.client`

Look around here https://github.com/obspy/obspy/blob/1440229af113d30933ca808a7a2b1daaa1eb6af6/obspy/clients/fdsn/tests/test_mass_downloader.py#L526 but note, as SDS does not reach out over the network it doesn't need to do all the mock-ing, it can use a small local test. There is already test data in https://github.com/obspy/obspy/tree/master/obspy/clients/filesystem/tests/data


> I am unfamiliar currently with how the project is set up, is there an SOP to making commits to the project? I have seen under the project tab that there are several columns that a feature/fix to an issue needs to go through to become a part of the package. Is there somewhere where I would submit these (potentially unit test and the subclass) files for review etc.?

The contributing guide is https://github.com/obspy/obspy/blob/master/CONTRIBUTING.md and what isn't explicit follows typical opensource/github conventions.
So, create a branch, and start an appropriate PR from it. Since this is a feature, base it off master.
You can ask any questions here or on gitter.

**Comment by millipedes** [comment]
@dsentinel Thank you for the information. I am working on the issue.

**Comment by megies** [comment]
> > @megies It seems as though your idea of making a bulk subclass would work (unless structurally we would want to implement it in another way).
> 
> I think the idea here is to incorporate this functionality into `SDSClient` so that it has the same interface as HTTP clients like FDSN. So we need to add `get_waveforms_bulk` to `obspy.clients.filesystem.sds.Client ` as `obspy.clients.fdsn.client.Client` does.

That. The subclassing above was just a proposal for the original poster as a workaround for the current stable release ObsPy. To fix this in obspy is just adding that function on the existing SDSClient class. (and yes a unit test in `clients/filesystem/tests/test_sds.py`)

> So, create a branch, and start an appropriate PR from it. Since this is a feature, base it off master.
> You can ask any questions here or on gitter.

:point_up_2:

**Comment by millipedes** [comment]
@dsentinel you have mentioned that the signature should be the same in `obspy.clients.fdsn.client.Client` as `obspy.clients.filesystem.sds.Client`.  After looking at the `get_waveforms_bulk` method in `obspy.clients.fdsn.client.Client` I have noticed that there are multiple methods that are used to error check and process user input (i.e. `get_bulk_string`, `_build_url`, `_download`, `_write_to_file_object` etc.) which are defined in `obspy.clients.fdsn.client.Client` (`get_bulk_string` is not in the Client class).

I have read through the code for these functions and I believe that they would be applicable to the `get_waveforms_bulk` method in `obspy.clients.filesystem.sds.Client`.

In terms of code structure, should I import the necessary functions from `obspy.clients.fdsn.client` to `obspy.clients.filesystem.sds.Client` or define them in `obspy.clients.filesystem.sds.Client`?

**Comment by calum-chamberlain** [comment]
Hi all, sorry to interrupt, but I wonder if it would be worth implementing this method on the [`WaveformClient` abstract base class](https://github.com/obspy/obspy/blob/master/obspy/clients/base.py#L257) and base `SDSClient` on that? Then we could have a default loop over `get_waveforms` as a fallback for all `WaveformClient` subclasses.

Because I haven't yet responded to the EQcorrscan thing here as well - I was lazily assuming that clients had similar methods, but it is a simple fix on my end to cope with there being no `get_waveforms_bulk` method on some clients - definitely my fault!

**Comment by dsentinel** [comment]
> Hi all, sorry to interrupt, but I wonder if it would be worth implementing this method on the [`WaveformClient` abstract base class](https://github.com/obspy/obspy/blob/master/obspy/clients/base.py#L257) and base `SDSClient` on that? Then we could have a default loop over `get_waveforms` as a fallback for all `WaveformClient` subclasses.

This looks like the right way to go. I haven't looked closely at this or seen the abc.
`get_waveforms` is the only abstract method, so I can't imagine it'd have any other impact.

**Comment by calum-chamberlain** [comment]
@millipedes I think the idea with this is to implement a very simple loop over the `.get_waveforms` method of the client - you shouldn't need all the additional methods that are used by `FDSN.Client` because they relate to downloading data, which the `SDS.Client` doesn't do.  I imagine the method would look something like:

```python
...
    def get_waveforms_bulk(bulk):
        st = Stream()
        for bulk_string in bulk:
            st += self.get_waveforms(*bulk_string)
        return st
```

**Comment by dsentinel** [comment]
@millipedes 
A bulk is a list of tuples:
```
        >>> bulk = [("IU", "ANMO", "*", "BHZ", t1, t2),
        ...         ("IU", "AFI", "1?", "BHE", t1, t3),
        ...         ("GR", "GRA1", "*", "BH*", t2, t3)]
```
```
[(network, station, location, channel, startime, endtime),...
```
These are all you need to call `get_waveforms`, as @calum-chamberlain shown above.

All the other methods (download, url... fileobject) aren't relevant as the data is local.

**Comment by millipedes** [comment]
Oh okay.  My misunderstanding, that is why it is in a `filesystem` directory.  This makes things much simpler. Thank you @calum-chamberlain and @dsentinel

**Comment by d-chambers** [comment]
It is a little more advanced, but now that ObsPy supports only 3.7+ we can actually make something like this work to check if a given client upholds the expected interface:

```python
from obspy.client.base import WaveformClient
from obspy.client.{whatever client you want} import Client

is_valid_waveform_client = issubclass(Client, WaveformClient)
```

I would be happy to tackle this in a different PR but if you want to give it a try feel free!

**Comment by millipedes** [comment]
@d-chambers I believe that at the moment that may be beyond my current understanding.  I would definitely be interested in studying a PR that you would make for it to better understand the topic.

**Comment by millipedes** [comment]
@dsentinel @megies I have forked the project and created a "feature_" branch according to the branching model.  I am now in the process of writing the docstring for the method, and I noticed that many of the other methods have doctests.  Is there any particular guideline that I should follow when writing a doctest into the docstring?

**Comment by megies** [comment]
@millipedes doctests usually act as an example usage for the API docs, rather than tests. tests should be in the unit test suite in general. For some very small helper function (something as simple as `multiply(a, b)`) we might only have doctests.

Also, you do not need to reimplement all those helper function you mentioned, any function starting with an underscore is "private" and only supposed to be used internally, and subject to API change/removal/... without any notice to the user base.

**Comment by megies** [comment]
@millipedes regarding docstrings check here: http://docs.obspy.org/coding_style.html

The first line should be strictly one line, with a short as possible description, then an empty line, and then the long description.

**Comment by millipedes** [comment]
@megies Thank you very much for the information.  I will read it and refer to it when necessary.  And the underscore insight makes a lot of sense, I will keep that in mind going forward.

**Comment by millipedes** [comment]
@dsentinel I have created a PR with the method in sds.py.  I am still working on the unit test for it.  I will likely have a small list of questions about it soon.

**Comment by millipedes** [comment]
@dsentinel After thinking about this issue and looking at the unit test for `get_waveforms_bulk` in fdsn, here are the problems/questions that I am running into for the unit test:

1) In https://github.com/obspy/obspy/tree/master/obspy/clients/filesystem/tests/data/tsindex_data there are three files that I can find, `timeseries.sqlite`, `CU/2018/001` (has an .mseed file in this directory), and `IU/2018/001` (has an .mseed file in this directory).
When writing this test should I attempt to get all data over `obspy/obspy/clients/filesystem/tests/data/tsindex_data/` which would read in the two .mseed files?  If so, there is a .sqlite file in this directory, can `get_waveforms` read .sqlite files?  (The alternative to this that I see would be to directly read in both .mseed files from their respective directories which would defeat the purpose of testing a bulk read).

2) I have noticed on the contributing guidelines that the tests should have the form `test_some_feature`.  I have noticed that this in the fdsn version of the method, the test name is `test_download_and_split_mseed`.  This is not applicable to this feature as we are not downloading any data.  What should I name the test for the sds `get_waveforms_bulk` method?

3) I would assume that the test would need to follow these steps, if there is a step that is incorrect/missing could you please provide some guidance:

- Create data in a bulk to be tested against (I would take the data from the .mseed files to be tested against and hard code them into the test)
- Call the `get_waveforms_bulk` method
- test the streams' attributes against the hard coded values to see if the data matches using the `assertEqual` method.

If these steps are correct there are at least two cases that immediately come to mind that could be tested:
- Test sending in wild cards into the method (this could be covered by the unit test for `get_waveforms` as currently I am calling this method in a loop).
- Test to see if a file is not there (I would assume put the above steps in a try block).

If there are any additional cases or either of the above cases are not applicable please let me know.
