### ISSUE TITLE
How to merge only overlapping traces

### ISSUE THREAD

**Issue by juanchosf** [obspy/obspy#2622]
* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a short, self contained, correct example that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)

**Comment by juanchosf** [comment]
As in title, how can I only merge overlapping traces so the gaps are not masked?

I have been trying merge() and obspy.core.trace.Trace.__add__ but it always processes the gaps.

Thank you!

**Comment by calum-chamberlain** [comment]
Can you provide some more information? Have you looked at the [docs page for the different methods](https://docs.obspy.org/packages/autogen/obspy.core.trace.Trace.__add__.html#obspy.core.trace.Trace.__add__) of `merge()`?

At a guess I think you might be talking about data where you have traces from a range of channels, some that overlap and some that don't, and you want to merge the overlaps, but retain separate traces for those traces that have gaps? If that is what you want to do then you can do something like:
```python
st = st.merge(method=1, interpolation_samples=2)  # Will interpolate across the overlap
st = st.split()  # Will split the data that have gaps
```

If that isn't helpful then please let us know what your input data look like (a copy of the output from `print(st)` should be fine), and what you want as output.

**Comment by megies** [comment]
@juanchosf please avoid double postings and use the users mailing list for usage questions (like you did in parallel anyway)
