### ISSUE TITLE
slclient.py configures the root logger

### ISSUE THREAD

**Issue by calcut** [obspy/obspy#2625]
In the master branch,slclient.py
https://github.com/obspy/obspy/blob/master/obspy/clients/seedlink/slclient.py

line 113 calls
`logging.basicConfig(level=numeric_level)`

which is configuring the root logger.
For me this has the effect of sending all my log messages to the console (of all levels). Instead I would like to use my own handlers to manage this.

I'm fairly new to this, but I understand that it is best practice for modules to use their own logger and not touch the root logger.
(e.g. See point 6 in here https://www.machinelearningplus.com/python/python-logging-guide/)

I've just commented out line 113 to work around this (is there a better way?)
But thought I would flag it up as a possible issue.

**Comment by trichter** [comment]
Thanks for flagging it up. I agree! Maybe the `basicConfig` call should be moved to the `main` method which appears to be the entry point for a console script (which is not registered in setup.py). Probably the call to `logger.setLevel` can also be removed as it is already covered by `basicConfig`?

**Comment by trichter** [comment]
In the docs of basicConig it states

> This function does nothing if the root logger already has handlers configured, unless the keyword argument force is set to True.

So maybe it is enough to configure the logging before the Client is initialized?

**Comment by calcut** [comment]
Hmm, I did try doing that, but without success.
(Although could be user error!)

I'm using the code below. I want:
- a stream handler to log warning/error/critical messages to console
- a file handler to log debug/info/warning/error/critical messages to a logfile

If I uncomment 
`logging.basicConfig(level=logging.WARNING)`
Then I don't get any debug messages in my file handler
or if I change to 
`logging.basicConfig(level=logging.DEBUG)`
Then all debug messages are printed to the console (and the file handler)

So I haven't figured out a way of calling logging.basicConfig() sensibly at the top level.
Perhaps I'm missing something.

(Also, I find that setting
log.setLevel(logging.DEBUG)
Does not prevent the root logger being configured/reconfigured by slclient.)

```
def create_log(name, path'):
    # Create a custom logger
    log = logging.getLogger(name)
    # logging.basicConfig(level=logging.WARNING)
    log.setLevel(logging.DEBUG)

    # Create handlers
    c_handler = logging.StreamHandler()
    f_handler = logging.FileHandler(path+'python.log')
    # c_handler.setLevel(logging.DEBUG)
    c_handler.setLevel(logging.WARNING)
    f_handler.setLevel(logging.DEBUG)
    # f_handler.setLevel(logging.WARNING)


    # Create formatters and add it to handlers
    c_format = logging.Formatter(
        '%(name)s - %(levelname)s - %(message)s')
    f_format = logging.Formatter(
        '%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    c_handler.setFormatter(c_format)
    f_handler.setFormatter(f_format)

    # Add handlers to the logger
    log.addHandler(c_handler)
    log.addHandler(f_handler)

    # log.warning('This is a warning')
    # log.error('This is an error')
    # log.info('This is info')
    # log.debug('This is for debug')
    return log
```

**Comment by calcut** [comment]
Hmm, I did try doing that, but without success.
(Although could be user error!)

I'm using the code below. I want:
- a stream handler to log warning/error/critical messages to console
- a file handler to log debug/info/warning/error/critical messages to a logfile

If I uncomment 
`logging.basicConfig(level=logging.WARNING)`
Then I don't get any debug messages in my file handler
or if I change to 
`logging.basicConfig(level=logging.DEBUG)`
Then all debug messages are printed to the console (and the file handler)

So I haven't figured out a way of calling logging.basicConfig() sensibly at the top level.
Perhaps I'm missing something.

(Also, I find that setting
log.setLevel(logging.DEBUG)
Does not prevent the root logger being configured/reconfigured by slclient.)

```
def create_log(name, path'):
    # Create a custom logger
    log = logging.getLogger(name)
    # logging.basicConfig(level=logging.WARNING)
    log.setLevel(logging.DEBUG)

    # Create handlers
    c_handler = logging.StreamHandler()
    f_handler = logging.FileHandler(path+'python.log')
    # c_handler.setLevel(logging.DEBUG)
    c_handler.setLevel(logging.WARNING)
    f_handler.setLevel(logging.DEBUG)
    # f_handler.setLevel(logging.WARNING)


    # Create formatters and add it to handlers
    c_format = logging.Formatter(
        '%(name)s - %(levelname)s - %(message)s')
    f_format = logging.Formatter(
        '%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    c_handler.setFormatter(c_format)
    f_handler.setFormatter(f_format)

    # Add handlers to the logger
    log.addHandler(c_handler)
    log.addHandler(f_handler)

    # log.warning('This is a warning')
    # log.error('This is an error')
    # log.info('This is info')
    # log.debug('This is for debug')
    return log
```

**Comment by calcut** [comment]
As an experiment, I tried adding 
`logging.basicConfig(level=logging.DEBUG, filename="python.log")`

This kind-of does what I want (and I see I can add handlers etc within that call)
I guess my problem is that I wasn't calling basicConfig anywhere, except slclient

This helped me
https://stackoverflow.com/questions/13479295/python-using-basicconfig-method-to-log-to-console-and-file

**Comment by trichter** [comment]
Fixed by the referenced PR.
