### ISSUE TITLE
Obspy 1.2 in Debian/Ubuntu repositories

### ISSUE THREAD

**Issue by carlosfherrera** [obspy/obspy#2632]
Dear ObsPy team,

I don't know if this is the right place to report this. I've noticed that apparently version 1.2 hasn't been incorporated into the Debian/Ubuntu repositories (please check link):

http://deb.obspy.org/pool/main/p/python-obspy/

Is there a plan to update the repositories, or not anymore? Can you also please add Ubuntu 20.04 Focal Fossa into the supported distributions?

Thanks!

**Comment by megies** [comment]
I had some problems getting the packaging done and didn't have time to investigate further.. so there's no timeline currently, sadly

**Comment by carlosfherrera** [comment]
Thanks for the response! It's understandable. So, for the moment I'll try to find other ways to install the newest version. Installing from source could be a good option.

**Comment by megies** [comment]
Anaconda is easiest in most cases @carlosfherrera
