### ISSUE TITLE
SEG2 read issue

### ISSUE THREAD

**Issue by spri902** [obspy/obspy#2634]
Experiencing some weird read issues with Geometrics Geode seismograph SEG2 files.
Sampling rate should be 48kHz but the trace stats have values of 48000.8 kHz
Additionally and likely a related issue are the rounding errors in the delta values. Including a sample file below. Does anyone have any custom read routines they'd like to share (bit shifting and block reading routines???)

 Assuming this is a similar issue to https://github.com/obspy/obspy/issues/2022 and https://github.com/obspy/obspy/pull/2385

The following warnings are printed when I read in a file:
/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/io/seg2/seg2.py:248: UserWarning: Non-zero value found in Trace's 'DELAY' field. This is not supported/tested yet and might lead to a wrong starttime of the Trace. Please contact the ObsPy developers with a sample file.
  warnings.warn(msg)
/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/io/seg2/seg2.py:372: UserWarning: Many companies use custom defined SEG2 header variables. This might cause basic header information reflected in the single traces' stats to be wrong (e.g. recording delays, first sample number, station code names, ..). Please check the complete list of additional unmapped header fields that gets stored in Trace.stats.seg2 and/or the manual of the source of the SEG2 files for fields that might influence e.g. trace start times.
  warnings.warn(WARNING_HEADER) 

[1667.dat.zip](https://github.com/obspy/obspy/files/4784862/1667.dat.zip)

 -  ObsPy version 1.2.1, Python version 3.7.3, OSX mojave
  -  anaconda install

**Comment by spri902** [comment]
@megies Any thoughts on this?

**Comment by savardge** [comment]
I have the same warnings with my SEG2 dataset (different instruments though).

For now, I just make sure to add the DELAY field to the trace start time to deal with that:
`trace.stats.starttime += float(tr.stats.seg2.DELAY)`

I also have these slightly different sampling rates when I read them in Obspy. I use the Obspy resample method or Pyrocko's Jackseis module to deal with that when it's an issue (like with the EQcorrscan package for example).

**Comment by megies** [comment]
@spri902 i never was involved in the SEG2 stuff, so I'd have to first dig into the code real deep like anybody else would looking into this issue. With these kind of issues, we have to rely on the people actually working on these submodules to step up

**Comment by megies** [comment]
Closing, nothing we can do, really
