### ISSUE TITLE
Question about instrument correction in PPSD

### ISSUE THREAD

**Issue by Gelio-0** [obspy/obspy#2638]
Hello everyone,

I'm new using ObsPy, so sorry for such a stupid question.
I have been trying remove instrument response, by providing metadata from a StatiobXML file. 
I use the following script which is based on the tutorial example to remove response  :

from obspy import read, read_inventory
from obspy.signal import PPSD

st = read("https://examples.obspy.org/BW.KW1..EHZ.D.2011.037")
tr = st[0]
tr_new = tr.copy()
inv = read_inventory("https://examples.obspy.org/BW_KW1.xml")
pre_filt = [0.001, 0.005, 45, 48 ]

tr_new.detrend(type='polynomial', order=6) 
tr_new.remove_response(inventory=inv, pre_filt=pre_filt, output="VEL", water_level=10, plot=True)
               # by the way I don't know how to fix the water level

And then I applied  PPSD : 
  ppsd = PPSD(tr_new.stats, metadata=inv, ppsd_length=60)
  ppsd.add(tr_new)
  ppsd.plot(cmap=pqlx, xaxis_frequency=True)

So ppsd values are in the range from -199 to -200. 

However, when I apply PPSD on data without response removal, the plot is correct:
  ppsd = PPSD(tr_new.stats, metadata=inv, ppsd_length=60)
  ppsd.add(tr)
  ppsd.plot(cmap=pqlx, xaxis_frequency=True).

Best.

**Comment by megies** [comment]
The instrument response is taken into account in the internals of the PPSD processing, no need to do it yourself. Actually as you have seen, if you do it yourself, the instrument correction will be doubled, leading to completely nonsensical values.

**Comment by Gelio-0** [comment]
Okay Thanks, I didn't know.
 But is there any possibility to know if the instrument correction is well done after PPSD ?

**Comment by megies** [comment]
Well, the source code is there, so if you have doubts just check it out:
https://github.com/obspy/obspy/blob/master/obspy/signal/spectral_estimation.py

Although it's quite confusing why you would trust `remove_response()` (which we wrote) for instrument correction but not trust us getting it right in PPSD (which also we wrote). Also hundreds of people are using PPSD, @aringler-usgs has some publications with instrument/ambient noise characterizations using PPSD.

**Comment by aringler-usgs** [comment]
@Gelio-0 I good check is if the PSD values are between the high- and low-noise models.  The attached paper gives a basic introduction to some of this sort of thing:
[srl-2019214.1 (15).pdf](https://github.com/obspy/obspy/files/4819145/srl-2019214.1.15.pdf)

If your data has values that are integers, then it is likely that your data hasn't had the instrument response removed (it is in counts).  If your data has a bunch of small floats, then you could be in a situation where the instrument response is removed.  However, it is better to not assume and double check that you have followed the processing steps.  Hopefully, that helps!  Good luck!

**Comment by Gelio-0** [comment]
Thanks to both of you. You helped me.
