### ISSUE TITLE
Bulk request in SeedLink module

### ISSUE THREAD

**Issue by nikosT** [obspy/obspy#2644]
It would be nice if ObsPy would offer a bulk request in get_waveforms by adding for example an inventory object or a station.code list object.

**Comment by d-chambers** [comment]
You know about `get_waveforms_bulk` right?

https://docs.obspy.org/packages/autogen/obspy.clients.fdsn.client.Client.get_waveforms_bulk.html

**Comment by nikosT** [comment]
> You know about `get_waveforms_bulk` right?
> 
> https://docs.obspy.org/packages/autogen/obspy.clients.fdsn.client.Client.get_waveforms_bulk.html

@d-chambers  I'm refferring to the SeedLink module.

**Comment by aringler-usgs** [comment]
@nikosT this might not be helpful, but you can wild card:

```
client.select_stream('GS','ASA5','HH*')
client.select_stream('GS','ASA5','LH*')
client.run()
```

**Comment by megies** [comment]
check out https://github.com/obspy/obspy/pull/2405/files#diff-a0493e27f48b50e18312b9f4508fc29dR74 and https://github.com/obspy/obspy/pull/2405/files#diff-0eb620aa1b2af06568b44a7b57bc1c04R167, might be easy to add a bulk request method

**Comment by nikosT** [comment]
> @nikosT this might not be helpful, but you can wild card:
> 
> ```
> client.select_stream('GS','ASA5','HH*')
> client.select_stream('GS','ASA5','LH*')
> client.run()
> ```

Well, I was wondering more if you could pass an inventory object or at least a list of stations. But anyway, thanks for the tip.

**Comment by nikosT** [comment]
> check out https://github.com/obspy/obspy/pull/2405/files#diff-a0493e27f48b50e18312b9f4508fc29dR74 and https://github.com/obspy/obspy/pull/2405/files#diff-0eb620aa1b2af06568b44a7b57bc1c04R167, might be easy to add a bulk request method

@megies Thanks! This is what I thought also to do but I was trying to avoid this development of code. However, it seems to be necessary otherwise the code will produce a significant slowdown.

I would strongly suggest adding this feature.

**Comment by nikosT** [comment]
`multiselect = ["%s_%s:%s%s" % (net.code, sta.code, cha.location_code, cha.code) \
                               for net in inventory for sta in net for cha in sta]
multiselect = ','.join(multiselect)
st=seedlink._multiselect_request(multiselect, t, t + 400)`

Well, actually it was pretty easy. However, a private function was used (aka API might change without notification).
The get_waveform function could have as argument an Inventory object.
I believe that the objects/classes Inventory + Stream + Client (e.g. fdsn,sds,seedlink etc) should be coupled to each other over API, so that the user would know -for instance- that requesting waveform is bound to the inventory -that he will set as an argument-.

**Comment by megies** [comment]
>  The get_waveform function could have as argument an Inventory object.

I'm not a big fan of that idea. I'd prefer to keep the API simple for the bulk request. You could add a utility helper function (maybe in `core.util` or in `clients.util` or as a method on `Inventory`) that converts an Inventory into the list given to a bulk request, maybe.

> Well, actually it was pretty easy. However, a private function was used (aka API might change without notification).

If somebody would add a `get_waveforms_bulk()` using the private method inside, it would be OK.

> I would strongly suggest adding this feature.

I don't see a reason not to add this `get_waveforms_bulk()`. We're open for PRs.

**Comment by megies** [comment]
stale, closing
