### ISSUE TITLE
Question about PPSD output value by default (without using special_hanging parameter).

### ISSUE THREAD

**Issue by Gelio-0** [obspy/obspy#2650]
Hello,

I would like to analyse ambient noise from different instruments (Geophone, BroadBand,  accelerometer..) by using ObsPy's PPSD. It is therefore necessary for me to have the same unit for the PSD estimation in order to compare them (from different instruments).

For example if my raw data are in velocity (geophone sensor), does ppsd estimation automatically convert it into acceleration, as it shows [(m/s²)²/Hz] [db] when we plot ? Then what if raw data are in acceleration (accelerometer sensor)?

Best.

**Comment by megies** [comment]
Please use the users mailing list for usage questions. Github is mostly for development realted topics and bug reports
