### ISSUE TITLE
Fine grained exceptions for FDSN client

### ISSUE THREAD

**Issue by yetinam** [obspy/obspy#2653]
I'm using the Obspy FDSN client for a fairly huge download and found myself parsing error messages from `FDSNException` objects, which is a bit ugly. I was wondering, if obspy could introduce more fine grained exceptions for different FDSN errors, e.g. `FDSNAuthentificationException`, `FDSNServerException`, ... This was previously done for the `FDSNNoDataException` (#1656).

If there is interest in this, I could write a pull request.

**Comment by megies** [comment]
I don't see a reason why we would not want more fine grained exceptions, so as far as I am concerned, feel free to make a PR.

**Comment by yetinam** [comment]
Hey @megies ,
could you please convert this issue into a PR? I implemented a draft for the exceptions at ec22245ad410b89613f04010396dabca36738f93.

**Comment by megies** [comment]
@yetinam i could, but that would make the first post in this ticket appear as if it was made by me.
I never understood why github did not add the issue->PR conversion properly, they have it hanging in this semi-official deprecated state for years. Let me know if I should go ahead

**Comment by yetinam** [comment]
Okay, than I'll just open a PR and reference this issue.
