### ISSUE TITLE
FDSNNoDataException: No data available for request.

### ISSUE THREAD

**Issue by SaulSJ** [obspy/obspy#2672]
Hi
I am trying to use client.get_waveforms, but I'm getting error.

from obspy import UTCDateTime
from obspy.clients.fdsn import Client
client = Client("IRIS")
t = UTCDateTime("2019-07-04T16:00:00.000")
st = client.get_waveforms("CI", "CCC", "*", "BHZ", t, t + 3)

I get the following message as a result,

FDSNNoDataException: No data available for request.

Observation
$ python3 --version
Python 3.6.9
import obspy
print (obspy.__version__)
1.2.1
$gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

I installed ObsPy with (pip3 install obspy)

For CHF station it works, but I don't know what the problem is for the CCC station, since data is available when I manually download at (http://ds.iris.edu/wilber3/find_event). 
I also saw something similar to my problem at (https://github.com/obspy/obspy/issues/1835); however, it doesn't fix my problem.

Thanks for the help

**Comment by megies** [comment]
I don't see what should go wrong from the obspy side here. This is the request obspy makes:

`http://service.iris.edu/fdsnws/dataselect/1/query?nodata=404&starttime=2019-07-04T16%3A00%3A00.000000&endtime=2019-07-04T16%3A00%3A03.000000&network=CI&station=CCC&location=%2A&channel=BHZ`

If you get this data from IRIS via other means, you should report it to IRIS web service staff.

**Comment by SaulSJ** [comment]
megies, I see. Thanks a lot

**Comment by megies** [comment]
Reopen if needed.
