### ISSUE TITLE
AttributeError: module 'obspy.signal' has no attribute 'filter' when not using stream or trace method to filter

### ISSUE THREAD

**Issue by Nickthenerd93** [obspy/obspy#2674]
Hello, I am trying to filter a numpy array with the obspy.signal.filter module. 
I am running the following code, for this example I use the seismogram from your filtering example, the error occurred as well with my own, locally saved .mseed files:
```
from obspy import read
import obspy.signal

st = read("https://examples.obspy.org/RJOB_061005_072159.ehz.new")
tr = st[0]
data = tr.data
data_filtered = obspy.signal.filter.lowpass(data, 1, 200, corners=2, zerophase=True)
data_envelope = obspy.signal.filter.envelope(data_filtered)

```
Running this code gets me the following error:
```
    data_envelope = obspy.signal.filter.envelope(data)

AttributeError: module 'obspy.signal' has no attribute 'filter'
```
If I insert the following code snippet  before the error occurs the code works:
```
st.filter('highpass', freq=1.0, corners=1, zerophase=True)
# or 
tr.filter('highpass', freq=1.0, corners=1, zerophase=True)
```
I am using Spyder version 4.1.3 with Python 3.8.3 on Linux, I installed obspy via conda install. The version is 1.2.2.

**Comment by megies** [comment]
Use `import obspy.signal.filter` at the top, that should do it

**Comment by Nickthenerd93** [comment]
Yes that did it, now I feel extremely stupid, thank you!

**Comment by megies** [comment]
> Yes that did it, now I feel extremely stupid, thank you!

To be honest, it confuses me too sometimes, but I also never really looked into it
