### ISSUE TITLE
Inventory __add__ mixes deep and shallow copies

### ISSUE THREAD

**Issue by yetinam** [obspy/obspy#2675]
Adding two inventories using the `__add__` operator leads to an inventory consting of a deep copy of the first inventory, but a shallow copy of the second inventory. For example `inv1 + inv2` returns a deep copy of `inv1`, but a shallow copy of `inv2`. This also implies that runtime of inventory addition can change substantially by swapping the summands, if the two inventories differ strongly in size. The function in question is implemented here: https://github.com/obspy/obspy/blob/95b3adbe138bbb9460d3d5dc779660df35daadbb/obspy/core/inventory/inventory.py#L168-L184

I'd suggest either using deep or shallow copies of both inventories. Personally I'd prefer shallow copies for performance reasons and because they leave the option of making a deep copy to the user. I could write a PR, if this should be changed.

**Comment by megies** [comment]
Good catch, I agree this should be changed. `__add__` should make a deepcopy of both items. `__iadd__` should add a deppcopy of `other`, imo.

CC @krischer

**Comment by trichter** [comment]
For merging two inventories without a deepcopy, `Inventory.extend` can be used. Although this does not call `__copy_inventory_metadata` when other is an inventory. Maybe this could be added? By the way, the docs of extend still talk about Catalog.
