### ISSUE TITLE
Gap in data from mass downloader

### ISSUE THREAD

**Issue by NoisyLeon** [obspy/obspy#2679]
Hi, 
I'm using the mass_downloader to download daily continuous records for ambient noise analysis.
While I find the function is quite easy to use and really fast, there is one big question I have.
I set the **reject_channels_with_gaps=False**, because I do **NOT** want to discard the data for the whole day if there is any gaps. However, I'm wondering **how the software would record the location of gaps** so that I can deal with the gapped data in later stages of data processing? Thanks in advance!

Best,
Lili

**Comment by heavelock** [comment]
Are you asking about how to find gaps in data you downloaded? I have no idea if the mass downloader itself have option to do that but you have a few other ways. The most naive is just to read the file and check length of seed. If it's >1, there is a high chance for gaps/overlaps. If you want something more reliable, take a look at script provided with obspy - obspy-scan. Save the results from obspy-scan to npz and interpret them afterwards. Or use local filesystem indexer option from obspy.  It will prepare database with metadata of signals for you. https://docs.obspy.org/master/packages/obspy.clients.filesystem.html

Anyway, for further usage questions you should head to the mailing list or to new discord forum we got. https://discourse.obspy.org/

**Comment by NoisyLeon** [comment]
Thanks Damian, this is really helpful.

Best,
Lili
