### ISSUE TITLE
No focal mechanism returned from client by range search

### ISSUE THREAD

**Issue by shipengcheng1230** [obspy/obspy#2684]
Hi, consider the following MWE:

```python
# python 3.8.3
# obspy 1.2.1
from urllib.parse import parse_qs, urlparse

import obspy
from obspy.clients.fdsn import Client

client = Client("USGS")
e1 = client.get_events(
    starttime=obspy.UTCDateTime(2017, 1, 1), endtime=obspy.UTCDateTime(2019, 1, 1),
    minmagnitude=5.0, minlongitude=-12, maxlongitude=-10, minlatitude=70, maxlatitude=72)
assert not e1[0].focal_mechanisms

parsed = urlparse(e1[0].resource_id.id)
eid = parse_qs(parsed.query)["eventid"][0]
e2 = client.get_events(eventid=eid)
assert e2[0].focal_mechanisms
```

If I search by range as in `e1`, the returned event does not have the focal mechanism information (but it may occasionally have, however, mostly not). If by event id as in `e2`, it will get that. I was wondering if this is an unimplemented feature.

Thanks!

**Comment by krischer** [comment]
You'll have to add `includeallorigins=True` to the first `get_events()` call. ObsPy has no control over the server side logic here - for details please see each service's documentation - e.g. here in the USGS case: https://earthquake.usgs.gov/fdsnws/event/1/

ObsPy in the end just constructs various fdsnws compatible URLs and queries those. You can see the URLs if you initialize the `Client` object with `debug=True`.

Also please use the ObsPy Forum for user questions in the future: https://discourse.obspy.org/

GIthub should be strictly reserved for development related issues.
