### ISSUE TITLE
xseed Parser: Misleading error message when trying to read non existent filename path

### ISSUE THREAD

**Issue by Alec-Mileman** [obspy/obspy#2686]
I've noticed whilst using the Parser function with .dlseed file type that the error 'First byte of data must be in [0-9<]' occurs when an incorrect directory name is entered. This can make it hard to identify whether your file type is corrupt, or that you've entered a wrong directory name

I'd like to make the developers aware, so they can include an error line that identifies an incorrect directory to the user.

**Comment by heavelock** [comment]
What do you mean by incorrect directory name? Inexistent one? 
Could you provide a small, easily [reproducible example ](http://sscce.org/)

**Comment by Alec-Mileman** [comment]
'''
from obspy.io.xseed import Parser
import obspy as ob

mseedpath = '/home/code/my_mseedfile.mseed'
dlseedpath = '/home/code/my_dlseedfile.dlseed'

st = ob.read(mseedpath)
parser = Parser(dlseedpath)
print(st)
'''

If you have a dlseed file in the above directory and change the file name to '123.dlseed', which doesn't exist, you'll get the error stated above, rather than an error indicating that the file directory does not exist.

**Comment by megies** [comment]
I can confirm this, we (had?) similar misleading errors when trying lo load a non existent path with lxml (e.g. to read StationXML).

This should ideally be fixed by centralizing file opening, I think we should be able to use `_generic_reader()` function for this from `obspy.core.util.base`

**Comment by megies** [comment]
See #2062 for a similar fix and we should reuse the same error message and exceptions as done there

**Comment by gbbofh** [comment]
I've started looking into resolving this issue.
