### ISSUE TITLE
Test fails in UTCDateTime.matplotlib_date

### ISSUE THREAD

**Issue by megies** [obspy/obspy#2690]
Current master, see https://tests.obspy.org/111684/#3 and #2689 

e.g.
```
File "/home/runner/work/obspy/obspy/obspy/core/trace.py", line 2536, in obspy.core.trace.Trace.times
Failed example:
tr.times("matplotlib")
Expected:
array([ 733643.01392361, 733643.01392373, 733643.01392384, ...,
733643.01427049, 733643.0142706 , 733643.01427072])
Got:
array([ 14480.01392361, 14480.01392373, 14480.01392384, ...,
14480.01427049, 14480.0142706 , 14480.01427072])
```

**Comment by QuLogic** [comment]
Probably the epoch change https://matplotlib.org/users/whats_new.html#dates-use-a-modern-epoch

**Comment by megies** [comment]
Ah, thanks for the link, so basically everything's fine and we just have to use `set_epoch()` in our test suite.

**Comment by megies** [comment]
Actually with all the different ways our tests can be executed, it might be a bit tricky to swap to the epoch that test results expect in all cases for doctests (unittests should be trivial, can just use `set_poch()` inside the test method)..
 - via `$ obspy-runtests`: can simply use `set_epoch()` inside `scripts/runtests.py`
 - via `$ pytest ...`: could maybe check for [`PYTEST_CURRENT_TEST`](https://docs.pytest.org/en/4.6.1/example/simple.html#pytest-current-test-environment-variable) inside `UTCDateTime.matplotlib_date()`  (although seems a bit convoluted)
 - via `$ python some_of_our_files.py` -- maybe no chance

**Comment by kdalbey** [comment]
I encountered this problem USING obspy, there was existing code that use obspy that worked on linux and mac but to get it to compile/link on windows10 using anaconda I had to update a few libraries including matplotlib and obspy.    Anyway I encountered this problem and got stuck on it for several days, the code that called obspy was always doing a matplotlib.dates.date2num(<UTCDateTime>.datetime) to get a number comparable to res[:,0] coming out of array_analysis.array_processing() 

but a small change to this the array_analysis.array_processing() would transparently fix this issue for your users in a backwards compatible way (requires matplotlib >=2.1.2, which is when matplotlib.dates.date2num started taking numpy.datetime64 which was introduced in numpy 1.7 so numpy >=1.7 also required)

if you 
import matplotlib.dates as mdates
at the top of array_analysis.py and then make the following change circa line 1022

    elif timestamp == 'mlabday':
        # 719163 == days between 1970 and 0001 + 1
        #res[:, 0] = res[:, 0] / (24. * 3600) + 719163
        res[:, 0] = res[:, 0] / (24. * 3600) + mdates.date2num(np.datetime64('1970-01-01'))

then it will work for whatever epoch the user happens to be using in their own code (even a non-standard one)

This fixed my problem.

**Comment by trichter** [comment]
@kdalbey Thanks for mentioning this issue. A similar fix is now implemented in the referenced PR.
