### ISSUE TITLE
SEGY read error

### ISSUE THREAD

**Issue by savardge** [obspy/obspy#2699]
Hi, 
I have trouble reading a 15 GB SEGY file. Obspy can read several hundreds of trace and then fails with:

> SEGYTraceReadingError: Too little data left in the file to unpack it according to
>                   its trace header. This is most likely either due to a wrong
>                   byte order or a corrupt file.

Is there any way Obspy could salvage the good uncorrupted traces and skip the bad ones?
I can send a link to that file privately in an email to any Obspy developer who would like to give a closer look.

Similar to issue #606 that was abandoned.

**Comment by megies** [comment]
You'll probably need 40-80 GB RAM or more in your machine depending on how small individual traces are to read a file of that size. What kind of a machine are you trying to read that file on?

**Comment by savardge** [comment]
I have access to 64 GB of RAM (it's an HPC cluster node). I am also using the iread_segy function to read sequentially through traces to minimize memory usage. My script loops through traces, merging them until they are a day-long stream then saves that to disk. In summary, it splits the SEGY file into day-long, single-channel files. My code has been working with many other SEGY files of similar size, so I don't think it's a memory issue. 

This one particular file seems to have a few corrupted traces for some reason, so I was wondering if the function could be modified to skip those so it can read the following traces, in case there is some good data that can be rescued. Perhaps it's a naive question and I don't know the SEGY format in-depth, but I thought I'd ask in case it's feasible. I know the first 700 traces were fine, but I don't know how much good data there is in the rest of the file.

**Comment by savardge** [comment]
Thankfully, my collaborators were able to send me an uncorrupted copy of the segy data. I will close the issue since salvaging parts of a corrupted file is probably a very uncommon problem to fix.

**Comment by megies** [comment]
Glad to hear you could work around the problem.
