### ISSUE TITLE
SEG-Y rev 2 write support

### ISSUE THREAD

**Issue by dbpodrasky** [obspy/obspy#2712]
Are there any plans or progress on implementing SEG-Y rev 2 write method(s)?

**Comment by ThomasLecocq** [comment]
Hi,

Short answer: no.

Long answer: yes, if someone takes the lead on this. I don't know any plan for such write method for now, certainly for a really old and complicated "standard", which is not really used anymore (except in industry, I suspect).

please use https://discourse.obspy.org/ for questions next time, the Issues here are used for development/bug reports.
