### ISSUE TITLE
NORDIC write and time weights

### ISSUE THREAD

**Issue by WayneCrawford** [obspy/obspy#2716]
I'm not sure that the current method of determining the pick weight when writing to Nordic is appropriate.  If I understand correctly, the arrival.time_weight value is used, but the documentation for time_weight says:

> time_weight = Weight of the arrival time for computation of the associated Origin. Note that the sum of all weights is not required to be unity.

This definition is copied directly from  the QuakeML documentaiton

By this definition, I would assume that the bigger the time_weight, the more sure the pick is, which is the opposite of the NORDIC/HYPO71 convention, which states that 

> 0 corresponds to w1=1.0, 1 to w1=0.75,  2 to w1=0.5, 3 to w1=0.25 and 4 to w1=0

where I assume that `w1` is closer to the StationXML/QuakeML  timeWeight.

This may work ok if you are deliberately writing a pick/arrival to output to NORDIC format, but probably not if you are inputting data from an outside source or trying to make a generally good/consistent event object.

If you agree that this is a problem, I can think of two solutions:

1. set the Nordic weight to `round(4*(N - time_weight))`, where 

  - `N=1` will reproduce the correspondance with w1 but depends on the time_weights are between 0 and 1
  - `N=max(time_weight)` might be more robust
 
2. allow write_nordic to take another input parameter which sets the pick.timeuncertainty corresponding to each NORDIC weight value.  This would which allows one to explicitly specify the time_uncertainty corresponding to each weight and would to avoid having to create an arrival for each pick if all you have is picks

I  favor a combination of both, basing the NORDIC weight on the arrival time_weight unless the pick.timeuncertainty mapping is specified in the write function call.

Regards
Wayne

**Comment by megies** [comment]
I'm not sure I fully understand the details of what you're proposing in 1) and 2). I understand the general issue, though, with older location codes often using integers 1 through (e.g.) 4 for degrading pick quality, which is kinda the inverse of float pick weighting.

So by all means, go ahead, you and @calum-chamberlain did most of the work here, so whatever you folks agree on works for me. If you base it on master for 2.0.0 it is OK to have the logic change there if it's properly documented and mentioned clearly in the changelog.

**Comment by WayneCrawford** [comment]
OK, here's my proposition @calum-chamberlain :
  
-  add a parameter uncertainty-mapping to write_select.   This could be a list of the maximum time_errors for a given nordic_weight, for example `[0.1, 0.2, 0.4, 0.8]` would give a weight of "0" for uncertainties less than 0.1s, "1" for 0.1-0.2s, "2" for 0.2-0.4, "3" for 0.4-0.8 and "4" for the rest.  No weight is given for a pick without a time_error

- if this parameter is not set, then the pick weight will be based on the Arrival.time_weight according to the following formula:

```
if all(time_weight <= 1): 
    nordic_weight = round(4. * (1-time_weight))  # alternatively floor(4.9999. * (1-time_weight))
else nordic_weight = round(4. * (max(time_weights) - 1)  # or the alternate form
```

The alternate form would give a more even nordic weight distribution

**Comment by calum-chamberlain** [comment]
Hi @WayneCrawford, sorry for the slow reply!

I see what you are saying and agree that NORDIC weighting is effectively the reverse of what is expected in location programs, and I think that mapping more appropriately would be good.

The proposition above seems very reasonable - I think we probably need to make sure that there is a reverse mapping for the case of reading from NORDIC as well.  We also need to cope with weights of `9`, which correspond to (I think) zero-confidence in absolute time, but can be used for S-P times.

Thanks for this: are you happy to start a PR with these changes @WayneCrawford ?

**Comment by megies** [comment]
> NORDIC weighting is effectively the reverse of what is expected in location programs

It really depends, a lot of "older" (but still used) location programs use integer weights in the style of 1 (lowest uncertainty) through 4 (not used), so one just have to be careful which one it is in all cases.

**Comment by WayneCrawford** [comment]
I still haven't gotten to this, but I found what I think is a bug in `utils.py:_str_conv(number, rounded=False)`:

The docstring states "if the int or float is None, returns empty string", but the implementation is:

```python
    if not number:
        return str(' ')
```

which means that 0.0 will return " ".  I think that this should be
```python
    if number is None:
        return str(' ')
```

**Comment by WayneCrawford** [comment]
The above does create a problem because of the following code in nordpick():

 ```python
weight = _str_conv(int(arrival.time_weight or 0))
```
which means that _str_conv never gets a `None`
I changed this code (inelegantly) to:
 ```python
if arrival.time_weight is None:
    weight = " "
else:
    weight = _str_conv(int(arrival.time_weight or 0))
```

**Comment by WayneCrawford** [comment]
I don't like defaulting the pick weight to "0" (best pick) but couldn't think of a way to do better, except maybe with a try...except case.  Anyway this is stop-gap stuff until version 2.x

**Comment by WayneCrawford** [comment]
On the same thread, I think that, further down in nordpick:

```python
else:
    caz, distance, timeres, azimuthres, azimuth, weight, ain = ( ' ', ' ', ' ', ' ', ' ', '0', ' ')
```
should be replaced by 
```python
else:
    caz, distance, timeres, azimuthres, azimuth, weight, ain = ( ' ', ' ', ' ', ' ', ' ', ' ', ' ')
```
Again, I don't think pick weights should default to 0 (best pick)

**Comment by calum-chamberlain** [comment]
Good catch on the `_str_conv` - that should be changed to return blank when given a `None` only.  This doesn't make a difference for using files in SEISAN because weights of `0` or blank are interpreted the same (e.g. full weight), so this wouldn't be a breaking change in that regard. 

if `_str_conv` copes with `None` then we shouldn't need the:
````python
if arrival.time_weight is None:
   weight = " "
else:
   weight = _str_conv(int(arrival.time_weight or 0))
````
although this would have to be updated with your fix for mapping weights.

The reason I set blank pick weights to a zero weight is because:
1. SEISAN interprets blank and 0 the same
2. If you do not explicitly weight a pick in SEISAN then the default weight is blank (`== None`), so this behaviour mimics that.
I don't think changing to any other weight makes sense, and certainly wouldn't be what was expected for SEISAN users (who are likely the main audience of this module).

**Comment by WayneCrawford** [comment]
Hi Calum,

I guess you are right overall, if SEISAN interprets blank and 0 the same.  My worry was that, when parsing picked data, if I see a "0" I assume that someone thought it was an excellent pick when in fact they (or a computer) simply didn't evaluate its quality.  Mostly semantic.

Cheers
Wayne

**Comment by calum-chamberlain** [comment]
I think you are right in thinking that, and so I think not changing `None` to `0` would be good just for clarity, so it would be great to change that `_str_conv` to your original suggestion:

```python
if number is None:
    return str(" ")  # I'm not sure we need the "str" now that we don't support Py 2
```

**Comment by WayneCrawford** [comment]
OK, would that be ok to change in an intermediate version ("bug fix", don't wait for 2.0)?

The other changes would wait for 2.0.  One other thing, I'd like to add a way to read the type "I" line.  Ideally, this line could be put back into a new NORDIC file, which means its value must be stored, like wavefiles.  Instead of adding another output to return in read_nordic, I think it might be better to change "return_wavnames" to something like "return_specific" and the second return variable would be a dictionary with keys = "wavenames", "infolines", etc, which would also allow addition of new line-types that don't have a corresponding QuakeML entry (are there others?).

What do you think?

Cheers
Wayne

_______________________________
Wayne Crawford
CNRS Researcher
Institut de Physique du Globe de Paris
1, rue Jussieu
75238 Paris Cedex 05
+33 6 5151 1054

On 2 November 2020 at 19:28:28, Calum Chamberlain (notifications@github.com) wrote:

I think you are right in thinking that, and so I think not changing None to 0 would be good just for clarity, so it would be great to change that _str_conv to your original suggestion:

if number is None:
    return str(" ")  # I'm not sure we need the "str" now that we don't support Py 2

**Comment by calum-chamberlain** [comment]
I think that would be okay to change in an intermediate version.

Adding reading of "I" lines would be great. I would probably put them into `Event.comments` verbatim though and just have them returned by default. Then the user can work out what to do with them. I don't know what we would do about writing them though.

I'm not keen to change the `return_wavenames` arguments - I know a few people who rely on that argument; unless you mapped that as a `kwarg` to something else.

**Comment by WayneCrawford** [comment]
Re: @calum-chamberlain's comment that, if `_str_conv()` copes with `None` would avoid having to use
```python
if arrival.time_weight is None:
   weight = " "
else:
   weight = _str_conv(int(arrival.time_weight or 0))
```

The problem is that `int()` doesn't cope with `None`, so a 0 is always passed to `_str_conv()` if `arrival.time_weight==None`

So I'm going to submit a PR with three changes, which will be explained in the comments

**Comment by megies** [comment]
corresponding PR is in #2749

**Comment by megies** [comment]
That corresponding PR was merged so I believe this can be closed, please reopen if not
