### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by rahultorlapati** [obspy/obspy#2721]
Using cached obspy-1.2.2.zip (24.7 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/anaconda3/bin/python /opt/anaconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/1z/07q21xj93x96c2h9z904lbd00000gn/T/pip-build-env-20toihbs/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'numpy>=1.6.1' setuptools
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/opt/anaconda3/lib/python3.7/site-packages/pip/__main__.py", line 23, in <module>
      from pip._internal.cli.main import main as _main  # isort:skip # noqa
    File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 5, in <module>
      import locale
    File "/opt/anaconda3/lib/python3.7/locale.py", line 16, in <module>
      import re
    File "/opt/anaconda3/lib/python3.7/re.py", line 145, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/anaconda3/bin/python /opt/anaconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/1z/07q21xj93x96c2h9z904lbd00000gn/T/pip-build-env-20toihbs/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'numpy>=1.6.1' setuptools Check the logs for full command output.

**Comment by QuLogic** [comment]
You have `enum34` (or some other `enum` backport) installed in your conda environment. You should remove it as it's only for <3.4.

**Comment by megies** [comment]
> It's also a good idea to create separate environments for testing instead of installing everything into the root environment.

:point_up_2: i'd recommend not installing any additional packages into base environment
