### ISSUE TITLE
docs: Replace mentions of obspy-users mailing list

### ISSUE THREAD

**Issue by dr-glenn** [obspy/obspy#2735]
I have tried to register - never received a response.
I tried to email to the list, got this "permanent error":

`A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:
  obspy-users@lists.swapbytes.de
    (generated from users@obspy.org)
    retry timeout exceeded
`
So I'll try https://gitter.im/obspy/obspy.

**Comment by barsch** [comment]
The user mailing list has been replaced with an discourse forum: https://discourse.obspy.org/. Where did you find the link to the old mailing list?

**Comment by dr-glenn** [comment]
The link is in what appears to be the latest online obspy documentation.
The last posting to it was sometime in July 2020.

It's good to know there's something new!

Glenn Nelson in Santa Cruz

**Comment by dr-glenn** [comment]
Here you go - home page of obspy docs: https://docs.obspy.org/, select
Mailing Lists from the top menu bar.

----
Glenn Nelson in Santa Cruz

**Comment by megies** [comment]
Ah thanks for pointing that out, we might have to change some pages in docs. Reopening as a reminder
