### ISSUE TITLE
Trace.times('utcdatetime') is slow

### ISSUE THREAD

**Issue by WayneCrawford** [obspy/obspy#2741]
Hi,
I'm writing a code using obspy and did a little profiling to speed it up.  I found that the biggest bottleneck in the code was
Trace.times('utcdatetime'), which takes 100-1000x longer than Trace.times('timestamp') for a 36000-point Trace.

Is there a way to speed this up?  If not, the documentation for times() should mention this so that users don't get clogged up by unnecessary calls to times('utcdatetime').

```python
from time import perf_counter
from obspy import read

tr = read('http://examples.obspy.org/RJOB_061005_072159.ehz.new')[0]
print(f'Running Trace.times() for {tr.stats.npts} samples')
for type in ['utcdatetime', 'matplotlib', 'timestamp', 'relative']:
    tic = perf_counter()
    times = tr.times(type)
    toc = perf_counter()
    print(f"{1.e3*(toc-tic):7.2f} ms for '{type}'")
```
gave me
```
 351.68 ms for 'utcdatetime'
  13.24 ms for 'matplotlib'
   0.44 ms for 'timestamp'
   0.24 ms for 'relative'
```
Cheers
Wayne

OBSpy version 1.2.1
installed using Anaconda

**Comment by QuLogic** [comment]
A patch like this:
```patch
diff --git a/obspy/core/trace.py b/obspy/core/trace.py
index bf36aab22..f0783fdb6 100644
--- a/obspy/core/trace.py
+++ b/obspy/core/trace.py
@@ -2559,8 +2559,8 @@ seismometer_correction_simulation.html#using-a-resp-file>`_.
         elif type == "timestamp":
             time_array = time_array + self.stats.starttime.timestamp
         elif type == "utcdatetime":
-            time_array = np.array(
-                [self.stats.starttime + t_ for t_ in time_array])
+            time_array = np.vectorize(lambda t: self.stats.starttime + t)(
+                time_array)
         elif type == "matplotlib":
             from matplotlib.dates import date2num
             time_array = (
```
goes from:
```
Running Trace.times() for 36000 samples
 227.91 ms for 'utcdatetime'
   9.03 ms for 'matplotlib'
   0.24 ms for 'timestamp'
   0.18 ms for 'relative'
```
to:
```
Running Trace.times() for 36000 samples
 140.80 ms for 'utcdatetime'
   8.62 ms for 'matplotlib'
   0.23 ms for 'timestamp'
   0.12 ms for 'relative'
```
but all the extra objects will probably still be slow any which way.

**Comment by d-chambers** [comment]
Hi @WayneCrawford ,

I would recommend avoiding using `UTCDateTime` in numpy arrays entirely. Numpy provides an official solution with [datetime64 and friends](https://numpy.org/doc/stable/reference/arrays.datetime.html). Does your application actually require `UTCDateTime` instances for some reason? 

I agree about the documentation, adding a warning in the docstring would be a great idea.

**Comment by WayneCrawford** [comment]
No, I can work just fine with timestamps, so there is no problem for me.  But I figured that others might try the same "easy" solution as I did, so a little documentation upgrade would save a lot of time for them.

Cheers
Wayne

_______________________________
Wayne Crawford
CNRS Researcher
Institut de Physique du Globe de Paris
1, rue Jussieu
75238 Paris Cedex 05
+33 6 5151 1054

On 3 November 2020 at 20:04:49, Derrick (notifications@github.com) wrote:

Hi @WayneCrawford ,

I would recommend avoiding using UTCDateTime in numpy arrays entirely. Numpy provides an official solution with datetime64 and friends. Does your application actually require UTCDateTime instances for some reason?

I agree about the documentation, adding a warning in the docstring would be a great idea.

**Comment by megies** [comment]
Well, the option to return sample times as `UTCDateTime` objects clearly is for convenience and when speed optimization is not the focus. I don't really the the issue, for people optimizing something for speed it should be pretty clear that it can't be the fastest solution to generate an array of ten thousands of custom non-lightweight objects. :wink:

**Comment by megies** [comment]
> so a little documentation upgrade would save a lot of time for them

PRs are always welcome, if you think there should be clarification on this.
