### ISSUE TITLE
Stream.stack sets starttime to 1970-01-01 if trace starttimes not equal

### ISSUE THREAD

**Issue by WayneCrawford** [obspy/obspy#2744]
Hi there

The title says it all.  I think it would be better to either:
   - quit with an error message
  - take one of the provided startimes if `not ntol==0` and the difference is less than the tolerance
  - trim the data to the same length/starttime before stacking if both differences are within `ntol`

An example of the current behavoir:
```python
from obspy import read
from obspy.core.stream import Stream

tr = read('http://examples.obspy.org/RJOB_061005_072159.ehz.new')[0]
tr2 = tr.copy()
tr3 = tr.copy()
tr3.stats.starttime += 0.001
st1 = Stream(traces=[tr, tr2])
st2 = Stream(traces=[tr, tr3])
print(st1)
print(st2)
st1.stack()
st2.stack()
print(st1)
print(st2)
```
gives
```
2 Trace(s) in Stream:
.RJOB..Z | 2005-10-06T07:21:59.850000Z - 2005-10-06T07:24:59.845000Z | 200.0 Hz, 36000 samples
.RJOB..Z | 2005-10-06T07:21:59.850000Z - 2005-10-06T07:24:59.845000Z | 200.0 Hz, 36000 samples
2 Trace(s) in Stream:
.RJOB..Z | 2005-10-06T07:21:59.850000Z - 2005-10-06T07:24:59.845000Z | 200.0 Hz, 36000 samples
.RJOB..Z | 2005-10-06T07:21:59.851000Z - 2005-10-06T07:24:59.846000Z | 200.0 Hz, 36000 samples
1 Trace(s) in Stream:
.RJOB..Z | 2005-10-06T07:21:59.850000Z - 2005-10-06T07:24:59.845000Z | 200.0 Hz, 36000 samples
1 Trace(s) in Stream:
.RJOB..Z | 1970-01-01T00:00:00.000000Z - 1970-01-01T00:02:59.995000Z | 200.0 Hz, 36000 samples
```

**Comment by trichter** [comment]
Hi,
we have `npts_tol` for the tolerance in number of samples and `time_tol` for the tolerance in starttimes (taking the median starttime if the difference is below the tolerance). I think both are part of obspy 1.2.

Quitting with an error message or raising a warning is probably not what we want, because stacking data of different time periods is a valid use case.

**Comment by WayneCrawford** [comment]
OK, I see and in fact this is correctly documented.  My mistake.

**Comment by trichter** [comment]
No problem...
