### ISSUE TITLE
issue with writing SC3 xml file(?)

### ISSUE THREAD

**Issue by hadighasemi** [obspy/obspy#2755]
Hi All,

I am trying to write an Obspy Catalogue object into a SC xml file, and noticed that the "magnitude" section is missing from the produced xml file! 

the version in use is: '1.2.2', and here is the sample script to generate the SC's xml file:

[write_SC_eq_cat_sample.txt](https://github.com/obspy/obspy/files/5586231/write_SC_eq_cat_sample.txt)

 any help would be appreciated!

Cheers
Hadi

**Comment by megies** [comment]
Seems like you need to link magnitude to origin.

```python
mag.origin_id = ot.resource_id
```

There's some other stuff to keep in mind, can read up here: https://github.com/obspy/obspy/blob/master/obspy/io/seiscomp/data/quakeml_1.2__sc3ml_0.10.xsl
