### ISSUE TITLE
TSIndex bugs

### ISSUE THREAD

**Issue by heavelock** [obspy/obspy#2761]
I'm trying to implement usage of TSIndex in my app and I found some bugs in the `Indexer` class of TSIndex

1. `leap_seconds_file="SEARCH"` and passing as `database`  an instance of `TSIndexDatabaseHandler` initialized not with argument `database` but with `session` raises error in method `_get_leap_seconds_file` on line `dbpath = os.path.dirname(self.request_handler.database)`. The request handler in this case does not have a `database` attribute. Changing value of `leap_seconds_file` fixes the problem because the if/else skips that part.
2. `Indexer.run` will likely not run either due to the same reason. If address will not be explicitly provided, to `Indexer` in `bulk_params["-sqlite"]`, and database will be passed as described before, this code will raise an exception:
```
        if self.bulk_params.get("-sqlite") is None:
            # set path to sqlite database
            self.bulk_params['-sqlite'] = self.request_handler.database
```
3. TSIndex is not compatible with PostgreSQL despite of mseedindex being able to use it but I guess its a design decision

@chad-iris @nick-falco

**Comment by megies** [comment]
CC @nick-falco @chad-iris

**Comment by chad-iris** [comment]
Thanks @heavelock.  There are a number of rough edges in the tsindex module usage and docs and I was planning on working on them in near future.  I'll add this to the list.

> TSIndex is not compatible with PostgreSQL despite of mseedindex being able to use it but I guess its a design decision

Can you expand on this a bit more, how is it not compatible?

It was not the original intention to make the module work with Postgres, but at the nudging of the reviewers we put a fair bit of time into using SQLAlchemy so it was DB agnostic and hopefully close to working.

**Comment by heavelock** [comment]
So, the incompatibilities that I can see: (numbering continuing from the initial post)
4. `Indexer.run` always runs method `TSIndexDatabaseHandler._set_sqlite_pragma()` (call `self.request_handler._set_sqlite_pragma()`
5. `Indexer.run` always adds to run cmd parameter `-sqlite` in that call:
```
        if self.bulk_params.get("-sqlite") is None:
            # set path to sqlite database
            self.bulk_params['-sqlite'] = self.request_handler.database
```
So even if you add `-pghost` to bulk_params along with all the connection details, `-sqlite` will be added either automatically (which will raise Exception since TSIndexDatabaseHandler.database is not set) or user has to add empty `-sqlite` and add that to the command on its own.

Solution proposals:
1. Either check for `.database` being `None` and set the dir to CWD or use the CWD directly. The latter one might be polluting in case of known sqlite db.
2. On initialization of `TSIndexDatabaseHandler` from `Session` grab `Session.url` and disect it to check if it's sqlite or postgres
2a. Also this would be super useful because from disected URL you can grab all necessary connection parameters for postgres. 
The url:
```
postgresql+psycopg2://postgres:postgres@postgres:5432/dbname

```
4. If the db is sqlite, set pragma, if postgres, call sql `CREATE EXTENSION hstore;` which is necessary. 
5. this could be fixed by with use of point 2a

BTW: If we are at connection params, mseedindex is not able to connect to postgres on different port than default because it does not have in CLI `-pgport` :P

**Comment by chad-iris** [comment]
I made some small progress on these issues in PR #2776, reducing the dependency on the database path, and isolating SQLite code when that engine is used.

The issue is bigger than I thought and the module remains dependent on specifying an SQLite database file (as opposed to a `TSIndexDatabaseHandler` object) for most operations.  In the PR I've added a warning to that docs that direct use of  `TSIndexDatabaseHandler` experimental.  It cannot yet be used to support TSIndex operation on other databases.

A `TSIndexDatabaseHandler` object cannot be used by the `Indexer` as it needs to have the path to the SQLite database or other connection parameters to pass to `mseedindex`.  This could be overcome by parsing the URL connection string as suggested, and SQLAlechmy has done that for us: https://docs.sqlalchemy.org/en/14/core/engines.html

A more significant issue is that the SQL schema is different between SQLite and PostgreSQL (timestamp versus string, hstore versus string) and needs different treatment.  Also, the current Client extraction code is using a GLOB operator for SQLite that is not supported on PostgreSQL, could be ported to LIKE usage though.  These are surmountable, but significant changes that require code specific to SQL engine dialect.  If I were to do this I would consider using raw SQL statements to avoid the ORM, which adds a layer of complexity that is hard to justify (it's already quite complex).

> BTW: If we are at connection params, mseedindex is not able to connect to postgres on different port than default because it does not have in CLI -pgport :P

It has a `-dbport` option though :P

**Comment by dsentinel** [comment]
Nice work

> A more significant issue is that the SQL schema is different between SQLite and PostgreSQL (timestamp versus string, hstore versus string) and needs different treatment. Also, the current Client extraction code is using a GLOB operator for SQLite that is not supported on PostgreSQL, could be ported to LIKE usage though. These are surmountable, but significant changes that require code specific to SQL engine dialect. If I were to do this I would consider using raw SQL statements to avoid the ORM, which adds a layer of complexity that is hard to justify (it's already quite complex).

SQLAlchemy has constructs for these cross platform differences e.g.

`DateTime` type which uses nativedb timestamps, or for db's lacking like  SQLite, strings and does the conversion back and forth automatically.

and

GLOB can be achieved with the `column.contains` 

`hstore` is a whole other ball of wax. I've only seen in Postgres. I'm not sure how to overcome in a clean way. The obvious choices are ditch hstore and use a table with FK. or for non Postgres db's use a pickled dict. I don't recall If I spoke up when I saw hstore in the original PR, but it did make me cringe. I would lean to the former, dropping hstore completely.

**Comment by chad-iris** [comment]
> DateTime type which uses nativedb timestamps, 
> GLOB can be achieved with the column.contains

Ah, thanks!  I _thought_ there must be a better way.

> hstore is a whole other ball of wax. I've only seen in Postgres. I'm not sure how to overcome in a clean way. The obvious choices are ditch hstore and use a table with FK. or for non Postgres db's use a pickled dict. I don't recall If I spoke up when I saw hstore in the original PR, but it did make me cringe. I would lean to the former, dropping hstore completely.

In addition to `hstore`, there are also arrays of `numrange[]` and `numeric[]` types to deal with.

The table schema (for both databases) is cooked and done in terms of backward-incompatible changes, with a large energy barrier before a new version of the schema could be justified.  This module is a bridge, adapting as needed, to an existing ecosystem; this tail does not easily wag that dog.

**Comment by dsentinel** [comment]
The joys of backwards compatibility. 

`indexable` may the a solution. Works with arrays as well, and json could be the sqlite solution. 

https://docs.sqlalchemy.org/en/13/orm/extensions/indexable.html

**Comment by megies** [comment]
Can this be closed?

**Comment by heavelock** [comment]
I bet it can, I did not look at that issue later on unfortunately. I hope I will my code from my times at Unistra open sourced soon and I might come back to that issue in the future. 
Cheers!
