### ISSUE TITLE
How to download the waveform files in SAC format using MassDowloader?

### ISSUE THREAD

**Issue by vivigb** [obspy/obspy#2769]
Eventhough I mass downloaded the waveform from the IRIS using Obspy MassDownloader. I think It is not possible to download the data in SAC format rather than MSEED. ! If it is not my mistake hope you consider to add such a functionality in next release.
Thank you

**Comment by jkmacc-LANL** [comment]
SAC files would be 3-4 times larger if that's what was actually downloaded, which could significantly slow things down.  While it may be more convenient for `mass_downloader` to optionally return SAC files, it really isn't too much work to convert them after downloading: 

```python
import glob
from obspy import read

for mfile in glob.glob('*.mseed', recursive=True):
    for (i, tr) in enumerate(read(mfile)):
        tr.write(mfile.replace('.mseed', "{}.sac".format(i)))

```

You'll want to probably keep track of directories better than this, but this is pretty close to an actual file conversion you could use.

**Comment by vivigb** [comment]
Thanks.
Yeah, it would be more convenient if `mass_downloader` have an option to download it in `.SAC` format.

**Comment by heavelock** [comment]
Well, since it is not what actually is being downloaded I think it should be left to user how to process the received data instead of hiding it within the obspy's code.
But anyway, nothing is stopping you from sending a PR with your proposal `mass_downloader` modification.

**Comment by ThomasLecocq** [comment]
Indeed, although I don't think this is particularly useful, you are welcome to submit a PR for this.
