### ISSUE TITLE
st.plot() making the kernal crash (Spyder, Win10)

### ISSUE THREAD

**Issue by vivigb** [obspy/obspy#2770]
```
from obspy import read
st=read('II.AAK.00.BHE.2008-01-18T19-16-51.mseed')
st+=read('II.AAK.00.BHN.2008-01-18T19-16-51.mseed')
st+=read('II.AAK.00.BHZ.2008-01-18T19-16-51.mseed')
st.plot()
```
Eventhough it is showing the figure, after closing the figure makes the kernal crash. I have to restart the kernal everytime when i execute `st.plot()`.
I am using spyder in conda environment on windows 10.

**Comment by ThomasLecocq** [comment]
Looks like a bug in Spyder (memory leak or else). Can you reproduce it un Jupyter Notebook or else ? How large are these three files ?

**Comment by vivigb** [comment]
Yeah , I am able to reproduce it in Jupyter notebook! I think I should report this in spyder's repository. 
Thanks

**Comment by megies** [comment]
> Yeah , I am able to reproduce it in Jupyter notebook! I think I should report this in spyder's repository.
> Thanks

I am guessing you meant "I can **not** reproduce in Jupyter"?

**Comment by vivigb** [comment]
I mean to say, the problem is only occurring in Spyder IDE, In Jupiter notebook, I am able to reproduce the map using `st.plot()`
