### ISSUE TITLE
apple silicon on conda forge

### ISSUE THREAD

**Issue by crotwell** [obspy/obspy#2779]
Is there any thoughts of adding obspy for the new Apple M1 chip (osx-arm64) on conda forge? Numpy 1.19.5 is already supported by conda forge for this arch and there are hints and instructions on what is needed to do here:
https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/

Happy to help with this, but not sure where to start.

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a [short, self contained, correct example](http://sscce.org/) that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)

**Comment by heavelock** [comment]
Personally, I don't know about conda build system. However, I will add building wheels for Apple silicon in #2783 via cibuildwheels.

**Comment by QuLogic** [comment]
The conda-forge build is handled on the [obspy feedstock](https://github.com/conda-forge/obspy-feedstock), and really doesn't have to do with this repo.

**Comment by crotwell** [comment]
See this PR on feedstock repo here:
https://github.com/conda-forge/obspy-feedstock/pull/45

Just waiting someone to merge it I think. 

@QuLogic are you able to review/merge? Thanks.

**Comment by lileipku00** [comment]
> See this PR on feedstock repo here:
> [conda-forge/obspy-feedstock#45](https://github.com/conda-forge/obspy-feedstock/pull/45)
> 
> Just waiting someone to merge it I think.
> 
> @QuLogic are you able to review/merge? Thanks.

still unable to install on apple m1

**Comment by calum-chamberlain** [comment]
This has been merged in conda-forge now and should be installable on new arm64 macs - can @crotwell or @lileipku00 or someone else with a new Mac give it a go installing the package, and if possible run the test suite - there may be some "expected" failures but it would be great if you can check to see that most of the package works.

**Comment by lileipku00** [comment]
Thanks.

I have installed successfully. But I don't know how to run the full test suite. There is no `obspy.test()` like `scipy.test()` and `numpy.test()`

**Comment by calum-chamberlain** [comment]
Great, thanks for that! It looks like there might be some matplotlib compatibility issues with the test suite, but I'm not sure that these will affect your use. Otherwise that looks pretty good, including the C-funcs that have been compiled for the arm chip.

Sorry this took so long. I'm going to close this for now. Thanks for your tests!
