### ISSUE TITLE
Obspy PPSD plots have discontinuity at period 0.05-0.06 seconds

### ISSUE THREAD

**Issue by franktorok** [obspy/obspy#2784]
the errors are present in the documentation plots here https://docs.obspy.org/tutorial/code_snippets/probabilistic_power_spectral_density.html
as well as in the plots I generated myself using Python 3.7 and ObsPy 1.2.1
You can see in the plot that the PPSD has the power shifted lower below 0.06 seconds

![image](https://user-images.githubusercontent.com/41352743/107842522-0e1d3e00-6e18-11eb-9829-cdfdb234774e.png)

**Comment by megies** [comment]
That could come from anti-aliasing filters that were applied in the recording system filter chain, but might be missing from the metadata so not corrected for? Something like that.. I don't think it's worth looking into
