### ISSUE TITLE
Installing obspy in pop! OS

### ISSUE THREAD

**Issue by GracielaRojo** [obspy/obspy#2785]
Hello,
I have POP! OS in my computer, from System 76. I installed obspy from the Anaconda regular repository, in a conda environment. It all seemed to go OK but the tests after installation reported 4 issues. (http://tests.obspy.org/?node=pop-os)

Should I install obspy from another source? 

Thank you in advance for your help (and sorry if I make mistakes in the formalities)

Technical specifications: 
obspy 1.2.2 (via anaconda), 
python 3.8 (with apt)
Linux Pop!_OS  20.04, version 20.04.27

**Comment by heavelock** [comment]
What were the issues?

**Comment by barsch** [comment]
I assume http://tests.obspy.org/?node=pop-os

**Comment by GracielaRojo** [comment]
Yes, http://tests.obspy.org/?node=pop-os . The four errors happen during the obspy.core test.

I ran numpy.test(label='full', verbose=2)         
to see if the numerical problem stems from there and the results are 
======= 8915 passed, 79 skipped, 15 xfailed, 4 xpassed in 172.27 seconds =======

Do you think numpy could be the issue?

**Comment by QuLogic** [comment]
Those failures are due to Matplotlib changing the date epoch, #2723

**Comment by GracielaRojo** [comment]
Thank you, QuLogic. I tried your commit from that issue and I ended up with more errors, https://tests.obspy.org/112989/

**Comment by barsch** [comment]
most errors are all related to a missing ```pyimgur``` module - which is not needed for productive usage only for tests - so can be safely ignored

but the very first error is new for me and should be reported - basically Python 3.9 changed the output of ```date.isocalendar()``` from ```tuple``` to ```named tuple``` (https://docs.python.org/3/library/datetime.html#datetime.date.isocalendar) - anyway not really an error just needs slight adjustment of the test case

IMHO you are save to go

**Comment by trichter** [comment]
@barsch Well, but those pyimgur errors only pop up because an image comparison failed.

The errors you see with version 1.2.2 with new matplotlib versions were addressed in #2708, but it is also safe in this case to simply ignore the failing tests.

**Comment by barsch** [comment]
@trichter - right, my bad shouldn't have read the last line only ..

**Comment by GracielaRojo** [comment]
Thank you all, I will use 1.2.2 then and report if things don't work as expected
