### ISSUE TITLE
Error when applying Inventory.plot using "local" projection

### ISSUE THREAD

**Issue by chrisweird7** [obspy/obspy#2787]
There is an error when I using Inventory.plot to draw distribution of stations, and I don't know how to deal with it.
When I use method='cartopy', the code is like this:
`inv = obspy.read_inventory()`
`inv.plot(projection='local', size=50, method='cartopy')`

The program can run properly.
But when I use basemap, the code is like this:
`inv.plot(projection='local', size=50)`

It lead to error information like:
`File "D:\Anaconda3\envs\obspy\lib\site-packages\pyproj\transformer.py", line 495, in transform
    errcheck=errcheck,
  File "pyproj/_transformer.pyx", line 477, in pyproj._transformer._Transformer._transform
pyproj.exceptions.ProjError: x, y, z, and time must be same size`

I'm sure I have installed basemap properly, and I can us events_plot with the code like this:
`cata = obspy.read_events()`
`cata.plot(projection='local')`

It runs well. So I can't find what is going wrong with my Inventory.plot.
My Python version is 3.6.12, obspy is 1.2.2, basemap is 1.2.1, this is my first question using GitHub for now and I truly hope someone can help me.

**Comment by trichter** [comment]
I don't know the solution to your problem. Maybe it is a bug in basemap?
basemap is not maintained anymore and support for basemap will probably be dropped in the next mayor release of obspy. Can you switch your workflow to cartopy?

**Comment by chrisweird7** [comment]
@trichter Thanks, I'll use cartopy instead.
