### ISSUE TITLE
Plotting SEGY files

### ISSUE THREAD

**Issue by trac2github** [obspy/obspy#279]
Hi,

I am having trouble plotting the SEGY files.  When I plot my traces, it only plots one of the traces.  Is there a way to plot all of my traces as subplots and save all of them to one output file?  

Also, when I write my data to an output file it only gives one trace as well.  I would like to be able to go through all of my traces and read and write data from them.  

Any suggestions?

**Comment by payal-verma** [comment]
> [anonymous] All of my traces are already in one stream, There is only one SEGY file that I am reading with 390 traces. Therefore, shouldn't all of my traces already be in one stream?
> 
> When I use st.plot(), it only plots one trace. Then I used a for loop to loop through each trace which worked and I was able to plot each trace, each was a different picture. I thought there was a way to plot each so they were subplots and they would show up in one file?
> 
> I was able to write each trace using a for loop.
> 
> Thanks.

Can you send me the for loop to go through each trace? Thank you.
