### ISSUE TITLE
Wrong Stats after using read() and Stream.append(tr)

### ISSUE THREAD

**Issue by PeterMakus** [obspy/obspy#2790]
I randomly encountered what seems to be a little weird bug to me:

When doing the following: 
```python
from obspy import read, UTCDateTime
from obspy.clients.fdsn import Client

# Create a Stream, so we can append files later
st = read()

# Get some trace, it really does not matter, how I obtain it (here I just download it for arguments sake)
# Neither does the network nor station matter
c = Client("Iris")
start = UTCDateTime('2015-08-01')
end = start + 320
tr = c.get_waveforms(network='IU', station='HRV', location='*', channel='*', starttime=start, endtime=end)[0]

# Append the data to our empty Stream
st.append(tr)

# Now, we check the stats of the data
print(st[0].stats)
```

Weirdly enough, this returns the following:
```
         network: BW
         station: RJOB
        location: 
         channel: EHZ
       starttime: 2009-08-24T00:20:03.000000Z
         endtime: 2009-08-24T00:20:32.990000Z
   sampling_rate: 100.0
           delta: 0.01
            npts: 3000
           calib: 1.0
    back_azimuth: 100.0
     inclination: 30.0
        response: Channel Response
	From M/S (Velocity in Meters Per Second) to COUNTS (Digital Counts)
	Overall Sensitivity: 2.5168e+09 defined at 0.020 Hz
	4 stages:
		Stage 1: PolesZerosResponseStage from M/S to V, gain: 1500
		Stage 2: CoefficientsTypeResponseStage from V to COUNTS, gain: 1.67785e+06
		Stage 3: FIRResponseStage from COUNTS to COUNTS, gain: 1
		Stage 4: FIRResponseStage from COUNTS to COUNTS, gain: 1 RJOB
```
Now if I write the data to disk using `st.write('wherever')` and read it again using `read()`, I get the correct stats file instead of the one from *BW.RJOB*.

I am on **Python3.8.6** and **Ubuntu20.10** and use **obspy1.2.2** over an **anaconda** environment.

I know that the use-case above might seem a little fabricated and the problem can be circumvented very easily, but it seems nonetheless like something that should perhaps be fixed.
Thanks for maintaining and improving this awesome project!

**Comment by trichter** [comment]
Can you check your code again? `st ` is defined as tuple and `AttributeError: 'tuple' object has no attribute 'append'`.

**Comment by PeterMakus** [comment]
Sorry, I edited it now. Didn't actually run this before as it was just meant to illustrate the issue.

**Comment by trichter** [comment]
`read()` without any filename loads an example stream consisting of 3 traces. When you append one trace, the stream should consist of 4 traces. You then show the contents of the first trace. Nothing unexpected until know. Please check `print(st)`. To get an empty stream use `st = Stream()`.

**Comment by PeterMakus** [comment]
Right, thanks I was not aware that `read()` was not a valid way to create an empty stream. I will close the issue (as there is in fact none)
