### ISSUE TITLE
Update website copyright to 2021

### ISSUE THREAD

**Issue by willschlitzer** [obspy/obspy#2791]
The copyright on the website currently reads 2008-2020, but it looks like there have been updates in the current year. I wasn't able to find the copyright information in the repo, so I'm sorry that this isn't a PR with the fix.

**Comment by barsch** [comment]
which page exactly?

**Comment by willschlitzer** [comment]
I'm seeing it on the footer for the home page of https://docs.obspy.org/

**Comment by barsch** [comment]
ah - docs building is currently broken and we (mainly @heavelock) are working on it - will be automatically updated as soon as docs builder is working again.
