### ISSUE TITLE
Reading SEG-Y rev2

### ISSUE THREAD

**Issue by dbpodrasky** [obspy/obspy#2798]
obspy.io.seg2.seg2._is_seg2()

python 2.7 or 3.x, obspy 1.1.0

_is_seg2() is used to decide if the input file is in SEG-Y rev2 format. This is done by attempting to read the SEG-Y revision number from the (optional) tape label, prepended to the textual header. The tape label is rarely, and certainly not universally, populated. This is not the correct place to attempt to read the revision number from. Instead the revision number should be read from the binary header, byte 3501.

It's understood that checking for the existence of the optional tape label is good practice, but the reader should not fail in the case that these optional bytes are not in the file. In this instance, the reader should next check the value of byte 3501 and proceed accordingly.

**Comment by ThomasLecocq** [comment]
I think you know much more this format & its requirements than all the ObsPy devs combined!  Please help & submit a PR with your suggestion codes!

**Comment by barsch** [comment]
obspy.io.seg2 == SEG-2 format (http://www.seg.org/documents/10161/77915/seg_2.pdf)

while 

obspy.io.segy == SEG-Y rev1 format (https://seg.org/Portals/0/SEG/News%20and%20Resources/Technical%20Standards/seg_y_rev1.pdf)

SEG-Y rev2 is not supported atm, or?

**Comment by dbpodrasky** [comment]
Fair enough. Will do.

**Comment by dbpodrasky** [comment]
The link for SEG-Y rev2 seems a bit dated. Check the following:

https://seg.org/Portals/0/SEG/News%20and%20Resources/Technical%20Standards/seg_y_rev2_0-mar2017.pdf <https://seg.org/Portals/0/SEG/News%20and%20Resources/Technical%20Standards/seg_y_rev2_0-mar2017.pdf>

**Comment by barsch** [comment]
again IMHO obspy.io.seg2 is not SEG-Y revision 2 - its stated in https://github.com/obspy/obspy/blob/master/obspy/io/seg2/seg2.py:

Pullan, S. (1990), Recommended standard for seismic (/radar) data files in the personal computer environment, Geophysics, 55 (9), 1260-1271. https://dx.doi.org/10.1190/1.1442942

**Comment by barsch** [comment]
but maybe @krischer can give some insight - he wrote the module

**Comment by dbpodrasky** [comment]
Oh, I see what you mean. In that case what is SEG-2?

**Comment by barsch** [comment]
Pullan, S. (1990), Recommended standard for seismic (/radar) data files in the personal computer environment, Geophysics, 55 (9), 1260-1271. https://dx.doi.org/10.1190/1.1442942

http://www.seg.org/documents/10161/77915/seg_2.pdf

**Comment by dbpodrasky** [comment]
I've never used, and don't know anyone who uses, SEG-2, so I can't help with that.

I can write a SEG-Y rev2 reader, but would need some help aligning this with the stream workflow used by obspy.

**Comment by krischer** [comment]
Yea - SEG-2 is a different format than SEG-Y. There is also SEG-1 and SEG-D and a bunch of others but ObsPy does not currently support these.

ObsPy currently supports SEG-Y rev 1 - support for rev 2 would be greatly appreciated.

Another possibility would be to write a bridge between ObsPy and segyio: https://github.com/equinor/segyio 
segyio is a pretty widely used library to read SEG-Y data and definitely seems more maintenance than the `obspy.io.segy` module.

**Comment by barsch** [comment]
SEG-2 is just a predecessor version of SEG-Y - there is actually also SEG-1 and there are conversion programs between all those formats. Anyway ```obspy.io.seg2``` is the wrong module to work on.

For writing an SEG-Y rev2 reading - it depends how fundamental the changes are between revision 1 and 2 - if you think its only small things than I would try to extend ```obspy.io.segy```.

**Comment by dbpodrasky** [comment]
Thanks, Lion. In which class/module should a SEG-Y rev2 reader go?

**Comment by dbpodrasky** [comment]
Yes, I did get quite confused by SEG-2 vs SEG-Y rev2. I appreciate the patient clarification!

I work with DAS (distributed acoustic sensing), so SEG-Y rev2 would be a big improvement. I will look into a PR on obspy.io.segy.

**Comment by krischer** [comment]
I agree with @barsch here - its best place likely is `obspy.io.segy` - `segyio` actually does not really distinguish between the versions as far as I know and it works for all revisions. Maybe something similar is possible here.

If this is a lot of work I still think it is worthwhile to look into converting `obspy.io.segy` into a bridge to `segyio`.

**Comment by ThomasLecocq** [comment]
Wooow using segY (or any of the SEG family formats) for DAS seem really a bad idea, certainly if traces have textual headers etc etc.... That duplicates soooo many informations.

**Comment by dbpodrasky** [comment]
Good or bad, it is standard practice to deliver DAS in SEG-Y. Extended textual file headers are optional and not commonly used with DAS datasets. Trace headers can be redundant, but 240 bytes per trace is not significant in light of the size of high-frequency DAS traces (30 seconds, recording at 1 kHz, encoded as IEEE-64-bit floats is 48,000 bytes!)

**Comment by dbpodrasky** [comment]
whoops! 480,000 bytes.

**Comment by megies** [comment]
stale, closing
