### ISSUE TITLE
Question: is C++ supported in the build system of obspy?

### ISSUE THREAD

**Issue by luca-s** [obspy/obspy#2800]
Dear developers,

I am evaluating the idea of providing a couple of PRs, but parts of the code is written in C++. Obviously I need to create a C wrapper around the C++ code to allow the binding to Python. However I don't know if C++ is supported when building the native code for obspy. Could you please clarify this point?

thank you 
Luca

**Comment by ThomasLecocq** [comment]
I _think_ no components of the obspy library is C++ now. I don't know if that would be a problem for the build systems etc... 

About the wrapper, you can wrap the C++ directly in python using the ``ctypes.CDLL`` : for exemple I do it here:

- cpp extension: https://github.com/ThomasLecocq/msnoise-tomo/blob/19f46d936fe64a5a59ebe5458f58f0cc80702e2a/src/libfta.cpp
- python binding: https://github.com/ThomasLecocq/msnoise-tomo/blob/19f46d936fe64a5a59ebe5458f58f0cc80702e2a/msnoise_tomo/lib/libvg_fta.py
- setup.py for building the cpp: https://github.com/ThomasLecocq/msnoise-tomo/blob/19f46d936fe64a5a59ebe5458f58f0cc80702e2a/setup.py#L140-L156

tom

**Comment by megies** [comment]
I think before anything else, it would be good to hear about what these proposed PRs would be doing roughly, because if it is out of scope for obspy then there is no need to even think about if it would fit the build system.

closing for now, feel free to reopen
