### ISSUE TITLE
`kind` arguments not working when plotting events from quakeml files?

### ISSUE THREAD

**Issue by nukenine** [obspy/obspy#2807]
Obspy version `1.2.2`
Python version `3.6` (also tried on `3.7`)

I downloaded [THIS quakeml file](https://earthquake.usgs.gov/archive/product/phase-data/us7000cc4d/us/1611440737040/quakeml.xml) from the USGS, in an attempt to make plots similar to the maps and radiation pattern plots [HERE](https://docs.obspy.org/master/packages/autogen/obspy.core.event.event.Event.plot.html). However, even when I explicitly write a `beachball` or `p_sphere` plot it will only plot the same projected map. How can I get similar plots to the obspy documentation? Thanks!

```
from obspy import read_events

qml=read_events(/path/to/qml)
qml.plot(kind='local')
```

Will show this projection and not local:
![Figure_1](https://user-images.githubusercontent.com/51235857/110559299-f2a10c80-8111-11eb-815b-2d3d3a3cfbfa.png)

Additionally, when I attempt to explicitly plot the beachball and radiation patterns it will show only show the same plot:

`qml.plot(kind=[['ortho', 'beachball'], ['p_sphere', 's_sphere']])`

I get similar results when I read the generic quakeml file from obspy with:

```
test=read_events()
test.plot(kind=[['ortho', 'beachball'], ['p_sphere', 's_sphere']])
```

**Comment by trichter** [comment]
Answered in discourse forum.
