### ISSUE TITLE
signal->polarization: incorrect timestamp of window

### ISSUE THREAD

**Issue by cweidle** [obspy/obspy#2811]
The timestamp assigned to the time windows in polarization analysis is imho incorrect.

polarization.py presently:
```
540             # we plot against the centre of the sliding window
541             if method.lower() == "pm":
542                 azimuth, incidence, error_az, error_inc = \
543                     particle_motion_odr(data, var_noise)
544                 res.append(np.array([newstart.timestamp + float(nstep) / fs,
545                            azimuth, incidence, error_az, error_inc]))
546             if method.lower() == "flinn":
547                 azimuth, incidence, reclin, plan = flinn(data, var_noise)
548                 res.append(np.array([newstart.timestamp + float(nstep) / fs,
549                                     azimuth, incidence, reclin, plan]))
```

plotting against the centre of the sliding window (comment in line 540) makes full sense 
but then lines 544 and 548 should be:
```
                     res.append(np.array([newstart.timestamp + float(nsamp) / 2 / fs,
```

### Why?
- `nsamp` is no of samples of sliding window
- `nstep` is no of samples to shift window from one timestamp to the next

if `win_frac = 0.5` (fraction of sliding window), the original version is correct.
else the timestamp will not be the center of the current timewindow but the starttime of the next timewindow.

### Example 
with `win_len = 0.3` and `win_frac = 0.1`
- original: polarization signal is shifted to earlier times than signal peak in waveform (P-pol pick is not central)
![polarization original](https://github.com/cweidle/tmpimages/raw/main/syndata_BAZ_045_INC_90_pol_BUG.png)

- fixed: polarization signal is centered around P-pol pick
![polarization fixed](https://github.com/cweidle/tmpimages/raw/main/syndata_BAZ_045_INC_90_pol.png)

**Comment by megies** [comment]
@cweidle or anybody else, happen to have the above data lying around still or have some other good example data + code to reproduce this? would help to save time trying to set up a case to check / work on this

**Comment by cweidle** [comment]
sure, the example above is a tapered cosine wavelet on the L-component of a LQT-system (Q,T zero), rotated to ZNE for a given incidence angle (90° horizontal) and azimuth (45°).
[syndata_BAZ_045_INC_90.mseed.zip](https://github.com/obspy/obspy/files/9871399/syndata_BAZ_045_INC_90.mseed.zip)

In the example above I added 0.6 * max.amplitude of random noise. Without noise the SVD in polarization_analysis fails.
hope this helps.

**Comment by megies** [comment]
@cweidle thanks again for reporting.. kinda embarrassing this took so long to get worked on
