### ISSUE TITLE
convert miniseed multıple files to sac files and merge them..I have a problem. please help me

### ISSUE THREAD

**Issue by sukranperk** [obspy/obspy#2819]
Hi all, 

I have multıple miniseed files. I want to convert them to sac files and merge then write into a folder. 
I must have year.day.00.00.0000.KO.stationname.HHZ.0.SAC file format 

My program is below but there is a problem about it.
This program gives only one sac file. :( How can ı do it? I am very new in obspy and python ! So maybe I make a obviously mistake.

from obspy import read

st = read('Desktop/2015/BAYB/HHZ.D/TU.BAYB..HHZ.D.2015.00*')
st.merge (method=0, fill_value=0 )
st.resample(10.0)
st.write('Desktop/obsdeneme/BAYB/2015.*.00.00.0000.KO.BAYB..HHZ.0.SAC', format="SAC")

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a [short, self contained, correct example](http://sscce.org/) that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)

**Comment by claudiodsf** [comment]
Hi @sukranperk, it seems normal to me that you get only one SAC file: the scope of `st.merge(method=0, fill_value=0)` is exactly this: to create a single trace where all the gaps have been filled with zeros.

Could you explain what would be your expected result?

**Comment by sukranperk** [comment]
I can explain it in more detail.

I have 365 day miniseed files (from TU.BAYB..HHZ.D.2015.001to TU.BAYB..HHZ.D.2015.365)

so ı want to convert them 365 sac fıles separately then I have to merge them 

I have to get 365 sac files whıch ı merged.  (it should be year.day.00.00.0000.KO.stationname.HHZ.0.SAC file format)  then I have to write it to 365 files separately.

How can I do that. My previous program gives only 1 sac file :((

**Comment by sukranperk** [comment]
> Hi @sukranperk, it seems normal to me that you get only one SAC file: the scope of `st.merge(method=0, fill_value=0)` is exactly this: to create a single trace where all the gaps have been filled with zeros.
> 
> Could you explain what would be your expected result?

I can explain it in more detail.

I have 365 day miniseed files (from TU.BAYB..HHZ.D.2015.001to TU.BAYB..HHZ.D.2015.365)

so ı want to convert them 365 sac fıles separately then I have to merge them

I have to get 365 sac files whıch ı merged. (it should be year.day.00.00.0000.KO.stationname.HHZ.0.SAC file format) then I have to write it to 365 files separately.

How can I do that. My previous program gives only 1 sac file :((

**Comment by claudiodsf** [comment]
Ok, so what you want to do is the following:

```python
from obspy import read
from glob import glob
import os

for mseedfile in glob('Desktop/2015/BAYB/HHZ.D/TU.BAYB..HHZ.D.2015.???'):
  st = read(mseedfile)
  st.merge (method=0, fill_value=0 )
  st.resample(10.0)
  outfile = os.path.basename(mseedfile) + '.SAC'
  outfile = os.path.join('Desktop/obsdeneme/BAYB', outfile)
  st.write(outfile, format='SAC')
```

What I'm doing here is to process each day separately and do a `st.merge()` on each file to remove gaps before writing the SAC files.

**Comment by sukranperk** [comment]
> Ok, so what you want to do is the following:
> 
> ```python
> from obspy import read
> from glob import glob
> import os
> 
> for mseedfile in glob('Desktop/2015/BAYB/HHZ.D/TU.BAYB..HHZ.D.2015.???'):
>   st = read(mseedfile)
>   st.merge(method=0, fill_value=0)
>   st.resample(10.0)
>   outfile = os.path.basename(mseedfile) + '.SAC'
>   outfile = os.path.join('Desktop/obsdeneme/BAYB', outfile)
>   st.write(outfile, format='SAC')
> ```
> 
> What I'm doing here is to process each day separately and do a `st.merge()` on each file to remove gaps before writing the SAC files.

thank you so much. This is what ı want :) I am very new in obspy and python so ı have to improve my obspy skills :) thank you again

**Comment by claudiodsf** [comment]
You're welcome 😉 

In the future please consider using the [ObsPy Forum](https://discourse.obspy.org) or our [Gitter Chat](https://gitter.im/obspy/obspy) to ask questions.
