### ISSUE TITLE
client.get_stations problem combining _US-TA and other networks

### ISSUE THREAD

**Issue by Keowne** [obspy/obspy#2825]
Hi, 

I'm finding an issue with downloading inventory information when combining the _US-TA network, with another network in the request. For example, I can get inventory info from _US-TA as follows (ObsPy version 1.2.2 on OSX, with an Anaconda installation):

```python
from obspy import UTCDateTime
from obspy.clients.fdsn import Client
client = Client('IRIS')
t0 = UTCDateTime("2017-01-31T00:00:00.000")
inventory = client.get_stations(network="_US-TA", sta="*", loc="*", channel="BDF", starttime=t0, endtime=t0+10, level="response")

In [2]: inventory.get_contents()['networks']
Out[2]: ['AK', 'II', 'TA']
```

And IM network inventory information for the same time period:
```python
inventory = client.get_stations(network="IM", sta="*", loc="*", channel="BDF", starttime=t0, endtime=t0+10, level="response")

In [4]: inventory.get_contents()['networks']
Out[4]: ['IM']
```

However, the networks cannot be combined together. I.e., the following only gives results for the _US-TA network, not the IM network: 

```python
inventory = client.get_stations(network="_US-TA,IM", sta="*", loc="*", channel="BDF", starttime=t0, endtime=t0+10, level="response")

In [6]: inventory.get_contents()['networks']
Out[6]: ['AK', 'II', 'TA']
```
The issue seems very _US-TA (and _US-TA-ADOPTED) specific, as I can combine other networks just fine, e.g.:

```python
inventory = client.get_stations(network="AV,IM", sta="*", loc="*", channel="BDF", starttime=t0, endtime=t0+10, level="response")

In [8]: inventory.get_contents()['networks']
Out[8]: ['AV', 'IM']
```
In years gone by with prior ObsPy versions, I was certainly able to combine the _US-TA network with other networks. I'm thinking ObsPy ~1.0.x, and maybe 1.1.0. However, testing with those package versions now produces the same problem. So maybe the issue is on the IRIS end? Or am I overlooking something super obvious? I wasn't able to find any references to this problem here or on the discourse site.

Thanks for any suggestions!

**Comment by barsch** [comment]
This has to be an IRIS problem - especially after testing with the older version of ObsPy

You can test your queries directly using the instructions at https://service.iris.edu/fdsnws/station/1/ - e.g. for your third query (network=_US-TA,IM):

https://service.iris.edu/fdsnws/station/1/query?network=_US-TA,IM&level=response&channel=BDF&starttime=2017-01-31T00:00:00.000&endtime=2017-01-31T00:00:10.000

results into
```
<FDSNStationXML xsi:schemaLocation="http://www.fdsn.org/xml/station/1 http://www.fdsn.org/xml/station/fdsn-station-1.1.xsd" schemaVersion="1.1">
  <Source>IRIS-DMC</Source>
  <Sender>IRIS-DMC</Sender>
  <Module>IRIS WEB SERVICE: fdsnws-station | version: 1.1.47</Module>
  <ModuleURI>http://service.iris.edu/fdsnws/station/1/query?network=IM,_US-TA&level=response&channel=BDF&starttime=2017-01-31T00:00:00.000&endtime=2017-01-31T00:00:10.000  </ModuleURI>
  <Created>2021-04-04T05:04:13</Created>
  <Network code="AK" startDate="1987-01-01T00:00:00" restrictedStatus="open">...</Network>
  <Network code="II" startDate="1986-01-01T00:00:00" restrictedStatus="open">...</Network>
  <Network code="TA" startDate="2003-01-01T00:00:00" restrictedStatus="open">...</Network>
</FDSNStationXML>
```

querying for ```IM``` only:

https://service.iris.edu/fdsnws/station/1/query?network=IM&level=response&channel=BDF&starttime=2017-01-31T00:00:00.000&endtime=2017-01-31T00:00:10.000

```
<FDSNStationXML xsi:schemaLocation="http://www.fdsn.org/xml/station/1 http://www.fdsn.org/xml/station/fdsn-station-1.1.xsd" schemaVersion="1.1">
  <Source>IRIS-DMC</Source>
  <Sender>IRIS-DMC</Sender>
  <Module>IRIS WEB SERVICE: fdsnws-station | version: 1.1.47</Module>
  <ModuleURI>http://service.iris.edu/fdsnws/station/1/query?network=IM&level=response&channel=BDFstarttime=2017-01-31T00:00:00.000&endtime=2017-01-31T00:00:10.000</ModuleURI>
  <Created>2021-04-04T05:06:18</Created>
  <Network code="IM" startDate="1965-01-01T00:00:00" restrictedStatus="open">...</Network>
</FDSNStationXML>
```

querying network ```_US-TA``` only

https://service.iris.edu/fdsnws/station/1/query?network=_US-TA&level=response&channel=BDF&starttime=2017-01-31T00:00:00.000&endtime=2017-01-31T00:00:10.000

```
...
<Network code="AK" startDate="1987-01-01T00:00:00" restrictedStatus="open">...</Network>
<Network code="II" startDate="1986-01-01T00:00:00" restrictedStatus="open">...</Network>
<Network code="TA" startDate="2003-01-01T00:00:00" restrictedStatus="open">...</Network>
...
```

but mitigating the problem by manually querying all networks ```IM,AK,TA,II``` seems to work

https://service.iris.edu/fdsnws/station/1/query?network=IM,AK,TA,II&level=response&channel=BDF&starttime=2017-01-31T00:00:00.000&endtime=2017-01-31T00:00:10.000

```
...
<Network code="AK" startDate="1987-01-01T00:00:00" restrictedStatus="open">...</Network>
<Network code="II" startDate="1986-01-01T00:00:00" restrictedStatus="open">...</Network>
<Network code="IM" startDate="1965-01-01T00:00:00" restrictedStatus="open">...</Network>
<Network code="TA" startDate="2003-01-01T00:00:00" restrictedStatus="open">...</Network>
...
```

So you may want to contact IRIS (see contact info at the bottom of https://service.iris.edu/fdsnws/station/1/) to figure out what is going on ...
