### ISSUE TITLE
Missing Information in NLLOC .obs file

### ISSUE THREAD

**Issue by JeldrikGaal** [obspy/obspy#2831]
- ObsPy version 1.2.2 Python version 2.7 and Platform Linux
- How did you install ObsPy: pip

When writing an event to an .obs file from NonLinLoc the field for the amplitude gets left empty even if the event has the amplitude values.

According to http://alomax.free.fr/nlloc/soft7.00/formats.html#_phase_nlloc_ the third last field is supposed to be:
Amplitude (expFloat*9.2)
    Maxumim peak-to-peak amplitude 

Meanwhile in the Code it just gets ignored: 
Code from: obspy/io/nlloc/core.py line 421 - 423
`info_ = fmt % (station.ljust(6), "?".ljust(4), component.ljust(4),
                       onset.ljust(1), phase_type.ljust(6), polarity.ljust(1),
                       date, hourminute, seconds, time_error, -1, -1, -1)
`

**Comment by megies** [comment]
Hmm, amplitude can come in all kinds of units though (raw counts, m/s, mm/s, ...?).. not sure, we might be doing more harm than good writing out amplitudes

**Comment by megies** [comment]
I'm closing this for now. If anybody wants to come forward with opinions how to do this, speak up. I just see too much ambiguity, writing amplitudes out, they could be in any kinds of units and might just cause confusion.

Maybe conditionally writing them if requested by user could be an idea. PRs welcome!
