### ISSUE TITLE
Way to retrieve .sgy files with obspy

### ISSUE THREAD

**Issue by StefanBloemheuvel** [obspy/obspy#2840]
Hi,

There is code from a project (from somebody on github) that i am trying to run, containing a lot of .sgy earthquake files.
However, i would like to download some .sgy of earthquakes from other stations as well myself.
I could not find a direct way to access those files with obspy, is there a way to retrieve those?

Kind regards,

Stefan

**Comment by d-chambers** [comment]
The docs have a good example: https://docs.obspy.org/packages/autogen/obspy.clients.fdsn.mass_downloader.html

In the future, please use the [obspy gitter](https://gitter.im/obspy/obspy) or the [obspy discourse](https://discourse.obspy.org/c/usage-questions/6) for usage questions. Github is for development purposes (reporting bugs, proposing features, etc.)
