### ISSUE TITLE
Meaning of channel codes

### ISSUE THREAD

**Issue by StefanBloemheuvel** [obspy/obspy#2841]
Hi,

I have a hard time trying to figure out what the meaning of the channels are in obspy when downloading waveforms.
The documentation provides the following information:

```
:type channel: str
:param channel: Select one or more SEED channel codes. Multiple codes
            are comma-separated (e.g. ``"BHZ,HHZ"``).
```

Is there an overview of what each channel does, and also when you should use specific channels over others?
For example, the network "CI"  (Southern California Seismic Network) returns data when asking for the channels "BH*", which i assume means all the channels beginning with BH. It then returns 3 channels which i think mean the X, Y, and Z. But what does BH mean? and why does it not return data when I am asking the same query to the network NX (Nanometrics Research Network)? 

Kind regards and thanks in advance!

Stefan

**Comment by d-chambers** [comment]
Hi @StefanBloemheuvel,

Here is an explanation of the seed channel naming: https://ds.iris.edu/ds/nodes/dmc/data/formats/seed-channel-naming/. There should be links to other documentation if you need additional information. 

Same comment as before though, please use the other channels (gitter/discourse) for questions not related to obspy development.
