### ISSUE TITLE
Consider adding a CSS/KBCore waveform writer plugin

### ISSUE THREAD

**Issue by jkmacc-LANL** [obspy/obspy#2843]
Following a question on the [forum](https://discourse.obspy.org/t/converting-reftek130-files-to-css-3-0-data-format/1241/3), where it was noted that a CSS waveform writer plugin doesn't seem to exist, but could be useful.  

> I think the reason one doesn't already exist may be that CSS wants to know things like the directory, file name, byte offset, and dtype of the waveform you're writing, some of which can be decided by the user at write-time.  This makes it slightly difficult for the waveform writing plug-in to manage, as it depends on external user code.  Since the user is writing external code anyway, it's not much more to ask that they just write the CSS table themselves.  With reasonable defaults, though, a waveform writer plugin for CSS should be possible.

We'd probably have assume a directory structure (or provides a template for one) and an on-disk format, but I think a CSS/KBCore plugin is doable.

**Comment by megies** [comment]
Closing for now to get number of open issues down. If anybody wants to implement a writer routine, go for it!
