### ISSUE TITLE
Telephones in Operator have too rigid a format.

### ISSUE THREAD

**Issue by larean** [obspy/obspy#2844]
ObsPy 1,2,2 Ubuntu 18.04.5 LTS installed with pip

Telephone field in Class Operator must have a very rigid format conceived for American phones:  "xxx-xxxx". While the number of digits is variable, this does not comply with most European formats. For example, in France a telephone might typically be "+33 (0)1 79 62 31 48". Area codes do not really exist (not used for dialing, as numbers are always dialed in full). Is it possible to simply accept any string or generalize the regular expressión to include parentheses, an optional initial plus sign and spaces?

Here is the traceback:

```

>  Traceback (most recent call last):
>   File "/home/arean/.local/bin/obsinfo-makeSTATIONXML", line 33, in <module>
>     sys.exit(load_entry_point('obsinfo==0.109', 'console_scripts', 'obsinfo-makeSTATIONXML')())
>   File "/home/arean/.local/lib/python3.6/site-packages/obsinfo/main/makeStationXML.py", line 48, in main
>     obj = Network(ObsMetadata(net_dict))
>   File "/home/arean/.local/lib/python3.6/site-packages/obsinfo/network/network.py", line 53, in __init__
>     self.obspy_network = self.to_obspy()     
>   File "/home/arean/.local/lib/python3.6/site-packages/obsinfo/network/network.py", line 70, in to_obspy
>     phones = [PhoneNumber(0, self.facility.phone_number)] if self.facility.phone_number else []
>   File "/home/arean/.local/lib/python3.6/site-packages/obspy/core/inventory/util.py", line 593, in __init__
>     self.phone_number = phone_number
>   File "/home/arean/.local/lib/python3.6/site-packages/obspy/core/inventory/util.py", line 604, in phone_number
>     raise ValueError(msg)
> ValueError: phone_number needs to match the pattern '[0-9]+-[0-9]+'


```

Input was: "33 2345-3485"

**Comment by scifi6546** [comment]
I agree that the phone number regex is far to strict because it does not allow valid US phone numbers for example (907) 123-4567. Maybe a better check is to make sure that the phone number only consists of numbers, and the characters `( )-`?

**Comment by scifi6546** [comment]
I think the following regex expression may work better, `(\(?)[0-9]+(\)?)+` It matches for groups of numbers optionally surrounded by parenthesis

**Comment by barsch** [comment]
```PhoneNumber``` class has the attributes ```area_code```, ```phone_number``` and ```country_code``` according to the StationXML standard, see
https://docs.obspy.org/packages/autogen/obspy.core.inventory.util.PhoneNumber.html
and StationXML specs:
http://docs.fdsn.org/projects/stationxml/en/latest/reference.html

**Comment by larean** [comment]
I beg to disagree with @barsch.  The FDSN standard does not include a dash for the phone number, it's a free form string.

Area codes should not be required as they are US centric, but you're right it's not an obspy issue. I will raise that point with FDSN itself. In the meantime, a free-form number without area code should be allowed in obspy, as the dash is NOT part of the standard.

Please allow spaces, dashes, parentheses and the plus sign, used in many countries to indicate country code.

**Comment by barsch** [comment]
the relevant part of the standard is not the documentation but the actual implementation as XML schema (XSD):

https://github.com/FDSN/StationXML/blob/master/fdsn-station.xsd#L890
```
<xs:element name="Phone" type="fsx:PhoneNumberType" minOccurs="0" maxOccurs="unbounded" />
```

https://github.com/FDSN/StationXML/blob/master/fdsn-station.xsd#L952-L965
```
<xs:complexType name="PhoneNumberType">
  <xs:sequence>
    <xs:element name="CountryCode" type="xs:integer" minOccurs="0"/>
    <xs:element name="AreaCode" type="xs:integer"/>
    <xs:element name="PhoneNumber">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="[0-9]+-[0-9]+"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:element>
  </xs:sequence>
  <xs:attribute name="description" type="xs:string" use="optional"/>
</xs:complexType>
```

here you can see that the ```PhoneNumber``` requires actually a dash but no spaces, or?

**Comment by barsch** [comment]
btw dashes, parentheses and a leading plus are not really relevant in order to store a international telephone number (read: a full telefon number starting with a country code) - so I'm actually confused why the dash in the last part is required at all ...

anyway its the standard we just implemented - if you want to change it you have to go via FDSN

**Comment by larean** [comment]
OK, thanks
