### ISSUE TITLE
NORDIC write of pick with 0. seconds leaves second field empty

### ISSUE THREAD

**Issue by WayneCrawford** [obspy/obspy#2848]
when writing out to a NORDIC file, obspy will output blanks when the seconds=0.  This is not standard NORDIC format and will not be read by obspy itself.

Here is a code that illustrates the point, using the attached file:

```python
from obspy.core.event import read_events
cat = read_events('nordic.txt', format='NORDIC')
cat.write('nordic2.txt', format='NORDIC')
cat = read_events('nordic2.txt', format='NORDIC')
```

The input file looks like:
```
 2019 10 7 2015 51.8 L -12.886  45.426 35.0  MAY 16 1.8 0.1LMAY                1
 GAP=145        2.33      19.4    12.6 21.4 -0.4136E+02 -0.5078E+02  0.6187E+02E
 2019-10-07-2015-42M.MAYOB_076                                                 6
 STAT SP IPHASW D HRMM SECON CODA AMPLIT PERI AZIMU VELO AIN AR TRES W  DIS CAZ7
 KNKL HZ  Pg  2A  2016 0.000                             126   -0.67 5 35.8 257 
 KNKL HN  Sg  3A  2016 3.670                             126   -2.73 2 35.8 257 
 KNKL HZ  IAML A  2016 5.470         9.3 0.05                          35.8 257 
```

and the output file:
```
 2019 10 7 2015 51.8 L -12.886  45.426 35.0  MAY  1 1.8 0.1LMAY                1
 Action:ARG 21-06-17 15:19 OP:OBSP STATUS:               ID:20191007201551     I
 DUMMY                                                                         6
 STAT SP IPHASW D HRMM SECON CODA AMPLIT PERI AZIMU VELO AIN AR TRES W  DIS CAZ7
 KNKL HZ  Pg  2A  2016                                   126   -0.67   35.8 257 
 KNKL HN  Sg  3A  2016 3.670                             126   -2.73   35.8 257 
 KNKL HZ  IAML A  2016 5.470         9.3 0.05                                   
```
`HZ IAML` also loses its `DIS` and `CAZ7` values, I don't know if this is important but at least it doesn't block reading.

  -  ObsPy version = 1.22
  - Python version=3.8.10
  - Platform = OSX
  -  ObsPy and Python installed using Anaconda

**Comment by WayneCrawford** [comment]
I suspect that the solution I proposed in #2749 would fix this, but that has been delayed so long that I can't get it to run any more on my machine.  So if someone wants to just implement the simplest part of what I did there (change `if not number` to `if number is None`), please do so.  The "problem" (from my point of view) with that is that the above code would change
```
 2019 10 7 2015 51.8 L -12.886  45.426 35.0  MAY 16 1.8 0.1LMAY                1
 GAP=145        2.33      19.4    12.6 21.4 -0.4136E+02 -0.5078E+02  0.6187E+02E
 2019-10-07-2015-42M.MAYOB_076                                                 6
 STAT SP IPHASW D HRMM SECON CODA AMPLIT PERI AZIMU VELO AIN AR TRES W  DIS CAZ7
 KNKL HZ  Pg  2A  2016 0.000                             126   -0.67 5 35.8 257 
 KNKL HN  Sg  3A  2016 3.670                             126   -2.73 2 35.8 257 
 KNKL HZ  IAML A  2016 5.470         9.3 0.05                          35.8 257 
```
to 
```
 2019 10 7 2015 51.8 L -12.886  45.426 35.0  MAY  1 1.8 0.1LMAY                1
 Action:ARG 21-06-17 15:19 OP:OBSP STATUS:               ID:20191007201551     I
 DUMMY                                                                         6
 STAT SP IPHASW D HRMM SECON CODA AMPLIT PERI AZIMU VELO AIN AR TRES W  DIS CAZ7
 KNKL HZ  Pg  2A  2016 0.000                             126   -0.67   35.8 257 
 KNKL HN  Sg  3A  2016 3.670                             126   -2.73   35.8 257 
 KNKL HZ  IAML0A  2016 5.470         9.3 0.05                                   
```
(see the added '0' on the last line?  I am against it because it could suggest to the user that the event was picked as best quality, whereas @calum-chamberlain is for it because a blank and a '0' are treated the same by the location codes).  So please do whichever (approve #2749 or make a new pull with the minimal change), but do one!

Regards
Wayne

**Comment by calum-chamberlain** [comment]
I think you are right that the solution in #2749 would fix the missing seconds. Sorry this slipped off my radar with such a gap between comments, and field work.

The missing CAZ and DIS may be fixed by #2814 but I'm a little lost about how far along that PR is.

**Comment by calum-chamberlain** [comment]
Hi @WayneCrawford - I have merged #2749 - can you test this bug using the maintenence_1.2.x branch please?

**Comment by WayneCrawford** [comment]
Honestly, I'm lost between the different branches and how to test one versus the other.  Could you explain to me how to do this?  Or just do it?

Thanks
Wayne

**Comment by calum-chamberlain** [comment]
The `0.00` seconds pick is fixed in maintenance_1.2.x

To make use of this branch you should:
1. Clone the obspy repository (if you haven't already);
2. `cd` into the obspy directory
3. fetch updates: `git fetch origin`
4. checkout the maintenance_1.2.x branch: `git checkout maintenance_1.2.x`
5. install that branch - I usually install in develop mode so that changing the branch changes the version found: `python setup.py develop` (you may to uninstall the version of obspy you have installed in your environment first.

The missing CAZ and DIS on the amplitude pick is not resolved elsewhere - this stems from amplitude picks not being associated with arrivals when read in - arrivals store this back azimuth and distance in QuakeML and obspy `Event` objects.

**Comment by calum-chamberlain** [comment]
I'm going to close this as the bug is resolved already in maintenance_1.2.x  Feel free to reopen if you feel this needs more.
