### ISSUE TITLE
No background For beachball!

### ISSUE THREAD

**Issue by NimaDolatabadi** [obspy/obspy#2853]
I'm trying to export beachballs as "svg" but the results have black background. I have even defined bgcolor but nothing is changed at all.
part of my code that does the job is:

```
for var in fichercsv:
            if i > 1:
                bb = beachball([float(var[1]), float(var[2]), float(var[3])],
                               size=500, linewidth=2, facecolor='b', edgecolor='k', format='svg', fig=None,
                               outfile=saveDir + '/' + str(var[0]))
                plt.close("all")
```
and the result is attached below. please help me fix this.
Regards
![2](https://user-images.githubusercontent.com/32169409/123526963-c0cbaa00-d6f0-11eb-8888-b7a0b1a61c63.png)

**Comment by barsch** [comment]
did you try ```bgcolor``` as documented here: https://docs.obspy.org/packages/autogen/obspy.imaging.beachball.beachball.html#obspy.imaging.beachball.beachball

**Comment by NimaDolatabadi** [comment]
Dear Barsch,
Last night while sleeping I just dreamt about the problem and found out that i have problem in importing libraries (LOL).
I was using `from obspy.imaging.mopad_wrapper import beachball` and even with defining `_bgcolor_` it gave me black background. so i have imported other library `from obspy.imaging.beachball import beachball` and it just completely did the job to my desire.
Thanks for your help
Regards
