### ISSUE TITLE
broken link in Vincenty documentation (404 not found)

### ISSUE THREAD

**Issue by wangliang1989** [obspy/obspy#2854]
https://docs.obspy.org/packages/autogen/obspy.geodetics.base.calc_vincenty_inverse.html

![image](https://user-images.githubusercontent.com/12059719/124139713-75cbe100-daba-11eb-9276-a3e35cd8b69c.png)

both 404

**Comment by mnky9800n** [comment]
where should the links actually point?

**Comment by wangliang1989** [comment]
not know

**Comment by wangliang1989** [comment]
I just want to find the content. I think you can find which one edited this.

**Comment by filefolder** [comment]
https://www.icsm.gov.au/publications/gda2020-technical-manual-v16

I would probably recommend just changing those links to this: https://www.icsm.gov.au/publications

**Comment by wangliang1989** [comment]
> https://www.icsm.gov.au/publications/gda2020-technical-manual-v16
> 
> I would probably recommend just changing those links to this: https://www.icsm.gov.au/publications

many stuff in the link

which one?

**Comment by filefolder** [comment]
https://www.icsm.gov.au/publications/gda2020-technical-manual-v16
