### ISSUE TITLE
nvhdr=7 ?

### ISSUE THREAD

**Issue by jwebster-LANL** [obspy/obspy#2859]
I am trying to save some data that has very accurate lat,lon information obtained from a differential gps system.  I need to preserve that accuracy in sac files, but when I do a normal st.write() the data gets changed after 4 decimal places or so (I need about 8 decimal places).

I'm guessing that what's happening is that the single precision default of the sac file is not enough to preserve the accuracy.

The [sac manual ](https://ds.iris.edu/files/sac-manual/sac_manual.pdf) (pg 18) addresses this. If you set NVHDR=7 (instead of the default 6), it will create a "footer" in the sac file that will can hold the necessary header values in double precision.

Is obspy currently setup to handle this?  If so, how? I scanned through the documentation and didn't see anything, but maybe I'm not looking in the right place.

**Comment by jkmacc-LANL** [comment]
I don't believe the SAC io module is set up for version 7 files.  I could try to help identify the changes needed to support versions >6, but I don't think they'd be trivial changes.

**Comment by jkmacc-LANL** [comment]
They for sure need to be SAC files?  If not, another option could be HDF5.

**Comment by jwebster-LANL** [comment]
I have a workaround for now, and I admit this is an edge case.  But maybe since this is something sac can do, it might be worth adding to obspy? Admittedly I have no idea how difficult it would be.

**Comment by jkmacc-LANL** [comment]
I could be wrong, and maybe it'd just be a few "if" clauses in the read/write routines.  I'm glad it's not a showstopper.  Maybe we should consider stating that only version 6 files are supported more prominently in the docs.  Closing, but feel free to re-open if we think version 7 support is worth it.
