### ISSUE TITLE
Neither Basemap nor Cartopy could be imported. Google Colab

### ISSUE THREAD

**Issue by Jordon-Chen** [obspy/obspy#2863]
**Description**
Hi, I ran into a problem when I used obspy to plot event map on the google colab platform.

**Version**
Ubuntu 18.04.5 LTS
python=3.7
obspy=1.2.2

**Reproduce**
[https://colab.research.google.com/drive/1e9-g_8DjGa6ryvC4qYp15ndtEbvwOmP-?usp=sharing](https://colab.research.google.com/drive/1e9-g_8DjGa6ryvC4qYp15ndtEbvwOmP-?usp=sharing)

**Traceback**
```
/usr/local/lib/python3.7/dist-packages/obspy/imaging/maps.py:66: UserWarning: Neither basemap nor cartopy installed, map plots will not work.
  warnings.warn(msg)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-0867c9f93335> in <module>()
      1 get_ipython().magic('matplotlib inline')
      2 import obspy
----> 3 fig = obspy.read_events().plot()

1 frames
/usr/local/lib/python3.7/dist-packages/obspy/imaging/maps.py in plot_map(method, *args, **kwargs)
    795             return plot_cartopy(*args, **kwargs)
    796         else:
--> 797             raise ImportError('Neither Basemap nor Cartopy could be imported.')
    798     elif method == 'basemap':
    799         if not HAS_BASEMAP:

ImportError: Neither Basemap nor Cartopy could be imported.
```

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a [short, self contained, correct example](http://sscce.org/) that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)

**Comment by calum-chamberlain** [comment]
Neither Basemap nor Cartopy is installed by default when installing ObsPy from pypi - check the list of optional dependencies [here](https://github.com/obspy/obspy/wiki/Dependencies) - you should just be able to `pip install cartopy` when you install obspy and carry on as you were. Although when I tried doing that in your notebook the kernel crashed.

**Comment by Jordon-Chen** [comment]
> Neither Basemap nor Cartopy is installed by default when installing ObsPy from pypi - check the list of optional dependencies [here](https://github.com/obspy/obspy/wiki/Dependencies) - you should just be able to `pip install cartopy` when you install obspy and carry on as you were. Although when I tried doing that in your notebook the kernel crashed.

Thanks for your reply. I also met this kernel crashed problem after running `pip install cartopy` .

**Comment by Jordon-Chen** [comment]
@calum-chamberlain Hi, I found a solution from the cartopy issue.
[https://github.com/SciTools/cartopy/issues/1788#issuecomment-842018805](https://github.com/SciTools/cartopy/issues/1788#issuecomment-842018805)

```
!apt-get install libproj-dev proj-data proj-bin
!apt-get install libgeos-dev
!pip install cython
!pip install cartopy
!apt-get -qq install python-cartopy python3-cartopy
!pip uninstall -y shapely # cartopy and shapely aren't friends (early 2020)
!pip install shapely --no-binary shapely
```
After doing the above block, the colab does not crash now.

Reproduce
[https://colab.research.google.com/drive/1c-eeyaMFYQqIQi_slK2PzplyeuzIIhlt?usp=sharing](https://colab.research.google.com/drive/1c-eeyaMFYQqIQi_slK2PzplyeuzIIhlt?usp=sharing)

**Comment by calum-chamberlain** [comment]
Thanks for digging into that and posting the issue and fix. I'm sure it will help someone else in the future.

I'm going to close this issue now as I think you solved it.

**Comment by Jordon-Chen** [comment]
I also found a solution from the stackoverflow to solve the **basemap** issue.
[https://stackoverflow.com/questions/54613992/how-to-install-and-use-basemap-on-google-colab](https://stackoverflow.com/questions/54613992/how-to-install-and-use-basemap-on-google-colab)

```
!apt-get install libgeos-3.5.0
!apt-get install libgeos-dev
!pip install https://github.com/matplotlib/basemap/archive/master.zip
# There is a problem with pyproj 2.0.1, so we need to downgrade it:
!pip install pyproj==1.9.6
```
After doing the above block, you can plot map with basemap library on the google colab now.

Reproduce
[https://colab.research.google.com/drive/1amfgwIn__iLa2n4sb648-1ZBjepjHS2F?usp=sharing](https://colab.research.google.com/drive/1amfgwIn__iLa2n4sb648-1ZBjepjHS2F?usp=sharing)
