### ISSUE TITLE
doctests error for obspy.signal.sosfilt - ideas ?

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#2865]
see this (in https://tests.obspy.org/114441/): 

looks like something changed upstream in scipy/numpy? 

```python
Traceback (most recent call last):
File "/usr/share/miniconda3/envs/test/lib/python3.8/doctest.py", line 2204, in runTest
raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for obspy.signal._sosfilt._zpk2sos
File "/home/runner/work/obspy/obspy/obspy/signal/_sosfilt.py", line 137, in _zpk2sos
----------------------------------------------------------------------
File "/home/runner/work/obspy/obspy/obspy/signal/_sosfilt.py", line 252, in obspy.signal._sosfilt._zpk2sos
Failed example:
sos[:, :3]
Expected:
array([[ 0.0014154 , 0.00248707, 0.0014154 ],
[ 1. , 0.72965193, 1. ],
[ 1. , 0.17594966, 1. ]])
Got:
array([[ 0.0014152 , 0.00248677, 0.0014152 ],
[ 1. , 0.72976874, 1. ],
[ 1. , 0.17607852, 1. ]])
----------------------------------------------------------------------
File "/home/runner/work/obspy/obspy/obspy/signal/_sosfilt.py", line 262, in obspy.signal._sosfilt._zpk2sos
Failed example:
sos[:, 3:]
Expected:
array([[ 1. , -1.32543251, 0.46989499],
[ 1. , -1.26117915, 0.6262586 ],
[ 1. , -1.25707217, 0.86199667]])
Got:
array([[ 1. , -1.32544025, 0.46989976],
[ 1. , -1.26118294, 0.62625924],
[ 1. , -1.2570723 , 0.8619958 ]])
```

any ideas ?

**Comment by ThomasLecocq** [comment]
The change occured between 
https://tests.obspy.org/114315/
and 
https://tests.obspy.org/114328/

the only difference in version for the main packages are:

scipy 1.6.3 --> 1.7.0
sqlalchemy 1.4.19 --> 1.4.20

**Comment by ThomasLecocq** [comment]
What I don't get is that the failing test is a backport of https://github.com/scipy/scipy/blob/1605c31af52afdf7feec22778476d4386d660acb/scipy/signal/filter_design.py#L1379-L1392 , which is exactly (still) the same...

**Comment by ThomasLecocq** [comment]
Aha, the doctests fail also for the scipy code !!

**Comment by trichter** [comment]
Most simple would be to skip this specific doctest.

**Comment by ThomasLecocq** [comment]
Nah, the scipy doctests also don't pass, so I'll PR the right values there and here, it doesn't change the shape of the resulting filter anyway.

**Comment by trichter** [comment]
Then, the doctest would fail for previous scipy versions. No big deal, but could be confusing for some users.

**Comment by ThomasLecocq** [comment]
closing as #2865 solves the issue for now
