### ISSUE TITLE
change .dat files to the miniSEED files

### ISSUE THREAD

**Issue by Abbas1192** [obspy/obspy#2873]
Hi 
I want to calculate time delay of arrival between several signals going through earth (the source is a vibration/drop test source). I have .dat files, if I want to read them in python, I will use the below code for several channels. For this type of file, how can I change it to the miniSEED files. Because I want to use miniSEED files in Geopsy software.

for i in range(0, num_channel):
fname = path+'/fifo' + str(i) + '.dat'
datatype = 'int16'
s = np.fromfile(fname, datatype)

**Comment by filefolder** [comment]
Hi, github is for issues with the software itself so I doubt anyone will answer you. For questions about how to use obspy I would recommend asking this question on the forum here: https://discourse.obspy.org/

Cheers

**Comment by ThomasLecocq** [comment]
this will help you: https://docs.obspy.org/tutorial/code_snippets/anything_to_miniseed.html

indeed please next time use discourse!
thomas
