### ISSUE TITLE
Could not access event's moment tensor (list index out of range)

### ISSUE THREAD

**Issue by Bhanuchander210** [obspy/obspy#2874]
### Environment

- Ubuntu 20.04.1 LTS
- Python 3.9.6
- obspy==1.2.2

### Installation
- pip install obspy

### Issue

When i am trying to plot an event using catalog like shown below code. 

```
client.get_events(endtime=end_time, starttime=start_time)
event = cat.events[0]
event.plot(outfile="event.png", show=False, kind='beachball')
```

it always throws exception message..

`Could not access event's moment tensor (list index out of range)`

### Observation

- event focal_mechanisms is empty

`event.focal_mechanisms`

Is there something i am missing here ?

**Comment by ThomasLecocq** [comment]
according to the answer here: https://github.com/obspy/obspy/issues/2684 you need to add includeallorigins=True to the get_events() call.

**Comment by Bhanuchander210** [comment]
Yep.. worked..!
Attaching snippet for reference..!

```
import obspy
from obspy.clients.fdsn import Client

cat = Client("USGS").get_events(starttime=obspy.UTCDateTime("2021-09-08T01:47:40"), endtime=obspy.UTCDateTime("2021-09-08T01:47:50"), includeallorigins=True)
for event in cat.events:
    print(event.short_str())
    event.plot(outfile=event.short_str() + "_bb.png", kind=['beachball'])
```
