### ISSUE TITLE
Missing timestamp in RESP conversion's "start date"

### ISSUE THREAD

**Issue by jschaeff** [obspy/obspy#2876]
-  ObsPy version, Python version and Platform: Python 3.9.6, obspy 1.2.2, GNU/Linux
  -  How did you install ObsPy and Python: obspy installed with pip

When using `obspy.io.xseed.parser`, in some cases (I could'nt determine for sure why), the `start Date` in the generated RESP file misses the time.

To reproduce:

1. Get the stationXML metadata and convert to dataless :
```
    wget -q  "http://ws.resif.fr/fdsnws/station/1/query?net=ZU&sta=LP15&loc=00&cha=HHZ&level=channel" -O ZU.LP15.00.HHZ.xml && java -jar stationxml-seed-converter-2.1.0.jar --output ZU.LP15.00.HHZ.dataless ZU.LP15.00.HHZ.xml
```
2.   Parse the dataless and write the response to file

```python
    from obspy.io.xseed.parser import Parser
    Parser('ZU.LP15.00.HHZ.dataless').write_resp(folder='.', zipped=False)
    /home/schaeffj/.local/lib/python3.9/site-packages/obspy/io/xseed/fields.py:377: UserWarning: Date is required.
    warnings.warn('Date is required.', UserWarning)
```
3.   Look at the file:
   at RESP.ZU.LP15.00.HHZ    

    #        << obspy, Version 1.2.2 >>
    #        
    #        ======== CHANNEL RESPONSE DATA ========
    B050F03     Station:     LP15
    B050F16     Network:     ZU
    B052F03     Location:    00
    B052F04     Channel:     HHZ
    B052F22     Start date:  2016,175
    B052F23     End date:    2016,322,23:59:59.0000
    #        =======================================
    #        +                  +---------------------------------------+                  +
    #        +                  |   Channel Sensitivity,  LP15 ch HHZ   |                  +
    #        +                  +---------------------------------------+                  +
    #        
    B058F03     Stage sequence number:                 0
    B058F04     Sensitivity:                           0.000000E+00
    B058F05     Frequency of sensitivity:              0.000000E+00 HZ
    B058F06     Number of calibrations:                0

The `Start date:` line misses the timestamp.

With another stationXML (for instance http://ws.resif.fr/fdsnws/station/1/query?net=FR&sta=CIEL&loc=00&cha=HHE&level=response) the `Start date` is complete and correct.

**Comment by paitor** [comment]
Have you verified that this is not an issue the dataless file (e.g. inspect the content using [pdcc](http://ds.iris.edu/ds/nodes/dmc/software/downloads/PDCC/3-0/manual/)), if this is the case,please provide the dataless file ZU.LP15.00.HHZ.dataless

**Comment by jschaeff** [comment]
We tried with another dataless exported by PDCC.
It reproduces the problem.

This input file : [ZU.station.LP15.New.dataless.txt](https://github.com/obspy/obspy/files/7137318/ZU.station.LP15.New.dataless.txt)

with this code:

```python
from obspy.io.xseed.parser import Parser
Parser('ZU.station.LP15.New.dataless').write_resp('.',zip=False)
```

Produces those RESP files: 
[RESP.ZU.LP15.00.HHE.txt](https://github.com/obspy/obspy/files/7137314/RESP.ZU.LP15.00.HHE.txt)
[RESP.ZU.LP15.00.HHN.txt](https://github.com/obspy/obspy/files/7137316/RESP.ZU.LP15.00.HHN.txt)
[RESP.ZU.LP15.00.HHZ.txt](https://github.com/obspy/obspy/files/7137317/RESP.ZU.LP15.00.HHZ.txt)

**Comment by ThomasLecocq** [comment]
the missing 00:00:00.00 comes from those lines:

https://github.com/obspy/obspy/blob/f026b8c70b92b462b14fe3cf5b0a3d5aef037344/obspy/core/utcdatetime.py#L1526-L1527

**Comment by ThomasLecocq** [comment]
the SEED norm states that this is a valid date:

> All positions of a time field must be zero padded to the left, but they do not need padding to the right if the time will be
truncated. “1987,023,04:23:05.1” and “1987,023” are correct.

--> p31 : http://www.fdsn.org/pdf/SEEDManual_V2.4.pdf

I wonder where you "UserWarning" comes from, and if it's from this field at all actually?

**Comment by jschaeff** [comment]
Thank you @ThomasLecocq for investigating. I was wondering if this is a valid date format, but could'nt find a reference.

I guess we can close this issue.

**Comment by ThomasLecocq** [comment]
@jschaeff I'm still curious to find out where the Warning comes from, so leave it open for now, thanks!

**Comment by megies** [comment]
There was enough time to be curious :stuck_out_tongue:  closing..
