### ISSUE TITLE
Memory leak through creation of "hidden" lists of strings in long-running application

### ISSUE THREAD

**Issue by qdbp** [obspy/obspy#2882]
Obspy version: 1.2.2

I have a long-running application that processes real-time seismic data, and has a memory leak which I've traced to the way ObsPy record history through `_add_processing_info`.

I have a single Trace to which I append new data, perform some statistics, then trim it down. However, every time I trim it down, `_add_processing_info` appends a string to the statistics:

```'ObsPy 1.2.2: trim(endtime=None::fill_value=None::nearest_sample=True::pad=False::starttime=UTCDateTime(2013, 11, 15, 4, 24, 4, 4500))'```

This causes memory to leak overtime in a very non-obvious way, since this is not part of the obspy public API (for instance, "processing" returns no hits on https://docs.obspy.org/packages/autogen/obspy.core.trace.Stats.html). It took me quite a while to hunt this issue down, and even more effort to attribute it `_add_processing_info` since for some reason `gc` does not pick up back-references for these lists correctly.

I believe a warning if this list grows past a certain amount should be issued, or a flag be documented as to how to turn this functionality off.

**Comment by qdbp** [comment]
I see this is done as part of `_add_processing_info` -- I want to make sure I'm not making a mistake somewhere with this before reopening it as an ObsPy problem.

**Comment by qdbp** [comment]
I've reopened this issue with an updated description.

**Comment by ThomasLecocq** [comment]
You can 

```python
for tr in st:
    tr.stats.processing = []
```
to prevent the processing info to be stored

**Comment by qdbp** [comment]
Yes, I ended up doing that. However, I still think that this is undocumented behavior that can cause hard-to-discover leaking memory merits at least documentation. Personally, I consider the fact that this processing recording is on by default to be a strange design choice.

**Comment by ThomasLecocq** [comment]
Thank you for your comment. Please suggest a Pull Request for change in the documentation and/or to the logic.

**Comment by megies** [comment]
I agree, we should probably set some limit on how many entries processing can have at maximum and then either..
 - let it grow larger still but at least the warning is shown
 - stop appending to processing info
 - make processing roll over in FIFO fashion

**Comment by megies** [comment]
fixed in above PR
