### ISSUE TITLE
Bugs when saving plotted beachballs to .pdf or .eps figures

### ISSUE THREAD

**Issue by sheng09** [obspy/obspy#2887]
https://github.com/obspy/obspy/blob/477659fe6fc940b87a2ffee09a47e6b34438bdf4/obspy/imaging/beachball.py#L167

I encountered a bug in plotting beachballs for source mechanisms. Specifically, when calling the functions `beach(...)` in `obspy/imaging/mopad_wrapper.py` or `obspy/imaging/beachball.py` with the arguments `axes` not equals `None`, there is always an error if save the plotted beachballs into vector files (e.g., .pdf or .eps).

To locate the error/bug, I found that the functions `beach(...)` calls the function
`matplotlib.transforms.IdentityTransform()` to create a Transform object. However, the
created object does not have the method `translate(...)` that is essential for saving
plots into vector files.

To fix the bug, it is simple by using the function `matplotlib.transforms.Affine2D(np.identity(3))`
instead of `matplotlib.transforms.IdentityTransform()` to create the Transform object.
The object created by the former has the method `translate(...)` and hence allows for
saving into vector files, while the object created by the latter does not.
Except for this difference, the objects created by the two functions have the same behaviors.

I have fixed the bug in my fork. The commit is my fork is here.
https://github.com/sheng09/obspy/commit/ac85a77e317f76ff4fd68505a18656c5d41a6e34
The fixing is very simple so that I revise in the master branch. Therefore, I simply raise the issue here instead of
newing a pull request. But I can new a PR if you think it is ok.

Below is an example for saving beachball plots into .pdf file. Without the fix, errors always happen. With the fix, errors disappear.

```python3
import matplotlib.pyplot as plt
import obspy.imaging.beachball as beachball

fig = plt.figure(figsize=(18, 5.5) )
ax = fig.add_subplot(111, aspect='equal')

bb = beachball.beach((0, 45, 90), facecolor='k', width=30, axes=ax, xy=(0, 0) )
ax.add_collection(bb)

plt.savefig('test.pdf')
```

**Comment by byoung4** [comment]
I also recently ran into this issue, and changing the PatchCollection's `IdentityTransform` to an `Affine2D` did not work for me.

However, I have been more successful playing with some of the axes transforms with the caveat that the beachballs will not be the correct aspect ratio if you change the xlims/ylims after computing the transform. To solve that, I added callbacks to the axes to recalculate the transforms.

I've pasted a code sample below, which should work in a Jupyter notebook. It will plot two sample beachballs which will be a consistent shape and maintain 1:1 aspect ratio as you pan, zoom, and change the xylims.

Perhaps there is an easier way to make this work that I don't know about.

```python
# import statements
import numpy as np
import matplotlib as mpl
import matplotlib.transforms
import matplotlib.pyplot as plt
import obspy


def EqualAspectTransform(axes, xy):
    """
    Return a transform that preserves the aspect ratio of a collection.
    
    :param axes: Axes that the Collection is plotted on
    :type axes: :class:`matplotlib.axes.Axes`
    :param xy: (x,y) position of the Collection
    :type xy: tuple or list
    :return: Matplotlib Transform object
    :rtype: :class:`matplotlib.transforms.CompositeGenericTransform`
    """
    return (
        # in the case of non-equal axes, scale the collection so that its width
        # is constant according to the smaller of the two axes
        mpl.transforms.Affine2D().scale(np.minimum(
                axes.transAxes.to_values()[0]/np.diff(axes.get_xlim()),
                axes.transAxes.to_values()[3]/np.diff(axes.get_ylim())
            ))
        # fix the aspect ratio of the collection to be equal, and translate to
        # the appropriate xy coordinates
        + mpl.transforms.ScaledTranslation(xy[0], xy[1], axes.transData)
    )


def beach(fm, linewidth=2, facecolor='b', bgcolor='w', edgecolor='k',
          alpha=1.0, xy=(0, 0), width=200, size=100, nofill=False,
          zorder=100, axes=None):
    """Wrapper to fix obpsy.imaging.beachball.beach aspect ratio hack"""
    
    # call obspy.imaging.beachball.beach() as normal if axes=None
    if not axes:
        
        # make a beachball
        bb = obspy.imaging.beachball.beach(fm, linewidth, facecolor, bgcolor,
                 edgecolor, alpha, xy, width, size, nofill, zorder, axes)

    # otherwise, plot at (0,0) and use transforms to fix the aspect ratio and
    # translate to the proper (x,y) coordinates
    else:
        
        # make a beachball centered at (0,0) and do not pass axes
        bb = obspy.imaging.beachball.beach(fm, linewidth, facecolor, bgcolor,
                 edgecolor, alpha, (0,0), width, size, nofill, zorder, None)
        
        # set the beachball's transform
        bb.set_transform(EqualAspectTransform(axes, xy))
        
        # create callbacks so it keeps its aspect ratio on zoom/pan/resize
        for event in ('xlim_changed', 'ylim_changed'):
            axes.callbacks.connect(event,
                lambda axes: bb.set_transform(EqualAspectTransform(axes, xy)))
        
    # return the beachball
    return bb


# moment tensor
mt = [-2.39, 1.04, 1.35, 0.57, -2.94, -0.94]

# make an non-equally-sized figure
fig, ax = plt.subplots(figsize=[10,6])

# make a couple beachballs
bb1 = beach(mt, width=5, xy=(2.5,5), axes=ax)
bb2 = beach(mt, width=2.5, facecolor="g", xy=(-1,-1.25), axes=ax)

# add the beachball to the plot
ax.add_artist(bb1)
ax.add_artist(bb2)

# decorate the plot
ax.set_xlim([-5, 10])
ax.set_ylim([-10, 10])
ax.grid()

# save figure and show
plt.savefig("example.pdf")
plt.show()
```

**Comment by megies** [comment]
I missed that ticket when it got first opened, but it seems the proposed fix works well. @byoung4 do you have an example for which that simple fix with `Affine2D` does not work?

**Comment by megies** [comment]
@byoung4 it seems your example works fine with the proposed fix and if passing in the `Axes` instance:

```python
# import statements
import matplotlib.pyplot as plt
import obspy

# moment tensor
mt = [-2.39, 1.04, 1.35, 0.57, -2.94, -0.94]

# make an non-equally-sized figure
fig, ax = plt.subplots(figsize=[10, 6])

# make a couple beachballs, and call axes=None.
# we'll implement the aspect ratio hack manually
xys = [(2.5, 5.0), (-1, -1.25)]  # xy coords
bbs = [obspy.imaging.beachball.beach(mt, width=5.0 * 50, facecolor="b", xy=xys[0], axes=ax),
       obspy.imaging.beachball.beach(mt, width=2.5 * 50, facecolor="g", xy=xys[1], axes=ax)]

# for each beachball
for bb in bbs:
    ax.add_collection(bb)

# decorate the plot
ax.set_xlim([-5, 10])
ax.set_ylim([-10, 10])
ax.grid()

# save figure and show
plt.savefig("example.pdf")
plt.show()
```

This works both in the interactive plot (with zooming in and out preserving circular shape) and in the pdf.

I think all you needed to do was pass in `axes=ax`. I had a look in the docs and the explanations seem fine (I don't use this much, and not sure what `unscaled axes` means, to be honest):
https://docs.obspy.org/master/packages/autogen/obspy.imaging.beachball.beach.html

![Screenshot from 2022-12-16 09-43-17](https://user-images.githubusercontent.com/1842780/208058971-04f60c12-14a2-4947-aa35-3fa66e8872e9.png)

**Comment by byoung4** [comment]
> @byoung4 it seems your example works fine with the proposed fix and if passing in the `Axes` instance:

Huh. I don't know what's on on my end, but your example still isn't working for me.

To be sure, I made a new Conda environment with `python=3.8` and `obspy=1.4.0`, then I went into `~/miniconda3/envs/beachball_test/lib/python3.8/site-packages/obspy/imaging` and changed Line 195 in `mopad_wrapper.py` from

```python
195    collection.set_transform(transforms.IdentityTransform())
```
to
```python
195    collection.set_transform(transforms.Affine2D(np.identity(3)))
```

and Line 166 in `beachball.py` from

```python
166    col.set_transform(transforms.IdentityTransform())
```
to
```python
166    col.set_transform(transforms.Affine2D(np.identity(3)))
```

To make sure the change stuck I also added a couple print statements.

Then I copied your code verbatim

```python
# import statements
import matplotlib.pyplot as plt
import obspy

# moment tensor
mt = [-2.39, 1.04, 1.35, 0.57, -2.94, -0.94]

# make an non-equally-sized figure
fig, ax = plt.subplots(figsize=[10, 6])

# make a couple beachballs, and call axes=None.
# we'll implement the aspect ratio hack manually
xys = [(2.5, 5.0), (-1, -1.25)]  # xy coords
bbs = [obspy.imaging.beachball.beach(mt, width=5.0 * 50, facecolor="b", xy=xys[0], axes=ax),
       obspy.imaging.beachball.beach(mt, width=2.5 * 50, facecolor="g", xy=xys[1], axes=ax)]

# for each beachball
for bb in bbs:
    ax.add_collection(bb)

# decorate the plot
ax.set_xlim([-5, 10])
ax.set_ylim([-10, 10])
ax.grid()

# save figure and show
plt.savefig("example.pdf")
plt.show()
```

And this is what I got:
![Screen Shot 2022-12-16 at 7 57 09 PM](https://user-images.githubusercontent.com/39967823/208220616-4d058e92-4d7e-465f-a7e1-bb7173f7749a.png)

The beachball is down there, but the xy coordinates are wrong, and it's off the corner of the plot no matter the xylims.

**Comment by megies** [comment]
@byoung4 hmm, yea, it works for me on matplotlib 3.5 but if I go to matplotlib 3.6 it indeed doesn't work. Need to investigate next week

**Comment by byoung4** [comment]
@megies Great catch.

After taking a look at changes in MPL 3.5.3 and MPL3.6.0, it appears that changing the `col._transOffset = ax.transData` to `col.set_offset_transform(ax.transData)` fixes the problem!

Working code example

```python
# import statements
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import transforms
import obspy

# moment tensor
mt = [-2.39, 1.04, 1.35, 0.57, -2.94, -0.94]

# make an non-equally-sized figure
fig, ax = plt.subplots(figsize=[10,6])

# make a couple beachballs, and call axes=None.
# we'll implement the aspect ratio hack manually
xys = [(2.5, 5.0), (-1, -1.25)]  # xy coords
bbs = [obspy.imaging.beachball.beach(mt, width=5.0*25, facecolor="b", xy=xys[0], axes=None),
       obspy.imaging.beachball.beach(mt, width=2.5*25, facecolor="g", xy=xys[1], axes=None)]

# for each beachball
for i in range(len(bbs)):
    
    # get beachball and xy coords
    bb = bbs[i]
    xy = xys[i]
    
    # perform the aspect ratio hack in obspy.imaging.beachball.beach
    # - https://github.com/obspy/obspy/blob/master/obspy/imaging/beachball.py#L164
    bb.set_transform(transforms.Affine2D(np.identity(3)))
    for p in bb._paths:
        p.vertices -= xy
    bb.set_offsets(xy)
    #bb._transOffset = ax.transData
    bb.set_offset_transform(ax.transData)
        
    # add the beachballs to the plot
    ax.add_collection(bb)

# decorate the plot
ax.set_xlim([-5, 10])
ax.set_ylim([-10, 10])
ax.grid()

# save figure and show
plt.savefig("example.pdf")
plt.show()
```

**Comment by megies** [comment]
Nice find!
