### ISSUE TITLE
trigger_onset() fails if characteristic function does not drop below off-threshold before hitting the end of the characteristic function

### ISSUE THREAD

**Issue by dizcza** [obspy/obspy#2891]
ObsPy: master branch, installed as `pip install -e .`
Ubuntu 20.04 LTS

Should `thr_on` be always less than `thr_off`, make a change to the `trigger_onset` function and throw an error respectively.

From the tutorials:

```python
cft = delayed_sta_lta(trace.data, int(5 * df), int(10 * df))
plot_trigger(trace, cft, 5, 10)  # thr_on < thr_off
...
cft = classic_sta_lta(trace.data, int(5. * df), int(10. * df))
plot_trigger(trace, cft, 1.5, 0.5)  # thr_on > thr_off
```

Now I want to swap the thresholds:

```python
cft = classic_sta_lta(trace.data, int(5. * df), int(10. * df))
plot_trigger(trace, cft, 0.5, 1.5)  # thr_on < thr_off

Traceback (most recent call last):
  File "/home/dizcza/PycharmProjects/other/obspy/misc/docs/source/tutorial/code_snippets/trigger_tutorial_classic_sta_lta.py", line 9, in <module>
    plot_trigger(trace, cft, 0.5, 1.5)
  File "/home/dizcza/PycharmProjects/other/obspy/obspy/signal/trigger.py", line 556, in plot_trigger
    on_off = np.array(trigger_onset(cft, thr_on, thr_off))
  File "/home/dizcza/PycharmProjects/other/obspy/obspy/signal/trigger.py", line 378, in trigger_onset
    while of[0] < on[0]:
IndexError: deque index out of range
```

**Comment by ThomasLecocq** [comment]
@dizcza reminder to check if this is still relevant after your PRs ?

**Comment by dizcza** [comment]
@ThomasLecocq yes, it's still relevant - I've not fixed this because the code is convoluted and I got lost.

**Comment by megies** [comment]
Can confirm that this is an actual bug. It happens when the event trigger is active towards the end of the characteristic function and then the ctf never falls below the off-threshold before hitting the end of the ctf.

**Comment by megies** [comment]
![Figure_2](https://user-images.githubusercontent.com/1842780/157486097-8fd72991-f3c6-4213-8ace-43ea33b07b1a.png)

so what happens is your second event trigger never goes above your off threshold and therefore also cant fall below it before trace ends..

**Comment by dizcza** [comment]
Glad that you worked it out.
I was not using the function. I just opened the issue to let you know.

**Comment by megies** [comment]
Fixed in linked PR
