### ISSUE TITLE
can't build obspy 1.2.2, `get_data_files_without_manifest`

### ISSUE THREAD

**Issue by qdbp** [obspy/obspy#2896]
Obspy doesn't pin the version of setuptools in its pyproject.toml. Due to a recent breaking change in setuptools 58.5:

https://github.com/pypa/setuptools/issues/2849

This is causing pep-517 compliant installers (such as recent versions of pip) to fail to build obspyt.

```
pip3 wheel obspy==1.2.2
...
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
...
      raise AttributeError(attr)
  AttributeError: get_data_files_without_manifest

```

**Comment by ThomasLecocq** [comment]
I can't reproduce this and all tests pass, so I guess the setuptools issue is solved now.
