### ISSUE TITLE
"no response found for NET ..." with "ppsd.add(tr)"

### ISSUE THREAD

**Issue by siderique** [obspy/obspy#2899]
When I execute "ppsd.add(tr)", out is "False" and below warning message is shown.

Other mini-seed file is working good with same response file(metadata).

I guess mini-seed file has some problems, but I want to know what is the reason.

WARNING: no response found for NET=OO, STA=OO, LOCID=00, CHAN=HGE, DATE=2021,304,15:59:58.2400  <----- start time
WARNING: no response found for NET=OO, STA=OO, LOCID=00, CHAN=HGE, DATE=2021,304,15:59:58.2400  <----- end time

I want to execute "PPSD" to evaluate Ambient Noise Levels.

Thank you

**Comment by flixha** [comment]
Does the miniseed file that does work with the ppsd-function have the same network/station/location and channel codes as the one that doesn't work? 
And can you check whether the response has a `.start_date` and `.end_date` set that matches the time that the "new" trace was recorded in?

**Comment by ThomasLecocq** [comment]
closing since no answer from OP
