### ISSUE TITLE
unexpected detrend in signal.util.enframe

### ISSUE THREAD

**Issue by jojomale** [obspy/obspy#2901]
Hi, I recently discovered that `signal.util.enframe()` (Obspy 1.2.2) removes a constant trend from each row (=each frame). For me, this was quite unexpected. If this behavior is intentional, it might be nice to document it at least.
Cheers,
Johanna

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a [short, self contained, correct example](http://sscce.org/) that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)

**Comment by megies** [comment]
The routines in there are from obspy's primordial soup, kind of.. dating from 2011 and coming in from some personal signal processing piece of work, so a lot in that part is very much tweaked to that old research project, so it might or might not fit everybody's needs (can't really say, never used those routines myself tbh).

In any case added some info to that docstring
