### ISSUE TITLE
Station.identifiers[0] should not be URI type

### ISSUE THREAD

**Issue by mikehagerty** [obspy/obspy#2905]
Hello!
Just want to say that obspy continues to be an incredibly useful package!

I'm trying to set the identifiers on an obspy Station instance.
According to FDSN schema 1.1 IdentifierType should be a simple string with "type" attribute:
```
  <xs:complexType name="IdentifierType">
    <xs:annotation>
      <xs:documentation>A type to document persistent identifiers.
        Identifier values should be specified without a URI scheme (prefix),
        instead the identifer type is documented as an attribute.
      </xs:documentation>
    </xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="type" type="xs:string"> </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

```
However, obspy (v.1.2.2) seems to have encoded this as xsd:anyURI type instead:

>>> wes.identifiers = ['10.157778/RESIF.FR']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mth/mth/miniconda3/envs/test_yasmine/lib/python3.8/site-packages/obspy/core/inventory/util.py", line 123, in identifiers
    _warn_on_invalid_uri(identifier)
  File "/Users/mth/mth/miniconda3/envs/test_yasmine/lib/python3.8/site-packages/obspy/core/inventory/util.py", line 1076, in _warn_on_invalid_uri
    msg = "Given string seems to not be a valid URI: ''" % uri
TypeError: not all arguments converted during string formatting

```
>>> wes.identifiers=['http://10.16778/RESIF.FR', 'http://32.2323/RESIF.CR']
>>> print("obspy is happy now!")
```

Tracking it down a bit further:

core/inventory/util.py:
```
    @identifiers.setter
    def identifiers(self, value):
        if not hasattr(value, "__iter__"):
            msg = "identifiers needs to be an iterable, e.g. a list."
            raise ValueError(msg)
        # make sure to unwind actual iterators, or the just might get exhausted
        # at some point
        identifiers = [identifier for identifier in value]
        for identifier in identifiers:
            _warn_on_invalid_uri(identifier)
        self._identifiers = identifiers
```

This calls:

```
def _warn_on_invalid_uri(uri):
    if not _is_valid_uri(uri):
        msg = "Given string seems to not be a valid URI: ''" % uri
        warnings.warn(msg)
```

And that msg seems to be missing the %s format to print uri and that seems to be
the error I'm getting.

So I guess there are 2 things:
1. identifiers - sholudn't be checked as valid_uri, at least not for basenode types
2. the _warn_on_invalid_uri() func has an error in msg.

Thanks!
-Mike

**Comment by megies** [comment]
Two things..
- yes, that error needs to be fixed
- stationxml is just storing the URI in two pieces (URI path as the text value and URI scheme attribute "type") whereas we decided to keep it in one piece in obspy internally, just to keep it simple, so checking and warning if not following URI syntax still seems like the right thing to do, also considering how FDSN StationXML xsd is pleading for a valid URI scheme:path syntax in the annotation ;-)
