### ISSUE TITLE
Assertion Error: SEISAN read()

### ISSUE THREAD

**Issue by anthonyrinaldi4** [obspy/obspy#2909]
* ObsPy version - 1.2.2
* Python version - 3.9.7
* Platform - Windows 10
* Installed obspy using pip

Code:
`from obspy import read`
`st = read('path/to/file/2009-11-01-0000-00S.LAVEE_001', format = "SEISAN")`

I get an AssertionError:
![image](https://user-images.githubusercontent.com/57881402/146475740-87ba2e78-1575-499a-a046-7532c5e3ebd0.png)

I have attached the SEISAN file for reference.
[2009-11-01-0000-00S.zip](https://github.com/obspy/obspy/files/7731508/2009-11-01-0000-00S.zip)

I have already tried reinstalling obspy, tried using python 3.7 and 3.8 and tried on GoogleColab and keep getting the same error.

**Comment by flixha** [comment]
Hi, I am guessing that this is an older Seisan waveform file for which the obspy-function does not fully recognize on what system (OS and fortran compiler) it was written, and hence how to read the bytes (see [decription of the challenge here](https://github.com/obspy/obspy/blob/c4faef6b2df110e844c28ca2aa9515888c019cb8/obspy/io/seisan/core.py#L59-L92)). I tried to look a bit what this file is, but I'm not experienced at that and I guess it was written on a system for which Obspy is not able to decipher. Would of course be nice to throw a more useful warning, or to understand and implement this very formatting.

As a workaround, you can use `wavetool` that comes with Seisan to convert this file to the new version of Seisan waveform files (start `wavetool`, enter path to file, press enter 6 times). Obspy reads the new Seisan file without problems.

**Comment by megies** [comment]
closing for lack of feedback
