### ISSUE TITLE
Release 1.2.3 or 1.3 (or 2.0) ?

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#2916]
We should do a 1.2.3 release ASAP, mainly due to the latest issue with numpy 1.22 (#2912 #2913) 

Please everybody try to check if any vital PR or issue needs to be finished that we want in 1.2.3, otherwise bump to 1.2.4 or later release

@obspy/maintainers

Currently problematic dependencies:

- numpy==1.22
- proj4>=6

**Comment by d-chambers** [comment]
@ThomasLecocq do you have the PyPi credentials? If so, we should consider setting up a token for doing automatic releases with a github actions. This would trigger whenever we add a new version tag. I did this for obsplus [here](https://github.com/d-chambers/obsplus/blob/8d6e3736b8e4fccbdc75554b14cc160a1a1ea45e/.github/workflows/release_published.yml#L47-L78).

**Comment by ThomasLecocq** [comment]
> @ThomasLecocq do you have the PyPi credentials? If so, we should consider setting up a token for doing automatic releases with a github actions. This would trigger whenever we add a new version tag. I did this for obsplus [here](https://github.com/d-chambers/obsplus/blob/8d6e3736b8e4fccbdc75554b14cc160a1a1ea45e/.github/workflows/release_published.yml#L47-L78).

nope, I don't think so, have to look for that

**Comment by d-chambers** [comment]
Ya, I think @megies used to do all of that so he has them for sure. If we can't publish to pypi it will make the release process very difficult...

**Comment by ThomasLecocq** [comment]
I will contact him now

**Comment by trichter** [comment]
Comparing changelogs of master and maintenance only these items are missing in master:

```
 - obspy.clients.filesystem.tsindex:
   * improvements to leap second file setup and other small fixes (see #2776)
 - obspy.io.nordic:
   * fixed a bug where the number 0 was converted to string ' ' instead of '0'
   * Made default pick weight ' ' (unspecified) instead of '0' (best)
```

**Comment by d-chambers** [comment]
ok, I will work on getting these into master now.

**Comment by d-chambers** [comment]
Let me know if I am wrong (@flixha, @calum-chamberlain, or anyone else who works with the seisan format), but I am fairly confident #2749 is made obsolete by #2814 and related work. We can ignore for now unless we hear otherwise.

**Comment by d-chambers** [comment]
Ok, I think master should have everything we need from the maintenance  branch (assuming changelog is up-to-date)  once #2931 merges.

**Comment by trichter** [comment]
I renamed previous milestone 2.0.0 to 1.3.0. I renamed previous milestone 1.2.3 to 1.3.1.
I moved all open issues in 1.3.0 to a new milestone 1.4.0.
I moved most closed issues in 1.3.1 to 1.3.0 double checking that they are in the current master.

**Comment by ThomasLecocq** [comment]
closing this issue here in favor of #2929

**Comment by calum-chamberlain** [comment]
@d-chambers - just to set this to rest - yes I'm confident that #2749 is made obsolete by #2814 and can be ignored.
