### ISSUE TITLE
OBSPY / MassDownLoader 

### ISSUE THREAD

**Issue by langlami** [obspy/obspy#2924]
Dear All,
This is not a bug report rather than a list of question about this great tool I am beginning to use.

I am using it to download a large amount of data.
From the code exemples given I wrote a small code. It works, great.
But, I don't understand everythings :
- how does the code manage the retreive, it does not seems to be sequential regarding the dates, true ?
- about the logging outputs, I did not achieve to get more information than the standard info. I try the "debug=True" option but it does not give so much more, I try to follow the exemple with the logging option, same. In fact I would like to get informations such as number of files to be collected, remaining number of files...
- What is the exact meaning of the message "[2022-01-05 10:51:40,540] - obspy.clients.fdsn.mass_downloader - INFO: Client 'IRIS' - No data available for request." ? Because it appears for exemple many times when I relaunch my script while many data have been already collected. Could it be that this message is also output when the file is already downloaded in the local directory ?
- in the exemple webpage [https://docs.obspy.org/packages/autogen/obspy.clients.fdsn.mass_downloader.html] there is a short mistake at the "step 3 : Start the Download" the parameter "chunk_size_in_mb" does not exist and seems to be "download_chunk_size_in_mb"

Thanks in advance for your answers,

Regards
Mickael.

**Comment by ThomasLecocq** [comment]
Hi, you shouldn't really use the Issues here to ask questions, that's the purpose of the https://discourse.obspy.org/ platform.

@krischer you're the best to answer this :-)

**Comment by QuLogic** [comment]
I'll close, as the question has been asked on Discourse.
