### ISSUE TITLE
Switch to using GitHub Discussions?

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#2927]
Just a question here to @obspy/maintainers : should we think to move the Q&A to the GitHub Discussions tab? I know we switched the forum to discourse, but since many (many) users continue to ask questions on the Issues, the GHD allows for moving Issues to discussions, discussions to issues, or to PR ... see https://github.com/ROBelgium/MSNoise/discussions for example

**Comment by d-chambers** [comment]
I am in favor of switching. It's nice to have everything obspy related in one place.

**Comment by trichter** [comment]
For me it does not matter.

**Comment by claudiodsf** [comment]
It would be nice to have everything on GitHub.

Would it be feasible to migrate everything from Discourse or to keep the two in sync?

**Comment by ThomasLecocq** [comment]
> It would be nice to have everything on GitHub.
> 
> Would it be feasible to migrate everything from Discourse or to keep the two in sync?

hehe, some already suffered to import from the mailing list/previous stuff to discourse...

**Comment by ThomasLecocq** [comment]
worth reading https://github.com/meilisearch/devrel/issues/21

**Comment by d-chambers** [comment]
>> worth reading meilisearch/devrel#21

Yes, they make some good points. Maybe we just leave it how it is then (at least until/if github discussion evolves).

**Comment by d-chambers** [comment]
Closing for now, repoen if you think we should consider GH discussions more.
