### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#2929]
Things to do, when release candidates and final release are done:
- [x] set the [version number and DOI in CHANGELOG.txt](https://github.com/obspy/obspy/blob/master/CHANGELOG.txt), set a git tag, [publish tag as a release](https://github.com/obspy/obspy/tags)
- [ ] Run docker tests (@krischer / @megies -- ~~are done routinely now, but double-checking can't hurt~~)
- [x] source distribution to [pypi](https://pypi.org/project/obspy/) (made by https://github.com/obspy/obspy/pull/2943)
- [x] wheels for all platforms on [pypi](https://pypi.org/project/obspy/): https://github.com/obspy/obspy/pull/2943
- [x] [conda packages](https://anaconda.org/conda-forge/obspy/files) built via [conda-forge feedstock](https://github.com/conda-forge/obspy-feedstock/pulls): https://github.com/conda-forge/obspy-feedstock/pull/49
- [ ] optionally: other packaging efforts
  - [ ] [debian packages](https://deb.obspy.org/)
  - [ ] redhat/centos packages
  - [ ] macports packages
- [x] [zenodo](https://zenodo.org/): reserve a DOI pre-release (done: **10.5281/zenodo.6327346**)
- [x] [zenodo](https://zenodo.org/): upload sdist zipball and finalize release
- [x] Update [docs](https://docs.obspy.org/) once released (should be done automatically, built in gh-actions and [deployed on our server by a bot](https://github.com/obspy/obspy/tree/master/misc/scripts/docs_deploybot))
- [x] [News entry in the wiki](https://github.com/obspy/obspy/wiki/#news)
- [x] "What's new?" page in the wiki --> https://github.com/obspy/obspy/wiki/What's-New-in-ObsPy-1.3
- [x] Email to the [announcements mailing list](https://mail.python.org/mailman3/lists/obspy.python.org/)
- [x] [Discourse announcement](https://discourse.obspy.org/c/announcements/11)
- [x] [Tweet](https://twitter.com/obspy)
- [x] update base branches for all pull requests bumped to 1.3.x to a new branch `maintenance_1.3.x`
- [ ] check dependency versions, some old distros we used to support might have gone EOL since release of 1.2, so we might be able to bump minimum dependency versions of e.g. numpy, scipy, matplotlib, ...
---
- [x] Party :tada: (don't tick before all other checkboxes are ticked!)

**Comment by ThomasLecocq** [comment]
I really think we want the SeisComP XML stuff in 1.3.0 --> @claudiodsf could you check/group the issues/PR & rebase somehow?

**Comment by trichter** [comment]
By the way, locally I always get a single fail due to flake8 when running obspy-runtests: https://tests.obspy.org/115482/

I suspect this output on stderr is related
```
/home/eule/dev/obspy/obspy/clients/fdsn/tests/test_client.py:76:22: E741 ambiguous variable name 'l'
/home/eule/dev/obspy/obspy/clients/fdsn/tests/test_client.py:78:27: E741 ambiguous variable name 'l'
/home/eule/dev/obspy/obspy/clients/fdsn/tests/test_client.py:81:31: E741 ambiguous variable name 'l'
/home/eule/dev/obspy/obspy/clients/fdsn/tests/test_client.py:99:27: E741 ambiguous variable name 'l'
/home/eule/dev/obspy/obspy/geodetics/base.py:481:31: E741 ambiguous variable name 'l'
/home/eule/dev/obspy/obspy/io/gse2/tests/test_libgse2.py:201:28: E741 ambiguous variable name 'l'
/home/eule/dev/obspy/obspy/io/nordic/core.py:2114:14: N806 variable 'add_BAZ_line' in function should be lowercase
/home/eule/dev/obspy/obspy/io/nordic/core.py:2132:18: N806 variable 'add_BAZ_line' in function should be lowercase
/home/eule/dev/obspy/obspy/io/sac/tests/test_sacpz.py:43:22: E741 ambiguous variable name 'l'
/home/eule/dev/obspy/obspy/io/sac/tests/test_sacpz.py:44:27: E741 ambiguous variable name 'l'
/home/eule/dev/obspy/obspy/io/sac/tests/test_sacpz.py:59:22: E741 ambiguous variable name 'l'
/home/eule/dev/obspy/obspy/io/sac/tests/test_sacpz.py:60:27: E741 ambiguous variable name 'l'
/home/eule/dev/obspy/obspy/signal/array_analysis.py:828:21: E741 ambiguous variable name 'l'
/home/eule/dev/obspy/obspy/signal/rotate.py:109:20: E741 ambiguous variable name 'l'
/home/eule/dev/obspy/obspy/taup/slowness_model.py:108:13: E741 ambiguous variable name 'l'
```

**Comment by ThomasLecocq** [comment]
looks like strict PEP8 (new?) checks ? (at least for the `l` param, the lowercase stuff could indead be corrected)

**Comment by trichter** [comment]
I added a fix for these pep8 fails to #2720.

**Comment by claudiodsf** [comment]
> I really think we want the SeisComP XML stuff in 1.3.0 --> @claudiodsf could you check/group the issues/PR & rebase somehow?

The relevant PRs are: #2124, #2284 and #2695.

I'll try to see what I can do...

**Comment by ThomasLecocq** [comment]
could be interesting to have a look at #2752 too

**Comment by d-chambers** [comment]
Here are my thoughts on this release vs 2.0.0

Let's try to get anything that doesn't change API/behavior into 1.3. Mainly bug fixes and some minor new features.

Then let's do a 2.0.0 release fairly quickly which will include things like:

1. Remove deprecated modules (seishub, arclink, db, ... others?) 
2. Merge #2592 (which is a great idea but may never exactly replicate the previous behavior)
3. Merge #2489 (changes obspy-runtest api)
4. Add more modernization to pre-commit (black, isort, etc...) which will be super nice but change almost every line of code
5. Add typehints to public methods/classes

 After all that we will have a thoroughly modern ObsPy codebase, but it will be hard to merge any previous work.

**Comment by ThomasLecocq** [comment]
Question relative to 1.3 -- we will need to provide whl & conda packages for python 3.7, 3.8, 3.9 and 3.10 -- so what do you think about adding 3.10 to the PR & master tests already now (see #2942 for python 3.10 test) ?

**Comment by ThomasLecocq** [comment]
I will rewrite #2783 for building wheels for all matrix items.
What do you think about https://github.com/marketplace/actions/build-deb-action to create the debian packages?

**Comment by trichter** [comment]
> Question relative to 1.3 -- we will need to provide whl & conda packages for python 3.7, 3.8, 3.9 and 3.10 -- so what do you think about adding 3.10 to the PR & master tests already now (see #2942 for python 3.10 test) ?

The question is: Why should we not try to support the newest version of Python?

> I started the wiki page : https://github.com/obspy/obspy/wiki/What's-New-in-ObsPy-1.3

For a starter you can copy content from here:
https://github.com/obspy/obspy/wiki/What's-New-in-ObsPy-2.0

> What do you think about https://github.com/marketplace/actions/build-deb-action to create the debian packages?

I have no clue about deb packaging, but I doubt that it is working out of the box.

**Comment by ThomasLecocq** [comment]
>The question is: Why should we not try to support the newest version of Python?
roger that :-) #2942 is now 🟢 for merging to master, to include all [3.7-3.10]

**Comment by filefolder** [comment]
> > I really think we want the SeisComP XML stuff in 1.3.0 --> @claudiodsf could you check/group the issues/PR & rebase somehow?
> 
> The relevant PRs are: #2124, #2284 and #2695.
> 
> I'll try to see what I can do...
> 
> EDIT: I pinged the authors of these three PRs and proposed to do the rebase/force-push myself 😉

Hiya, as alluded in the other PR thread i have made an attempt here: #2962. Still need help on a couple things.

**Comment by trichter** [comment]
Can we push for this next release? Only a few issues are left in the 1.3.0 milestone...

**Comment by megies** [comment]
So... initially I think the plan was to make a Py3-only release shortly after 1.2.x and name it 1.3.0, without a lot of actual changes besides dropping Python 2. That obviously didn't happen like that and the changelog is quite long for this release and we dropped some deprecated things as well..

.. so, maybe we could even label this 2.0.0 instead as it's quite a big step?

But I don't wanna hold up the release with a discussion about it, just a thought.

**Comment by trichter** [comment]
For me 1.3.0 is enough, the changelog is long, but the API changes are not crowdy, the only big change being the different invocation of `obspy-runtests`. @filefolder I agree to push out the next release ASAP, calling a fix release 2.0 is IMHO not a good idea, I was first thinking you want to make a good joke :grin:

**Comment by d-chambers** [comment]
I really want to see #2592 merged but since it may never quite work like evalresp it probably needs a major version bump, so perhaps we save 2.0 for that? We also should make UTCDateTime immutable which could break some codes so it should go into 2.0 as well.

**Comment by trichter** [comment]
I created a tag `1.3.0a1` referring to the latest commit in master since no open issues for the 1.3.0 milestones are left (anything missing?). We could still change the version number to `2.0.0`. Wheels and source were uploaded to testpypi. For testing you can install the wheel for your platform with

```
pip install -i https://test.pypi.org/simple/ obspy
```

The source dist can be installed with

```
pip install -i https://test.pypi.org/simple/ --no-binary=obspy obspy
```

**Comment by megies** [comment]
Conda feedstock looks OK-ish on the a1: https://github.com/conda-forge/obspy-feedstock/pull/49
Half the nodes have green lights: https://tests.obspy.org/?node=conda-forge

There are a handful of fails though, but due to (what I think is) a [bug in pytest-json-report](https://github.com/obspy/obspy/pull/2489#issuecomment-1060491035) it's kinda painful to check all individual nodes.

**Comment by trichter** [comment]
According to the uploaded test reports pytest-json-report is used in a quiet old version for conda-forge. Can we pin to a newer version?

**Comment by megies** [comment]
> [...] quiet old version for conda-forge. Can we pin to a newer version?

Yes, pretty much just needs those autobot PRs on their feedstock taken care of

**Comment by megies** [comment]
It seems conda forge by default now also does pypy builds.. I don't know much about pypy but I guess we never did any pypy builds before and I should just disable pypy builds in our feedstock?

**Comment by megies** [comment]
Besides the failing pypy stuff, there is only one conda build on our feedstock with errors:
https://tests.obspy.org/120817/#1

**Comment by megies** [comment]
Nevermind, actually there's some other issues with mseed tests getting stuck.. I kinda remember something like that happening before but can't find mention of it right now
 - https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=471214&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1183ba29-a0b5-5324-8463-2a49ace9e213&l=6633
Seems to be affecting all windows builds in conda forge, @ThomasLecocq you see any problems on win on your machine?

**Comment by trichter** [comment]
Just had a look into `test_mseed_special_issues.py` and comments in `test_infinite_loop` test mention that it is not working when building conda packages on Windows. So, its skip condition just needs to be adapted.

**Comment by megies** [comment]
Ah, thanks, I knew it was in there somewhere but didnt search for the right terms.. ;-)

**Comment by trichter** [comment]
Thanks to @megies the conda feedstock is up to date. Anything left? Now we just need to tag the tip of master and draft a release? Do we want to update the wiki page for 1.3 or just write the most relevant changes in the release notes?

**Comment by megies** [comment]
> Now we just need to tag the tip of master and draft a release? 

Yeah, let's go :rocket: 


>  Do we want to update the wiki page for 1.3 or just write the most relevant changes in the release notes?

Not sure what you mean, but yea, we should do most of the low hanging fruit things from the above check list ( so omit all packaging besides conda :rofl: )

**Comment by trichter** [comment]
> Can you create the release from it?

Can do it, too. I saw it's just copy-pasting the changelog basically.

**Comment by megies** [comment]
> Can do it, too. I saw it's just copy-pasting the changelog basically.

Yes, the github release is just setting the tag to "release", pasting in the changelog and optionally might be good to attach docs build once ready

**Comment by megies** [comment]
> Can you create the release from it? Edit: This will again trigger the building of wheels and finally the upload to pypi.

Uhm.. not sure I understand.. how do we get it built for pypi?

**Comment by trichter** [comment]
Just wait a moment:

https://github.com/obspy/obspy/actions/runs/1963651953

We will see if it works.
