### ISSUE TITLE
Python 3.9 tests - Image Comparison

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#2930]
#2925 added 3.9 to the test matrix but ! this comes at a price, of some ugly temporary stuff:

- currently 3 different environment files for the 3 versions tested
- awful hack in:
  - obspy/core/tests/test_util_base.py
  - obspy/core/util/testing.py
  - obspy/signal/tests/test_spectral_estimation.py

Ideas:
- saving the "baseline", "computed" & "difference" images to a local folder of the runner
- if not empty, zipping that folder and providing it as an artifact for each test run (or upload it somewhere as 1 file)
- therefore removing the imgur uploads which are not very practical
- then with those, find out how bad/strong most of the images are on all platforms & why (e.g. for some it's only xlabels, but for some others, e.g. response information, there are significant shape change, e.g. https://i.imgur.com/L1d4DNF.png

**Comment by QuLogic** [comment]
Possibly switch to `pytest-mpl` to go along with #2489?

**Comment by ThomasLecocq** [comment]
the 3 awful hacks are properly reverted in #2489

**Comment by d-chambers** [comment]
Yes, image comparison tests are removed in #2489, awful hacks and all
