### ISSUE TITLE
Import error for obspy v1.2.2 (windows, pip install)

### ISSUE THREAD

**Issue by FelixSchwock** [obspy/obspy#2940]
I get an AttributeError when importing obspy (v1.2.2) in a jupyter notebook. I use windows and installed obspy using pip in a Python 3.8 conda environment.

This are the code and error message:

`import obspy`

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_32556/3356176566.py in <module>
----> 1 import obspy

~\anaconda3\envs\obspy\lib\site-packages\obspy\__init__.py in <module>
     37 
     38 # don't change order
---> 39 from obspy.core.utcdatetime import UTCDateTime  # NOQA
     40 from obspy.core.util import _get_version_string
     41 __version__ = _get_version_string(abbrev=10)

~\anaconda3\envs\obspy\lib\site-packages\obspy\core\__init__.py in <module>
    122 
    123 # don't change order
--> 124 from obspy.core.utcdatetime import UTCDateTime  # NOQA
    125 from obspy.core.util.attribdict import AttribDict  # NOQA
    126 from obspy.core.trace import Stats, Trace  # NOQA

~\anaconda3\envs\obspy\lib\site-packages\obspy\core\utcdatetime.py in <module>
     25 import numpy as np
     26 from obspy.core.compatibility import py3_round
---> 27 from obspy.core.util.deprecation_helpers import ObsPyDeprecationWarning
     28 
     29 # Regular expression used in the init function of the UTCDateTime objects which

~\anaconda3\envs\obspy\lib\site-packages\obspy\core\util\__init__.py in <module>
     25 # import order matters - NamedTemporaryFile must be one of the first!
     26 from obspy.core.util.attribdict import AttribDict
---> 27 from obspy.core.util.base import (ALL_MODULES, DEFAULT_MODULES,
     28                                   NATIVE_BYTEORDER, NETWORK_MODULES,
     29                                   NamedTemporaryFile, _read_from_plugin,

~\anaconda3\envs\obspy\lib\site-packages\obspy\core\util\base.py in <module>
     34 from pkg_resources import get_entry_info, iter_entry_points
     35 
---> 36 from obspy.core.util.misc import to_int_or_zero, buffered_load_entry_point
     37 
     38 

~\anaconda3\envs\obspy\lib\site-packages\obspy\core\util\misc.py in <module>
    212 try:
    213     from numpy import loadtxt
--> 214     loadtxt(np.array([0]), ndmin=1)
    215 except TypeError:
    216     # otherwise redefine loadtxt

~\anaconda3\envs\obspy\lib\site-packages\numpy\lib\npyio.py in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows, like)
   1084         # the need for decoding and estimate the number of columns.
   1085         for first_line in line_iter:
-> 1086             ncols = len(usecols or split_line(first_line))
   1087             if ncols:
   1088                 # Put first_line back.

~\anaconda3\envs\obspy\lib\site-packages\numpy\lib\npyio.py in split_line(line)
    975         """Chop off comments, strip, and split at delimiter."""
    976         for comment in comments:  # Much faster than using a single regex.
--> 977             line = line.split(comment, 1)[0]
    978         line = line.strip('\r\n')
    979         return line.split(delimiter) if line else []

AttributeError: 'numpy.int32' object has no attribute 'split'`

**Comment by calum-chamberlain** [comment]
Kia ora, see this issue: https://github.com/obspy/obspy/issues/2912 - a new obspy release is coming to fix this. In the meantime you can downgrade to numpy 1.21.
