### ISSUE TITLE
P arrival not given by tauP

### ISSUE THREAD

**Issue by sfps1108** [obspy/obspy#2941]
* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a [short, self contained, correct example](http://sscce.org/) that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)

# Edit by @calum-chamberlain - original (lightly edited) title here:
Hi. I have the latest version of Obspy working in linux. I installed Obspy and Python by Anaconda. I have been working with some seismic data, I calculate the epicenter distance with the method `obspy.clients.iris.client.Client.distaz`, next I calculate the P arrival time with the method `obspy.taup.tau.TauPyModel.get_ray_paths`. When calculating the epicenter distance all is good, but in the moment I want to calculate the P arrival time, some calculated values throw an error of the type `list index out of range`. For instance, when I type the following code: 

```python
m = TauPyModel("ak135f_no_mud") 
p_arrival = m.get_ray_paths(source_depth_in_km = 50.0, distance_in_degree = 3.94823, phase_list=["P"])[0] 
```
an error appears.

**Comment by sfps1108** [comment]
![imagen](https://user-images.githubusercontent.com/97415300/148707095-a0c6e0a1-fd89-4fd8-bb86-ee0de3adbfdd.png)

**Comment by calum-chamberlain** [comment]
Can you make the title of the issue something much shorter and fill out the issue form please.

**Comment by calum-chamberlain** [comment]
The phase-list you specified does not include any of the computed phases, hence the `IndexError`.

Try running:
```python
arrivals = m.get_ray_paths(source_depth_in_km = 50.0, distance_in_degree = 3.94823)
for arr in arrivals:
    print(arr)
```
to see the computed phases for this location. Check the [phase naming in TauP](https://docs.obspy.org/packages/obspy.taup.html#phase-naming-in-obspy-taup) section of the docs for what these mean. The first arriving phase in your example is an upward going P-phase denoted by the lower-case p tag. You might want to be more permissive of different P-phase arrival types in your `phase_list`.
