### ISSUE TITLE
Default instrument set to DISP if not known but VEL is simulated

### ISSUE THREAD

**Issue by jwassermann** [obspy/obspy#2945]
Hi - it's not directly an issue but an inconvenient default setting. We are working more and more with rotational motion sensors which physical unit is rad/s. As we ask the manufacturers of the instrument to send stationXML or NRL lookups together with the equipment it would be best to include the rad/s and rad physical units also into obspy. This means, however, that the list of intputs and outputs in the obspy remove_response routine needs to be extended to rotation rate and rotation (if we want to be completely precise). 
A current "flaw" in obspy remove_response default settings is (at least for me) that if the instrument type is not known, it will assume its is a DISP sensor and simulates then as default a VEL sensor. I think  this is not a good strategy even when the first step IS mentioned in the docs. I prefer to have both defaults in the same physical space, which would result in less surprises - at least that's what I have done in my local copy. Cheers Jo

**Comment by d-chambers** [comment]
Hey @jwassermann I think changes in defaults for `remove_response` would best implemented after/during #2592 which will be after 1.3.0. I will tag this issue to make sure we revisit sometime after 1.3 is released.

**Comment by megies** [comment]
From the evalresp manpage of the version we currently still use:

https://github.com/obspy/obspy/blob/221c7ef4a960e8001115a8cd7111dd5854239b21/obspy/signal/src/evalresp/evalresp.1#L209-L216

Didn't try it, but maybe we could use that `DEF` (default units) thingy, sounds like it doesn't add any integration/differentiation.

Looks like [evalresp (even in newest versions 5.0.0) has no handling for rotational units](https://github.com/iris-edu/evalresp/blob/315617bb06ea7fc6853f6abe435265e26c8ce191/libsrc/evalresp/input.c#L409-L501).

**Comment by megies** [comment]
OK, for future reference, we just had a look and the issue is here:

https://github.com/obspy/obspy/blob/221c7ef4a960e8001115a8cd7111dd5854239b21/obspy/core/inventory/response.py#L1195-L1202

We could maybe see if when unknown units are encountered, we override `output` and set it to `DEF` (assumingly doing nothing). Overall it might still be problematic, since basically on unknown units we tell evalresp simply for every stage that input and output units are all the same.

**Comment by aringler-usgs** [comment]
It might be useful to deal with the case of polynomial responses as well.  These will usually be for pressure sensors ([example](http://service.iris.edu/irisws/resp/1/query?net=IU&sta=ANMO&loc=31&cha=LDO&starttime=2012-09-21T00:00:00&endtime=2599-12-31T23:59:59)).

Rough logic for dealing with this following.  I can make a pull request to include this after #2592 gets included.

```
def remove_polynomial(st, inv):
    # Simple function to remove the response of polynomial responses
    for tr in st.select(channel='LDO'):
        # Grab polynomial response
        resp = inv.get_response(tr.id, tr.stats.starttime).instrument_polynomial.coefficients
        # Go to floats to avoid type issues.
        tr.data = np.require(tr.data, dtype=np.float64)
        # Make a data vector of zeros
        data_temp = np.zeros_like(tr.data)
        # For each coefficient add the data to data_temp
        for idx, coef in enumerate(resp):
            data_temp += coef*(tr.data**idx) 

        tr.data = data_temp

    return
```

**Comment by aringler-usgs** [comment]
@megies Ack good catch.  Someone on a slack channel was having issues with the polynomial response.  However, in 1.2.2 the polynomial response works.  I should have had them check their code version.  Sorry for the confusion!
