### ISSUE TITLE
Cannot import obspy 1.2.2

### ISSUE THREAD

**Issue by seismomomo** [obspy/obspy#2959]
I can't import obspy because of an issue with the UTCDateTime module. I think it's related to [this issue](https://github.com/obspy/obspy/issues/2958) posted minutes before mine.

#### Specifications
- Obspy 1.2.2
- Python 3.10
- OS: Linux
- Installed using miniconda
- Problem first noticed: Jan 14, 2022
- Last time above versioning worked: Jan 11, 2022

#### Things tried
- Creating a new environment
- Reinstalling miniconda
- Downgrading from python 3.10 to python 3.9
- Creating an environment with only obspy and ipython
- Downloading everything via conda-forge channel

iPython command:
`import obspy` 

Output:
> AttributeError                            Traceback (most recent call last)
> Input In [1], in <module>
> ----> 1 import obspy

> File ~/software/pkg/miniconda3/envs/test-python/lib/python3.9/site-packages/obspy/__init__.py:39, in <module>
>      36 import requests
>      38 # don't change order
> ---> 39 from obspy.core.utcdatetime import UTCDateTime  # NOQA
>      40 from obspy.core.util import _get_version_string
>      41 __version__ = _get_version_string(abbrev=10)

> File ~/software/pkg/miniconda3/envs/test-python/lib/python3.9/site-packages/obspy/core/__init__.py:124, in <module>
>     121 from future.builtins import *  # NOQA
>    123 # don't change order
> --> 124 from obspy.core.utcdatetime import UTCDateTime  # NOQA
>     125 from obspy.core.util.attribdict import AttribDict  # NOQA
>     126 from obspy.core.trace import Stats, Trace  # NOQA

> File ~/software/pkg/miniconda3/envs/test-python/lib/python3.9/site-packages/obspy/core/utcdatetime.py:27, in <module>
>      25 import numpy as np
>      26 from obspy.core.compatibility import py3_round
> ---> 27 from obspy.core.util.deprecation_helpers import ObsPyDeprecationWarning
>      29 # Regular expression used in the init function of the UTCDateTime objects which
>      30 # is called a lot. Thus pre-compile it.
>      31 _YEAR0REGEX = re.compile(r"^(\d{1,3}[-/,])(.*)$")

> File ~/software/pkg/miniconda3/envs/test-python/lib/python3.9/site-packages/obspy/core/util/__init__.py:27, in <module>
>      25 # import order matters - NamedTemporaryFile must be one of the first!
>      26 from obspy.core.util.attribdict import AttribDict
> ---> 27 from obspy.core.util.base import (ALL_MODULES, DEFAULT_MODULES,
>      28                                   NATIVE_BYTEORDER, NETWORK_MODULES,
>      29                                   NamedTemporaryFile, _read_from_plugin,
>      30                                   create_empty_data_chunk, get_example_file,
>      31                                   get_script_dir_name, MATPLOTLIB_VERSION,
>      32                                   SCIPY_VERSION, NUMPY_VERSION,
>      33                                   BASEMAP_VERSION, CARTOPY_VERSION,
>      34                                   PROJ4_VERSION, CatchAndAssertWarnings)
>      35 from obspy.core.util.misc import (BAND_CODE, CatchOutput, complexify_string,
>      36                                   guess_delta, loadtxt, score_at_percentile,
>      37                                   to_int_or_zero, SuppressOutput)
>      38 from obspy.core.util.obspy_types import (ComplexWithUncertainties, Enum,
>      39                                          FloatWithUncertainties)

> File ~/software/pkg/miniconda3/envs/test-python/lib/python3.9/site-packages/obspy/core/util/base.py:36, in <module>
>      33 from future.utils import native_str
>      34 from pkg_resources import get_entry_info, iter_entry_points
> ---> 36 from obspy.core.util.misc import to_int_or_zero, buffered_load_entry_point
>      39 # defining ObsPy modules currently used by runtests and the path function
>      40 DEFAULT_MODULES = ['clients.filesystem', 'core', 'db', 'geodetics', 'imaging',
>      41                    'io.ah', 'io.arclink', 'io.ascii', 'io.cmtsolution',
>      42                    'io.cnv', 'io.css', 'io.dmx', 'io.focmec', 'io.hypodd',
>    (...)
>      49                    'io.win', 'io.xseed', 'io.y', 'io.zmap', 'realtime',
>      50                    'scripts', 'signal', 'taup']

> File ~/software/pkg/miniconda3/envs/test-python/lib/python3.9/site-packages/obspy/core/util/misc.py:214, in <module>
>     212 try:
>     213     from numpy import loadtxt
> --> 214     loadtxt(np.array([0]), ndmin=1)
>     215 except TypeError:
>     216     # otherwise redefine loadtxt
>     217     def loadtxt(*args, **kwargs):

> File ~/software/pkg/miniconda3/envs/test-python/lib/python3.9/site-packages/numpy/lib/npyio.py:1086, in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows, like)
>    1083 # Read until we find a line with some values, and use it to determine
>    1084 # the need for decoding and estimate the number of columns.
>    1085 for first_line in line_iter:
> -> 1086     ncols = len(usecols or split_line(first_line))
>    1087     if ncols:
>    1088         # Put first_line back.
>    1089         line_iter = itertools.chain([first_line], line_iter)

> File ~/software/pkg/miniconda3/envs/test-python/lib/python3.9/site-packages/numpy/lib/npyio.py:977, in loadtxt.<locals>.split_line(line)
>     975 """Chop off comments, strip, and split at delimiter."""
>     976 for comment in comments:  # Much faster than using a single regex.
> --> 977     line = line.split(comment, 1)[0]
>     978 line = line.strip('\r\n')
>     979 return line.split(delimiter) if line else []

> AttributeError: 'numpy.int64' object has no attribute 'split'

**Comment by ThomasLecocq** [comment]
Yes, the same issue & same cause. We are preparing a next release, in the meantime, please downgrade numpy to 1.21

**Comment by FSet89** [comment]
Downgrading  numpy causes the error that I reported in the mentioned issue

**Comment by seismomomo** [comment]
Downgrading numpy to 1.21 worked for me

**Comment by megies** [comment]
original ticket #2912
