### ISSUE TITLE
 Extended textual headers are not yet supported

### ISSUE THREAD

**Issue by Me2ll** [obspy/obspy#2987]
Hi, I encountered this error while reading the file. (.gcf)

![Screenshot_16](https://user-images.githubusercontent.com/8104526/155284827-f11617ba-c952-435e-9bbf-1d325530503c.png)

**Comment by BigSamu** [comment]
Apparently, Extended Textual Headers in Obspy are not supported yet. Someone can confirm this. Is there a way to read stanzas of those headers in an easy way (key-value pairs I mean) in a SEGY file (rev1 or rev2)?

**Comment by Me2ll** [comment]
As a temporary solution i used this,

![Screenshot_17](https://user-images.githubusercontent.com/8104526/156511956-c7cace0b-748f-4b76-b98e-0fdd26c06cd6.png)

**Comment by BigSamu** [comment]
But that option allows you to read extended textual headers? I understand that this is not possible yet.

**Comment by Me2ll** [comment]
my problem was with GCF @megies

**Comment by BigSamu** [comment]
I was referring to SEGY files format @megies. Sorry for the confusion

**Comment by megies** [comment]
> my problem was with GCF @megies

I'm pretty sure GCF does not have anything like "extended textual headers", so if you see that trying to read a gcf file, the only thing I can think of is obspy trying to read your GCF file as a SEGY file. Try to specify `read(..., format='GCF')` and if you did not do that it might be that your GCF file is somehow identified by obspy as a GCF file, which we would need to fix if that is really the case.

**Comment by megies** [comment]
Closing for now. Pretty sure this never was about gcf but SEGY extended textual headers, and I don't see anybody coming forth volunteering to implement those at this point

**Comment by paitor** [comment]
Sorry for a late comment. As pointed out in #3055 while updating the gcf reader there is a weakness in the _is_segy() function that may cause identifying a gcf file as a segy file. This ought to be addressed at some point by someone familiar with the segy format.

**Comment by megies** [comment]
@paitor do we have a GCF file that `_is_segy()` sees as a (false) positive?

**Comment by paitor** [comment]
Well, I can construct a silly example but it only fails on windows...

**Comment by megies** [comment]
> Well, I can construct a silly example but it only fails on windows...

well then nevermind, because i dont have windows ;)

**Comment by paitor** [comment]
Me neither had to borrow one. In any case the potential issue with the
automatic format detection in the read function should be hidden now as I
changed the order in which formats are tested (gcf before segy).

If I remember correctly the silly example consisted in writing big endian
data to file on a little endian OS (silly as I can't wrap my head around
why this is tested in obspy even for formats with no endianess flag in the
header) coupled to the windows c-compiler doing funny stuff

**Comment by megies** [comment]
Gotcha, shouldn't be an issue anymore then :+1:
