### ISSUE TITLE
mention cartopy in setup.py?

### ISSUE THREAD

**Issue by megies** [obspy/obspy#3000]
Maybe we should put cartopy into setup.py under `EXTRAS_REQUIRE['...']`, maybe as 'imaging' or 'maps'? I know its purely cosmetic, but people tend to look up dependencies in setup.py.

**Comment by trichter** [comment]
I agree! See https://github.com/obspy/obspy/pull/2981/commits/731cd1e121da97031ed94b3bec6d136ac0ac0e4b in #2981.

**Comment by megies** [comment]
:rofl:
