### ISSUE TITLE
Inconsistent behaviour with st.merge(method=-1)

### ISSUE THREAD

**Issue by TomWinder** [obspy/obspy#3004]
**Issue description:**
When merging with `method=-1` (i.e. `st._cleanup()`), `merge()` does not explicitly return the resulting `Stream` object, whereas for the other methods it does. This can desirable - e.g. cycling through a `Stream` and applying the merge operation individually for each id, such that if one amongst many doesn't pass the merge checks then they are not all rejected (see e.g. https://github.com/QuakeMigrate/QuakeMigrate/issues/137) . I would imagine doing this with:

```
ids = set([tr.id for tr in st])
st_merged = Stream()
for tr_id in ids:
    st_merged += st.select(id=tr_id).merge(method=-1)
```

This is currently possible, but only by using the internal `st._cleanup()` function, which does explicitly return the new `Stream` object.

**Suggested fix:**

Lines 2009-2011 of `obspy.core.stream`:
```
        self._cleanup(**kwargs)
        if method == -1:
-            return
+            return self
```

**Platform info:**
 - ObsPy version: 1.2.2
 - Python version: 3.8.4
 - Operating System: Ubuntu 16.04
 - Installed through anaconda

**Comment by trichter** [comment]
Hi Tom,

thanks for raising this issue. Sounds reasonable.
Could you provide a PR against master branch?

**Comment by TomWinder** [comment]
I have made the PR - not sure if the linking with this issue is correct, so please let me know if that needs changing!
