### ISSUE TITLE
instrument correction on miniseed using dataless

### ISSUE THREAD

**Issue by manudavi** [obspy/obspy#3022]
Hi,

I am quite new to ObsPy, and I am trying to process a miniseed file by applying instrument correction included in a separate seedless file.
The result I am getting does not look right, the time history has a strong base line deviation, I am not sure if I need to define any more input for the function simulate to work?

I have done the check just on a single trace of the stream. If I want to extend to the whole stream, does the routine understand which instrument correction to apply? 

Many thanks for any help you can give me.

Those are the code lines I am using:

import obspy
from obspy import read
from obspy.io.xseed import Parser

st=read("bdsAutodrm-rU8TsD") # contains the input miniseed file
print(st)
tr7= st[6]  # assign trace to new variable

st.plot()
tr7.plot()

tr7.write('2021-12-27-WOL00-BH1-SH_ASC.asc', format='SH_ASC') # extracting one trace from the stream

#st = obspy.read("2021-12-27-WOL00-BH1-SH_ASC.asc")
#st = obspy.read("bdsAutodrm-rU8TsD")

parser = Parser("202112270145-0245WOL.dataless") 
print(parser)

tr7.simulate(seedresp={'filename': parser, 'units': "ACC"}) #Apply instrument response to trace
tr7.write('2021-12-27-WOL00-BH1-SH_ASC_cor.asc', format='SH_ASC') #saves corrected waveform
tr7.plot()

**Comment by megies** [comment]
Please use our User Forum for usage questions, thanks!
https://discourse.obspy.org/

[read_inventory](https://docs.obspy.org/master/packages/autogen/obspy.core.inventory.inventory.read_inventory.html) should be able to read Dataless SEED, `Parser` and `seed_resp=` is outdated.
