### ISSUE TITLE
No uploads to test server from CI since 3 days

### ISSUE THREAD

**Issue by trichter** [obspy/obspy#3031]
I wanted to check out tests.obspy.org. But since three days uploads from CI are not working. Locally it's working for me.

E.g. https://github.com/obspy/obspy/runs/5690003276

```
Error: Could not sent a test report to tests.obspy.org.
Bad Request
```

**Comment by megies** [comment]
maybe there is something in server logs? @barsch

**Comment by barsch** [comment]
bad requests are not logged - will look into it ...

**Comment by barsch** [comment]
thats really strange - no code changes from my side, no packages/dependencies have been updated, no code changes on obspy side and nothing at all in the logs ... however, some non gh-action reports are going through ..., see https://tests.obspy.org/ - so no idea :/

@trichter can you please send me the resulting report JSON file (which is failing) so I try to debug it locally

**Comment by barsch** [comment]
https://github.com/obspy/obspy/blob/master/obspy/scripts/runtests.py#L135 should also include ```print(response.content)``` to get the actual error message and not only the HTTP status code

**Comment by trichter** [comment]
@basch The environment dictionary in the JSON is empty now. It was automagically filled before. So actually, it is more consistent now. Maybe the release of pytest-metadata 2.0.0 on Mar 22 is related.

The content of the sever response is `b"'Packages'"` and probably hints to this line:

https://github.com/obspy/reporter/blob/cf56a9b1039864d50a9b9724dc8bc5159e01eeab/src/reporter/core/views.py#L45

You could check instead for  pytest in dependencies dictionary. Also the query for python version needs to be changed, e.g. `['platform_info']['python_version']`.

Relevant json files: https://github.com/obspy/obspy/actions/runs/2042105327#artifacts

**Comment by trichter** [comment]
> should also include print(response.content)

I pushed it directly to maintenance branch.

**Comment by barsch** [comment]
@trichter thanks - this helped a lot to clear up the issue!

should be fixed in https://github.com/obspy/reporter/commit/501eca00770420fc2e80563b1f7dde58677189a2 - is also already deployed on the server, so let's see if it works now ...

**Comment by trichter** [comment]
@barsch Thanks! It is working again. `dependencies['pytest']` is inserted by ourselves in conftest.py and should be present in all uploaded JSON reports, i.e. the second try clause is not necessary.
