### ISSUE TITLE
expanded channel information in str(Station)

### ISSUE THREAD

**Issue by filefolder** [obspy/obspy#3039]
### Problem

This is also PR  https://github.com/obspy/obspy/pull/3024 but figured I'd try to get a few more eyeballs on it before throwing in the towel. 

To me the 'station' view of an inventory (e.g.` inv[0][0]`) is sort of redundant to the 'network' view and isn't particularly helpful to quickly assess the channel information. Personally I like to be able to see what sample rates are present and QC any span overlaps quickly at a glance. 

I had two preliminary alternatives but seeking opinions. First is a complete expansion of the channels (with samplerate and span)
```
Station MCQ (Macquarie Island)
	Station Code: MCQ
	Channel Count: 30/30 (Selected/Total)
	2004-06-28T00:00:00.000000Z -
	Access: open
	Latitude: -54.4986, Longitude: 158.9561, Elevation: 14.0 m
	Available Channels:
	    .00.HNZ   200.00 Hz   2020-03-15 to None
	    .00.HNN   200.00 Hz   2020-03-15 to None
	    .00.HNE   200.00 Hz   2020-03-15 to None
	    .00.HHZ   200.00 Hz   2020-03-15 to None
	    .00.HHN   200.00 Hz   2020-03-15 to None
	    .00.HHE   200.00 Hz   2020-03-15 to None
	    .00.BNZ    40.00 Hz   2020-03-15 to None
	    .00.BNN    40.00 Hz   2020-03-15 to None
	    .00.BNE    40.00 Hz   2020-03-15 to None
	    .00.BHZ    40.00 Hz   2020-03-15 to None
	      ..BHZ    40.00 Hz   2008-04-28 to None
	    .00.BHN    40.00 Hz   2020-03-15 to None
	      ..BHN    40.00 Hz   2008-04-28 to None
	    .00.BHE    40.00 Hz   2020-03-15 to None
	      ..BHE    40.00 Hz   2008-04-28 to None
	      ..BHZ    20.00 Hz   2004-06-28 to 2008-04-27
	      ..BHN    20.00 Hz   2004-06-28 to 2008-04-27
	      ..BHE    20.00 Hz   2004-06-28 to 2008-04-27
	      ..LCQ     1.00 Hz   2008-04-28 to None
	      ..LCE     1.00 Hz   2008-04-28 to None
	      ..AX0     1.00 Hz   2008-04-28 to None
	      ..VPB     0.10 Hz   2008-04-28 to None
	      ..VMW     0.10 Hz   2008-04-28 to None
	      ..VMV     0.10 Hz   2008-04-28 to None
	      ..VMU     0.10 Hz   2008-04-28 to None
	      ..VKI     0.10 Hz   2008-04-28 to None
	      ..VEP     0.10 Hz   2008-04-28 to None
	      ..VEC     0.10 Hz   2008-04-28 to None
	      ..VEA     0.10 Hz   2008-04-28 to None
	      ..VCO     0.10 Hz   2008-04-28 to None
```

and 2) is more or less the same but joining the CH codes. This is probably my preference.
```
Station MCQ (Macquarie Island)
	Station Code: MCQ
	Channel Count: 30/30 (Selected/Total)
	2004-06-28T00:00:00.000000Z -
	Access: open
	Latitude: -54.4986, Longitude: 158.9561, Elevation: 14.0 m
	Available Channels:
	    .00.HN[ENZ]   200.00 Hz   2020-03-15 to None
	    .00.BN[ENZ]    40.00 Hz   2020-03-15 to None
	      ..BH[ENZ]    40.00 Hz   2008-04-28 to None
	      ..BH[ENZ]    20.00 Hz   2004-06-28 to 2008-04-27
	      ..LC[EQ]      1.00 Hz   2008-04-28 to None
	      ..AX0         1.00 Hz   2008-04-28 to None
	      ..VPB         0.10 Hz   2008-04-28 to None
	      ..VM[UVW]     0.10 Hz   2008-04-28 to None
	      ..VKI         0.10 Hz   2008-04-28 to None
	      ..VE[ACP]     0.10 Hz   2008-04-28 to None
	      ..VCO         0.10 Hz   2008-04-28 to None
```
It may also be interesting to present any non-standard information here as well (e.g. nonzero azimuth/dip, non geophysical channels), >10m borehole depth, that kind of thing. 

The concern is, is this too much information? At the network level I would say definitely, but if you're at the station level my feeling is you want as much information as possible before printing the entire station.channels list.

**Comment by megies** [comment]
I think I agreed at some point in the other ticket, that it might make sense to expand the Station info some, I can agree that it is kinda the same as on network level. Personally I find option 1) might be overdoing it a bit and I'm not sure if it really that fast to grasp as an overview (but I do have strong enough of an opinion to strongly oppose that one either). 

Option 2) looks really good to me though, and I'd be all for it. I'm not sure how you'd want to add more channel detail information there without cluttering it though, but if you have ideas go ahead and put em here. =)

And lastly, again, I think it's a pity that we never (yet..?!) got that visual Inventory representation / content overview plot thing across the finish line, I think that's exactly what you'd want to get an idea of an inventory's contents fast (see #2023).

**Comment by filefolder** [comment]
now merged // but do send any gripes through
