### ISSUE TITLE
Missing documentation of kwarg stations in Network class 

### ISSUE THREAD

**Issue by paitor** [obspy/obspy#3060]
### Documentation Link

https://docs.obspy.org/packages/autogen/obspy.core.inventory.network.Network.html

### Problem

Currently documentation for kwarg `stations` in the `Network` class is missing

### Suggested improvement

Add documentation (presumably an instance of the `Station` class is expected?)

**Comment by megies** [comment]
> Add documentation (presumably an instance of the `Station` class is expected?)

`Network.__init__(stations=...)` should be a list of `Station` type, yes!
