### ISSUE TITLE
Obspy Event cannont be written in NORDIC format when it comes from a SeisComP3 event located with hypo71

### ISSUE THREAD

**Issue by dsiervo** [obspy/obspy#3066]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

I am loading events from a SeisComP3 server into Obspy using Client.get_events and then writing them in NORDIC format.
Doing this I get an error when the preferred origin was located with Hypo71.

### Code to Reproduce

```python
from obspy.clients.fdsn import Client

client = Client(server_IP+":"+port_fdsn)
cat = client.get_events(eventid='SGC2022jirgrh', includearrivals=True)

for event in cat:
        event.write('SGC2022jirgrh.sfile', format="NORDIC", userid="anls")
```

### Error Traceback

```Python traceback
File "seiscomp2sfiles_circulo_kale_v2.py", line 75, in <module>
    event.write('SGC2022jirgrh.sfile', format="NORDIC", userid="anls")
  File "/home/sgc/anaconda3/envs/eqt/lib/python3.7/site-packages/obspy/core/event/event.py", line 320, in write
    Catalog(events=[self]).write(filename, format, **kwargs)
  File "/home/sgc/anaconda3/envs/eqt/lib/python3.7/site-packages/obspy/core/event/catalog.py", line 509, in write
    return write_format(self, filename, **kwargs)
  File "/home/sgc/anaconda3/envs/eqt/lib/python3.7/site-packages/obspy/io/nordic/core.py", line 940, in write_select
    string_io=select, high_accuracy=high_accuracy)
  File "/home/sgc/anaconda3/envs/eqt/lib/python3.7/site-packages/obspy/io/nordic/core.py", line 1149, in _write_nordic
    sfile.write(_write_hyp_error_line(origin) + '\n')
  File "/home/sgc/anaconda3/envs/eqt/lib/python3.7/site-packages/obspy/io/nordic/core.py", line 1310, in _write_hyp_error_line
    cov = Ellipse.from_origin_uncertainty(origin.origin_uncertainty).\
  File "/home/sgc/anaconda3/envs/eqt/lib/python3.7/site-packages/obspy/io/nordic/ellipse.py", line 67, in from_origin_uncertainty
    a = uncert.max_horizontal_uncertainty
AttributeError: 'NoneType' object has no attribute 'max_horizontal_uncertainty'
```

### ObsPy Version?

1.2.2

### Operating System?

Ubuntu 18.04

### Python Version?

Python 3.7.11

### Installation Method?

conda

**Comment by megies** [comment]
@flixha you able to work on this? That part of the code isn't taking into account that there are different ways that origin uncertainties can be specified. Should be trivial to fix.

**Comment by flixha** [comment]
@megies Yes I can look at this; I have a few small updates for the Nordic I/O support lined up anyways so that's a good point to get them all in a clean PR.

@dsiervo Could you write one event where you get the error to a quakeml file and share that here? That would make fixing the issue a bit easier for me. While it should not be hard to fix, the devil is in the detail here. There's already support for assigning the location uncertainties from different uncertainty definitions, so it's not fully obvious why it fails in this case after it has already gone through a check. So testing it on a real file would be the easiest to fix it.

**Comment by megies** [comment]
> There's already support for assigning the location uncertainties from different uncertainty definitions, so it's not fully obvious why it fails in this case after it has already gone through a check

Ah OK, cool, didn't see that part just briefly checked the error message. :+1:

**Comment by megies** [comment]
Great to hear, so then it seems it's OK to close the issue. :rocket:
