### ISSUE TITLE
Clarify xcorr_3c docstring

### ISSUE THREAD

**Issue by core-man** [obspy/obspy#3069]
### Documentation Link

https://docs.obspy.org/packages/autogen/obspy.signal.cross_correlation.xcorr_3c.html

### Problem

A new implementation of cross-correlation, i.e., `correlate`, is created in #1585 and `xcorr` is removed in  #1979. But the documentation for `xcorr_3c` still refers to `xcorr`:

https://github.com/obspy/obspy/blob/654442a26d7d1af213fc7a86831d655b79586031/obspy/signal/cross_correlation.py#L313

### Suggested improvement

I guess this line should replace `xcorr` with `correlate`, right?

**Comment by megies** [comment]
@trichter should know better

**Comment by trichter** [comment]
> I guess this line should replace xcorr with correlate, right?

Yes, it just needs to be replaced.
