### ISSUE TITLE
network code mismatch for network BX in ISC event picks

### ISSUE THREAD

**Issue by maritinkolej** [obspy/obspy#3102]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

Atleast events from ISC catalog for my region (Botswana) have an error in the event waveform ID Network code. WaveformStreamID
network_code: 'IR'
station_code: 'KHWEE'
channel_code: ''
location_code: '--'
The network_code is supposed to be BX here.
Other networks are also showing as IR which is not correct. 

### Code to Reproduce

```python
client = Client("ISC")
cat = client.get_events(eventid=618328264, includearrivals=True)

def get_trace_params(pick):
    net = pick.waveform_id.network_code
    sta = pick.waveform_id.station_code

    trace_params = {
        "station_network_code": net,
        "station_code": sta,
        "trace_channel": pick.waveform_id.channel_code[:2],
        "station_location_code": pick.waveform_id.location_code,
    }

    return trace_params

get_trace_params(catalog[0].picks[0])
```

### Error Traceback

```Python traceback
{'station_network_code': 'IR',
 'station_code': 'BROLN',
 'trace_channel': 'B?',
 'station_location_code': '--'}
```

### ObsPy Version?

obspy 1.22

### Operating System?

Debian

### Python Version?

python --version 3.77

### Installation Method?

conda

**Comment by filefolder** [comment]
this seems more like an ISC/catalog issue than an obspy/software issue

**Comment by megies** [comment]
Yes, this is a usage question. @maritinkolej please use our forum for things like this :smiley: 

https://discourse.obspy.org

I didn't see this was cross posted, here my reply from gitter:

Maybe you should talk to ISC why they use this alternate code for those stations. I am guessing you are trying to download data based on the WaveformStreamID of the picks in the event files in an automated way? That's a good approach and you can simply fix the network code on the fly in your program, something like..

```python
from obspy.clients.fdsn import Client
client = Client('IRIS')
inv = client.get_stations(network='BX', level='station')
sta_codes_bx = [sta.code for net in inv for sta in net]

for pick in event.picks:
    is_IR = pick.waveform_id.network_code == 'IR'
    should_be_BX = pick.waveform_id.station_code in sta_codes_bx
    if is_IR and should_be_BX:
        pick.waveform_id.network_code = 'BX'
    client.get_waveforms(....)
```

**Comment by maritinkolej** [comment]
Noted very well, next time I will use the forum, and thank you very much for your kind assistance. The information is very helpful.

thanks again

Joseph
________________________________

**Comment by megies** [comment]
Looks like there might be some weirdness in what network codes ISC has set on (some?) picks in their event database. @shicks-seismo would you know whom to best make aware of this? Not sure at this point if and how big of an issue this is and where it might come from, so not saying that it is an ISC made issue :smile:

**Comment by maritinkolej** [comment]
This may be useful to you. The response from ISC is that "the ISC Bulletin uses the network code IR (International Registry) as all stations submitted to the ISC for registration receive this code as the default network code. The IR does not currently make use of FDSN network codes e.g BX".

**Comment by ThomasLecocq** [comment]
> This may be useful to you. The response from ISC is that "the ISC Bulletin uses the network code IR (International Registry) as all stations submitted to the ISC for registration receive this code as the default network code. The IR does not currently make use of FDSN network codes e.g BX".

LOL, the ISC recognising it's high time they change their default system to make use of network codes ! It's crazy now when someone wants to add a station to the ISC, have to find a free 3 or 4 letter code, pffff

**Comment by megies** [comment]
ugh
