### ISSUE TITLE
Error when create new stationxml file

### ISSUE THREAD

**Issue by Y-Tang99** [obspy/obspy#3108]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

Hello,
I need to create new stationxml files for removing instrument response purposes. I followed the instruction using this link: https://docs.obspy.org/tutorial/code_snippets/stationxml_file_from_scratch.html

However, I always got an error. To be more specific, the error is about the sensor[key]. My code is shown here:
![image](https://user-images.githubusercontent.com/59553039/178162095-d3ed88fd-0666-4ac7-990d-2f19d318f0a7.png)
The error message is shown here:
![image](https://user-images.githubusercontent.com/59553039/178162117-e051b159-70f9-4937-a2a4-341f22e269de.png)

I just wonder how to put the keys correctly? Any specific guidelines? Thank you!

### Code to Reproduce

```python
# creat station.xml file

import obspy
from obspy.core.inventory import Inventory, Network, Station, Channel, Site
from obspy.clients.nrl import NRL


# We'll first create all the various objects. These strongly follow the
# hierarchy of StationXML files.
inv = Inventory(
    # We'll add networks later.
    networks=[],
    # The source should be the id whoever create the file.
    source="ABCDE")

net = Network(
    # This is the network code according to the SEED standard.
    code="ABCDE",
    # A list of stations. We'll add one later.
    stations=[],
    description="ABCD",
    # Start-and end dates are optional.
    start_date=obspy.UTCDateTime(2021, 1, 1))

sta = Station(
    # This is the station code according to the SEED standard.
    code="ABCD",
    latitude=-7.649,
    longitude=16.904,
    elevation=14.05,
    creation_date=obspy.UTCDateTime(2022, 7, 8),
    site=Site(name="ABCD"))

cha = Channel(
    # This is the channel code according to the SEED standard.
    code="HHE",
    # This is the location code according to the SEED standard.
    location_code="",
    # Note that these coordinates can differ from the station coordinates.
    latitude=-7.649,
    longitude=16.904,
    elevation=14.05,
    depth=0.0,
    azimuth=0.0,
    dip=-90.0,
    sample_rate=100)

# By default this accesses the NRL online. Offline copies of the NRL can
# also be used instead
nrl = NRL()
# The contents of the NRL can be explored interactively in a Python prompt,
# see API documentation of NRL submodule:
# http://docs.obspy.org/packages/obspy.clients.nrl.html
# Here we assume that the end point of data logger and sensor are already
# known:
response = nrl.get_response( # doctest: +SKIP
    sensor_keys=['Guralp', 'CMG-40T', '10 seconds', '50 Hz', '1600 V/m/s'],
    datalogger_keys=['SeismologyResearchCentre', 'Gecko', '128', '100'])


# Now tie it all together.
cha.response = response
sta.channels.append(cha)
net.stations.append(sta)
inv.networks.append(net)

# And finally write it to a StationXML file. We also force a validation against
# the StationXML schema to ensure it produces a valid StationXML file.
#
# Note that it is also possible to serialize to any of the other inventory
# output formats ObsPy supports.
inv.write("ABCD_HHE.xml", format="stationxml", validate=True)
```

### Error Traceback

```Python traceback
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_8536\136603463.py in <cell line: 56>()
     54 # Here we assume that the end point of data logger and sensor are already
     55 # known:
---> 56 response = nrl.get_response( # doctest: +SKIP
     57     sensor_keys=['Guralp', 'CMG-40T', '10 seconds', '50 Hz', '1600 V/m/s'],
     58     datalogger_keys=['SeismologyResearchCentre', 'Gecko', '128', '100'])

~\anaconda3\envs\obspy\lib\site-packages\obspy\clients\nrl\client.py in get_response(self, datalogger_keys, sensor_keys)
    208         """
    209         dl_resp = self.get_datalogger_response(datalogger_keys)
--> 210         sensor_resp = self.get_sensor_response(sensor_keys)
    211 
    212         # Combine both by replace stage one in the data logger with stage

~\anaconda3\envs\obspy\lib\site-packages\obspy\clients\nrl\client.py in get_sensor_response(self, sensor_keys)
    169         sensor = self.sensors
    170         for key in sensor_keys:
--> 171             sensor = sensor[key]
    172 
    173         # Parse to an inventory object and return a response object.

~\anaconda3\envs\obspy\lib\site-packages\obspy\clients\nrl\client.py in __getitem__(self, name)
    248 
    249     def __getitem__(self, name):
--> 250         value = super(NRLDict, self).__getitem__(name)
    251         # if encountering a not yet parsed NRL Path, expand it now
    252         if isinstance(value, NRLPath):

KeyError: '10 seconds'
```

### ObsPy Version?

1.3.0

### Operating System?

Win11

### Python Version?

3.8

### Installation Method?

conda

**Comment by calum-chamberlain** [comment]
'10 seconds' isn't a known/valid key for this sensor. You might want to try exploring the NRL interactively in the Python prompt using the link just above your call to the NRL:
```python
print(nrl.sensors['Guralp']['CMG-40T'])
```
```
Select the natural period (or passband) for this sensor (11 items):
  '100s - 50Hz', '10s - 100Hz', '1s - 100Hz', '20s - 50Hz',
  '2s - 100Hz', '30s - 100Hz', '30s - 50 Hz', '40s - 100Hz',
  '5s - 100Hz', '60s - 100Hz', '60s - 50Hz'
```

**Comment by Y-Tang99** [comment]
Thank you for the reply, much appreciate it!

Now I successfully created the stationxml file. However, it cannot be used to remove the instrument response in my case. The error shows  "No matching response information found."

My code is:

st = obspy.read("pathname\ABCD.ms")
inv = read_inventory("pathname\ABCD_HHE.xml")
tr0 = st[0]
freq1=a
freq2=b
pre_filt=[0.001, 0.01, freq1, freq2]
tr.remove_response(inventory=inv, output="ACC", water_level=60, plot=True, pre_filt=pre_filt, 
                   zero_mean=True,taper=True, taper_fraction=0.05)


The error Traceback is:


ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_11048\2744217782.py in <cell line: 10>()
      8 
      9 
---> 10 tr.remove_response(inventory=inv, output="ACC", water_level=60, plot=True, pre_filt=pre_filt, 
     11                    zero_mean=True,taper=True, taper_fraction=0.05)
     12 

~\anaconda3\envs\obspy\lib\site-packages\decorator.py in fun(*args, **kw)
    230             if not kwsyntax:
    231                 args, kw = fix(args, kw, sig)
--> 232             return caller(func, *(extras + args), **kw)
    233     fun.__name__ = func.__name__
    234     fun.__doc__ = func.__doc__

~\anaconda3\envs\obspy\lib\site-packages\obspy\core\trace.py in _add_processing_info(func, *args, **kwargs)
    280     info = info % "::".join(arguments)
    281     self = args[0]
--> 282     result = func(*args, **kwargs)
    283     # Attach after executing the function to avoid having it attached
    284     # while the operation failed.

~\anaconda3\envs\obspy\lib\site-packages\obspy\core\trace.py in remove_response(self, inventory, output, water_level, pre_filt, zero_mean, taper, taper_fraction, plot, fig, **kwargs)
   2813             import matplotlib.pyplot as plt
   2814 
-> 2815         response = self._get_response(inventory)
   2816         # polynomial response using blockette 62 stage 0
   2817         if not response.response_stages and response.instrument_polynomial:

~\anaconda3\envs\obspy\lib\site-packages\obspy\core\trace.py in _get_response(self, inventories)
   2635         elif len(responses) < 1:
   2636             msg = "No matching response information found."
-> 2637             raise ValueError(msg)
   2638         return responses[0]
   2639 

ValueError: No matching response information found.

**Comment by Y-Tang99** [comment]
Ok, I understand now. Thank you! I think we should close this issue now.

**Comment by megies** [comment]
@Y-Tang99 please try to take usage questions to our [forum](https://discourse.obspy.org).. but we know that for newer users it can sometimes be hard to determine what the issue is =)
