### ISSUE TITLE
Scipy v1.9.0 renames scipy.signal.hanning to scipy.signal.hann

### ISSUE THREAD

**Issue by arkottke** [obspy/obspy#3116]
### Problem

Automated tests that use scipy v1.9.0 fail because `scipy.signal.hanning` has been removed in favor of `scipy.signal.hann` as noted in the [changelog](https://docs.scipy.org/doc/scipy/release.1.9.0.html). It seems like this has been in the works since [v1.1.0](https://docs.scipy.org/doc/scipy/release.1.1.0.html?highlight=hann).

### Proposed solution

Move to embracing the `scipy` convention by using `hann` instead of `hanning` in the code base. 

Alternatively, just make this change when calling `scipy.signal.get_window`. Note that `numpy` hasn't made this change and still uses `numpy.hanning` see this [discussion](https://github.com/numpy/numpy/issues/17303).

**Comment by liamtoney** [comment]
For anyone coming across this — the quickfix is to add the kwarg `window='hann'` to, e.g., your
```python
st.resample(...)
```
call.
