### ISSUE TITLE
XMLSyntaxError when reading station inventory with unescaped Ampersand character

### ISSUE THREAD

**Issue by martijnende** [obspy/obspy#3138]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

When reading the station inventory of the `CI.DEV` station, I get an `XMLSyntaxError`. Apparently `read_inventory` got stuck on a "&" in the description of the station:
```
<Description>N. Palm Springs, Power Line & Diablo Rds, SCE Substation</Description>
```
When I store the inventory directly in memory, I get a `TypeError` instead:
```
TypeError: Unknown format for file /tmp/obspy-cqbniban.tmp
```
When storing and reading the inventory in text format, everything works fine. My `lxml` version is `4.8.0`, installed through conda.

### Code to Reproduce

```python
from obspy.clients.fdsn import Client
from obspy import read_inventory

client = Client("IRIS")
client.get_stations(network="CI", station="DEV", filename="inventory.xml", format="xml")
inventory = read_inventory("inventory.xml", format="stationxml")
```

### Error Traceback

```Python traceback
Traceback (most recent call last):
  File "/mnt/Pollux/Deep learning/DAS/deconvolution/teleseismic/bug_xml.py", line 37, in <module>
    inventory = read_inventory("inventory2.xml", format="stationxml")
  File "/home/vanden/anaconda3/envs/py38/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/vanden/anaconda3/envs/py38/lib/python3.8/site-packages/obspy/core/util/decorator.py", line 291, in _map_example_filename
    return func(*args, **kwargs)
  File "/home/vanden/anaconda3/envs/py38/lib/python3.8/site-packages/obspy/core/inventory/inventory.py", line 91, in read_inventory
    return _generic_reader(path_or_file_object, _read, format=format,
  File "/home/vanden/anaconda3/envs/py38/lib/python3.8/site-packages/obspy/core/util/base.py", line 657, in _generic_reader
    generic = callback_func(pathnames[0], **kwargs)
  File "/home/vanden/anaconda3/envs/py38/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/vanden/anaconda3/envs/py38/lib/python3.8/site-packages/obspy/core/util/decorator.py", line 202, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "/home/vanden/anaconda3/envs/py38/lib/python3.8/site-packages/obspy/core/inventory/inventory.py", line 100, in _read
    inventory, format = _read_from_plugin('inventory', filename, format=format,
  File "/home/vanden/anaconda3/envs/py38/lib/python3.8/site-packages/obspy/core/util/base.py", line 422, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "/home/vanden/anaconda3/envs/py38/lib/python3.8/site-packages/obspy/io/stationxml/core.py", line 152, in _read_stationxml
    root = etree.parse(path_or_file_object).getroot()
  File "src/lxml/etree.pyx", line 3536, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1902, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1805, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "inventory2.xml", line 21
lxml.etree.XMLSyntaxError: xmlParseEntityRef: no name, line 21, column 48
```

### ObsPy Version?

1.3.0

### Operating System?

Linux Mint 19

### Python Version?

3.8.8

### Installation Method?

conda

**Comment by megies** [comment]
This is a problem of an illegal xml document. Ampersand (`&`) is a special character in xml/html and needs to be escaped as `&amp;` in textual output. So the problem is whoever produced this document not taking into account this fact.

```bash
$ xmllint inventory.xml 
inventory.xml:21: parser error : xmlParseEntityRef: no name
     <Description>N. Palm Springs, Power Line & Diablo Rds, SCE Substation</Desc
```

CC @chad-iris, maybe IRIS might want to check for errors like this throughout their data and make providers of the metadata aware of the issue.

**Comment by megies** [comment]
Compare e.g.:

```python
from obspy import Inventory
inv = Inventory([], 'Example & Co')
inv.write('/tmp/trash.xml', 'STATIONXML')
```

```xml
<?xml version='1.0' encoding='UTF-8'?>
<FDSNStationXML xmlns="http://www.fdsn.org/xml/station/1" schemaVersion="1.1">
  <Source>Example &amp; Co</Source>
  <Module>ObsPy 1.3.0</Module>
  <ModuleURI>https://www.obspy.org</ModuleURI>
  <Created>2022-09-16T07:30:38.985874Z</Created>
</FDSNStationXML>
```

**Comment by martijnende** [comment]
Thanks @megies. The second error I get when storing the result directly in memory (`TypeError: Unknown format for file /tmp/obspy-cqbniban.tmp`) is not very informative of this kind of problem. Is the `TypeError` raised as a consequence of the `XMLSyntaxError`, thinking that the filetype is not XML?

**Comment by megies** [comment]
Yes, basically the file goes through filetype auto-discovery and `_is_stationxml()` returns `False`. Not sure how exactly to improve this, since that is what is expected from that filetype checker.. be robust and strictly answer yes or no.

```python
            try:
                xmldoc = etree.parse(path_or_file_object)
            except etree.XMLSyntaxError:
                return False
```

**Comment by megies** [comment]
I guess we could add some workaround in `get_stations()` for when output is left default or `xml` since we dont really need filetype discovery in that case..

**Comment by martijnende** [comment]
I'd say that the filetype should not necessarily depend on its contents being syntactically correct. In the first place, XML files should have a schema declared, so if that is the case then the file creator's intention is clear. If no schema is declared, then a second attempt could be made through the file's syntax.

**Comment by megies** [comment]
I'm not sure about that, really. Strictly speaking this is not an XML file. XML parser doesn't even read it. We'd be basically writing our own mini parser, reading plain text and parsing XML headers. I don't think we want to do that.
Any software that is attempting to write XML, should make sure it's actually writing XML.

But like I said, since we expect StationXML in this case, we probably should not go through filetype discovery and just show an error trying to read StationXML.

**Comment by martijnende** [comment]
Ok, I see. Skipping filetype discovery seems like the best solution then.

**Comment by chad-iris** [comment]
Thanks for the tag.  The IRIS service has been updated to address this issue.  Now working:

```Python
In [1]: from obspy.clients.fdsn import Client
   ...: from obspy import read_inventory
   ...: 
   ...: client = Client("IRIS")
   ...: client.get_stations(network="CI", station="DEV", filename="inventory.xml", format="xml")
   ...: inventory = read_inventory("inventory.xml", format="stationxml")
   ...: 

In [2]: inventory
Out[2]: 
Inventory created at 2022-09-19T19:50:51.675700Z
	Created by: IRIS WEB SERVICE: fdsnws-station | version: 1.1.50
		    http://service.iris.edu/fdsnws/station/1/query?network=CI&station=D...
	Sending institution: IRIS-DMC (IRIS-DMC)
	Contains:
		Networks (1):
			CI
		Stations (1):
			CI.DEV (Devers)
		Channels (0):


In [3]: 
```

**Comment by megies** [comment]
Good to hear @chad-iris, thanks!

I will leave this open until we added the filetype discovery skip, which should help with showing a clearer error.

**Comment by megies** [comment]
this is getting handled and tracked in a PR, no need to keep this open anymore
