### ISSUE TITLE
client.fdsn: query POST request Content-Type

### ISSUE THREAD

**Issue by petrrr** [obspy/obspy#3139]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

During the testing of a new FDSNWS station service application a problem surfaced when we started using ObsPy's  FDSN client with bulk requests. 

When using `client.get_station_bulk()` the request is send as a POST request, with method `query` and a POST payload which is specified in the FDSN standard [1]. The format of the payload is probably best described as text, though this is not explicitly mentioned in the document [2]. 

The ObsPy client sets the HTTP header `Content-Type` to the value `application/x-www-form-urlencoded`. We concluded that this Content-Type does **not** correctly describing the content of the provided body payload. For this `Content-Type: application/x-www-form-urlencoded` we expect to receive a content of the following pattern:
```
key1=value1&key2=value2
```
These are then interpreted in a similar way as query parameters in the URL string.

The problem with setting the wrong Content-Type is that various frameworks attempt to interpret the provided payload, do not provide any data as "body", fail due to an unexpected content wrt. to the header declaration and therefore behave in an unpredictable way.  

Note: 
There is a closely related issue #2364, were the same problem was already discussed in the contest of a similar problem. I however opt to open this new which focused  specifically on the Content-Type Header provided by ObsPy's FDSN client and the provided POST body payload. 

* [1] http://fdsn.org/webservices/fdsnws-station-1.1.pdf
* [2] https://github.com/FDSN/fdsnws-station/issues/8

### Code to Reproduce

```python
from obspy.clients.fdsn import Client

bulk = [['IV', 'ACER', '*', 'BHZ,HHZ', '2021-01-01T00:00:00', '2021-12-31T00:00:00'],
        ['MN', 'AQU', '*', 'BHZ,HHZ', '2021-01-01T00:00:00', '2021-12-31T00:00:00']]

client = Client("INGV")
inv = client.get_stations_bulk(bulk)

# sniff traffic to check Header content
```

### Error Traceback

```Python traceback
none
```

### ObsPy Version?

1.3.0

### Operating System?

any, verified on macOS, Linux

### Python Version?

3.10.7 (probably not relevant)

**Comment by megies** [comment]
Can confirm, this needs to be changed

**Comment by petrrr** [comment]
@megies: Thanks for addressing the issue and for the fix.
