### ISSUE TITLE
fdsn.client: add query parameters to get_station_bulk()

### ISSUE THREAD

**Issue by petrrr** [obspy/obspy#3140]
### Problem

The get_station_bulk() method implements the FDSNWS station POST query requests. However, while the standard supports various query parameters, get_station_bulk() currently supports only a subset as key=value pairs at the start of the request body:  level, includerestriced (typo!), includeavailability.

### Proposed solution

Add query parameters supported by the standard and/or the service endpoint. 

Some extra complexity is caused by the fact that most parameters are only "optional" and the specs are not very clear about the set of supported parameters. For GET method the set of supported parameters is declared by  `application.wadl`. It is used by ObsPy to discover available parameters for an endpoint. For POST this seems not to apply and it is not clear if we can assume that the same parameters are supported by GET and POST request.

* get_station_bulk() should support at least all "required" parameters, i.e. minlatitude, maxlatitude, minlongitude, maxlongitude;

* Optional parameters includerestricted and includeavailability are already available, though they might not be supported by the service endpoint because "optional";

* format and nodata (optional) seem particularly useful.

**Comment by filefolder** [comment]
I'm probably wrong but I assumed this function was expressly for downloading a list of _known_ stations/channels, in which case having the extra search parameters is redundant (e.g. you would just use `get_stations`). Also I don't think it's an issue to make include restricted/availability mandatory as every server should have a default (NO) for this already. `Format `should probably added though as currently the method can only save as xml from the looks of it. 

typo is line 1185 of `clients/fdsn/client.py` but it looks like that's been fixed

i can push a PR in a sec...

**Comment by megies** [comment]
> Some extra complexity is caused by the fact that most parameters are only "optional" and the specs are not very clear about the set of supported parameters. For GET method the set of supported parameters is declared by `application.wadl`. It is used by ObsPy to discover available parameters for an endpoint. For POST this seems not to apply and it is not clear if we can assume that the same parameters are supported by GET and POST request.

I think we will just have to assume that the server will return a useful error message if one of the optional parameters is not accepted?

**Comment by megies** [comment]
> typo is line 1185 of `clients/fdsn/client.py` but it looks like that's been fixed

yes the typo is fixed, overlooked this issue here

**Comment by megies** [comment]
> in which case having the extra search parameters is redundant (e.g. you would just use `get_stations`

I would just argue to follow the FDSNWS specs to the letter, and it says all parameters are supposed to be put into the POST data part.

![Screenshot from 2022-10-11 15-48-58](https://user-images.githubusercontent.com/1842780/195114488-9664d9e7-78de-40d1-9f2b-c3402abc2675.png)
