### ISSUE TITLE
set_flags_in_fixed_headers: wrong use of sampling rate

### ISSUE THREAD

**Issue by etmseed** [obspy/obspy#3163]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

My code generates mseed files and calls the function `obspy.io.mseed.util.set_flags_in_fixed_headers`.
The flags to be set are of the 'DURATION' kind and I could observe in the resulting files that some records had the flags set when they should not wrt to their data dates.

I looked into the  code of this function and I think I found a buggy line. In obspy-1.3, it is in
obspy/io/mseed/util.py:1160-1163
```
                # date of the last sample is recstart+samp_rate*(nb_samples-1)
                # We assume here that a record with samples [0, 1, ..., n]
                # has a period [ date_0, date_n+1 [  AND NOT [ date_0, date_n ]
                realendtime = recstart + samp_rate * (nb_samples)
```
As far I understand it, it should be :
```
                # date of the last sample is recstart+(nb_samples-1)/samp_rate
                # We assume here that a record with samples [0, 1, ..., n]
                # has a period [ date_0, date_n+1 [  AND NOT [ date_0, date_n ]
                realendtime = recstart + nb_samples / samp_rate
```

What comforts me in this analysis is the line 814 of the same file, in the function `_get_record_information`:
```
        info['endtime'] = starttime + (npts - 1) / samp_rate
```

### ObsPy Version?

1.0.2 and 1.3 (and probably all intermediates)

### Operating System?

CentOS

### Python Version?

2.7

### Installation Method?

pip

**Comment by megies** [comment]
Without looking at the details, looks like you're correct `sampling_rate * num_samples` as time increment doesn't make sense.

**Comment by megies** [comment]
Fix is in main branches now

**Comment by etmseed** [comment]
Hi megies,
Sorry for my late reaction. I just have had a look into the main stream code and I think you did not update the comment above the faulty line. I did it in my issue description : you may reuse it if you like.
Regards.

**Comment by megies** [comment]
@etmseed done, thanks!

**Comment by etmseed** [comment]
Hi @megies,

I came back on looking on that comment because of a very low frequency I got (0.1Hz).
                # We assume here that a record with samples [0, 1, ..., n]
                # has a period [ date_0, date_n+1 [  AND NOT [ date_0, date_n ]
                realendtime = recstart + nb_samples / samp_rate
Actually, on my example, I have an event that starts between date_n and date_n+1 (a 10s range !). This way of computing the realendtime includes the start of the event and I end up with a 30-min long record flagged with the event. From a scientific point of view, it means that the whole record is not relevant because the measures were impacted by that event.
On the contrary, all of the record data were got before the event started and are thus relevant !

My understanding would be that the line should have been: 
                realendtime = recstart + (nb_samples - 1) / samp_rate
and the line 1244:
                     if(event_start <= recend) and (recstart <= event_end):
(instead of event_start < recend)

Do you happen to know the reason(s) why this deliberate choice had been made here ?

Thanks in advance...
