### ISSUE TITLE
problems reading a quakeml file

### ISSUE THREAD

**Issue by 19giovi87** [obspy/obspy#3168]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

Hi,

I'm not able to import QUAKEML file with read_events.
I tried with several different files and import these was always OK in the past.

### Code to Reproduce

```python
from obspy.core.event.catalog import read_events

file = '1553071.qml'
catalog = read_events('1553071.qml', format='QUAKEML')
```

### Error Traceback

```Python traceback
During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/var/folders/mn/3dbtdb4s54n7knrl5l5l0yfc0000gq/T/ipykernel_34408/3236540767.py", line 1, in <cell line: 1>
    catalog = read_events(os.path.join(PATH_QML_FILE,file),

  File "/Users/giovanni_work/anaconda3/envs/pygmt/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)

  File "/Users/giovanni_work/anaconda3/envs/pygmt/lib/python3.9/site-packages/obspy/core/util/decorator.py", line 291, in _map_example_filename
    return func(*args, **kwargs)

  File "/Users/giovanni_work/anaconda3/envs/pygmt/lib/python3.9/site-packages/obspy/core/event/catalog.py", line 809, in read_events
    return _generic_reader(pathname_or_url, _read, format=format, **kwargs)

  File "/Users/giovanni_work/anaconda3/envs/pygmt/lib/python3.9/site-packages/obspy/core/util/base.py", line 657, in _generic_reader
    generic = callback_func(pathnames[0], **kwargs)

  File "/Users/giovanni_work/anaconda3/envs/pygmt/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)

  File "/Users/giovanni_work/anaconda3/envs/pygmt/lib/python3.9/site-packages/obspy/core/util/decorator.py", line 202, in uncompress_file
    result = func(filename, *args, **kwargs)

  File "/Users/giovanni_work/anaconda3/envs/pygmt/lib/python3.9/site-packages/obspy/core/event/catalog.py", line 817, in _read
    catalog, format = _read_from_plugin('event', filename, format=format,

  File "/Users/giovanni_work/anaconda3/envs/pygmt/lib/python3.9/site-packages/obspy/core/util/base.py", line 410, in _read_from_plugin
    raise TypeError(msg % (format, ', '.join(eps)))

TypeError: Format "QUAKEML" is not supported. Supported types:
```

### ObsPy Version?

1.3.0

### Operating System?

macOS 11.6.8

### Python Version?

3.9

### Installation Method?

conda

**Comment by megies** [comment]
Looks like a broken installation.

What does this say:

```
from obspy.core.util.base import ENTRY_POINTS
print(ENTRY_POINTS['event'])
```

**Comment by 19giovi87** [comment]
Hi Megies,
here's the output:

`OrderedDict([('QUAKEML', EntryPoint.parse('QUAKEML = obspy.io.quakeml.core')), ('NLLOC_HYP', EntryPoint.parse('NLLOC_HYP = obspy.io.nlloc.core')), ('CMTSOLUTION', EntryPoint.parse('CMTSOLUTION = obspy.io.cmtsolution.core')), ('EVT', EntryPoint.parse('EVT = obspy.io.sh.evt')), ('FNETMT', EntryPoint.parse('FNETMT = obspy.io.nied.fnetmt')), ('FOCMEC', EntryPoint.parse('FOCMEC = obspy.io.focmec.core')), ('GSE2', EntryPoint.parse('GSE2 = obspy.io.gse2.bulletin')), ('HYPODDPHA', EntryPoint.parse('HYPODDPHA = obspy.io.hypodd.pha')), ('IMS10BULLETIN', EntryPoint.parse('IMS10BULLETIN = obspy.io.iaspei.core')), ('MCHEDR', EntryPoint.parse('MCHEDR = obspy.io.pde.mchedr')), ('NDK', EntryPoint.parse('NDK = obspy.io.ndk.core')), ('NORDIC', EntryPoint.parse('NORDIC = obspy.io.nordic.core')), ('SC3ML', EntryPoint.parse('SC3ML = obspy.io.seiscomp.event')), ('SCARDEC', EntryPoint.parse('SCARDEC = obspy.io.scardec.core')), ('ZMAP', EntryPoint.parse('ZMAP = obspy.io.zmap.core'))])`

**Comment by megies** [comment]
Can you run `obspy-runtests` on command line and send the report to server?

**Comment by 19giovi87** [comment]
How do I send the report to server?

**Comment by filefolder** [comment]
could you also attach your 1553071.qml file here, or a small example that produces the error?

**Comment by megies** [comment]
> How do I send the report to server?

Run `obspy-runtests`, answer "yes" at the end.

**Comment by 19giovi87** [comment]
> could you also attach your 1553071.qml file here, or a small example that produces the error?
Here it is
[1553071.qml.zip](https://github.com/obspy/obspy/files/9763232/1553071.qml.zip)

**Comment by 19giovi87** [comment]
> > How do I send the report to server?
> 
> Run `obspy-runtests`, answer "yes" at the end.

Ok, done.
https://tests.obspy.org/128164/

Thank you

**Comment by filefolder** [comment]
> > could you also attach your 1553071.qml file here, or a small example that produces the error?
> 
> Here it is [1553071.qml.zip](https://github.com/obspy/obspy/files/9763232/1553071.qml.zip)

Thanks.. I can read it fine. I have re-rewritten the catalog on my machine in case something happened in the initial write process. The only thing possibly unusual it is the encoding and the standalone="yes" tag in the header which I am not accustomed to seeing in these ex `<?xml version="1.0" encoding="US-ASCII" standalone="yes"?>`

[1553071_rewritten.qml.txt](https://github.com/obspy/obspy/files/9763674/1553071_rewritten.qml.txt)

**Comment by megies** [comment]
@19giovi87 well, I don't see any problems with your installation and I can read the file just fine, so no idea what happened. Only thing I can think of right now is you were using a different Python environment when trying to read that file with a broken obspy installation

**Comment by 19giovi87** [comment]
> @19giovi87 well, I don't see any problems with your installation and I can read the file just fine, so no idea what happened. Only thing I can think of right now is you were using a different Python environment when trying to read that file with a broken obspy installation

Right, that was the problem. I thought I was using the usual conda enviroment but apparently something was messed up with spyder.

Thanks a lot for your help!
