### ISSUE TITLE
possible aliasing in trace.downsample

### ISSUE THREAD

**Issue by trac2github** [obspy/obspy#318]
During the integer decimation of trace.downsample a lowpass
is constructed with 4 corners at 0.4 \* samplerate / decimation_factor.
In an example of a 200 Hz seismogram with an integer decimation of 2
the new nyquist frequency will be at 50 Hz. Using the lowpass constructed
by trace.downsample, the frequency response of this filter will be attenuated
by 11.5 dB at this new nyquist frequency.

I am now used to lowpass filters with 65 to 95 dB attenuation at the new nyquist frequency to avoid aliasing during integer decimation.
Does anyone have other opinions / experience?

[[Image(lowpass4intdecimation.png)]]

``` python
#!python
from __future__ import division
import numpy as np
import scipy.signal as sg
import matplotlib.pyplot as plt

sampling_rate = 200
decimation_factor = 2
# calculate lower corner frequency (obspy.core.trace.py:1299)
low_corner = 0.4 * sampling_rate / decimation_factor

corners = 4  # obspy.signal.filter.py:104
# calculate b, a for filter obspy.signal.filter.py:120-130
nyquist = sampling_rate * 0.5
[b, a] = sg.iirfilter(corners, low_corner/nyquist, btype='lowpass', ftype='butter',
                      output='ba')
# calculate frequency response
w, h = sg.freqz(b, a, int(nyquist))
freq = w/np.pi * nyquist

new_nyquist = sampling_rate/decimation_factor*.5
plt.plot(freq, 20*np.log10(abs(h)))
plt.title('Lowpass @ %3.1f Hz, New Nyquist %3.1f' % (low_corner,
  new_nyquist))
plt.axvline(new_nyquist)
plt.xlabel('Frequency [Hz]')
plt.ylabel('Magnitude [dB]')
plt.show()                   
```

**Comment by liamtoney** [comment]
The plot created by the code in https://github.com/obspy/obspy/issues/318#issuecomment-8407108 is attached below for anyone else looking for it. Perhaps this plot could be embedded in [the docs for `lowpass_cheby_2()`](https://docs.obspy.org/packages/autogen/obspy.signal.filter.lowpass_cheby_2.html#obspy.signal.filter.lowpass_cheby_2) for convenience? Currently there's just a non-linked reference to this issue number.

![rs95.png](https://user-images.githubusercontent.com/38269494/148611161-4b9664fc-9064-4a2e-8f54-82b1789f1379.png)
