### ISSUE TITLE
No package for debian stable (bullseye)

### ISSUE THREAD

**Issue by N7DR** [obspy/obspy#3181]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

https://github.com/obspy/obspy/wiki/Installation-on-Linux-via-Apt-Repository says:
  ObsPy is packed (sic) for all Debian and Ubuntu releases which are still officially supported

However, there is no .deb package for current debian stable (bullseye).

(As a result, my scripts for examining magnetometer data are no longer working.)

### ObsPy Version?

unable to install

### Operating System?

debian

### Python Version?

3.9.2

**Comment by megies** [comment]
> ObsPy is packed (sic) for all Debian and Ubuntu releases which are still officially supported

Sadly, I had to abandon Deb/untu packaging efforts after the (quite messy) packaging setup broke for a new distro and I couldn't figure out how to fix the build in 1-2 afternoons and could not spend more time on it. Sadly, Python packaging for Debian is not as well documented as you'd like, or I'm just not using the right pieces of information. And it is very annoying to debug problems in the packaging.

Any help with packaging is welcome, but until then probably there will be no packages.

As a workaround if you want to use the system Python, you can add ObsPy by installing it with `/usr/bin/pip3`, it will go into a separate directory that is different from the directory where `apt` installed packages are held, so even if not ideal, this is actually not as messy as you'd think.

Just make sure to have all dependencies installed via `apt`, then pip will not have to install anything else besides obspy itself (sadly the pip version in bullseye doesn't have "dry-run" yet, but if you miss a dependency you could just delete /usr/local/lib/python3.9 and start over):

```bash
# aptitude install python3-pip python3-numpy python3-scipy python3-matplotlib python3-lxml python3-setuptools python3-sqlalchemy python3-decorator python3-requests python3-packaging python3-pyproj python3-pytest python3-geographiclib python3-cartopy python3-pyshp python3-ipython ipython3
```

(or just as a regular user with `/usr/bin/pip3` which should go into `~/.local` I think)

![Screenshot from 2022-10-18 13-16-45](https://user-images.githubusercontent.com/1842780/196418834-37df7a28-f275-4490-becd-d17342d3312e.png)
![Screenshot from 2022-10-18 13-16-12](https://user-images.githubusercontent.com/1842780/196418838-b6ba30e6-4d24-4638-b12f-9bd9820b83ac.png)
![Screenshot from 2022-10-18 13-16-59](https://user-images.githubusercontent.com/1842780/196418842-b116160e-34a4-419d-a7b0-2f5622d040c8.png)

**Comment by N7DR** [comment]
Tobias Megies wrote on 10/18/22 05:40:
>> ObsPy is packed (sic) for all Debian and Ubuntu releases which are still officially supported
> 
> Sadly, I had to abandon Deb/untu packaging efforts after the (quite messy) packaging setup broke for a new distro and I couldn't figure out how to fix the build in 1-2 afternoons and could not spend more time on it. Sadly, Python packaging for Debian is not as well documented as you'd like, or I'm just not using the right pieces of information. And it is very annoying to debug problems in the packaging.
> 
> Any help with packaging is welcome, but until then probably there will be no packages.
> 

Packaging anything in debian is voodoo magic as far as I'm concerned. I looked 
into it once for a couple of my own projects and after floundering for an hour 
or so and getting deeper and deeper into a rat-hole I just gave up and figured 
that if people want to run anything of mine they can download it from githib 
and type "make".

> As a workaround if you want to use the system Python, you can add ObsPy by installing it with `/usr/bin/pip3`, it will go into a separate directory that is different from the directory where `apt` installed packages are held, so even if not ideal, this is actually not as messy as you'd think.
> 
> Just make sure to have all dependencies installed via `apt`, then pip will not have to install anything else besides obspy itself (sadly the pip version in bullseye doesn't have "dry-run" yet, but if you miss a dependency you could just delete /usr/local/lib/python3.9 and start over):
> 
> ```bash
> # aptitude install python3-pip python3-numpy python3-scipy python3-matplotlib python3-lxml python3-setuptools python3-sqlalchemy python3-decorator python3-requests python3-packaging python3-pyproj python3-pytest python3-geographiclib python3-cartopy python3-pyshp python3-ipython ipython3
> ```
> 
> (or just as a regular user with `/usr/bin/pip3` which should go into `~/.local` I think)
> 
> ![Screenshot from 2022-10-18 13-16-45](https://user-images.githubusercontent.com/1842780/196418834-37df7a28-f275-4490-becd-d17342d3312e.png)
> ![Screenshot from 2022-10-18 13-16-12](https://user-images.githubusercontent.com/1842780/196418838-b6ba30e6-4d24-4638-b12f-9bd9820b83ac.png)
> ![Screenshot from 2022-10-18 13-16-59](https://user-images.githubusercontent.com/1842780/196418842-b116160e-34a4-419d-a7b0-2f5622d040c8.png)
> 

All done, with no errors that I noticed. I hope to have a chance to test it 
all tomorrow.

Thank you VERY much. I'd never have figured it out without your assistance.

   Doc

-- 
Web:  http://enginehousebooks.com/drevans

**Comment by N7DR** [comment]
D. R. Evans wrote on 10/18/22 14:51:
> Tobias Megies wrote on 10/18/22 05:40:

> 
>> As a workaround if you want to use the system Python, you can add ObsPy by installing it with `/usr/bin/pip3`, it will go into a separate directory that is different from the directory where `apt` installed packages are held, so even if not ideal, this is actually not as messy as you'd think.
>>
>> Just make sure to have all dependencies installed via `apt`, then pip will not have to install anything else besides obspy itself (sadly the pip version in bullseye doesn't have "dry-run" yet, but if you miss a dependency you could just delete /usr/local/lib/python3.9 and start over):
>>
>> ```bash
>> # aptitude install python3-pip python3-numpy python3-scipy python3-matplotlib python3-lxml python3-setuptools python3-sqlalchemy python3-decorator python3-requests python3-packaging python3-pyproj python3-pytest python3-geographiclib python3-cartopy python3-pyshp python3-ipython ipython3
>> ```
>>
>> (or just as a regular user with `/usr/bin/pip3` which should go into `~/.local` I think)
>>
>> ![Screenshot from 2022-10-18 13-16-45](https://user-images.githubusercontent.com/1842780/196418834-37df7a28-f275-4490-becd-d17342d3312e.png)
>> ![Screenshot from 2022-10-18 13-16-12](https://user-images.githubusercontent.com/1842780/196418838-b6ba30e6-4d24-4638-b12f-9bd9820b83ac.png)
>> ![Screenshot from 2022-10-18 13-16-59](https://user-images.githubusercontent.com/1842780/196418842-b116160e-34a4-419d-a7b0-2f5622d040c8.png)
>>
> 
> All done, with no errors that I noticed. I hope to have a chance to test it
> all tomorrow.
> 

FYI, python3-pydantic also needs to be installed.

Having installed that package, it all seems to work. Thank you again.

   Doc

-- 
Web:  http://enginehousebooks.com/drevans

**Comment by megies** [comment]
> python3-pydantic also needs to be installed

It's not one of our dependencies so it must be a dependency of some other package you're using

**Comment by N7DR** [comment]
Tobias Megies wrote on 10/20/22 02:08:
>> python3-pydantic also needs to be installed
> 
> It's not one of our dependencies so it must be a dependency of some other package you're using
> 

My command line:
 
/home/n7dr/Downloads/programs/geomag-algorithms-221017/geomag-algorithms-master/bin/geomag.py 
  --input edge  --inchannels H D Z F  --observatory BOU  --starttime 
2022-10-19T16:12:16Z  --endtime 2022-10-19T18:12:16Z --output iaga2002 
--outchannels H D Z F  --output-file /tmp/magnetometer-bou.tmp
   says it requires python3-pedantic.

I guess that geomag.py is the cause; the installation instructions for that 
don't include python3-pedantic (it just says numpy and obspy), but perhaps 
they are incomplete.

   Doc

-- 
Web:  http://enginehousebooks.com/drevans
