### ISSUE TITLE
How to change the color and symbols of events in a one-day plot ?

### ISSUE THREAD

**Issue by HuiLIU1121** [obspy/obspy#3190]
Hello, I am a beginner of obspy. I have a problem need to be solved now.

`st2.plot(type='dayplot', fig=fig, events=list(load_events));`

The code I attached can only plot the events using yellow stars which is based on the stream.plot() function. What if I want to change the symbols and color of events in a one-day plot? 

Thank you~

**Comment by megies** [comment]
Please use our forum for usage / Python questions like this.

This can not be controlled via obspy, but you can prevent the figure from immediately showing up and then make further changes through matplotlib API.

```python
fig = plt.figure()
st.plot(type="dayplot", fig=fig, show=False)
# more tweaks here, the event stars are in one of "fig.axes[..].lines[..]", set_marker() is what you want to look for
plt.show()
```
