### ISSUE TITLE
Can obspy remove spikes? like using median filter or so?

### ISSUE THREAD

**Issue by JUNZHU-SEIS** [obspy/obspy#3195]
### Problem

I process marine data, which include many spikes.
Is there any standard workflow to remove those spikes?

**Comment by filefolder** [comment]
There is a lot of subjective considerations and/or "art" to this so I doubt something will ever be officially introduced. 

In essence it comes down to 1) identifying which samples are anomalous 2) removing and interpolating them. The second part is relatively straightforward. The first part, I have found that identifying spikes can usually be done by calculating the standard deviation of scatter in the waveform data relative to some lowpass filtered version, and then presuming that spikes will be greater than ~4 times (e.g. 4x sigma) of this, but it really depends on the data and the nature of the spiking.

**Comment by trichter** [comment]
SciPy has a handy `find_peaks` function which is by the way internally used by ObsPy's `correlation_detector`.

**Comment by megies** [comment]
Please use our forum for questions like this in the future, so that ideally the community can chime in and not only the main developers, @JUNZHU-SEIS 

https://discourse.obspy.org/
