### ISSUE TITLE
CI broken

### ISSUE THREAD

**Issue by d-chambers** [obspy/obspy#3198]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

It appears the current CI installation is not sufficient to resolve all of the deps for testing. See [here](https://github.com/obspy/obspy/actions/runs/3337526220/jobs/5523982383).

I can reproduce this issue locally by using the appropriate env file in the .github folder and installing obspy with 

```bash
pip install . --no-deps
```

However, if I replace the no deps with an editable installation everything works fine

```bash
pip install  -e .
```

I think this was mentioned in #3176  but I didn't follow that thread completely. Any ideas why this is setup this way @trichter  or @megies ?

### Installation Method?

developer installation / from source / git checkout

**Comment by trichter** [comment]
I think this error is due to a bug in pytest-metadata, see https://github.com/pytest-dev/pytest-metadata/issues/54. The new version of this package fixing the bug is available on pypi, but not yet in conda. I expect the `pip install` without `--no-deps` dwonloads the latest version from pypi and overwrites the version installed by conda.

**Comment by d-chambers** [comment]
Ah, great thanks @trichter you are on the ball. 

I opened an issue with the conda-forge feedstock to see if the maintainers would be willing to push out a new version. Hopefully when that happens the issue will be resolved.

**Comment by d-chambers** [comment]
The conda-forge maintainers of pytest-metadata released a new version and CI appears to work again. For reference, [here](https://github.com/pytest-dev/pytest/pull/10396) is the relevant pytest PR which explains that parts of the py library are now vendor-ed and other parts not, hence why an attribute error is raised rather than an import error in older versions of pytest-metadata.
