### ISSUE TITLE
Problem connecting to UIB/NORSAR FDSNWS

### ISSUE THREAD

**Issue by megies** [obspy/obspy#3200]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

Failing to connect to UIB/NORSAR FDSNWS, more details see [forum post](https://discourse.obspy.org/t/meet-problems-when-using-massdownloader-to-download-data/1540/2).

Looks like the web server is rewriting some URLs we try to lookup, problems with a redirect?

@alanfbaird @Erik-BM I see you as members of @NorwegianSeismicArray.. any chance you might now who to make aware of this issue?

### Code to Reproduce

```python
from obspy.clients.fdsn import Client
client = Client("UIB-NORSAR")
```

### Error Traceback

```Python traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 client = Client("UIB-NORSAR")

File ~/miniconda3/envs/default/lib/python3.10/site-packages/obspy/clients/fdsn/client.py:277, in Client.__init__(self, base_url, major_versions, user, password, user_agent, debug, timeout, service_mappings, force_redirect, eida_token, _discover_services)
    274     print("Request Headers: %s" % str(self.request_headers))
    276 if _discover_services:
--> 277     self._discover_services()
    278 else:
    279     self.services = DEFAULT_SERVICES

File ~/miniconda3/envs/default/lib/python3.10/site-packages/obspy/clients/fdsn/client.py:1549, in Client._discover_services(self)
   1547         print("Discovered dataselect service")
   1548 elif "event" in url and "application.wadl" in url:
-> 1549     self.services["event"] = WADLParser(wadl).parameters
   1550     if self.debug is True:
   1551         print("Discovered event service")

File ~/miniconda3/envs/default/lib/python3.10/site-packages/obspy/clients/fdsn/wadl_parser.py:87, in WADLParser.__init__(self, wadl_string)
     84         else:
     85             msg = "Could not parse the WADL at '%s'. Invalid WADL?" \
     86                 % url
---> 87             raise ValueError(msg)
     89 if not parameters:
     90     msg = "Could not find any parameters"

ValueError: Could not parse the WADL at 'http://eida.geo.uib.no/nnsn_eqcat/fdsnws/event/1/'. Invalid WADL?
```

### ObsPy Version?

1.3.1

### Operating System?

Linux

### Python Version?

3.10.5

### Installation Method?

conda

**Comment by paitor** [comment]
@megies  Lars Ottemöller is listed as contact person on https://www.fdsn.org/datacenters/detail/UIB-NORSAR/

**Comment by megies** [comment]
> @megies Lars Ottemöller is listed as contact person on https://www.fdsn.org/datacenters/detail/UIB-NORSAR/

I sent out an email :+1:

**Comment by jan-michalek** [comment]
Hi, UIB tried to redirect the FDSNWS EVENT service (which is running on different server) to the same server where DATASELECT and STATION services are running. It didn't go well so UIB reverted to original configuration. I believe this issue can be closed.

**Comment by megies** [comment]
> Hi, UIB tried to redirect the FDSNWS EVENT service (which is running on different server) to the same server where DATASELECT and STATION services are running. It didn't go well so UIB reverted to original configuration. I believe this issue can be closed.

Yes, looks like event service was removed and everything working. I think the setup could've worked though, just that redirect forcing the URL to get changed on client side needed changing I think, but it's been a while meddling with web server config, so can't say for sure
