### ISSUE TITLE
Raising FDSNTooManyRequestsException in error handling typo

### ISSUE THREAD

**Issue by fabgiamp** [obspy/obspy#3219]
Hello,
according to this code, present also in the current version (1.3.1):

https://github.com/obspy/obspy/blob/0d77efd744c8aa6fc8bb9ac2fe367cbc86b1656b/obspy/clients/fdsn/client.py#L1836-L1838

the first argument of the mentioned exception appears to be a tuple. This causes a TypeError when effectively too many requests are done and the FDSNTooManyRequestsException raises:

```
TypeError: sequence item 0: expected str instance, tuple found
```
It seems to be a small typo since the other exceptions have simple strings as first argument.

**Comment by megies** [comment]
> It seems to be a small typo since the other exceptions have simple strings as first argument.

yep seems like a copy-paste problem. Thanks!
