### ISSUE TITLE
seedlink basic_client always runs get_info

### ISSUE THREAD

**Issue by raciner** [obspy/obspy#3231]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

in clients/seedlink/basic_client.py, Line 132

`if any('*' in x for x in (network, station, location, channel)) \`
 `               or ('?' in x for x in (network, station)):` 
            
always evaluates to true, so self.get_info will be called no matter what.

What's actually needed is:

`if any('*' in x for x in (network, station, location, channel)) \` 
`                 or any('?' in x for x in (network, station)):` 

### ObsPy Version?

current master

### Installation Method?

None

**Comment by megies** [comment]
Oooops! Nice catch!

**Comment by QuLogic** [comment]
Fixed by #3232
