### ISSUE TITLE
Sudden AttributeError: 'numpy.float64' object has no attribute 'split' error when importing Obspy inside Docker Container

### ISSUE THREAD

**Issue by MarcoEsposito890** [obspy/obspy#3260]
### Avoid duplicates

- [ ] I searched existing issues

### Bug Summary

Hello, 

I was running a Python script using the Obspy library inside a Docker container. I have now rebuilt a new container with (more or less) the same script and dependencies, but I get this error on import

AttributeError: 'numpy.float64' object has no attribute 'split' 

which didn't happen before. I have searched the issue and I saw it might depend on Python/numpy versions. At the moment I'm unable to fix it by upgrading or downgrading the libraries.

My Dockerfile

FROM continuumio/miniconda3

RUN mkdir src
WORKDIR src/
COPY . .

RUN /bin/bash && \
        conda config --add channels conda-forge && \
    conda init bash && \
    . ~/.bashrc && \
    conda create -n obspy python=3.9 && \
    conda activate obspy

RUN conda install obspy

EXPOSE 1883

CMD python3 script.py

### Error Traceback

```Python traceback
Traceback (most recent call last):
ClientMQTT          |   File "/src/client_mqtt_SHM_multisensors.py", line 9, in <module>
ClientMQTT          |     from obspy import Stream, Trace, read
ClientMQTT          |   File "/opt/conda/lib/python3.9/site-packages/obspy/__init__.py", line 39, in <module>
ClientMQTT          |     from obspy.core.utcdatetime import UTCDateTime  # NOQA
ClientMQTT          |   File "/opt/conda/lib/python3.9/site-packages/obspy/core/__init__.py", line 124, in <module>
ClientMQTT          |     from obspy.core.utcdatetime import UTCDateTime  # NOQA
ClientMQTT          |   File "/opt/conda/lib/python3.9/site-packages/obspy/core/utcdatetime.py", line 27, in <module>
ClientMQTT          |     from obspy.core.util.deprecation_helpers import ObsPyDeprecationWarning
ClientMQTT          |   File "/opt/conda/lib/python3.9/site-packages/obspy/core/util/__init__.py", line 27, in <module>
ClientMQTT          |     from obspy.core.util.base import (ALL_MODULES, DEFAULT_MODULES,
ClientMQTT          |   File "/opt/conda/lib/python3.9/site-packages/obspy/core/util/base.py", line 36, in <module>
ClientMQTT          |     from obspy.core.util.misc import to_int_or_zero, buffered_load_entry_point
ClientMQTT          |   File "/opt/conda/lib/python3.9/site-packages/obspy/core/util/misc.py", line 214, in <module>
ClientMQTT          |     loadtxt(np.array([0]), ndmin=1)
ClientMQTT          |   File "/opt/conda/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1086, in loadtxt
ClientMQTT          |     ncols = len(usecols or split_line(first_line))
ClientMQTT          |   File "/opt/conda/lib/python3.9/site-packages/numpy/lib/npyio.py", line 977, in split_line
ClientMQTT          |     line = line.split(comment, 1)[0]
ClientMQTT          | AttributeError: 'numpy.int64' object has no attribute 'split'
```

### ObsPy Version?

1.2.2

### Operating System?

Ubuntu

### Python Version?

3.9

### Installation Method?

conda

**Comment by ThomasLecocq** [comment]
please mention the numpy version on both sides, this is most likely due to changes in the API

**Comment by MarcoEsposito890** [comment]
> please mention the numpy version on both sides, this is most likely due to changes in the API

the numpy version is 1.22.3

**Comment by ThomasLecocq** [comment]
obspy version "1.2.2" is the culprit, update to latest !

**Comment by MarcoEsposito890** [comment]
> obspy version "1.2.2" is the culprit, update to latest !

Oh thanks, it was that simple. Sorry for the inconvenience

**Comment by megies** [comment]
another duplicate of #2912
