### ISSUE TITLE
Calculate Probability Density Functions (PDF) using Obspy

### ISSUE THREAD

**Issue by kozan88** [obspy/obspy#3268]
Hello,
I am trying to generate Probability Density Functions (PDF) for local seismic stations. 
I am a little confused about that. I have read that Obspy can generate Probabilistic Power Spectral Densities (PPSDs). Is it the same?
The figure below is an example of PDF;
![image](https://user-images.githubusercontent.com/115682049/221168068-92b99a69-429e-4cf3-9e96-6cf54589ce04.png)

The other is for PPSD plotted by Obspy;
![image](https://user-images.githubusercontent.com/115682049/221168230-f89deaeb-e6fc-434e-a571-4687ccc06ef2.png)

I need to plot PDFs for local seismic station (Figure 1)

**Comment by trichter** [comment]
Answered in the forum

**Comment by kozan88** [comment]
I could not find it, could you please send me the link of question in the forum?

**Comment by trichter** [comment]
https://discourse.obspy.org/t/calculating-ppsd-for-sac-data
