### ISSUE TITLE
Xseed parser does not allow reading mutiple blockette 55 into ResponseListResponseStage object

### ISSUE THREAD

**Issue by isbreen** [obspy/obspy#3275]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

Posted this in the obspy forum and thanks for the answer @megies 

I copied it here for further potential discussion and added test files. Have a fix that seems to work and will add a PR.

I stumbled over a (legacy) dataless seed response file where the responses are defined as frequency, amplitude, phase list (FAP) values.

The issue: Obspy read_inventory() reads only the first part of the FAP list. It turned out that multiple blockette 55 entries existed dividing the FAP response into different subsequent frequency ranges.

According to the SEED manual this is allowed: “…This blockette could exceed the maximum of 9999 characters. If so, continue with another blockette [55] on the next record. Set field 3 the same, but ignore fields 4 and 5 in subsequent blockettes.”

It seems in obspy.io.xseed.parser this is not taken into account, i.e. only the first blockette 55 is read for each channel in the dataless seed file.

Test files attached include a anonymized inventory of the station (because I am not sure if it can be shared). If you open the stationxml you see that the FAP list goes until 10 Hz. If you read the seed file with obspy it stops at 3 Hz.

[test_files.zip](https://github.com/obspy/obspy/files/10908028/test_files.zip)

(I create the xml file after I fixed the seed parser)

### Code to Reproduce

```python
inv=read_inventory('dummy_test_station.seed')
print(inv)
for stage in inv[0][0][0].response.response_stages:
    for f in stage.response_list_elements: print(f.frequency)
```

### ObsPy Version?

1.3.0

### Operating System?

Linux

### Python Version?

3.10.4

### Installation Method?

conda

**Comment by megies** [comment]
Ah you have some test files here. Could you make them a bit smaller though for inclusion in the PR? For testing purposes it should be enough to have just a few value pairs in each blockette.

**Comment by isbreen** [comment]
> 

I'm afraid this is not so easy. I can edit the response in the station xml (or the response object in obspy). But there I cannot control how many value pairs go into a blockette. This is done by the xml2seed conversing program (I use the java stationxml-seed-converter from IRIS). When I remove too many pairs in the xml, the seed file would have only a single blockette and then it does not qualify as a test file. The only thing I can do is to reduce to two blockettes.

**Comment by megies** [comment]
[dummy_b55_1024.seed.txt](https://github.com/obspy/obspy/files/10970386/dummy_b55_1024.seed.txt)

@isbreen i did some manual tinkering and used your file to change it to a file with 2 blockettes 55 with 3 value pairs each and also reduced the record length to 1024 bytes, to reduce bloat in the first two records, see attached file

```python
inv = read_inventory("dummy_b55_1024.seed")
resp = inv[0][0][0].response
stage = resp.response_stages[0]
for elem in stage.response_list_elements:
    print(elem.frequency, elem.amplitude, elem.phase)
```

```
0.1172 0.00138495 -5.0
0.1367 0.00247239 -7.5
0.1563 0.00422287 -8.78
3.3594 68.5493 -167.3
3.3789 69.3155 -167.44
3.3984 70.134 -167.56
```
