### ISSUE TITLE
Adding capacity to use fdsnws-availability webservice

### ISSUE THREAD

**Issue by jschaeff** [obspy/obspy#3278]
### Problem

EIDA nodes are progressively deploying `fdsnws-availability` webservice. It's going to be also advertised in the routing system.

It would be marvelous if obspy could be a client for this new webservice which is already deployed at ODC and RESIF.
It would also allow the `Client.get_waveforms()` to be smarter and check availability of data before issuing a dataselect query or adapt the parameters of the query to the availability advertised by this new webservice.

**Comment by megies** [comment]
see #3002

**Comment by jschaeff** [comment]
Great I can see some on going work there. I'll follow it.

Thanks for the ref.
