### ISSUE TITLE
Request: more responses in obspy.signal.seismometer

### ISSUE THREAD

**Issue by trac2github** [obspy/obspy#328]
Hi, all.  I think obspy.signal.seismometer is potentially quite useful, but there's only Wood-Anderson response information in there currently.  The PASSCAL Center at New Mexico Tech maintains a page with many other instrument response parameters.  Could these be added?  I'm happy to try to put together the dictionaries!  Also, with additional responses, perhaps a better way to look them up is called for (a dictionary of dictionaries, so that one can search the keys?).

Best,
Jonathan

http://www.passcal.nmt.edu/content/instrumentation/sensors/sensor-comparison-chart

**Comment by megies** [comment]
I think this can be closed.. maintaining yet another list of seismometer response info makes no sense IMHO. If anything we should build a client to retrieve from [NRL](http://ds.iris.edu/NRL/) but thats no simple task I think.
