### ISSUE TITLE
fatal error: 'stdlib.h' file not found

### ISSUE THREAD

**Issue by wuhongsheng** [obspy/obspy#3293]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

I try pip install  obspy==1.4.0 output error info :
 creating build/temp.macosx-13-x86_64-3.11
    creating build/temp.macosx-13-x86_64-3.11/src
    creating build/temp.macosx-13-x86_64-3.11/src/lxml
    clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/opt/ruby/include -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/Users/whs/CLionProjects/806a2/venv/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/lxml/etree.c -o build/temp.macosx-13-x86_64-3.11/src/lxml/etree.o -w -flat_namespace
    In file included from src/lxml/etree.c:96:
    /usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11/Python.h:23:12: fatal error: 'stdlib.h' file not found
    #  include <stdlib.h>
               ^~~~~~~~~~
    1 error generated.
    Compile failed: command '/usr/local/opt/llvm@14/bin/clang' failed with exit code 1
    cc -I/usr/include/libxml2 -c /var/folders/g1/b8c35tf50r3937_qx1nxh0p40000gn/T/xmlXPathInites9m0o1k.c -o var/folders/g1/b8c35tf50r3937_qx1nxh0p40000gn/T/xmlXPathInites9m0o1k.o
    clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=13'
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    Perhaps try: xcode-select --install
    *********************************************************************************
    error: command '/usr/local/opt/llvm@14/bin/clang' failed with exit code 1
    ----------------------------------------

### ObsPy Version?

1.4.0

### Installation Method?

None

**Comment by calum-chamberlain** [comment]
Thanks for posting your issue - can you please fill out the rest of the contents of the form. Specifically knowing exactly what OS you are running would help in replicating your issue.

Note that as detailed in the [installation wiki](https://github.com/obspy/obspy/wiki#installation), obspy strongly recommends installing via anaconda or conda to avoid issues like this. Is there a good reason for you not to go down this route?

If you do need to persist with a pip install then you should make sure that you have the dependencies you need installed. Did you try the suggested fix provided by the error message (`xcode-select --install`) to make sure that libxml2 is installed?

**Comment by QuLogic** [comment]
> src/lxml/etree.c

This is failing to build `lxml`; it is not an ObsPy problem.
