### ISSUE TITLE
One data is added when reading 0.5 byte data in WIN format

### ISSUE THREAD

**Issue by TazawaK17** [obspy/obspy#3309]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

I, Tazawa Kota, and Shimizu Toshiya report some bugs in obspy.
When reading the WIN format, there were occasional outputs of more than 6000 samples of data from a 60-second period file at 100 Hz. Therefore, we examined the relevant code in obspy/io/win/core.py and discovered three bugs.

1. When the data is 0.5 byte datawide and the sampling frequency is even, the code reads surplus 0.5 byte data at the end.
2. The shift operation have to be performed at first, but addition is performed before it.
3. The size of integer data in Python is not being considered. The shift operation has be not functioning.

obspy/io/win/core.py lines 132 -> 140
```
                if datawide == 0.5:
                    for i in range(xlen):
                        idata2 = output[chanum][-1] + \
                            from_buffer(sdata[i:i + 1], np.int8)[0] >> 4
                        output[chanum].append(idata2)
                        idata2 = idata2 +\
                            (from_buffer(sdata[i:i + 1],
                                         np.int8)[0] << 4) >> 4
                        output[chanum].append(idata2)
```

The following is the code we have modified.

```
                if datawide == 0.5:
                    for i in range(xlen):
                        # 2
                        idata2 = output[chanum][-1] + \
                            (from_buffer(sdata[i:i + 1], 
                                         np.int8)[0] >> 4)
                        output[chanum].append(idata2)
                        # 3
                        lower4 = from_buffer(sdata[i:i + 1],
                                         np.int8)[0] & 0xF
                        if lower4 & 0x8:
                            lower4 -= 0x10
                        idata2 = idata2 + lower4
                        # 1
                        if i == xlen-1 and srate % 2 == 0:
                            break
                        output[chanum].append(idata2)
```

### Code to Reproduce

```python
from obspy import read

# 1 minute data in a file
# There is one 0.5 byte data at f113 in this file
st = read("1070533011_1701260003.win")

for tr in st:
    print(tr)

"""
output---------------
...f111 | 2017-01-26T00:03:00.000000Z - 2017-01-26T00:03:59.990000Z | 100.0 Hz, 6000 samples
...f112 | 2017-01-26T00:03:00.000000Z - 2017-01-26T00:03:59.990000Z | 100.0 Hz, 6000 samples
...f113 | 2017-01-26T00:03:00.000000Z - 2017-01-26T00:04:00.000000Z | 100.0 Hz, 6001 samples
---------------------
                                                                                  ^here
"""
```

### ObsPy Version?

1.4.0

### Operating System?

windows11

### Python Version?

3.10.6

### Installation Method?

pip

**Comment by d-chambers** [comment]
Hi @TazawaK17, thank you for your detailed bug report and proposed fixes. Two questions:

1. Can you upload the file you reference in your example so we can reproduce the issue? 

2. Do you feel comfortable submitting a PR with your proposed changes?

**Comment by TazawaK17** [comment]
Here are the answers:

1. The file is included in the ZIP file attached to this form.　The ZIP file contains a WIN file and before-and-after fix waveform images.
2. I am not yet familiar with using GitHub, so it may take a little time, but I will give it a try.

[sample_WIN.zip](https://github.com/obspy/obspy/files/11684279/sample_WIN.zip)

**Comment by TazawaK17** [comment]
Here are the answers:

1. The file is included in the ZIP file attached to this form. The ZIP file contains a WIN file and before-and-after fix waveform images.
2. I am not yet familiar with using GitHub, so it may take a little time, but I will give it a try.

[sample_WIN.zip](https://github.com/obspy/obspy/files/11699446/sample_WIN.zip)

**Comment by d-chambers** [comment]
Hey @TazawaK17, I am a little bit confused by the difference between the `1701260003_afterFix.png` and `1701260003_beforeFix.png` images. In beforeFix there is clearly an event around 3:52 on station f113. This doesn't show in the afterFix. What am I missing here? 

![image](https://github.com/obspy/obspy/assets/11671536/0031941c-15bc-460c-9abc-69bcc46008b8)
![image](https://github.com/obspy/obspy/assets/11671536/5cb0e4c7-68e9-44c9-b5c4-a34d717cf678)

**Comment by d-chambers** [comment]
I can reproduce the images with the current maintenance_1.4.x branch and @TazawaK17's maintenance_1.4.x. Another quick question though: After the fix is the data array on f113 supposed to be exactly 6000 samples long? When I run the new code it still has 6001 samples.

**Comment by TazawaK17** [comment]
> I am a little bit confused by the difference between the `1701260003_afterFix.png` and `1701260003_beforeFix.png` images. In beforeFix there is clearly an event around 3:52 on station f113. This doesn't show in the afterFix. What am I missing here?

That event is noise caused by the No. 2 and No. 3 bugs.
In the case of No. 2, addition is performed before the shift operation, resulting in smaller absolute values being visible. For example, when the previous value is 0x0f and the difference value is 0x01, the correct value should be 0x10, but the output shows 0x01.
As for No. 3, the size of integer data in Python is not being considered, causing the difference values to be larger than the correct values. For example, when a byte is 0x35, the correct difference value is 0x05, but it is treated as 0x35.
Based on the above, it can't read correctly when reading 0.5-byte data.

> I can reproduce the images with the current maintenance_1.4.x branch and @TazawaK17's maintenance_1.4.x. Another quick question though: After the fix is the data array on f113 supposed to be exactly 6000 samples long? When I run the new code it still has 6001 samples.

I'm sorry. I was missing "-1" to add on line 141. Already fixed.

**Comment by megies** [comment]
Merged into maintenance and it will be in release version 1.4.1 soon
