### ISSUE TITLE
AttributeError: 'ArtistList' object has no attribute 'remove' when "un-zooming" a stream plot

### ISSUE THREAD

**Issue by filefolder** [obspy/obspy#3318]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

Minor but annoying bug when clicking the "home" button after zooming in on a plotted stream. The red `Warning: Zooming into MinMax Plot!` text in the corner isn't being cleared. Before I delve into it I figure someone may already be aware of whatever matplotlib (?) thing has changed. 

```
st.plot()

Installed gtk4 event loop hook.
Traceback (most recent call last):
  File "/home/seis/.local/lib/python3.11/site-packages/matplotlib/cbook/__init__.py", line 304, in process
    func(*args, **kwargs)
  File "/home/seis/.local/lib/python3.11/site-packages/obspy/imaging/waveform.py", line 1445, in _warn_on_xaxis_zoom
    self._remove_zoomlevel_warning_text()
  File "/home/seis/.local/lib/python3.11/site-packages/obspy/imaging/waveform.py", line 1457, in _remove_zoomlevel_warning_text
    ax.texts.remove(self._minmax_warning_text)
    ^^^^^^^^^^^^^^^
AttributeError: 'ArtistList' object has no attribute 'remove'
```

### Code to Reproduce

```python
1) st.plot()

2) zoom in with the magnifying glass

3) click the "home" icon to resume the original view
```

### ObsPy Version?

1.4.0

### Operating System?

Debian 12

### Python Version?

3.11

### Installation Method?

pip

**Comment by megies** [comment]
I've come across this API change in mpl 3.6 in megies/obspyck#104. Should be an easy fix. Thanks for the report!

**Comment by megies** [comment]
@filefolder should be fixed by above PR, tested it locally as well
