### ISSUE TITLE
write header of sac for b and e

### ISSUE THREAD

**Issue by yjgao-gfz** [obspy/obspy#3324]
Hello, dear experts.
Here I am trying to write the b and o to sac files through obspy, but when I read the saved sac after writing, it didn't change, is it a bug?
Best regards,
yjgao

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a [short, self contained, correct example](http://sscce.org/) that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)

**Comment by jkmacc-LANL** [comment]
Hi,

Could you paste a minimum working example illustrating the problem you're having?  I'm happy to look into this if I can see what you're doing.

Thanks!

**Comment by yjgao-gfz** [comment]
Thanks, it is solved
