### ISSUE TITLE
Reading CyberShake seismograms in obspy

### ISSUE THREAD

**Issue by jrekoske** [obspy/obspy#3359]
### Problem

Hi, is there any interest to add an obspy reader for CyberShake seismogram data? These are synthetic seismograms used for seismic hazard analysis. The documentation for the format is here: 

https://strike.scec.org/scecpedia/Accessing_CyberShake_Seismograms#Seismogram_Format

and that page contains some example Python code used to read the data. It'd be nice to be able to load these seismograms directly into traces using obspy `read`

**Comment by megies** [comment]
Should be fairly simple to add, you wanna give it a shot?
