### ISSUE TITLE
SEGY Format Unrecognized After Packaging with PyInstaller or cx_Freeze

### ISSUE THREAD

**Issue by plada000** [obspy/obspy#3366]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

I'm having an issue with obspy when I try to create an executable file using PyInstaller or cx_Freeze. My code reads SEGY format data and runs perfectly fine when executed in PyCharm. However, after packaging it into an executable, the program fails to read the SEGY format, even though I have ensured that all relevant libraries, especially obspy, are included in the package.

### Code to Reproduce

```python
from obspy import read
# ...
try:
    st = read(full_path)
except Exception as e:
    logging.error(f"Failed to read {full_path}: {e}")
    QMessageBox.critical(self, 'Error', f'Failed to read {full_path}: {str(e)}')
    continue

logging.info(f"Successfully read {full_path}. Starting processing...")
st = read(full_path, format='SEGY')
logging.info(f"Read complete. Processing {full_path} ...")

new_file = os.path.join(self.target_dir, f"{counter}.SGY")
# ...
```

### Error Traceback

```Python traceback
Unknown format for file E:/PY/data/00012411.SGY
```

### ObsPy Version?

1.4

### Operating System?

windows

### Python Version?

Python 3.8.2rc2

### Installation Method?

pip

**Comment by plada000** [comment]
Error log:
Checking system path
sys.path: ['C:\\pythonProject10\\dist\\build\\exe.win-amd64-3.8\\lib\\library.zip', 'C:\\pythonProject10\\dist\\build\\exe.win-amd64-3.8\\lib']
Attempting to read SEGY file from E:\PY\data\00012411.SGY
Failed to read E:\PY\data\00012411.SGY: Format "SEGY" is not supported. Supported types: 
Exception type: <class 'TypeError'>
Exception args: ('Format "SEGY" is not supported. Supported types: ',)
Exception traceback:

**Comment by ThomasLecocq** [comment]
Packaging obspy to executable requires to properly link all entry points and data files etc, otherwise you'll only pack the core and not the io.segy for example, leading to that error

**Comment by plada000** [comment]
Hello,

I've been facing issues while trying to package my Python application that uses the ObsPy library with PyInstaller. I followed your previous advice and made sure to include the core ObsPy modules as well as 'io.segy' in the `hiddenimports` section of my `.spec` file. After doing so, I observed that the `_internal` folder in the packaged output now includes `obspy\io\segy\segy.py`, among other ObsPy files. However, I still encounter the same error that says "Format 'SEGY' is not supported."

Here is the modified `.spec` file I am currently using:

```python
a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('C:\\pythonProject10\\Lib\\site-packages\\obspy', 'obspy')],
    hiddenimports=['obspy.core', 'obspy.io', 'obspy.signal', 'obspy.io.segy'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
Could you please guide me on what I might be missing or need to modify to resolve this issue?

Thank you for your assistance.

**Comment by ThomasLecocq** [comment]
You should look into obspy's setup.py and add the entry points that are mentioned (even all of them to test first)

**Comment by plada000** [comment]
Hi Thomas,I've attempted to understand the relevant entry points, but I'm not entirely clear on the details. The only thing I see related to SEGY is obspy.io.segy.core. I tried modifying the PyInstaller spec file, particularly the hiddenimports section, but my attempts have not yielded success.

My questions are:

1.Is modifying hiddenimports in the spec file a valid approach for resolving this issue?
2.Could the problem be related to the read function or any other part of ObsPy?
3.Do you have any detailed guidance or successful case studies for packaging ObsPy-based applications with PyInstaller?

I have been troubleshooting this problem for an extended period, and I would greatly appreciate any detailed assistance you can provide. studies for packaging ObsPy-based applications with PyInstaller?

I have been troubleshooting this problem for an extended period, and I would greatly appreciate any detailed assistance you can provide.

Thank you for your time and your contributions to the community.

**Comment by plada000** [comment]
Hi Thomas,I wanted to update you on my recent progress regarding the issues I previously reported with packaging my ObsPy-based application. This time, I used cx_Freeze to package the script. Subsequently, I replaced the ObsPy directory in the packaged application with the one from my regular installation directory. The application is now running as expected.

I plan to investigate further to determine which specific files were missing initially. I will communicate my findings with you at a later time.

Thank you for your ongoing support and for providing such an invaluable resource to the community.

**Comment by plada000** [comment]
I have been facing issues with packaging my Obspy project using cx_Freeze. After comparing the Obspy folders before and after packaging, I noticed the following differences:

Files only in the pre-packaged Obspy directory (C:/pythonProject10/Lib/site-packages/obspy): __pycache__, conftest.py, __init__.py

Files only in the post-packaged Obspy directory (C:/pythonProject10/dist/build/exe.win-amd64-3.8/lib/obspy): __init__.pyc, conftest.pyc

Could you please help me understand which missing files might be causing the issues? Do you have any insights into why this discrepancy is causing the problem?

I would appreciate your detailed guidance or any successful case examples that could help resolve this issue.

Thank you for your time and support.

**Comment by plada000** [comment]
[compare.csv](https://github.com/obspy/obspy/files/13197379/compare.csv)
Apologies for the confusion in my previous message. I've now created a CSV file that lists all the missing files between the packaged and unpackaged ObsPy directories. This should help clarify which files are absent. I'll share the CSV file shortly for your reference. Could you please take a look to help identify the issue?

**Comment by yanzangtian** [comment]
Hi, plada000 ! May I ask how you solved it using pyinstaller? Would it be convenient for you to show me the information in the spec file? I would greatly appreciate it

**Comment by yanzangtian** [comment]
Thank you for your help. I've successfully packaged it, used the cx_Freeze, and I'm currently testing if the program works。Here's my setup.py，However, you need to copy the obspy-1.4.0.dist-info folder to the lib folder before you can run the program properly.

from cx_Freeze import setup, Executable
import sys
import obspy
sys.setrecursionlimit(8000)
exe = Executable(
    script="main.py",
    base="Console",
)

setup(
    name="location",
    version="0.1",
    description="Description of your project",
    executables=[exe],
    options={
        'build_exe': {
            'packages': ['obspy'],  
            'include_files': ['D:\\software\\pulse.sac','D:\\Python\\Lib\\site-packages\\obspy-1.4.0.dist-info']  
                 }
            }
)
