### ISSUE TITLE
obspy.clients.fdsn fails to get some station metadata

### ISSUE THREAD

**Issue by tianzeliu** [obspy/obspy#3368]
I was trying to use `obspy.clients.fdsn` to get station metadata from the IRIS DMC but found that it failed to get significant portions of the data. Take the station IU.SJF for example, the script below:

`from obspy.clients.fdsn import Client`
`client = Client("IRIS")`
`inv = client.get_stations(starttime="1996-03-21-00-00-00", endtime="2023-10-25-23-59-59", network="IU", station="SFJ", channel="BH*,HH*", level="response")`
`inv.write("./SJF.xml", "STATIONXML")`

only retrieves the channel metadata for 1996–1999, whereas the IRIS DMC contains the metadata for 1996–2005: [https://ds.iris.edu/mda/IU/SFJ/?starttime=1996-03-21T00:00:00&endtime=2005-01-31T16:00:00](url), which can be fully retrieved using the Perl script FetchData provided by IRIS. In another case, the same script returns an error while retrieving the metadata for IU.SJFD, whereas the metadata clearly exists: [https://ds.iris.edu/mda/IU/SFJD/?starttime=2005-01-31T16:00:00&endtime=2599-12-31T23:59:59](url).

**Comment by aringler-usgs** [comment]
Hi @tianzeliu I just checked this and it doesn't look like the issue is with `obspy.clients.fdsn`.

Here is what I get with SFJ

```(mypython) aringler@IGSKGACGLTENG01 Desktop % python check.py 
Inventory created at 2023-10-31T19:15:38.855700Z
	Created by: IRIS WEB SERVICE: fdsnws-station | version: 1.1.52
		    http://service.iris.edu/fdsnws/station/1/query?starttime=1996-03-21...
	Sending institution: IRIS-DMC (IRIS-DMC)
	Contains:
		Networks (1):
			IU
		Stations (1):
			IU.SFJ (Sondre Stromfjord, Greenland)
		Channels (6):
			IU.SFJ..BHZ, IU.SFJ..BHN, IU.SFJ..BHE, IU.SFJ.00.BHZ, IU.SFJ.00.BHN
			IU.SFJ.00.BHE
```

and here is SFJD

```
Inventory created at 2023-10-31T19:17:14.771000Z
	Created by: IRIS WEB SERVICE: fdsnws-station | version: 1.1.52
		    http://service.iris.edu/fdsnws/station/1/query?starttime=1996-03-21...
	Sending institution: IRIS-DMC (IRIS-DMC)
	Contains:
		Networks (1):
			IU
		Stations (1):
			IU.SFJD (Sondre Stromfjord, Greenland)
		Channels (39):
			IU.SFJD.00.BHZ (5x), IU.SFJD.00.BHN (2x), IU.SFJD.00.BHE (2x), 
			IU.SFJD.00.BH1 (3x), IU.SFJD.00.BH2 (3x), IU.SFJD.10.BHZ (4x), 
			IU.SFJD.10.BHN (2x), IU.SFJD.10.BHE (2x), IU.SFJD.10.BH1 (2x), 
			IU.SFJD.10.BH2 (2x), IU.SFJD.10.HHZ (4x), IU.SFJD.10.HHN (2x), 
			IU.SFJD.10.HHE (2x), IU.SFJD.10.HH1 (2x), IU.SFJD.10.HH2 (2x)
```

There are multiple epochs for these channels.  This is coming from sensor swaps.  Is the issue with the station xml?  I didn't look closely but it looked okay to me.

**Comment by tianzeliu** [comment]
Interesting. Somehow I can't reproduce the problem anymore. Sorry for the disruption!
