### ISSUE TITLE
`Stream.plot(type='section')` does not respect `method='full'`

### ISSUE THREAD

**Issue by liamtoney** [obspy/obspy#3375]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

When using the Stream plotting method with `type='section'`, no matter the `method` used the data are resampled if they exceed 10,000 samples, see here in the `__init__()` method for `WaveformPlotting`:
https://github.com/obspy/obspy/blob/00122ed909bf6a488ed25d279a83dbea10a6599a/obspy/imaging/waveform.py#L125-L129
and in `__sect_init_traces()`:
https://github.com/obspy/obspy/blob/00122ed909bf6a488ed25d279a83dbea10a6599a/obspy/imaging/waveform.py#L1235-L1239

It seems to me that the latter bit of code should be checking if `method='full'` and if so, setting `tmp_data = tr.data` — rather than resampling. Currently that kwarg is not checked. Therefore, as it stands, users have no way of fully plotting the data without resampling if they're using `type='section'`.

I'm happy to make a PR to address this.

### ObsPy Version?

1.4.0

### Operating System?

macOS (M1)

### Python Version?

3.11.5

### Installation Method?

conda

**Comment by megies** [comment]
> I'm happy to make a PR to address this.

Sure, go ahead!

**Comment by liamtoney** [comment]
Great. What branch should I base my feature branch off of? [`maintenance_1.4.x`](https://github.com/obspy/obspy/tree/maintenance_1.4.x)?

**Comment by megies** [comment]
> Great. What branch should I base my feature branch off of? [`maintenance_1.4.x`](https://github.com/obspy/obspy/tree/maintenance_1.4.x)?

Yes. Qualifies as a "bug", so that's where I would base it off of.

**Comment by liamtoney** [comment]
Closing this seeing as #3379 was merged.

**Comment by megies** [comment]
> Closing this seeing as #3379 was merged.

github does close stuff automatically, but when the PR goes into maintenance branch it will only close the related issue after maintenance is merged into master, which will happen eventually but sometimes not immediately :+1:

**Comment by liamtoney** [comment]
> when the PR goes into maintenance branch it will only close the related issue after maintenance is merged into master

Ah! Didn't know this. Thanks.
