### ISSUE TITLE
libmseed version 3

### ISSUE THREAD

**Issue by Gilaverbuch** [obspy/obspy#3377]
### Problem

Hi, 

There is a new miniSEED version released, libmseed v3 (https://earthscope.github.io/libmseed/). Currently, Obspy does not seem to be able to handle the new miniSEED version. Does anyone know if that will change anytime soon?

Thanks,
Gil

**Comment by QuLogic** [comment]
Duplicate of #2376. You should search first, as all the information is in that issue.
