### ISSUE TITLE
Support for Obspy on the Linux, ARM64, platform

### ISSUE THREAD

**Issue by Omid87** [obspy/obspy#3425]
### Problem

Request for the inclusion of ARM64 architecture support for the Linux platform in ObsPy. As the ARM64 architecture gains prominence in various computing environments, particularly in scientific research and data processing fields, extending support for ARM64 would greatly enhance the usability and accessibility of ObsPy for a wider range of users and systems. 

### Proposed solution

Package and distribute the Linux, ARM64,  version of the Obspy on both Conda-forge and Pypi.

**Comment by Omid87** [comment]
I tried to package the application on Debian ARM64 platform and here is the error I get. 

```
conda build .  
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.26
Adding in variants from internal_defaults
Attempting to finalize metadata for obspy
Reloading output folder: ...working... done
Getting pinned dependencies: ...working... done
BUILD START: ['obspy-1.1.0-py312hb3f6f3f_0.tar.bz2']
Reloading output folder: ...working... done
Solving environment (_h_env): ...working... done
Reloading output folder: ...working... done
Solving environment (_test_env): ...working... done

## Package Plan ##

  environment location: /home/orangepi/miniconda3/conda-bld/obspy_1712861782103/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
ld_placehold_placehold_placehold_placehold_placehold_pl


The following NEW packages will be INSTALLED:

   **_I DELETED THE LIST OF PACKAGES TO MAKE IT SHORTER_**

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Source cache directory is: /home/orangepi/miniconda3/conda-bld/src_cache
Found source in cache: obspy-1.1.0_ef48b4e52a.zip
Extracting download
source tree in: /home/orangepi/miniconda3/conda-bld/obspy_1712861782103/work
export PREFIX=/home/orangepi/miniconda3/conda-bld/obspy_1712861782103/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
ld_placehold_placehold_placehold_placehold_pl
export SRC_DIR=/home/orangepi/miniconda3/conda-bld/obspy_1712861782103/work
Traceback (most recent call last):
  File "/home/orangepi/miniconda3/conda-bld/obspy_1712861782103/work/setup.py", line 47, in <module>
    from numpy.distutils.core import DistutilsSetupError, setup
ModuleNotFoundError: No module named 'numpy.distutils'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/orangepi/miniconda3/lib/python3.12/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/orangepi/miniconda3/lib/python3.12/site-packages/conda/cli/main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/home/orangepi/miniconda3/lib/python3.12/site-packages/conda/cli/conda_argparse.py", line 175, in do_call
        result = plugin_subcommand.action(getattr(args, "_args", args))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/orangepi/miniconda3/lib/python3.12/site-packages/conda_build/plugin.py", line 17, in build
        return execute(args)
               ^^^^^^^^^^^^^
      File "/home/orangepi/miniconda3/lib/python3.12/site-packages/conda_build/cli/main_build.py", line 581, in execute
        api.build(
      File "/home/orangepi/miniconda3/lib/python3.12/site-packages/conda_build/api.py", line 250, in build
        return build_tree(
               ^^^^^^^^^^^
      File "/home/orangepi/miniconda3/lib/python3.12/site-packages/conda_build/build.py", line 3762, in build_tree
        packages_from_this = build(
                             ^^^^^^
      File "/home/orangepi/miniconda3/lib/python3.12/site-packages/conda_build/build.py", line 2634, in build
        utils.check_call_env(
      File "/home/orangepi/miniconda3/lib/python3.12/site-packages/conda_build/utils.py", line 408, in check_call_env
        return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/orangepi/miniconda3/lib/python3.12/site-packages/conda_build/utils.py", line 384, in _func_defaulting_env_to_os_environ
        raise subprocess.CalledProcessError(proc.returncode, _args)
    subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/orangepi/miniconda3/conda-bld/obspy_1712861782103/work/conda_build.sh']' returned non-zero exit status 1.

`$ /home/orangepi/miniconda3/bin/conda build .`

  environment variables:
                 CIO_TEST=<not set>
    CONDA_ALLOW_SOFTLINKS=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/orangepi/miniconda3/bin/conda
             CONDA_PREFIX=/home/orangepi/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/orangepi/miniconda3/bin/python
               CONDA_ROOT=/home/orangepi/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/home/orangepi/miniconda3/bin:/home/orangepi/miniconda3/condabin:/usr/
                          local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

     active environment : base
    active env location : /home/orangepi/miniconda3
            shell level : 1
       user config file : /home/orangepi/.condarc
 populated config files : /home/orangepi/.condarc
          conda version : 24.3.0
    conda-build version : 24.3.0
         python version : 3.12.2.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=cortex_a72
                          __conda=24.3.0=0
                          __glibc=2.31=0
                          __linux=5.10.110=0
                          __unix=0=0
       base environment : /home/orangepi/miniconda3  (writable)
      conda av data dir : /home/orangepi/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-aarch64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-aarch64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-aarch64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/orangepi/miniconda3/pkgs
                          /home/orangepi/.conda/pkgs
       envs directories : /home/orangepi/miniconda3/envs
                          /home/orangepi/.conda/envs
               platform : linux-aarch64
             user-agent : conda/24.3.0 requests/2.31.0 CPython/3.12.2 Linux/5.10.110-rockchip-rk3588 debian/11.9 glibc/2.31 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:  
Timeout reached. No report sent.
```

**Comment by megies** [comment]
Have you tried like this?

```shell
(base) $ conda create -n obspy pip numpy scipy matplotlib lxml setuptools sqlalchemy decorator requests
(base) $ conda activate obspy
(obspy) $ pip install obspy
```

**Comment by Omid87** [comment]
I'm currently able to install `Obspy` in development mode by creating a `conda` environment and utilizing `pip install -e .` for installation. However, I'm encountering difficulties when attempting to package Obspy using `conda build .` on the Linux ARM64 platform.

To provide more context, I'm a member of the software team at [EPIC](https://www.passcal.nmt.edu/home) (EarthScope Primary Instrument Center). We're in the process of expanding the compatibility of the [PASSOFT suite](https://www.passcal.nmt.edu/content/software-resources) to the ARM64 platform. `PASSOFT`, developed, packaged, and distributed by EPIC, relies on `Obspy` as a dependency.

In order to package `PASSOFT` for the Linux ARM64 platform, it's crucial that all dependencies are available on this specific platform. Unfortunately, `Obspy` isn't currently available for ARM64. As an interim solution until `Obspy` becomes available for ARM64, I intend to package `Obspy` for this platform and host it on our local [conda channel](https://onyx.passcal.nmt.edu/passcal/). This approach will enable `PASSOFT` to be installed on Linux ARM64 systems.

**Comment by megies** [comment]
Looking at your initial failure report.. did you have numpy installed before running conda build?

**Comment by Omid87** [comment]
I left all dependencies to be handled by Obspy build script and conda build command. Basically when you build a conda package, using `conda build` command, you have no control over the process. Everything must be specified in your `meta.yaml` and the process is automated. Here is the link to `conda build` documentation:
https://docs.conda.io/projects/conda-build/en/stable/concepts/recipe.html

**Comment by megies** [comment]
Yeah, I realize that. It's just we used to have numpy explicitly in our setup.py as an import (for distutils I think), so it had to be there before starting the build process. Not 100% sure how it is these days but we still have it in our conda-forge recipe as a build requirement (might be a relic, but I see your build failing due to missing numpy).

You could just install numpy in your base/root environment to try and see if it helps. In any case our build recipe stuff for conda is here, maybe it helps:
https://github.com/conda-forge/obspy-feedstock/

**Comment by megies** [comment]
Btw, I just noticed.. why are you trying to build obspy 1.1.0? That's a release that's 7 years old.

**Comment by steve8x8** [comment]
Indeed - I would not expect 1.1.0 to work with Python 3.1x (for more reasons than just dropped distutils)... 

OTOH, I'd appreciate if aarch64 wheels could be built and made available via PyPI.

**Comment by megies** [comment]
> OTOH, I'd appreciate if aarch64 wheels could be built and made available via PyPI.

Our pypi wheels are built through github actions and our conda packages are built through conda-forge infrastrucutre. I don't use or know these architectures mentioned here tbh, so if you have instructions how to add these things, drop the info here =)
I tried a quick search and I didn't really find anything definitive enough to justify really look into it more.

**Comment by Omid87** [comment]
> Yeah, I realize that. This is not about a "run" dependency, but about a "build" dependency, which comes earlier and might not be able to be resolved by conda, it might have to be there at build time and conda can't handle it missing from the base environment.
> 
> It's just we used to have numpy explicitly in our setup.py as an import, so even a "pip install" on any platform would fail with numpy not there beforehand (for distutils I think), it had to be there before starting the build process. Not 100% sure how it is these days but we still have it in our conda-forge recipe as a build requirement (might be a relic, but I see your build is failing due to missing numpy).
> 
> You could just install numpy in your base/root environment to try and see if it helps, might be thats an easy one-line fix to your build issues (I dont see a reason why it wouldn't build otherwise and that is how your build errors out "missing numpy"). In any case our build recipe stuff for conda is here, maybe it helps: https://github.com/conda-forge/obspy-feedstock/

I will install the numpy in my environment and give it a try again.

**Comment by Omid87** [comment]
> Btw, I just noticed.. why are you trying to build obspy 1.1.0? That's a release that's 7 years old.
> 
> ```
> BUILD START: ['obspy-1.1.0-py312hb3f6f3f_0.tar.bz2']
> ```
> 
> ```
> Traceback (most recent call last):
>   File "/home/orangepi/miniconda3/conda-bld/obspy_1712861782103/work/setup.py", line 47, in <module>
>     from numpy.distutils.core import DistutilsSetupError, setup
> ModuleNotFoundError: No module named 'numpy.distutils'
> ```

I first used the master branch to package Obspy and after noticing the issue with the version number, I switched to the branch `maintenance_1.4.x` and still the same issue. Which branch is carrying the most updated version?

**Comment by megies** [comment]
Not sure how exactly you do the build, but it's weird that it pulls in 1.1.0 when now 1.4.1 is the newest release. You could also try to use our conda-forge feedstock to build locally, there is a script in there with that name, never tried it myself though.

Also, in principle we should be able to build `linux-aarch64` through conda-forge, just not sure how to tell conda-forge to do that. If you could find out how or where to look it up we could give that a try too.

**Comment by Omid87** [comment]
> @Omid87 looks like adding `linux-aarch64` to conda-forge was trivial, packages are being built right now, so you could try them out in like half an hour

Thank you so much @megies.
