### ISSUE TITLE
Extracting Single Shot Data

### ISSUE THREAD

**Issue by ZHR0623** [obspy/obspy#3428]
### Problem

 Is it possible for obspy to split a segy file containing multiple shots sets by shot set? Because I want to save one of the shots as a segy file for a single shot set.

**Comment by ThomasLecocq** [comment]
Hi,

Yes, you can access individual records of segy files and save them to any other format. 

I believe you checked this doc page already: https://docs.obspy.org/packages/obspy.io.segy.html

Alternatively, you could try using [segio](https://github.com/equinor/segyio).
