### ISSUE TITLE
Convert Pole and Zero to xml file

### ISSUE THREAD

**Issue by boulanouar1** [obspy/obspy#3431]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

Dear Obspy users, 
I am trying to convert Pole and zero file to inventory xml.
Is there any way to do it using Obspy?
Thank you in advance 

### ObsPy Version?

1.2.2

### Operating System?

OX

### Python Version?

3.11

### Installation Method?

conda

**Comment by megies** [comment]
Please post usage questions on our forum: https://discourse.obspy.org/
