### ISSUE TITLE
MATLAB seismogram export needs updating to latest Python dict syntax

### ISSUE THREAD

**Issue by benjaminfernando** [obspy/obspy#3439]
### Documentation Link

https://docs.obspy.org/tutorial/code_snippets/export_seismograms_to_matlab.html

### Problem

At the moment, the tr.stats object has .iteritems() rather than .items() applied to it. I think this is still Python 2 syntax, not 3. 

(disclaimer: don't use MATLAB myself, posting for a student...). 

### Suggested improvement

Change the code snippet to be tr.stats.items() which worked for me.

**Comment by d-chambers** [comment]
Thanks @benjaminfernando. Do you want to create a PR? This one should be really simple. The code snippet file is [here](https://github.com/obspy/obspy/blob/master/misc/docs/source/tutorial/code_snippets/export_seismograms_to_matlab.py).

**Comment by trichter** [comment]
@megies, by the way, if one looks at the doc building log in github actions, you will see even more bugs in the tutorial.

**Comment by megies** [comment]
> @megies, by the way, if one looks at the doc building log in github actions, you will see even more bugs in the tutorial.

:see_no_evil:
