### ISSUE TITLE
coverage upload not working

### ISSUE THREAD

**Issue by trichter** [obspy/obspy#3459]
Here is a representative message from the github actions runner:

```
warning - 2024-05-23 09:32:54,825 -- Some files were not found --- {"not_found_files": ["obspy/coverage.xml"]}
info - 2024-05-23 09:32:54,891 -- Found 12 coverage files to report
info - 2024-05-23 09:32:54,891 -- > /home/runner/work/obspy/obspy/obspy/io/focmec/tests/data/focmec_all.lst
info - 2024-05-23 09:32:54,891 -- > /home/runner/work/obspy/obspy/obspy/io/focmec/tests/data/focmec_8sta-noratios.lst
info - 2024-05-23 09:32:54,891 -- > /home/runner/work/obspy/obspy/obspy/io/focmec/tests/data/focmec_qedUWne.lst
info - 2024-05-23 09:32:54,891 -- > /home/runner/work/obspy/obspy/build/lib.linux-x86_64-cpython-312/obspy/taup/tests/data/sample_ttimes_ak135.lst
info - 2024-05-23 09:32:54,891 -- > /home/runner/work/obspy/obspy/obspy/taup/tests/data/sample_ttimes_ak135.lst
info - 2024-05-23 09:32:54,891 -- > /home/runner/work/obspy/obspy/obspy/io/focmec/tests/data/focmec_8sta.lst
info - 2024-05-23 09:32:54,891 -- > /home/runner/work/obspy/obspy/build/lib.linux-x86_64-cpython-312/obspy/io/focmec/tests/data/focmec_qedUWne.lst
info - 2024-05-23 09:32:54,891 -- > /home/runner/work/obspy/obspy/obspy/taup/tests/data/sample_ttimes_iasp91.lst
info - 2024-05-23 09:32:54,891 -- > /home/runner/work/obspy/obspy/build/lib.linux-x86_64-cpython-312/obspy/io/focmec/tests/data/focmec_8sta.lst
info - 2024-05-23 09:32:54,891 -- > /home/runner/work/obspy/obspy/build/lib.linux-x86_64-cpython-312/obspy/taup/tests/data/sample_ttimes_iasp91.lst
info - 2024-05-23 09:32:54,892 -- > /home/runner/work/obspy/obspy/build/lib.linux-x86_64-cpython-312/obspy/io/focmec/tests/data/focmec_8sta-noratios.lst
info - 2024-05-23 09:32:54,892 -- > /home/runner/work/obspy/obspy/build/lib.linux-x86_64-cpython-312/obspy/io/focmec/tests/data/focmec_all.lst
warning - 2024-05-23 09:32:54,902 -- There was an issue decoding: obspy/io/ah/tests/data/ah1.c, file fixes were not applied to this file.
warning - 2024-05-23 09:32:54,902 -- There was an issue decoding: obspy/io/ah/tests/data/ah2.c, file fixes were not applied to this file.
info - 2024-05-23 09:32:55,040 -- Process Upload complete
error - 2024-05-23 09:32:55,041 -- Upload failed: {"detail":"You do not have permission to perform this action."}
```

**Comment by megies** [comment]
Maybe the token or whatever we use for auth expired

**Comment by megies** [comment]
@trichter I copied the token it shows after login in to codecov into our github actions secrets again and pushed an empty commit on master to trigger CI, let's see

**Comment by d-chambers** [comment]
By looking at the [installed apps](https://github.com/obspy/obspy/settings/installations) it looks like we don't have the codecov app installed for the ObsPy repo. I see we have a fresh CI token added only a few weeks ago, but if the app wasn't installed it might raise this kind of error when the bot tries to leave a comment about coverage on the PR page.

**Comment by d-chambers** [comment]
Ok, I just installed it. Next CI trigger let's see if it solves the issue.

**Comment by megies** [comment]
Still the same..

```
error - 2024-05-24 06:43:06,448 -- Upload failed: {"detail":"You do not have permission to perform this action."}
```

**Comment by d-chambers** [comment]
[This issue](https://github.com/codecov/codecov-action/issues/1273) details an identical case. There are different scopes for codecov tokens. It is possible that whoever added the codecov token last week (I can't see who) accidentally added a personal token or token scoped to a different project. So we need to log into codecov and select the obspy organization before generating the token. But, for some reason when I log into codecov I can't select the ObsPy organization. Does anyone have that option?

![image](https://github.com/obspy/obspy/assets/11671536/1ad1de0a-93b7-477c-a7ee-dee6187a4188)

**Comment by QuLogic** [comment]
I went to https://app.codecov.io/gh/obspy/obspy/settings, regenerated the token, updated the repository secrets, and restarted the last workflow, and I think it worked? https://github.com/obspy/obspy/actions/runs/9219754931/job/25583901396#step:10:74

**Comment by QuLogic** [comment]
However, these seem to have all errored? https://app.codecov.io/gh/obspy/obspy/commit/cd08b60d9d841ce20a37a1676fdac47e87d25493

**Comment by trichter** [comment]
Inside obspy-runtests we cd to obspy's root directory. The coverage.xml is probably laying around there and the coverage upload script cannot find it. We can specify the output location of the coverage.xml file with `obspy-runtests ... --cov=xml:abs_output_loc`

**Comment by trichter** [comment]
I think the current setup only works with an editable install, which we used a while ago on github actions.
