### ISSUE TITLE
Numpy 2.0(.0rc2)

### ISSUE THREAD

**Issue by megies** [obspy/obspy#3460]
Numpy 2.0 will release with some changes in behavior in June. We need to ideally adjust our code to work with it like before or pin `numpy<2`.

https://numpy.org/devdocs/numpy_2_0_migration_guide.html

https://mail.python.org/archives/list/numpy-discussion@python.org/thread/AACXABTJ5T44T275ISQWKGL3IIOZAYTB/

https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-0-specific-advice

https://tests.obspy.org/140045/

Numpy 2.0.0rc2 can be installed with conda like this (or using the new env file from the related pull request)
```shell
(base)$ conda create -n np2 python numpy==2.0.0rc2 conda-forge/label/numpy_rc::_numpy_rc obspy pytest pytest-json-report
# optionally switch to dev obspy
(base)$ conda activate np2
(np2)$ conda remove --offline --force obspy
(np2)$ pip install -e /path/to/obspy/git
```

**Comment by megies** [comment]
As far as I understand we don't rely on numpy C API but it seems still we need to make sure wheels are built on numpy 2.x. Not sure about it though, it's quite confusing to me. Also, IIUC, we build wheels in the same environment that is used for testing in all the various matrix jobs which would mean we can't easily make sure numpy 2 is used to build wheels. Also not sure about that assessment though :rofl: 

There is some info here it seems how to control build env, not sure if that helps
https://cibuildwheel.pypa.io/en/v2.18.1/options/#examples_11

**Comment by megies** [comment]
see conda-forge/obspy-feedstock#67

**Comment by trichter** [comment]
Hi! What is the rationale behind #3461? Do you want to fix the numpy2 issues in that PR or merge it and fix the issues with subsequent PRs?

We want to fix numpy2 issues before the 1.5.0 release?

**Comment by megies** [comment]
> Hi! What is the rationale behind #3461? Do you want to fix the numpy2 issues in that PR or merge it and fix the issues with subsequent PRs?

I think just work in that PR on fixes, no real need to get the CI change into master without the fixes, I'd say
 
> We want to fix numpy2 issues before the 1.5.0 release?

I think we should try yeah, pretty sure it's mostly trivial fixes, like manual upcasting of types and stuff like that

**Comment by megies** [comment]
> I don't think that should be the case. You'd only need to build against it to get the ABI to match. It _should_ be sufficient to ensure we test it somewhere.

Yeah, I read more on it and I agree, probably we're good.

@trichter probably we could attach built wheels as artifacts so we can just briefly grab one wheel built on numpy 1.x and check it locally vs numpy 2.0.0rc2

**Comment by trichter** [comment]
> @trichter probably we could attach built wheels as artifacts so we can just briefly grab one wheel built on numpy 1.x and check it locally vs numpy 2.0.0rc2

This is already done. You can just grab the wheels for py3.12 from the build_wheels run triggered by pushes to the master branch. If you want to download wheels for other python versions, you can add the `test_wheels` flag in a PR.
