### ISSUE TITLE
Bug report for gap/overlap

### ISSUE THREAD

**Issue by siderique** [obspy/obspy#3479]
Some traces is considered as a gap. In my opinion, unsorted starttime of traces cause some errors in gap/overlap calculation logic.
I attached my mini-seed file. [KW_KCG_HGE_20240201.zip](https://github.com/user-attachments/files/15948597/KW_KCG_HGE_20240201.zip)

  -  ObsPy version (1.4.0), Python version (3.11.8) and Platform (Windows)
  -  How did you install ObsPy and Python (anaconda)

**Comment by ThomasLecocq** [comment]
Hi @siderique ,

could you provide more details, example prints or plots of your data? The obspy crew is a small set of volunteers that usually don't have a lot of time to go in depth into each data file etc, but we're happy to help !

**Comment by megies** [comment]
Seems like crappy data, should toss out that digitizer looks like.

miniSEED records:
 - aren't ordered in the file properly
 - aren't numbered like they usually are

The above is just unusual, nothing problematic, but quite fishy in terms of quality of the recording hardware.

The main problem to me seems to be that while the start times of all records kind of line up exactly, they don't, if you sort the start times of all records and run a diff through that list of values, you can see that most start times behave as expected with exactly one second offset, but then sometimes the next block has the exact same start time as the block before or twice the expected difference or even three times.

![Figure_1](https://github.com/obspy/obspy/assets/1842780/de421566-337e-482f-a02c-b766303209a2)


My guess would be, digitizer equipment is really bad and sometimes screws up the start time of the 100 sample block. And this in combination with mini seed records neither numbered consecutively nor ordered in the file properly causes libmseed to run into problems trying to make sense of the data.

Nothing we can do really.
