### ISSUE TITLE
Raise a FDSNException rather than a ValueError when a service is not present in Client.services

### ISSUE THREAD

**Issue by simonpanay** [obspy/obspy#3483]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

This morning I stumble on a ValueError raised by obspy.clients.fdsn.Client.get_waveforms
It appears that during client initialization, the request for services "application.wadl" returned a (transient) 50X error.
Later, when executing get_waveforms method, "dataselect" was not present in Client.services and a ValueError was raised.

Should obspy raise a FDSNException (or more specific like FDSNNoServiceException) rather than this ValueError ?
It would be easier later on to handle this kind of exception in our programs.

```python
try:
    client.get_waveforms(....)
except FDSNNoDataException:
    pass
except FDSNException:
    handle(...)
```
Would be cleaner than :
```python
try:
    client.get_waveforms(....)
except FDSNNoDataException:
    pass
except FDSNException, ValueError:
    handle(...)
```

### Error Traceback

```Python traceback
ValueError: The current client does not have a dataselect service.
  ...
  File "obspy/clients/fdsn/client.py", line 858, in get_waveforms
    raise ValueError(msg)
```

### ObsPy Version?

1.4.1

### Operating System?

Ubuntu

### Python Version?

3.11.9

### Installation Method?

pip

**Comment by simonpanay** [comment]
If this issue makes sense and if needed I'm willing to work on the PR

**Comment by megies** [comment]
Sounds absolutely reasonable to me. Happy to get a PR for it (off of master branch)! :+1:

**Comment by simonpanay** [comment]
I quicky replaced ValueError exceptions in get_waveforms|events|stations|[_bulk] with FDSNNoServiceException in PR #3488
I tried to run tests as explained in documentation but got a bunch of UnicodeDecodeError related failed tests. I'm not sure of what I done wrong here (perhaps nothing). I expect to at least update some tests to reflect this exception raising changes
