### ISSUE TITLE
Inclusion for mseed3 format?

### ISSUE THREAD

**Issue by marbail** [obspy/obspy#3490]
### Documentation Link

https://docs.obspy.org/pr/mseed3/packages/obspy.io.mseed3.html

### Problem

I see in the version 1.4.0 of the documentation that support for the mseed3 format is included with the installation of the simplemseed library. However, the latest version of the git hub repository doesn't seem to include this support, nor the branch "maintenance_1.4.x". Do you know which branch I need to download to get this mseed3 support?

### Suggested improvement

Maybe the ObsPy branch version containing the mseed3 support should be indicated.

**Comment by megies** [comment]
> I see in the version 1.4.0 of the documentation that support for the mseed3 format is included

What you linked above is not a release documentation but docs built for a pull request branch, see #3411

**Comment by megies** [comment]
Documentation for current stable release:
 - https://docs.obspy.org/

Documentation for older releases:
 - https://docs.obspy.org/archive/

Documentation for current master branch:
 - https://docs.obspy.org/master

Documentation for pull requests that requested a docs build to check how docs additions/changes look like rendered:
 - https://docs.obspy.org/pr

**Comment by megies** [comment]
It's sad we don't have mseed3 support yet, but pretty much all active developers left without others stepping up
