### ISSUE TITLE
Cannot read a WIN-format file

### ISSUE THREAD

**Issue by suchanun** [obspy/obspy#3495]
### Documentation Link

https://docs.obspy.org/packages/autogen/obspy.core.stream.read.html

### Problem

I need to read [a WIN-format file](https://www.seis.nagoya-u.ac.jp/~maeda/ymaeda_opentools_doc/include/win/data_format.html). However when I do `read(file_path, format='WIN')`,
I got an error "invalid literal for int() with base 10: '2e'". Do you know what the problem is? 

Upon reading it directly into text using python, i got the text below (some parts are omitted):

#p 110904.002014 . shiina
#p 11 09 04 00 20 14
#p D069 0 09 809 10 012 +0
#p D06A 1 18 850 18 950 +0
#p D078 0 09 050 09 150 +0
#p D079 1 16 950 17 250 +0
#p D082 0 08 603 08 627 -1
................[omitted].......................
#s 11/09/04 00:20                   19/02/19 16:21:15
#s E.YT2M     U  18.390 0.007  23.039 0.003   0.0 0.00e-00   35.80981  140.56311     15
#s E.TKWM     U  18.413 0.001  23.103 0.006   0.0 0.00e-00   35.76961  140.51761      2
#s E.YMKM     U  18.413 0.001  23.051 0.057   0.0 0.00e-00   35.78367  140.53569     22
.................[omitted].......................

**Comment by megies** [comment]
Can't say much without the file that makes issues.

**Comment by ThomasLecocq** [comment]
Hi, is your file a new WIN32 file or the older format ? Obspy only supports the old format.
