### ISSUE TITLE
epoch2hum

### ISSUE THREAD

**Issue by rgoalcast** [obspy/obspy#3499]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

cannot import name 'epoch2num' from 'matplotlib.dates' 

### Code to Reproduce

```python
from pdart.extra_plots.plot_timing_divergence import plot_timing
```

### ObsPy Version?

1.4.1

### Installation Method?

developer installation / from source / git checkout

**Comment by megies** [comment]
Hi @rgoalcast, this is the wrong place to report issues with `matplotlib` or `pdart` (i dont even know what that is). But sounds like this "pdart" project needs to adjust to some matplotlib API changes maybe.
