### ISSUE TITLE
obspy.xseed: getPAZ() returns IndexError

### ISSUE THREAD

**Issue by barsch** [obspy/obspy#511]
Using http://www.data.scec.org/ftp/stations/seed/dataless.CI.DEV with ```obpsy.xseed.parpser.Parser.getPAZ()``` results into an IndexError.

```python
 >>> from obspy.xseed import Parser
 >>> from obspy import UTCDateTime
 >>> parser = Parser("dataless.CI.DEV")
 >>> dt = UTCDateTime("2012-04-13")
 >>> paz = parser.getPAZ('CI.DEV..BHZ', dt)
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/usr/lib/python2.6/site-packages/obspy-0.8.3-py2.6-linux-x86_64.egg/obspy/core/util/decorator.py", line 67, in echo_func
     return func(*args, **kwargs)
   File "/usr/lib/python2.6/site-packages/obspy-0.8.3-py2.6-linux-x86_64.egg/obspy/xseed/parser.py", line 480, in getPAZ
     abbreviation = blockette.stages[0][1]
IndexError: list index out of range
```
Blockette 060 has only one stage but line 485 looks for a second stage - however I'm not sure if we should try/except + pass here - @krischer pls have a look.

See also: http://lists.obspy.org/pipermail/obspy-users/2013-February/000406.html

**Comment by jcrummey** [comment]
Just noting that we have changed how our dataless files are built, we now can load PAZ with the getPAZ method. So this bug is no longer an issue for us.

**Comment by krischer** [comment]
Thanks for reporting this. As dataless SEED is on its way out I doubt we'll deal with this within ObsPy. I'm closing this. In case somebody still needs this, please reopen.
