### ISSUE TITLE
Arclink client getInventory with polynomial response

### ISSUE THREAD

**Issue by msimon00** [obspy/obspy#533]
Hi,

when trying to get the PAZ for all stations, it fails for some stations, when paz_id startswith ResponsePolynomial, instead of ResponsePAZ (as is usually)

here the printout of:
- station id
- xml_doc
- paz_id

for the failing stations

```
G ATD LKI
<Element {http://geofon.gfz-potsdam.de/ns/Inventory/1.0/}inventory at 0x2833e10>
ResponsePolynomial#20121008133958.583026.366
G ATD LDI
<Element {http://geofon.gfz-potsdam.de/ns/Inventory/1.0/}inventory at 0x2833e10>
ResponsePolynomial#20121008133958.581088.360
G RODM LKI
<Element {http://geofon.gfz-potsdam.de/ns/Inventory/1.0/}inventory at 0x2833e10>
ResponsePolynomial#20121008134140.162698.3794
G RODM LDO
<Element {http://geofon.gfz-potsdam.de/ns/Inventory/1.0/}inventory at 0x2833e10>
ResponsePolynomial#20121008134140.160064.3788
...
G TAOE MDI
<Element {http://geofon.gfz-potsdam.de/ns/Inventory/1.0/}inventory at 0x2833e10>
ResponsePolynomial#20121008134221.359693.5109
G SSB LKI
<Element {http://geofon.gfz-potsdam.de/ns/Inventory/1.0/}inventory at 0x2833e10>
ResponsePolynomial#20121008134151.332597.4687
```

**Comment by QuLogic** [comment]
I believe the ObsPy routines should handle polynomial responses now, but the example here doesn't seem to download for me. I just get `ArcLinkException: b'UNSET'`.

**Comment by krischer** [comment]
Puhhh...I am really not familiar with Arclink and not sure which error it should raise. @barsch can you have a look?

Nonetheless removing a polynomial response is right now limited to anything that can parse to our internal obspy.station.response.Response class. Which is essentially only StationXML right now. ArcLink serves SEED files which ObsPy can read but the polynomial response removal for them is currently not hooked up.

**Comment by bonaime** [comment]
Can you try
client.status_delay=2
after you created your client ? 

UNSET is usually return when there is a timeout from the arclink server.

**Comment by megies** [comment]
> SEED files which ObsPy can read but the polynomial response removal for them is currently not hooked up.

Actually, it should be possible to use polynomial response from SEED when reading with `obspy.xseed.Parser` and going via `seedresp={'filename': my_parser, ..}` option using evalresp.. or am i missing something?

Nevertheless.. as long as no additional requests or reports about this come in I would still see this as pretty low priority..

**Comment by krischer** [comment]
evalresp cannot deal with polynomial responses.

Now #566 by @bonaime implemented it for Parser objects but in the end we only added it for our internal response representation and thus StationXML: a6c5593c84b6a4a79d90a9eed7dae4edabf43727

Maybe we should also add the already coded option do to it from SEED files but then the actual functions to call become a bit messy I fear. I am not sure how to best approach this.

**Comment by megies** [comment]
> I am not sure how to best approach this.

I would tend to only work on this if there is actual demand.. with all the FDSN infrastructure popping up I am not sure how much this would be used really..

**Comment by barsch** [comment]
obsolete due to https://github.com/obspy/obspy/pull/1987
