### ISSUE TITLE
obspy.core.trace.Trace.trim(pad=..., fill_value=...) should provide a <type 'numpy.ndarray'> object

### ISSUE THREAD

**Issue by petrrr** [obspy/obspy#540]
Hey,
it looks like there is a minor issue in the case method trim() is used with a particular set of parameters, that is if padding is requested (pad=True) and a fill_value is specified as well.

Background:
- Default behaviour of trim() is to limit the resulting traces to existing data, and this works fine;
- In case padding is requested, the resulting data window is extended, a masked array is returned and non existing samples are masked; (as well the expected and documented behaviour);

From documentation and intuition, the "fill_value" parameter would serve to avoid creation of a masked array in the case padding is asked (2nd case). However, the behaviour is slightly different and a <class 'numpy.ma.core.MaskedArray'> object is still returned, but mask is set to True. See also below ...

``` python
In [31]: print tr
IV.MMN..HHZ | 2012-01-01T00:00:00.000000Z - 2012-01-01T20:50:58.990000Z | 100.0 Hz, 7505900 samples

In [32]: tr.trim(starttime=obspy.UTCDateTime("2012-01-01T20:00:00.000000Z"), endtime=obspy.UTCDateTime("2012-01-01T21:00:00.000000Z"), pad=True, fill_value=-999 )

In [33]: print tr
IV.MMN..HHZ | 2012-01-01T20:00:00.000000Z - 2012-01-01T21:00:00.000000Z | 100.0 Hz, 360001 samples

In [34]: print tr.data
[ -34.  -41. -107. ..., -999. -999. -999.]

In [35]: print type(tr.data)
<class 'numpy.ma.core.MaskedArray'>

In [36]: tr.data
Out[36]:
masked_array(data = [ -34.  -41. -107. ..., -999. -999. -999.],
            mask = False,
      fill_value = 1e+20)
```

I would argue that this "intermediate" behaviour is unexpected and not very useful. Providing a fill_value should prevent the creation of the masked array.

**Comment by echavess** [comment]
Hi Guys; 

I am trying to trim my waveforms centered around the p-wave arrivals. For that I am doing the next: 

```
st = read('main')
tr = st[0]
p = tr.stats.sac.a
ndata = tr.trim(p-5, p+5) # for cutting data 5 s before and 5 s after p-wave arrival. 

```
Although it does trim the waveform 5 s before P it doesn't do the same after P, instead, it gives me more than a minute waveform after P-arrival. The sample rate is 100Hz. 

Any ideas how can I trim my data correctly? 
Thanks in advance, 
Esteban

**Comment by megies** [comment]
Strange, but impossible to debug without the data, your code looks fine (if that `sac.a` is the UTCDateTime you're after)

**Comment by echavess** [comment]
Hi @megies, 

Here is the link to the data. I'll appreciate your help. 
[](https://www.dropbox.com/sh/d0h3yf4i063tb8k/AAB5LMOxafZZes-DvMzrymgza?dl=0)

Cheers; 
Esteban

**Comment by megies** [comment]
This `tr.stats.sac.a` is no absolute time but a float. I'm no SAC user but I guess it is to be interpreted to some other absolute time in SAC headers. `trim` with floats is cutting relative to starttime/endttime, although this is badly documented and only visible in the source code. See https://github.com/obspy/obspy/blob/master/obspy/core/trace.py#L948-L949 and https://github.com/obspy/obspy/blob/master/obspy/core/trace.py#L1015-L1016.

**Comment by jkmacc-LANL** [comment]
To get a useful `UTCDateTime` for trimming, I think you'd want to do something like:

```python
from obspy.io.sac.util import get_sac_reftime

t = get_sac_reftime(tr.stats.sac)
p = t + tr.stats.sac.a
ndata = tr.trim(p-5, p+5)
```

**Comment by echavess** [comment]
@jkmacc-LANL That works well. Thanks very much!

**Comment by jkmacc-LANL** [comment]
I'm glad that's helpful.  Obligatory disclaimer: `get_sac_reftime` is in part of ObsPy that is subject to change, so I'd caution against relying heavily on it.  It probably won't change anytime soon, but it's worth the warning.

**Comment by megies** [comment]
Thanks for posting the solution @jkmacc-LANL!
