### ISSUE TITLE
readSEGY - wrong header definitions or memory issue?

### ISSUE THREAD

**Issue by globusyna** [obspy/obspy#606]
We are trying to read 4.5 Gb segy file using readSEGY from obspy.segy.core.
With error message:
SEGYTraceReadingError: Too little data left in the file to unpack it according to
                  its trace header. This is most likely either due to a wrong
                  byteorder or a corrupt file.
Can this error arise due to memory issue if program reads file into stream object? 

Or is it more likely that header definitions in the file are wrong.
However no problems reading similar files but 4 times smaller.
(PC, windows, 8gb RAM)

With regards, Tatiana.

**Comment by savardge** [comment]
Hi, 
I have the same issue and it's not memory problems for sure. Obspy can read several hundreds of trace and suddenly fails with:

> SEGYTraceReadingError: Too little data left in the file to unpack it according to
>                   its trace header. This is most likely either due to a wrong
>                   byte order or a corrupt file.

Is there any way Obspy could salvage the good uncorrupted traces and skip the bad ones?
It is a very big file (15GB), but I can send a link to that file privately in an email to any Obspy developer who would like to give a closer look.
