### ISSUE TITLE
add alternative terms for Trace.stats attributes

### ISSUE THREAD

**Issue by barsch** [obspy/obspy#742]
I'm sometimes pretty annoyed by the terms we chose at the beginning of this project and would like to fix this a bit by introducing new alternative terms for most attributes of the `obspy.core.Trace.stats` AttribDict, e.g.:

`stats.network` -> `stats.net`
`stats.station` -> `stats.sta`
`stats.location` -> `stats.loc`
`stats.channel` -> `stats.cha`
`stats.sampling_rate` -> `stats.sr`
`stats.npts` -> `stats.number_of_points`

Maybe even add an alternative for `Trace.stats` by introducing `Trace.meta` or `Trace.metadata`.

Just to make sure: I don't want to delete anything - I just want to smooth the user experience by introducing more common/meaningful synonyms for existing terms.

Any other suggestions/ideas/comments?

**Comment by megies** [comment]
stale, closing.
