### ISSUE TITLE
links to github issues/PRs in docs

### ISSUE THREAD

**Issue by megies** [obspy/obspy#803]
Would be nice to use [matplotlib's Sphinx extension](https://github.com/matplotlib/matplotlib/blob/master/doc/sphinxext/github.py) in API docs to..
- make plain text issue references (e.g. `#783`) into github issue directive (e.g. `:ghissue:`783`:`) (postprocess output html pages?); would be especially nice for changelogs in API pages
- link to contributing users on github / dynamically create list of contributors (adding a static list of contributors outside of github)

see.. 
- http://matplotlib.org/users/github_stats.html
- http://matplotlib.org/_sources/users/github_stats.txt
- https://github.com/matplotlib/matplotlib/blob/master/tools/github_stats.py

**Comment by QuLogic** [comment]
There's actually [something built in to Sphinx](http://sphinx-doc.org/ext/extlinks.html) that works for stuff like issue trackers. We'd probably still have to change the issue number if moved off of GitHub though.
