### ISSUE TITLE
Request for supporting units.

### ISSUE THREAD

**Issue by petrrr** [obspy/obspy#845]
This is a spinoff from #841. I would argue that obspy should support consistent handling of units. I am not sure how far we want to go wrt sophistication, but at least there should be the possibility to store and track this information along with the trace, probably as stats attribute and to allow to:
- to store equivalent information as it is provided by some seismic format;
- to use units (or quantity) when requesting instrument response;
- to allow some operations to manipulate this info (e.g. integration, derivative);

At least we should be able to encode if we are dealing about counts, volts, displacement, velocity, acceleration for seismic data (probably other quantity will turn out useful) and which units are used exactly (nm/s vs. m/s vs. cm/s) or allow provide some scaling factor (maybe calib) is sufficient here.

@krischer provided the following link: http://pint.readthedocs.org/en/0.5.1/

**Comment by megies** [comment]
stale, closing.

Also this might be unrealistic, given the fact that users can modify trace data directly in arbitrary ways, which would lead to reported units not being valid etc
