### ISSUE TITLE
http://docs.obspy.org/tutorial/code_snippets/waveform_plotting_tutorial.html page is outdated

### ISSUE THREAD

**Issue by bonaime** [obspy/obspy#883]
Hi,

I have seen few problems on this page
http://docs.obspy.org/tutorial/code_snippets/waveform_plotting_tutorial.html

4.5. Creating a One-Day Plot
=> The graph should be updated. Dayplot now does display all the information of the trace

For this tutorial
http://docs.obspy.org/plot_directive/tutorial/code_snippets/waveform_plotting_tutorial_5.py  
- there is a DeprecationWarning:
```log
DeprecationWarning: The obspy.neries module is deprecated and will be removed with the next major release. To access EMSC event data please use the obspy.fdsn client (use `Client(base_url='NERIES')`), for access to ORFEUS waveform data please use the obspy.fdsn client (use `Client(base_url='ORFEUS')`) and for travel times please use obspy.taup.
  warnings.warn(msg, DeprecationWarning)
/usr/local/lib/python2.7/site-packages/obspy/imaging/waveform.py:471: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  (e.__class__.__name__, e.message)
/usr/local/lib/python2.7/site-packages/obspy/imaging/waveform.py:472: UserWarning: Could not download the events because of 'Exception: This service was shut down on the server side, please use the obspy.fdsn Client instead (with `base_url='NERIES'`).'.
```
and the graph is displayed without the Event information. 
- the graph needs to be also updated without all the trace information
- the example code displayed on the webpage loads a local file (st = read("/tmp/GR.BFO..LHZ.2012.108")) and the tutorial file use a webfile (st = read("http://examples.obspy.org/GR.BFO..LHZ.2012.108")). I think that both should use the same webfile

**Comment by bonaime** [comment]
7883f23d14e439719961f531f475e1c1d3397f32

**Comment by megies** [comment]
:+1:
