### ISSUE TITLE
Dispersion curves with obspy?

### ISSUE THREAD

**Issue by bgoutorbe** [obspy/obspy#898]
Is it the correct place to ask a question?

Anyway, I was wondering if it is possible to calculate a theoretical Rayleigh wave dispersion curve, from a simple Earth model given as input (flat, 1D), within obspy framework. My ultimate goal is to derive simple sensitivity kernels (derivative of the Rayleigh group velocity with respect to Vs at fixed period, function of depth) to serve for guide to a qualitative interpretation of dispersion maps.

If this is not possible is obspy, can anyone point me to an existing program, in Python or other?

thanks

**Comment by ThomasLecocq** [comment]
@bgoutorbe : seeing the progress of your code (https://github.com/bgoutorbe/seismic-noise-tomography) I suppose you have found some solutions already? Can we close this?

**Comment by bgoutorbe** [comment]
yes I found a solution, unfortunately not a pure Python one, using the Computer Programs in Seismology.
