### ISSUE TITLE
conda - official obspy binstar ?

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#914]
seeing this: https://github.com/obspy/obspy/tree/d62c10da1864232ae3de4aed0c299ef167e089db/misc/installer/anaconda/obspy , what prevents us to build an "official" obspy binstar account with conda packages for all platforms ?

**Comment by mbyt** [comment]
we are finally there https://binstar.org/obspy :o)

**Comment by ThomasLecocq** [comment]
Yeahhhhhhhhhhhhhhhhhhhhhhhhhhhhhh :-)
