### ISSUE TITLE
Possible memory leak in SeedLinkConnection.collect()

### ISSUE THREAD

**Issue by mbankdmt** [obspy/obspy#918]
I'm seeing memory usage growth when using SeedLinkConnection.collect() in a loop.

Linux or Windows
obspy 0.9.2
numpy 1.8.2
python 2.7.6

Can anyone confirm?

**Comment by QuLogic** [comment]
There was a [recent mailing list post](http://lists.swapbytes.de/archives/obspy-users/2015-January/001619.html) that claims this leak is caused by `range`. That being said, the development version will use the generator version of `range`, and this will likely fix the issue (assuming that is the cause).

**Comment by mbyt** [comment]
@mbankdmt could you comment on the status of this ticket?

Based on the above comment, the memory could be due to range (why ever???). However, this is replaced in current master --- therefore, does this problem still persist in master?

**Comment by mbankdmt** [comment]
I just cloned the latest master and did a run of the above code snippet against it. On my system the memory leak is still showing up.

**Comment by mbyt** [comment]
Just tried your script, and I think I can reproduce the issue. I got the following output:
```
...
gc: collectable <list 0x7f1ce7ebb9e0>
gc: collectable <list 0x7f1ce7ebb878>
gc: collectable <list 0x7f1ce7eb7b00>
Unreachable objects: 25
Additional memory usage after 10 packets: 0 bytes, 0 bytes/packet
Additional memory usage after 20 packets: 0 bytes, 0 bytes/packet
...
Additional memory usage after 150 packets: 4096 bytes, 27 bytes/packet
Additional memory usage after 160 packets: 24576 bytes, 153 bytes/packet
Additional memory usage after 170 packets: 49152 bytes, 289 bytes/packet
Additional memory usage after 180 packets: 65536 bytes, 364 bytes/packet
Additional memory usage after 190 packets: 90112 bytes, 474 bytes/packet
...
```

**Comment by mbyt** [comment]
With #940, the output is now:
```
...
gc: collectable <list 0x7f9752d4ebd8>
gc: collectable <list 0x7f9752aff1b8>
gc: collectable <list 0x7f9752affb90>
Unreachable objects: 33
Additional memory usage after 10 packets: 12288 bytes, 1228 bytes/packet
Additional memory usage after 20 packets: 12288 bytes, 614 bytes/packet
...
Additional memory usage after 190 packets: 16384 bytes, 86 bytes/packet
Additional memory usage after 200 packets: 16384 bytes, 81 bytes/packet
...
```

Looks good to me!

**Comment by mbyt** [comment]
@mbankdmt thanks a lot for reporting and the detailed analysis. Please reopen the issue, if this nevertheless did not resolve the problem.

I think a test in `obspy/seedlink/tests/test_seedlinkconnection.py` for this issue, based upon our above script is worth it. Are you motivated to contribute? If so please open a pull request for this. If not, I'll do that.

Thanks a lot for your help and fast responses!

**Comment by QuLogic** [comment]
Hmm, interesting that you still see a little bit of additional memory usage. Somehow I managed to get an even 0 out of it.

**Comment by mbyt** [comment]
This memory usage is correct from my point of view. On the script provided above, it measures the usage between the first iteration of the loop and any consequent. Therefore, I assume a constant value here is great.

Are my conclusions correct @mbankdmt ?

**Comment by mbyt** [comment]
And another update. Running this for quite a while now, gives me:
```
Additional memory usage after 29360 packets: 24576 bytes, 0 bytes/packet
Additional memory usage after 29370 packets: 24576 bytes, 0 bytes/packet
Additional memory usage after 29380 packets: 24576 bytes, 0 bytes/packet
Additional memory usage after 29390 packets: 24576 bytes, 0 bytes/packet
Additional memory usage after 29400 packets: 24576 bytes, 0 bytes/packet
Additional memory usage after 29410 packets: 24576 bytes, 0 bytes/packet
```
Same as 160 packets when the bug was still in. Therefore, I assume, we internally need to to resize once to 24576 but than we are OK. So we are constant for 29410 packages. Great work @QuLogic !
