### ISSUE TITLE
Tectonic plate boundary data

### ISSUE THREAD

**Issue by QuLogic** [obspy/obspy#921]
It can be useful when plotting to include plate boundaries. I'm sure there are other uses, similar to the Flinn-Engdahl regions. Alternatively, it could make sense to send this to a lower level, like Basemap and/or Cartopy.

There are a few sources of this data:
- [UTexas Institute for Geophysics](http://www.ig.utexas.edu/research/projects/plates/data.htm) - Available as GMT, KMZ, or shapefiles. Might be the newest data.
- [USGS](http://earthquake.usgs.gov/learn/kml.php) - Available as a KMZ (I have not viewed it.)
- [Peter Bird, 2002 compilation](http://peterbird.name/publications/2003_PB2002/2003_PB2002.htm) - Available in its own format. Seems pretty detailed, might have more seismological data.
- [Nuvel dataset](http://jules.unavco.org/GMT/) - Again, in its own format. Not sure of the origin, but it's linked from [EarthByte](http://www.earthbyte.org/Resources/resources_plate_boundaries.html). Might be the oldest result.

The one difficult thing to find in any of these is the license (except USGS, I guess). I think I tried contacting the UTexas one almost a year ago, but haven't seen any response.

**Comment by QuLogic** [comment]
[Here](https://github.com/fraxen/tectonicplates) is a copy of Peter Bird's plate data in a modern format. It's under the ODC, though I'm not sure how the transformation jives with any of Bird's rights (since I'm still not sure of his license.)

**Comment by krischer** [comment]
I checked with the author of the data and he checked with Bird so it should be all good!

**Comment by megies** [comment]
We can only include it under its original license (this ODC license thing). Is that a problem for our overall LGPL license?

**Comment by QuLogic** [comment]
I would not normally release _data_ as LGPL, since it's usually a software license. If we did include it, I'd just leave it as ODC-By. Based on [this GPL FAQ](http://www.gnu.org/licenses/gpl-faq.html#GPLOutput), data transformed by a program would not inherit its license, so I don't see why we'd need to keep the data LGPL just because it's in the same package.

**Comment by megies** [comment]
Well.. it's just that right now, *everything* in ObsPy that has a definitive license assigned to it is LGPL. Now if we start again including things under different licenses again.. dunno..

**Comment by ThomasLecocq** [comment]
why not contacting @fraxen and asking him to re-licence to LGPL ? is that complicated ?

**Comment by QuLogic** [comment]
True, but LGPL on data is a bit weird, and we've never really had anything large enough to care, I think (except maybe taup tables?) We could make a separate package for this, with a separate license, and more specific dependencies on fiona/shapely/cartopy/etc.

**Comment by megies** [comment]
That sounds like more complexity and more maintenance efforts. I guess we could have a routine in the code that downloads the files when it's first used. That way we could keep it out of the main repo. Either way has its drawbacks, I guess.
I just think it would really be a shame to get back to a license mix after all the hard work to sort everything out to LGPL.

**Comment by QuLogic** [comment]
If we'd only need to support Cartopy, it's easy to make a `Downloader` for it.

**Comment by krischer** [comment]
Could we not just have a submodule/subtree and keep in an `external` folder or something along these lines? This would only marginally complicate things and we don't get a dependency on Cartopy.

**Comment by QuLogic** [comment]
Well, yes, I meant it'd only be available with Cartopy.

**Comment by megies** [comment]
stale, closing.

Also, might be worth a thought to do this in cartopy directly, I'd wager
