### ISSUE TITLE
unpurged requests left behind at server

### ISSUE THREAD

**Issue by megies** [obspy/obspy#922]
People at GFZ just mentioned that we leave behind unpurged requests at server side. In principle we send a `PURGE` at the end of each request operation (e.g. https://github.com/obspy/obspy/blob/master/obspy/arclink/client.py#L363) but it seems that in some cases a `PURGE` is not sent..

**Comment by barsch** [comment]
obsolete due to https://github.com/obspy/obspy/pull/1987
