### ISSUE TITLE
Miniseed fixed header flags: begin event, end event, event in progress

### ISSUE THREAD

**Issue by sfieux** [obspy/obspy#925]
Hello,

I have a question about the expected behaviour of the `begin_event`, `end_event` and `event_in_progress` flags in a miniSEED file. I guess these flags are supposed to be related with each other, so I was wondering if the implementation in `obspy.mseed.util.set_flags_in_fixed_headers` was correct (for now, there is no correlation at all). I don't know the usual bahaviour of dataloggers, so I thought I would better ask here to know exactly how to change them if necessary.
- Event starting with the record: when `begin_event` is set, can `event_in_progress` be set?
- Event ending with the record: when `end_event` is set, can `event_in_progress` be set?
- Event contained in the record: are `begin_event` and `end_event` both set? How about `event_in_progress`?

**Comment by krischer** [comment]
I honestly don't know and from looking at the SEED documentation I guess it might be different for different dataloggers... @jwassermann, @CTrabant any clue about this?

**Comment by CTrabant** [comment]
Specifics on how to use these are not in the SEED manual.  I believe the intention is that they are related in the sense that a begin_event is always followed (eventually) by an end_event and that in between the two event_in_progress is set.

While these flags might be useful for a network operator as input into a detection system, they are rarely if ever relied on when using archive data.

Chad
