### ISSUE TITLE
Unclear starttime behavior using section plot and sac files

### ISSUE THREAD

**Issue by Permian** [obspy/obspy#926]
I've created a section plot using sacfiles, where the nzhour, etc. (or kztime) are equal to the origin time. The origin marker was set to zero.
It turned out that the starttimes used by obspy are different from the sac times, i.e. shifted by the sac header variable 'B'. Therefore, the travel times do not increase with epicentral distance. 

The correction for the starttime resulted in two problems (see full script below):

1.When I use the trim command
   `tr.trim(tr.stats.starttime-tr.stats.sac.b)`
   then the starttimes are equal to the origin time and the waves increase correctly with the distance. 
   BUT when I overwrite the trace starttimes using
  `tr.stats.starttime=tr.stats.starttime-tr.stats.sac.b`
   the traces are still shifted by the B value in the plot although the starttimes were correctly set.
   Why are the overwritten starttimes not recognized by section plot?
   What is the difference using trim command?   

2.Consequently, when I set the B variable to zero in the sac headers the starttime issue should be avoided. But this is not the case!
Indeed, the obspy starttimes are correct (=origin time) BUT the traces in the plot are still shifted by a time shift that equals the previous B value (which was set to zero)! 
How this can be?? This would mean that the B variable is also set somewhere else in the sac header and used by obspy?! 
I already have looked into the source codes of sacio and waveform plotting but I couldn't find an explanation for this curious starttime behaviors.

```javascript
st=read('*BHZ*sac')

print "starttime before correction"
for tr in st:
     print tr.stats.station, tr.stats.starttime, tr.stats.sac.b

## epicenter
eq_lat = st[0].stats.sac.evla
eq_lon = st[0].stats.sac.evlo
evdp = st[0].stats.sac.evdp
mag = st[0].stats.sac.mag
evtime = UTCDateTime('2008-06-13,23:43:46.79')  ## origin time


for tr in st:
        tr.stats.coordinates = ({'latitude': tr.stats.sac.stla, 'longitude': tr.stats.sac.stlo})
        tr.stats.distance = gps2DistAzimuth(tr.stats.coordinates.latitude,tr.stats.coordinates.longitude,eq_lat,eq_lon)[0]
        tr.trim(tr.stats.starttime-tr.stats.sac.b)   ### works
        #tr.stats.starttime=tr.stats.starttime-tr.stats.sac.b   ### does not work, ignored by section plot
        

print "starttime after correction"
for tr in st:
     print tr.stats.station, tr.stats.starttime, tr.stats.sac.b


## Plot for degrees: section plot ignores changed starttime of the traces?
#st.trim(evtime,evtime+2000)    ### works with trim
st.plot(fig=fig, type='section', plot_dx=1, dist_degree=True, ev_coord=(eq_lat, eq_lon), linewidth=.25, grid_linewidth=.25, time_down=True, norm='stream', scale=0.4, recordlength=2000)   ### does not work without trim

## or plot this way
#st.plot(fig=fig, type='section', plot_dx=1, dist_degree=True, ev_coord=(eq_lat, eq_lon), linewidth=.25, grid_linewidth=.25, time_down=True, norm='stream', scale=0.4, starttime=UTCDateTime('2008-06-13,23:43:46.79'), recordlength=2000)   ### works setting starttime=origin time
```

**Comment by mbyt** [comment]
@Permian could you comment on the status of the issue?

Does it still persist in master?

Regarding the SAC B header value (begin in the following code snipplet), the important section of code is this (https://github.com/obspy/obspy/blob/master/obspy/sac/sacio.py#L369)
```python
 # convert start time to sac reference time, if it is not default
if begin == -12345:
    reftime = starttime
else:
    reftime = starttime - begin
```

From my memory: The reference time in SAC might either be the time of the first sample (if the SAC B header value == 0.0) or the origin time of the event (see also http://seismolab.gso.uri.edu/~savage/sac/manual/newusers.html section "How SAC Handles Time").

As concrete example (https://github.com/obspy/obspy/blob/master/obspy/sac/tests/data/dis.G.SCZ.__.BHE_short):
* origin time at epicener (SAC reference time):  2004-01-03T08:09:02
* starttime of first sample at the station recording the seismogram (obspy starttime): 2004-01-03T08:16:09
* offset of starttime relative to origin time of epicenter (SAC B header value): 427 seconds

**Comment by megies** [comment]
I've just discussed with @Permian, this was most likely just a misunderstanding with manually setting a `b` header value in SAC and not adapting the start time. If problems pop up again, please feel free to reopen.
