### ISSUE TITLE
Need better integration methods

### ISSUE THREAD

**Issue by krischer** [obspy/obspy#941]
This a continuation of #924.

We want to have some better integration methods.

**Comment by QuLogic** [comment]
If we're going to add new methods, maybe we should have left the `type` keyword in?

**Comment by krischer** [comment]
Yea that makes sense. Feel free to add it directly in the master.

**Comment by QuLogic** [comment]
Also, ping @martinvandriel so we don't forget about the Lanzcos interpolation he has.

**Comment by megies** [comment]
@krischer, I think this can be closed, right?

**Comment by krischer** [comment]
Hmm...yea I guess the spline interpolation is quite good. It would still be nice to have some better differentiation methods (see http://www.holoborodko.com/pavel/numerical-methods/numerical-derivative/lanczos-low-noise-differentiators/ and other pages on the website) but this is a different issue.
