### ISSUE TITLE
Automatic PyPI deployment

### ISSUE THREAD

**Issue by QuLogic** [obspy/obspy#945]
Travis can be configured to [deploy to PyPI automatically](http://docs.travis-ci.com/user/deployment/pypi/). Seems like something that would make your life just a smidgen easier.

**Comment by QuLogic** [comment]
Plus [Windows with AppyVeyor](http://kirbyfan64.github.io/posts/using-appveyor-to-distribute-python-wheels.html).

**Comment by megies** [comment]
Hmm.. I think manually deploying to Pypi is not much of a hassle (compared to the days of testing the release before it ;-).. closing for now. Reopen if you like..
