### ISSUE TITLE
Base all waveform plugins on BytesIO instead of filenames

### ISSUE THREAD

**Issue by mbyt** [obspy/obspy#952]
Currently we have something similar to that:
```
def isGSE2(filename):
def readGSE2(filename, headonly=False, verify_chksum=True,
def writeGSE2(stream, filename, inplace=False, **kwargs):  # @UnusedVariable
```
for all waveform plugins.

I definitely think support for BytesIO similar to #950 makes sense for all waveform plugins. However, I propose to open the file in core.stream.Stream.{read,write} and pass the file pointer to the waveform `{is,read,write}XXX`. Then we have the logic for opening and closing the files only once and we basically enforce that all new waveform plugins support BytesIO 

Surely, this will break code out there which directly uses  `{is,read,write}XXX`. However, the most common and the only recommended way (e.g. st.write("GSE2") stays the same.

**Comment by krischer** [comment]
+1

Right now we also perform all kinds of magic in the main `read()` function which hides what is going on at times.

**Comment by megies** [comment]
> Surely, this will break code out there which directly uses {is,read,write}XXX. However, the most common and the only recommended way (e.g. st.write("GSE2") stays the same.

To..
 - avoid breaking existing code and..
 - further discourage use of these methods..

..we could leave the old routines (e.g. `readMSEED()`) for one major release cycle, deprecate them and unregister them in `setup.py`.. and switch to new private methods (e.g. `_read_MSEED()`) that register in `setup.py` with the new behavior.

**Comment by krischer** [comment]
I would honestly just make a cut with a new version (eventually ;-)). This is just too much work and most of these function actually state that they should **NOT** be called directly, e.g.:

http://docs.obspy.org/master/packages/autogen/obspy.mseed.core.readMSEED.html

So we never made any guarantees on the stability of these methods so they are fair game and can be changed however we desire :-)

**Comment by megies** [comment]
Yeah sure.. it's a bit overhead but not too much I would say. And it might be a good spot to actually make them private functions (to be even clearer about them not being intended to be used). Anyway.. I'm fine with either way to do it. :)

**Comment by mbyt** [comment]
> And it might be a good spot to actually make them private functions (to be even clearer about them not being intended to be used)

+1

**Comment by QuLogic** [comment]
Same/related to #852.

**Comment by megies** [comment]
Closing as a duplicate..
