### ISSUE TITLE
future and mock are build dependency

### ISSUE THREAD

**Issue by krischer** [obspy/obspy#958]
~~After merging #944 `future` is now a build dependency~~ EDIT: After merging #984 this is not longer the case.

We need to either bootstrap this or workaround it somehow. The best solution would of course be to have a non-pickled model serialization routine.

**Comment by QuLogic** [comment]
And so is `mock` now.

The main thing to get this done is to rewrite the `TauBranch` class somehow. There are (2, N) instances in the model. Each instance contains a few scalars, but _also_ some arrays, which are unfortunately different lengths. So while we can turn all the scalars into (2, N) arrays, we can't turn the others into (2, N, M) since M is not fixed. Once we have only arrays, we just need to use NumPy to save it.

**Comment by krischer** [comment]
Could we just serialize everything to JSON? I know its slow but it is very cross platform and the models only need to be read once.

**Comment by QuLogic** [comment]
Can we do that directly? Or do we still need to encoder/decoder class to do stuff? If it's the latter, we might as well try implementing [`object.__getstate__()`](https://docs.python.org/2/library/pickle.html#object.__getstate__) in some way to get pickling through NumPy to work.

**Comment by krischer** [comment]
No it would require a custom encoder/decoder. My reasoning would just be that its a more standard format then any of the filetypes numpy can serialize to.

**Comment by mbyt** [comment]
numpy arrays can directly be serialized to to binary using `ndarray.tofile()`. That's absolutely cross platform, same interface as C, however, the flexible size @QuLogic mentioned is a no go for this approach :\.

**Comment by krischer** [comment]
Its unfortunately not cross platform, see http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tofile.html

```
This is a convenience function for quick storage of array data. Information on
endianness and precision is lost, so this method is not a good choice for files
intended to archive data or transport data between machines with different
endianness. Some of these problems can be overcome by outputting the data
as text files, at the expense of speed and file size.
```

It probably unlikely to matter for any of the platforms of interest to us but if possible we might as well support other architectures.

**Comment by mbyt** [comment]
To my understanding, this is only the case, if you did not specify the endianess in the dtype you are serializing or not using this dtype for deserialization (`np.fromfile(.., dtype=dtype`). However, I never worked on a big endian architecture with numpy available .... so I cannot be sure ...

**Comment by krischer** [comment]
I don't know. Will it not always just dump the bytes in the native byteorder? It probably does not matter in any case as it would be pretty hard to get hands on some big-endian hardware I guess.

**Comment by mbyt** [comment]
no, definitely not, I use it a lot.

Do something like `np.array([1], dtype='>u4').tofile('one.bin')` and check out the result in the hex editor. All you need to do for deserialization is to remember that dtype (which might be structured).

Nevertheless, the major problem of this issue is a different one ;).

**Comment by mbyt** [comment]
> Each instance contains a few scalars, but also some arrays, which are unfortunately different lengths. So while we can turn all the scalars into (2, N) arrays, we can't turn the others into (2, N, M) since M is not fixed. Once we have only arrays, we just need to use NumPy to save it.

Do you know all this size in advance? If yes, one possible, but probably ugly solution could be to store all the scalars in `(2, N)` and an extra pointer to the non fixed `M` array. These non fixed `M` arrays could them self be stored in a structured array pool, which could look like:
```python
pool_dtype = np.dtype([
  ('arr1', '<f8', 815),
  ('arr2', '<f8', 700),
  ('arr3', '<f8', 623),
...
])
Where 815, 700, 623 represent the flexible sizes.

Thus in this example the pointer to the pool could be the three character string `arr[1-3]`.
```

**Comment by krischer** [comment]
What about just using `numpy.savez` and coming up with some naming scheme to distinguish the different arrays?

**Comment by megies** [comment]
Debian Squeeze (not so important probably, LTS til 2016) and Ubuntu Precise (LTS til 2017) have a too old mock version, I'm getting `patch() got an unexpected keyword argument return_value`.

**Comment by QuLogic** [comment]
Try:
```python
        with patch('obspy.core.util.libnames._load_CDLL') as load:
            load.return_value = taulib
```

**Comment by megies** [comment]
That (plus some numpy 1.6 backwards compat) solves it, thanks.

**Comment by megies** [comment]
See #984.
