### ISSUE TITLE
Multiple Warnings (Data integrity check failed) while downloading waveforms

### ISSUE THREAD

**Issue by bgoutorbe** [obspy/obspy#962]
Dear obspy developers,

I got strange warnings trying to download waveforms from IRIS client:

from obspy.fdsn import Client
from obspy.core import UTCDateTime

client = Client('IRIS')

st = client.get_waveforms('GT', 'BDFB', '*', 'BHZ', UTCDateTime(1993, 7, 23), UTCDateTime(1993, 7, 24))

This returns tons of warnings such as:

/usr/lib/python2.7/dist-packages/obspy/mseed/core.py:308: InternalMSEEDReadingWarning: (null): Warning: Data integrity check for Steim-1 failed, last_data=-1770, xn=0
  warnings.warn(msg[6:].strip(), InternalMSEEDReadingWarning)
/usr/lib/python2.7/dist-packages/obspy/mseed/core.py:308: InternalMSEEDReadingWarning: (null): Warning: Data integrity check for Steim-1 failed, last_data=499, xn=350
  warnings.warn(msg[6:].strip(), InternalMSEEDReadingWarning)
/usr/lib/python2.7/dist-packages/obspy/mseed/core.py:308: InternalMSEEDReadingWarning: (null): Warning: Data integrity check for Steim-1 failed, last_data=-2500, xn=-665
...

Should I worry about such warnings?

Thanks for your help
BG

**Comment by krischer** [comment]
Hi,

yea you should worry. Those warning come up if the checksum of some records in the file don't match the data. This happens if the data is corrupt so I guess you cannot really use it anymore. Best remove the offending parts or contact IRIS although I am not sure they can do anything about it.

You can also clearly see the corruption if you plot the data:

![blub](https://cloud.githubusercontent.com/assets/800487/6305156/63785bdc-b929-11e4-8155-6806a23f4c82.png)

Cheers!

**Comment by bgoutorbe** [comment]
yes I also had noticed that these data clearly seemed corrupted. However the warnings occur on various other dates, at which the corruption is not so clear, e.g.:

st = client.get_waveforms('GT', 'BDFB', '*', 'BHZ', UTCDateTime(1993, 7, 22), UTCDateTime(1993, 7, 23))

![figure_1](https://cloud.githubusercontent.com/assets/6411320/6305873/75c9f84a-b915-11e4-963e-3256d59c1420.png)

Is there a way to catch the warnings in order to discard the data? I tried something like this:

import warnings
warnings.filterwarnings('error')

but it is not working, because (I think) the warnings are encapsulated in a callback function.

thanks
Bruno

**Comment by bgoutorbe** [comment]
to complete my previous post, when I  use warnings.filterwarnings('error'), I get a lot of exception messages such as the ones below but the program does not actually raise any exception:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/usr/lib/python2.7/dist-packages/obspy/mseed/core.py", line 308, in log_error_or_warning
    warnings.warn(msg[6:].strip(), InternalMSEEDReadingWarning)
obspy.mseed.core.InternalMSEEDReadingWarning: (null): Warning: Data integrity check for Steim-1 failed, last_data=1723, xn=-449
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/usr/lib/python2.7/dist-packages/obspy/mseed/core.py", line 308, in log_error_or_warning
    warnings.warn(msg[6:].strip(), InternalMSEEDReadingWarning)
obspy.mseed.core.InternalMSEEDReadingWarning: (null): Warning: Data integrity check for Steim-1 failed, last_data=-370, xn=2314

**Comment by bgoutorbe** [comment]
ok I found a trick to catch the warnings, by redirecting sys.stderr to a custom object holding the error/warning messages.

**Comment by QuLogic** [comment]
Yes, the exception is raised in a callback from C code, so it does not bubble up entirely. I'm not sure there's any other way to catch them.
