### ISSUE TITLE
False Documentation imaging.beachball

### ISSUE THREAD

**Issue by miili** [obspy/obspy#967]
For plotting beachballs with `imaging.beachball` the documentation states `...where the coordinate system is 1,2,3 = Up,South,East which equals r,theta,phi)`.

However actually the conversion between Up, South, East (z,y,x) and r, theta, phi is as:

```
Mrr =  Mzz
Mtt =  Mxx
Mpp =  Myy
Mrt =  Mxz
Mrp = -Myz
Mtp = -Mxy
```

Maybe this should be documented correctly.

**Comment by QuLogic** [comment]
> Up, South, East (z,y,x)

Are you sure about this one? That's not a right-handed system.

**Comment by mbyt** [comment]
@QuLogic I fully agree, Up, South, East is not a right-handed system. However, this is what it stated in the doc since a long time. So you think we have a general problem here? Or is it just the z,y,x which is not an ideal convention from your point of view?

**Comment by QuLogic** [comment]
I'm not sure what the usual convention is here; the simplest is just to swap `x` and `y`, so that South == `x` and East == `y` and you'd get a right-handed system again. That would change the conversion again; I haven't worked out whether it would match the original documentation.

**Comment by QuLogic** [comment]
Actually, reading it again, it says `(1,2,3) == (Up,South,East)`, which is really `(x,y,z)==(Up,South,East)` and would be correctly right-handed. Does that correct the conversion?

**Comment by mbyt** [comment]
Yes, this could be it. Perhaps for the doc it is the best to replace for the conversion explanation z,y,x with 1,2,3: `Mrr=M11, Mtt=M33, Mpp=M22, Mrt=M31, Mrp=-M21, Mtp=-M32`. @miili ?

**Comment by miili** [comment]
@QuLogic yes, my mistake it is `x, y, z = U, S, E` after the documentation.

@mbyt yes this is it, maybe just put this into the documentation of the two `obspy.imaging` methods?

**Comment by QuLogic** [comment]
I'm still uncertain as to why U, S, E are different from r, theta, phi?

I looked at _Modern Global Seismology_, page 351, Box 8.3 "Moment Tensor Conventions" and it states "vectors r-hat, theta-hat, phi-hat point upward, southward, and eastward, respectively". I don't know why the negative signs are necessary, then?

**Comment by miili** [comment]
The signature was necessary for me to plot the beachball in the right orientation.
Maybe just mention the relation between `x, y, z` and `r, theta, phi` in the documentation to avoid confusion.
It could be that x, y, z does not translate to U, S, E as per convention.

@QuLogic What is `r, t, p *^hat*`?

**Comment by zduputel** [comment]
There are basically two conventions commonly used in seismology :
- A convention where we have (x,y,z) at the source as (North, East, Down)... this convention is used for example in Aki and Richards book (Quantitative Seismology, cf. 2nd paragraph in Box 4.4 attached).
- Another convention used in normal mode studies based on the coordinates (r, theta, phi) where the moment tensor components at the source are given with directions (Up, South, East). This convention is used for example by Harvard CMT and Global CMT (cf., Dziewonski et al., JGR 1981).

It follows that components of M in the two systems are related by:
Mrr = Mzz 
Mtt = Mxx 
Mpp = Myy 
Mrt = Mxz 
Mrp = -Myz 
Mtp = -Mxy

![screen shot 2015-03-03 at 15 49 17](https://cloud.githubusercontent.com/assets/5542937/6464776/e8babdee-c1bc-11e4-90bc-52eb62d0369e.png)

**Comment by QuLogic** [comment]
> The signature was necessary for me to plot the beachball in the right orientation.

Right, but just to confirm, `U, S, E` are the same as `r, theta, phi`? You just incorrectly assigned _Cartesian_ `x, y, z` to `U, S, E`.

> Maybe just mention the relation between x, y, z and r, theta, phi in the documentation to avoid confusion.

Yes, that would likely reduce the chance of this problem.

> @QuLogic What is r, t, p *^hat*?

*^hat* is the convention for unit (basis) vectors.

**Comment by mbyt** [comment]
Therefore, the documentation should read as follows (new part is bold)?

Focal mechanism that is either number of mechanisms (NM) by 3 (strike, dip, and rake) or NM x 6 (M11, M22, M33, M12, M13, M23 - the six independent components of the moment tensor, where the coordinate system is 1,2,3 = Up,South,East which equals r,theta,phi **- Harvard/Global CMT convention).  The relation to Aki and Richards x,y,z equals North,East,Down convention is as follows: Mrr=Mzz, Mtt=Mxx, Mpp=Myy, Mrt=Mxz, Mrp=-Myz, Mtp=-Mxy.** The strike is of the first plane, clockwise relative to north.

**Comment by QuLogic** [comment]
That makes sense to me.
