### ISSUE TITLE
SEISAN Waveform import bug

### ISSUE THREAD

**Issue by EPAnt** [obspy/obspy#970]
It seems there is a bug when importing SEISAN waveform files. This can be checked when importing the test files in ```obspy/seisan/tests``` . Basicaly, the last sample of the data array usually has an unusually high value, resulting in a strange jerk/pulse in the waveform file. Because of this I usually just do
``` python
for el in st: el.data=el.data = el.data[:-1]
```
to delete the last sample...

I provided two waveform files, one in SEISAN, and another in MSEED which was converted from the SEISAN waveform using SEISAN/wavetool . However, I have tested the test waveforms already provided in the repository ```obspy/seisan/tests/data``` and the results is the same, altough the amplitude of the waveforms does obsfuscate this bug sometimes...

**Comment by ThomasLecocq** [comment]
Not sure it's a bug... I noticed this when converting some SEISAN and I suspected it was some "sync -second pulse" ? Where are the files you attached ? Do both waveforms have the same number of points ?

**Comment by QuLogic** [comment]
I'm closing this one in favour of #969.
