### ISSUE TITLE
libmseed 2.14 released

### ISSUE THREAD

**Issue by CTrabant** [obspy/obspy#976]
Version 2.14 of libmseed has been released:
https://seiscode.iris.washington.edu/projects/libmseed/files

Changes from the 2.13 version (currently in master):
https://seiscode.iris.washington.edu/news/31

The closing of a memory leak that could be encountered during errors in packing miniSEED records is the most significant change.  There is also supported added for minimalistic handling of leap seconds defined in a standard leap second file.

**Comment by megies** [comment]
Thanks for letting us know, Chad!

**Comment by mbyt** [comment]
@CTrabant definitely: thanks for letting us know.

Alls tests pass:
* windows: https://ci.appveyor.com/project/obspy/obspy/build/1.0.154-master
* linux: https://travis-ci.org/obspy/obspy/builds/53992816

**Comment by QuLogic** [comment]
This [infinite loop bug](https://seiscode.iris.washington.edu/issues/617) was not fixed (and the fix was undone in #977). I'm not sure how the tests passed without it though.

**Comment by QuLogic** [comment]
> Perhaps some alternative change was made.

Evidently something did fix the problem for the test file, but did not fix the infinite loop. The re-applied fix is in #978.
