### ISSUE TITLE
Use os.path.expanduser when resolving local file paths?

### ISSUE THREAD

**Issue by megies** [obspy/obspy#979]
I think we should consider using `os.path.expanduser` (and maybe even `os.path.expandvars`) when reading local files, right now something like `read("~/some.mseed")` doesn't work.

**Comment by krischer** [comment]
+1

Although if you just use tab completion in ipython it expands it for you ;-)

**Comment by barsch** [comment]
http://stackoverflow.com/questions/10487827/why-am-i-forced-to-os-path-expanduser-in-python

**Comment by megies** [comment]
Ok, so maybe better not do it automatically to avoid garbling potentially valid (and rather weird) filenames..
