### ISSUE TITLE
Releasing 0.10.0/0.10.1

### ISSUE THREAD

**Issue by krischer** [obspy/obspy#987]
Hi all,

in order to avoid the mess we had during our last release I would like to coordinate this release a bit. From my point of view we can tag and release as soon as everything in this issue is taken care off.

* [x] Test the source distribution.

   - source distribution looks good to me (@megies, Debian 7 wheezy, anaconda python 2.7/3.4), non-network tests all pass. we definitely have to do something about `MANIFEST.in` though, things will get left out in the future again if we don't change something

Can some people please install via

```bash
$ pip install https://www.geophysik.uni-muenchen.de/~krischer/obspy-0.9.2.dev0-2226.g8cc48.obspy.master.tar.gz
```

and run `obspy-runtests` or `obspy3-runtests` respectively. This is the final distribution that ends up on pypi so we should make sure it contains everything we need.

* [x] Build `*.egg` and `*.exe` distributions for Windows once 0.10.0 is tagged. I guess this goes to @barsch.

* [x] Do we want wheels? If yes we have to build them.

 - wheels for linux can be built by pushing a commit to #685 after tagging and then found in obspy/wheelhouse

* [x] What's new page. I started a page to introduce people to whats new in the new version here: https://github.com/obspy/obspy/wiki/What's-New-in-ObsPy-0.10.0
Please feel free to edit it. It's meant as advertisement so please add pictures and what not.
I got the list of contributors with `git shortlog -n -s master...0.9.2` so please add people if I forgot someone.

* [x] Updating installation instructions and other wiki pages.

* [x] Post release message to user mailing list (and announcements list) once everything is ready. This honor goes to @QuLogic for being a super active new contributor :-)

**FOR ALL PACKAGES: PLEASE BE AWARE THAT OBSPY IS NOW PY2K and PY3K SO YOU MIGHT HAVE TO BUILT MULTIPLE PACKAGES**

* [x] Build Anaconda packages for all platforms and tests them on a number of other platforms. We still need Windows builds and Linux builds from older libc versions. Please use the branch in #982 for this.

   - Windows and Linux (libc 2.14) conda packages can be built by adjusting and pushing to obspy/conda-builder.

* [x] Debian/Ubuntu packages. Packaging looks good right now and packages can be built after tagging (@megies)

* [ ] Raspian packages. @megies 

* [x] Fedora/RHEL/CentOS packages. I think these are also good to go. @QuLogic 

* [x] Macports packages. @petrrr 

* [ ] What about OpenSUSE packages?

* [ ] NetBSD/FreeBSD; see #824 - I guess we can try to contact the people who built them.

* [ ] Other packages? If yes, which? And what is the status of these?

* [x] Fix tests page to support the new version scheme

* [x] Did I forget anything else? Feel free to edit this post.

We'll tag as soon as enough people report back that building packages works fine.

**Comment by krischer** [comment]
Release message draft for mailing list, please edit!

---

Dear ObsPy Users,

after over 2200 commits from 25 contributors ObsPy 0.10.0 is finished and has been released. 

The new key features are support for Python 3, a slew of new file formats, and a new TauP implementation. A detailed list of changes with much more information can be found here: https://github.com/obspy/obspy/wiki/What's-New-in-ObsPy-0.10.0

Full changelog: https://github.com/obspy/obspy/releases/tag/0.10.0

The new release is up on PyPi (including Windows binaries), we have Anaconda packages for all platforms, and the Debian/Ubuntu packages have also been updated. 

Installation guides for various platforms can be found in the wiki: https://github.com/obspy/obspy/wiki#installation

All the best and let us know if you experience any problems,

the ObsPy Development Team

**Comment by petrrr** [comment]
Hi Lion,
great news that 0.10.0 is about to be released.

Please note that for Macports the package is build automatically after committing the updated port. So there is no action needed before official release, but immediately after publishing on PyPI. 

However, I will do some testing with the release candidate and report back. I will check the box for Macports as soon I can comfirm that all is well.

**Comment by petrrr** [comment]
BTW: To we really want to keep the obspy-* / obspy3- distinction? 
Obspy 3 basically makes little sense to me. There are some package manages which add a `-3` o `-34` at the end, but shouldn't this be left install environment to decide how to handle this?
For example for Macports I will need to patch this.

**Comment by krischer** [comment]
I tend to agree. Apparently this was needed for the debian/ubuntu packages so @megies can give a more informed opinion. If possible I would also vote to remove this distinction if not we can also deal with it.

**Comment by megies** [comment]
In deb packaging, packages for python2 and python3 need to be separate packages. But.. the executables for e.g. `obspy-runtests` end up in the same directory `/usr/bin` and thus they would collide and essentially nobody knows which one is currently on the system..

> but shouldn't this be left install environment to decide how to handle this?

So how is it supposed to work..? If you `pip2 install obspy` and then afterwards `pip3 install obspy` you're overwriting the previously installed `obspy-runtests` (Py2) with it's Py3 counterpart. Is this the desired/expected behavior?

I'll happily listen to any other solutions to this collision..

**Comment by krischer** [comment]
I usually only work with virtual/conda envs and thus two python versions are never active at the same time. I think the scripts should have the same name no matter the python version but they should be renamed for specific purposes like the debian packages where I see your point. Could this be done during package building in the case of debian?

**Comment by megies** [comment]
> Could this be done during package building in the case of debian?

Ah well, I'll move it to deb packaging, exclusively then.

**Comment by petrrr** [comment]
Yes, I think this is the better solution as any package environment has it own conventions here.  Thanks!
Actually, Macports also renames the scripts for different versions, but it is handled by the packages manager.

**Comment by mbyt** [comment]
I'd vote against eggs and wheels.

Just in order to simplify maintenance (at least for me coding is more fun than packaging ;o). If people do not like conda nor the packages for their operating system (exe, deb, rpm,...), they still can install from source --- hey it's easy now, no fortan needed anymore, hurray!

**Comment by mbyt** [comment]
And by the way, impressive ticket, great what's new document, and great release email.

One thing I'm not sure about is, if we should actively ping the package maintainers of these operating systems. Usually it's the other way around, people release and the "os" guys follow the mailing list and do the remainder...

**Comment by petrrr** [comment]
Hi guys, 
I am observing a version conflict between the most recent releases of pep8 @1.6.2 and flake8 @2.4.0 which claims to require pep8 < 1.6. Not sure if this is real, or could be removed. Has anyone came across this?
```
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pep8 1.6.2 (/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages), Requirement.parse('pep8<1.6,>=1.5.7'))
```

Also: On my system the tests output does not really look very clean:

```
petr% obspy3-runtests-3.4
.....................................................................................................................................................................................................................E..sss..................................................................................................................................................................................................................................................................................ss..s....................................................................................................s..Warning: underflow encountered in multiply
Warning: underflow encountered in multiply
Warning: underflow encountered in multiply
Warning: underflow encountered in multiply
Warning: underflow encountered in multiply
Warning: underflow encountered in multiply
Warning: underflow encountered in multiply
..........Warning: underflow encountered in double_scalars
Warning: underflow encountered in multiply
.Warning: underflow encountered in double_scalars
Warning: underflow encountered in multiply
.Warning: underflow encountered in double_scalars
Warning: underflow encountered in multiply
.............................................................................Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/obspy/mseed/core.py", line 346, in log_error_or_warning
    raise InternalMSEEDReadingError(msg[7:].strip())
obspy.mseed.core.InternalMSEEDReadingError: Invalid blockette offset (12365) less than or equal to current offset (12365)
.........................................................................................................................................................................................................................................................................................................................................................................................sss...sss.......................................

................................................................................

```

Doesn't give a good impression. Is this something which can be fixed easily?

**Comment by QuLogic** [comment]
Stuff from me:
 - [ ] Test the source distribution.
 - [ ] Review What's new page.
 - [ ] Updating installation instructions and other wiki pages.
 - [ ] Fedora/RHEL/CentOS packages.

**Comment by petrrr** [comment]
This is not directly related to the Obspy release itself but to the overall image of the project:
- [ ] fix tests page to support the new version scheme

Moreover, I'd argue that the truncated hash in the new version scheme will be to short to be resolvable by GitHub. 

https://github.com/obspy/obspy/tree/0.9.2-2230-ga014
vs.
https://github.com/obspy/obspy/tree/0.9.2-2230-ga014c844e4

**Comment by QuLogic** [comment]
> Also: On my system the tests output does not really look very clean:

We should maybe ignore the underflows instead of printing them, but you can use `obspy-runtests -q` if you want really quiet, though I'm not sure it will hide the C printing stuff.

**Comment by QuLogic** [comment]
As an FYI, 7 characters is the minimum for unambiguous hashes (so far):
```
$ git log --all --pretty='format:%H' | cut -c -7 | sort | uniq -c | sort -r | head -1
      1 fffdd0d
$ git log --all --pretty='format:%H' | cut -c -6 | sort | uniq -c | sort -r | head -1
      2 e423f2
```

**Comment by QuLogic** [comment]
Fedora/CentOS builds are ready to go, based on a014c844e4cc89b5ddced4f12df8757f12ff0a79 (latest master).

**Comment by barsch** [comment]
maybe its time to introduce with 0.10.x a new tag ```<hash></hash>``` in the root of each test reports and get rid of ```<installed></installed>``` for each sub module, see http://tests.obspy.org/22737/xml/

**Comment by krischer** [comment]
#982 now builds conda packages for Linux 32/64 bit on CentOS 6 using Docker. It can also build OSX packages. It builds on CentOS 6 as it has a fairly low version libc for maximum compatibility. Can people please test the packages on as clean as possible Anaconda/Miniconda installations?

```bash
$ conda install -c obspy obspy
```

should do the trick.

**Comment by krischer** [comment]
Now we only need to manage windows conda packages.

**Comment by krischer** [comment]
@mbyt I think we definitely want windows eggs at least. They are the reason `easy_install obspy` usually works just fine. I guess the same argument can be made for `pip` and wheels.

**Comment by megies** [comment]
> Why are some 4 and some 10? Anyway, we should probably increase it. The default git describe is 7.

That is a complete miracle to me, we have `__version__ = _getVersionString(abbrev=10)` in our top-level `__init__.py`.

**Comment by petrrr** [comment]
Concerning the hash length, I recall that at least in one occasion the length=7 hash (default describe string) was not resolved. So I propose to stick to len=10.

**Comment by megies** [comment]
Again, we had `10` as length in there for a loooong time. I have no idea how anything shorter can pop up in our version number.

**Comment by petrrr** [comment]
Well, my obspy.__version__ is correct, when committing a test, it is truncated. So it either happens on submission or it is the just the visualization on the tests page.

**Comment by petrrr** [comment]
I have an other one. I just submitted test: http://tests.obspy.org/22772/
To me this looks like obspy is using a recent feature of matplotlib.
- [ ] add appropriate constrain on motplotlib version
Anyone has an idea when which version we need?

**Comment by megies** [comment]
baseline images are done with 1.3.1. yours is a different problem, maybe try this http://askubuntu.com/questions/578129/plotting-with-matplotlib-in-python-3-pylab-tkinter-and-qt-fontmanager-errors/578130#578130

**Comment by petrrr** [comment]
Thanks @megies for the link. Solved!

**Comment by mbyt** [comment]
> @mbyt I think we definitely want windows eggs at least. They are the reason easy_install obspy usually works just fine on windows. I guess the same argument can be made for pip and wheels.

@krischer alright understood, let's do that. I just wanted to make sure, that we are doing more coding in the future than packaging :o).

**Comment by petrrr** [comment]
I remember that for debian there were manpages for scripts. Are these still around? Can they remain in the PyPI package?

**Comment by mbyt** [comment]
Man pages are now auto build within the setup.py see:
* https://github.com/obspy/obspy/blob/master/setup.py#L133
* https://github.com/obspy/obspy/blob/master/setup.py#L559
however, never tried it by myself...

**Comment by mbyt** [comment]
Ah sorry, and one further thought with respect to supporting multiple differing package types. Do we need to do this all over again, as soon as we deliver the first bug fix release?

**Comment by QuLogic** [comment]
> Do we need to do this all over again

I think the big problem is the new Python 3 support, and the new packaging format. Probably once this stuff is smoothed out, most of this work won't be necessary the next time (one can hope, anyway).

**Comment by krischer** [comment]
0.10.0 is tagged, start your packaging engines!

**Comment by krischer** [comment]
For bugfixes, please once again adhere to our branching model:

https://github.com/obspy/obspy/wiki/ObsPy-Git-Branching-Model

**Comment by mbyt** [comment]
> 0.10.0 is tagged, start your packaging engines!

Cool, great!

> For bugfixes, please once again adhere to our branching model:

And I just fell in love with simple way by committing everything to trunk, eh s/trunk/master/g --- just kidding

**Comment by QuLogic** [comment]
Just an FYI, `RELEASE-VERSION` is not included within GitHub's automatic packages, so be sure to set the version accordingly.

**Comment by krischer** [comment]
Yea...the github releases are never correct...but the pypi ones are. So all packages should be built from the pypi release.

**Comment by petrrr** [comment]
I know strictly this is now not relevant. But I wonder if we still need to keep numpy as a build dependency. After removing all Fortran, we might live without.

**Comment by petrrr** [comment]
@krischer: There is a actually a minor issue with the PyPI packages. It untars only with permissions to the user. This is pretty unusual and causes permission problems, at least on Macports, especially for the `obspy.egg-info`. I could fix this, but maybe this will cause problems to other people/packaging systems as well.

**Comment by QuLogic** [comment]
Since we're pointing out issues with the PyPI packages, they're missing some top-level stuff, like the changelog, readme, etc. There also appears to be an extra `tmp` directory.

**Comment by petrrr** [comment]
Just in case you are planing to update the PyPI tarball: PLEASE avoid any stealth updates, these are horrible to handle for packaging systems.

**Comment by krischer** [comment]
@petrrr Good point with the permissions. I guess the permission issue disappears if we release as a zip file?

@QuLogic I guess we have to have real files instead of symlinks there

@megies Remove your `tmp` dir ;-)

@barsch Can you give me (krischer on pypi) push rights to the obspy packaging

Where all these issues not there on the source distribution I linked to in the first post in this issue? If not, then we can just a source distribution from my machine.

**Comment by krischer** [comment]
@petrrr Can we not just silently update tonight? I guess nobody except you will see the issue otherwise. otherwise we will of course not just silently update

It will not even update any code just permissions and other issues.

**Comment by QuLogic** [comment]
[Set umask before building](http://stackoverflow.com/a/18604540) to fix permissions.

**Comment by megies** [comment]
> @megies Remove your tmp dir ;-)

You said no, when I asked if I should go to a clean checkout for pushing to pypi..

**Comment by krischer** [comment]
fair enough ;-)

**Comment by megies** [comment]
@petrrr care to join gitter chat? Is it a problem for you if I remove pypi tarball?

**Comment by QuLogic** [comment]
I guess I'll send the announcement once some of these packages are ticked off at the top...
