### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by c546824** [obspy/obspy#990]
congratulations on the new release!

a minor point, the link to taup tutorial looks broken...
http://docs.obspy.org/tutorial/code_snippets/travel_time.html

**Comment by QuLogic** [comment]
Documentation hasn't been built yet.

**Comment by QuLogic** [comment]
> congratulations on the new release!

And thanks, BTW!

**Comment by QuLogic** [comment]
FYI, the new documentation is now available.
