### ISSUE TITLE
Provide a more complete help for the setup.py script.

### ISSUE THREAD

**Issue by petrrr** [obspy/obspy#991]
It would be great if `setup.py --help` would become really meaningful. Currently there are several undocumented commands and flags. The ones I noted during packaging are:
 - ~~`build_man`~~
 - ~~`install_man`~~
 - `--manprefix=`

But probably there are others I am not aware of.

**Comment by QuLogic** [comment]
Try `python setup.py --help-commands`?

**Comment by petrrr** [comment]
Sorry, my bad. `--help-command works`, and now I remember I already came across this ;-/. How would I get informed about the --manprefix?

**Comment by petrrr** [comment]
Again, my bad. But now I reply to myself ;-) Its: `python setup.py install_man --help`. 
Sorry for the noise! I am a bit tired.

**Comment by petrrr** [comment]
Just one related doubt. I understand that something like 
`python setup.py install_man --manprefix=${prefix}/share/man --root=${destroot}` should be possible. 
That is providing installing into a dedicated destroot directory. Is this really working like this?

**Comment by QuLogic** [comment]
Yes, I use `--root` for building RPMs. I'm not sure about the combination with `--manprefix=` as it's not necessary here. Based on the code, `manprefix` is for the destination _root_, i.e., specifying both should do `${destroot}/${prefix}/share/man` (if I read it correctly.)

**Comment by petrrr** [comment]
Yes it works.

**Comment by petrrr** [comment]
There might be one small issue though. I would expect that `build_man` would generate that manpages (and it does) and if they are already generated `install_man` would only install/copy them. However, I see that `install_man` always recreates them. No big deal though.

**Comment by QuLogic** [comment]
Use `--skip-build` like for `install`.
