### ISSUE TITLE
SCEDC webservice access not working

### ISSUE THREAD

**Issue by SCEDC** [obspy/obspy#998]
Hi, we have started investigating whether our webservices (http://service.scedc.caltech.edu/) can be accessed from ObsPy.

First we need to update the URL mappings -- 
In [2]: from obspy.fdsn.header import URL_MAPPINGS

In [4]: for key in sorted(URL_MAPPINGS.keys()):
   ...:     print("{0:<7} {1}".format(key,  URL_MAPPINGS[key]))

We need to change the entry for "SCEC" to this:

SCEDC    http://service.scedc.caltech.edu

When we tried accessing our URL (service.scedc.caltech.edu) - we got this output:
"NotImplementedError: Bad request. Please contact the developers.”

Can you direct us on how to resolve these issue?

**Comment by krischer** [comment]
Hi,

we can change the mapping, no problem.

To use the service you also have to specify the protocol, so

```python
from obspy.fdsn import Client
c = Client("http://service.scedc.caltech.edu")
```

should do the trick.

Your service currently does not provide `application.wadl` files which are required according to the FDSNWS standard. ObsPy uses these to discover what the particular FDSNWS implementation is capable of.

Right now you have dataselect and station services, so the following URLs must return WADL files in order to be standard compliant:

http://service.scedc.caltech.edu/fdsnws/dataselect/1/application.wadl
http://service.scedc.caltech.edu/fdsnws/station/1/application.wadl

Example files from IRIS:

http://service.iris.edu/fdsnws/dataselect/1/application.wadl
http://service.iris.edu/fdsnws/station/1/application.wadl

All the best,

Lion

**Comment by krischer** [comment]
Once you provide these files, ObsPy should work fine with your FDSN web service.

**Comment by megies** [comment]
Seems the [application.wadl](http://service.scedc.caltech.edu/fdsnws/station/1/application.wadl) was added in the meantime, although the webservice is still experiencing problems internally. At least connecting to the webservice works, so I'll close this now. Please reopen if necessary.

I'll also change the URL mapping to:
```python
"SCEC": "http://service.scedc.caltech.edu"
```
I would prefer to leave it `SCEC` and not change it to `SCEDC` as people might already be using `SCEC` in their code. If it is important for you to change it to `SCEDC` please let us know, we could manually catch this in the code, although I would like to avoid blowing up the code for this minor issue.

**Comment by QuLogic** [comment]
Uh, are you sure `SCEDC` replaces `SCEC`? One is at Caltech, the other is at USC.

**Comment by megies** [comment]
Not sure at all, just thought @SCEDC knows what's going on and the URL we used to have (http://www.data.scec.org) forwards to SCEDC in big friendly letters?

**Comment by QuLogic** [comment]
Ah, interesting. Would be useful if [the main page](http://www.scec.org/) mentioned it too.

**Comment by megies** [comment]
SCEDC site is mentioning some website move in the news (although the full story link is broken). Just a wild guess, this might be about merging waveform/earthquake resources to one web service endpoint?

**Comment by CTrabant** [comment]
> Ah, interesting. Would be useful if the main page <http://www.scec.org/> mentioned it too.
> 
SCEC is a large, multi-institution consortium.  The SCEDC is one data resource of SCEC and is at the top entry on their data resources page:

http://www.scec.org/resources/data/index.html <http://www.scec.org/resources/data/index.html>

You should use SCEDC, it is more specific and appropriate for the FDSN WS endpoints they have identified.

**Comment by SCEDC** [comment]
Hi,

Sorry to have joined this thread so late.  Yes, please use SCEDC.  As Chad mentioned, we are a data resource for SCEC and receive partial funding from them, but we are run out of Caltech and serve as the seismic archive of the Southern California Seismic Network.  We are trying to make our web services more similar to that of IRIS and data centers such as the NCEDC.

**Comment by QuLogic** [comment]
OK, great, with that cleared up, should we be adding a `SCEDC` alias or just use `SCEC` by itself?

**Comment by SCEDC** [comment]
Please use SCEDC.

**Comment by SCEDC** [comment]
Btw. Thanks for pointing out the broken link for our news page.  We are still doing development to get the webservices functional in Obspy.
-Ellen

**Comment by megies** [comment]
So, just to be sure-sure before I add a reroute/deprecation warning for `SCEC`. This is a *replacement* for the old `SCEC` FDSNWS URL, right?

**Comment by SCEDC** [comment]
Yes - that is correct. - Ellen

**Comment by megies** [comment]
Ok, thanks for clarification.

**Comment by SCEDC** [comment]
Hello,

This is Aparna Bhaskaran, a developer at SCEDC. I am facing some issues trying to use obspy with our web services to get waveform data. I installed obspy via Anaconda and am using python 2.7. I get the following error.

{aparnab@iron:bin} ./python2.7
Python 2.7.9 |Anaconda 2.1.0 (64-bit)| (default, Mar  9 2015, 16:20:48) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> from obspy.fdsn.client import Client
>>> client = Client("http://service.scedc.caltech.edu")
>>> from obspy import UTCDateTime
>>> t2 = UTCDateTime("2015-03-29T00:00:00Z")
>>> t1 = UTCDateTime("2015-03-28T23:00:00Z")
>>> st = client.get_waveforms("CI", "ISA", '**', "LHE", t1, t2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aparnab/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-linux-x86_64.egg/obspy/fdsn/client.py", line 594, in get_waveforms
    data_stream = self._download(url)
  File "/home/aparnab/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-linux-x86_64.egg/obspy/fdsn/client.py", line 1188, in _download
    raise NotImplementedError(msg)
NotImplementedError: Bad request. Please contact the developers.


The same request works via the web service form. What am I missing in my implementation of the web service that is making obspy unhappy? Please advice.

regards,
Aparna

**Comment by krischer** [comment]
Hi Aparna,

if you initialize the client with

```python
client = Client("http://service.scedc.caltech.edu", debug=True)
```

you can see the exact error message and what URLs are being downloaded. In the case you demonstrated above, the attempted URL is

http://service.scedc.caltech.edu/fdsnws/dataselect/1/query?network=CI&station=ISA&location=%2A%2A&starttime=2015-03-28T23%3A00%3A00.000000&endtime=2015-03-29T00%3A00%3A00.000000&channel=LHE

and your service complains about the `endtime` parameter.

Hope it help!

Lion

**Comment by SCEDC** [comment]
Thanks, Lion. I will take a look. 

Aparna

**Comment by SCEDC** [comment]
I was able to fix the last issue I had, thanks to Lion's input. I have another question. I want to add an extra request parameter to the waveform webservice call, called zerofilloff. I am creating a dictionary kwargs = {'zerofilloff':'true'} and passing it on to get_waveforms(net, sta, location, seedchan, t1, t2, **kwargs). And I get : 

>>> st = client.get_waveforms("CI", "ISA", '**', "LHE", t1, t2,**kwargs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aparnab/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-linux-x86_64.egg/obspy/fdsn/client.py", line 592, in get_waveforms
    "dataselect", DEFAULT_PARAMETERS['dataselect'], kwargs)
  File "/home/aparnab/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-linux-x86_64.egg/obspy/fdsn/client.py", line 1018, in _create_url_from_parameters
    raise TypeError(msg)
TypeError: The parameter 'zerofilloff' is not supported by the service.

When I test the parameter via the browser, it works fine. I am able to get miniseed data back and plot it. Please advice.

regards,
Aparna

**Comment by QuLogic** [comment]
You need to add the definition of `zerofilloff` in your WADL as well.

**Comment by SCEDC** [comment]
It's in the wadl already. http://service.scedc.caltech.edu/fdsnws/dataselect/1/application.wadl

regards,
Aparna

**Comment by krischer** [comment]
This works fine for me:

```python
>>> c.get_waveforms("CI", "ISA", '', "LHE", obspy.UTCDateTime(2013, 1, 1), obspy.UTCDateTime(2013, 1, 1, 1, 1), zerofilloff='true')
```

I guess you did not restart Python? The wadl files are cached and will only be downloaded once per Python run.

**Comment by krischer** [comment]
In the wadl files you can (and should probably) also specify the types of the parameters which is especially important for non-standard parameters. Otherwise ObsPy assumes they take strings as parameters which might result in misformed queries.

Instead of

```xml
<param name="zerofilloff" style="query"/>
```
best use something like the following in the wadl files. Also not that you can specify the default value and some documentation which will help users to figure out how your service works.

```xml
<param name="zerofilloff" style="query" type="xs:boolean" default="false">
    <doc xml:lang="english" title="Description of the parameter"/>
</param>
```

**Comment by SCEDC** [comment]
Cool! Thanks a lot, Lion. I had not restarted python. And I will add the type for the request parameters and documentation to the wadl.
